---
permalink: switch-cisco-3232c/cn1610-migrate-to-3232c-overview.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Cisco Nexus 3232cスイッチを設定する前に、プロセスの概要と命名法を確認してください。 
---
= 移行の要件
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232Cスイッチは、AFF またはFAS クラスタのクラスタスイッチとして使用できます。クラスタスイッチでは、3つ以上のノードでONTAP クラスタを構築できます。


NOTE: 手順 では、 ONTAP コマンドと Cisco Nexus 3000 シリーズスイッチコマンドの両方を使用する必要があります。特に明記されていないかぎり、 ONTAP コマンドを使用します。

必要に応じて、詳細については次を参照してください。

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 および CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco イーサネットスイッチ"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== CN1610の移行要件

クラスタスイッチは、次のノード接続をサポートします。

* NetApp CN1610 ：ポート 0/1~0/12 （ 10GbE ）
* Cisco Nexus 3232C ：ポート e1/1~30 （ 40 または 100 、または 4x10GbE ）


クラスタスイッチは、次のスイッチ間リンク（ ISL ）ポートを使用します。

* NetApp CN1610 ：ポート 0/13~0/16 （ 10GbE ）
* Cisco Nexus 3232C ：ポート 1/31-32 （ 100GbE ）


[NOTE]
====
Cisco Nexus 3232C クラスタスイッチで 10G ブレークアウトケーブルを 4 本使用する必要があります。

====
次の表に、ネットアップ CN1610 スイッチから Cisco Nexus 3232C クラスタスイッチへの移行時に各段階で必要となるケーブル接続を示します。

|===
| 段階 | 説明 | 必要なケーブル 


 a| 
初期
 a| 
CN1610 から CN1610 （ SFP+ から SFP+ ）
 a| 
SFP+ 光ファイバケーブルまたは銅線直接接続ケーブル 4 本



 a| 
移行
 a| 
CN1610 から 3232C （ QSFP から SFP+ ）
 a| 
QSFP ケーブル × 1 、 SFP+ 光ファイバケーブル × 4 、銅線ブレークアウトケーブル × 4



 a| 
最後に
 a| 
3232C から 3232C （ QSFP から QSFP ）
 a| 
QSFP 光ファイバケーブルまたは銅線直接接続ケーブル × 2

|===
該当する参照構成ファイル (RCF) をダウンロードしておく必要があります。  10 GbEおよび40/100 GbEポートの数は、以下のRCFで定義されています。link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco ® Cluster Network Switch Reference Configuration File Download （ Cisco ® クラスタネットワークスイッチリファレンス構成ファイルのダウンロード"^] 。

この手順でサポートされているONTAPおよびNX-OSのバージョンは、次のとおりです。link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco イーサネットスイッチ"^] 。

この手順でサポートされているONTAPおよびFASTPATHのバージョンは、次のとおりです。link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 / CN1610 スイッチ"^] 。

.使用例について
移行手順の例では、4つのノードを使用します。

* 2つのノードで4つの10GbEクラスタインターコネクトポート（* e0a *、* e0b *、* e0c *、* e0d *）を使用します。
* 他の2つのノードは、* e4a *および* e4e *という2本の40GbEクラスタインターコネクトファイバケーブルを使用します。
+
にはlink:https://hwu.netapp.com/["_ Hardware Universe _"^]、プラットフォームのクラスタファイバケーブルに関する情報が記載されています。



この手順の例では、スイッチとノードで次の命名法を使用しています。

* ノードは* n1 *、* n2 *、* n3 *、および* n4 *です。
* コマンド出力は、 ONTAP ソフトウェアのリリースによって異なる場合があります。
* 交換するCN1610スイッチは* CL1 *および* CL2 *です。
* CN1610スイッチに代わるNexus 3232Cスイッチは、* c1 *および* c2 *です。
* * n1_clus1 *は、ノード* n1 *のクラスタスイッチ1（CL1またはC1）に接続された最初のクラスタ論理インターフェイス（LIF）です。
* * n1_clus2 *は、ノード* n1 *のクラスタスイッチ2（CL2またはC2）に接続された最初のクラスタLIFです。
* * n1_clus3 *は、ノード* n1 *のクラスタスイッチ2（CL2またはC2）に接続されている2番目のLIFです。
* * n1_clus4 *は、ノード* n1 *のクラスタスイッチ1（CL1またはC1）に接続されている2番目のLIFです。
* 10 GbEおよび40/100 GbEポートの数は、次のURLで入手可能なリファレンス構成ファイル（RCF）で定義されています。link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco ® Cluster Network Switch Reference Configuration File Download （ Cisco ® クラスタネットワークスイッチリファレンス構成ファイルのダウンロード"^] 。


.次の手順
link:cn1610-prepare-to-migrate.html["移行を準備"]です。
