---
permalink: switch-cisco-3232c/cn5596-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Cisco Nexus 3232cスイッチを設定する前に、プロセスの概要と命名法を確認してください。 
---
= 移行の要件
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232Cスイッチは、AFF またはFAS クラスタのクラスタスイッチとして使用できます。クラスタスイッチでは、3つ以上のノードでONTAP クラスタを構築できます。

[NOTE]
====
手順 では、 ONTAP コマンドと Cisco Nexus 3000 シリーズスイッチコマンドの両方を使用する必要があります。特に明記されていないかぎり、 ONTAP コマンドを使用します。

====
詳細については、を参照してください

* http://support.netapp.com/NOW/download/software/cm_switches/["Cisco Ethernet Switch 概要 ページ"^]
* http://hwu.netapp.com["Hardware Universe"^]




== Cisco Nexus 5596の要件

クラスタスイッチは、ノードへの接続に次のポートを使用します。

* Nexus 5596：ポートe1/1~40（10GbE）
* Nexus 3232C：ポートe1/1~30（10/40 / 100GbE）


クラスタスイッチは、次のスイッチ間リンク（ ISL ）ポートを使用します。

* Nexus 5596：ポートe1/41~48（10GbE）
* Nexus 3232C：ポートe1/31~32（40 / 100GbE）


。 link:https://hwu.netapp.com/["_ Hardware Universe _"^] Nexus 3232C スイッチでサポートされているケーブル接続の詳細については、次の URL を参照

* 10GbE クラスタ接続のノードには、 QSFP-SFP+ 光ファイバブレークアウトケーブルまたは QSFP+ 銅線ブレークアウトケーブルが必要です。
* 40 / 100GbE クラスタ接続に対応した QSFP / QSFP28 光モジュールには、ファイバケーブルまたは QSFP / QSFP28 銅線直接接続ケーブルが必要です。


クラスタスイッチは、適切な ISL ケーブル接続を使用します。

* 導入： Nexus 5596 （ SFP+ から SFP+ ）
+
** SFP+ ファイバケーブルまたは銅線直接接続ケーブル × 8


* 中間： Nexus 5596 から Nexus 3232C （ QSFP から 4xSFP+ へのブレークアウト）
+
** QSFP / SFP+ ファイバブレークアウトケーブルまたは銅線ブレークアウトケーブル × 1


* 最終： Nexus 3232C から Nexus 3232C （ QSFP28 から QSFP28 ）
+
** QSFP28 ファイバケーブルまたは銅線直接接続ケーブル × 2


* Nexus 3232C スイッチでは、 40/100 ギガビットイーサネットモードまたは 4 × 10 ギガビットイーサネットモードのいずれかで QSFP/QSFP28 ポートを動作させることができます。
+
デフォルトでは、 40/100 ギガビットイーサネットモードには 32 個のポートがあります。これらの 40 ギガビットイーサネットポートには、 2 タプルの命名規則で番号が付けられます。たとえば、 2 番目の 40 ギガビットイーサネットポートには、 1/2 という番号が付けられます。

+
設定を 40 ギガビットイーサネットから 10 ギガビットイーサネットに変更するプロセスは _ ブレークアウト _ と呼ばれ、設定を 10 ギガビットイーサネットから 40 ギガビットイーサネットに変更するプロセスは _ ブレークイン _ と呼ばれます。

+
40/100 ギガビットイーサネットポートを 10 ギガビットイーサネットポートに分割すると、 3 タプルの命名規則に従ってポート番号が付けられます。たとえば、 2 番目の 40/100 ギガビットイーサネットポートのブレークアウトポートには、 1/2/1 、 1/2/2 、 1/2/3 、および 1/2/4 の番号が付けられます。

* Nexus 3232C スイッチの左側には、 1/33 および 1/34 という 2 つの SFP+ ポートがあります。
* Nexus 3232C スイッチの一部のポートを 10GbE または 40/100GbE で実行するように設定しておきます。
+
[NOTE]
====
最初の 6 つのポートを 4x10 GbE モードに分割するには、「 interface breakout module 1 port 1-6 map 10g-4x 」コマンドを使用します。同様に、 no interface breakout module 1 port 1-6 map 10g-4x コマンドを使用して、ブレークアウト構成から最初の 6 つの QSFP+ ポートをグループ化し直すことができます。

====
* ノードから Nexus 3232C クラスタスイッチへの 10GbE および 40/100GbE 接続に関する必要なドキュメントの計画、移行、および確認が完了している。
* この手順 でサポートされている ONTAP と NX-OS のバージョンはにあります link:http://support.netapp.com/NOW/download/software/cm_switches/.html["Cisco Ethernet Switches のページ"^]。


.使用例について
この手順 の例では、 Cisco Nexus 5596 スイッチを Cisco Nexus 3232C スイッチに交換する方法について説明します。この手順は、他の古い Cisco スイッチ（ 3132Q-V など）で（変更を伴う）使用できます。

手順 では、スイッチとノードで次の命名法も使用されています。

* コマンド出力は、 ONTAP のリリースによって異なる場合があります。
* 交換するNexus 5596スイッチは、* CL1 *および* CL2 *です。
* Nexus 5596スイッチに代わるNexus 3232Cスイッチは、* c1 *および* c2 *です。
* * n1_clus1 *は、ノード* n1 *のクラスタスイッチ1（CL1またはC1）に接続された最初のクラスタ論理インターフェイス（LIF）です。
* * n1_clus2 *は、ノード* n1 *のクラスタスイッチ2（CL2またはC2）に接続された最初のクラスタLIFです。
* * n1_clus3 *は、ノード* n1 *のクラスタスイッチ2（CL2またはC2）に接続されている2番目のLIFです。
* * n1_clus4 *は、ノード* n1 *のクラスタスイッチ1（CL1またはC1）に接続されている2番目のLIFです。
* 10GbE ポートと 40 / 100GbE ポートの数は、で使用可能なリファレンス構成ファイル（ RCF ）に定義されています https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® Cluster Network Switch Reference Configuration File Download （ Cisco ® クラスタネットワークスイッチリファレンス構成ファイルのダウンロード"^] ページ
* ノードは* n1 *、* n2 *、* n3 *、および* n4 *です。


この手順 の例では、4つのノードを使用しています。

* 2つのノードで4つの10GbEクラスタインターコネクトポート（* e0a *、* e0b *、* e0c *、* e0d *）を使用します。
* 他の2つのノードは、* e4a *と* e4e *の2つの40GbEクラスタインターコネクトポートを使用します。
+
にはlink:https://hwu.netapp.com/["_ Hardware Universe _"^]、プラットフォームの実際のクラスタポートが表示されます。



.対象となるシナリオ
この手順 では、次のシナリオについて説明します。

* クラスタは、 2 つの Nexus 5596 クラスタスイッチで接続され、機能している 2 つのノードから始まります。
* c2 で交換するクラスタスイッチ CL2 （手順 1~19 ）
+
** CL2 に接続されているすべてのノードのすべてのクラスタポートと LIF のトラフィックを最初のクラスタポートに移行し、 CL1 に接続されている LIF を移行します。
** CL2 に接続されているすべてのノードのすべてのクラスタポートからケーブルを外し、サポートされているブレークアウトケーブルを使用してポートを新しいクラスタスイッチ C2 に再接続します。
** CL1 と CL2 間の ISL ポート間のケーブルを外し、サポートされているブレークアウトケーブルを使用して CL1 から C2 にポートを再接続します。
** すべてのノードの C2 に接続されているすべてのクラスタポートと LIF のトラフィックがリバートされます。


* c2で交換するクラスタスイッチCL2。
+
** CL1 に接続されているすべてのノードのすべてのクラスタポートまたは LIF のトラフィックが、 C2 に接続されている 2 つ目のクラスタポートまたは LIF に移行されます。
** CL1 に接続されているすべてのノードのすべてのクラスタポートからケーブルを外し、サポートされているブレークアウトケーブルを使用して新しいクラスタスイッチ C1 に再接続します。
** CL1 と C2 の間の ISL ポート間のケーブル接続を解除し、サポートされているケーブル接続を使用して C1 から C2 に再接続します。
** すべてのノードの C1 に接続されているすべてのクラスタポートまたは LIF のトラフィックがリバートされます。


* クラスタの詳細を示す例で、2つのFAS9000ノードがクラスタに追加されました。


.次の手順
link:cn5596-prepare-to-migrate.html["移行を準備"]です。
