---
permalink: switch-cisco-3232c/cn5596-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Cisco Nexus 3232c スイッチを構成する前に、プロセスと命名法の概要を確認してください。 
---
= 移行要件
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C スイッチは、 AFFまたはFASクラスタ内のクラスタ スイッチとして使用できます。クラスタ スイッチを使用すると、2 つ以上のノードを持つONTAPクラスタを構築できます。

[NOTE]
====
この手順では、ONTAPコマンドとCisco Nexus 3000シリーズ スイッチ コマンドの両方を使用する必要があります。特に明記されていないかぎり、ONTAPコマンドを使用します。

====
詳細については、以下を参照してください。

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== Cisco Nexus 5596の要件

クラスタ スイッチは、ノードへの接続に次のポートを使用します。

* Nexus 5596: ポート e1/1-40 (10 GbE)
* Nexus 3232C: ポート e1/1-30 (10/40/100 GbE)


クラスタ スイッチは、次のスイッチ間リンク（ISL）ポートを使用します。

* Nexus 5596: ポート e1/41-48 (10 GbE)
* Nexus 3232C: ポート e1/31-32 (40/100 GbE)


そのlink:https://hwu.netapp.com/["_ハードウェアユニバース_"^]Nexus 3232C スイッチへのサポートされているケーブル接続に関する情報が含まれています。

* 10 GbE クラスタ接続を持つノードには、QSFP から SFP+ への光ファイバー ブレークアウト ケーブルまたは QSFP から SFP+ への銅線ブレークアウト ケーブルが必要です。
* 40/100 GbE クラスター接続を持つノードには、ファイバー ケーブルまたは QSFP/QSFP28 銅線直接接続ケーブルを備えたサポートされている QSFP/QSFP28 光モジュールが必要です。


クラスタ スイッチは適切な ISL ケーブルを使用します。

* 開始: Nexus 5596 (SFP+ から SFP+)
+
** 8本のSFP+ファイバーまたは銅線直接接続ケーブル


* 暫定: Nexus 5596 から Nexus 3232C (QSFP から 4xSFP+ ブレークアウト)
+
** 1本のQSFPからSFP+へのファイバーブレイクアウトケーブルまたは銅線ブレイクアウトケーブル


* 最終: Nexus 3232C から Nexus 3232C (QSFP28 から QSFP28)
+
** 2本のQSFP28光ファイバーまたは銅線直接接続ケーブル


* Nexus 3232C スイッチでは、QSFP/QSFP28 ポートを 40/100 ギガビット イーサネット モードまたは 4 x10 ギガビット イーサネット モードのいずれかで動作させることができます。
+
デフォルトでは、40/100 ギガビット イーサネット モードには 32 個のポートがあります。これらの 40 ギガビット イーサネット ポートには、2 タプルの命名規則に従って番号が付けられます。たとえば、2 番目の 40 ギガビット イーサネット ポートの番号は 1/2 になります。

+
40 ギガビット イーサネットから 10 ギガビット イーサネットに構成を変更するプロセスは _ブレイクアウト_ と呼ばれ、10 ギガビット イーサネットから 40 ギガビット イーサネットに構成を変更するプロセスは _ブレイクイン_ と呼ばれます。

+
40/100 ギガビット イーサネット ポートを 10 ギガビット イーサネット ポートに分割すると、結果のポートは 3 タプルの命名規則を使用して番号が付けられます。たとえば、2 番目の 40/100 ギガビット イーサネット ポートのブレークアウト ポートには、1/2/1、1/2/2、1/2/3、1/2/4 という番号が付けられます。

* Nexus 3232C スイッチの左側には、1/33 と 1/34 と呼ばれる 2 つの SFP+ ポートがあります。
* Nexus 3232C スイッチの一部のポートを 10 GbE または 40/100 GbE で実行するように設定しました。
+
[NOTE]
====
最初の6つのポートを4x10 GbEモードにするには、 `interface breakout module 1 port 1-6 map 10g-4x`指示。同様に、最初の6つのQSFP+ポートをブレイクアウト構成から再グループ化するには、 `no interface breakout module 1 port 1-6 map 10g-4x`指示。

====
* ノードから Nexus 3232C クラスタ スイッチへの 10 GbE および 40/100 GbE 接続の計画と移行が完了し、必要なドキュメントを読みました。
* この手順でサポートされているONTAPおよびNX-OSのバージョンは次のとおりです。link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^] 。


.使用された例について
この手順の例では、 Cisco Nexus 5596 スイッチをCisco Nexus 3232C スイッチに置き換える方法について説明します。これらの手順は、他の古いCiscoスイッチ (3132Q-V など) でも使用できます (変更を加える必要があります)。

この手順では、次のスイッチとノードの命名法も使用します。

* コマンド出力は、ONTAPのリリースによって異なる場合があります。
* 交換する Nexus 5596 スイッチは *CL1* と *CL2* です。
* Nexus 5596 スイッチを置き換える Nexus 3232C スイッチは *C1* と *C2* です。
* *n1_clus1* は、ノード *n1* のクラスタ スイッチ 1 (CL1 または C1) に接続された最初のクラスタ論理インターフェイス (LIF) です。
* *n1_clus2* は、ノード *n1* のクラスタ スイッチ 2 (CL2 または C2) に接続された最初のクラスタ LIF です。
* *n1_clus3* は、ノード *n1* のクラスタ スイッチ 2 (CL2 または C2) に接続された 2 番目の LIF です。
* *n1_clus4* は、ノード *n1* のクラスタ スイッチ 1 (CL1 または C1) に接続された 2 番目の LIF です。
* 10 GbEおよび40/100 GbEポートの数は、link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® クラスタ ネットワーク スイッチ リファレンス コンフィギュレーション ファイルのダウンロード"^] 。
* ノードは *n1*、*n2*、*n3*、*n4* です。


この手順の例では、次の 4 つのノードを使用します。

* 2 つのノードは、4 つの 10 GbE クラスター相互接続ポート *e0a*、*e0b*、*e0c*、および *e0d* を使用します。
* 他の 2 つのノードは、2 つの 40 GbE クラスター相互接続ポート *e4a* と *e4e* を使用します。
+
そのlink:https://hwu.netapp.com/["_ハードウェアユニバース_"^]プラットフォーム上の実際のクラスター ポートを一覧表示します。



.対象となるシナリオ
この手順では、次のシナリオについて説明します。

* クラスタは、2 つの Nexus 5596 クラスタ スイッチで接続され機能している 2 つのノードから開始されます。
* クラスタ スイッチ CL2 を C2 に置き換えます (手順 1 ～ 19):
+
** CL2 に接続されているすべてのノード上のすべてのクラスタ ポートと LIF 上のトラフィックは、CL1 に接続されている最初のクラスタ ポートと LIF に移行されます。
** CL2 に接続されているすべてのノードのすべてのクラスタ ポートからケーブルを外し、サポートされているブレークアウト ケーブルを使用してポートを新しいクラスタ スイッチ C2 に再接続します。
** CL1 と CL2 間の ISL ポート間のケーブルを外し、サポートされているブレークアウト ケーブルを使用してポートを CL1 から C2 に再接続します。
** すべてのノードの C2 に接続されているすべてのクラスタ ポートと LIF 上のトラフィックが元に戻されます。


* クラスタ スイッチ CL2 を C2 に置き換えます。
+
** CL1 に接続されているすべてのノードのすべてのクラスタ ポートまたは LIF 上のトラフィックは、C2 に接続されている 2 番目のクラスタ ポートまたは LIF に移行されます。
** CL1 に接続されているすべてのノードのすべてのクラスター ポートからケーブルを外し、サポートされているブレークアウト ケーブルを使用して新しいクラスター スイッチ C1 に再接続します。
** CL1 と C2 間の ISL ポート間のケーブルを外し、サポートされているケーブルを使用して C1 から C2 に再接続します。
** すべてのノードの C1 に接続されているすべてのクラスタ ポートまたは LIF 上のトラフィックが元に戻されます。


* 2 つのFAS9000ノードがクラスターに追加され、クラスターの詳細を示す例が表示されます。


.次の手順
link:cn5596-prepare-to-migrate.html["移行の準備"]。
