---
permalink: switch-cisco-3232c/concept-migrate-a-cn1610-switch-to-a-cisco-nexus-3232c-cluster-switch.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: CN1610 クラスタスイッチを Cisco Nexus 3232C クラスタスイッチに交換する場合は、特定の設定情報、ポート接続、およびケーブル接続要件に注意する必要があります。 
---
= CN1610 スイッチを Cisco Nexus 3232C クラスタスイッチに移行する
:icons: font
:imagesdir: ../media/


[role="lead"]
CN1610 クラスタスイッチを Cisco Nexus 3232C クラスタスイッチに交換する場合は、特定の設定情報、ポート接続、およびケーブル接続要件に注意する必要があります。

クラスタスイッチは、次のノード接続をサポートします。

* NetApp CN1610 ：ポート 0/1~0/12 （ 10GbE ）
* Cisco Nexus 3232C ：ポート e1/1~30 （ 40 または 100 、または 4x10GbE ）


クラスタスイッチは、次のスイッチ間リンク（ ISL ）ポートを使用します。

* NetApp CN1610 ：ポート 0/13~0/16 （ 10GbE ）
* Cisco Nexus 3232C ：ポート 1/31-32 （ 100GbE ）


[NOTE]
====
Cisco Nexus 3232C クラスタスイッチで 10G ブレークアウトケーブルを 4 本使用する必要があります。

====
次の表に、ネットアップ CN1610 スイッチから Cisco Nexus 3232C クラスタスイッチへの移行時に各段階で必要となるケーブル接続を示します。

|===
| 段階 | 説明 | 必要なケーブル 


 a| 
初期
 a| 
CN1610 から CN1610 （ SFP+ から SFP+ ）
 a| 
SFP+ 光ファイバケーブルまたは銅線直接接続ケーブル 4 本



 a| 
移行
 a| 
CN1610 から 3232C （ QSFP から SFP+ ）
 a| 
QSFP ケーブル × 1 、 SFP+ 光ファイバケーブル × 4 、銅線ブレークアウトケーブル × 4



 a| 
最後に
 a| 
3232C から 3232C （ QSFP から QSFP ）
 a| 
QSFP 光ファイバケーブルまたは銅線直接接続ケーブル × 2

|===
該当するリファレンス構成ファイル（ RCF ）をダウンロードしておく必要があります。10GbE ポートと 40/100GbE ポートの数は、で使用可能な RCF に定義されています https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® Cluster Network Switch Reference Configuration File Download （ Cisco ® クラスタネットワークスイッチリファレンス構成ファイルのダウンロード"^] ページ

この手順 でサポートされている ONTAP および NX-OS のバージョンは、 [Cisco Ethernet Switches] ページにリストされています。

https://mysupport.netapp.com/NOW/download/software/cm_switches/["Cisco イーサネットスイッチ"^]

この手順 でサポートされている ONTAP および fastpath のバージョンは、 NetApp CN1601 および CN1610 スイッチのページに記載されています。

http://support.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 / CN1610 スイッチ"^]
