---
permalink: switch-cisco-3232c/concept-migrate-from-a-cisco-5596-switch-to-a-cisco-nexus-3232c.html 
sidebar: sidebar 
keywords: migrate, cisco nexus 5596 switch, 3232c 
summary: Cisco Nexus 5596 クラスタスイッチを Cisco Nexus 3232C クラスタスイッチに交換する場合は、特定の設定情報、ポート接続、およびケーブル接続要件に注意する必要があります。 
---
= Cisco Nexus 5596 スイッチを Cisco Nexus 3232C スイッチに移行する
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 5596 クラスタスイッチを Cisco Nexus 3232C クラスタスイッチに交換する場合は、特定の設定情報、ポート接続、およびケーブル接続要件に注意する必要があります。

* この手順 では、次のクラスタスイッチを例として使用します。
+
** Nexus 5596
** Nexus 3232C


* クラスタスイッチは、ノードへの接続に次のポートを使用します。
+
** ポート e1/1~40 （ 10GbE ）： Nexus 5596
** ポート e1/1~30 （ 10/40/100GbE ）： Nexus 3232C


* クラスタスイッチは、次のスイッチ間リンク（ ISL ）ポートを使用します。
+
** ポート e1/41~48 （ 10GbE ）： Nexus 5596
** ポート e1/31~32 （ 40/100GbE ）： Nexus 3232C


* Nexus3232C スイツチヘノサホオトサレルケエフルセツソクノシヨウホウ Hardware Universe
+
** 10GbE クラスタ接続のノードには、 QSFP-SFP+ 光ファイバブレークアウトケーブルまたは QSFP+ 銅線ブレークアウトケーブルが必要です。
** 40 / 100GbE クラスタ接続に対応した QSFP / QSFP28 光モジュールには、ファイバケーブルまたは QSFP / QSFP28 銅線直接接続ケーブルが必要です。


* クラスタスイッチは、適切な ISL ケーブル接続を使用します。
+
** 導入： Nexus 5596 （ SFP+ から SFP+ ）
+
*** SFP+ ファイバケーブルまたは銅線直接接続ケーブル × 8


** 中間： Nexus 5596 から Nexus 3232C （ QSFP から 4xSFP+ へのブレークアウト）
+
*** QSFP / SFP+ ファイバブレークアウトケーブルまたは銅線ブレークアウトケーブル × 1


** 最終： Nexus 3232C から Nexus 3232C （ QSFP28 から QSFP28 ）
+
*** QSFP28 ファイバケーブルまたは銅線直接接続ケーブル × 2




* Nexus 3232C スイッチでは、 40/100 ギガビットイーサネットモードまたは 4 × 10 ギガビットイーサネットモードのいずれかで QSFP/QSFP28 ポートを動作させることができます。
+
デフォルトでは、 40/100 ギガビットイーサネットモードには 32 個のポートがあります。これらの 40 ギガビットイーサネットポートには、 2 タプルの命名規則で番号が付けられます。たとえば、 2 番目の 40 ギガビットイーサネットポートには、 1/2 という番号が付けられます。設定を 40 ギガビットイーサネットから 10 ギガビットイーサネットに変更するプロセスは _ ブレークアウト _ と呼ばれ、設定を 10 ギガビットイーサネットから 40 ギガビットイーサネットに変更するプロセスは _ ブレークイン _ と呼ばれます。40/100 ギガビットイーサネットポートを 10 ギガビットイーサネットポートに分割すると、 3 タプルの命名規則に従ってポート番号が付けられます。たとえば、 2 番目の 40/100 ギガビットイーサネットポートのブレークアウトポートには、 1/2/1 、 1/2/2 、 1/2/3 、および 1/2/4 の番号が付けられます。

* Nexus 3232C スイッチの左側には、 1/33 および 1/34 という 2 つの SFP+ ポートがあります。
* Nexus 3232C スイッチの一部のポートを 10GbE または 40/100GbE で実行するように設定しておきます。
+
[NOTE]
====
最初の 6 つのポートを 4x10 GbE モードに分割するには、「 interface breakout module 1 port 1-6 map 10g-4x 」コマンドを使用します。同様に、 no interface breakout module 1 port 1-6 map 10g-4x コマンドを使用して、ブレークアウト構成から最初の 6 つの QSFP+ ポートをグループ化し直すことができます。

====
* ノードから Nexus 3232C クラスタスイッチへの 10GbE および 40/100GbE 接続に関する必要なドキュメントの計画、移行、および確認が完了している。
* この手順 でサポートされている ONTAP と NX-OS のバージョンはにあります link:http://support.netapp.com/NOW/download/software/cm_switches/.html["Cisco Ethernet Switches のページ"^]。

