---
permalink: switch-cisco-3232c/migrate-requirements-3232c.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: CN1610 クラスタ スイッチをCisco Nexus 3232C クラスタ スイッチに置き換える場合は、特定の構成情報、ポート接続、およびケーブル接続の要件に注意する必要があります。 
---
= Cisco Nexus 3232C クラスタ スイッチの移行要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C クラスタ スイッチに移行する前に、構成情報、ポート接続、およびケーブル接続の要件を確認してください。



== CN1610 移行要件

クラスター スイッチは次のノード接続をサポートします。

* NetApp CN1610: ポート 0/1 ～ 0/12 (10 GbE)
* Cisco Nexus 3232C: ポート e1/1-30 (40 または 100 または 4x10GbE)


クラスタ スイッチは、次のスイッチ間リンク (ISL) ポートを使用します。

* NetApp CN1610: ポート 0/13 ～ 0/16 (10 GbE)
* Cisco Nexus 3232C: ポート 1/31-32 (100GbE)


[NOTE]
====
Cisco Nexus 3232C クラスタ スイッチでは、4x10G ブレークアウト ケーブルを使用する必要があります。

====
次の表は、 NetApp CN1610 スイッチからCisco Nexus 3232C クラスタ スイッチに移行する際に各段階で必要なケーブル接続を示しています。

|===
| 段階 | 説明 | 必要なケーブル 


 a| 
初期
 a| 
CN1610からCN1610（SFP+からSFP+）
 a| 
4本のSFP+光ファイバーまたは銅線直接接続ケーブル



 a| 
移行
 a| 
CN1610から3232C（QSFPからSFP+）
 a| 
1本のQSFPと4本のSFP+光ファイバーまたは銅線ブレークアウトケーブル



 a| 
ファイナル
 a| 
3232C から 3232C (QSFP から QSFP)
 a| 
2本のQSFP光ファイバーまたは銅線直接接続ケーブル

|===
該当する参照構成ファイル (RCF) をダウンロードしておく必要があります。10 GbEおよび40/100 GbEポートの数は、利用可能なRCFで定義されています。link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® クラスタ ネットワーク スイッチ リファレンス コンフィギュレーション ファイルのダウンロード"^] 。

この手順でサポートされているONTAPおよびNX-OSのバージョンは、次のとおりです。link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^] 。

この手順でサポートされているONTAPおよびFASTPATHのバージョンは、次のとおりです。link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601およびCN1610スイッチ"^] 。



== CN5596の要件

クラスタ スイッチは、ノードへの接続に次のポートを使用します。

* ポート e1/1-40 (10 GbE): Nexus 5596
* ポート e1/1-30 (10/40/100 GbE): Nexus 3232C
+
** クラスタ スイッチは、次のスイッチ間リンク（ISL）ポートを使用します。


* ポート e1/41-48 (10 GbE): Nexus 5596
* ポート e1/31-32 (40/100 GbE): Nexus 3232C
+
** そのlink:https://hwu.netapp.com/["_ハードウェアユニバース_"^]Nexus 3232C スイッチへのサポートされているケーブル接続に関する情報が含まれています。


* 10 GbE クラスタ接続を持つノードには、QSFP から SFP+ への光ファイバー ブレークアウト ケーブルまたは QSFP から SFP+ への銅線ブレークアウト ケーブルが必要です。
* 40/100 GbE クラスター接続を備えたノードには、ファイバー ケーブルまたは QSFP/QSFP28 銅線直接接続ケーブルを備えたサポートされている QSFP/QSFP28 光モジュールが必要です。
+
** クラスタ スイッチは適切な ISL ケーブルを使用します。


* 開始: Nexus 5596 (SFP+ から SFP+)
+
** 8本のSFP+ファイバーまたは銅線直接接続ケーブル


* 暫定: Nexus 5596 から Nexus 3232C (QSFP から 4xSFP+ ブレークアウト)
+
** 1本のQSFPからSFP+へのファイバーブレイクアウトケーブルまたは銅線ブレイクアウトケーブル


* 最終: Nexus 3232C から Nexus 3232C (QSFP28 から QSFP28)
+
** 2本のQSFP28光ファイバーまたは銅線直接接続ケーブル
+
*** Nexus 3232C スイッチでは、QSFP/QSFP28 ポートを 40/100 ギガビット イーサネット モードまたは 4 x10 ギガビット イーサネット モードのいずれかで動作させることができます。
+
デフォルトでは、40/100 ギガビット イーサネット モードには 32 個のポートがあります。これらの 40 ギガビット イーサネット ポートには、2 タプルの命名規則に従って番号が付けられます。たとえば、2 番目の 40 ギガビット イーサネット ポートの番号は 1/2 になります。  40 ギガビット イーサネットから 10 ギガビット イーサネットに構成を変更するプロセスは _ブレイクアウト_ と呼ばれ、10 ギガビット イーサネットから 40 ギガビット イーサネットに構成を変更するプロセスは _ブレイクイン_ と呼ばれます。 40/100 ギガビット イーサネット ポートを 10 ギガビット イーサネット ポートに分割すると、結果のポートは 3 タプルの命名規則を使用して番号が付けられます。たとえば、2 番目の 40/100 ギガビット イーサネット ポートのブレークアウト ポートには、1/2/1、1/2/2、1/2/3、1/2/4 という番号が付けられます。

*** Nexus 3232C スイッチの左側には、1/33 と 1/34 と呼ばれる 2 つの SFP+ ポートがあります。
*** Nexus 3232C スイッチの一部のポートを 10 GbE または 40/100 GbE で動作するように設定しました。
+
[NOTE]
====
最初の6つのポートを4x10 GbEモードにするには、 `interface breakout module 1 port 1-6 map 10g-4x`指示。同様に、最初の6つのQSFP+ポートをブレイクアウト構成から再グループ化するには、 `no interface breakout module 1 port 1-6 map 10g-4x`指示。

====
*** ノードから Nexus 3232C クラスタ スイッチへの 10 GbE および 40/100 GbE 接続の計画と移行が完了し、必要なドキュメントを読みました。
*** この手順でサポートされているONTAPおよびNX-OSのバージョンは次のとおりです。link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^] 。





