---
permalink: switch-cisco-3232c/migrate-from-switchless-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Cisco Nexus 3232cスイッチを設定する前に、プロセスの概要と命名法を確認してください。 
---
= 移行の要件
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
2ノードスイッチレスクラスタの場合は、Cisco Nexus 3232Cクラスタネットワークスイッチを含む2ノードスイッチクラスタに移行できます。この手順は無停止で実行されます。

.作業を開始する前に
次のインストールと接続を確認します。

* ポートはノード接続に使用できます。クラスタスイッチは、 Inter-Switch Link （ ISL ；スイッチ間リンク）ポート e1/31~32 を使用します。
* クラスタ接続用の適切なケーブルを用意しておきます。
+
** 10GbE クラスタ接続のノードには、ブレークアウト光ケーブルまたは QSFP / SFP+ 銅線ブレークアウトケーブルを備えた QSFP 光モジュールが必要です。
** 40/100GbE クラスタ接続が確立されているノードには、サポートされている QSFP/QSFP28 光モジュール（ファイバケーブルまたは QSFP/QSFP28 銅線直接接続ケーブル）が必要です。
** クラスタスイッチでは、適切なISLケーブル接続が必要です。
+
*** QSFP28ファイバケーブルまたは銅線直接接続ケーブル×2。




* 構成が適切にセットアップされ、機能している。
+
2 ノードスイッチレスクラスタの設定で 2 ノードが接続され、機能している必要があります。

* すべてのクラスタポートが「稼働」状態です。
* Cisco Nexus 3232Cクラスタスイッチがサポートされます。
* 既存のクラスタネットワーク構成には次のものがあります。
+
** 両方のスイッチの冗長で完全に機能している Nexus 3232C クラスタインフラ
** スイッチにインストールされている最新の RCF および NX-OS バージョン
** 両方のスイッチで管理接続を使用します
** 両方のスイッチへのコンソールアクセス
** 移行されていない、すべてのクラスタ論理インターフェイス（LIF）の状態が「up」になっている必要があります
** スイッチの初期カスタマイズ
** すべての ISL ポートが有効でケーブル接続されている




.使用例について
この手順の例では、スイッチとノードで次の命名法を使用しています。

* Nexus 3232Cクラスタスイッチ、* C1 *および* C2 *。
* ノードは* n1 *および* n2 *です。


この手順の例では、2つのノードを使用し、それぞれに2つの40GbEクラスタインターコネクトポート* e4a *と* e4e *を使用します。にlink:https://hwu.netapp.com/["_ Hardware Universe _"^]は、プラットフォームのクラスタポートに関する詳細が記載されています。

* * n1_clus1 *は、ノード* n1 *のクラスタスイッチ* c1 *に接続される最初のクラスタ論理インターフェイス（LIF）です。
* * n1_clus2 *は、ノード* n1 *のクラスタスイッチ* c2 *に接続される最初のクラスタLIFです。
* * n2_clus1 *は、ノード* n2 *のクラスタスイッチ* c1 *に接続される最初のクラスタLIFです。
* * n2_clus2 *は、ノード* n2 *のクラスタスイッチ* c2 *に接続する2番目のクラスタLIFです。
* 10GbE ポートと 40 / 100GbE ポートの数は、で使用可能なリファレンス構成ファイル（ RCF ）に定義されています https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® Cluster Network Switch Reference Configuration File Download （ Cisco ® クラスタネットワークスイッチリファレンス構成ファイルのダウンロード"^] ページ


[NOTE]
====
手順 では、 ONTAP コマンドと Cisco Nexus 3000 シリーズスイッチコマンドの両方を使用する必要があります。特に明記されていないかぎり、 ONTAP コマンドを使用します。

====
.次の手順
link:migrate-from-switchless-prepare-to-migrate.html["移行を準備"]です。
