---
permalink: switch-cisco-3232c/migrate-from-cisco-nexus-5596.html 
sidebar: sidebar 
keywords: migrate, cisco nexus 5596 switch, 3232c 
summary: クラスタ内の既存のCisco Nexus 5596 クラスタ スイッチを Nexus 3232C クラスタ スイッチに置き換えるには、特定の一連のタスクを実行する必要があります。 
---
= Cisco Nexus 5596 クラスタ スイッチからCisco Nexus 3232C クラスタ スイッチへの移行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nexus 3232C クラスタ スイッチを含むクラスタ内の既存のCisco Nexus 5596 クラスタ スイッチを移行するには、次の手順に従ってください。



== 要件の確認

移行前に必ず確認してくださいlink:migrate-requirements-3232c.html["移行要件"]。

[NOTE]
====
この手順では、ONTAPコマンドとCisco Nexus 3000シリーズ スイッチ コマンドの両方を使用する必要があります。特に明記されていないかぎり、ONTAPコマンドを使用します。

====
詳細については、以下を参照してください。

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== スイッチを移行する

.例について
この手順の例では、 Cisco Nexus 5596 スイッチをCisco Nexus 3232C スイッチに置き換える方法について説明します。これらの手順は、他の古いCiscoスイッチ (3132Q-V など) でも使用できます (変更を加える必要があります)。

この手順では、次のスイッチとノードの命名法も使用します。

* コマンド出力は、ONTAPのリリースによって異なる場合があります。
* 交換する Nexus 5596 スイッチは CL1 と CL2 です。
* Nexus 5596 スイッチを置き換える Nexus 3232C スイッチは C1 と C2 です。
* n1_clus1 は、ノード n1 のクラスタ スイッチ 1 (CL1 または C1) に接続された最初のクラスタ論理インターフェイス (LIF) です。
* n1_clus2 は、ノード n1 のクラスタ スイッチ 2 (CL2 または C2) に接続された最初のクラスタ LIF です。
* n1_clus3 は、ノード n1 のクラスタ スイッチ 2 (CL2 または C2) に接続された 2 番目の LIF です。
* n1_clus4 は、ノード n1 のクラスタ スイッチ 1 (CL1 または C1) に接続された 2 番目の LIF です。
* 10 GbEおよび40/100 GbEポートの数は、次のURLで入手可能なリファレンス構成ファイル（RCF）で定義されています。link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® クラスタ ネットワーク スイッチ リファレンス コンフィギュレーション ファイルのダウンロード"^] 。
* ノードは n1、n2、n3、n4 です。


この手順の例では、次の 4 つのノードを使用します。

* 2 つのノードは、4 つの 10 GbE クラスター相互接続ポート (e0a、e0b、e0c、e0d) を使用します。
* 他の 2 つのノードは、2 つの 40 GbE クラスター相互接続ポート (e4a、e4e) を使用します。そのlink:https://hwu.netapp.com/["_ハードウェアユニバース_"^]プラットフォーム上の実際のクラスター ポートを一覧表示します。


.シナリオ
この手順では、次のシナリオについて説明します。

* クラスタは、2 つの Nexus 5596 クラスタ スイッチで接続され機能している 2 つのノードから開始されます。
* クラスタ スイッチ CL2 を C2 に置き換えます (手順 1 ～ 19):
+
** CL2 に接続されているすべてのノード上のすべてのクラスタ ポートと LIF 上のトラフィックは、CL1 に接続されている最初のクラスタ ポートと LIF に移行されます。
** CL2 に接続されているすべてのノードのすべてのクラスタ ポートからケーブルを外し、サポートされているブレークアウト ケーブルを使用してポートを新しいクラスタ スイッチ C2 に再接続します。
** CL1 と CL2 間の ISL ポート間のケーブルを外し、サポートされているブレークアウト ケーブルを使用してポートを CL1 から C2 に再接続します。
** すべてのノードの C2 に接続されているすべてのクラスタ ポートと LIF 上のトラフィックが元に戻されます。


* クラスタ スイッチ CL2 を C2 に置き換えます。
+
** CL1 に接続されているすべてのノードのすべてのクラスタ ポートまたは LIF 上のトラフィックは、C2 に接続されている 2 番目のクラスタ ポートまたは LIF に移行されます。
** CL1 に接続されているすべてのノードのすべてのクラスター ポートからケーブルを外し、サポートされているブレークアウト ケーブルを使用して新しいクラスター スイッチ C1 に再接続します。
** CL1 と C2 間の ISL ポート間のケーブルを外し、サポートされているケーブルを使用して C1 から C2 に再接続します。
** すべてのノードの C1 に接続されているすべてのクラスタ ポートまたは LIF 上のトラフィックが元に戻されます。


* 2 つのFAS9000ノードがクラスターに追加され、クラスターの詳細を示す例が表示されます。




=== ステップ1: 移行の準備

. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

+
[NOTE]
====
AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

====
. 構成内のデバイスに関する情報を表示します。
+
`network device-discovery show`

+
.例を表示
[%collapsible]
====
次の例は、各クラスタ相互接続スイッチの各ノードに設定されているクラスタ相互接続インターフェイスの数を示しています。

[listing, subs="+quotes"]
----
cluster::> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    CL1                 Ethernet1/1      N5K-C5596UP
            e0b    CL2                 Ethernet1/1      N5K-C5596UP
            e0c    CL2                 Ethernet1/2      N5K-C5596UP
            e0d    CL1                 Ethernet1/2      N5K-C5596UP
n2         /cdp
            e0a    CL1                 Ethernet1/3      N5K-C5596UP
            e0b    CL2                 Ethernet1/3      N5K-C5596UP
            e0c    CL2                 Ethernet1/4      N5K-C5596UP
            e0d    CL1                 Ethernet1/4      N5K-C5596UP
8 entries were displayed.
----
====
. 各クラスタ インターフェイスの管理ステータスまたは動作ステータスを決定します。
+
.. ネットワーク ポートの属性を表示します。
+
`network port show -role cluster`

+
.例を表示
[%collapsible]
====
次の例では、ノード n1 と n2 のネットワーク ポート属性を表示します。

[listing, subs="+quotes"]
----
cluster::*> *network port show –role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
.. 論理インターフェースに関する情報を表示します。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
次の例では、クラスタ上のすべての LIF に関する一般情報（現在のポートを含む）を表示します。

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
.. 検出されたクラスター スイッチに関する情報を表示します。
+
`system cluster-switch show`

+
.例を表示
[%collapsible]
====
次の例は、アクティブなクラスタ スイッチを示しています。

[listing, subs="+quotes"]
----
cluster::*> *system cluster-switch show*

Switch                        Type               Address         Model
----------------------------- ------------------ --------------- ---------------
CL1                           cluster-network    10.10.1.101     NX5596
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP
CL2                           cluster-network    10.10.1.102     NX5596
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP

2 entries were displayed.
----
====


. 要件に応じて適切な RCF とイメージが新しい 3232C スイッチにインストールされていることを確認し、ユーザーとパスワード、ネットワーク アドレス、その他のカスタマイズなど、サイトの重要なカスタマイズを行います。
+
[NOTE]
====
この時点で両方のスイッチを準備する必要があります。

====
+
RCF とイメージをアップグレードする必要がある場合は、次の手順を実行する必要があります。

+
.. NetAppサポート サイトの「Cisco Ethernet Switches」ページに移動します。
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^]

.. そのページの表で、スイッチと必要なソフトウェア バージョンを書き留めてください。
.. 適切なバージョンの RCF をダウンロードします。
.. *説明* ページで *続行* をクリックし、ライセンス契約に同意してから、*ダウンロード* ページの指示に従って RCF をダウンロードします。
.. 適切なバージョンのイメージ ソフトウェアをダウンロードします。
+
__ONTAP 8.x 以降のクラスタおよび管理ネットワーク スイッチのリファレンス構成ファイル__ のダウンロード ページを参照し、適切なバージョンをクリックします。

+
正しいバージョンを見つけるには、_ONTAP 8.x 以降の Cluster Network Switch のダウンロード ページ_ を参照してください。



. 交換する 2 番目の Nexus 5596 スイッチに関連付けられている LIF を移行します。
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ -source-node _source-node-name_ - destination-node _node-name_ -destination-port _destination-port-name_`

+
.例を表示
[%collapsible]
====
次の例は、ノード n1 および n2 の LIF が移行されることを示しています。LIF の移行はすべてのノードで実行する必要があります。

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1 -
destination-node n1 -destination-port e0a*
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus3 -source-node n1 -
destination-node n1 -destination-port e0d*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2 -
destination-node n2 -destination-port e0a*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus3 -source-node n2 -
destination-node n2 -destination-port e0d*
----
====
. クラスターの健全性を確認します。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
次の例は、各クラスターの現在のステータスを示しています。

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0a     false
            n1_clus3   up/up      10.10.0.3/24       n1            e0d     false
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0a     false
            n2_clus3   up/up      10.10.0.7/24       n2            e0d     false
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====




=== ステップ2: ポートを構成する

. スイッチ CL2 に物理的に接続されているクラスタ相互接続ポートをシャットダウンします。
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.例を表示
[%collapsible]
====
次のコマンドは、n1 および n2 上の指定されたポートをシャットダウンしますが、すべてのノード上のポートをシャットダウンする必要があります。

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin false*
cluster::*> *network port modify -node n1 -port e0c -up-admin false*
cluster::*> *network port modify -node n2 -port e0b -up-admin false*
cluster::*> *network port modify -node n2 -port e0c -up-admin false*
----
====
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 詳細を表示するには、show コマンドを実行する前に数秒待ってください。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[ステップ3]] アクティブNexus 5596スイッチCL1のISL41～48をCiscoを使用してシャットダウンします。 `shutdown`指示。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 シリーズ NX-OS コマンド リファレンス"^] 。

+
.例を表示
[%collapsible]
====
次の例は、Nexus 5596 スイッチ CL1 で ISL 41 ～ 48 がシャットダウンされていることを示しています。

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface e1/41-48*
(CL1)(config-if-range)# *shutdown*
(CL1)(config-if-range)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. 適切なCiscoコマンドを使用して、CL1 と C2 の間に一時的な ISL を構築します。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 シリーズ NX-OS コマンド リファレンス"^] 。

+
.例を表示
[%collapsible]
====
次の例は、CL1 と C2 の間に一時的な ISL が設定されていることを示しています。

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *interface port-channel 2*
C2(config-if)# *switchport mode trunk*
C2(config-if)# *spanning-tree port type network*
C2(config-if)# *mtu 9216*
C2(config-if)# *interface breakout module 1 port 24 map 10g-4x*
C2(config)# *interface e1/24/1-4*
C2(config-if-range)# *switchport mode trunk*
C2(config-if-range)# *mtu 9216*
C2(config-if-range)# *channel-group 2 mode active*
C2(config-if-range)# *exit*
C2(config-if)# *exit*
----
====
. すべてのノードで、Nexus 5596 スイッチ CL2 に接続されているすべてのケーブルを取り外します。
+
サポートされているケーブルを使用して、すべてのノード上の切断されたポートを Nexus 3232C スイッチ C2 に再接続します。

. Nexus 5596 スイッチ CL2 からすべてのケーブルを取り外します。
+
適切なCisco QSFP から SFP+ へのブレークアウト ケーブルを接続して、新しいCisco 3232C スイッチ (C2) のポート 1/24 を既存の Nexus 5596 (CL1) のポート 45 ～ 48 に接続します。

. アクティブ Nexus 5596 スイッチ CL1 の ISL ポート 45 ～ 48 を起動します。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 シリーズ NX-OS コマンド リファレンス"^] 。

+
.例を表示
[%collapsible]
====
次の例では、ISL ポート 45 ～ 48 が起動されています。

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface e1/45-48*
(CL1)(config-if-range)# *no shutdown*
(CL1)(config-if-range)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. ISLが `up`Nexus 5596 スイッチ CL1 上。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 シリーズ NX-OS コマンド リファレンス"^] 。

+
.例を表示
[%collapsible]
====
次の例では、ポートeth1/45からeth1/48が(P)を示しており、これはISLポートが `up`ポートチャネル内。

[listing, subs="+quotes"]
----
CL1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/41(D)   Eth1/42(D)   Eth1/43(D)
                                    Eth1/44(D)   Eth1/45(P)   Eth1/46(P)
                                    Eth1/47(P)   Eth1/48(P)
----
====
. インターフェイス eth1/45-48 の実行構成ですでに「channel-group 1 mode active」が設定されていることを確認します。
. すべてのノードで、3232C スイッチ C2 に接続されているすべてのクラスタ相互接続ポートを起動します。
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.例を表示
[%collapsible]
====
次の例は、指定されたポートがノード n1 および n2 で起動されることを示しています。

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin true*
cluster::*> *network port modify -node n1 -port e0c -up-admin true*
cluster::*> *network port modify -node n2 -port e0b -up-admin true*
cluster::*> *network port modify -node n2 -port e0c -up-admin true*
----
====
. すべてのノードで、C2 に接続されている移行されたすべてのクラスタ相互接続 LIF を元に戻します。
+
`network interface revert -vserver Cluster -lif _lif-name_`

+
.例を表示
[%collapsible]
====
次の例は、移行されたクラスタ LIF がホーム ポートに戻されることを示しています。

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver Cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n1_clus3*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus3*
----
====
. すべてのクラスタ相互接続ポートがホームに戻っていることを確認します。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
次の例では、clus2のLIFがホームポートに戻ったことを示し、現在のポート列のポートのステータスが `true`の中で `Is Home`カラム。もし `Is Home`価値は `false`LIF は元に戻されていません。

[listing]
----
cluster::*> *network interface show -role cluster*
(network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
. クラスター化されたポートが接続されていることを確認します。
+
`network port show -role cluster`

+
.例を表示
[%collapsible]
====
次の例は、前の例の結果を示しています。 `network port modify`コマンドを実行して、すべてのクラスタインターコネクトが `up`:

[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step15]] クラスタ内の各ノードで、交換する最初の Nexus 5596 スイッチ CL1 に関連付けられているインターフェイスを移行します。
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ -source-node _source-node-name_
-destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.例を表示
[%collapsible]
====
次の例は、ノード n1 および n2 で移行されるポートまたは LIF を示しています。

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus1 -source-node n1 -
destination-node n1 -destination-port e0b*
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus4 -source-node n1 -
destination-node n1 -destination-port e0c*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus1 -source-node n2 -
destination-node n2 -destination-port e0b*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus4 -source-node n2 -
destination-node n2 -destination-port e0c*
----
====
. クラスターのステータスを確認します。
+
`network interface show`

+
.例を表示
[%collapsible]
====
次の例は、必要なクラスタ LIF がクラスタ スイッチ C2 でホストされている適切なクラスタ ポートに移行されたことを示しています。

[listing, subs="+quotes"]
----
cluster::*> *network interface show*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0b     false
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0c     false
            n2_clus1   up/up      10.10.0.5/24       n2            e0b     false
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0c     false
8 entries were displayed.

----- ------- ----
----
====
. すべてのノードで、CL1 に接続されているノード ポートをシャットダウンします。
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.例を表示
[%collapsible]
====
次の例では、ノード n1 および n2 で指定されたポートがシャットダウンされています。

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0a -up-admin false*
cluster::*> *network port modify -node n1 -port e0d -up-admin false*
cluster::*> *network port modify -node n2 -port e0a -up-admin false*
cluster::*> *network port modify -node n2 -port e0d -up-admin false*
----
====
. アクティブ 3232C スイッチ C2 の ISL 24、31、および 32 をシャットダウンします。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 シリーズ NX-OS コマンド リファレンス"^] 。

+
.例を表示
[%collapsible]
====
次の例は、ISL がシャットダウンされていることを示しています。

[listing, subs="+quotes"]
----
C2# *configure*
C2(Config)# *interface e1/24/1-4*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config)# *interface 1/31-32*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config-if)# *exit*
C2#
----
====
. すべてのノードで、Nexus 5596 スイッチ CL1 に接続されているすべてのケーブルを取り外します。
+
サポートされているケーブルを使用して、すべてのノード上の切断されたポートを Nexus 3232C スイッチ C1 に再接続します。

. Nexus 3232C C2 ポート e1/24 から QSFP ブレークアウト ケーブルを取り外します。
+
サポートされているCisco QSFP 光ファイバ ケーブルまたは直接接続ケーブルを使用して、C1 のポート e1/31 および e1/32 を C2 のポート e1/31 および e1/32 に接続します。

. ポート 24 の設定を復元し、C2 の一時ポート チャネル 2 を削除します。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 シリーズ NX-OS コマンド リファレンス"^] 。

+
.例を表示
[%collapsible]
====
次の例は、適切なCiscoコマンドを使用してポート m24 の設定が復元される様子を示しています。

[listing, subs="+quotes"]
----
C2# configure
C2(config)# *no interface breakout module 1 port 24 map 10g-4x*
C2(config)# *no interface port-channel 2*
C2(config-if)# *int e1/24*
C2(config-if)# *description 40GbE Node Port*
C2(config-if)# *spanning-tree port type edge*
C2(config-if)# *spanning-tree bpduguard enable*
C2(config-if)# *mtu 9216*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. 次のCiscoコマンドを入力して、アクティブ 3232C スイッチ C2 の ISL ポート 31 と 32 を起動します。 `no shutdown`
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 シリーズ NX-OS コマンド リファレンス"^] 。

+
.例を表示
[%collapsible]
====
次の例はCiscoコマンドを示しています `switchname configure`3232CスイッチC2で起動:

[listing, subs="+quotes"]
----
C2# configure
C2(config)# interface ethernet 1/31-32
C2(config-if-range)# no shutdown
----
====
. ISL接続が `up`3232C スイッチ C2 で。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 シリーズ NX-OS コマンド リファレンス"^] 。

+
ポートeth1/31とeth1/32は（P）を示し、ポートチャネルの両方のISLポートがアップしていることを意味する。

+
.例を表示
[%collapsible]
====
[listing]
----

C1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. すべてのノードで、新しい 3232C スイッチ C1 に接続されているすべてのクラスタ相互接続ポートを起動します。
+
`network port modify`

+
.例を表示
[%collapsible]
====
次の例は、3232C スイッチ C1 上の n1 および n2 のすべてのクラスタ相互接続ポートが起動されていることを示しています。

[listing]
----

cluster::*> network port modify -node n1 -port e0a -up-admin true
cluster::*> network port modify -node n1 -port e0d -up-admin true
cluster::*> network port modify -node n2 -port e0a -up-admin true
cluster::*> network port modify -node n2 -port e0d -up-admin true
----
====
. クラスター ノード ポートのステータスを確認します。
+
`network port show`

+
.例を表示
[%collapsible]
====
次の例では、新しい 3232C スイッチ C1 上のすべてのノード上のすべてのクラスタ相互接続ポートが稼働していることを確認します。

[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
. すべてのノードで、特定のクラスタ LIF をホーム ポートに戻します。
+
`network interface revert -server Cluster -lif _lif-name_`

+
.例を表示
[%collapsible]
====
次の例は、特定のクラスタ LIF がノード n1 および n2 上のホーム ポートに戻されることを示しています。

[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus1
cluster::*> network interface revert -vserver Cluster -lif n1_clus4
cluster::*> network interface revert -vserver Cluster -lif n2_clus1
cluster::*> network interface revert -vserver Cluster -lif n2_clus4
----
====
. インターフェイスがホームであることを確認します。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
次の例は、クラスタ相互接続インターフェースのステータスを示しています。 `up`そして `Is Home`n1とn2の場合:

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step29]] Nexus 3232C クラスタ スイッチにノードを追加してクラスタを拡張します。
+
次の例では、ノード n3 と n4 に、両方の Nexus 3232C クラスタ スイッチ上のポート e1/7 と e1/8 にそれぞれ接続された 40 GbE クラスタ ポートがあり、両方のノードがクラスタに参加していることを示しています。使用される 40 GbE クラスタ相互接続ポートは e4a と e4e です。

+
構成内のデバイスに関する情報を表示します。

+
** `network device-discovery show`
** `network port show -role cluster`
** `network interface show -role cluster`
** `system cluster-switch show`


+
.例を表示
[%collapsible]
====
[listing]
----
cluster::> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    C1                 Ethernet1/1/1    N3K-C3232C
            e0b    C2                 Ethernet1/1/1    N3K-C3232C
            e0c    C2                 Ethernet1/1/2    N3K-C3232C
            e0d    C1                 Ethernet1/1/2    N3K-C3232C
n2         /cdp
            e0a    C1                 Ethernet1/1/3    N3K-C3232C
            e0b    C2                 Ethernet1/1/3    N3K-C3232C
            e0c    C2                 Ethernet1/1/4    N3K-C3232C
            e0d    C1                 Ethernet1/1/4    N3K-C3232C
n3         /cdp
            e4a    C1                 Ethernet1/7      N3K-C3232C
            e4e    C2                 Ethernet1/7      N3K-C3232C
n4         /cdp
            e4a    C1                 Ethernet1/8      N3K-C3232C
            e4e    C2                 Ethernet1/8      N3K-C3232C
12 entries were displayed.
----
+

[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
12 entries were displayed.
----
+

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4e     true
12 entries were displayed.
----
+

[listing]
----
cluster::*> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.103      NX3232C
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network     10.10.1.104      NX3232C
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

CL1                           cluster-network   10.10.1.101     NX5596
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP
CL2                           cluster-network    10.10.1.102     NX5596
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP

4 entries were displayed.
----
====
. 交換したNexus 5596を取り外します。 `system cluster-switch delete`自動的に削除されない場合は、コマンドを実行します。
+
`system cluster-switch delete -device switch-name`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch delete –device CL1
cluster::> system cluster-switch delete –device CL2
----
====




=== ステップ3: 手順を完了する

. 適切なクラスタ スイッチが監視されていることを確認します。
+
`system cluster-switch show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.103      NX3232C
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network     10.10.1.104      NX3232C
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
====
. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.次の手順
link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを構成する"]。
