---
permalink: switch-cisco-3232c/migrate-from-switchless-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Cisco Nexus 3232c スイッチを設定する前に、プロセスと用語の概要を確認してください。 
---
= 移行要件
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
2ノードのスイッチレスクラスタを使用している場合は、Cisco Nexus 3232Cクラスタネットワークスイッチを含む2ノードのスイッチドクラスタに移行できます。これは無停止の手順です。

.開始する前に
次のインストールと接続を確認します。

* ノード接続用のポートが利用可能です。クラスタスイッチは、Inter-Switch Link （ISL）ポート e1/31-32 を使用します。
* クラスタ接続に適切なケーブルが揃っています。
+
** 10 GbEクラスタ接続を備えたノードには、ブレークアウトファイバーケーブル付きのQSFP光モジュール、またはQSFP to SFP+銅線ブレークアウトケーブルが必要です。
** 40/100 GbE クラスタ接続を備えたノードには、ファイバーケーブルを使用するサポート対象の QSFP/QSFP28 光モジュール、または QSFP/QSFP28 銅線ダイレクトアタッチケーブルが必要です。
** クラスタスイッチには、適切なISLケーブルが必要です。
+
*** 2x QSFP28 光ファイバーまたは銅線ダイレクトアタッチケーブル。




* 設定は正しく行われ、正常に機能しています。
+
2つのノードは接続され、スイッチレスの2ノードクラスタ構成で正常に動作している必要があります。

* すべてのクラスター ポートは *up* 状態です。
* Cisco Nexus 3232C クラスタスイッチがサポートされています。
* 既存のクラスター ネットワーク構成は次のとおりです。
+
** 両方のスイッチ上に冗長構成で完全に機能するNexus 3232Cクラスタインフラストラクチャ
** スイッチにインストールされている最新のRCFおよびNX-OSバージョン
** 両方のスイッチにおける管理接続
** 両方のスイッチへのコンソールアクセス
** 移行されていない状態で *up* 状態にあるすべてのクラスタ論理インターフェイス（LIF）
** スイッチの初期カスタマイズ
** すべてのISLポートが有効化され、ケーブル接続済み




.使用されている例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* Nexus 3232C クラスタスイッチ、*C1* および *C2*。
* ノードは*n1*と*n2*です。


この手順の例では、2つのノードを使用し、それぞれが2つの40 GbEクラスタ インターコネクトポート *e4a* と *e4e* を使用します。link:https://hwu.netapp.com/["Hardware Universe"^]には、お使いのプラットフォームのクラスタポートに関する詳細情報が記載されています。

* *n1_clus1* は、ノード *n1* のクラスタスイッチ *C1* に接続される最初のクラスタ論理インターフェイス （LIF） です。
* *n1_clus2* は、ノード *n1* のクラスタスイッチ *C2* に接続される最初のクラスタ LIF です。
* *n2_clus1* は、ノード *n2* のクラスタスイッチ *C1* に接続される最初のクラスタ LIF です。
* *n2_clus2* は、ノード *n2* のクラスタスイッチ *C2* に接続される 2 番目のクラスタ LIF です。
* 10 GbE および 40/100 GbE ポートの数は、 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco® クラスタ ネットワークスイッチリファレンス設定ファイルのダウンロード"^]ページで入手可能なリファレンス構成ファイル（RCF）で定義されています。


[NOTE]
====
この手順では、ONTAPコマンドとCisco Nexus 3000シリーズ スイッチ コマンドの両方を使用する必要があります。特に明記されていないかぎり、ONTAPコマンドを使用します。

====
.次の手順
移行要件を確認したら、link:migrate-from-switchless-prepare-to-migrate.html["スイッチの移行準備"]。
