---
permalink: switch-cisco-3232c/migrate-from-cisco-nexus-5596.html 
sidebar: sidebar 
keywords: migrate, cisco nexus 5596 switch, 3232c 
summary: クラスタ内の既存の Cisco Nexus 5596 クラスタスイッチを Nexus 3232C クラスタスイッチに交換するには、特定の順序でタスクを実行する必要があります。 
---
= Cisco Nexus 5596 クラスタスイッチから Cisco Nexus 3232C クラスタスイッチへの移行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存の Cisco Nexus 5596 クラスタスイッチを Nexus 3232C クラスタスイッチを使用するクラスタに移行するには、この手順に従ってください。



[[review-requirements]]
== 要件の確認

移行前に必ずlink:migrate-requirements-3232c.html["移行要件"]を確認してください。

[NOTE]
====
この手順では、ONTAPコマンドとCisco Nexus 3000シリーズ スイッチ コマンドの両方を使用する必要があります。特に明記されていないかぎり、ONTAPコマンドを使用します。

====
詳細については、以下を参照してください。

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^]
* link:http://hwu.netapp.com["Hardware Universe"^]
* link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["HWU にない機器をインストールするには、どのような追加情報が必要ですか?"^]




[[migrate-the-switch]]
== スイッチを移行する

.例について
この手順の例では、Cisco Nexus 5596 スイッチを Cisco Nexus 3232C スイッチに交換する方法について説明します。これらの手順は（一部修正を加えて）他の古い Cisco スイッチ（例：3132Q-V）にも使用できます。

この手順では、以下のスイッチおよびノードの命名規則も使用します。

* コマンド出力は、ONTAPのリリースによって異なる場合があります。
* 交換対象となるNexus 5596スイッチは、CL1とCL2です。
* Nexus 5596スイッチの後継機種となるNexus 3232Cスイッチは、C1とC2です。
* n1_clus1は、ノードn1のクラスタスイッチ1（CL1またはC1）に接続された最初のクラスタ論理インターフェース（LIF）です。
* n1_clus2 は、ノード n1 のクラスタスイッチ 2 （CL2 または C2） に接続された最初のクラスタ LIF です。
* n1_clus3は、ノードn1のクラスタスイッチ2（CL2またはC2）に接続されている2番目のLIFです。
* n1_clus4は、ノードn1のクラスタスイッチ1（CL1またはC1）に接続された2番目のLIFです。
* 10 GbEポートと40/100 GbEポートの数は、link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® クラスタ ネットワークスイッチリファレンス設定ファイルのダウンロード"^]で入手可能な参照構成ファイル（RCF）で定義されています。
* ノードは n1 、 n2 、 n3 、 n4 です。


この手順の例では、4つのノードを使用します。

* 2つのノードは、4つの10 GbEクラスタ インターコネクトポートを使用します：e0a、e0b、e0c、e0d。
* 他の2つのノードは2つの40GbEクラスタ インターコネクト ポートを使用します：e4a、e4e。link:https://hwu.netapp.com/["Hardware Universe"^]には、プラットフォーム上の実際のクラスタ ポートが記載されています。


.シナリオ
この手順は、以下のシナリオを対象としています：

* このクラスタは、2台のNexus 5596クラスタスイッチに接続されて動作する2つのノードで構成された状態から始まります。
* クラスタスイッチCL2をC2に交換する（手順1～19）：
+
** CL2に接続されているすべてのノード上のすべてのクラスタポートとLIF上のトラフィックは、CL1に接続されている最初のクラスタポートとLIFに移行されます。
** CL2に接続されているすべてのノードのすべてのクラスタポートからケーブルを外し、サポートされているブレークアウトケーブルを使用してポートを新しいクラスタスイッチC2に再接続します。
** CL1とCL2間のISLポート間のケーブルを外し、サポートされているブレークアウトケーブルを使用してCL1からC2へのポートを再接続します。
** すべてのノード上の C2 に接続されているすべてのクラスタポートおよび LIF のトラフィックが元に戻されます。


* クラスタスイッチ CL2 を C2 に交換します。
+
** CL1に接続されているすべてのノード上のすべてのクラスタポートまたはLIF上のトラフィックは、C2に接続されている2番目のクラスタポートまたはLIFに移行されます。
** CL1に接続されているすべてのノードのすべてのクラスタポートからケーブルを外し、サポートされているブレークアウトケーブルを使用して、新しいクラスタスイッチC1に再接続します。
** CL1とC2間のISLポート間のケーブルを外し、C1からC2へサポートされているケーブルを使用して再接続します。
** すべてのノード上の C1 に接続されているすべてのクラスタポートまたは LIF のトラフィックがリバートされます。


* 2つのFAS9000ノードがクラスタに追加され、クラスタの詳細を示す例が表示されています。




[[step-1-prepare-for-migration]]
=== ステップ1: 移行の準備

. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

+
[NOTE]
====
AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

====
. 設定内のデバイスに関する情報を表示します。
+
`network device-discovery show`

+
.例を表示
[%collapsible]
====
次の例は、各クラスタ インターコネクト スイッチについて、各ノードに設定されているクラスタ インターコネクト インターフェイスの数を示しています：

[listing, subs="+quotes"]
----
cluster::> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    CL1                 Ethernet1/1      N5K-C5596UP
            e0b    CL2                 Ethernet1/1      N5K-C5596UP
            e0c    CL2                 Ethernet1/2      N5K-C5596UP
            e0d    CL1                 Ethernet1/2      N5K-C5596UP
n2         /cdp
            e0a    CL1                 Ethernet1/3      N5K-C5596UP
            e0b    CL2                 Ethernet1/3      N5K-C5596UP
            e0c    CL2                 Ethernet1/4      N5K-C5596UP
            e0d    CL1                 Ethernet1/4      N5K-C5596UP
8 entries were displayed.
----
====
. 各クラスタ インターフェイスの管理ステータスまたは動作ステータスを決定します。
+
.. ネットワーク ポートの属性を表示します。
+
`network port show -role cluster`

+
.例を表示
[%collapsible]
====
次の例は、ノードn1とn2のネットワークポート属性を表示します。

[listing, subs="+quotes"]
----
cluster::*> *network port show –role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
.. 論理インターフェースに関する情報を表示します。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
次の例は、クラスタ上のすべてのLIFに関する一般的な情報（現在のポートを含む）を表示します。

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
.. 検出されたクラスタスイッチに関する情報を表示します。
+
`system cluster-switch show`

+
.例を表示
[%collapsible]
====
以下の例は、アクティブなクラスタスイッチを示しています。

[listing, subs="+quotes"]
----
cluster::*> *system cluster-switch show*

Switch                        Type               Address         Model
----------------------------- ------------------ --------------- ---------------
CL1                           cluster-network    10.10.1.101     NX5596
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP
CL2                           cluster-network    10.10.1.102     NX5596
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP

2 entries were displayed.
----
====


. 要件に応じて、新しい 3232C スイッチに適切な RCF とイメージがインストールされていることを確認し、ユーザーとパスワード、ネットワークアドレス、その他のカスタマイズなど、必要なサイトのカスタマイズを行います。
+
[NOTE]
====
この時点で、両方のスイッチを準備する必要があります。

====
+
RCFとイメージをアップグレードする必要がある場合は、以下の手順を完了する必要があります：

+
.. NetApp Support SiteのCisco Ethernet Switchesページに移動します。
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^]

.. そのページにある表で、お使いのスイッチと必要なソフトウェアのバージョンを確認してください。
.. 適切なバージョンのRCFをダウンロードしてください。
.. *概要* ページで *続行* をクリックし、ライセンス契約に同意してから、*ダウンロード* ページの指示に従って RCF をダウンロードしてください。
.. 適切なバージョンのイメージソフトウェアをダウンロードしてください。
+
__ONTAP 8.x 以降のクラスタおよび管理ネットワークスイッチのリファレンス構成ファイル__ のダウンロードページを参照し、適切なバージョンをクリックしてください。

+
適切なバージョンを確認するには、_ONTAP 8.x 以降のクラスタ ネットワーク スイッチのダウンロード ページ_を参照してください。



. 交換対象となる2台目のNexus 5596スイッチに関連付けられているLIFを移行します。
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ -source-node _source-node-name_ - destination-node _node-name_ -destination-port _destination-port-name_`

+
.例を表示
[%collapsible]
====
以下の例は、ノード n1 と n2 の LIF を移行する様子を示しています。LIF の移行はすべてのノードで実行する必要があります：

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1 -
destination-node n1 -destination-port e0a*
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus3 -source-node n1 -
destination-node n1 -destination-port e0d*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2 -
destination-node n2 -destination-port e0a*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus3 -source-node n2 -
destination-node n2 -destination-port e0d*
----
====
. クラスタのヘルスを確認します。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
以下の例は、各クラスターの現在の状態を示しています。

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0a     false
            n1_clus3   up/up      10.10.0.3/24       n1            e0d     false
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0a     false
            n2_clus3   up/up      10.10.0.7/24       n2            e0d     false
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====




[[step-2-configure-ports]]
=== ステップ2: ポートを構成する

. スイッチ CL2 に物理的に接続されているクラスタ インターコネクト ポートをシャットダウンします：
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.例を表示
[%collapsible]
====
以下のコマンドはn1とn2上の指定されたポートをシャットダウンしますが、ポートはすべてのノードでシャットダウンする必要があります：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin false*
cluster::*> *network port modify -node n1 -port e0c -up-admin false*
cluster::*> *network port modify -node n2 -port e0b -up-admin false*
cluster::*> *network port modify -node n2 -port e0c -up-admin false*
----
====
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注:* 詳細を表示するには、show コマンドを実行する前に数秒間待ってください。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step3]] アクティブな Nexus 5596 スイッチである CL1 の ISL 41 ～ 48 を、Cisco `shutdown`コマンドを使用してシャットダウンします。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]の適切なガイドを参照してください。

+
.例を表示
[%collapsible]
====
次の例は、Nexus 5596スイッチCL1上でISL 41～48をシャットダウンする様子を示しています。

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface e1/41-48*
(CL1)(config-if-range)# *shutdown*
(CL1)(config-if-range)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. 適切な Cisco コマンドを使用して、CL1 と C2 の間に一時的な ISL を構築します。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]の適切なガイドを参照してください。

+
.例を表示
[%collapsible]
====
以下の例は、CL1とC2の間に一時的なISLを設定する場合の例を示しています。

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *interface port-channel 2*
C2(config-if)# *switchport mode trunk*
C2(config-if)# *spanning-tree port type network*
C2(config-if)# *mtu 9216*
C2(config-if)# *interface breakout module 1 port 24 map 10g-4x*
C2(config)# *interface e1/24/1-4*
C2(config-if-range)# *switchport mode trunk*
C2(config-if-range)# *mtu 9216*
C2(config-if-range)# *channel-group 2 mode active*
C2(config-if-range)# *exit*
C2(config-if)# *exit*
----
====
. すべてのノードで、Nexus 5596スイッチCL2に接続されているすべてのケーブルを取り外します。
+
サポートされているケーブルを使用して、すべてのノードの切断されたポートを Nexus 3232C スイッチ C2 に再接続します。

. Nexus 5596スイッチCL2からすべてのケーブルを取り外します。
+
新しい Cisco 3232C スイッチ C2 のポート 1/24 を既存の Nexus 5596 CL1 のポート 45 ～ 48 に接続する、適切な Cisco QSFP から SFP+ へのブレークアウト ケーブルを取り付けます。

. アクティブな Nexus 5596 スイッチ CL1 上で、ISL のポート 45 ～ 48 を起動します。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]の適切なガイドを参照してください。

+
.例を表示
[%collapsible]
====
以下の例は、ISLのポート45～48が起動する様子を示しています。

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface e1/45-48*
(CL1)(config-if-range)# *no shutdown*
(CL1)(config-if-range)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. ISLがNexus 5596スイッチCL1上に `up`あることを確認します。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]の適切なガイドを参照してください。

+
.例を表示
[%collapsible]
====
次の例では、ポート eth1/45 から eth1/48 に （P） が表示されています。これは、ISL ポートが `up`ポートチャネル内にあることを示しています。

[listing, subs="+quotes"]
----
CL1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/41(D)   Eth1/42(D)   Eth1/43(D)
                                    Eth1/44(D)   Eth1/45(P)   Eth1/46(P)
                                    Eth1/47(P)   Eth1/48(P)
----
====
. eth1/45-48インターフェースの実行コンフィグレーションに`channel-group 1 mode active`が既に設定されていることを確認してください。
. すべてのノードで、3232C スイッチ C2 に接続されているすべてのクラスタ インターコネクト ポートを起動します：
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.例を表示
[%collapsible]
====
以下の例は、ノード n1 と n2 で指定されたポートが起動される様子を示しています。

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin true*
cluster::*> *network port modify -node n1 -port e0c -up-admin true*
cluster::*> *network port modify -node n2 -port e0b -up-admin true*
cluster::*> *network port modify -node n2 -port e0c -up-admin true*
----
====
. すべてのノードで、C2に接続されている移行済みのすべてのクラスタ インターコネクト LIF をリバートします：
+
`network interface revert -vserver Cluster -lif _lif-name_`

+
.例を表示
[%collapsible]
====
次の例は、移行されたクラスタLIFが元のホームポートに戻される様子を示しています。

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver Cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n1_clus3*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus3*
----
====
. すべてのクラスタ インターコネクト ポートがホームに戻っていることを確認します：
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
次の例は、clus2 上の LIF がホーム ポートに戻ったことを示しています。また、Current Port 列のポートのステータスが `true`（ `Is Home`列）である場合、LIF が正常に元に戻ったことを示しています。 `Is Home`の値が `false`の場合、LIF は元に戻されていません。

[listing]
----
cluster::*> *network interface show -role cluster*
(network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
. クラスタ化されたポートが接続されていることを確認します。
+
`network port show -role cluster`

+
.例を表示
[%collapsible]
====
次の例は、前の `network port modify`コマンドの結果を示しており、すべてのクラスタ インターコネクトが `up`であることを確認しています：

[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step15]] クラスタ内の各ノードで、交換対象となる最初の Nexus 5596 スイッチ CL1 に関連付けられているインターフェイスを移行します。
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ -source-node _source-node-name_
-destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.例を表示
[%collapsible]
====
次の例は、ノードn1とn2で移行されるポートまたはLIFを示しています。

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus1 -source-node n1 -
destination-node n1 -destination-port e0b*
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus4 -source-node n1 -
destination-node n1 -destination-port e0c*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus1 -source-node n2 -
destination-node n2 -destination-port e0b*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus4 -source-node n2 -
destination-node n2 -destination-port e0c*
----
====
. クラスターのステータスを確認します：
+
`network interface show`

+
.例を表示
[%collapsible]
====
次の例は、必要なクラスタ LIF がクラスタスイッチ C2 上の適切なクラスタポートに移行されたことを示しています。

[listing, subs="+quotes"]
----
cluster::*> *network interface show*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0b     false
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0c     false
            n2_clus1   up/up      10.10.0.5/24       n2            e0b     false
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0c     false
8 entries were displayed.

----- ------- ----
----
====
. すべてのノードで、CL1に接続されているノードポートをシャットダウンします。
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.例を表示
[%collapsible]
====
次の例は、ノード n1 と n2 で指定されたポートがシャットダウンされる様子を示しています。

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0a -up-admin false*
cluster::*> *network port modify -node n1 -port e0d -up-admin false*
cluster::*> *network port modify -node n2 -port e0a -up-admin false*
cluster::*> *network port modify -node n2 -port e0d -up-admin false*
----
====
. アクティブな 3232C スイッチ C2 の ISL 24、31、32 をシャットダウンします。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]の適切なガイドを参照してください。

+
.例を表示
[%collapsible]
====
以下の例は、ISLがシャットダウンされる様子を示しています。

[listing, subs="+quotes"]
----
C2# *configure*
C2(Config)# *interface e1/24/1-4*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config)# *interface 1/31-32*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config-if)# *exit*
C2#
----
====
. すべてのノードで、Nexus 5596スイッチCL1に接続されているすべてのケーブルを取り外します。
+
サポートされているケーブルを使用して、すべてのノードの切断されたポートを Nexus 3232C スイッチ C1 に再接続します。

. Nexus 3232C C2ポートe1/24からQSFPブレークアウトケーブルを取り外します。
+
サポートされている Cisco QSFP 光ファイバーケーブルまたはダイレクトアタッチケーブルを使用して、C1 のポート e1/31 と e1/32 を C2 のポート e1/31 と e1/32 に接続します。

. ポート24の設定を復元し、C2上の一時的なPort Channel 2を削除します。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]の適切なガイドを参照してください。

+
.例を表示
[%collapsible]
====
以下の例は、適切な Cisco コマンドを使用してポート m24 の設定を復元する様子を示しています：

[listing, subs="+quotes"]
----
C2# configure
C2(config)# *no interface breakout module 1 port 24 map 10g-4x*
C2(config)# *no interface port-channel 2*
C2(config-if)# *int e1/24*
C2(config-if)# *description 40GbE Node Port*
C2(config-if)# *spanning-tree port type edge*
C2(config-if)# *spanning-tree bpduguard enable*
C2(config-if)# *mtu 9216*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. アクティブな 3232C スイッチである C2 で、次の Cisco コマンドを入力して ISL ポート 31 と 32 を起動します： `no shutdown`
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]の適切なガイドを参照してください。

+
.例を表示
[%collapsible]
====
次の例は、3232C スイッチ C2 で実行された Cisco コマンド `switchname configure`を示しています：

[listing, subs="+quotes"]
----
C2# configure
C2(config)# interface ethernet 1/31-32
C2(config-if-range)# no shutdown
----
====
. ISL接続が3232CスイッチC2上に `up`あることを確認してください。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]の適切なガイドを参照してください。

+
ポートeth1/31とeth1/32は（P）と表示されるはずです。これは、両方のISLポートがポートチャネルでアクティブになっていることを意味します。

+
.例を表示
[%collapsible]
====
[listing]
----

C1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. すべてのノードで、新しい 3232C スイッチ C1 に接続されているすべてのクラスタ インターコネクト ポートを起動します：
+
`network port modify`

+
.例を表示
[%collapsible]
====
次の例は、3232C スイッチ C1 上で n1 と n2 のすべてのクラスタ インターコネクト ポートが起動される様子を示しています。

[listing]
----

cluster::*> network port modify -node n1 -port e0a -up-admin true
cluster::*> network port modify -node n1 -port e0d -up-admin true
cluster::*> network port modify -node n2 -port e0a -up-admin true
cluster::*> network port modify -node n2 -port e0d -up-admin true
----
====
. クラスタノードポートのステータスを確認します。
+
`network port show`

+
.例を表示
[%collapsible]
====
次の例は、新しい 3232C スイッチ C1 上のすべてのノードのすべてのクラスタ インターコネクト ポートが稼働中であることを確認します。

[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
. すべてのノードで、特定のクラスタLIFをホームポートに戻します。
+
`network interface revert -server Cluster -lif _lif-name_`

+
.例を表示
[%collapsible]
====
次の例は、ノードn1とn2上で、特定のクラスタLIFがホームポートにリバートされる様子を示しています。

[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus1
cluster::*> network interface revert -vserver Cluster -lif n1_clus4
cluster::*> network interface revert -vserver Cluster -lif n2_clus1
cluster::*> network interface revert -vserver Cluster -lif n2_clus4
----
====
. インターフェースがホームであることを確認してください。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
次の例は、n1とn2のクラスタ インターコネクト インターフェースのステータスが `up`および `Is Home`であることを示しています：

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step29]] Nexus 3232C クラスタスイッチにノードを追加してクラスタを拡張します。
+
以下の例は、ノードn3とn4がそれぞれNexus 3232Cクラスタスイッチのポートe1/7とe1/8に40 GbEクラスタポートで接続されており、両方のノードがクラスタに参加していることを示しています。使用される40 GbEクラスタ インターコネクト ポートはe4aとe4eです。

+
設定に含まれるデバイスに関する情報を表示します。

+
** `network device-discovery show`
** `network port show -role cluster`
** `network interface show -role cluster`
** `system cluster-switch show`


+
.例を表示
[%collapsible]
====
[listing]
----
cluster::> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    C1                 Ethernet1/1/1    N3K-C3232C
            e0b    C2                 Ethernet1/1/1    N3K-C3232C
            e0c    C2                 Ethernet1/1/2    N3K-C3232C
            e0d    C1                 Ethernet1/1/2    N3K-C3232C
n2         /cdp
            e0a    C1                 Ethernet1/1/3    N3K-C3232C
            e0b    C2                 Ethernet1/1/3    N3K-C3232C
            e0c    C2                 Ethernet1/1/4    N3K-C3232C
            e0d    C1                 Ethernet1/1/4    N3K-C3232C
n3         /cdp
            e4a    C1                 Ethernet1/7      N3K-C3232C
            e4e    C2                 Ethernet1/7      N3K-C3232C
n4         /cdp
            e4a    C1                 Ethernet1/8      N3K-C3232C
            e4e    C2                 Ethernet1/8      N3K-C3232C
12 entries were displayed.
----
+

[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
12 entries were displayed.
----
+

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4e     true
12 entries were displayed.
----
+

[listing]
----
cluster::*> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.103      NX3232C
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network     10.10.1.104      NX3232C
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

CL1                           cluster-network   10.10.1.101     NX5596
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP
CL2                           cluster-network    10.10.1.102     NX5596
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP

4 entries were displayed.
----
====
. 交換した Nexus 5596 が自動的に削除されない場合は、 `system cluster-switch delete` コマンドを使用して取り外してください：
+
`system cluster-switch delete -device switch-name`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch delete –device CL1
cluster::> system cluster-switch delete –device CL2
----
====




[[step-3-complete-the-procedure]]
=== ステップ3: 手順を完了する

. 適切なクラスタスイッチが監視されていることを確認してください。
+
`system cluster-switch show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.103      NX3232C
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network     10.10.1.104      NX3232C
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
====
. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.次の手順
link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを構成する"]。
