---
permalink: switch-cisco-3232c/migrate-from-switchless-prepare-to-migrate.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: 2ノードのスイッチレスクラスタから Cisco Nexus 3232C クラスタスイッチへの移行を準備します。 
---
= スイッチレスクラスタから Cisco Nexus 3232C クラスタスイッチへの移行準備
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C クラスタスイッチを使用して、2ノードのスイッチレスクラスタをスイッチドクラスタに移行するための準備を行います。

.手順
. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

+
[NOTE]
====
AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

====
. 各クラスタ インターフェイスの管理ステータスまたは動作ステータスを確認します。
+
.. ネットワーク ポートの属性を表示します。
+
`network port show -role cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -
4 entries were displayed.
----
====
.. 論理インターフェイスとそれに指定されたホーム ノードに関する情報を表示します。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ---
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true

4 entries were displayed.
----
====
.. advanced 権限コマンドを使用して、スイッチレスクラスタ検出が有効になっていることを確認します：
+
`network options detect-switchless-cluster show``

+
.例を表示
[%collapsible]
====
次の例の出力は、スイッチレスクラスタ検出が有効になっていることを示しています。

[listing, subs="+quotes"]
----
cluster::*> *network options detect-switchless-cluster show*
Enable Switchless Cluster Detection: true
----
====


. 新しい 3232C スイッチに適切な RCF とイメージがインストールされていることを確認し、ユーザー、パスワード、ネットワークアドレスの追加など、必要なサイトのカスタマイズを行います。
+
この時点で、両方のスイッチを準備する必要があります。RCFとイメージソフトウェアをアップグレードする必要がある場合は、以下の手順に従ってください。

+
.. NetApp Support SiteのCisco Ethernet Switchesページに移動します。
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch/["Ciscoイーサネット スイッチ"^]

.. そのページにある表で、お使いのスイッチと必要なソフトウェアのバージョンを確認してください。
.. 適切なバージョンのRCFをダウンロードしてください。
.. *概要* ページで *続行* を選択し、ライセンス契約に同意してから、*ダウンロード* ページの指示に従って RCF をダウンロードしてください。
.. 適切なバージョンのイメージソフトウェアをダウンロードしてください。
+
link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco クラスタおよび管理ネットワーク スイッチのリファレンス設定ファイルのダウンロード"^]



. *概要* ページで *続行* を選択し、ライセンス契約に同意してから、*ダウンロード* ページの指示に従って RCF をダウンロードしてください。
. Nexus 3232C スイッチ C1 および C2 では、ノード側のすべてのポート C1 および C2 を無効にしますが、ISL ポート e1/31-32 は無効にしないでください。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]の以下のリストを参照してください。

+
.例を表示
[%collapsible]
====
以下の例は、RCF `NX3232_RCF_v1.0_24p10g_24p100g.txt`でサポートされている構成を使用して、Nexus 3232C クラスタスイッチ C1 および C2 でポート 1 ～ 30 を無効にする方法を示しています：

[listing, subs="+quotes"]
----
C1# copy running-config startup-config
[########################################] 100% Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit
C2# copy running-config startup-config
[########################################] 100% Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. 対応ケーブルを使用して、C1のポート1/31と1/32をC2の同じポートに接続します。
. C1とC2のISL ポートが正常に動作していることを確認します。
+
`show port-channel summary`

+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]の以下のリストを参照してください。

+
.例を表示
[%collapsible]
====
次の例は、Cisco `show port-channel summary`コマンドを使用して、C1およびC2上のISLポートが動作していることを確認する方法を示しています：

[listing, subs="+quotes"]
----
C1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
      Port-
Group Channel      Type   Protocol  Member Ports
-------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------

Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. スイッチに接続されている近隣デバイスの一覧を表示します。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]の以下のリストを参照してください。

+
.例を表示
[%collapsible]
====
次の例は、Cisco コマンド `show cdp neighbors`がスイッチ上の隣接デバイスを表示するために使用されている様子を示しています。

[listing, subs="+quotes"]
----
C1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3232C  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3232C  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
----
====
. 各ノードのクラスタ ポート接続状況を表示します。
+
`network device-discovery show`

+
.例を表示
[%collapsible]
====
次の例は、2ノードのスイッチレスクラスタ構成で表示されるクラスタ ポートの接続状況を示しています。

[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====


.次の手順
スイッチの移行準備が完了したら、link:migrate-from-switchless-configure-ports.html["ポートを設定する"]。
