---
permalink: switch-cisco-3232c/migrate-from-switchless-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Cisco Nexus 3232c スイッチを構成する前に、プロセスと命名法の概要を確認してください。 
---
= 移行要件
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
2 ノードのスイッチレス クラスタがある場合は、 Cisco Nexus 3232C クラスタ ネットワーク スイッチを含む 2 ノードのスイッチ クラスタに移行できます。この手順は無停止で実行されます。

.開始する前に
次のインストールと接続を確認します。

* ノード接続にポートを使用できます。クラスタ スイッチは、スイッチ間リンク (ISL) ポート e1/31-32 を使用します。
* クラスター接続に適したケーブルがあります。
+
** 10 GbE クラスター接続を備えたノードには、ブレークアウト ファイバー ケーブル付きの QSFP 光モジュール、または QSFP から SFP+ への銅ブレークアウト ケーブルが必要です。
** 40/100 GbE クラスター接続を備えたノードには、ファイバー ケーブルまたは QSFP/QSFP28 銅線直接接続ケーブルを備えたサポートされている QSFP/QSFP28 光モジュールが必要です。
** クラスタ スイッチには適切な ISL ケーブルが必要です。
+
*** 2 本の QSFP28 ファイバーまたは銅線直接接続ケーブル。




* 構成は適切に設定され、機能しています。
+
2 つのノードは、2 ノード スイッチレス クラスター設定で接続され、機能している必要があります。

* すべてのクラスター ポートは *up* 状態です。
* Cisco Nexus 3232C クラスタ スイッチがサポートされています。
* 既存のクラスター ネットワーク構成は次のとおりです。
+
** 両方のスイッチに冗長化され、完全に機能する Nexus 3232C クラスタ インフラストラクチャ
** スイッチ上の最新のRCFおよびNX-OSバージョン
** 両方のスイッチでの管理接続
** 両方のスイッチへのコンソールアクセス
** 移行されていない、*up*状態のすべてのクラスタ論理インターフェース（LIF）
** スイッチの初期カスタマイズ
** すべてのISLポートが有効になり、ケーブル接続されています




.使用された例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* Nexus 3232C クラスタ スイッチ、*C1* および *C2*。
* ノードは *n1* と *n2* です。


この手順の例では、2 つのノードを使用し、各ノードで 2 つの 40 GbE クラスタ相互接続ポート *e4a* と *e4e* を使用します。そのlink:https://hwu.netapp.com/["_ハードウェアユニバース_"^]プラットフォーム上のクラスター ポートに関する詳細が記載されています。

* *n1_clus1* は、ノード *n1* のクラスタ スイッチ *C1* に接続される最初のクラスタ論理インターフェイス (LIF) です。
* *n1_clus2* は、ノード *n1* のクラスタ スイッチ *C2* に接続される最初のクラスタ LIF です。
* *n2_clus1* は、ノード *n2* のクラスタ スイッチ *C1* に接続される最初のクラスタ LIF です。
* *n2_clus2* は、ノード *n2* のクラスタ スイッチ *C2* に接続される 2 番目のクラスタ LIF です。
* 10 GbEおよび40/100 GbEポートの数は、 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco® クラスタ ネットワーク スイッチ リファレンス コンフィギュレーション ファイルのダウンロード"^]ページ。


[NOTE]
====
この手順では、ONTAPコマンドとCisco Nexus 3000シリーズ スイッチ コマンドの両方を使用する必要があります。特に明記されていないかぎり、ONTAPコマンドを使用します。

====
.次の手順
link:migrate-from-switchless-prepare-to-migrate.html["移行の準備"]。
