---
permalink: switch-cisco-3232c/migrate-from-two-node-switchless-cluster.html 
sidebar: sidebar 
keywords: migrate, two-node cluster, switchless, cisco nexus 3232c 
summary: Cisco Nexus 3232C クラスタスイッチを使用して、2ノードのスイッチレスクラスタからスイッチドクラスタに移行します。これは無停止の手順です。 
---
= 2ノードのスイッチレスクラスタから Cisco Nexus 3232C クラスタスイッチへの移行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C クラスタスイッチを使用して、2ノードのスイッチレスクラスタからスイッチドクラスタに移行します。これは無停止の手順です。



[[review-requirements]]
== 要件の確認

.開始する前に
次のインストールと接続を確認します。

* ノード接続用のポートが利用可能です。クラスタスイッチは、Inter-Switch Link （ISL）ポート e1/31-32 を使用します。
* クラスタ接続に適切なケーブルが揃っています。
+
** 10 GbEクラスタ接続を備えたノードには、ブレークアウトファイバーケーブル付きのQSFP光モジュール、またはQSFP to SFP+銅線ブレークアウトケーブルが必要です。
** 40/100 GbE クラスタ接続を備えたノードには、ファイバーケーブルを使用した対応 QSFP/QSFP28 光モジュール、または QSFP/QSFP28 銅線ダイレクトアタッチケーブルが必要です。
** クラスタスイッチには、適切なISLケーブル（2x QSFP28光ファイバーまたは銅線ダイレクトアタッチケーブル）が必要です。


* 設定は正しく行われ、正常に機能しています。
+
2つのノードは接続され、スイッチレスの2ノードクラスタ構成で正常に動作している必要があります。

* すべてのクラスター ポートは *up* 状態です。
* Cisco Nexus 3232C クラスタスイッチがサポートされています。
* 既存のクラスター ネットワーク構成は次のとおりです。
+
** 両方のスイッチ上に冗長構成で完全に機能するNexus 3232Cクラスタインフラストラクチャ
** スイッチにインストールされている最新のRCFおよびNX-OSバージョン
** 両方のスイッチにおける管理接続
** 両方のスイッチへのコンソールアクセス
** 移行されていない状態で *up* 状態にあるすべてのクラスタ論理インターフェイス（LIF）
** スイッチの初期カスタマイズ
** すべてのISLポートが有効化され、ケーブル接続済み




.例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* Nexus 3232C クラスタスイッチ、C1 および C2。
* ノードはn1とn2です。


この手順の例では、2つのノードを使用し、それぞれが2つの40 GbEクラスタ インターコネクト ポートe4aとe4eを使用します。link:https://hwu.netapp.com/["Hardware Universe"^]には、お使いのプラットフォーム上のクラスタ ポートに関する詳細情報が含まれています。

* n1_clus1は、ノードn1のクラスタスイッチC1に接続される最初のクラスタ論理インターフェース（LIF）です。
* n1_clus2は、ノードn1のクラスタ スイッチC2に接続される最初のクラスタLIFです。
* n2_clus1は、ノードn2のクラスタスイッチC1に接続される最初のクラスタLIFです。
* n2_clus2は、ノードn2のクラスタスイッチC2に接続される2番目のクラスタLIFです。
* 10 GbEポートと40/100 GbEポートの数は、link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® クラスタ ネットワークスイッチリファレンス設定ファイルのダウンロード"^]で入手可能な参照構成ファイル（RCF）で定義されています。


[NOTE]
====
この手順では、ONTAPコマンドとCisco Nexus 3000シリーズ スイッチ コマンドの両方を使用する必要があります。特に明記されていないかぎり、ONTAPコマンドを使用します。

====


[[step-1-display-and-migrate-physical-and-logical-ports]]
== ステップ1：物理ポートと論理ポートを表示して移行する

. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

+
[NOTE]
====
AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

====
. 各クラスタ インターフェイスの管理ステータスまたは動作ステータスを確認します。
+
.. ネットワーク ポートの属性を表示します。
+
`network port show -role cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -
4 entries were displayed.
----
====
.. 論理インターフェイスとそれに指定されたホーム ノードに関する情報を表示します。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ---
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true

4 entries were displayed.
----
====
.. advanced 権限コマンドを使用して、スイッチレスクラスタ検出が有効になっていることを確認します：
+
`network options detect-switchless-cluster show``

+
.例を表示
[%collapsible]
====
次の例の出力は、スイッチレスクラスタ検出が有効になっていることを示しています。

[listing, subs="+quotes"]
----
cluster::*> *network options detect-switchless-cluster show*
Enable Switchless Cluster Detection: true
----
====


. 新しい 3232C スイッチに適切な RCF とイメージがインストールされていることを確認し、ユーザー、パスワード、ネットワークアドレスの追加など、必要なサイトのカスタマイズを行います。
+
この時点で、両方のスイッチを準備する必要があります。RCFとイメージソフトウェアをアップグレードする必要がある場合は、以下の手順に従ってください。

+
.. NetApp Support SiteのCisco Ethernet Switchesページに移動します。
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^]

.. そのページにある表で、お使いのスイッチと必要なソフトウェアのバージョンを確認してください。
.. 適切なバージョンのRCFをダウンロードしてください。
.. *概要* ページで *続行* をクリックし、ライセンス契約に同意してから、*ダウンロード* ページの指示に従って RCF をダウンロードしてください。
.. 適切なバージョンのイメージソフトウェアをダウンロードしてください。
+
link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco クラスタおよび管理ネットワーク スイッチのリファレンス設定ファイルのダウンロード"^]。



. *概要* ページで *続行* をクリックし、ライセンス契約に同意してから、*ダウンロード* ページの指示に従って RCF をダウンロードしてください。
. Nexus 3232C スイッチ C1 および C2 では、ノード側のすべてのポート C1 および C2 を無効にしますが、ISL ポート e1/31-32 は無効にしないでください。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]に記載されているガイドを参照してください。

+
.例を表示
[%collapsible]
====
以下の例は、RCF `NX3232_RCF_v1.0_24p10g_24p100g.txt`でサポートされている構成を使用して、Nexus 3232C クラスタスイッチ C1 および C2 でポート 1 ～ 30 を無効にする方法を示しています：

[listing, subs="+quotes"]
----
C1# copy running-config startup-config
[########################################] 100% Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit
C2# copy running-config startup-config
[########################################] 100% Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. 対応ケーブルを使用して、C1のポート1/31と1/32をC2の同じポートに接続します。
. C1とC2のISL ポートが正常に動作していることを確認します。
+
`show port-channel summary`

+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]に記載されているガイドを参照してください。

+
.例を表示
[%collapsible]
====
次の例は、Cisco `show port-channel summary`コマンドを使用して、C1およびC2上のISLポートが動作していることを確認する方法を示しています：

[listing, subs="+quotes"]
----
C1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
      Port-
Group Channel      Type   Protocol  Member Ports
-------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------

Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. スイッチに接続されている近隣デバイスの一覧を表示します。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]に記載されているガイドを参照してください。

+
.例を表示
[%collapsible]
====
次の例は、Cisco コマンド `show cdp neighbors`がスイッチ上の隣接デバイスを表示するために使用されている様子を示しています。

[listing, subs="+quotes"]
----
C1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3232C  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3232C  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
----
====
. 各ノードのクラスタ ポート接続状況を表示します。
+
`network device-discovery show`

+
.例を表示
[%collapsible]
====
次の例は、2ノードのスイッチレスクラスタ構成で表示されるクラスタ ポートの接続状況を示しています。

[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====
. n1_clus1およびn2_clus1のLIFを、それぞれの宛先ノードの物理ポートに移行します。
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ source-node _source-node-name_ -destination-port _destination-port-name_`

+
.例を表示
[%collapsible]
====
次の例に示すように、各ローカルノードに対してコマンドを実行する必要があります。

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e4e*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e4e*
----
====




[[step-2-shut-down-the-reassigned-lifs-and-disconnect-the-cables]]
== ステップ2：再割り当てしたLIFをシャットダウンし、ケーブルを外す

. クラスタインターフェースが正常に移行されたことを確認します。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
次の例は、移行完了後にn1_clus1およびn2_clus1 LIFの「Is Home」ステータスが「false」になったことを示しています。

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
 4 entries were displayed.
----
====
. ステップ 9 で移行した n1_clus1 および n2_clus1 LIF のクラスタ ポートをシャットダウンします。
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.例を表示
[%collapsible]
====
次の例に示すように、各ポートに対してコマンドを実行する必要があります。

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin false*
cluster::*> *network port modify -node n2 -port e4a -up-admin false*
----
====
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[ステップ4]] ノードn1のe4aからケーブルを外します。
+
実行中の設定を参照し、Nexus 3232C スイッチでサポートされているケーブルを使用して、スイッチ C1 の最初の 40 GbE ポート（この例ではポート 1/7）を n1 の e4a に接続してください。





[[step-3-enable-the-cluster-ports]]
== ステップ3：クラスタ ポートを有効にする

. ノードn2のe4aからケーブルを外します。
+
実行中の設定を参照し、サポートされているケーブルを使用して、e4aをC1上の次に利用可能な40 GbEポート（ポート1/8）に接続できます。

. C1上のすべてのノード接続ポートを有効にします。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]に記載されているガイドを参照してください。

+
.例を表示
[%collapsible]
====
以下の例は、RCF `NX3232_RCF_v1.0_24p10g_26p100g.txt`でサポートされている構成を使用して、Nexus 3232C クラスタスイッチ C1 および C2 でポート 1 ～ 30 を有効にする方法を示しています：

[listing, subs="+quotes"]
----
C1# *configure*
C1(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C1(config-if-range)# *no shutdown*
C1(config-if-range)# *exit*
C1(config)# *exit*
----
====
. 各ノードで最初のクラスタ ポート（e4a）を有効にします。
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin true*
cluster::*> *network port modify -node n2 -port e4a -up-admin true*
----
====
. 両方のノードでクラスタが起動していることを確認してください。
+
`network port show -role cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

4 entries were displayed.
----
====
. 各ノードについて、移行されたすべてのクラスタ インターコネクト LIF を元に戻します：
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.例を表示
[%collapsible]
====
次の例に示すように、各LIFを個別にホームポートに戻す必要があります。

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus1*
cluster::*> *network interface revert -vserver cluster -lif n2_clus1*
----
====
. すべての LIF がホームポートに戻っていることを確認します。
+
`network interface show -role cluster`

+
 `Current Port`列にリストされているすべてのポートについて、 `Is Home`列に `true`の値が表示されている必要があります。表示されている値が `false`の場合、ポートはリバートされていません。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====




[[step-4-enable-the-reassigned-lifs]]
== ステップ4：再割り当てしたLIFを有効にする

. 各ノードのクラスタ ポート接続状況を表示します。
+
`network device-discovery show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    n1                  e4e              FAS9000
----
====
. 各ノードのコンソールで、clus2をポートe4aに移行します。
+
`network interface migrate cluster -lif _lif-name_ -source-node _source-node-name_ -destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.例を表示
[%collapsible]
====
次の例に示すように、各LIFを個別にホームポートに移行する必要があります。

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus2 -source-node n1
-destination-node n1 -destination-port e4a*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus2 -source-node n2
-destination-node n2 -destination-port e4a*
----
====
. 両方のノードでクラスタポート clus2 LIF をシャットダウンします：
+
`network port modify`

+
.例を表示
[%collapsible]
====
次の例は、指定されたポートが `false`に設定され、両方のノードでポートがシャットダウンされる様子を示しています。

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin false*
cluster::*> *network port modify -node n2 -port e4e -up-admin false*
----
====
. クラスタ LIF のステータスを確認します：
+
`network interface show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. ノードn1のe4eからケーブルを外します。
+
実行中の設定を参照し、Nexus 3232C スイッチモデルに適したケーブルを使用して、スイッチ C2 の最初の 40 GbE ポート（この例ではポート 1/7）をノード n1 の e4e に接続してください。

. ノードn2のe4eからケーブルを外します。
+
実行中の設定を参照し、Nexus 3232C スイッチモデルに適したケーブルを使用して、e4e を C2 上の次に利用可能な 40 GbE ポート（ポート 1/8）に接続できます。

. C2上のノード側のすべてのポートを有効にします。
+
.例を表示
[%collapsible]
====
以下の例は、RCFでサポートされている構成を使用して、Nexus 3132Q-VクラスタスイッチC1およびC2でポート1～30を有効にする方法を示しています `NX3232C_RCF_v1.0_24p10g_26p100g.txt`：

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C2(config-if-range)# *no shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
----
====
. 各ノードで、2番目のクラスタ ポートであるe4eを有効にします。
+
`network port modify`

+
.例を表示
[%collapsible]
====
次の例は、各ノードで2番目のクラスタポートe4eが起動される様子を示しています。

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin true*
cluster::*> *network port modify -node n2 -port e4e -up-admin true*s
----
====
. 各ノードについて、移行されたすべてのクラスタ インターコネクト LIF を元に戻します： `network interface revert`
+
.例を表示
[%collapsible]
====
以下の例は、移行されたLIFがホームポートに戻される様子を示しています。

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver Cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus2*
----
====
. すべてのクラスタ インターコネクト ポートがホーム ポートに戻っていることを確認します。
+
`network interface show -role cluster`

+
 `Current Port`列にリストされているすべてのポートについて、 `Is Home`列に `true`の値が表示されている必要があります。表示されている値が `false`の場合、ポートはリバートされていません。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. すべてのクラスタ インターコネクト ポートが `up`状態であることを確認します：
+
`network port show -role cluster`

. 各クラスタ ポートが各ノードに接続されているクラスタ スイッチ ポート番号を表示します： `network device-discovery show`
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1          /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    C2                  Ethernet1/7      N3K-C3232C
n2          /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    C2                  Ethernet1/8      N3K-C3232C
----
====
. 検出および監視対象のクラスタ スイッチを表示します。
+
`system cluster-switch show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *system cluster-switch show*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.101      NX3232CV
Serial Number: FOX000001
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP

C2                          cluster-network     10.10.1.102      NX3232CV
Serial Number: FOX000002
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP 2 entries were displayed.
----
====
. スイッチレスクラスタ検出によって、スイッチレスクラスタオプションが無効に変更されたことを確認します。
+
`network options switchless-cluster show`

. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[ステップ16]] 自動ケース作成を抑制した場合は、AutoSupport メッセージを呼び出して再度有効にします：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.次の手順
link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを構成する"]。
