---
permalink: switch-cisco-3232c/replace-cluster-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3232c, cluster switch 
summary: 障害のある Cisco Nexus 3232C クラスタスイッチを交換します。この手順は無停止で実行できます。 
---
= Cisco Nexus 3232C クラスタスイッチの交換
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタの動作を中断することなく、障害のある Cisco Nexus 3232C クラスタスイッチを交換します。この無停止手順では、交換用スイッチを準備し、障害が発生したスイッチから接続を移行します。



[[review-requirements]]
== 要件の確認

.要件
既存のクラスターおよびネットワーク構成が以下の特性を備えていることを確認してください。

* Nexus 3232C クラスタインフラストラクチャは冗長構成となっており、両方のスイッチで完全に機能します。
+
Ciscoイーサネット スイッチ ページには、スイッチの最新の RCF および NX-OS バージョンが記載されています。

* すべてのクラスタポートは *up* の状態である必要があります。
* 両方のスイッチに管理接続が存在する必要があります。
* すべてのクラスタ論理インターフェース（LIF）は稼働状態であり、移行されていません。


交換用の Cisco Nexus 3232C スイッチには、以下の特徴があります：

* 管理ネットワーク接続は機能しています。
* 交換用スイッチへのコンソール アクセスが確立されています。
* 適切な RCF および NX-OS オペレーティング システム イメージがスイッチにロードされます。
* スイッチの初期カスタマイズが完了しました。


.詳細情報
以下を参照してください：

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^]
* link:http://hwu.netapp.com["Hardware Universe"^]
* link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["HWU にない機器をインストールするには、どのような追加情報が必要ですか?"^]




[[enable-console-logging]]
== コンソールログを有効にする

NetApp、使用しているデバイスでコンソール ログを有効にし、スイッチを交換するときに次のアクションを実行することを強くお勧めします。

* メンテナンス中はAutoSupport を有効のままにしておきます。
* メンテナンスの前後にAutoSupportメンテナンスをトリガーして、メンテナンス期間中のケース作成を無効にします。詳細については、このナレッジベース記事link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: スケジュールされたメンテナンス期間中の自動ケース作成を抑制する方法"^]を参照してください。
* すべての CLI セッションのセッション ログを有効にします。セッションログを有効にする方法については、このナレッジベースの記事の「セッション出力のログ記録」セクションを参照してください。link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAPシステムへの最適な接続を実現するための PuTTY の設定方法"^] 。




[[replace-the-switch]]
== スイッチを交換する

.タスク概要
この交換手順では、以下のシナリオについて説明します：

* このクラスタは当初、2台のNexus 3232Cクラスタスイッチ（CL1とCL2）に接続された4つのノードで構成されています。
* クラスタ スイッチ CL2 を C2 に交換する予定です（手順 1 ～ 21）：
+
** 各ノードにおいて、クラスタ スイッチ CL2 に接続されているクラスタ LIF を、クラスタ スイッチ CL1 に接続されているクラスタポートに移行します。
** クラスタ スイッチ CL2 のすべてのポートからケーブルを外し、交換用クラスタ スイッチ C2 の同じポートにケーブルを再接続します。
** 各ノードで、移行したクラスタLIFを元に戻します。




.例について
この交換手順では、2台目のNexus 3232CクラスタスイッチCL2を新しい3232CスイッチC2に交換します。

この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 4つのノードはn1、n2、n3、n4です。
* n1_clus1は、ノードn1のクラスタスイッチC1に接続された最初のクラスタ論理インターフェース（LIF）です。
* n1_clus2は、ノードn1のクラスタ スイッチCL2またはC2に接続された最初のクラスタLIFです。
* n1_clus3は、ノードn1のクラスタ スイッチC2に接続された2番目のLIFです。
* n1_clus4は、ノードn1用のクラスタスイッチCL1に接続された2番目のLIFです。


10 GbEポートと40/100 GbEポートの数は、link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® クラスタ ネットワークスイッチリファレンス設定ファイルのダウンロード"^]で入手可能な参照構成ファイル（RCF）で定義されています。

この置換手順の例では、4つのノードを使用します。2つのノードは4つの10 GBクラスタ インターコネクト ポート（e0a、e0b、e0c、e0d）を使用します。他の2つのノードは2つの40 GBクラスタ インターコネクト ポート（e4aとe4e）を使用します。お使いのプラットフォームに適したクラスタポートを確認するには、link:https://hwu.netapp.com["Hardware Universe"^]を参照してください。



[[step-1-display-and-migrate-the-cluster-ports-to-switch]]
=== ステップ1：クラスタ ポートを表示してスイッチに移行する

. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

+
[NOTE]
====
AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

====
. 設定内のデバイスに関する情報を表示します。
+
`network device-discovery show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface         Platform
----------- ------ ------------------- ----------------  ----------------
n1         /cdp
            e0a    CL1                 Ethernet1/1/1    N3K-C3232C
            e0b    CL2                 Ethernet1/1/1    N3K-C3232C
            e0c    CL2                 Ethernet1/1/2    N3K-C3232C
            e0d    CL1                 Ethernet1/1/2    N3K-C3232C

n2         /cdp
            e0a    CL1                 Ethernet1/1/3    N3K-C3232C
            e0b    CL2                 Ethernet1/1/3    N3K-C3232C
            e0c    CL2                 Ethernet1/1/4    N3K-C3232C
            e0d    CL1                 Ethernet1/1/4    N3K-C3232C

n3         /cdp
            e4a    CL1                 Ethernet1/7      N3K-C3232C
            e4e    CL2                 Ethernet1/7      N3K-C3232C

n4         /cdp
            e4a    CL1                 Ethernet1/8      N3K-C3232C
            e4e    CL2                 Ethernet1/8      N3K-C3232C
----
====
. 各クラスタ インターフェイスの管理ステータスまたは動作ステータスを決定します。
+
.. ネットワーク ポートの属性を表示します。
+
`network port show -role cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
(network port show)
Node: n1
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- ------------
e0a       Cluster      Cluster          up   9000 auto/10000  -
e0b       Cluster      Cluster          up   9000 auto/10000  -
e0c       Cluster      Cluster          up   9000 auto/10000  -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- ------------
e0a       Cluster      Cluster          up   9000  auto/10000 -
e0b       Cluster      Cluster          up   9000  auto/10000 -
e0c       Cluster      Cluster          up   9000  auto/10000 -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -
----
====
.. 論理インターフェース（LIF）に関する情報を表示します。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
             Logical    Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port   Home
----------- ---------- ---------- ------------------ ------------- ------- ---
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e0a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e0e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e0a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e0e     true
----
====
.. 検出されたクラスタ スイッチを表示します：
+
`system cluster-switch show`

+
.例を表示
[%collapsible]
====
以下の出力例は、クラスタ スイッチを表示したものです。

[listing, subs="+quotes"]
----
cluster::> *system cluster-switch show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                         cluster-network    10.10.1.101      NX3232C
        Serial Number: FOX000001
         Is Monitored: true
               Reason: None
     Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
       Version Source: CDP

CL2                         cluster-network    10.10.1.102      NX3232C
        Serial Number: FOX000002
         Is Monitored: true
               Reason: None
     Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
       Version Source: CDP
----
====


. 新しい Nexus 3232C スイッチに適切な RCF とイメージがインストールされていることを確認し、必要なサイトのカスタマイズを行ってください。
+
.. NetApp Support Site にアクセスしてください。
+
http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. *Cisco Ethernet Switches* のページに移動し、表に記載されている必要なソフトウェアバージョンを確認してください。
+
https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^]

.. 適切なバージョンのRCFをダウンロードしてください。
.. *概要* ページで *続行* をクリックし、ライセンス契約に同意してから、*ダウンロード* ページに移動してください。
.. *Cisco® クラスタおよび管理ネットワーク スイッチ リファレンス構成ファイル ダウンロード* ページから、適切なバージョンのイメージ ソフトウェアをダウンロードしてください。
+
link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® クラスタおよび管理ネットワークスイッチのリファレンス構成ファイルのダウンロード"^]



. クラスタ LIF を、交換用スイッチ C2 に接続されている物理ノードポートに移行します。
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ -source-node _node-name_ -destination-node _node-name_ -destination-port _port-name_`

+
.例を表示
[%collapsible]
====
次の例に示すように、すべてのクラスタ LIF を個別に移行する必要があります。

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1 -destination-
node n1 -destination-port e0a*
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus3 -source-node n1 -destination-
node n1 -destination-port e0d*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2 -destination-
node n2 -destination-port e0a*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus3 -source-node n2 -destination-
node n2 -destination-port e0d*
cluster::*> *network interface migrate -vserver Cluster -lif n3_clus2 -source-node n3 -destination-
node n3 -destination-port e4a*
cluster::*> *network interface migrate -vserver Cluster -lif n4_clus2 -source-node n4 -destination-
node n4 -destination-port e4a*
----
====
. クラスタポートのステータスとホーム指定を確認します：
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0a     false
            n1_clus3   up/up      10.10.0.3/24       n1            e0d     false
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0a     false
            n2_clus3   up/up      10.10.0.7/24       n2            e0d     false
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4a     false
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4a     false
----
====
. 元のスイッチ CL2 に物理的に接続されているクラスタ インターコネクト ポートをシャットダウンします：
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.例を表示
[%collapsible]
====
次の例は、すべてのノードでクラスタ インターコネクト ポートがシャットダウンされていることを示しています。

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin false*
cluster::*> *network port modify -node n1 -port e0c -up-admin false*
cluster::*> *network port modify -node n2 -port e0b -up-admin false*
cluster::*> *network port modify -node n2 -port e0c -up-admin false*
cluster::*> *network port modify -node n3 -port e4e -up-admin false*
cluster::*> *network port modify -node n4 -port e4e -up-admin false*
----
====
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none
.
.
n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
.
.
n3
.
.
.n4
.
.
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e0a    10.10.0.1
Cluster n1_clus2 n1        e0b    10.10.0.2
Cluster n1_clus3 n1        e0c    10.10.0.3
Cluster n1_clus4 n1        e0d    10.10.0.4
Cluster n2_clus1 n2        e0a    10.10.0.5
Cluster n2_clus2 n2        e0b    10.10.0.6
Cluster n2_clus3 n2        e0c    10.10.0.7
Cluster n2_clus4 n2        e0d    10.10.0.8
Cluster n3_clus1 n4        e0a    10.10.0.9
Cluster n3_clus2 n3        e0e    10.10.0.10
Cluster n4_clus1 n4        e0a    10.10.0.11
Cluster n4_clus2 n4        e0e    10.10.0.12
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8 10.10.0.9 10.10.0.10 10.10.0.11
10.10.0.12 Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 32 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.1 to Remote 10.10.0.9
    Local 10.10.0.1 to Remote 10.10.0.10
    Local 10.10.0.1 to Remote 10.10.0.11
    Local 10.10.0.1 to Remote 10.10.0.12
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.9
    Local 10.10.0.2 to Remote 10.10.0.10
    Local 10.10.0.2 to Remote 10.10.0.11
    Local 10.10.0.2 to Remote 10.10.0.12
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.9
    Local 10.10.0.3 to Remote 10.10.0.10
    Local 10.10.0.3 to Remote 10.10.0.11
    Local 10.10.0.3 to Remote 10.10.0.12
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.9
    Local 10.10.0.4 to Remote 10.10.0.10
    Local 10.10.0.4 to Remote 10.10.0.11
    Local 10.10.0.4 to Remote 10.10.0.12
Larger than PMTU communication succeeds on 32 path(s) RPC status:
8 paths up, 0 paths down (tcp check)
8 paths up, 0 paths down (udp check)
----
--
====


[[step-2-migrate-isls-to-switch-cl1-and-c2]]
=== 手順2：ISLをスイッチCL1およびC2に移行します

. クラスタ スイッチ CL1 のポート 1/31 と 1/32 をシャットダウンします。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]に記載されているガイドを参照してください。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface e1/31-32*
(CL1)(config-if-range)# *shutdown*
(CL1)(config-if-range)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. クラスタ スイッチ CL2 に接続されているすべてのケーブルを取り外し、すべてのノードについて交換用スイッチ C2 に再接続してください。
. クラスタ スイッチ CL2 のポート e1/31 と e1/32 からスイッチ間リンク（ISL）ケーブルを取り外し、交換用スイッチ C2 の同じポートに再接続します。
. クラスタ スイッチ CL1 の ISL ポート 1/31 および 1/32 を起動します。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]に記載されているガイドを参照してください。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface e1/31-32*
(CL1)(config-if-range)# *no shutdown*
(CL1)(config-if-range)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. CL1上でISLが稼働していることを確認してください。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]に記載されているガイドを参照してください。

+
ポートEth1/31とEth1/32は `(P)`を示しているはずです。これは、ISLポートがポートチャネルでアクティブになっていることを意味します。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
CL1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. クラスタ スイッチ C2 で ISL が稼働していることを確認します。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 Series NX-OS コマンドリファレンス"^]に記載されているガイドを参照してください。

+
.例を表示
[%collapsible]
====
ポートEth1/31とEth1/32には（P）と表示されるはずです。これは、両方のISLポートがポートチャネルでアクティブになっていることを意味します。

[listing, subs="+quotes"]
----
C2# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. すべてのノードで、交換用スイッチ C2 に接続されているすべてのクラスタ インターコネクト ポートを起動します。
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin true*
cluster::*> *network port modify -node n1 -port e0c -up-admin true*
cluster::*> *network port modify -node n2 -port e0b -up-admin true*
cluster::*> *network port modify -node n2 -port e0c -up-admin true*
cluster::*> *network port modify -node n3 -port e4e -up-admin true*
cluster::*> *network port modify -node n4 -port e4e -up-admin true*
----
====




[[step-3-revert-all-lifs-to-originally-assigned-ports]]
=== ステップ3：すべてのLIFを元の割り当てポートに戻す

. すべてのノード上で移行済みのクラスタ インターコネクト LIF をすべて元に戻します：
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.例を表示
[%collapsible]
====
次の例に示すように、すべてのクラスタ インターコネクト LIF を個別にリバートする必要があります。

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver cluster -lif n1_clus3*
cluster::*> *network interface revert -vserver cluster -lif n2_clus2*
cluster::*> *network interface revert -vserver cluster -lif n2_clus3*
Cluster::*> *network interface revert -vserver cluster -lif n3_clus2*
Cluster::*> *network interface revert -vserver cluster -lif n4_clus2*
----
====
. クラスタ インターコネクト ポートがホームに戻されたことを確認します：
+
`network interface show`

+
.例を表示
[%collapsible]
====
次の例は、 `Current Port`列にリストされているポートの、 `Is Home`列におけるステータスが `true`であるため、すべてのLIFが正常にリバートされたことを示しています。ポートの値が `false`の場合、LIFはリバートされていません。

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
             n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
             n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
             n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
             n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
             n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
             n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
             n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
             n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
             n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
             n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
             n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
             n4_clus2   up/up      10.10.0.12/24      n4            e4e     true
----
====
. クラスタポートが接続されていることを確認します。
+
`network port show -role cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000 auto/10000  -
e0b       Cluster      Cluster          up   9000 auto/10000  -
e0c       Cluster      Cluster          up   9000 auto/10000  -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
 --------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 -
e0b       Cluster      Cluster          up   9000  auto/10000 -
e0c       Cluster      Cluster          up   9000  auto/10000 -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
----
====
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none
.
.
n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
.
.
n3
.
.
.n4
.
.
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e0a    10.10.0.1
Cluster n1_clus2 n1        e0b    10.10.0.2
Cluster n1_clus3 n1        e0c    10.10.0.3
Cluster n1_clus4 n1        e0d    10.10.0.4
Cluster n2_clus1 n2        e0a    10.10.0.5
Cluster n2_clus2 n2        e0b    10.10.0.6
Cluster n2_clus3 n2        e0c    10.10.0.7
Cluster n2_clus4 n2        e0d    10.10.0.8
Cluster n3_clus1 n4        e0a    10.10.0.9
Cluster n3_clus2 n3        e0e    10.10.0.10
Cluster n4_clus1 n4        e0a    10.10.0.11
Cluster n4_clus2 n4        e0e    10.10.0.12
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8 10.10.0.9 10.10.0.10 10.10.0.11
10.10.0.12 Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 32 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.1 to Remote 10.10.0.9
    Local 10.10.0.1 to Remote 10.10.0.10
    Local 10.10.0.1 to Remote 10.10.0.11
    Local 10.10.0.1 to Remote 10.10.0.12
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.9
    Local 10.10.0.2 to Remote 10.10.0.10
    Local 10.10.0.2 to Remote 10.10.0.11
    Local 10.10.0.2 to Remote 10.10.0.12
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.9
    Local 10.10.0.3 to Remote 10.10.0.10
    Local 10.10.0.3 to Remote 10.10.0.11
    Local 10.10.0.3 to Remote 10.10.0.12
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.9
    Local 10.10.0.4 to Remote 10.10.0.10
    Local 10.10.0.4 to Remote 10.10.0.11
    Local 10.10.0.4 to Remote 10.10.0.12
Larger than PMTU communication succeeds on 32 path(s) RPC status:
8 paths up, 0 paths down (tcp check)
8 paths up, 0 paths down (udp check)
----
--
====


[[step-4-verify-all-ports-and-lif-are-correctly-migrated]]
=== ステップ4：すべてのポートとLIFが正しく移行されたことを確認します

. 以下のコマンドを入力して、設定内のデバイスに関する情報を表示します。
+
以下のコマンドは、どの順序で実行しても構いません。

+
** `network device-discovery show`
** `network port show -role cluster`
** `network interface show -role cluster`
** `system cluster-switch show`


+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    C1                 Ethernet1/1/1    N3K-C3232C
            e0b    C2                 Ethernet1/1/1    N3K-C3232C
            e0c    C2                 Ethernet1/1/2    N3K-C3232C
            e0d    C1                 Ethernet1/1/2    N3K-C3232C
n2         /cdp
            e0a    C1                 Ethernet1/1/3    N3K-C3232C
            e0b    C2                 Ethernet1/1/3    N3K-C3232C
            e0c    C2                 Ethernet1/1/4    N3K-C3232C
            e0d    C1                 Ethernet1/1/4    N3K-C3232C
n3         /cdp
            e4a    C1                 Ethernet1/7      N3K-C3232C
            e4e    C2                 Ethernet1/7      N3K-C3232C

n4         /cdp
            e4a    C1                 Ethernet1/8      N3K-C3232C
            e4e    C2                 Ethernet1/8      N3K-C3232C

cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000 auto/10000  -
e0b       Cluster      Cluster          up   9000 auto/10000  -
e0c       Cluster      Cluster          up   9000 auto/10000  -
e0d       Cluster      Cluster          up   9000 auto/10000  -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 -
e0b       Cluster      Cluster          up   9000  auto/10000 -
e0c       Cluster      Cluster          up   9000  auto/10000 -
e0d       Cluster      Cluster          up   9000  auto/10000 -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

cluster::*> *network interface show -role cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            nm1_clus1  up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4e     true

cluster::*> *system cluster-switch show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                          cluster-network   10.10.1.101      NX3232C
             Serial Number: FOX000001
              Is Monitored: true
                    Reason: None
          Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
            Version Source: CDP
CL2                          cluster-network   10.10.1.102      NX3232C
             Serial Number: FOX000002
              Is Monitored: true
                    Reason: None
          Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
            Version Source: CDP

C2                          cluster-network    10.10.1.103      NX3232C
             Serial Number: FOX000003
              Is Monitored: true
                    Reason: None
          Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
            Version Source: CDP 3 entries were displayed.
----
====
. 交換されたクラスタ スイッチ CL2 が自動的に削除されていない場合は、削除してください。
+
`system cluster-switch delete -device cluster-switch-name`

. 適切なクラスタスイッチが監視されていることを確認してください。
+
`system cluster-switch show`

+
.例を表示
[%collapsible]
====
次の例は、 `Is Monitored`状態が `true`であるため、クラスタ スイッチが監視されていることを示しています。

[listing, subs="+quotes"]
----
cluster::> *system cluster-switch show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                         cluster-network    10.10.1.101      NX3232C
            Serial Number: FOX000001
             Is Monitored: true
                   Reason: None
         Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
           Version Source: CDP

C2                          cluster-network    10.10.1.103      NX3232C
            Serial Number: FOX000002
             Is Monitored: true
                   Reason: None
         Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
           Version Source: CDP
----
====
. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.次の手順
スイッチを交換したら、link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを設定する"]できます。
