---
permalink: switch-cisco-3232c/required-documentation-3232c.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Cisco Nexus 3232C スイッチのインストールとメンテナンスについては、推奨されるすべてのドキュメントを必ず確認してください。 
---
= Cisco Nexus 3232Cスイッチのドキュメント要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C スイッチのインストールとメンテナンスについては、推奨されるすべてのドキュメントを必ず確認してください。



== スイッチのドキュメント

Cisco Nexus 3232Cスイッチをセットアップするには、次のドキュメントが必要です。 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Cisco Nexus 3000 シリーズ スイッチのサポート"^]ページ。

[cols="1,2"]
|===
| ドキュメント タイトル | 説明 


 a| 
_Nexus 3000 シリーズ ハードウェア インストール ガイド_
 a| 
サイト要件、スイッチ ハードウェアの詳細、およびインストール オプションに関する詳細情報を提供します。



 a| 
_Cisco Nexus 3000 シリーズ スイッチ ソフトウェア コンフィギュレーション ガイド_ (スイッチにインストールされている NX-OS リリースのガイドを選択してください)
 a| 
ONTAP操作用にスイッチを構成する前に必要な初期スイッチ構成情報を提供します。



 a| 
_Cisco Nexus 3000 シリーズ NX-OS ソフトウェア アップグレードおよびダウングレード ガイド_ (スイッチにインストールされている NX-OS リリースのガイドを選択してください)
 a| 
必要に応じて、スイッチをONTAP対応スイッチ ソフトウェアにダウングレードする方法に関する情報を提供します。



 a| 
_Cisco Nexus 3000 シリーズ NX-OS コマンド リファレンス マスター インデックス_
 a| 
Ciscoが提供するさまざまなコマンド リファレンスへのリンクを提供します。



 a| 
_Cisco Nexus 3000 MIB リファレンス_
 a| 
Nexus 3000 スイッチの管理情報ベース (MIB) ファイルについて説明します。



 a| 
_Nexus 3000 シリーズ NX-OS システム メッセージ リファレンス_
 a| 
Cisco Nexus 3000 シリーズ スイッチのシステム メッセージについて説明します。システム メッセージには情報メッセージと、リンク、内部ハードウェア、またはシステム ソフトウェアの問題の診断に役立つメッセージがあります。



 a| 
_Cisco Nexus 3000 シリーズ NX-OS リリース ノート (スイッチにインストールされている NX-OS リリースのノートを選択してください)_
 a| 
Cisco Nexus 3000 シリーズの機能、バグ、および制限について説明します。



 a| 
Cisco Nexus 6000、 Cisco Nexus 5000 シリーズ、 Cisco Nexus 3000 シリーズ、およびCisco Nexus 2000 シリーズの規制、コンプライアンス、および安全性に関する情報
 a| 
Nexus 3000 シリーズ スイッチに関する国際機関のコンプライアンス、安全性、および法定情報を提供します。

|===


== ONTAPシステムのドキュメント

ONTAPシステムをセットアップするには、オペレーティングシステムのバージョンに応じて次のドキュメントが必要です。 https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^] 。

[cols="1,2"]
|===
| Name | 説明 


 a| 
コントローラ固有の_インストールおよびセットアップ手順_
 a| 
NetAppハードウェアのインストール方法について説明します。



 a| 
ONTAPのドキュメント
 a| 
ONTAPリリースのあらゆる側面に関する詳細情報を提供します。



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
NetApp のハードウェア構成と互換性に関する情報を提供します。

|===


== レールキットとキャビネットのドキュメント

3232C CiscoスイッチをNetAppキャビネットにインストールするには、次のハードウェア ドキュメントを参照してください。

[cols="1,2"]
|===
| Name | 説明 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["42U システムキャビネット、ディープガイド"^]
 a| 
42U システム キャビネットに関連する FRU について説明し、メンテナンスおよび FRU 交換の手順を示します。



 a| 
link:install-cisco-nexus-3232c.html["NetAppキャビネットにCisco Nexus 3232Cスイッチをインストールする"^]
 a| 
Cisco Nexus 3232C スイッチを 4 ポストNetAppキャビネットにインストールする方法について説明します。

|===