---
permalink: switch-cisco-3232c/setup-switch.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: 必要な構成情報とドキュメントがまだない場合は、クラスタと管理ネットワーク スイッチを設定する前にその情報を収集する必要があります。 
---
= 3232Cクラスタスイッチを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C スイッチをセットアップおよび構成するには、次の手順に従ってください。

.開始する前に
* インストール サイトの HTTP、FTP、または TFTP サーバーにアクセスして、該当する NX-OS および参照構成ファイル (RCF) リリースをダウンロードします。
* 該当するNX-OSバージョンは、 https://software.cisco.com/download/home["Ciscoソフトウェアのダウンロード"^]ページ。
* 必要なクラスター ネットワークおよび管理ネットワーク スイッチのドキュメント。
+
見るlink:required-documentation-3232c.html["必要な書類"]詳細についてはこちらをご覧ください。

* 必要なコントローラのドキュメントとONTAP のドキュメント。
+
https://netapp.com/us/documenation/index.aspx["NetAppのドキュメント"^]

* 適用可能なライセンス、ネットワークおよび構成情報、およびケーブル。
* 完成したケーブル配線ワークシート。
* 適用可能なNetAppクラスタネットワークおよび管理ネットワークRCFは、 NetAppサポートサイトからダウンロードできます。 http://mysupport.netapp.com/["mysupport.netapp.com"^]受け取ったスイッチについて。すべてのCiscoクラスタ ネットワークおよび管理ネットワーク スイッチは、標準のCisco工場出荷時のデフォルト構成で出荷されます。これらのスイッチにも NX-OS ソフトウェアの最新バージョンが搭載されていますが、RCF はロードされていません。


.手順
. クラスター ネットワークと管理ネットワーク スイッチおよびコントローラーをラックに設置します。
+
[cols="1,2"]
|===
| ...をインストールする場合 | 操作 


 a| 
NetAppシステムキャビネット内のCisco Nexus 3232C
 a| 
NetAppキャビネットにスイッチをインストールする手順については、『 NetAppキャビネットへのCisco Nexus 3232C クラスタ スイッチとパススルー パネルのインストール』ガイドを参照してください。



 a| 
通信ラック内の機器
 a| 
スイッチ ハードウェア インストール ガイドおよびNetApp のインストールおよびセットアップ手順に記載されている手順を参照してください。

|===
. 完成した配線ワークシートを使用して、クラスター ネットワークと管理ネットワーク スイッチをコントローラーに配線します。
. クラスター ネットワークと管理ネットワークのスイッチとコントローラーの電源をオンにします。
. クラスター ネットワーク スイッチの初期構成を実行します。
+
スイッチを初めて起動するときに、次の初期設定の質問に適切な回答を入力してください。サイトのセキュリティ ポリシーによって、有効にする応答とサービスが定義されます。

+
[cols="1,2"]
|===
| プロンプト | 応答 


 a| 
自動プロビジョニングを中止して通常のセットアップを続行しますか?  （はい/いいえ）
 a| 
「はい」と答えます。デフォルトは「いいえ」です。



 a| 
安全なパスワード標準を強制しますか?  （はい/いいえ）
 a| 
「はい」と答えます。デフォルトは「はい」です。



 a| 
管理者のパスワードを入力してください。
 a| 
デフォルトのパスワードは「`admin`」です。新しい強力なパスワードを作成する必要があります。弱いパスワードは拒否される可能性があります。



 a| 
基本設定ダイアログに入りますか?  （はい/いいえ）
 a| 
スイッチの初期設定では「*はい*」と応答します。



 a| 
別のログインアカウントを作成しますか?  （はい/いいえ）
 a| 
答えは、代替管理者に関するサイトのポリシーによって異なります。デフォルトは*いいえ*です。



 a| 
読み取り専用 SNMP コミュニティ文字列を構成しますか?  （はい/いいえ）
 a| 
「いいえ」と答えます。デフォルトは「いいえ」です。



 a| 
読み取り/書き込み SNMP コミュニティ文字列を構成しますか?  （はい/いいえ）
 a| 
「いいえ」と答えます。デフォルトは「いいえ」です。



 a| 
スイッチ名を入力します。
 a| 
スイッチ名は 63 文字の英数字に制限されます。



 a| 
アウトオブバンド (mgmt0) 管理構成を続行しますか?  （はい/いいえ）
 a| 
そのプロンプトに対して「*yes*」（デフォルト）と応答します。  mgmt0 IPv4 アドレス: プロンプトで、IP アドレス ip_address を入力します。



 a| 
デフォルトゲートウェイを設定しますか?  （はい/いいえ）
 a| 
「はい」と答えます。  default-gateway: プロンプトの IPv4 アドレスに、default_gateway を入力します。



 a| 
高度な IP オプションを構成しますか?  （はい/いいえ）
 a| 
「いいえ」と答えます。デフォルトは「いいえ」です。



 a| 
Telnet サービスを有効にしますか?  （はい/いいえ）
 a| 
「いいえ」と答えます。デフォルトは「いいえ」です。



 a| 
SSH サービスを有効にしましたか?  （はい/いいえ）
 a| 
「はい」と答えます。デフォルトは「はい」です。


NOTE: ログ収集機能のために Ethernet Switch Health Monitor (CSHM) を使用する場合は、SSH が推奨されます。セキュリティを強化するには、SSHv2も推奨されます。



 a| 
生成する SSH キーのタイプ (dsa/rsa/rsa1) を入力します。
 a| 
デフォルトは *rsa* です。



 a| 
キービット数（1024～2048）を入力します。
 a| 
1024～2048 のキービット数を入力します。



 a| 
NTP サーバーを設定しますか?  （はい/いいえ）
 a| 
「いいえ」と答えます。デフォルトは「いいえ」です。



 a| 
デフォルトのインターフェース層（L3/L2）を設定します。
 a| 
*L2*で応答します。デフォルトは L2 です。



 a| 
デフォルトのスイッチ ポート インターフェイスの状態 (shut/noshut) を設定します。
 a| 
*noshut* と応答します。デフォルトは noshut です。



 a| 
CoPP システム プロファイル (厳密/中程度/寛容/高密度) を設定します。
 a| 
*strict* で応答します。デフォルトは厳密です。



 a| 
設定を編集しますか?  （はい/いいえ）
 a| 
この時点で新しい構成が表示されるはずです。入力した設定を確認し、必要な変更を加えます。設定に満足している場合は、プロンプトに対して「*no*」と応答します。構成設定を編集する場合は、「はい」と答えてください。



 a| 
この設定を使用して保存しますか?  （はい/いいえ）
 a| 
設定を保存するには、「*はい*」と応答します。これにより、キックスタート イメージとシステム イメージが自動的に更新されます。


NOTE: この段階で設定を保存しないと、次回スイッチを再起動したときに変更は有効になりません。

|===
. セットアップの最後に表示される画面で選択した構成を確認し、必ず構成を保存してください。
. クラスタネットワークスイッチのバージョンを確認し、必要に応じて、 NetAppがサポートするバージョンのソフトウェアをスイッチにダウンロードします。 https://software.cisco.com/download/home["Ciscoソフトウェアのダウンロード"^]ページ。


.次の手順
スイッチの設定が完了したら、 link:prepare-install-cisco-nexus-3232c.html["NX-OSとRCFのインストールの準備"]。
