---
permalink: switch-cisco-3232c/setup_worksheet_3232c.html 
sidebar: sidebar 
keywords: cable worksheet, Cisco NX 3232C 
summary: サポートされているプラットフォームを文書化する場合は、完成したサンプル配線ワークシートをガイドとして使用して、空の配線ワークシートを完成させる必要があります。各スイッチは、単一の 100GbE、40GbE ポート、または 4 x 10GbE ポートとして構成できます。 
---
= Cisco Nexus 3232C の配線ワークシート一式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サポートされているプラットフォームを文書化する場合は、このページの PDF をダウンロードし、ケーブル接続ワークシートを完成させてください。

サンプル配線ワークシートには、スイッチからコントローラへの推奨ポート割り当ての例が示されています。空白のワークシートには、クラスターの設定に使用できるテンプレートが用意されています。

各スイッチは、単一の 100GbE、40GbE ポート、または 4 x 10GbE ポートとして構成できます。



== ケーブル接続ワークシートの例

各スイッチ ペアのサンプル ポート定義は次のとおりです。

[cols="1, 1, 1, 1"]
|===
2+| クラスタスイッチA 2+| クラスタスイッチB 


| スイッチ ポート | ノードとポートの使用状況 | スイッチ ポート | ノードとポートの使用状況 


 a| 
1
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
1
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
2
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
2
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
3
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
3
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
4
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
4
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
5
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
5
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
6
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
6
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
7
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
7
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
8
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
8
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
9
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
9
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
10
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
10
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
11
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
11
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
12
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
12
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
13
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
13
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
14
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
14
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
15
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
15
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
16
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
16
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
17
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
17
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
18
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード
 a| 
18
 a| 
4x10GbE/4x25GbEまたは40/100GbEノード



 a| 
19
 a| 
40G/100GbEノード19
 a| 
19
 a| 
40G/100GbEノード19



 a| 
20
 a| 
40G/100GbEノード20
 a| 
20
 a| 
40G/100GbEノード20



 a| 
21
 a| 
40G/100GbEノード21
 a| 
21
 a| 
40G/100GbEノード21



 a| 
22
 a| 
40G/100GbEノード22
 a| 
22
 a| 
40G/100GbEノード22



 a| 
23
 a| 
40G/100GbEノード23
 a| 
23
 a| 
40G/100GbEノード23



 a| 
24
 a| 
40G/100GbEノード24
 a| 
24
 a| 
40G/100GbEノード24



 a| 
25～30
 a| 
リザーブ
 a| 
25～30
 a| 
リザーブ



 a| 
31
 a| 
スイッチBポート31への100GbE ISL
 a| 
31
 a| 
スイッチAポート31への100GbE ISL



 a| 
32
 a| 
スイッチBポート32への100GbE ISL
 a| 
32
 a| 
スイッチAポート32への100GbE ISL

|===


== 空白の配線ワークシート

空白の配線ワークシートを使用して、クラスター内のノードとしてサポートされているプラットフォームを文書化できます。  _サポートされているクラスタ接続_セクション https://hwu.netapp.com["Hardware Universe"^]プラットフォームで使用されるクラスター ポートを定義します。

[cols="1, 1, 1, 1"]
|===
2+| クラスタスイッチA 2+| クラスタスイッチB 


| スイッチ ポート | ノード/ポートの使用状況 | スイッチ ポート | ノード/ポートの使用状況 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11
 a| 
 a| 
11
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25～30
 a| 
リザーブ
 a| 
25～30
 a| 
リザーブ



 a| 
31
 a| 
スイッチBポート31への100GbE ISL
 a| 
31
 a| 
スイッチAポート31への100GbE ISL



 a| 
32
 a| 
スイッチBポート32への100GbE ISL
 a| 
32
 a| 
スイッチAポート32への100GbE ISL

|===
.次の手順
link:install-switch-3232c.html["スイッチをインストールする"] 。
