---
permalink: switch-cisco-3232c/setup_worksheet_3232c.html 
sidebar: sidebar 
keywords: cable worksheet, Cisco NX 3232C 
summary: サポート対象のプラットフォームを文書化する場合は、入力済みのケーブル接続ワークシートの例を参考にして、空白のケーブル接続ワークシートに記入する必要があります。各スイッチは、単一の 100GbE ポート、 40GbE ポート、または 4 × 10GbE ポートとして設定できます。 
---
= Cisco Nexus 3232Cケーブル接続ワークシートに記入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サポートされるプラットフォームを文書化する場合は、このページのPDFをダウンロードしてケーブル接続ワークシートに記入します。

ケーブル接続ワークシートの例には、スイッチからコントローラへの推奨されるポート割り当ての例が示されています。空白のワークシートには、クラスタのセットアップに使用できるテンプレートが用意されています。

各スイッチは、単一の 100GbE ポート、 40GbE ポート、または 4 × 10GbE ポートとして設定できます。



== ケーブル接続ワークシートの例

各スイッチペアのポート定義の例を次に示します。

[cols="1, 1, 1, 1"]
|===
2+| クラスタスイッチ A 2+| クラスタスイッチ B 


| スイッチポート | 使用するノードとポート | スイッチポート | 使用するノードとポート 


 a| 
1.
 a| 
4 × 10G / 40G / 100G ノード
 a| 
1.
 a| 
4 × 10G / 40G / 100G ノード



 a| 
2.
 a| 
4 × 10G / 40G / 100G ノード
 a| 
2.
 a| 
4 × 10G / 40G / 100G ノード



 a| 
3.
 a| 
4 × 10G / 40G / 100G ノード
 a| 
3.
 a| 
4 × 10G / 40G / 100G ノード



 a| 
4.
 a| 
4 × 10G / 40G / 100G ノード
 a| 
4.
 a| 
4 × 10G / 40G / 100G ノード



 a| 
5.
 a| 
4 × 10G / 40G / 100G ノード
 a| 
5.
 a| 
4 × 10G / 40G / 100G ノード



 a| 
6.
 a| 
4x10G / 40G / 100G ノード
 a| 
6.
 a| 
4x10G / 40G / 100G ノード



 a| 
7.
 a| 
4 × 10G / 40G / 100G ノード
 a| 
7.
 a| 
4 × 10G / 40G / 100G ノード



 a| 
8.
 a| 
4 × 10G / 40G / 100G ノード
 a| 
8.
 a| 
4 × 10G / 40G / 100G ノード



 a| 
9.
 a| 
4 × 10G / 40G / 100G ノード
 a| 
9.
 a| 
4 × 10G / 40G / 100G ノード



 a| 
10.
 a| 
4 × 10G / 40G / 100G ノード
 a| 
10.
 a| 
4 × 10G / 40G / 100G ノード



 a| 
11.
 a| 
4 × 10G / 40G / 100G ノード
 a| 
11.
 a| 
4 × 10G / 40G / 100G ノード



 a| 
12.
 a| 
4 × 10G / 40G / 100G ノード
 a| 
12.
 a| 
4 × 10G / 40G / 100G ノード



 a| 
13
 a| 
4 × 10G / 40G / 100G ノード
 a| 
13
 a| 
4 × 10G / 40G / 100G ノード



 a| 
14
 a| 
4 × 10G / 40G / 100G ノード
 a| 
14
 a| 
4 × 10G / 40G / 100G ノード



 a| 
15
 a| 
4 × 10G / 40G / 100G ノード
 a| 
15
 a| 
4 × 10G / 40G / 100G ノード



 a| 
16
 a| 
4 × 10G / 40G / 100G ノード
 a| 
16
 a| 
4 × 10G / 40G / 100G ノード



 a| 
17
 a| 
4 × 10G / 40G / 100G ノード
 a| 
17
 a| 
4 × 10G / 40G / 100G ノード



 a| 
18
 a| 
4 × 10G / 40G / 100G ノード
 a| 
18
 a| 
4 × 10G / 40G / 100G ノード



 a| 
19
 a| 
40G / 100G ノード 19
 a| 
19
 a| 
40G / 100G ノード 19



 a| 
20
 a| 
40G / 100G ノード 20
 a| 
20
 a| 
40G / 100G ノード 20



 a| 
21
 a| 
40G / 100G ノード 21
 a| 
21
 a| 
40G / 100G ノード 21



 a| 
22
 a| 
40G / 100G ノード 22
 a| 
22
 a| 
40G / 100G ノード 22



 a| 
23
 a| 
40G / 100G ノード 23
 a| 
23
 a| 
40G / 100G ノード 23



 a| 
24
 a| 
40G / 100G ノード 24
 a| 
24
 a| 
40G / 100G ノード 24



 a| 
25 ～ 30
 a| 
予約済み
 a| 
25 ～ 30
 a| 
予約済み



 a| 
31.
 a| 
100G ISL 経由でスイッチ B ポート 31
 a| 
31.
 a| 
100G ISL 経由でスイッチ A ポート 31



 a| 
32
 a| 
100G ISL 経由でスイッチ B ポート 32
 a| 
32
 a| 
100G ISL 経由でスイッチ A ポート 32

|===


== 空白のケーブル接続ワークシート

空白のケーブル接続ワークシートを使用して、クラスタ内のノードとしてサポートされるプラットフォームを文書化できます。のサポートされるクラスタ接続セクション https://["Hardware Universe"^] プラットフォームで使用されるクラスタポートを定義します。

[cols="1, 1, 1, 1"]
|===
2+| クラスタスイッチ A 2+| クラスタスイッチ B 


| スイッチポート | 使用するノード / ポート | スイッチポート | 使用するノード / ポート 


 a| 
1.
 a| 
 a| 
1.
 a| 



 a| 
2.
 a| 
 a| 
2.
 a| 



 a| 
3.
 a| 
 a| 
3.
 a| 



 a| 
4.
 a| 
 a| 
4.
 a| 



 a| 
5.
 a| 
 a| 
5.
 a| 



 a| 
6.
 a| 
 a| 
6.
 a| 



 a| 
7.
 a| 
 a| 
7.
 a| 



 a| 
8.
 a| 
 a| 
8.
 a| 



 a| 
9.
 a| 
 a| 
9.
 a| 



 a| 
10.
 a| 
 a| 
10.
 a| 



 a| 
11.
 a| 
 a| 
11.
 a| 



 a| 
12.
 a| 
 a| 
12.
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25 ～ 30
 a| 
予約済み
 a| 
25 ～ 30
 a| 
予約済み



 a| 
31.
 a| 
100G ISL 経由でスイッチ B ポート 31
 a| 
31.
 a| 
100G ISL 経由でスイッチ A ポート 31



 a| 
32
 a| 
100G ISL 経由でスイッチ B ポート 32
 a| 
32
 a| 
100G ISL 経由でスイッチ A ポート 32

|===