---
permalink: switch-cisco-3232c/smart-call-home-3232c.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Cisco Nexus 3232C スイッチをクラスタスイッチとして AFF または FAS クラスタで使用できます。 
---
= Smart Call Homeの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Smart Call Home を使用するには、電子メールを使用して Smart Call Home システムと通信するようにクラスター ネットワーク スイッチを構成する必要があります。さらに、オプションでクラスタ ネットワーク スイッチを設定して、Cisco の組み込み Smart Call Home サポート機能を利用することもできます。

Cisco の Smart Call Home は、ネットワーク上のハードウェアおよびソフトウェアコンポーネントを監視します。重大なシステム構成上の問題が発生した場合、メールによる通知が生成され、宛先プロファイルに設定されているすべての受信者にアラートが送信されます。

[NOTE]
====
ONTAP は、AFX クラスタスイッチを監視するためのイーサネットスイッチヘルスモニタリング（CSHM）をサポートするとともに、スイッチ診断ログを収集する機能も備えています。

Cisco の Smart Call Home は、スイッチで発生する可能性のあるあらゆる問題を解決するために、プロアクティブなサポートを提供するオプションです。

====
Smart Call Home を使用する前に、次の要件に注意してください。

* 電子メール サーバーを設置する必要があります。
* スイッチは電子メール サーバーに IP 接続できる必要があります。
* 連絡先名 (SNMP サーバーの連絡先)、電話番号、住所情報を設定する必要があります。これは、受信したメッセージの送信元を特定するために必要です。
* CCO ID は、会社の適切なCisco SMARTnet サービス契約に関連付ける必要があります。
* デバイスを登録するには、 Cisco SMARTnet サービスが稼働している必要があります。


その http://www.cisco.com/c/en/us/products/switches/index.html["Ciscoサポートサイト"^]Smart Call Home を構成するためのコマンドに関する情報が含まれています。

スマートコールホームは、新規システムのインストールおよびセットアップ時、またはインストール後に設定できます。
