---
permalink: switch-cisco-3232c/task-upgrade-nx-os-software-and-rcfs-on-cisco-nexus-3232c-storage-switches.html 
sidebar: sidebar 
keywords: upgrade, cisco nexus, 3232c storage switch 
summary: Cisco NX-OS ソフトウェアおよびリファレンス構成ファイル（ RCF ）は、 Cisco Nexus 3232C ストレージスイッチでアップグレードできます。 
---
= Cisco Nexus 3232C ストレージスイッチをアップグレードする
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco NX-OS ソフトウェアおよびリファレンス構成ファイル（ RCF ）は、 Cisco Nexus 3232C ストレージスイッチでアップグレードできます。

ストレージスイッチで NX-OS ソフトウェアと RCF をアップグレードする前に、次の条件が満たされている必要があります。

* スイッチが完全に機能している必要があります（ログにエラーがないか、または同様の問題が発生していないか）。
* NX-OS だけをインストールして現在の RCF バージョンをそのまま使用する場合は、目的のブートイメージを反映するように、 RCF で必要なブート変数を確認または設定しておく必要があります。
+
現在のブートイメージを反映するようにブート変数を変更する必要がある場合は、あとでリブートしたときに正しいバージョンがインスタンス化されるように、 RCF を再適用する前に変更する必要があります。

* で提供されているソフトウェアとアップグレードのガイドを参照しておく必要があります http://www.cisco.com/en/US/products/ps9670/prod_installation_guides_list.html["Cisco Nexus 3000 シリーズスイッチ"^] Cisco ストレージのアップグレードおよびダウングレード手順の詳細なドキュメントについては、ページを参照してください。
* 10GbE ポートと 40 / 100GbE ポートの数は、で使用可能なリファレンス構成ファイル（ RCF ）に定義されています https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco ® イーサネットスイッチ"^] ページ


* 手順 の概要： *

* ** I.スイッチおよびポート（<<step1_upgrade_3232c,手順 1.>>- <<step4_upgrade_3232c,4.>>） **
* ** IIRCF を Cisco スイッチ S2 にコピーします（<<step5_upgrade_3232c,手順 5.>> - <<step8_upgrade_3232c,8.>>） **
* ** III.NX-OS イメージを Cisco スイッチ S2 にダウンロードし、（<<step9_upgrade_3232c,手順 9.>> - <<step12_upgrade_3232c,12.>>） **
* ** IVスイッチとポートのヘルスステータスを再確認する（<<step13_upgrade_3232c,手順 13>> - <<step15_upgrade_3232c,15>>） **
* ** V.繰り返します <<step1_upgrade_3232c,手順 1.>>- <<step17_upgrade_3232c,17>> Cisco スイッチ S1.** の場合


この手順 の例では、 2 つのノードを使用します。 node1 には 2 つのストレージポート、 node2 には 2 つのストレージポートがあります。を参照してください link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] をクリックして、プラットフォームの正しいストレージポートを確認します。


NOTE: コマンド出力は、 ONTAP のリリースによって異なる場合があります。

この手順の例では、スイッチとノードで次の命名法を使用しています。

* 2 つのストレージスイッチの名前は S1 と S2 です。
* ノードは node1 と node2 になります。



NOTE: 手順 では、 ONTAP コマンドと Cisco Nexus 3000 シリーズスイッチコマンドの両方を使用する必要があります。特に明記されていないかぎり、 ONTAP コマンドを使用します。

.手順
. [[stp1_upgrade_32c]] このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。 "system node AutoSupport invoke -node * -type all -message MAINT= xh`
+
_x_ は、メンテナンス時間の長さ（時間単位）です。

+

NOTE: AutoSupport メッセージはテクニカルサポートにこのメンテナンスタスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

. ストレージスイッチが使用可能であることを確認します。「 system switch ethernet show
+
[listing]
----
storage::*> system switch ethernet show
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
S1
                            storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

S2
                            storage-network    172.17.227.6     NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

2 entries were displayed.
storage::*>
----
. ノードポートが正常で動作していることを確認します。「 storage port show -port-type enet
+
[listing]
----
storage::*> storage port show -port-type ENET
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
. [[step4_upgrade_32c]] クラスタにストレージスイッチやケーブル接続の問題がないことを確認します : "system health alert show-instance
+
[listing]
----
storage::*> system health alert show -instance
There are no entries matching your query.
----
. [[step5_upgrade_32c]] スイッチ S2 上の RCF を、 FTP 、 HTTP 、 TFTP 、 SFTP 、 SCP のいずれかの転送プロトコルを使用してスイッチのブートフラッシュにコピーします。
+
Cisco コマンドの詳細については、『』の該当するガイドを参照してください https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 シリーズ NX-OS コマンドリファレンス"^]。

+
次に、 HTTP を使用して、 RCF をスイッチ S2 上のブートフラッシュにコピーする例を示します。

+
[listing]
----
S2# copy http://172.16.10.1//cfg/Nexus_3232C_RCF_v1.6-Storage.txt bootflash: vrf management
% Total    % Received % Xferd  Average  Speed   Time    Time     Time                          Current
                               Dload    Upload  Total   Spent    Left                          Speed
  100        3254       100    3254     0       0       8175     0 --:--:-- --:--:-- --:--:–   8301
Copy complete, now saving to disk (please wait)...
Copy complete.
S2#
----
. 以前にダウンロードした RCF を bootflash:`copy bootflash:` に適用します
+
次の例は、スイッチ S2 にインストールされている RCF ファイル「 Nexus_32323_RCF v1.6 -Storage.txt 」を示しています。

+
[listing]
----
S2# copy Nexus_3232C_RCF_v1.6-Storage.txt running-config echo-commands
----
. RCF ファイルが正しい新しいバージョンであることを確認します。 'how running-config
+
出力をチェックして正しい RCF があることを確認する場合は、次の情報が正しいことを確認してください。

+
** RCF バナー
** ノードとポートの設定
** 出力のカスタマイズは、サイトの設定によって異なります。ポートの設定を確認し、インストールした RCF に固有の変更がないかリリースノートを参照してください。


+
[NOTE]
====
「 show banner motd 」コマンドのバナー出力では、「重要な注意事項」セクションの説明を読んで、スイッチの適切な設定と動作を確認する必要があります。

====
+
[listing]
----
S2# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : Cisco Nexus 3232C
* Filename : Nexus_3232C_RCF_v1.6-Storage.txt
* Date     : Oct-20-2020
* Version  : v1.6
*
* Port Usage : Storage configuration
* Ports  1-32: Controller and Shelf Storage Ports
* Ports 33-34: Disabled
*
* IMPORTANT NOTES*
* - This RCF utilizes QoS and requires TCAM re-configuration, requiring RCF
*   to be loaded twice with the Storage Switch rebooted in between.
*
* - Perform the following 4 steps to ensure proper RCF installation:
*
*   (1) Apply RCF first time, expect following messages:
*       - Please save config and reload the system...
*       - Edge port type (portfast) should only be enabled on ports...
*       - TCAM region is not configured for feature QoS class IPv4 ingress...
*
*   (2) Save running-configuration and reboot Cluster Switch
*
*   (3) After reboot, apply same RCF second time and expect following messages:
*       - % Invalid command at '^' marker
*       - Syntax error while parsing...
*
*   (4) Save running-configuration again
******************************************************************************
S2#
----
. [[step8_upgrade_32c]] ソフトウェアのバージョンとスイッチの設定が正しいことを確認したら、「 running-config 」ファイルをスイッチ S2 の「 startup-config 」ファイルにコピーします。
+
Cisco コマンドの詳細については、『』の該当するガイドを参照してください https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 シリーズ NX-OS コマンドリファレンス"^]。

+
次に 'running-config' ファイルが 'artup-config ファイルに正常にコピーされた例を示します

+
[listing]
----
S2# copy running-config startup-config
[########################################] 100% Copy complete.
----
. [[step9_upgrade_32c]] NX-OS イメージをスイッチ S2 にダウンロードします。
. システムイメージをインストールして、次回スイッチ S2 をリブートするときに新しいバージョンがロードされるようにします。
+
次の出力に示すように、スイッチは 10 秒後に新しいイメージでリブートされます。

+
[listing]
----
S2# install all nxos bootflash:nxos.9.3.4.bin
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.3.4.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  bootable          Impact  Install-type  Reason
------  --------  --------------  ------------  ------
     1       yes      disruptive         reset  default upgrade is not hitless


Images will be upgraded according to following table:
Module       Image                  Running-Version(pri:alt)           New-Version  Upg-Required
------  ----------  ----------------------------------------  --------------------  ------------
     1        nxos                                    9.3(3)                9.3(4)           yes
     1        bios     v08.37(01/28/2020):v08.23(09/23/2015)    v08.38(05/29/2020)            no


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n]  y
input string too long
Do you want to continue with the installation (y/n)?  [n] y

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS


Finishing the upgrade, switch will reboot in 10 seconds.
S2#
----
. 設定を保存します。
+
Cisco コマンドの詳細については、『』の該当するガイドを参照してください https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 シリーズ NX-OS コマンドリファレンス"^]。

+
次の例に示すように、システムをリブートするように求められます。

+
[listing]
----
S2# copy running-config startup-config
[########################################] 100% Copy complete.
S2# reload
This command will reboot the system. (y/n)?  [n] y
----
. [[step12_upgrade_32c]] 新しい NX-OS バージョン番号がスイッチにあることを確認します。
+
[listing]
----
S2# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.38
 NXOS: version 9.3(4)
  BIOS compile time:  05/29/2020
  NXOS image file is: bootflash:///nxos.9.3.4.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 02:28:31]


Hardware
  cisco Nexus3000 C3232C Chassis (Nexus 9000 Series)
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K

  Device name: S2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)

Last reset at 157524 usecs after Mon Nov  2 18:32:06 2020
  Reason: Reset due to upgrade
  System version: 9.3(3)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

S2#
----
. [[step13_upgrade_32c]] 再起動後にストレージ・スイッチが使用可能であることを再確認します :"system switch ethernet show
+
[listing]
----
storage::*> system switch ethernet show
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
S1
                            storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

S2
                            storage-network    172.17.227.6     NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

2 entries were displayed.
storage::*>
----
. スイッチ・ポートが正常であり ' 再起動後に動作可能であることを確認します storage port show -port-type enet
+
[listing]
----
storage::*> storage port show -port-type ENET
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
. [[step15_upgrade_32c]] クラスタにストレージスイッチやケーブル接続に問題がないことを再確認します : "system health alert show-instance `
+
[listing]
----
storage::*> system health alert show -instance
There are no entries matching your query.
----
. 手順 を繰り返して、スイッチ S1 の NX-OS ソフトウェアと RCF をアップグレードします。
. [[step17_upgrade_32c]] 自動ケース作成を抑制した場合は、 AutoSupport メッセージを呼び出すことで再度有効にします。 "system node AutoSupport invoke -node * -type all -message MAINT=end`

