---
permalink: switch-cisco-3232c/task-steps-to-replace-a-cisco-nexus-3232c-storage-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus, 3232c storage switch 
summary: 障害が発生した Cisco Nexus 3232C ストレージスイッチは、特定の順序でタスクを実行することで、無停止で交換できます。 
---
= Cisco Nexus 3232C ストレージスイッチを交換する手順
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害が発生した Cisco Nexus 3232C ストレージスイッチは、特定の順序でタスクを実行することで、無停止で交換できます。

既存のネットワーク構成には、次のような特徴があります。

* Cisco Ethernet Switches のページに、スイッチ上の最新の RCF および NX-OS バージョンが含まれています。
* 両方のスイッチで管理接続が確立されている必要があります。
+
[NOTE]
====
スイッチの交換が必要かどうかを確認するために、すべてのトラブルシューティング手順が完了していることを確認します。

====


交換用 Cisco Nexus 3232C スイッチには、次の特性が必要です。

* 管理ネットワーク接続が機能している必要があります。
* 交換用スイッチへのコンソールアクセスが確立されている必要があります。
* 適切な RCF および NX-OS オペレーティングシステムイメージをスイッチにロードする必要があります。
* スイッチの初期カスタマイズが完了している必要があります。


* 手順 の概要： *

* * 交換するスイッチが S2 であることを確認します（手順 ,1.-,5.*
* * スイッチ S2 からケーブルを外します ,（手順 6 ）*
* * ケーブルをスイッチ NS2 に接続し直します（手順 ,7.*
* * スイッチ NS2 のすべてのデバイス構成を確認します ( 手順 ,8.-,10.*
* この手順 は、 2 番目の Nexus 3232C ストレージスイッチ S2 を新しい 3232C スイッチ NS2 に置き換えます。
* 2 つのノードは node1 と node2 になります。


.手順
. [[1]] このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージ「 system node AutoSupport invoke -node * -type all -message MAINT=xh` 」を呼び出して、ケースの自動作成を抑制します
+
_x_ は、メンテナンス時間の長さ（時間単位）です。

+
[NOTE]
====
AutoSupport メッセージはテクニカルサポートにこのメンテナンスタスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

====
. ストレージノードポートのヘルスステータスをチェックして、ストレージスイッチ S1 に接続されていることを確認します。「 storage port show -port-type enet 」
+
[listing]
----
storage::*> storage port show -port-type ENET
                                      Speed                     VLAN
Node               Port Type  Mode    (Gb/s) State    Status      ID
------------------ ---- ----- ------- ------ -------- --------- ----
node1
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
node2
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
----
. ストレージ・スイッチ S1 が使用可能であることを確認します： network device-discovery show
+
[listing]
----
storage::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- ----------------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
----
. 動作中のスイッチで「 show lldp neighbors 」コマンドを実行して、ノードとすべてのシェルフの両方が表示されることを確認します。「 show lldp neighbors
+
[listing]
----
S1# show lldp neighbors
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID               Local Intf      Hold-time  Capability  Port ID
node1                   Eth1/1          121        S           e3a
node2                   Eth1/2          121        S           e3a
SHFGD2008000011         Eth1/5          121        S           e0a
SHFGD2008000011         Eth1/6          120        S           e0a
SHFGD2008000022         Eth1/7          120        S           e0a
SHFGD2008000022         Eth1/8          120        S           e0a
----
. [f5] ストレージ・システムのシェルフ・ポートを確認します storage shelf port show -fields remote-device 、 remote-port
+
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port

shelf  id  remote-port  remote-device
-----  --  -----------  -------------
3.20   0   Ethernet1/5  S1
3.20   1   -            -
3.20   2   Ethernet1/6  S1
3.20   3   -            -
3.30   0   Ethernet1/7  S1
3.20   1   -            -
3.30   2   Ethernet1/8  S1
3.20   3   -            -
----
. [[6] ] ストレージスイッチ S2 に接続されているすべてのケーブルを取り外します。
. [7] 交換用スイッチ NS2 にすべてのケーブルを再接続します。
. [8]] ストレージ・ノード・ポートの正常性状態を再確認します storage port show -port type enet
+
[listing]
----
storage::*> storage port show -port-type ENET
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ------------ ---
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
. 両方のスイッチが使用可能であることを確認します。「 network device-discovery show 」を参照してください
+
[listing]
----
storage::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/1       NX3232C
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
            e7b    NS2                       Ethernet1/1       -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/2       NX3232C
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
            e7b    NS2                       Ethernet1/2       -
----
. [ten]] ストレージ・システムのシェルフ・ポートを確認します storage shelf port show -fields remote-device 、 remote-port
+
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf id remote-port remote-device
----- -- ----------- -------------
3.20  0  Ethernet1/5 S1
3.20  1  Ethernet1/5 NS2
3.20  2  Ethernet1/6 S1
3.20  3  Ethernet1/6 NS2
3.30  0  Ethernet1/7 S1
3.20  1  Ethernet1/7 NS2
3.30  2  Ethernet1/8 S1
3.20  3  Ethernet1/8 NS2
----
. ケースの自動作成を抑制した場合は、 AutoSupport メッセージ「 system node AutoSupport invoke -node * -type all -message MAINT=end 」を呼び出して作成を再度有効にします

