---
permalink: switch-cisco-9336/9336-overview.html 
sidebar: sidebar 
keywords: cisco nexus 9336c-fx2 
summary: 3 つ以上のノードで ONTAP クラスタを構築する場合は、サポートされている 2 つのクラスタネットワークスイッチが必要です。オプションとして、追加の管理スイッチを使用できます。 
---
= Cisco 9336C-FX2 スイッチの概要
:icons: font
:imagesdir: ../media/


[role="lead"]
3 つ以上のノードで ONTAP クラスタを構築する場合は、サポートされている 2 つのクラスタネットワークスイッチが必要です。オプションとして、追加の管理スイッチを使用できます。

Cisco Nexus 9336C-FX2 スイッチ（ X190200/X190210 ）は、スイッチに付属の標準ブラケットを使用して、ネットアップシステムキャビネットまたは他社製キャビネットに設置できます。

次の表に、 9336C-FX2 スイッチ、ファン、および電源装置の部品番号と概要を示します。

[cols="1,2"]
|===
| パーツ番号 | 説明 


 a| 
X190200-CS-PE
 a| 
N9K-9336C-FX2 、 CS 、 PTSX 、 36PT10/25/40/100GQSFP28



 a| 
X190200-CS-PI
 a| 
N9K-9336C-FX2 、 CS 、 PSIN 、 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PE のこと
 a| 
N9K-9336C 、 FTE 、 PTSX 、 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C 、 FTE 、 PSIN 、 36PT10/25/40/100GQSFP28



 a| 
X190002
 a| 
アクセサリキット X190001/X190003



 a| 
X-NXA-PAC1100W-PE2
 a| 
N9K-9336C AC 1100W PSU - ポート側排気



 a| 
X-NXA-PAC1100W-PI2
 a| 
N9K-9336C AC 1100W PSU - ポート側吸気



 a| 
X-NXA-FAN-65CFM-pe
 a| 
N9K-9336C 65CFM 、ポート側排気



 a| 
X-NXA-FAN-65CFM-pi
 a| 
N9K-9336C 65CFM 、ポート側吸気

|===


== その他のサポートされるスイッチ

* Nexus 3232C
+
Cisco Nexus 3232C スイッチ（ X190100 ）は、スイッチに付属のカスタムブラケットを使用してネットアップシステムキャビネットに設置するか、スイッチに付属の標準ブラケットを使用してラックに設置できます。

* Nexus3132Q-V
+
Cisco Nexus 3132Q-V スイッチ（ X190001 ）は、スイッチに付属の標準ブラケットを使用して、ネットアップシステムキャビネットまたはサードパーティ製キャビネットに設置できます。



次のクラスタスイッチは、ネットアップからは提供されなくなりましたが、 Cisco では期間限定でサポートする予定です。

* Nexus 5596UP / 5596T
+
Cisco Nexus 5596UP スイッチ（ X1967-R6 ）または 5596T （ X1989-R6 ）は、スイッチに付属のカスタムブラケットを使用してネットアップシステムキャビネットに設置するか、スイッチに付属の標準ブラケットを使用してラックに設置できます。

+
Nexus 5596UP スイッチは、 1 つまたは 2 つの 16 ポート拡張モジュール（ X1988-R6 ）もサポートします。

+
Nexus 5596T スイッチは、 FAS2520 のクラスタインターコネクトスイッチとしてのみサポートされており、無停止でハードウェアをアップグレードする場合に使用します。

+
http://support.netapp.com/info/communications/ECMP12454150.html["販売終了"^] 詳細


