---
permalink: switch-cisco-9336/migrate-to-2n-switched.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched 9336C-FX2 cluster environment,switchless cluster environments,9336C-FX2 switches 
summary: 既存の 2 ノードスイッチレスクラスタ環境を使用している場合は、 Cisco Nexus 9336C-FX2 スイッチを使用して 2 ノードスイッチクラスタ環境に移行し、 3 ノード以上にクラスタを拡張できます。 
---
= Cisco Nexus 9336C-FX2 クラスタスイッチを使用したネットアップのスイッチクラスタ環境への移行方法
:icons: font
:imagesdir: ../media/


[role="lead"]
既存の 2 ノードスイッチレスクラスタ環境を使用している場合は、 Cisco Nexus 9336C-FX2 スイッチを使用して 2 ノードスイッチクラスタ環境に移行し、 3 ノード以上にクラスタを拡張できます。

2 ノードスイッチレス構成：

* 2 ノードスイッチレス構成が適切にセットアップされて機能している必要があります。
* ノードで ONTAP 9.8 以降が実行されている必要があります。
* すべてのクラスタポートが up 状態になっている必要があります。
* すべてのクラスタ LIF （論理インターフェイス）が、 up 状態でホームポートにある必要があります。


Cisco Nexus 9336C-FX2 スイッチの構成：

* 両方のスイッチに管理ネットワーク接続が必要です。
* クラスタスイッチへのコンソールアクセスが必要です。
* Nexus 9336C-FX2 ノード間スイッチおよびスイッチ間接続には、 TwinAx ケーブルまたはファイバケーブルを使用する必要があります。
+
Hardware Universe * には、ケーブル接続の詳細が記載されています。

+
https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - スイッチ"]

* スイッチ間リンク（ ISL ）ケーブルは、 9336C-FX2 スイッチの両方でポート 1/35 および 1/36 に接続する必要があります。
* 9336C-FX2 スイッチの初期カスタマイズが完了している必要があります。次のようにします。
+
** 9336C-FX2 スイッチは最新バージョンのソフトウェアを実行しています
** リファレンス構成ファイル（ RCF ）がスイッチに適用されており、 SMTP 、 SNMP 、 SSH などのサイトのカスタマイズが新しいスイッチで設定されている必要があります。




この手順の例では、クラスタスイッチとノードで次の命名法を使用しています。

* 9336C-FX2 スイッチの名前は cs1 と cs2 です。
* クラスタ SVM の名前は node1 と node2 になります。
* LIF の名前は、ノード 1 では node1_clus1 と node1_clus2 、ノード 2 では node2_clus1 と node2_clus2 です。
* 「 cluster1 ：： * > 」プロンプトは、クラスタの名前を示します。
* この手順で使用されるクラスタポートは e0a および e0b です。
+
Hardware Universe * には、プラットフォームの実際のクラスタ・ポートに関する最新情報が含まれています。

+
https://hwu.netapp.com["Hardware Universe"]

+
.. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。「 system node AutoSupport invoke -node * -type all -message MAINT= xh
+
x は、メンテナンス時間の長さ（時間単位）です。

+

NOTE: AutoSupport メッセージはテクニカルサポートにこのメンテナンスタスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

.. 権限レベルを advanced に変更します。続行するかどうかを尋ねられたら、「 y 」と入力します。「 set -privilege advanced 」
+
詳細プロンプト (`*>') が表示されます

.. 新しいクラスタスイッチ cs1 と cs2 の両方で、すべてのノード側ポート（ ISL ポートではない）を無効にします。
+
ISL ポートを無効にしないでください。

+
次の例は、スイッチ cs1 でノードに接続されたポート 1~34 が無効になっていることを示しています。

+
[listing]
----
cs1# **config**
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# **interface e/1-34**
cs1(config-if-range)# **shutdown**
----
.. 2 つの 9336C-FX2 スイッチ cs1 と cs2 間の ISL 上の ISL ポートと物理ポートがポート 1/35 と 1/36 で動作していることを確認します。「 How port-channel summary
+
次の例は、スイッチ cs1 上の ISL ポートが up になっていることを示しています。

+
[listing]
----
cs1# **show port-channel summary**

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
+
次の例は、スイッチ cs2 上の ISL ポートが up になっていることを示しています。

+
[listing]
----
(cs2)# **show port-channel summary**

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
.. 隣接デバイスのリストを表示します。「 CDP 隣接デバイスの表示」
+
このコマンドは、システムに接続されているデバイスに関する情報を提供します。

+
次の例は、スイッチ cs1 上の隣接デバイスを示しています。

+
[listing]
----
cs1# **show cdp neighbors**

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
+
次の例は、スイッチ cs2 上の隣接デバイスを表示します。

+
[listing]
----
cs2# **show cdp neighbors**

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
.. すべてのクラスタ・ポートが up であることを確認します。「 network port show -ipspace Cluster 」
+
各ポートは 'Link' のために表示され 'Health Status' のために正常である必要があります

+
[listing]
----
cluster1::*> **network port show -ipspace Cluster**

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.
----
.. すべてのクラスタ LIF が up で動作していることを確認します。「 network interface show -vserver cluster 」
+
各クラスタ LIF には、「 Is Home 」には true が、「 TStatus Admin/Oper 」には up/up と表示されるはずです

+
[listing]
----
cluster1::*> **network interface show -vserver Cluster**

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
.. すべてのクラスタ LIF で自動リバートが有効になっていることを確認します。「 network interface show -vserver Cluster -fields auto-revert
+
[listing]
----
cluster1::*> **network interface show -vserver Cluster -fields auto-revert**

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
.. ノード 1 のクラスタポート e0a からケーブルを外し、 9336C-FX2 スイッチでサポートされている適切なケーブル接続を使用して、クラスタスイッチ cs1 のポート 1 に e0a を接続します。
+
Hardware Universe * には、ケーブル接続の詳細が記載されています。

+
https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - スイッチ"]

.. ノード 2 のクラスタポート e0a からケーブルを外し、 9336C-FX2 スイッチでサポートされている適切なケーブル接続を使用して、クラスタスイッチ cs1 のポート 2 に e0a を接続します。
.. クラスタスイッチ cs1 のすべてのノード側ポートを有効にします。
+
次の例は、スイッチ cs1 でポート 1/1~1/34 が有効になっていることを示しています。

+
[listing]
----
cs1# **config**
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# **interface e1/1-34**
cs1(config-if-range)# **no shutdown**
----
.. すべてのクラスタ LIF が up であり、運用可能であり、 Is Home に true と表示されていることを確認します。「 network interface show -vserver Cluster
+
次の例では、すべての LIF がノード 1 とノード 2 で up になっていて、 Is Home の結果が true であることを示します。

+
[listing]
----
cluster1::*> **network interface show -vserver Cluster**

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true

4 entries were displayed.
----
.. クラスタ内のノードのステータスに関する情報を表示します
+
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

+
[listing]
----
cluster1::*> **cluster show**

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
.. ノード 1 のクラスタポート e0b からケーブルを外し、 9336C-FX2 スイッチでサポートされている適切なケーブル接続を使用して、クラスタスイッチ cs2 のポート 1 に e0b を接続します。
.. ノード 2 のクラスタポート e0b からケーブルを外し、 9336C-FX2 スイッチでサポートされている適切なケーブル接続に従って、クラスタスイッチ cs2 のポート 2 に接続します。
.. クラスタスイッチ cs2 のすべてのノード側ポートを有効にします。
+
次の例は、スイッチ cs2 でポート 1/1~1/34 が有効になっていることを示しています。

+
[listing]
----
cs2# **config**
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# **interface e1/1-34**
cs2(config-if-range)# **no shutdown**
----
.. すべてのクラスタ・ポートが up であることを確認します。「 network port show -ipspace Cluster 」
+
次の例は、ノード 1 とノード 2 のすべてのクラスタポートが up になっていることを示しています。

+
[listing]
----
cluster1::*> **network port show -ipspace Cluster**

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.
----
.. すべてのインターフェイスに Is Home に true が表示されていることを確認します
+

NOTE: この処理が完了するまでに数分かかることがあります。

+
次の例では、すべての LIF がノード 1 とノード 2 で up になっていて、 Is Home の結果が true であることを示します。

+
[listing]
----
cluster1::*> **network interface show -vserver Cluster**

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true

4 entries were displayed.
----
.. 両方のノードがそれぞれ 1 つのスイッチに接続されていることを確認します。「 How CDP Neighbors' 」
+
次の例は、両方のスイッチの該当する結果を示しています。

+
[listing]
----
(cs1)# **show cdp neighbors**

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           FAS2980       e0a
node2              Eth1/2         133    H           FAS2980       e0a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 4

(cs2)# **show cdp neighbors**

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           FAS2980       e0b
node2              Eth1/2         133    H           FAS2980       e0b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 4
----
.. クラスタ内で検出されたネットワークデバイスに関する情報を表示します。「 network device-discovery show -protocol cdp
+
[listing]
----
cluster1::*> **network device-discovery show -protocol cdp**
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C9336C
            e0b    cs2                       0/2               N9K-C9336C
node1      /cdp
            e0a    cs1                       0/1               N9K-C9336C
            e0b    cs2                       0/1               N9K-C9336C

4 entries were displayed.
----
.. 設定が無効になっていることを確認します。「 network options switchless-cluster show
+

NOTE: コマンドが完了するまでに数分かかることがあります。3 分間の有効期間が終了することを通知するアナウンスが表示されるまで待ちます。

+
次の例の誤った出力は、設定が無効になっていることを示しています。

+
[listing]
----
cluster1::*> **network options switchless-cluster show**
Enable Switchless Cluster: false
----
.. クラスタ内のノード・メンバーのステータスを確認します cluster show
+
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

+
[listing]
----
cluster1::*> **cluster show**

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
.. クラスタネットワークが完全に接続されていることを確認します。「 cluster ping-cluster -node node-name 」
+
[listing]
----
cluster1::*> **cluster ping-cluster -node node2**
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
.. 特権レベルを admin に戻します。 'et -privilege admin'
.. ONTAP 9.8 以降では、「 system switch ethernet log setup -password 'system switch ethernet log enable -collection' 」コマンドを使用して、スイッチ関連のログファイルを収集するための Ethernet スイッチヘルスモニタログ収集機能を有効にします
+
[listing]
----
cluster1::*> **system switch ethernet log setup-password**
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> **system switch ethernet log setup-password**

Enter the switch name: **cs1**
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] **y**

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> **system switch ethernet log setup-password**

Enter the switch name: **cs2**
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] **y**

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> **system  switch ethernet log enable-collection**

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] **y**

Enabling cluster switch log collection.

cluster1::*>
----
+

NOTE: これらのコマンドのいずれかでエラーが返される場合は、ネットアップサポートにお問い合わせください。

.. ONTAP リリース 9.5P16 、 9.6P12 、および 9.7P10 以降のパッチリリースでは、次のコマンドを使用して、スイッチ関連のログファイルを収集するためのイーサネットスイッチヘルスモニタログ収集機能を有効にします。「 system cluster-switch log setup -password 'System cluster-switch log enable-collection' 」
+
[listing]
----
cluster1::*> **system cluster-switch log setup-password**
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> **system cluster-switch log setup-password**

Enter the switch name: **cs1**
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] **y**

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> **system cluster-switch log setup-password**

Enter the switch name: **cs2**
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] **y**

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> **system cluster-switch log enable-collection**

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] **y**

Enabling cluster switch log collection.

cluster1::*>
----
+

NOTE: これらのコマンドのいずれかでエラーが返される場合は、ネットアップサポートにお問い合わせください。

.. ケースの自動作成を抑制した場合は、 AutoSupport メッセージを呼び出して再度有効にします。「 system node AutoSupport invoke -node * -type all -message MAINT=end



