---
permalink: switch-cisco-9336/replace-configure-new-switch.html 
sidebar: sidebar 
keywords: Nexus 9336C-FX2 switches initial installation, configure cisco cluster switch 
summary: この章で説明する手順を実行すると、新しい Nexus 9336C-FX2 スイッチを設定できます。 
---
= Cisco Nexus 9336C-FX2 クラスタスイッチを設定します
:icons: font
:imagesdir: ../media/


[role="lead"]
この章で説明する手順を実行すると、新しい Nexus 9336C-FX2 スイッチを設定できます。

ONTAP 9.8 以降を実行しているシステムに Nexus 9336C-FX2 スイッチを取り付けるには、まず IP アドレスと設定を設定して、スイッチが管理インターフェイスを介して通信できるようにします。その後、 NX-OS ソフトウェアとリファレンス構成ファイル（ RCF ）をインストールできます。この手順は、コントローラが追加される前に Nexus 9336C-FX2 スイッチを準備するためのものです。

この手順の例では、スイッチとノードで次の命名法を使用しています。

* Nexus 9336C-FX2 スイッチの名前は cs1 と cs2 です。
* この手順で使用している例では、 2 番目のスイッチ _cs2 * 。 _ でアップグレードが開始されます
* クラスタ LIF の名前は、ノード 1 では node1_clus1 と node1_clus2 、ノード 2 では node2_clus1 と node2_clus2 です。
* IPspace 名は Cluster です。
* 「 cluster1 ：： * > 」プロンプトは、クラスタの名前を示します。
* 各ノードのクラスタポートの名前は e0a および e0b です。
+
プラットフォームでサポートされている実際のクラスタポートについては、 Hardware Universe を参照してください。

+
https://hwu.netapp.com/Home/Index["NetApp Hardware Universe の略"^]

* Nexus 9336C-FX2 スイッチでサポートされるノード接続は、ポート 1/1~1/34 です。
* Nexus 9336C-FX2 スイッチでサポートされるスイッチ間リンク（ ISL ）は、ポート 1/35 および 1/36 です。
* この手順の例では 2 つのノードを使用していますが、 1 つのクラスタには最大 24 のノードを含めることができます。

