---
settings:
  name: Install and maintain
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  pdf:
    zip-level: 1
    zip-filename: ontap-systems-switches-pdfs.zip
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP ストレージシステムのドキュメントを切り替える
    url: "/index.html"
  - title: リリース ノート
    entries:
    - title: スイッチの最新情報
      url: "/whats-new.html"
    - title: サポート終了
      url: "/eoa-switches.html"
  - title: 始めましょう
    entries:
    - title: ONTAPシステムスイッチについて学ぶ
      url: "/get-started/learn-switch-concept.html"
    - title: クイック スタート
      url: "/get-started/get-up-and-running.html"
  - title: AFXシステムスイッチ
    url: "/afx/index.html"
    entries:
    - section: switch-cisco-9808
    - section: switch-cisco-9332d-gx2b
    - section: switch-cisco-9364d-gx2a
  - title: クラスタースイッチ
    url: "/cluster/index.html"
    entries:
    - section: switch-bes-53248
    - section: switch-cisco-9336c-fx2
  - title: ストレージ スイッチ
    url: "/storage/index.html"
    entries:
    - section: switch-cisco-9336c-fx2-storage
  - title: 共有スイッチ
    url: "/shared/index.html"
    entries:
    - section: switch-cisco-9336c-fx2-shared
      pdf-filename: スイッチ-cisco-9336c-fx2-ストレージ
  - title: スイッチの状態を監視する
    url: "/cshm/index.html"
    entries:
    - section: switch-cshm-configure
    - section: switch-cshm-monitor
    - section: switch-cshm-log-collection
  - title: 販売終了スイッチ
    url: "/eoa/index.html"
    entries:
    - section: switch-cisco-3232c
    - section: switch-cisco-3232c-storage
    - section: switch-cisco-3132q-v
    - section: switch-cisco-92300
    - section: switch-netapp-cn1610
    - section: switch-nvidia-sn2100
    - section: switch-nvidia-sn2100-storage
  - title: 法律上の表示
    url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
