---
settings: {}
sidebar:
  entries:
  - title: ホーム
    url: "/index.html"
  - section: switch-bes-53248
  - section: switch-cisco-9336
  - section: switch-cisco-9336c-shared
  - section: switch-cisco-92300
  - section: other
  - title: 法的通知
    url: "/legal-notices.html"
