---
settings:
  name: ONTAP Systems Switches
  search: ontap-systems-switches
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,zh-cn,ko-kr
sidebar:
  entries:
  - title: AFF および FAS スイッチのドキュメント
    url: "/index.html"
  - section: switch-bes-53248
  - section: switch-cisco-3132q-v
  - section: switch-cisco-3232c
  - section: switch-cisco-9336c-fx2
  - section: switch-cisco-9336c-fx2-shared
  - section: switch-cisco-92300
  - section: switch-netapp-cn1610
  - section: other
  - title: 法的通知
    url: "/legal-notices.html"
