---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, switches, fas, aff systems 
summary: FAS システムとAFF システムの新しいスイッチについて説明します。 
---
= スイッチの新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS システムとAFF システムの新しいスイッチについて説明します。スイッチの詳細については、を参照して https://hwu.netapp.com/Switch/Index["NetApp Hardware Universe の略"^]ください。



== 新たにサポートされるスイッチ

[cols="25h,~,~"]
|===
| スイッチ | 説明 | 最初から利用可能です 


 a| 
12 ポート 10/25/40/100GbE Cisco Nexus 9336C-FX2-T クラスタおよびストレージ スイッチ (X190212-CS-PE および X190212-CS-PI)
 a| 
10/25/40/100GbE クラスター構成と 100GbE ストレージ (スイッチ接続ストレージ) 構成をサポートします。
 a| 
ONTAP 9.10.1



 a| 
16ポート100GbE NVIDIAスイッチ（X190006-PEおよびX190006-PI）
 a| 
NVIDIA SN2100クラスタインターコネクトスイッチとストレージスイッチのサポート（MetroCluster IP構成のサポートを含む）。
 a| 
ONTAP 9.10.1



 a| 
36ポート100GbE Ciscoスイッチ（X190200-CS-PEおよびX190200-CS-PI）
 a| 
MetroCluster IP 構成のサポートを含め、同じ Cisco Nexus 9336C-FX2 スイッチペアで共有インフラ（クラスタ、 HA 、およびスイッチ接続ストレージ）をサポートします。
 a| 
ONTAP 9.9.1



 a| 
36ポート100GbE Ciscoスイッチ（X190200-CS-PEおよびX190200-CS-PI）、（X190210-FE-PEおよびX190210-FE-PI）
 a| 
Cisco Nexus 9336C-FX2クラスタインターコネクトスイッチとストレージスイッチは、AFFおよびASAストレージシステム、およびフロントエンドデータ接続に対応しています。
 a| 
ONTAP 9.8



 a| 
Broadcom BES-53248 スイッチ（ X190005 および X190005R ）
 a| 
10 / 25GbEおよび40 / 100GbEポートを搭載したAFF / FASコントローラで、Broadcom BES-53248クラスタインターコネクトスイッチがサポートされます。
 a| 
ONTAP 9.8



 a| 
36ポート100GbE Ciscoスイッチ（X190200）および32ポート100GbE Ciscoスイッチ（X190100およびX190100R）
 a| 
Cisco Nexus 3232Cストレージスイッチをサポートし、NS224 NVMeドライブシェルフAFFおよびASAストレージシステムを接続します。

* AFF A800/AFF ASA A800
* AFF A700 / AFF ASA A700
* AFF A400 / AFF ASA A400 を選択します
* AFF A320

 a| 
ONTAP 9.8

|===