---
permalink: switch-nvidia-sn2100/cabling-considerations-sn2100-cluster.html 
sidebar: sidebar 
keywords: sn2100 SN2100 cabling setup, sn2100 switches configuration, cumulus linux os 
summary: NVIDIA SN2100スイッチを設定する前に、次の情報を確認してください。 
---
= ケーブル接続と構成に関する考慮事項を確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIA SN2100スイッチを設定する前に、次の考慮事項を確認してください。



== NVIDIAポートの詳細

|===


| *スイッチポート* | *ポートの使用状況* 


 a| 
swp1s0-3
 a| 
10/40クラスタポートノード



 a| 
swp2s0-3
 a| 
25：100クラスタポートノード



 a| 
swp3-14 40/100クラスタポートノード
 a| 
swp15-16 40/100 Inter-Switch Link（ISL；スイッチ間リンク）ポート

|===
を参照してください https://hwu.netapp.com/Switch/Index["Hardware Universe"] スイッチポートの詳細については、を参照してください。



== 光接続

SN2100スイッチでは、X1151A NIC、X1146A NIC、またはオンボード100GbEポートを使用した場合にのみ、光接続がサポートされます。例：

* ポートe0aとe0b上のAFF A800
* ポートe0gとe0hにAFF A320を追加します




== QSAアダプタ

QSAアダプタを使用してプラットフォーム上のオンボードインテルクラスタポートに接続した場合、すべてのリンクが表示されるわけではありません。FAS2750、AFF A300、FAS8200（オール10G）、AFF A250（25G）などのプラットフォームが該当します。

この問題 を解決するには、次の手順を実行します。

. Intel 10Gの場合、swp1s0-3リンク速度を10000に手動で設定し、オートネゴシエーションをオフに設定します。
. Chelsio 25Gの場合、swp2s0～3リンク速度を25000に手動で設定し、オートネゴシエーションをオフに設定します。



NOTE: 10G / 25G QSAを使用して、ブレークアウト以外の40 / 100Gポートを使用します。ブレークアウト用に設定されたポートにはQSAアダプタを挿入しないでください。



== スイッチポートの速度

スイッチポートのトランシーバによっては、スイッチポートの速度を固定の速度に設定しなければならない場合があります。10Gおよび25Gブレークアウトポートを使用する場合は、自動ネゴシエーションがオフになっていて、スイッチのポート速度をハードセットしていることを確認してください。例：

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ net add int swp1s3 link autoneg off && net com
--- /etc/network/interfaces     2019-11-17 00:17:13.470687027 +0000
+++ /run/nclu/ifupdown2/interfaces.tmp  2019-11-24 00:09:19.435226258 +0000
@@ -37,21 +37,21 @@
     alias 10G Intra-Cluster Node
     link-autoneg off
     link-speed 10000  *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp1s3
iface swp1s3
     alias 10G Intra-Cluster Node
-    link-autoneg off
+    link-autoneg on
     link-speed 10000 *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp2s0
iface swp2s0
     alias 25G Intra-Cluster Node
     link-autoneg off
     link-speed 25000 *<---- port speed set*
----
.次の手順
link:install-cable-shelves-sn2100-cluster.html["NS224シェルフをスイッチ接続型ストレージとしてケーブル接続します"]。
