---
permalink: switch-nvidia-sn2100/cabling-considerations-sn2100-cluster.html 
sidebar: sidebar 
keywords: SN2100 cabling setup, sn2100 switches configuration, cumulus linux os 
summary: NVIDIA SN2100 スイッチを構成する前に、次の情報を確認してください。 
---
= ケーブル配線と構成の考慮事項を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIA SN2100 スイッチを構成する前に、次の考慮事項を確認してください。



== NVIDIAポートの詳細

|===


| *スイッチポート* | *ポートの使用* 


 a| 
swp1s0-3
 a| 
4x10GbEブレイクアウトクラスタポートノード



 a| 
swp2s0-3
 a| 
4x25GbEブレイクアウトクラスタポートノード



 a| 
swp3-14
 a| 
40/100GbE クラスターポートノード



 a| 
swp15-16
 a| 
100GbE スイッチ間リンク (ISL) ポート

|===
参照 https://hwu.netapp.com/Switch/Index["Hardware Universe"^]スイッチ ポートの詳細については、こちらをご覧ください。



== 光接続によるリンクアップ遅延

リンクアップの遅延が 5 秒を超える場合、Cumulus Linux 5.4 以降では高速リンクアップがサポートされます。リンクを設定するには、 `nv set`次のようにコマンドを実行します。

[listing, subs="+quotes"]
----
*nv set interface <interface-id> link fast-linkup on*
*nv config apply*
*reload the switchd*
----
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus-cs13:mgmt:~$ *nv set interface swp5 link fast-linkup on*
cumulus@cumulus-cs13:mgmt:~$ *nv config apply*
*switchd need to reload on this config change*

Are you sure? [y/N] *y*
applied [rev_id: 22]

Only switchd reload required
----
====


== 銅線接続のサポート

この問題を解決するには、次の構成変更が必要です。

[role="tabbed-block"]
====
.キュムラス・リナックス 4.4.3
--
. 40GbE/100GbE 銅線ケーブルを使用して各インターフェースの名前を識別します。
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show interface pluggables*

Interface  Identifier     Vendor Name     Vendor PN    Vendor SN      Vendor Rev
---------  -------------  --------------  -----------  -------------  ----------
swp3       0x11 (QSFP28)  Molex           112-00576    93A2229911111  B0
swp4       0x11 (QSFP28)  Molex           112-00576    93A2229922222  B0
----
. 次の2行を `/etc/cumulus/switchd.conf`40GbE/100GbE 銅線ケーブルを使用しているすべてのポート (swp<n>) のファイル:
+
** `interface.swp<n>.enable_media_depended_linkup_flow=TRUE`
** `interface.swp<n>.enable_short_tuning=TRUE`
+
例えば：

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo nano /etc/cumulus/switchd.conf*
.
.
interface.swp3.enable_media_depended_linkup_flow=TRUE
interface.swp3.enable_short_tuning=TRUE
interface.swp4.enable_media_depended_linkup_flow=TRUE
interface.swp4.enable_short_tuning=TRUE
----


. 再起動する `switchd`サービス：
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo systemctl restart switchd.service*
----
. ポートが稼働していることを確認します。
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP              Summary
-----  --------- ----  -----  ---------- ----------------- --------
UP     swp3      100G  9216   Trunk/L2                     Master: bridge(UP)
UP     swp4      100G  9216   Trunk/L2                     Master: bridge(UP)
----


--
.キュムラス Linux 5.x
--
. 40GbE/100GbE 銅線ケーブルを使用して各インターフェースの名前を識別します。
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show interface --view=pluggables*

Interface  Identifier     Vendor Name     Vendor PN    Vendor SN      Vendor Rev
---------  -------------  --------------  -----------  -------------  ----------
swp3       0x11 (QSFP28)  Molex           112-00576    93A2229911111  B0
swp4       0x11 (QSFP28)  Molex           112-00576    93A2229922222  B0
----
. リンクを設定するには、 `nv set`次のようにコマンドを実行します。
+
** `nv set interface <interface-id> link fast-linkup on`
** `nv config apply`
** リロード `switchd`サービス
+
例えば：

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set interface swp5 link fast-linkup on*
cumulus@cumulus:mgmt:~$ *nv config apply*
switchd need to reload on this config change

Are you sure? [y/N] *y*
applied [rev_id: 22]

Only switchd reload required
----


. ポートが稼働していることを確認します。
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP              Summary
-----  --------- ----  -----  ---------- ----------------- --------
UP     swp3      100G  9216   Trunk/L2                     Master: bridge(UP)
UP     swp4      100G  9216   Trunk/L2                     Master: bridge(UP)
----


--
====
ナレッジベースの記事を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric_Interconnect_and_Management_Switches/NVIDIA_SN2100_switch_fails_to_connect_using_40_100GbE_copper_cable["SN2100スイッチが40/100GbE銅線ケーブルを使用して接続できない"^]詳細についてはこちらをご覧ください。

Cumulus Linux 4.4.2 では、X1151A NIC、X1146A NIC、またはオンボード 100GbE ポートを備えた SN2100 スイッチでは銅線接続はサポートされません。例えば：

* ポートe0aおよびe0b上のAFF A800
* ポートe0gとe0hのAFF A320




== QSAアダプター

QSA アダプターを使用してプラットフォーム上の 10GbE/25GbE クラスター ポートに接続すると、リンクが起動しない可能性があります。

この問題を解決するには、次の手順を実行します。

* 10GbE の場合、swp1s0-3 リンク速度を手動で 10000 に設定し、自動ネゴシエーションをオフに設定します。
* 25GbE の場合、swp2s0-3 リンク速度を手動で 25000 に設定し、自動ネゴシエーションをオフに設定します。



NOTE: 10GbE/25GbE QSA アダプターを使用する場合は、非ブレイクアウト 40GbE/100GbE ポート (swp3-swp14) に挿入します。ブレークアウト用に設定されているポートに QSA アダプタを挿入しないでください。



== ブレイクアウトポートのインターフェース速度の設定

スイッチ ポートのトランシーバーによっては、スイッチ インターフェイスの速度を固定速度に設定する必要がある場合があります。  10GbE および 25GbE ブレークアウト ポートを使用する場合は、自動ネゴシエーションがオフになっていることを確認し、スイッチのインターフェイス速度を設定します。

[role="tabbed-block"]
====
.キュムラス・リナックス 4.4.3
--
例えば：

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net add int swp1s3 link autoneg off && net com*
--- /etc/network/interfaces     2019-11-17 00:17:13.470687027 +0000
+++ /run/nclu/ifupdown2/interfaces.tmp  2019-11-24 00:09:19.435226258 +0000
@@ -37,21 +37,21 @@
     alias 10G Intra-Cluster Node
     link-autoneg off
     link-speed 10000  *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp1s3
iface swp1s3
     alias 10G Intra-Cluster Node
-    link-autoneg off
+    link-autoneg on
     link-speed 10000 *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp2s0
iface swp2s0
     alias 25G Intra-Cluster Node
     link-autoneg off
     link-speed 25000 *<---- port speed set*
----
インターフェースとポートのステータスをチェックして、設定が適用されていることを確認します。

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show interface*

State  Name      Spd    MTU    Mode        LLDP             Summary
-----  --------  -----  -----  ----------  ---------------  --------------------------------------
.
.
UP     swp1s0     10G   9216   Trunk/L2    cs07 (e4c)       Master: br_default(UP)
UP     swp1s1     10G   9216   Trunk/L2    cs07 (e4d)       Master: br_default(UP)
UP     swp1s2     10G   9216   Trunk/L2    cs08 (e4c)       Master: br_default(UP)
UP     swp1s3     10G   9216   Trunk/L2    cs08 (e4d)       Master: br_default(UP)
.
.
UP     swp3       40G   9216   Trunk/L2    cs03 (e4e)       Master: br_default(UP)
UP     swp4       40G   9216   Trunk/L2    cs04 (e4e)       Master: br_default(UP)
DN     swp5       N/A   9216   Trunk/L2                     Master: br_default(UP)
DN     swp6       N/A   9216   Trunk/L2                     Master: br_default(UP)
DN     swp7       N/A   9216   Trunk/L2                     Master: br_default(UP)
.
.
UP     swp15      100G  9216   BondMember  cs01 (swp15)     Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  cs01 (swp16)     Master: cluster_isl(UP)
.
.
----
--
.キュムラス Linux 5.x
--
例えば：

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set interface swp1s3 link auto-negotiate off*
cumulus@cumulus:mgmt:~$ *nv set interface swp1s3 link speed 10G*
cumulus@cumulus:mgmt:~$ *nv show interface swp1s3*

link                                                                                            
  auto-negotiate        off                     off                     off                   
  duplex                full                    full                    full                  
  speed                 10G                     10G                     10G                   
  fec                   auto                    auto                    auto                  
  mtu                   9216                    9216                    9216                  
[breakout]                                                                                    
  state                 up                      up                      up
----
インターフェースとポートのステータスをチェックして、設定が適用されていることを確認します。

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show interface*

State  Name      Spd    MTU    Mode        LLDP             Summary
-----  --------  -----  -----  ----------  ---------------  --------------------------------------
.
.
UP     swp1s0     10G   9216   Trunk/L2    cs07 (e4c)       Master: br_default(UP)
UP     swp1s1     10G   9216   Trunk/L2    cs07 (e4d)       Master: br_default(UP)
UP     swp1s2     10G   9216   Trunk/L2    cs08 (e4c)       Master: br_default(UP)
UP     swp1s3     10G   9216   Trunk/L2    cs08 (e4d)       Master: br_default(UP)
.
.
UP     swp3       40G   9216   Trunk/L2    cs03 (e4e)       Master: br_default(UP)
UP     swp4       40G   9216   Trunk/L2    cs04 (e4e)       Master: br_default(UP)
DN     swp5       N/A   9216   Trunk/L2                     Master: br_default(UP)
DN     swp6       N/A   9216   Trunk/L2                     Master: br_default(UP)
DN     swp7       N/A   9216   Trunk/L2                     Master: br_default(UP)
.
.
UP     swp15      100G  9216   BondMember  cs01 (swp15)     Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  cs01 (swp16)     Master: cluster_isl(UP)
.
.
----
--
====
.次の手順
link:install-cable-shelves-sn2100-cluster.html["NS224シェルフをスイッチ接続ストレージとしてケーブル接続"] 。
