---
permalink: switch-nvidia-sn2100/cabling-considerations-sn2100-cluster.html 
sidebar: sidebar 
keywords: sn2100 SN2100 cabling setup, sn2100 switches configuration, cumulus linux os 
summary: NVIDIA SN2100スイッチを設定する前に、次の情報を確認してください。 
---
= ケーブル接続と構成に関する考慮事項を確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIA SN2100スイッチを設定する前に、次の考慮事項を確認してください。



== NVIDIAポートの詳細

|===


| *スイッチポート* | *ポートの使用状況* 


 a| 
swp1s0-3
 a| 
10GbEブレークアウトクラスタポートノード×4



 a| 
swp2s0-3
 a| 
25GbEブレークアウトクラスタポートノード×4



 a| 
swp3-14
 a| 
40 / 100クラスタポートノード



 a| 
swp15-16
 a| 
40 / 100 Inter-Switch Link（ISL；スイッチ間リンク）ポート

|===
を参照してください https://hwu.netapp.com/Switch/Index["Hardware Universe"^] スイッチポートの詳細については、を参照してください。



== 光接続

Cumulus Linux 4.4.2では、X1151A NIC、X1146A NIC、またはオンボード100GbEポートを備えたSN2100スイッチでは、光接続のみがサポートされます。例：

* ポートe0aとe0b上のAFF A800
* ポートe0gとe0hにAFF A320を追加します


Cumulus Linux 4.4.3以降では、この問題 を修正するために次の設定変更が必要です。

. に次の2行を追加します `/etc/cumulus/switchd.conf` 40 / 100GbE銅線ケーブルを使用する各ポート（SWP <n> ）のファイル：
+
** `interface.swp<n>.enable_media_depended_linkup_flow=TRUE`
** `interface.swp<n>.enable_short_tuning=TRUE`


. switchdデーモンを再起動します。 `systemctl restart switchd`


以下を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric_Interconnect_and_Management_Switches/NVIDIA_SN2100_switch_fails_to_connect_using_40_100GbE_copper_cable["KB"^] を参照してください。

.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *cat /etc/cumulus/switchd.conf | grep swp3*
interface.swp3.enable_media_depended_linkup_flow=TRUE
interface.swp3.enable_short_tuning=TRUE
cumulus@cumulus:mgmt:~$ *cat /etc/cumulus/switchd.conf | grep swp6*
interface.swp6.enable_media_depended_linkup_flow=TRUE
interface.swp6.enable_short_tuning=TRUE
cumulus@cumulus:mgmt:~$
----
====


== QSAアダプタ

プラットフォームのオンボードクラスタポートへの接続にQSAアダプタを使用すると、リンクが有効にならないことがあります。

この問題 を解決するには、次の手順を実行します。

* 10Gの場合は、swp1s0-3リンク速度を手動で10000に設定し、自動ネゴシエーションをoffに設定します。
* 25Gの場合は、swp2s0-3リンク速度を25000に手動で設定し、オートネゴシエーションをoffに設定します。



NOTE: 10G/25G QSAを使用する場合は、ブレークアウトされていない40/100Gポートに挿入します。ブレークアウト用に設定されたポートにはQSAアダプタを挿入しないでください。



== ブレークアウトポートのインターフェイス速度を設定しています

スイッチポートのトランシーバによっては、スイッチインターフェイスの速度を固定速度に設定する必要があります。10Gおよび25Gブレークアウトポートを使用する場合は、自動ネゴシエーションがオフになっていることを確認し、スイッチのインターフェイス速度をハードセットします。例：

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ net add int swp1s3 link autoneg off && net com
--- /etc/network/interfaces     2019-11-17 00:17:13.470687027 +0000
+++ /run/nclu/ifupdown2/interfaces.tmp  2019-11-24 00:09:19.435226258 +0000
@@ -37,21 +37,21 @@
     alias 10G Intra-Cluster Node
     link-autoneg off
     link-speed 10000  *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp1s3
iface swp1s3
     alias 10G Intra-Cluster Node
-    link-autoneg off
+    link-autoneg on
     link-speed 10000 *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp2s0
iface swp2s0
     alias 25G Intra-Cluster Node
     link-autoneg off
     link-speed 25000 *<---- port speed set*
----
.次の手順
link:install-cable-shelves-sn2100-cluster.html["NS224シェルフをスイッチ接続型ストレージとしてケーブル接続します"]。
