---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: NVIDIA SN2100スイッチのインストールとメンテナンスについては、すべての要件と推奨されるドキュメントを確認してください。 
---
= NVIDIA SN2100スイッチの構成要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIA SN2100スイッチのインストールとメンテナンスについては、すべての設定要件を確認してください。



== インストールの要件

3 つ以上のノードで ONTAP クラスタを構築する場合は、サポートされている 2 つのクラスタネットワークスイッチが必要です。オプションとして、追加の管理スイッチを使用できます。

NVIDIA SN2100スイッチ（X190006）は、スイッチに付属の標準ブラケットを使用して、NVIDIAデュアル/シングルスイッチキャビネットに設置します。

ケーブル配線のガイドラインについては、を参照してください link:cabling-considerations-sn2100-cluster.html["ケーブル接続と構成に関する考慮事項を確認"]。



== ONTAP およびLinuxのサポート

NVIDIA SN2100スイッチは、Cumulus Linuxを実行する10 / 25 / 40 / 100GbEスイッチです。スイッチは以下をサポートしています。

* ONTAP 9.10.1P3以降
+
SN2100スイッチは、ONTAP 9.10.1P3以降のクラスタアプリケーションとストレージアプリケーションに、別 々 のスイッチペアで対応します。

* Cumulus Linux（CL）OSバージョン
+
** 特定のCLバージョンは、NetAppによって認定およびサポートされています。最新の互換性情報については、またはを参照してlink:https://mysupport.netapp.com/site/info/nvidia-cluster-switch["NVIDIAイーサネットスイッチの情報"^]link:https://hwu.netapp.com["NetApp Hardware Universe の略"^]ください。
** NVIDIAからSN2100 Cumulusソフトウェアをダウンロードするには、NVIDIAのエンタープライズサポートポータルにアクセスするためのログイン資格情報が必要です。ナレッジベースの記事を参照してください https://kb.netapp.com/onprem/Switches/Nvidia/How_To_Register_With_NVIDIA_For_Enterprise_Support_Portal_Access["エンタープライズサポートポータルアクセスのためのNVIDIAへの登録方法"^]。




* Cumulus Linuxは、スイッチがCumulus LinuxまたはONIEを実行しているときにインストールできます。

