---
permalink: switch-nvidia-sn2100/configure-software-overview-sn2100-cluster.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: ソフトウェア構成またはNVIDIA SN2100スイッチの概要。 
---
= NVIDIA SN2100スイッチのソフトウェアインストールワークフロー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIA SN2100スイッチのソフトウェアをインストールして設定するには、次の手順に従います。

. link:install-cumulus-mode-sn2100-cluster.html["Cumulus LinuxをCumulusモードでインストールします"] または link:install-onie-mode-sn2100-cluster.html["Cumulus LinuxをONIEモードでインストールします"]。Cumulus Linux（CL）OSは、スイッチでCumulus LinuxまたはONIEを実行している場合にインストールできます。
. link:install-rcf-sn2100-cluster.html["リファレンス構成ファイル（RCF）スクリプトをインストールします"]。クラスタリングアプリケーションとストレージアプリケーション用に2つのRCFスクリプトが用意されています。各の手順 は同じです。
. link:install-snmpv3-sn2100-cluster.html["スイッチログ収集用のSNMPv3を設定します"]。このリリースでは、スイッチのログ収集とSwitch Health Monitoring（SHM）のSNMPv3がサポートされています。



NOTE: この手順では、ネットワークコマンドラインユーティリティ（NCLU）を使用します。NCLUは、すべてのLinuxに完全にアクセスできるようにするコマンドラインインタフェースです。netコマンドは、端末からアクションを実行するために使用するラッパーユーティリティです。
