---
permalink: switch-nvidia-sn2100/install-onie-mode-sn2100-cluster.html 
sidebar: sidebar 
keywords: install cumulus onie mode, sn2100 SN2100 switches setup, cumulus linux, onie mode 
summary: Cumulus Linux（CL）OSは、スイッチでCumulus LinuxまたはONIEを実行している場合にインストールできます。 
---
= Cumulus LinuxをONIEモードでインストールします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スイッチがONIEモードで動作している場合、この手順 に従ってCumulus Linux（CL）OSをインストールします。


NOTE: Cumulus Linux（CL）OSは、スイッチでONIEまたはCumulus Linuxを実行している場合にインストールできます（を参照） link:install-cumulus-mode-sn2100-cluster.html["クムルスモードでインストールします"]）。

.このタスクについて
Open Network Install Environment（ONIE）を使用してCumulus Linuxをインストールすると、ネットワークインストーライメージを自動的に検出できます。これにより、Cumulus Linuxなどのオペレーティングシステムの選択により、スイッチをセキュリティ保護するシステムモデルが容易になります。ONIEでCumulus Linuxをインストールする最も簡単な方法は、ローカルHTTP検出です。


NOTE: ホストがIPv6対応の場合は、Webサーバを実行していることを確認します。ホストがIPv4対応の場合は、Webサーバに加えてDHCPも実行されていることを確認します。

この手順 では、管理者がONIEで起動した後にCumulus Linuxをアップグレードする方法を説明します。

.手順
. Cumulus LinuxインストールファイルをWebサーバーのルートディレクトリにダウンロードします。このファイルの名前をに変更します。 `onie-installer`。
. イーサネットケーブルを使用して、スイッチの管理イーサネットポートにホストを接続します。
. スイッチの電源をオンにします。
+
スイッチはONIEイメージインストーラをダウンロードして起動します。インストールが完了すると、ターミナルウィンドウにCumulus Linuxログインプロンプトが表示されます。

+

NOTE: Cumulus Linuxをインストールするたびに、ファイルシステム構造全体が消去され、再構築されます。

. SN2100スイッチをリブートします。
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. GNU GRUB画面で*Esc*キーを押して、通常の起動プロセスを中断し、*ONIE*を選択して、*Enter*を押します。
. 次の画面で「* ONIE: OSのインストール*」を選択します。
. ONIEインストーラの検出処理が実行され、自動インストールが検索されます。Enter *を押して、プロセスを一時的に停止します。
. 検出プロセスが停止したら、次の手順を実行します。
+
[listing, subs="+quotes"]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. ネットワークでDHCPサービスが実行されている場合は、IPアドレス、サブネットマスク、およびデフォルトゲートウェイが正しく割り当てられていることを確認します。
+
`ifconfig eth0`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff

ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.233.204.1    0.0.0.0         UG    0      0      0   eth0
10.233.204.0    *               255.255.254.0   U     0      0      0   eth0
----
====
. IPアドレッシング方式が手動で定義されている場合は、次の手順を実行します。
+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0 10.233.204.71 netmask 255.255.254.0*
ONIE:/ # *route add default gw 10.233.204.1*
----
. 手順9を繰り返して、静的情報が正しく入力されていることを確認します。
. Cumulus Linuxのインストール：
+
[listing]
----
# onie-nos-install http://<web-server>/<path>/cumulus-linux-4.4.2-mlx-amd64.bin
----
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-4.4.2-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-4.4.2-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
====
. インストールが完了したら、スイッチにログインします。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *netapp1!*
Retype new password: *netapp1!*
----
====
. Cumulus Linuxのバージョンを確認します。
+
`net show version`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.2u4
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.2*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.2”*
----
====


.次の手順
link:install-rcf-sn2100-cluster.html["リファレンス構成ファイル（RCF）スクリプトをインストールします"]。
