---
permalink: switch-nvidia-sn2100/migrate-cn1610-sn2100-cluster-switch.html 
sidebar: sidebar 
keywords: migrate cluster NVIDIA SN2100 cluster switches cn1610 
summary: ONTAPクラスタ用のNetApp CN1610 クラスタ スイッチをNVIDIA SN2100 クラスタ ネットワーク スイッチに無停止で移行できます。 
---
= CN1610 クラスタ スイッチをNVIDIA SN2100 クラスタ スイッチに移行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPクラスタのNetApp CN1610 クラスタ スイッチをNVIDIA SN2100 クラスタ スイッチに移行できます。この手順は無停止で実行されます。



== 要件の確認

NetApp CN1610 クラスタ スイッチをNVIDIA SN2100 クラスタ スイッチに置き換える場合は、特定の構成情報、ポート接続、およびケーブル接続の要件に注意する必要があります。見るlink:configure-overview-sn2100-cluster.html["NVIDIA SN2100スイッチのインストールと構成の概要"]。

.サポートされるスイッチ
次のクラスタ スイッチがサポートされます。

* NetApp CN1610
* NVIDIA SN2100


サポートされているポートとその設定の詳細については、 https://hwu.netapp.com/["Hardware Universe"^] 。

.開始する前に
構成が次の要件を満たしていることを確認します。

* 既存のクラスターは正しくセットアップされ、機能しています。
* 中断のない操作を保証するために、すべてのクラスター ポートは *up* 状態になっています。
* NVIDIA SN2100 クラスター スイッチは、参照構成ファイル (RCF) が適用された正しいバージョンの Cumulus Linux がインストールされ、構成され、動作しています。
* 既存のクラスター ネットワーク構成は次のとおりです。
+
** CN1610 スイッチを使用した冗長化され完全に機能するNetAppクラスター。
** CN1610 スイッチと新しいスイッチの両方への管理接続とコンソール アクセス。
** すべてのクラスタ LIF がアップ状態であり、クラスタ LIF がホーム ポート上にあります。
** ISL ポートが有効になり、CN1610 スイッチ間および新しいスイッチ間でケーブル接続されます。


* 一部のポートは、 NVIDIA SN2100 スイッチ上で 40GbE または 100GbE で動作するように構成されています。
* ノードからNVIDIA SN2100 クラスター スイッチへの 40GbE および 100GbE 接続を計画、移行、および文書化しました。




== スイッチを移行する

.例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 既存の CN1610 クラスタ スイッチは _c1_ と _c2_ です。
* 新しいNVIDIA SN2100 クラスター スイッチは _sw1_ と _sw2_ です。
* ノードは _node1_ と _node2_ です。
* クラスター LIF は、ノード 1 ではそれぞれ _node1_clus1_ と _node1_clus2_、ノード 2 では _node2_clus1_ と _node2_clus2_ です。
* その `cluster1::*>`プロンプトはクラスターの名前を示します。
* この手順で使用されるクラスター ポートは _e3a_ と _e3b_ です。
* ブレイクアウト ポートの形式は、swp[ポート]s[ブレイクアウト ポート 0-3] です。たとえば、swp1 の 4 つのブレークアウト ポートは、_swp1s0_、_swp1s1_、_swp1s2_、_swp1s3_ です。


.タスク概要
この手順では、次のシナリオについて説明します。

* まずスイッチ c2 をスイッチ sw2 に置き換えます。
+
** クラスター ノードへのポートをシャットダウンします。クラスターの不安定性を回避するには、すべてのポートを同時にシャットダウンする必要があります。
** 次に、ノードと c2 間のケーブルが c2 から切断され、sw2 に再接続されます。


* スイッチ c1 はスイッチ sw1 に置き換えられます。
+
** クラスター ノードへのポートをシャットダウンします。クラスターの不安定性を回避するには、すべてのポートを同時にシャットダウンする必要があります。
** 次に、ノードと c1 間のケーブルが c1 から切断され、sw1 に再接続されます。





NOTE: この手順では、動作中のスイッチ間リンク (ISL) は必要ありません。これは、RCF バージョンの変更によって ISL 接続が一時的に影響を受ける可能性があるため、設計によるものです。クラスタ操作を中断せずに実行するために、次の手順では、ターゲット スイッチで手順を実行しながら、すべてのクラスタ LIF を動作中のパートナー スイッチに移行します。



=== ステップ1: 移行の準備

. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
ここで、_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

. 続行するかどうかを尋ねられたら *y* と入力して、権限レベルを「advanced」に変更します。
+
`set -privilege advanced`

+
advancedのプロンプト（*>）が表示されます。

. クラスタ LIF の自動復帰を無効にします。
+
`network interface modify -vserver Cluster -lif * -auto-revert false`





=== ステップ2: ポートとケーブルを構成する

. 各クラスタ インターフェイスの管理ステータスまたは動作ステータスを決定します。
+
各ポートは `Link`そして `healthy`のために `Health Status`。

+
.. ネットワーク ポートの属性を表示します。
+
`network port show -ipspace Cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
.. LIF とその指定されたホーム ノードに関する情報を表示します。
+
`network interface show -vserver Cluster`

+
各LIFには `up/up`のために `Status Admin/Oper`そして `true`のために `Is Home`。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current     Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node        Port    Home
----------- -----------  ---------- ------------------ ----------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
            node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
            node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
            node2_clus2  up/up      169.254.19.183/16  node2       e3b     true

----
====


. 各ノード上のクラスター ポートは、次のコマンドを使用して、既存のクラスター スイッチに次のように (ノードの観点から) 接続されます。
+
`network device-discovery show -protocol`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e3a    c1 (6a:ad:4f:98:3b:3f)    0/1               -
            e3b    c2 (6a:ad:4f:98:4c:a4)    0/1               -
node2      /cdp
            e3a    c1 (6a:ad:4f:98:3b:3f)    0/2               -
            e3b    c2 (6a:ad:4f:98:4c:a4)    0/2               -
----
====
. クラスタ ポートとスイッチは、次のコマンドを使用して、スイッチの観点から次のように接続されます。
+
`show cdp neighbors`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 0/1           124     H          AFF-A400         e3a
node2                 0/2           124     H          AFF-A400         e3a
c2                    0/13          179     S I s      CN1610           0/13
c2                    0/14          175     S I s      CN1610           0/14
c2                    0/15          179     S I s      CN1610           0/15
c2                    0/16          175     S I s      CN1610           0/16

c2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 0/1           124    H           AFF-A400         e3b
node2                 0/2           124    H           AFF-A400         e3b
c1                    0/13          175    S I s       CN1610           0/13
c1                    0/14          175    S I s       CN1610           0/14
c1                    0/15          175    S I s       CN1610           0/15
c1                    0/16          175    S I s       CN1610           0/16
----
====
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e3a
Cluster node1_clus2 169.254.49.125 node1     e3b
Cluster node2_clus1 169.254.47.194 node2     e3a
Cluster node2_clus2 169.254.19.183 node2     e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step5]]スイッチc2で、クラスタLIFをフェイルオーバーするために、ノードのクラスタポートに接続されているポートをシャットダウンします。
+
[listing, subs="+quotes"]
----
(c2)# *configure*
(c2)(Config)# *interface 0/1-0/12*
(c2)(Interface 0/1-0/12)# *shutdown*
(c2)(Interface 0/1-0/12)# *exit*
(c2)(Config)# *exit*
(c2)#
----
. NVIDIA SN2100 でサポートされている適切なケーブルを使用して、ノード クラスター ポートを古いスイッチ c2 から新しいスイッチ sw2 に移動します。
. ネットワーク ポートの属性を表示します。
+
`network port show -ipspace Cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. 各ノード上のクラスター ポートは、ノードの観点から見ると、次のようにクラスター スイッチに接続されます。
+
`network device-discovery show -protocol`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /lldp
            e3a    c1  (6a:ad:4f:98:3b:3f)   0/1               -
            e3b    sw2 (b8:ce:f6:19:1a:7e)   swp3              -
node2      /lldp
            e3a    c1  (6a:ad:4f:98:3b:3f)   0/2               -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4              -
----
====
. スイッチ sw2 で、すべてのノード クラスタ ポートが稼働していることを確認します。
+
`net show interface`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
====
. スイッチ c1 で、クラスタ LIF をフェイルオーバーするために、ノードのクラスタ ポートに接続されているポートをシャットダウンします。
+
[listing, subs="+quotes"]
----
(c1)# *configure*
(c1)(Config)# *interface 0/1-0/12*
(c1)(Interface 0/1-0/12)# *shutdown*
(c1)(Interface 0/1-0/12)# *exit*
(c1)(Config)# *exit*
(c1)#
----
. NVIDIA SN2100 でサポートされている適切なケーブルを使用して、ノード クラスター ポートを古いスイッチ c1 から新しいスイッチ sw1 に移動します。
. クラスターの最終構成を確認します。
+
`network port show -ipspace Cluster`

+
各ポートには `up`のために `Link`そして `healthy`のために `Health Status`。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. 各ノード上のクラスター ポートは、ノードの観点から見ると、次のようにクラスター スイッチに接続されます。
+
`network device-discovery show -protocol`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3            -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3            -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4            -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4            -
----
====
. スイッチ sw1 および sw2 で、すべてのノード クラスタ ポートが稼働していることを確認します。
+
`net show interface`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3a               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3a               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw2 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw2 (swp16)       Master: cluster_isl(UP)


cumulus@sw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- -----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
====
. 両方のノードが各スイッチにそれぞれ 1 つの接続を持っていることを確認します。
+
`net show lldp`

+
.例を表示
[%collapsible]
====
次の例は、両方のスイッチの適切な結果を示しています。

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost          RemotePort
---------  -----  ----------  ------------------  -----------
swp3       100G   Trunk/L2    node1               e3a
swp4       100G   Trunk/L2    node2               e3a
swp15      100G   BondMember  sw2                 swp15
swp16      100G   BondMember  sw2                 swp16

cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost          RemotePort
---------  -----  ----------  ------------------  -----------
swp3       100G   Trunk/L2    node1               e3b
swp4       100G   Trunk/L2    node2               e3b
swp15      100G   BondMember  sw1                 swp15
swp16      100G   BondMember  sw1                 swp16
----
====




=== ステップ3: 構成を確認する

. クラスタ LIF で自動復帰を有効にします。
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. スイッチ sw2 で、すべてのクラスタ ポートをシャットダウンして再起動し、ホーム ポートにないすべてのクラスタ LIF の自動復帰をトリガーします。


[role="tabbed-block"]
====
.キュムラス 4.4.3
--
[listing, subs="+quotes"]
----
cumulus@sw2:mgmt:~$ *net add interface swp1-14 link down*
cumulus@sw2:mgmt:~$ *net pending*
cumulus@sw2:mgmt:~$ *net commit*

(Wait for 5-10 seconds before re-enabling the ports)

cumulus@sw2:mgmt:~$ *net add interface swp1-14 link up*
cumulus@sw2:mgmt:~$ *net pending*
cumulus@sw2:mgmt:~$ *net commit*

(After executing the link state up command, the nodes detect the change and begin to auto-revert the cluster LIFs to their home ports)
----
--
.Cumulus 5.x
--
[listing, subs="+quotes"]
----
cumulus@sw2:mgmt:~$ *nv set interface swp1-14 link state down*
cumulus@sw2:mgmt:~$ *nv config apply*
cumulus@sw2:mgmt:~$ *nv show interface*

(Wait for 5-10 seconds before re-enabling the ports)

cumulus@sw2:mgmt:~$ *nv set interface swp1-14 link state up*
cumulus@sw2:mgmt:~$ *nv config apply*
cumulus@sw2:mgmt:~$ *nv show interface*

(After executing the link state up command, the nodes detect the change and begin to auto-revert the cluster LIFs to their home ports)
----
--
====
. [[step3]]クラスタLIFがホームポートに戻ったことを確認します（これには1分ほどかかる場合があります）。
+
`network interface show -vserver Cluster`

+
いずれかのクラスタ LIF がホーム ポートに戻っていない場合は、手動で戻します。LIF を所有するローカル ノードの各ノード管理 LIF またはSP/ BMCシステム コンソールに接続する必要があります。

+
`network interface revert -vserver Cluster -lif *`

. 権限レベルを管理者に戻します。
+
`set -privilege admin`

. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.次の手順
スイッチを移行した後は、 link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを設定する"]。
