---
permalink: switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched NVIDIA SN2100 cluster environment,switchless cluster environments,NVIDIA SN2100 switches 
summary: 既存の2ノードスイッチレスクラスタ環境を使用している場合は、NVIDIA SN2100スイッチを使用して2ノードスイッチクラスタ環境に移行して、3ノード以上にクラスタを拡張できます。 
---
= NVIDIA SN2100クラスタスイッチを使用する2ノードスイッチクラスタに移行します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存の2ノードスイッチレスクラスタ環境を使用している場合は、NVIDIA SN2100スイッチを使用して2ノードスイッチクラスタ環境に移行して、3ノード以上にクラスタを拡張できます。

使用する手順は、各コントローラに 2 つの専用クラスタネットワークポートがあるか、 1 つのクラスタポートがあるかによって異なります。ここで説明するプロセスは、光ポートまたはTwinaxポートを使用するすべてのノードに対応しますが、ノードでクラスタネットワークポートにオンボード10GBASE-T RJ45ポートを使用している場合、このスイッチではサポートされません。



== 要件を確認

.2ノードスイッチレス構成
次の点を確認します

* 2ノードスイッチレス構成が適切にセットアップされて機能している。
* ノードでONTAP 9.10.1P3以降が実行されている。
* すべてのクラスタポートが「稼働」状態です。
* すべてのクラスタLIF（論理インターフェイス）の状態が* up *になっていて、ホームポートにあることを確認してください。


.NVIDIA SN2100クラスタスイッチ構成
次の点を確認します

* 両方のスイッチに管理ネットワーク接続があります。
* クラスタスイッチへのコンソールアクセスがあります。
* NVIDIA SN2100ノード間スイッチおよびスイッチ間接続には、Twinaxケーブルまたはファイバケーブルを使用します。
+

IMPORTANT: を参照してください link:cabling-considerations-sn2100-cluster.html["ケーブル接続と構成に関する考慮事項を確認"] 警告および詳細については、を参照してください。。 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - スイッチ"^] ケーブル接続の詳細についても説明しています。

* スイッチ間リンク（ISL）ケーブルは、両方のNVIDIA SN2100スイッチのポートswp15およびswp16に接続されています。
* 両方のSN2100スイッチの初期カスタマイズが完了しているため、次のことが可能です。
+
** SN2100スイッチは、最新バージョンのCumulus Linuxを実行しています
** リファレンス構成ファイル（RCF）がスイッチに適用されます
** SMTP、SNMP、SSHなどのサイトのカスタマイズは、新しいスイッチで設定します。
+
。 https://hwu.netapp.com["Hardware Universe"^] プラットフォームの実際のクラスタポートに関する最新情報が含まれます。







== スイッチを移行します

.例について
この手順の例では、クラスタスイッチとノードで次の命名法を使用しています。

* SN2100スイッチの名前は_sw1_and _sw2_.です。
* クラスタ SVM の名前は、 _node1 と _node2 _ です。
* LIF の名前は、ノード 1 では _node1_clus1_AND _node1_clus2_on 、ノード 2 では _node2_clus1_and _node2_clus2_on です。
* 「 cluster1 ：： * > 」プロンプトは、クラスタの名前を示します。
* この手順 で使用されているクラスタポートは_e3aおよび_e3bです。
* ブレークアウトポートの形式は、SWP[ポート] s [ブレークアウトポート0-3]です。たとえば'swp1の4つのブレークアウトポートは'_swp1s0'_swp1s1_'_swp1s2s'_swp1s3_です




=== 手順1：移行の準備

. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。「 system node AutoSupport invoke -node * -type all -message MAINT= xh
+
ここで、 _ x _ はメンテナンス時間の長さ（時間）です。

. 権限レベルを advanced に変更します。続行するかどうかを尋ねられたら、「 y 」と入力します。「 set -privilege advanced 」
+
詳細プロンプト (`*>') が表示されます





=== 手順2：ポートとケーブルを設定する

[role="tabbed-block"]
====
.Cumulus Linux 4.4.x
--
. 新しいクラスタスイッチsw1とSW2の両方で、すべてのノード側ポート（ISLポートではない）を無効にします。
+
ISL ポートを無効にしないでください。

+
次のコマンドは、スイッチsw1およびSW2のノード側ポートを無効にします。

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*

cumulus@sw2:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
. 2つのSN2100スイッチsw1とSW2間のISL上のISLポートと物理ポートが、ポートswp15とswp16上で動作していることを確認します。
+
`net show interface`

+
次のコマンドは、スイッチsw1およびsw2でISLポートがupになっていることを示しています。

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw2 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw2 (swp16)  Master: cluster_isl(UP)

cumulus@sw2:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw1 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw1 (swp16)  Master: cluster_isl(UP)
----


--
.Cumulus Linux 5.x
--
. 新しいクラスタスイッチsw1とsw2の両方で、ノード側のポート（ISLポートではない）をすべて無効にします。
+
ISL ポートを無効にしないでください。

+
次のコマンドは、スイッチsw1およびSW2のノード側ポートを無効にします。

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set interface swp1s0-3,swp2s0-3,swp3-14 link state down*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv save*

cumulus@sw2:~$ *nv set interface swp1s0-3,swp2s0-3,swp3-14 link state down*
cumulus@sw2:~$ *nv config apply*
cumulus@sw2:~$ *nv save*
----
. 2つのSN2100スイッチsw1とSW2間のISL上のISLポートと物理ポートが、ポートswp15とswp16上で動作していることを確認します。
+
`nv show interface`

+
次の例は、スイッチsw1およびsw2でISLポートがupになっていることを示しています。

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface*

Interface     MTU    Speed  State  Remote Host  Remote Port                          Type    Summary
------------- ------ -----  ------ ------------ ------------------------------------ ------- -------
...
...
+ swp14       9216          down                                                     swp
+ swp15       9216   100G   up     ossg-rcf1    Intra-Cluster Switch ISL Port swp15  swp
+ swp16       9216   100G   up     ossg-rcf2    Intra-Cluster Switch ISL Port swp16  swp


cumulus@sw2:~$ *nv show interface*

Interface     MTU    Speed  State  Remote Host  Remote Port                          Type    Summary
------------- ------ -----  ------ ------------ ------------------------------------ ------- -------
...
...
+ swp14       9216          down                                                     swp
+ swp15       9216   100G   up     ossg-rcf1    Intra-Cluster Switch ISL Port swp15  swp
+ swp16       9216   100G   up     ossg-rcf2    Intra-Cluster Switch ISL Port swp16  swp
----


--
====
. [[step3]]すべてのクラスタポートが動作していることを確認します。
+
「 network port show 」のように表示されます

+
各ポートが表示されます `up` の場合 `Link` に対して健全です `Health Status`。

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show*

Node: node1

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. すべてのクラスタ LIF が動作していることを確認します。
+
「 network interface show 」を参照してください

+
には、各クラスタLIFにtrueと表示されます `Is Home` には、があります `Status Admin/Oper` の `up/up`。

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
====
. クラスタLIFで自動リバートを無効にします。
+
network interface modify -vserver Cluster -lif *-auto-revert false

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   false
          node1_clus2   false
          node2_clus1   false
          node2_clus2   false

----
====
. ノード1のクラスタポートe3aからケーブルを外し、SN2100スイッチでサポートされている適切なケーブル接続を使用して、クラスタスイッチsw1のポート3にe3aを接続します。
+
。 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - スイッチ"^] ケーブル接続の詳細については、を参照してください。

. ノード2のクラスタポートe3aからケーブルを外し、SN2100スイッチでサポートされている適切なケーブル接続を使用して、クラスタスイッチsw1のポート4にe3aを接続します。


[role="tabbed-block"]
====
.Cumulus Linux 4.4.x
--
. [[step8]]スイッチsw1で、すべてのノード側ポートを有効にします。
+
次のコマンドは、スイッチsw1のすべてのノード側ポートを有効にします。

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----


. [[step]]スイッチsw1で、すべてのポートが稼働していることを確認します。
+
`net show interface all`

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3a)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3a)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----


--
.Cumulus Linux 5.x
--
. [[step8]]スイッチsw1で、すべてのノード側ポートを有効にします。
+
次のコマンドは、スイッチsw1のすべてのノード側ポートを有効にします。

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set interface swp1s0-3,swp2s0-3,swp3-14 link state up*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv config save*
----


. [[step9]]スイッチsw1で、すべてのポートが稼働していることを確認します。
+
`nv show interface`

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface*

Interface    State  Speed  MTU    Type      Remote Host                 Remote Port  Summary
-----------  -----  -----  -----  --------  --------------------------  -----------  ----------
...
...
swp1s0       up     10G    9216   swp       odq-a300-1a                         e0a
swp1s1       up     10G    9216   swp       odq-a300-1b                         e0a
swp1s2       down   10G    9216   swp
swp1s3       down   10G    9216   swp
swp2s0       down   25G    9216   swp
swp2s1       down   25G    9216   swp
swp2s2       down   25G    9216   swp
swp2s3       down   25G    9216   swp
swp3         down          9216   swp
swp4         down          9216   swp
...
...
swp14        down          9216   swp
swp15        up     100G   9216   swp       ossg-int-rcf10                    swp15
swp16        up     100G   9216   swp       ossg-int-rcf10                    swp16
----


--
====
. [[step10]]すべてのクラスタポートが動作していることを確認します。
+
「 network port show -ipspace cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例は、ノード 1 とノード 2 のすべてのクラスタポートが up になっていることを示しています。

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. クラスタ内のノードのステータスに関する情報を表示します。
+
「 cluster show 」を参照してください

+
.例を示します
[%collapsible]
====
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

----
====
. ノード1のクラスタポートe3bからケーブルを外し、SN2100スイッチでサポートされている適切なケーブルを使用して、クラスタスイッチSW2のポート3にe3bを接続します。
. ノード2のクラスタポートe3bからケーブルを外し、SN2100スイッチでサポートされている適切なケーブルを使用して、クラスタスイッチSW2のポート4にe3bを接続します。


[role="tabbed-block"]
====
.Cumulus Linux 4.4.x
--
. [[step14]]スイッチSW2で、すべてのノード側ポートを有効にします。
+
次のコマンドは、スイッチSW2のノード側ポートを有効にします。

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
. [[step15]]スイッチSW2で、すべてのポートが稼働していることを確認します。
+
`net show interface all`

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3b)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3b)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----


. [[step16]]スイッチsw1とsw2の両方で、両方のノードが各スイッチに1つずつ接続されていることを確認します。
+
`net show lldp`

+
次の例は、sw1とSW2の両方のスイッチについて適切な結果を示しています。



[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  sw2                swp15
swp16      100G   BondMember  sw2                swp16

cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3b
swp4       100G   Trunk/L2    node2              e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
--
.Cumulus Linux 5.x
--
. [[step14]]スイッチSW2で、すべてのノード側ポートを有効にします。
+
次のコマンドは、スイッチSW2のノード側ポートを有効にします。

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *nv set interface swp1s0-3,swp2s0-3,swp3-14 link state up*
cumulus@sw2:~$ *nv config apply*
cumulus@sw2:~$ *nv config save*
----
. [[step15]]スイッチSW2で、すべてのポートが稼働していることを確認します。
+
`nv show interface`

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *nv show interface*

Interface    State  Speed  MTU    Type      Remote Host                 Remote Port  Summary
-----------  -----  -----  -----  --------  --------------------------  -----------  ----------
...
...
swp1s0       up     10G    9216   swp       odq-a300-1a                         e0a
swp1s1       up     10G    9216   swp       odq-a300-1b                         e0a
swp1s2       down   10G    9216   swp
swp1s3       down   10G    9216   swp
swp2s0       down   25G    9216   swp
swp2s1       down   25G    9216   swp
swp2s2       down   25G    9216   swp
swp2s3       down   25G    9216   swp
swp3         down          9216   swp
swp4         down          9216   swp
...
...
swp14        down          9216   swp
swp15        up     100G   9216   swp       ossg-int-rcf10                    swp15
swp16        up     100G   9216   swp       ossg-int-rcf10                    swp16
----


. [[step16]]スイッチsw1とsw2の両方で、両方のノードが各スイッチに1つずつ接続されていることを確認します。
+
`nv show interface --view=lldp`

+
次の例は、スイッチsw1とsw2の両方に該当する結果を示しています。

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface --view=lldp*

Interface    Speed  Type      Remote Host                         Remote Port
-----------  -----  --------  ----------------------------------  -----------
...
...
swp1s0       10G    swp       odq-a300-1a                         e0a
swp1s1       10G    swp       odq-a300-1b                         e0a
swp1s2       10G    swp
swp1s3       10G    swp
swp2s0       25G    swp
swp2s1       25G    swp
swp2s2       25G    swp
swp2s3       25G    swp
swp3                swp
swp4                swp
...
...
swp14               swp
swp15        100G   swp       ossg-int-rcf10                      swp15
swp16        100G   swp       ossg-int-rcf10                      swp16

cumulus@sw2:~$ *nv show interface --view=lldp*

Interface    Speed  Type      Remote Host                         Remote Port
-----------  -----  --------  ----------------------------------  -----------
...
...
swp1s0       10G    swp       odq-a300-1a                         e0a
swp1s1       10G    swp       odq-a300-1b                         e0a
swp1s2       10G    swp
swp1s3       10G    swp
swp2s0       25G    swp
swp2s1       25G    swp
swp2s2       25G    swp
swp2s3       25G    swp
swp3                swp
swp4                swp
...
...
swp14               swp
swp15        100G   swp       ossg-int-rcf10                      swp15
swp16        100G   swp       ossg-int-rcf10                      swp16
----


--
====
. [[step17]]クラスタ内で検出されたネットワークデバイスに関する情報を表示します。
+
`network device-discovery show -protocol lldp`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3          -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4          -
----
====
. すべてのクラスタポートが動作していることを確認します。
+
「 network port show -ipspace cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例は、ノード 1 とノード 2 のすべてのクラスタポートが up になっていることを示しています。

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

----
====




=== 手順3：構成を確認します

. すべてのクラスタLIFで自動リバートを有効にします。
+
`net interface modify -vserver Cluster -lif * -auto-revert true`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *net interface modify -vserver Cluster -lif * -auto-revert true*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
----
====
. すべてのインターフェイスに Is Home の true が表示されていることを確認します。
+
`net interface show -vserver Cluster`

+

NOTE: この処理が完了するまでに1分かかることがあります。

+
.例を示します
[%collapsible]
====
次の例では、すべての LIF がノード 1 とノード 2 で up になっていて、 Is Home の結果が true であることを示します。

[listing, subs="+quotes"]
----
cluster1::*> *net interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true

----
====
. 設定が無効になっていることを確認します。
+
network options switchless-cluster show

+
.例を示します
[%collapsible]
====
次の例の誤った出力は、設定が無効になっていることを示しています。

[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: *false*
----
====
. クラスタ内のノードメンバーのステータスを確認します。
+
「 cluster show 」を参照してください

+
.例を示します
[%collapsible]
====
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. リモートクラスタインターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
を使用できます `network interface check cluster-connectivity` コマンドを使用してクラスタ接続のアクセスチェックを開始し、詳細を表示します。

`network interface check cluster-connectivity start` および `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注：*数秒待ってからコマンドを実行して `show`詳細を表示してください。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.すべてのONTAPリリース
--
すべてのONTAPリリースで、 `cluster ping-cluster -node <name>` 接続を確認するコマンド：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node1
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step6]]権限レベルをadminに戻します。
+
「特権管理者」

. ケースの自動作成を抑制した場合は、 AutoSupport メッセージを呼び出して作成を再度有効にします。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます



.次の手順
link:../switch-cshm/config-overview.html["スイッチヘルス監視の設定"]です。
