---
permalink: switch-nvidia-sn2100/replace-sn2100-switch-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia sn2100 cluster switch - nvidia SN2100 
summary: 障害のあるNVIDIA SN2100ストレージスイッチを無停止手順 \（NDU \）で交換します。 
---
= NVIDIA SN2100ストレージスイッチを交換してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIA SN2100ストレージスイッチを交換する場合は、特定の構成情報、ポート接続、およびケーブル接続の要件に注意する必要があります。

.作業を開始する前に
NVIDIA SN2100ストレージスイッチにCumulusソフトウェアとRCFをインストールする前に、次の条件が満たされていることを確認する必要があります。

* お使いのシステムではNVIDIA SN2100ストレージスイッチをサポートできます。
* 該当する RCF をダウンロードしておく必要があります。
* 。 http://hwu.netapp.com["Hardware Universe"^] サポートされているポートとその構成の詳細が表示されます。


.このタスクについて
既存のネットワーク構成には、次のような特徴があります。

* スイッチの交換が必要かどうかを確認するために、すべてのトラブルシューティング手順が完了していることを確認します。
* 両方のスイッチで管理接続が確立されている必要があります。
+

NOTE: スイッチの交換が必要かどうかを確認するために、すべてのトラブルシューティング手順が完了していることを確認します。



交換用NVIDIA SN2100スイッチには次の特性が必要です。

* 管理ネットワーク接続が機能している必要があります。
* 交換用スイッチへのコンソールアクセスが確立されている必要があります。
* 適切なRCFおよびCumulusオペレーティングシステムイメージをスイッチにロードする必要があります。
* スイッチの初期カスタマイズが完了している必要があります。


.手順のまとめ
この手順 は、2台目のNVIDIA SN2100ストレージスイッチSW2を新しいNVIDIA SN2100スイッチnsw2に置き換えます。2 つのノードは node1 と node2 になります。

完了する手順：

* 交換するスイッチがSW2であることを確認します。
* スイッチSW2からケーブルを外します。
* スイッチnsw2にケーブルを再接続します。
* スイッチnsw2のすべてのデバイス設定を確認します。


.手順
. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。「 system node AutoSupport invoke -node * -type all -message MAINT= xh
+
_x_ は、メンテナンス時間の長さ（時間単位）です。

. 権限レベルを advanced に変更します。続行するかどうかを尋ねられたら、「 * y * 」と入力します。「 set -privilege advanced 」
. ストレージノードポートのヘルスステータスをチェックして、ストレージスイッチ S1 に接続されていることを確認します。
+
storage port show -port-type enet

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. ストレージ・スイッチsw1が使用可能であることを確認しますnetwork device-discovery show
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show protocol lldp*
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface   Platform
--------   ----  -----------------------   ---------   ---------
node1/lldp
           e3a   sw1 (b8:ce:f6:19:1b:42)   swp3        -
node2/lldp
           e3a   sw1 (b8:ce:f6:19:1b:42)   swp4        -
cluster1::*>
----
====
. 動作中のスイッチでnet show interfaceコマンドを実行して'ノードとすべてのシェルフの両方が表示されることを確認しますnet show interface
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e3a)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e3a)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. ストレージ・システムのシェルフ・ポートを確認しますstorage shelf port show -fields remote-device、remote-port
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   swp3          sw1
3.20    1   -             -
3.20    2   swp4          sw1
3.20    3   -             -
3.30    0   swp5          sw1
3.20    1   -             -
3.30    2   swp6          sw1
3.20    3   -             -
cluster1::*>
----
====
. ストレージスイッチSW2に接続されているすべてのケーブルを取り外します。
. 交換用スイッチnsw2にすべてのケーブルを再接続します。
. ストレージノードポートのヘルスステータスを再確認します storage port show -port -type enet
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. 両方のスイッチが使用可能であることを確認します:net device-discovery show
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show protocol lldp*
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
node1/lldp
          e3a  sw1 (b8:ce:f6:19:1b:96)    swp1        -
          e7b  nsw2 (b8:ce:f6:19:1a:7e)   swp1        -
node2/lldp
          e3a  sw1 (b8:ce:f6:19:1b:96)    swp2        -
          e7b  nsw2 (b8:ce:f6:19:1a:7e)   swp2        -
cluster1::*>
----
====
. ストレージ・システムのシェルフ・ポートを確認しますstorage shelf port show -fields remote-device、remote-port
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     swp3            sw1
3.20    1     swp3            nsw2
3.20    2     swp4            sw1
3.20    3     swp4            nsw2
3.30    0     swp5            sw1
3.20    1     swp5            nsw2
3.30    2     swp6            sw1
3.20    3     swp6            nsw2
cluster1::*>
----
====
. イーサネットスイッチヘルスモニタのログ収集機能のパスワードを作成します。
+
「システムスイッチイーサネットログセットアップ - パスワード」

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*sw1*
*nsw2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *csw1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *nsw2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. イーサネットスイッチヘルスモニタのログ収集機能を有効にします。
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
10分待ってから、ログ収集が完了したことを確認します。

+
`system switch ethernet log show`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> system switch ethernet log show
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------  ---------    
1      sw1  (b8:ce:f6:19:1b:42)     4/29/2022 03:05:25   complete   
2      nsw2 (b8:ce:f6:19:1b:96)     4/29/2022 03:07:42   complete
----
====
+

CAUTION: これらのコマンドのいずれかでエラーが返された場合、またはログの収集が完了しない場合は、NetAppサポートにお問い合わせください。

. 特権レベルを admin に戻します。 'et -privilege admin'
. ケースの自動作成を抑制した場合は、 AutoSupport メッセージ「 system node AutoSupport invoke -node * -type all -message MAINT=end 」を呼び出して作成を再度有効にします

