---
permalink: switch-nvidia-sn2100/replace-sn2100-switch-cluster.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia msn2100 cluster switch - nvidia SN2100 
summary: クラスタネットワーク内の不良なNVIDIA SN2100スイッチの交換は、無停止手順 （NDNDU）です。 
---
= NVIDIA SN2100クラスタスイッチを交換してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタネットワーク内の不良なNVIDIA SN2100スイッチを交換するには、この手順 に従います。これは、無停止の手順 （NDU；非停止アップグレード）です。



== 要件を確認

.既存のクラスタとネットワークインフラ
次の点を確認します

* 既存のクラスタは、少なくとも1つのクラスタスイッチが完全に接続された状態で、完全に機能することが確認されています。
* すべてのクラスタポートが稼働している必要があります
* すべてのクラスタLIFが、upの状態でホームポートにあることを確認します。
* ONTAP `cluster ping-cluster -node node1` コマンドは、基本的な接続とPMTU以上の通信がすべてのパスで成功したことを示します。


.NVIDIA SN2100交換用スイッチ
次の点を確認します

* 交換用スイッチの管理ネットワーク接続は機能しています。
* 交換用スイッチへのコンソールアクセスが確立されている。
* ノード接続は、ポートswp1からswp14です。
* ポートswp15およびswp16では、すべてのスイッチ間リンク（ISL）ポートが無効になっています。
* 目的のリファレンス構成ファイル（RCF）とCumulusオペレーティングシステムイメージスイッチがスイッチにロードされます。
* スイッチの初期カスタマイズが完了しました。


また、STP、SNMP、SSHなどの以前のサイトカスタマイズがすべて新しいスイッチにコピーされていることを確認します。


NOTE: クラスタ LIF を移行するコマンドは、そのクラスタ LIF がホストされているノードで実行する必要があります。



== スイッチを交換します

.例について
この手順の例では、スイッチとノードで次の命名法を使用しています。

* 既存のNVIDIA SN2100スイッチの名前は_sw1_AND _sw2_です。
* 新しいNVIDIA SN2100スイッチの名前は_nsw2_.
* ノード名は _node1_AND _node2 _ です。
* 各ノードのクラスタポートの名前は _e3a および _e3b _ です。
* クラスタLIFの名前は、ノード1の場合は_node1_clus1_AND _node1_clus2_(1つ)、ノード2の場合は_node2_clus1_and _node2_clus2_(1つ)です。
* すべてのクラスタ・ノードへの変更を求めるプロンプトは、'cluster1：*>`です
* ブレークアウトポートの形式は、SWP[ポート] s [ブレークアウトポート0-3]です。たとえば'swp1の4つのブレークアウトポートは'_swp1s0'_swp1s1_'_swp1s2s'_swp1s3_です


.クラスタネットワークトポロジについて
この手順 は、次のクラスタネットワークトポロジに基づいています。

.トポロジの例を表示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false


cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true


cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3          -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4          -
----
[+]

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    sw2                e3a
swp4       100G   Trunk/L2    sw2                e3a
swp15      100G   BondMember  sw2                swp15
swp16      100G   BondMember  sw2                swp16


cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    sw1                e3b
swp4       100G   Trunk/L2    sw1                e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
====


=== 手順1：交換の準備をします

. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= xh 」というメッセージが表示されます

+
ここで、 _ x _ はメンテナンス時間の長さ（時間）です。

. 権限レベルを advanced に変更します。続行するかどうかを尋ねられたら、「 * y * 」と入力します。
+
「 advanced 」の権限が必要です

+
advanced のプロンプト（ * > ）が表示されます。

. 適切なRCFとイメージをスイッチnsw2にインストールし、必要なサイトの準備を行います。
+
必要に応じて、新しいスイッチ用のRCFおよびCumulusソフトウェアの適切なバージョンを確認、ダウンロード、およびインストールします。

+
.. ご使用のクラスタスイッチに適用可能なCumulusソフトウェアは、_nvidia Support_siteからダウンロードできます。ダウンロードページの手順に従って、インストールするONTAP ソフトウェアのバージョンに対応したCumulus Linuxをダウンロードします。
.. 適切な RCF はから入手できます link:https://mysupport.netapp.com/site/products/all/details/nvidia-cluster-storage-switch/downloads-tab["NVIDIAクラスタとストレージスイッチ_"^] ページダウンロードページの手順に従って、インストールする ONTAP ソフトウェアのバージョンに対応する正しい RCF をダウンロードします。






=== 手順2：ポートとケーブルを設定する

. 新しいスイッチnsw2にadminとしてログインし、ノードクラスタインターフェイス（ポートswp1からswp14）に接続するすべてのポートをシャットダウンします。
+
クラスタノードの LIF は、各ノードのもう一方のクラスタポートにすでにフェイルオーバーされている必要があります。

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@nsw2:~$ *net pending*
cumulus@nsw2:~$ *net commit*
----
====
. クラスタLIFで自動リバートを無効にします。
+
network interface modify -vserver Cluster -lif *-auto-revert false

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

Warning: Disabling the auto-revert feature of the cluster logical interface may effect the availability of your cluster network. Are you sure you want to continue? {y|n}: *y*
----
====
. すべてのクラスタ LIF で自動リバートが有効になっていることを確認します。
+
`net interface show -vserver Cluster -fields auto-revert`

. SN2100スイッチsw1でISLポートswp15およびswp16をシャットダウンします。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp15-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. すべてのケーブルをSN2100 sw1スイッチから取り外し、SN2100 nsw2スイッチの同じポートに接続します。
. sw1スイッチとnsw2スイッチの間で、ISLポートswp15とswp16を起動します。
+
.例を示します
[%collapsible]
====
次のコマンドは、スイッチsw1でISLポートswp15およびswp16を有効にします。

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp15-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
次の例は、スイッチsw1のISLポートがupになっていることを示しています。

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------- ----------------------
...
...
UP     swp15        100G  9216   BondMember  nsw2 (swp15)   Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  nsw2 (swp16)   Master: cluster_isl(UP)
----
+次の例は、スイッチnsw2のISLポートがupになっていることを示しています。

[+]

[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------  -----------------------
...
...
UP     swp15        100G  9216   BondMember  sw1 (swp15)    Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)    Master: cluster_isl(UP)
----
====
. ポートを確認します `e3b` すべてのノードで動作：
+
「 network port show -ipspace cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
次のような出力が表示されます。

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                         Ignore
                                                   Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ----- ------------ -------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false


Node: node2
                                                                         Ignore
                                                   Speed(Mbps) Health    Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status    Status
--------- ------------ ---------------- ---- ----- ----------- --------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false
----
====
. これで、各ノードのクラスタポートは、ノードから見て次のようにクラスタスイッチに接続されました。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp3          -
node2      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp4          -
----
====
. すべてのノードクラスタポートが動作していることを確認します。
+
`net show interface`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
====
. 両方のノードのそれぞれで、各スイッチに 1 つの接続があることを確認します。
+
`net show lldp`

+
.例を示します
[%collapsible]
====
次の例は、両方のスイッチの該当する結果を示しています。

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  nsw2               swp15
swp16      100G   BondMember  nsw2               swp16


cumulus@nsw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1                e3b
swp4       100G   Trunk/L2    node2                e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
====
. クラスタ LIF で自動リバートを有効にします。
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. スイッチnsw2で、ノードのネットワークポートに接続されているポートを起動します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net del interface swp1-14 link down*
cumulus@nsw2:~$ *net pending*
cumulus@nsw2:~$ *net commit*
----
====
. クラスタ内のノードに関する情報を表示します。
+
「 cluster show 」を参照してください

+
.例を示します
[%collapsible]
====
次の例では、このクラスタのノード node1 と node2 のノードの健常性が true であることを示します。

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node          Health  Eligibility
------------- ------- ------------
node1         true    true
node2         true    true
----
====
. すべての物理クラスタポートが動作していることを確認します。
+
「 network port show -ipspace cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node node1                                                               Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace     Broadcast Domain  Link  MTU   Admin/Oper  Status   Status
--------- ----------- ----------------- ----- ----- ----------- -------- ------
e3a       Cluster     Cluster           up    9000  auto/10000  healthy  false
e3b       Cluster     Cluster           up    9000  auto/10000  healthy  false

Node: node2
                                                                         Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link  MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ----- ----- ----------- -------- ------
e3a       Cluster      Cluster          up    9000  auto/10000  healthy  false
e3b       Cluster      Cluster          up    9000  auto/10000  healthy  false
----
====




=== 手順3：手順 を完了します

. クラスタネットワークが正常であることを確認します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost      RemotePort
---------  -----  ----------  --------------  -----------
swp3       100G   Trunk/L2    node1           e3a
swp4       100G   Trunk/L2    node2           e3a
swp15      100G   BondMember  nsw2            swp15
swp16      100G   BondMember  nsw2            swp16
----
====
. イーサネットスイッチヘルスモニタのログ収集機能のパスワードを作成します。
+
「システムスイッチイーサネットログセットアップ - パスワード」

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. イーサネットスイッチヘルスモニタのログ収集機能を有効にします。
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
10分待ってから、ログ収集が完了したことを確認します。

+
`system switch ethernet log show`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> system switch ethernet log show
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------  ---------    
1      cs1 (b8:ce:f6:19:1b:42)      4/29/2022 03:05:25   complete   
2      cs2 (b8:ce:f6:19:1b:96)      4/29/2022 03:07:42   complete
----
====
+

CAUTION: これらのコマンドのいずれかでエラーが返された場合、またはログの収集が完了しない場合は、NetAppサポートにお問い合わせください。

. 権限レベルを admin に戻します。
+
「特権管理者」

. ケースの自動作成を抑制した場合は、 AutoSupport メッセージを呼び出して作成を再度有効にします。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます


