---
permalink: switch-nvidia-sn2100/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, ontap, install the cluster switch health monitor (csm) configuration file for SN2100 switches' 
summary: この手順を使用して、 NVIDIA SN2100 クラスタ スイッチのクラスタ スイッチ ヘルス モニタリングに適した構成ファイルをインストールできます。 
---
= イーサネットスイッチヘルスモニタ構成ファイルをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIAイーサネット スイッチでイーサネット スイッチのヘルス モニタリングを構成するには、次の手順に従います。

これらの手順は、 NVIDIA X190006-PEおよびX190006-PIスイッチが正しく検出されない場合に適用されます。これは、実行することで確認できます。 `system switch ethernet show`モデルに *OTHER* が表示されているかどうかを確認します。  NVIDIAスイッチのモデルを識別するには、次のコマンドで部品番号を見つけます。 `nv show platform hardware` NVIDIA CL 5.8以前の場合、または `nv show platform`それ以降のバージョンの場合。

[NOTE]
====
次のONTAPリリースでNVIDIA CL 5.11.x を使用するときに、ヘルス モニタリングとログ収集を意図したとおりに機能させたい場合は、これらの手順も推奨されます。これらの手順を実行しなくてもヘルス監視とログ収集は機能する可能性がありますが、これらの手順を実行することですべてが正しく動作することが保証されます。

* 9.10.1P20、9.11.1P18、9.12.1P16、9.13.1P8、9.14.1、9.15.1以降のパッチリリース


====
.開始する前に
* ONTAPクラスタが起動して実行されていることを確認します。
* CSHM で利用可能なすべての機能を使用するには、スイッチで SSH を有効にします。
* クリア `/mroot/etc/cshm_nod/nod_sign/`すべてのノード上のディレクトリ:
+
.. ノードシェルに入ります:
+
`system node run -node <name>`

.. 高度な権限に変更:
+
`priv set advanced`

.. 設定ファイルを一覧表示する `/etc/cshm_nod/nod_sign`ディレクトリ。ディレクトリが存在し、そこに設定ファイルが含まれている場合は、ファイル名が一覧表示されます。
+
`ls /etc/cshm_nod/nod_sign`

.. 接続されているスイッチ モデルに対応するすべての構成ファイルを削除します。
+
不明な場合は、上記のサポート対象モデルのすべての構成ファイルを削除してから、同じモデルの最新の構成ファイルをダウンロードしてインストールしてください。

+
`rm /etc/cshm_nod/nod_sign/<filename>`

.. 削除された構成ファイルがディレクトリ内に存在しないことを確認します。
+
`ls /etc/cshm_nod/nod_sign`





.手順
. 対応するONTAPリリース バージョンに基づいて、イーサネット スイッチ ヘルス モニタ構成の zip ファイルをダウンロードします。このファイルは、 https://mysupport.netapp.com/site/info/nvidia-cluster-switch["NVIDIAイーサネットスイッチ"^]ページ。
+
.. NVIDIA SN2100 ソフトウェアのダウンロード ページで、*Nvidia CSHM ファイル* を選択します。
.. 「注意/必読」ページでチェックボックスを選択して同意します。
.. エンド ユーザー ライセンス契約ページで、同意するチェック ボックスをオンにして、[同意して続行] をクリックします。
.. Nvidia CSHM ファイル - ダウンロード ページで、該当する構成ファイルを選択します。利用可能なファイルは次のとおりです。




[role="tabbed-block"]
====
.ONTAP 9.15.1以降
--
* MSN2100-CB2FC-v1.4.zip
* MSN2100-CB2RC-v1.4.zip
* X190006-PE-v1.4.zip
* X190006-PI-v1.4.zip


--
.ONTAP 9.11.1 から 9.14.1
--
* MSN2100-CB2FC_PRIOR_R9.15.1-v1.4.zip
* MSN2100-CB2RC_PRIOR_R9.15.1-v1.4.zip
* X190006-PE_PRIOR_9.15.1-v1.4.zip
* X190006-PI_PRIOR_9.15.1-v1.4.zip


--
====
. [[step2]]該当するzipファイルを社内のWebサーバーにアップロードします。
. クラスタ内のいずれかのONTAPシステムから詳細モード設定にアクセスします。
+
`set -privilege advanced`

. スイッチ ヘルス モニター構成コマンドを実行します。
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet*
----
. コマンド出力が、使用しているONTAPバージョンに応じて次のテキストで終了していることを確認します。


[role="tabbed-block"]
====
.ONTAP 9.15.1以降
--
イーサネット スイッチのヘルス モニタリング構成ファイルがインストールされました。

--
.ONTAP 9.11.1 から 9.14.1
--
SHM は構成ファイルをインストールしました。

--
.ONTAP 9.10.1
--
CSHM ダウンロード パッケージが正常に処理されました。

--
====
エラーが発生した場合は、NetAppサポートにお問い合わせください。

. [[step6]]イーサネットスイッチヘルスモニターのポーリング間隔の2倍まで待機します。 `system switch ethernet polling-interval show`次のステップを完了する前に、 をクリックしてください。
. コマンドを実行する `system switch ethernet show`ONTAPシステムで、監視対象フィールドが *True* に設定され、シリアル番号フィールドに *Unknown* が表示されていない状態でクラスタ スイッチが検出されていることを確認します。
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
----



NOTE: 構成ファイルを適用した後もモデルに *OTHER* が表示される場合は、 NetAppサポートにお問い合わせください。

参照 https://docs.netapp.com/us-en/ontap-cli/system-switch-ethernet-configure-health-monitor.html["システムスイッチイーサネットヘルスモニターの設定"^]詳細についてはコマンドを参照してください。

.次の手順
link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを構成する"] 。
