---
permalink: switch-cisco-9336c-fx2/index.html 
sidebar: sidebar 
keywords: cisco, switch, cisco 9336 switch 
summary: 'Cisco 9336-FX2` スイッチ' 
---
= 概要と要件：Cisco Nexus 9336C-FX2スイッチ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9336C-FX2スイッチの設置とメンテナンスについては、設定要件とマニュアル要件を確認してください。

3 つ以上のノードで ONTAP クラスタを構築する場合は、サポートされている 2 つのクラスタネットワークスイッチが必要です。オプションとして、追加の管理スイッチを使用できます。

Cisco Nexus 9336C-FX2 スイッチ（ X190200/X190210 ）は、スイッチに付属の標準ブラケットを使用して、ネットアップシステムキャビネットまたは他社製キャビネットに設置できます。



== スイッチのコンポーネント

次の表に、 9336C-FX2 スイッチ、ファン、および電源装置の部品番号と概要を示します。

[cols="1,2"]
|===
| パーツ番号 | 説明 


 a| 
X190200-CS-PE
 a| 
N9K-9336C-FX2 、 CS 、 PTSX 、 36PT10/25/40/100GQSFP28



 a| 
X190200-CS-PI
 a| 
N9K-9336C-FX2 、 CS 、 PSIN 、 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PE のこと
 a| 
N9K-9336C 、 FTE 、 PTSX 、 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C 、 FTE 、 PSIN 、 36PT10/25/40/100GQSFP28



 a| 
X190002
 a| 
アクセサリキット X190001/X190003



 a| 
X-NXA-PAC1100W-PE2
 a| 
N9K-9336C AC 1100W PSU - ポート側排気



 a| 
X-NXA-PAC1100W-PI2
 a| 
N9K-9336C AC 1100W PSU - ポート側吸気



 a| 
X-NXA-FAN-65CFM-pe
 a| 
N9K-9336C 65CFM 、ポート側排気



 a| 
X-NXA-FAN-65CFM-pi
 a| 
N9K-9336C 65CFM 、ポート側吸気

|===


== 設定要件

クラスタを設定するには、スイッチに適切な数とタイプのケーブルとコネクタが必要です。最初に設定するスイッチのタイプに応じて、付属のコンソールケーブルを使用してスイッチのコンソールポートに接続する必要があります。また、特定のネットワーク情報を指定する必要があります。



== ネットワーク要件

すべてのスイッチ設定には、次のネットワーク情報が必要です。

* 管理ネットワークトラフィック用の IP サブネット
* 各ストレージシステムコントローラおよび該当するすべてのスイッチのホスト名と IP アドレス
* ほとんどのストレージシステムコントローラは、イーサネットサービスポート（レンチマーク）に接続することで、 e0M インターフェイスを介して管理されます。AFF A800 システムおよび AFF A700 システムでは、 e0M インターフェイスは専用のイーサネットポートを使用します。


を参照してください https://["Hardware Universe"^] 最新情報については、



== Smart Call Homeの要件

Smart Call Home は、ネットワーク上のハードウェアおよびソフトウェアコンポーネントを監視し、重大なシステム状態に関する電子メールベースの通知を生成します。デバイスでイベントが発生すると、 Smart Call Home は宛先プロファイルで設定されているすべての受信者にアラートを送信します。

E メールを使用して Smart Call Home システムと通信するように、クラスタネットワークスイッチを設定する必要があります。必要に応じて、 Cisco の組み込み Smart Call Home サポート機能を利用するように、クラスタネットワークスイッチをセットアップできます。

Smart Call Home 機能を使用する前に、次の考慮事項について理解しておく必要があります。

* E メールサーバが配置されている必要があります。
* スイッチは、 E メールサーバに IP 接続されている必要があります。
* 連絡先名（ SNMP サーバの連絡先）、電話番号、住所情報が設定されている必要があります。これは、受信したメッセージの送信元を判別するために必要です。
* 会社の適切な Cisco SMARTnet サービス契約に、 CCO ID を関連付ける必要があります。
* デバイスを登録するには、 Cisco SMARTnet サービスが導入されている必要があります。


。 http://["シスコサポートサイト"^] Smart Call Homeを設定するコマンドについて説明します。



== ドキュメントの要件

Cisco 9336-FX2スイッチとONTAP クラスタをセットアップするには、特定のスイッチおよびコントローラのマニュアルが必要です。



=== スイッチのドキュメント

Cisco Nexus 9336C-FX2スイッチをセットアップするには、から次のマニュアルを入手する必要があります https://["Cisco Nexus 9000 シリーズスイッチのサポート"^] ページ

[cols="1,2"]
|===
| ドキュメントタイトル | 説明 


 a| 
_ Nexus 9000 Series Hardware Installation Guide _
 a| 
サイト要件、スイッチハードウェアの詳細、およびインストールオプションに関する詳細情報を提供します。



 a| 
_Cisco Nexus 9000 Series Switch Software Configuration Guides _ （スイッチにインストールされている NX-OS リリースのガイドを選択）
 a| 
スイッチを ONTAP 動作用に設定する前に必要なスイッチの初期設定に関する情報を提供します。



 a| 
_Cisco Nexus 9000 シリーズ NX-OS ソフトウェアアップグレードおよびダウングレードガイド _ （スイッチにインストールされている NX-OS リリースのガイドを選択）
 a| 
必要に応じてスイッチを ONTAP 対応スイッチソフトウェアにダウングレードする方法について説明します。



 a| 
_Cisco Nexus 9000 シリーズ NX-OS コマンドリファレンスマスターインデックス _
 a| 
シスコが提供するさまざまなコマンドリファレンスへのリンクを示します。



 a| 
_Cisco Nexus 9000 MIB リファレンス _
 a| 
Nexus 9000 スイッチの管理情報ベース（ MIB ）ファイルについて説明します。



 a| 
_Nexus 9000 シリーズ NX-OS システムメッセージリファレンス _
 a| 
Cisco Nexus 9000 シリーズスイッチのシステムメッセージ、情報メッセージ、およびリンク、内部ハードウェア、またはシステムソフトウェアの問題の診断に役立つその他のメッセージについて説明します。



 a| 
_Cisco Nexus 9000 Series NX-OS Release Notes （スイッチにインストールされている NX-OS リリースのノートを選択） _
 a| 
Cisco Nexus 9000 シリーズの機能、バグ、および制限事項について説明します。



 a| 
Cisco Nexus 9000 シリーズの適合規格および安全性に関する情報
 a| 
Nexus 9000 シリーズスイッチの国際的な適合規格、安全性、および法令に関する情報を提供します。

|===


=== ONTAP システムのドキュメント

ONTAP システムをセットアップするには、使用しているオペレーティングシステムのバージョンに応じて、で次のドキュメントを参照する必要があります https://["ONTAP 9 ドキュメンテーション・センター"^]。

[cols="1,2"]
|===
| 名前 | 説明 


 a| 
コントローラ固有の設置およびセットアップ手順 _
 a| 
ネットアップハードウェアの設置方法について説明します。



 a| 
ONTAP のドキュメント
 a| 
ONTAP リリースのすべての側面に関する詳細情報を提供します。



 a| 
https://["Hardware Universe"^]
 a| 
ネットアップハードウェアの構成と互換性に関する情報を提供します。

|===


=== レールキットおよびキャビネットのドキュメント

Cisco 9336-FX2スイッチをネットアップキャビネットに設置するには、次のハードウェアマニュアルを参照してください。

[cols="1,2"]
|===
| 名前 | 説明 


 a| 
https://["『 42U System Cabinet 、 Deep Guide 』を参照してください"^]
 a| 
42U システムキャビネットに関連する FRU について説明し、メンテナンスおよび FRU の交換手順を示します。



 a| 
link:install-switch-and-passthrough-panel.html["NetAppキャビネットにCisco 9336-FX2スイッチを設置します"^]
 a| 
4ポストのネットアップキャビネットにCisco Nexus 9336C-FX2スイッチを設置する方法について説明します。

|===