---
permalink: switch-cisco-9336c-fx2-storage/install-rcf-software-9336c-storage.html 
sidebar: sidebar 
keywords: install rcf, cisco switches, storage 
summary: Nexus 9336C-FX2 ストレージ スイッチを初めてセットアップした後、RCF をインストールできます。この手順を使用して、RCF バージョンをアップグレードすることもできます。 
---
= 参照設定ファイルをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nexus 9336C-FX2 および 9336C-FX2-T ストレージ スイッチを初めてセットアップした後、リファレンス構成ファイル (RCF) をインストールします。

ナレッジベースの記事を参照link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["リモート接続を維持しながらCiscoインターコネクトスイッチの設定をクリアする方法"^]RCF をインストールする際の詳細については、こちらをご覧ください。

.開始する前に
次のインストールと接続を確認します。

* スイッチへのコンソール接続。スイッチにリモートアクセスできる場合、コンソール接続はオプションです。
* スイッチ s1 とスイッチ s2 の電源がオンになり、スイッチの初期セットアップが完了します（Management IP アドレスと SSH がセットアップされています）。
* 必要な NX-OS バージョンがインストールされました。
* ONTAP ノード ストレージ ポートとストレージ シェルフ ポートが接続されていません。




== ステップ1: スイッチにRCFをインストールする

. SSH またはシリアル コンソールを使用してスイッチ s2 にログインします。
. FTP、TFTP、SFTP、SCPのいずれかの転送プロトコルを使用して、スイッチs2のブートフラッシュにRCFをコピーします。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 シリーズ NX-OS コマンド リファレンス"^] 。

+
.例を表示
[%collapsible]
====
この例では、TFTPを使用してスイッチs2のブートフラッシュにRCFをコピーしています。

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9336C-FX2-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 前の手順でブートフラッシュにダウンロードしたRCFを適用します。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 シリーズ NX-OS コマンド リファレンス"^] 。

+
.例を表示
[%collapsible]
====
この例では、スイッチ s2 に RCF `NX9336C-FX2-RCF-v1.13-1-Storage.txt` がインストールされています：

[listing]
----
s2# copy NX9336C-FX2-RCF-v1.13-1-Storage.txt running-config echo-commands
----
====
. バナー出力を調べる `show banner motd`指示。スイッチを正しく構成し、操作するには、これらの手順を読んで従う必要があります。
+
.例を表示
[%collapsible]
====
[listing]
----
s2# show banner motd

**********************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch    : NX9336C-FX2
* Filename  : NX9336C-FX2-RCF-v1.13-1-Storage.txt
* Date      : 05-22-2025
* Version   : v1.13
*
* Port Usage : Storage configuration
* Ports  1-36: 100GbE Controller and Shelf Storage Ports
*
* IMPORTANT NOTES
*
* Interface port-channel999 is reserved to identify the version of this file.
**********************************************************
----
====
. RCF が正しい新しいバージョンであることを確認します。
+
`show running-config`

+
次の情報が正しいことを確認してください。

+
** RCFのバナー
** ノードとポートの設定
** カスタマイズ
+
出力内容はサイトの構成によって異なります。ポートの設定を確認し、インストールしたRCFに固有の変更がないかリリース ノートを参照してください。



. 現在のカスタム追加を記録します `running-config`ファイルと使用中の RCF ファイル。
. RCFのバージョンとスイッチの設定が正しいことを確認したら、 `running-config`ファイルに `startup-config`ファイル。
+
[listing]
----
s2# copy running-config startup-config [########################################] 100% Copy complete
----
. スイッチs2をリブートします。
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. スイッチ s1 で手順 1 ～ 8 を繰り返します。
. ONTAP クラスタ内のすべてのノードのノード ストレージ ポートとストレージ シェルフ ポートをスイッチ s1 と s2 に接続します。




== ステップ2: スイッチの接続を確認する

. スイッチ ポートが *up* であることを確認します。
+
`show interface brief`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
s1# *show interface brief | grep up*
mgmt0  --           up     _<mgmt ip address>_                       1000    1500
Eth1/11         1       eth  trunk  up      none                     100G(D) --
Eth1/12         1       eth  trunk  up      none                     100G(D) --
Eth1/13         1       eth  trunk  up      none                     100G(D) --
Eth1/14         1       eth  trunk  up      none                     100G(D) --
Eth1/15         1       eth  trunk  up      none                     100G(D) --
Eth1/16         1       eth  trunk  up      none                     100G(D) --
Eth1/17         1       eth  trunk  up      none                     100G(D) --
Eth1/18         1       eth  trunk  up      none                     100G(D) --
Eth1/23         1       eth  trunk  up      none                     100G(D) --
Eth1/24         1       eth  trunk  up      none                     100G(D) --
Eth1/25         1       eth  trunk  up      none                     100G(D) --
Eth1/26         1       eth  trunk  up      none                     100G(D) --
Eth1/27         1       eth  trunk  up      none                     100G(D) --
Eth1/28         1       eth  trunk  up      none                     100G(D) --
Eth1/29         1       eth  trunk  up      none                     100G(D) --
Eth1/30         1       eth  trunk  up      none                     100G(D) --
----
====
. 次のコマンドを使用して、ノード ストレージ ポートとストレージ シェルフ ポートが正しい VLAN にあることを確認します：
+
`show vlan brief`

+
`show interface trunk`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
s1# *show vlan brief*

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po999
30   VLAN0030                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/19, Eth1/20
                                                Eth1/21, Eth1/22, Eth1/23
                                                Eth1/24, Eth1/25, Eth1/26
                                                Eth1/27, Eth1/28, Eth1/29
                                                Eth1/30, Eth1/31, Eth1/32
                                                Eth1/33, Eth1/34, Eth1/35
                                                Eth1/36

s1# *show interface trunk*

-----------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
-----------------------------------------------------
Eth1/1        1       trunking      --
Eth1/2        1       trunking      --
Eth1/3        1       trunking      --
Eth1/4        1       trunking      --
Eth1/5        1       trunking      --
Eth1/6        1       trunking      --
Eth1/7        1       trunking      --
Eth1/8        1       trunking      --
Eth1/9        1       trunking      --
Eth1/10       1       trunking      --
Eth1/11       1       trunking      --
Eth1/12       1       trunking      --
Eth1/13       1       trunking      --
Eth1/14       1       trunking      --
Eth1/15       1       trunking      --
Eth1/16       1       trunking      --
Eth1/17       1       trunking      --
Eth1/18       1       trunking      --
Eth1/19       1       trunking      --
Eth1/20       1       trunking      --
Eth1/21       1       trunking      --
Eth1/22       1       trunking      --
Eth1/23       1       trunking      --
Eth1/24       1       trunking      --
Eth1/25       1       trunking      --
Eth1/26       1       trunking      --
Eth1/27       1       trunking      --
Eth1/28       1       trunking      --
Eth1/29       1       trunking      --
Eth1/30       1       trunking      --
Eth1/31       1       trunking      --
Eth1/32       1       trunking      --
Eth1/33       1       trunking      --
Eth1/34       1       trunking      --
Eth1/35       1       trunking      --
Eth1/36       1       trunking      --

--------------------------------------------------------------------------------
Port          Vlans Allowed on Trunk
--------------------------------------------------------------------------------
Eth1/1        30
Eth1/2        30
Eth1/3        30
Eth1/4        30
Eth1/5        30
Eth1/6        30
Eth1/7        30
Eth1/8        30
Eth1/9        30
Eth1/10       30
Eth1/11       30
Eth1/12       30
Eth1/13       30
Eth1/14       30
Eth1/15       30
Eth1/16       30
Eth1/17       30
Eth1/18       30
Eth1/19       30
Eth1/20       30
Eth1/21       30
Eth1/22       30
Eth1/23       30
Eth1/24       30
Eth1/25       30
Eth1/26       30
Eth1/27       30
Eth1/28       30
Eth1/29       30
Eth1/30       30
Eth1/31       30
Eth1/32       30
Eth1/33       30
Eth1/34       30
Eth1/35       30
Eth1/36       30

--------------------------------------------------------------------------------
Port          Vlans Err-disabled on Trunk
--------------------------------------------------------------------------------
Eth1/1        none
Eth1/2        none
Eth1/3        none
Eth1/4        none
Eth1/5        none
Eth1/6        none
Eth1/7        none
Eth1/8        none
Eth1/9        none
Eth1/10       none
Eth1/11       none
Eth1/12       none
Eth1/13       none
Eth1/14       none
Eth1/15       none
Eth1/16       none
Eth1/17       none
Eth1/18       none
Eth1/19       none
Eth1/20       none
Eth1/21       none
Eth1/22       none
Eth1/23       none
Eth1/24       none
Eth1/25       none
Eth1/26       none
Eth1/27       none
Eth1/28       none
Eth1/29       none
Eth1/30       none
Eth1/31       none
Eth1/32       none
Eth1/33       none
Eth1/34       none
Eth1/35       none
Eth1/36       none

--------------------------------------------------------------------------------
Port          STP Forwarding
--------------------------------------------------------------------------------
Eth1/1        none
Eth1/2        none
Eth1/3        none
Eth1/4        none
Eth1/5        none
Eth1/6        none
Eth1/7        none
Eth1/8        none
Eth1/9        none
Eth1/10       none
Eth1/11       30
Eth1/12       30
Eth1/13       30
Eth1/14       30
Eth1/15       30
Eth1/16       30
Eth1/17       30
Eth1/18       30
Eth1/19       none
Eth1/20       none
Eth1/21       none
Eth1/22       none
Eth1/23       30
Eth1/24       30
Eth1/25       30
Eth1/26       30
Eth1/27       30
Eth1/28       30
Eth1/29       30
Eth1/30       30
Eth1/31       none
Eth1/32       none
Eth1/33       none
Eth1/34       none
Eth1/35       none
Eth1/36       none

--------------------------------------------------------------------------------
Port          Vlans in spanning tree forwarding state and not pruned
--------------------------------------------------------------------------------
Eth1/1        Feature VTP is not enabled
none
Eth1/2        Feature VTP is not enabled
none
Eth1/3        Feature VTP is not enabled
none
Eth1/4        Feature VTP is not enabled
none
Eth1/5        Feature VTP is not enabled
none
Eth1/6        Feature VTP is not enabled
none
Eth1/7        Feature VTP is not enabled
none
Eth1/8        Feature VTP is not enabled
none
Eth1/9        Feature VTP is not enabled
none
Eth1/10       Feature VTP is not enabled
none
Eth1/11       Feature VTP is not enabled
30
Eth1/12       Feature VTP is not enabled
30
Eth1/13       Feature VTP is not enabled
30
Eth1/14       Feature VTP is not enabled
30
Eth1/15       Feature VTP is not enabled
30
Eth1/16       Feature VTP is not enabled
30
Eth1/17       Feature VTP is not enabled
30
Eth1/18       Feature VTP is not enabled
30
Eth1/19       Feature VTP is not enabled
none
Eth1/20       Feature VTP is not enabled
none
Eth1/21       Feature VTP is not enabled
none
Eth1/22       Feature VTP is not enabled
none
Eth1/23       Feature VTP is not enabled
30
Eth1/24       Feature VTP is not enabled
30
Eth1/25       Feature VTP is not enabled
30
Eth1/26       Feature VTP is not enabled
30
Eth1/27       Feature VTP is not enabled
30
Eth1/28       Feature VTP is not enabled
30
Eth1/29       Feature VTP is not enabled
30
Eth1/30       Feature VTP is not enabled
30
Eth1/31       Feature VTP is not enabled
none
Eth1/32       Feature VTP is not enabled
none
Eth1/33       Feature VTP is not enabled
none
Eth1/34       Feature VTP is not enabled
none
Eth1/35       Feature VTP is not enabled
none
Eth1/36       Feature VTP is not enabled
none
----
====
+

NOTE: 特定のポートと VLAN の使用法の詳細については、RCF のバナーと重要な注意事項のセクションを参照してください。





== ステップ3: ONTAPクラスタをセットアップする

NetApp、 System Manager を使用して新しいクラスタを設定することをお勧めします。

System Manager は、ノード管理 IP アドレスの割り当て、クラスターの初期化、ローカル層の作成、プロトコルの構成、初期ストレージのプロビジョニングなど、クラスターのセットアップと構成のためのシンプルで簡単なワークフローを提供します。

へ移動 https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["System Managerを使用した新しいクラスタでのONTAPの設定"]セットアップ手順についてはこちらをご覧ください。

.次の手順
RCFをインストールしたら、link:configure-ssh-keys.html["SSH設定を確認する"]
