---
permalink: switch-cisco-9336c-fx2-storage/install-nxos-overview-9336c-storage.html 
sidebar: sidebar 
keywords: cisco, nx-os, software, reference, configuration, file, rcf, install, fx2, cluster, switch, install nx-os software and rcfs on cisco nexus 9336-fx2 cluster switches - cisco nexus 9336x-fx2 
summary: 'Cisco NX-OS ソフトウェアとリファレンス コンフィギュレーション ファイル (RCF) をCisco Nexus 9336C-FX2 クラスタ スイッチにインストールする必要があります。' 
---
= NX-OSソフトウェアとRCFのインストールまたはアップグレードの準備
:allow-uri-read: 


[role="lead"]
NX-OS ソフトウェアとリファレンス コンフィギュレーション ファイル (RCF) をインストールする前に、次の手順に従ってください。

.例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 2 台の Cisco スイッチの名前は s1 と s2 です。
* ノード名はcluster1-01とcluster1-02です。


.タスク概要
この手順では、ONTAPコマンドとCisco Nexus 9000シリーズ スイッチ コマンドの両方を使用する必要があります。特に明記されていないかぎり、ONTAPコマンドを使用します。

.手順
. AutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出して自動ケース作成を抑制します： `system node autosupport invoke -node * -type all -message MAINT=xh`
+
ここで、x はメンテナンス ウィンドウの期間 (時間単位) です。

+

NOTE: AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

. 続行するかどうかを尋ねられたら *y* と入力して、権限レベルを「advanced」に変更します。
+
[source, cli]
----
set -privilege advanced
----
+
高度なプロンプト(`*>`）が表示されます。

. 各スイッチの各ノードに設定されているインターフェイスの数を表示します：
+
[source, cli]
----
network device-discovery show -protocol lldp
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/lldp
            e5a    s1                        Eth1/2            N9K-C9336C
            e3b    s2                        Eth1/2            N9K-C9336C
cluster1-01/lldp
            e5a    s1                        Eth1/1            N9K-C9336C
            e3b    s2                        Eth1/1            N9K-C9336C
.
.
----
====
. 各ノード ストレージ ポートおよびストレージ シェルフ ポートの管理ステータスまたは動作ステータスを確認します。
+
.. ノード ストレージ ポート属性を表示します：
+
[source, cli]
----
storage port show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -

.
.
----
====
.. ストレージ シェルフ ポートの属性を表示します：
+
[source, cli]
----
storage shelf port show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. スイッチが監視されるように、スイッチ ヘルス モニタリング（CSHM）がスイッチに対して有効になっていることを確認します：
+
[source, cli]
----
system switch ethernet show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N9K-C9336C-FX2
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N9K-C9336C-FX2
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====




.次の手順
NX-OSソフトウェアとRCFをインストールする準備ができたら、 link:install-nxos-software-9336c-storage.html["NX-OSソフトウェアをインストールまたはアップグレードする"]。
