---
permalink: switch-cisco-9336c-fx2-storage/install-9336c-storage.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, storage, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: 必要な構成情報とドキュメントがまだない場合は、ストレージおよび管理ネットワーク スイッチをセットアップする前にその情報を収集する必要があります。 
---
= 9336C-FX2および9336C-FX2-Tストレージスイッチをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9336C-FX2 および 9336C-FX2-T ストレージ スイッチをインストールするには、次の手順に従います。

.開始する前に
以下のものがあることを確認してください。

* インストール サイトの HTTP、FTP、または TFTP サーバーにアクセスして、該当する NX-OS および参照構成ファイル (RCF) リリースをダウンロードします。
* 該当するNX-OSバージョンは、 https://software.cisco.com/download/home["Ciscoソフトウェアのダウンロード"^]ページ。
* 適用可能なライセンス、ネットワークおよび構成情報、およびケーブル。
* 完了link:setup-worksheet-9336c-storage.html["配線ワークシート"]。
* 該当するNetAppストレージ ネットワークおよび管理ネットワークRCFは、NetApp Support Siteから http://mysupport.netapp.com/["mysupport.netapp.com"^]ダウンロードされます。
+
すべての Cisco ストレージ ネットワークおよび管理ネットワーク スイッチには、標準の Cisco 工場出荷時のデフォルト設定が適用されています。これらのスイッチには NX-OS ソフトウェアの最新バージョンも搭載されていますが、RCF はロードされていません。

* 必要なスイッチドキュメント。見るlink:required-documentation-9336c-storage.html["必要な書類"]詳細についてはこちらをご覧ください。


.手順
. ネットワークおよび管理ネットワーク スイッチとコントローラをラックに設置します。
+
[cols="1,2"]
|===
| ...をインストールする場合 | 操作 


 a| 
NetAppシステムキャビネット内のCisco Nexus 9336C-FX2
 a| 
見るlink:install-switch-and-passthrough-panel-9336c-storage.html["NetAppキャビネットにスイッチをインストールする"]NetAppキャビネットにスイッチをインストールする手順については、こちらをご覧ください。



 a| 
通信ラック内の機器
 a| 
スイッチ ハードウェア インストール ガイドおよびNetApp のインストールおよびセットアップ手順に記載されている手順を参照してください。

|===
. 完成した配線ワークシートを使用して、ネットワーク スイッチと管理ネットワーク スイッチをコントローラに配線します。
. ネットワークおよび管理ネットワーク スイッチとコントローラの電源をオンにします。


.次の手順
オプションとして、 link:install-switch-and-passthrough-panel-9336c-storage.html["NetAppキャビネットにCisco Nexus 9336C-FX2スイッチをインストールする"]。それ以外の場合は、 link:setup-switch-9336c-storage.html["スイッチを設定する"]。
