---
permalink: switch-cisco-9336c-fx2-storage/replace-storage-switch-9336c-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: 'クラスタ ネットワーク内の故障した Nexus 9336C-FX2 スイッチを交換することは、無停止の手順 (NDU) です。' 
---
= Cisco Nexus 9336C-FX2および9336C-FX2-Tストレージスイッチの交換
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ ネットワーク内の故障した Nexus 9336C-FX2 および 9336C-FX2-T スイッチを交換できます。この手順は無停止で実行されます。

.開始する前に
Cisco Nexus 9336C-FX2 および 9336C-FX2-T ストレージ スイッチに NX-OS ソフトウェアと RCF をインストールする前に、次の点を確認してください。

* システムは、 Cisco Nexus 9336C-FX2 および 9336C-FX2-T ストレージ スイッチをサポートできます。
* サポートされているONTAP 、NX-OS、および RCF バージョンについては、 Ciscoイーサネット スイッチ ページのスイッチ互換性表を参照しました。
* Cisco Web サイトで入手可能な適切なソフトウェアおよびアップグレード ガイドを参照しました。
* 該当する RCF をダウンロードしました。
* 既存のネットワーク構成には次の特性があります。
+
** Ciscoイーサネット スイッチ ページには、スイッチの最新の RCF および NX-OS バージョンが記載されています。
** 両方のスイッチに管理接続が存在する必要があります。


* 交換用Cisco Nexus 9336C-FX2 スイッチには次の特性があります。
+
** 管理ネットワーク接続は機能しています。
** 交換用スイッチへのコンソール アクセスが確立されています。
** 適切な RCF および NX-OS オペレーティング システム イメージがスイッチにロードされます。
** スイッチの初期設定が完了しました。




.タスク概要
この手順では、2 番目の Nexus 9336C-FX2 ストレージ スイッチ s2 を新しい 9336C-FX スイッチ ns2 に置き換えます。2 つのノードは cluster1-01 と cluster1-02 です。

完了するための手順:

* 交換するスイッチが s2 であることを確認します。
* スイッチ s2 からケーブルを外します。
* ケーブルをスイッチns2に再接続します。
* スイッチ ns2 上のすべてのデバイス構成を確認します。
+

NOTE: RCF バージョンと NX-OS バージョンのコマンド構文には依存関係がある場合があります。



.手順
. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

. ストレージ ノード ポートのヘルス ステータスを確認して、ストレージ スイッチ s1 への接続があることを確認します：
+
`storage port show -port-type ENET`

+
.例を表示
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
cluster1-02
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
.
.
----
====
. ストレージ スイッチ s1 が使用可能であることを確認します：
+
`network device-discovery show`

+
.例を表示
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
cluster1-01/cdp
           e5a   s1                        Ethernet1/1 NX9336C
           e4a   cluster1-02               e4a         AFF-A700
           e4e   cluster1-02               e4e         AFF-A700
cluster1-01/lldp
           e5a   s1                        Ethernet1/1 -
           e4a   cluster1-02               e4a         -
           e4e   cluster1-02               e4e         -
cluster1-02/cdp
           e3b   s1                        Ethernet1/2 NX9336C
           e4a   cluster1-01               e4a         AFF-A700
           e4e   cluster1-01               e4e         AFF-A700
cluster1-02/lldp
           e3b   s1                        Ethernet1/2 -
           e4a   cluster1-01               e4a         -
           e4e   cluster1-01               e4e         -
.
.
----
====
. ショーを運営する `lldp neighbors`動作中のスイッチでコマンドを実行して、両方のノードとすべてのシェルフが表示されることを確認します。
+
`show lldp neighbors`

+
.例を表示
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
cluster1-01      Eth1/1       121          S             e5a
cluster1-02      Eth1/2       121          S             e5a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. ストレージ システム内のストレージ シェルフ ポートを確認します：
+
`storage shelf port show -fields remote-device,remote-port`

+
.例を表示
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   s1
3.20    1   -             -
3.20    2   Ethernet1/6   s1
3.20    3   -             -
3.30    0   Ethernet1/7   s1
3.20    1   -             -
3.30    2   Ethernet1/8   s1
3.20    3   -             -
.
.
----
====
. ストレージ スイッチ s2 に接続されているすべてのケーブルを取り外します。
. すべてのケーブルを交換用スイッチ ns2 に再接続します。
. ストレージ ノード ポートのヘルス ステータスを再確認します。
+
`storage port show -port-type ENET`

+
.例を表示
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
cluster1-02
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
.
.
----
====
. 両方のスイッチが使用可能であることを確認します。
+
`network device-discovery show`

+
.例を表示
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
cluster1-01/cdp
          e3a  s1                         Ethernet1/1 NX9336C
          e4a  cluster1-02                e4a         AFF-A700
          e4e  cluster1-02                e4e         AFF-A700
          e7b  ns2                       Ethernet1/1 NX9336C
cluster1-01/lldp
          e3a  s1                         Ethernet1/1 -
          e4a  cluster1-02                e4a         -
          e4e  cluster1-02                e4e         -
          e7b  ns2                        Ethernet1/1 -
cluster1-02/cdp
          e3a  s1                         Ethernet1/2 NX9336C
          e4a  cluster1-01                e4a         AFF-A700
          e4e  cluster1-01                e4e         AFF-A700
          e7b  ns2                        Ethernet1/2 NX9336C
cluster1-02/lldp
          e3a  s1                         Ethernet1/2 -
          e4a  cluster1-01                e4a         -
          e4e  cluster1-01                e4e         -
          e7b  ns2                        Ethernet1/2 -
.
.
----
====
. ストレージ システムのシェルフ ポートを確認します。
+
`storage shelf port show -fields remote-device,remote-port`

+
.例を表示
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     s1
3.20    1     Ethernet1/5     ns2
3.20    2     Ethernet1/6     s1
3.20    3     Ethernet1/6     ns2
3.30    0     Ethernet1/7     s1
3.20    1     Ethernet1/7     ns2
3.30    2     Ethernet1/8     s1
3.20    3     Ethernet1/8     ns2
storage::*>
----
====
. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.次の手順
スイッチを交換したら、 link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを設定する"]。
