---
permalink: switch-cisco-9336c-fx2-storage/replace-storage-switch-9336c-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: クラスタネットワーク内の障害のある Nexus 9336C-FX2 スイッチの交換は、無停止手順（ NDU ）です。 
---
= Cisco Nexus 9336C-FX2 ストレージスイッチを交換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタネットワーク内の故障したNexus 9336C-FX2スイッチは交換できます。これは無停止の手順です。

.作業を開始する前に
Cisco Nexus 9336C-FX2ストレージスイッチにNX-OSソフトウェアとRCFをインストールする前に、次の点を確認します。

* ご使用のシステムでは、 Cisco Nexus 9336C-FX2 ストレージスイッチをサポートできます。
* サポートされているONTAP 、NX-OS、およびRCFのバージョンについては、Ciscoイーサネットスイッチのページにあるスイッチ互換性の表を参照してください。
* シスコのWebサイトで入手可能な適切なソフトウェアおよびアップグレードガイドを参照しておきます。


Cisco Nexus 3000シリーズスイッチ：

* 該当するRCFをダウンロードしておきます。
* 既存のネットワーク構成には次のような特徴があります。
+
** Cisco Ethernet Switches のページに、スイッチ上の最新の RCF および NX-OS バージョンが含まれています。
** 両方のスイッチで管理接続が確立されている必要があります。


* 交換用Cisco Nexus 9336C-FX2スイッチには、次の特徴があります。
+
** 管理ネットワーク接続は機能しています。
** 交換用スイッチへのコンソールアクセスが確立されています。
** 適切なRCFおよびNX-OSオペレーティングシステムイメージがスイッチにロードされます。
** スイッチの初期設定が完了しました。




.このタスクについて
この手順 は、2番目のNexus 9336C-FX2ストレージスイッチS2を新しい9336C-FXスイッチNS2に置き換えます。2 つのノードは node1 と node2 になります。

完了する手順：

* 交換するスイッチが S2 であることを確認します。
* スイッチ S2 からケーブルを外します。
* スイッチ NS2 にケーブルを再接続します
* スイッチ NS2 のすべてのデバイス構成を確認します
+

NOTE: RCFバージョンとNX-OSバージョンのコマンド構文には依存関係がある場合があります。



.手順
. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。
+
'system node AutoSupport invoke -node * -type all -message MAINT=xh`

+
_x_ は、メンテナンス時間の長さ（時間単位）です。

. ストレージノードポートのヘルスステータスをチェックして、ストレージスイッチ S1 に接続されていることを確認します。
+
storage port show -port-type enet

+
.例を示します
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. ストレージスイッチS1が使用可能であることを確認します。
+
「 network device-discovery show 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
node1/cdp
           e3a   S1                        Ethernet1/1 NX9336C
           e4a   node2                     e4a         AFF-A700
           e4e   node2                     e4e         AFF-A700
node1/lldp
           e3a   S1                        Ethernet1/1 -
           e4a   node2                     e4a         -
           e4e   node2                     e4e         -
node2/cdp
           e3a   S1                        Ethernet1/2 NX9336C
           e4a   node1                     e4a         AFF-A700
           e4e   node1                     e4e         AFF-A700
node2/lldp
           e3a   S1                        Ethernet1/2 -
           e4a   node1                     e4a         -
           e4e   node1                     e4e         -
storage::*>
----
====
. showを実行します `lldp neighbors` 動作中のスイッチに対してコマンドを実行し、ノードとすべてのシェルフの両方が表示されることを確認します。
+
`show lldp neighbors`

+
.例を示します
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
node1            Eth1/1       121          S             e3a
node2            Eth1/2       121          S             e3a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. ストレージシステムのシェルフポートを確認します。
+
`storage shelf port show -fields remote-device,remote-port`

+
.例を示します
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   S1
3.20    1   -             -
3.20    2   Ethernet1/6   S1
3.20    3   -             -
3.30    0   Ethernet1/7   S1
3.20    1   -             -
3.30    2   Ethernet1/8   S1
3.20    3   -             -
storage::*>
----
====
. ストレージスイッチ S2 に接続されているすべてのケーブルを取り外します。
. 交換用スイッチの NS2 にすべてのケーブルを再接続します。
. ストレージノードポートのヘルスステータスを再確認します。
+
storage port show -port-type enet

+
.例を示します
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. 両方のスイッチが使用可能であることを確認します。
+
「 network device-discovery show 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
node1/cdp
          e3a  S1                         Ethernet1/1 NX9336C
          e4a  node2                      e4a         AFF-A700
          e4e  node2                      e4e         AFF-A700
          e7b   NS2                       Ethernet1/1 NX9336C
node1/lldp
          e3a  S1                         Ethernet1/1 -
          e4a  node2                      e4a         -
          e4e  node2                      e4e         -
          e7b  NS2                        Ethernet1/1 -
node2/cdp
          e3a  S1                         Ethernet1/2 NX9336C
          e4a  node1                      e4a         AFF-A700
          e4e  node1                      e4e         AFF-A700
          e7b  NS2                        Ethernet1/2 NX9336C
node2/lldp
          e3a  S1                         Ethernet1/2 -
          e4a  node1                      e4a         -
          e4e  node1                      e4e         -
          e7b  NS2                        Ethernet1/2 -
storage::*>
----
====
. ストレージシステムのシェルフポートを確認します。
+
`storage shelf port show -fields remote-device,remote-port`

+
.例を示します
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     S1
3.20    1     Ethernet1/5     NS2
3.20    2     Ethernet1/6     S1
3.20    3     Ethernet1/6     NS2
3.30    0     Ethernet1/7     S1
3.20    1     Ethernet1/7     NS2
3.30    2     Ethernet1/8     S1
3.20    3     Ethernet1/8     NS2
storage::*>
----
====
. ケースの自動作成を抑制した場合は、 AutoSupport メッセージを呼び出して作成を再度有効にします。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます



.次の手順
link:../switch-cshm/config-overview.html["スイッチヘルス監視の設定"]です。
