---
permalink: switch-cisco-9808/configure-upgrade-rcf-9808.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: Cisco Nexus 9808 スイッチのリファレンス構成ファイル（RCF）のバージョンをアップグレードして、新しいハードウェア、新しい ONTAP バージョンのサポート、または AFX 2K システム構成での新しい NX-OS バージョンへの対応を実現します。 
---
= RCFバージョンのアップグレード - Cisco Nexus 9808
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 2K システム構成で新しいハードウェア、新しい ONTAP バージョン、または新しい NX-OS バージョンへの対応をサポートするために、Cisco Nexus 9808 スイッチの参照構成ファイル（RCF）バージョンをアップグレードします。


NOTE: RCFのバージョンをサポートされていないバージョンにアップグレードまたはダウングレードしないでください。

.開始する前に
* link:configure-install-upgrade-rcf-overview-9808.html["RCF のインストールまたはアップグレードの概要"]ページを読んでいる必要があります。
* シリアルコンソールを使用してスイッチに接続しているか、基本的な設定情報が保存されている必要があります。これは、RCFアップグレード手順では、スイッチの設定を消去し、基本的な構成を実行する必要があるためです。
* スイッチの設定に関する最新のバックアップがあることを確認してください。
* クラスターが完全に機能していることを確認してください。つまり、ログにエラーや同様の問題がないことを確認してください。
* 最新のRCFバージョンが必要です。
* RCFファイルには、目的のブートイメージを反映したブート構成が必要です。
+
現在のブート イメージを反映するようにブート設定を変更する必要がある場合は、あとでリブートしたときに正しいバージョンがインスタンス化されるように、RCFを再適用する前に変更する必要があります。



.タスク概要
* 両方のスイッチのRCFをアップグレードする作業は、システムを中断することなく行えます。
+
** この手順では、スイッチ間リンク（ISL）の運用は必要ありません。これは意図的な設計であり、RCF のバージョン変更は ISL 接続に一時的に影響を与える可能性があるためです。クラスタの運用に支障をきたさないようにするため、この手順では、ターゲットスイッチで手順を実行しながら、クラスタのすべての LIF を運用パートナースイッチに移行します。
** この手順では、まず最初のスイッチ（cs1）のRCFをアップグレードし、次に2番目のスイッチ（cs2）に対して同じ手順を繰り返します。


* この手順では、ONTAPコマンドとCisco Nexus 9000シリーズスイッチのコマンドを使用します。各手順には、コマンドを入力する際に使用するCLIが示されています。
* この手順の例で使用するスイッチとノードの名前は次のとおりです。
+
** 2 つのCiscoスイッチの名前は cs1 と cs2 です。
** ノード名は、node1-01、node1-02、node1-03、node1-04 です。
** クラスタ LIF 名は次のとおりです。
+
*** node1-01 の node1-01_clus1 と node1-01_clus2
*** node1-02 の node1-02_clus1 と node1-02_clus2
*** node1-03 の node1-03_clus1 と node1-03_clus2
*** node1-04 の node1-04_clus1 と node1-04_clus2


** その `cluster1::*>`プロンプトはクラスターの名前を示します。






[[step-1-prepare-for-the-upgrade]]
== ステップ1: アップグレードの準備

次の手順のコマンドは、ONTAP CLIから入力します。

. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
[source, cli]
----
system node autosupport invoke -node * -type all -message MAINT=xh
----
+
ここで、_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

. 続行するかどうかを尋ねられたら *y* と入力して、権限レベルを「advanced」に変更します。
+
[source, cli]
----
set -privilege advanced
----
+
advancedのプロンプト（*>）が表示されます。

. スイッチに接続されている各ノード上のポートを表示します。
+
[source, cli]
----
network device-discovery show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/5       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/14      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/7       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/16      N9K-C9808
            e2a    cs1(FOXXXXXXXXX)          Ethernet1/3       N9K-C9808
            e2b    cs2(FOXXXXXXXXX)          Ethernet1/12      N9K-C9808
node1-01/lldp
            e10a   cs1 (ec:bb:78:9e:c7:e8)   Ethernet1/5       -
            e10b   cs2 (ec:bb:78:9e:c8:0c)   Ethernet1/14      -
            e8a    cs1 (ec:bb:78:9e:c7:f0)   Ethernet1/7       -
            e8b    cs2 (ec:bb:78:9e:c8:14)   Ethernet1/16      -
            e1a    cs1 (ec:bb:78:9e:c7:d8)   Ethernet1/1       -
            e1b    cs2 (ec:bb:78:9e:c7:fc)   Ethernet1/10      -
            e2a    cs1 (ec:bb:78:9e:c7:e0)   Ethernet1/3       -
            e2b    cs2 (ec:bb:78:9e:c8:04)   Ethernet1/12      -
node1-02/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/6       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/15      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/8       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/17      N9K-C9808
            e2a    cs1(FOXXXXXXXXXX)         Ethernet1/2       N9K-C9808
            e2b    cs2(FOX3005Q66Q)          Ethernet1/13      N9K-C9808
node1-02/lldp
            e10a   cs1 (ec:bb:78:9e:c7:ec)   Ethernet1/6       -
            e10b   cs2 (ec:bb:78:9e:c8:10)   Ethernet1/15      -
            e8a    cs1 (ec:bb:78:9e:c7:f4)   Ethernet1/8       -
            e8b    cs2 (ec:bb:78:9e:c8:18)   Ethernet1/17      -
            e1a    cs1 (ec:bb:78:9e:c7:dc)   Ethernet1/2       -
            e1b    cs2 (ec:bb:78:9e:c8:00)   Ethernet1/11      -
            e2a    cs1 (ec:bb:78:9e:c7:e4)   Ethernet1/4       -
            e2b    cs2 (ec:bb:78:9e:c8:08)   Ethernet1/13      -
.
.
.
----
====
. 各ポートの管理および動作ステータスを確認します。
+
.. *クラスターポート*
+
... すべてのクラスター ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-02
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-03

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-04
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false
----
====
... すべてのクラスタ インターフェイス (LIF) がホーム ポート上にあることを確認します。
+
[source, cli]
----
network interface show -role cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network           Current      Current Is
Vserver     Interface          Admin/Oper Address/Mask      Node         Port    Home
----------- ------------------ ---------- ----------------- ------------ ------- ----
Cluster
            node1-01_clus1     up/up      169.254.3.4/23     node1-01    e2a     true
            node1-01_clus2     up/up      169.254.3.5/23     node1-01    e2b     true
            node1-02_clus1     up/up      169.254.3.8/23     node1-02    e2a     true
            node1-02_clus2     up/up      169.254.3.9/23     node1-02    e2b     true
            node1-03_clus1     up/up      169.254.1.3/23     node1-03    e2a     true
            node1-03_clus2     up/up      169.254.1.1/23     node1-03    e2b     true
            node1-04_clus1     up/up      169.254.1.6/23     node1-04    e2a     true
            node1-04_clus2     up/up      169.254.1.7/23     node1-04    e2b     true
----
====
... クラスターに両方のスイッチの情報が表示されることを確認します。
+
[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs2(FDOXXXXXXXX)            cluster-network    10.228.137.233   N9K-C9808
     Serial Number: FDOXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(3)(F)
    Version Source: CDP/ISDP


cs1(FOXXXXXXXXX)            cluster-network    10.228.137.234   N9K-C9808
     Serial Number: FOXXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(3)(F)
    Version Source: CDP/ISDP
----
====


.. *HAポート*
+
... すべての HA ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
ha interconnect status show -node <node-name>
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====
... すべての HA ポートが正しく設定されており、インターコネクトタイプが RoCE であることを確認してください。
+
[source, cli]
----
ha interconnect config show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect config show*
  (system ha interconnect config show)
                       Node: node1-01
          Interconnect Type: RoCE
            Local System ID: 542023071
          Partner System ID: 542022984
       Connection Initiator: local
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.111     0x0
e1b-18  169.254.18.242     0x0



                       Node: node1-02
          Interconnect Type: RoCE
            Local System ID: 542022984
          Partner System ID: 542023071
       Connection Initiator: partner
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.208     0x0
e1b-18  169.254.18.169     0x0
.
.
.
----
====


.. *ストレージポート*
+
... すべてのストレージ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage port show -port-type ENET
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-02
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-03
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-04
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
----
====


.. *ストレージシェルフポート*
+
... すべてのストレージ シェルフ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage shelf port show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.0
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false
----
====
... すべてのストレージ シェルフ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 cs1(FOXXXXXXXXX)
1.1   1  connected       Ethernet1/15/1 cs2(FDOXXXXXXXX)
1.1   2  connected       Ethernet1/17/2 cs1(FOXXXXXXXXX)
1.1   3  connected       Ethernet1/15/2 cs2(FDOXXXXXXXX)
1.1   4  connected       Ethernet1/17/3 cs1(FOXXXXXXXXX)
1.1   5  connected       Ethernet1/15/3 cs2(FDOXXXXXXXX)
1.1   6  connected       Ethernet1/17/4 cs1(FOXXXXXXXXX)
1.1   7  connected       Ethernet1/15/4 cs2(FDOXXXXXXXX)
1.1   8  connected       Ethernet1/19/1 cs1(FOXXXXXXXXX)
1.1   9  connected       Ethernet1/17/1 cs2(FDOXXXXXXXX)
1.1   10 connected       Ethernet1/19/2 cs1(FOXXXXXXXXX)
1.1   11 connected       Ethernet1/17/2 cs2(FDOXXXXXXXX)
1.1   12 connected       Ethernet1/19/3 cs1(FOXXXXXXXXX)
1.1   13 connected       Ethernet1/17/3 cs2(FDOXXXXXXXX)
1.1   14 connected       Ethernet1/19/4 cs1(FOXXXXXXXXX)
1.1   15 connected       Ethernet1/17/4 cs2(FDOXXXXXXXX)
----
====




. クラスタLIFの自動ロールバックを無効にします。クラスタLIFはパートナークラスタスイッチにフェイルオーバーし、対象スイッチでこの手順を実行する間、そのままの状態を維持します。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----




[[step-2-configure-ports]]
== ステップ2: ポートを構成する

. スイッチCLIを使用して、スイッチcs1上で、各ラインカードのノードのすべてのポートに接続されているポートをシャットダウンします。
+
次の例は、ラインカード1のすべてのポートをシャットダウンするコマンドを示しています `e1`、 `e1-1/1-18`、 `e1/19/1-4`、 `e1/20/1-4`… `e1/35/1-4`。スイッチ上の各ラインカードに対して、これらのコマンドを繰り返してください。

+
[listing, subs="+quotes"]
----
cs1# *config terminal*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-18*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/19/1-4,e1/20/1-4,e1/21/1-4,e1/22/1-4,e1/23/1-4,e1/24/1-4,e1/25/1-4,e1/26/1-4,e1/27/1-4,e1/28/1-4,e1/29/1-4,e1/30/1-4,e1/31/1-4,e1/32/1-4,e1/33/1-4,e1/34/1-4,e1/35/1-4*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----
+

CAUTION: ネットワーク接続の問題を避けるため、接続されている*すべて*のポートを必ずシャットダウンしてください。詳細については、ナレッジベースの記事link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["スイッチ OS のアップグレード中にクラスタ LIF を移行するとノードがクォーラム外になる"^]を参照してください。

. ONTAP CLI を使用して、クラスタ LIF がスイッチ cs1 でホストされているポートにフェイルオーバーしたことを確認します。数秒かかる場合があります。
+
[source, cli]
----
network interface show -role cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current     Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node        Port    Home
----------- --------------- ---------- ------------------ ----------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01    e2a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01    e2b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02    e2a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02    e2b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03    e2a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03    e2b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04    e2a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04    e2b     true

8 entries were displayed.
----
====
. ONTAP CLI を使用して、クラスターが正常であることを確認します：
+
[source, cli]
----
cluster show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health  Eligibility   Epsilon
----------------- ------- ------------  -------
node1-01          true    true          false
node1-02          true    true          false
node1-03          true    true          true
node1-04          true    true          false
----
====
. まだ実施していない場合は、スイッチの CLI を使用して、次のコマンドの出力をテキストファイルにコピーし、現在のスイッチ設定のコピーを保存してください：
+
`show running-config`

+
..  `show diff running-config`コマンドを使用して、bootflashに保存されているRCFファイルと比較します。それ以外の場合は、サードパーティ製の差分/比較ツールを使用してください。


. 基本的な設定の詳細を `write_erase.cfg`ブートフラッシュ上のファイル。
+
[NOTE]
====
必ず以下を設定してください。

** ユーザ名とパスワード
** 管理IPアドレス
** デフォルト ゲートウェイ
** スイッチ名


====
+
[CAUTION]
====
 `write_erase.cfg`ファイルがすでに存在する場合は、次のように `write_erase_old.cfg`に名前を変更してください：

`cs1# move bootflash:write_erase.cfg write_erase_old.cfg`

====
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

+
詳細については、ナレッジベースの記事link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["リモート接続を維持しながらCiscoインターコネクトスイッチの設定をクリアする方法"^]を参照してください。

. スイッチのCLIを使用して、 `write_erase.cfg`ファイルが想定どおりに設定されていることを確認します：
+
`show file bootflash:write_erase.cfg`

. スイッチのCLIを使用して、 `write erase`コマンドを実行し、現在保存されている設定を消去します：
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. スイッチのCLIを使用して、以前に保存した基本設定をスタートアップ設定にコピーします。
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. スイッチのCLIを使用して、スイッチを再起動します。
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 管理 IP アドレスに再度アクセスできるようになったら、SSH 経由でスイッチにログインします。
+
SSH キーに関連するホスト ファイル エントリを更新する必要がある場合があります。

. スイッチの CLI を使用して、FTP、TFTP、SFTP、または SCP のいずれかの転送プロトコルを使用して、RCF をスイッチ cs1 の bootflash にコピーします。
+
Cisco コマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 シリーズ NX-OS コマンド リファレンス"^]ガイドの適切なガイドを参照してください。

+
`copy <protocol>: bootflash: vrf management`

+
.例を表示
[%collapsible]
====
この例では、TFTPを使用してスイッチcs1のブートフラッシュにRCFをコピーしています。

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *RCF-v10.1-NX9808-CL1-ST1.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. スイッチのCLIを使用して、以前にダウンロードしたRCFをブートフラッシュに適用します。
+
Cisco コマンドの詳細については、link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 シリーズ NX-OS コマンド リファレンス"^]ガイドの適切なガイドを参照してください。

+
この例では、スイッチ cs1 に RCF `RCF-v10.1-NX9808-CL1-ST1.txt` がインストールされています：

+
[listing, subs="+quotes"]
----
cs1# *copy RCF-v10.1-NX9808-CL1-ST1.txt running-config echo-commands*
----
+
[CAUTION]
====
RCF の *インストール ノート*、*重要ノート*、および *バナー* セクションを必ずよくお読みください。スイッチが正しく動作するように設定するためには、出力を確認し、その指示に従う必要があります。

====
. スイッチ CLI を使用して、RCF が正しい新しいバージョンであることを確認します。
+
`show running-config`

+
次の情報が正しいことを確認してください。

+
** RCFのバナー
** ノードとポートの設定
** カスタマイズ
+
出力内容はサイトの構成によって異なります。ポートの設定を確認し、インストールしたRCFに固有の変更がないかリリース ノートを参照してください。



. 以前のカスタマイズをスイッチ構成に再適用します。
+
スイッチがRCF 10.1以降を実行している場合は、必要に応じてlink:configure-install-upgrade-rcf-overview-9808.html#change-port-speed-configuration["ポート速度設定を変更する"]できます。

. スイッチCLIを使用して、RCFバージョン、カスタム追加、およびスイッチ設定が正しいことを確認した後、 `running-config`ファイルを `startup-config`ファイルにコピーします。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 シリーズ NX-OS コマンド リファレンス"^]ガイドの適切なガイドを参照してください。

+
`cs1# *copy running-config startup-config*`

+
`[########################################] 100% Copy complete`

. スイッチのCLIを使用して、スイッチcs1を再起動します。スイッチの再起動中は、ノード上で報告される「`cluster switch health monitor`」アラートや「`cluster ports down`」イベントは無視して構いません。
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. ONTAP CLIを使用して、クラスタ上のすべてのポートの健全性を確認します。
+
.. *クラスターポート*
+
... クラスター内のすべてのノードでクラスター ポートが稼働しており正常であることを確認します。
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-02
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-03
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-04
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false
----
====
... クラスターからスイッチの健全性を確認します。
+
[source, cli]
----
network device-discovery show -protocol cdp
----
+
[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/5       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/14      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/7       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/16      N9K-C9808
            e2a    cs1(FOXXXXXXXXX)          Ethernet1/3       N9K-C9808
            e2b    cs2(FOXXXXXXXXX)          Ethernet1/12      N9K-C9808
node1-02/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/6       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/15      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/8       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/17      N9K-C9808
            e2a    cs1(FOXXXXXXXXXX)         Ethernet1/2       N9K-C9808
            e2b    cs2(FOX3005Q66Q)          Ethernet1/13      N9K-C9808
.
.
.
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs2(FDOXXXXXXXX)           cluster-network    10.228.137.233    N9K-C9808
     Serial Number: FDOXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.6(3)(F)
    Version Source: CDP/ISDP

cs1(FOXXXXXXXXX)           cluster-network    10.228.137.234    N9K-C9808
     Serial Number: FOXXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.6(3)(F)
    Version Source: CDP/ISDP
----
====


.. *HAポート*
+
... すべての HA ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
ha interconnect status show -node <node-name>
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====
... すべての HA ポートが正しく設定されており、インターコネクトタイプが RoCE であることを確認してください。
+
[source, cli]
----
ha interconnect config show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect config show*
  (system ha interconnect config show)
                       Node: node1-01
          Interconnect Type: RoCE
            Local System ID: 542023071
          Partner System ID: 542022984
       Connection Initiator: local
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.111     0x0
e1b-18  169.254.18.242     0x0



                       Node: node1-02
          Interconnect Type: RoCE
            Local System ID: 542022984
          Partner System ID: 542023071
       Connection Initiator: partner
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.208     0x0
e1b-18  169.254.18.169     0x0
.
.
.
----
====


.. *ストレージポート*
+
... すべてのストレージ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage port show -port-type ENET
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-02
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-03
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-04
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
----
====


.. *ストレージシェルフポート*
+
... すべてのストレージ シェルフ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage shelf port show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.0
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false
----
====
... すべてのストレージ シェルフ ポートの接続ステータスを確認します。
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 cs1(FOXXXXXXXXX)
1.1   1  connected       Ethernet1/15/1 cs2(FDOXXXXXXXX)
1.1   2  connected       Ethernet1/17/2 cs1(FOXXXXXXXXX)
1.1   3  connected       Ethernet1/15/2 cs2(FDOXXXXXXXX)
1.1   4  connected       Ethernet1/17/3 cs1(FOXXXXXXXXX)
1.1   5  connected       Ethernet1/15/3 cs2(FDOXXXXXXXX)
1.1   6  connected       Ethernet1/17/4 cs1(FOXXXXXXXXX)
1.1   7  connected       Ethernet1/15/4 cs2(FDOXXXXXXXX)
1.1   8  connected       Ethernet1/19/1 cs1(FOXXXXXXXXX)
1.1   9  connected       Ethernet1/17/1 cs2(FDOXXXXXXXX)
1.1   10 connected       Ethernet1/19/2 cs1(FOXXXXXXXXX)
1.1   11 connected       Ethernet1/17/2 cs2(FDOXXXXXXXX)
1.1   12 connected       Ethernet1/19/3 cs1(FOXXXXXXXXX)
1.1   13 connected       Ethernet1/17/3 cs2(FDOXXXXXXXX)
1.1   14 connected       Ethernet1/19/4 cs1(FOXXXXXXXXX)
1.1   15 connected       Ethernet1/17/4 cs2(FDOXXXXXXXX)
----
====




. ONTAP CLI を使用して、クラスターが正常であることを確認します：
+
[source, cli]
----
cluster show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health   Eligibility   Epsilon
----------------- -------- ------------- -------
node1-01          true     true          false
node1-02          true     true          false
node1-03          true     true          true
node1-04          true     true          false

4 entries were displayed.
----
====
. スイッチ cs2 で手順 4 ～ 18 を繰り返します。
. ONTAP CLIを使用して、クラスタLIFの自動リバートを有効にします。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----




[[step-3-verify-the-cluster-network-configuration-and-cluster-health]]
== ステップ3: クラスターネットワーク構成とクラスターの健全性を確認する

. スイッチのCLIを使用して、クラスタポートに接続されているスイッチポートが*稼働中*であることを確認します。
+
[source, cli]
----
show interface brief
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
--------------------------------------------------------------------------------
Ethernet        VLAN    Type Mode   Status  Reason                 Speed     Port
Interface                                                                    Ch #
--------------------------------------------------------------------------------
Eth1/1          1       eth  trunk  up      none                     400G(D) --
Eth1/2          1       eth  trunk  up      none                     400G(D) --
Eth1/3          1       eth  trunk  up      none                     400G(D) --
Eth1/4          1       eth  trunk  up      none                     400G(D) --
Eth1/5          1       eth  trunk  up      none                     400G(D) --
Eth1/6          1       eth  trunk  up      none                     400G(D) --
Eth1/7          1       eth  trunk  up      none                     400G(D) --
Eth1/8          1       eth  trunk  up      none                     400G(D) --
Eth1/9          1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/10         1       eth  trunk  up      none                     400G(D) --
Eth1/11         1       eth  trunk  up      none                     400G(D) --
Eth1/12         1       eth  trunk  up      none                     400G(D) --
Eth1/13         1       eth  trunk  up      none                     400G(D) --
Eth1/14         1       eth  trunk  up      none                     400G(D) --
Eth1/15         1       eth  trunk  up      none                     400G(D) --
Eth1/16         1       eth  trunk  up      none                     400G(D) --
Eth1/17         1       eth  trunk  up      none                     400G(D) --
Eth1/18         1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/19/1       1       eth  trunk  up      none                     100G(D) --
Eth1/19/2       1       eth  trunk  up      none                     100G(D) --
Eth1/19/3       1       eth  trunk  up      none                     100G(D) --
Eth1/19/4       1       eth  trunk  up      none                     100G(D) --
Eth1/20/1       1       eth  trunk  up      none                     100G(D) --
Eth1/20/2       1       eth  trunk  up      none                     100G(D) --
Eth1/20/3       1       eth  trunk  up      none                     100G(D) --
Eth1/20/4       1       eth  trunk  up      none                     100G(D) --
.
.
.
Eth1/30/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/30/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/30/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/30/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/31/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/31/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/31/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/31/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/32/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/32/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/32/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/32/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/33/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/33/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/33/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/33/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/34/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/34/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/34/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/34/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/35/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/35/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/35/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/35/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/36         1       eth  trunk  down    XCVR not inserted        auto(D) 1

------------------------------------------------------------------------------------
Port-channel VLAN    Type Mode   Status  Reason                    Speed   Protocol
								                                                           Interface
------------------------------------------------------------------------------------
Po1          1       eth  trunk  down    No operational members    auto(D)  lacp
Po998        1       eth  access down    Administratively down     auto(I)  none
Po999        1       eth  access down    Administratively down     auto(I)  none
----
====
. スイッチのCLIを使用して、想定されるノードがまだ接続されていることを確認します。
+
[source, cli]
----
show cdp neighbors
----
+
[source, cli]
----
show lldp neighbors
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                  Eth1/3         179    H         AFX-2K          e7a
cs2                  Eth1/4         123    H         AFX-2K          e7a
cs1                  Eth1/5         179    H         AFX-2K          e10a
cs2                  Eth1/6         123    H         AFX-2K          e10a
cs1                  Eth1/7         179    H         AFX-2K          e11a
cs2                  Eth1/8         123    H         AFX-2K          e11a
cs1                  Eth1/12        179    H         AFX-2K          e7b
cs2                  Eth1/13        123    H         AFX-2K          e7b
cs1                  Eth1/14        179    H         AFX-2K          e10b
cs2                  Eth1/15        123    H         AFX-2K          e10b
cs1                  Eth1/16        179    H         AFX-2K          e11b
cs2                  Eth1/17        123    H         AFX-2K          e11b

cs1# *show lldp neighbors*
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID            Local Intf      Hold-time  Capability  Port ID
cs1                    Eth1/1          121        S           e1a
cs2                    Eth1/2          121        S           e1a
cs1                    Eth1/3          121        S           e7a
cs2                    Eth1/4          121        S           e7a
cs1                    Eth1/5          121        S           e10a
cs2                    Eth1/6          121        S           e10a
cs1                    Eth1/7          121        S           e11a
cs2                    Eth1/8          121        S           e11a
cs1                    Eth1/10         121        S           e1b
cs2                    Eth1/11         121        S           e1b
cs1                    Eth1/12         121        S           e7b
cs2                    Eth1/13         121        S           e7b
cs1                    Eth1/14         121        S           e10b
cs2                    Eth1/15         121        S           e10b
cs1                    Eth1/16         121        S           e11b
cs2                    Eth1/17         121        S           e11b
952551000983           Eth1/19/1       120        S           e1a
952551000983           Eth1/19/2       120        S           e3a
952551000983           Eth1/19/3       120        S           e1a
952551000983           Eth1/19/4       120        S           e3a
952551000983           Eth1/20/1       120        S           e2a
952551000983           Eth1/20/2       120        S           e4a
952551000983           Eth1/20/3       120        S           e2a
952551000983           Eth1/20/4       120        S           e4a
.
.
.
----
====
. スイッチのCLIを使用して、以下のコマンドでクラスタノードが正しいクラスタVLANに属していることを確認します。
+
[source, cli]
----
show vlan brief
----
+
[source, cli]
----
show interface trunk
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show vlan brief*

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po1, Po998, Po999, Eth1/1
                                                Eth1/2, Eth1/3, Eth1/4, Eth1/5
                                                Eth1/6, Eth1/7, Eth1/8, Eth1/9
                                                Eth1/10, Eth1/11, Eth1/12
                                                Eth1/13, Eth1/14, Eth1/15
                                                Eth1/16, Eth1/17, Eth1/18
                                                Eth1/36, Eth1/19/1, Eth1/19/2
                                                Eth1/19/3, Eth1/19/4, Eth1/20/1
.
.

                                                Eth1/33/4, Eth1/34/1, Eth1/34/2
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
17   VLAN0017                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/19/1, Eth1/19/2
                                                Eth1/19/3, Eth1/19/4, Eth1/20/1
                                                Eth1/20/2, Eth1/20/3, Eth1/20/4
                                                Eth1/21/1, Eth1/21/2, Eth1/21/3
.
.
                                                Eth1/30/4, Eth1/31/1, Eth1/31/2
                                                Eth1/31/3, Eth1/31/4, Eth1/32/1
                                                Eth1/32/2, Eth1/32/3, Eth1/32/4
                                                Eth1/33/1, Eth1/33/2, Eth1/33/3
                                                Eth1/33/4, Eth1/34/1, Eth1/34/2
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
18   VLAN0018                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/19/1, Eth1/19/2
                                                Eth1/19/3, Eth1/19/4, Eth1/20/1
.
.
                                                Eth1/30/1, Eth1/30/2, Eth1/30/3
                                                Eth1/30/4, Eth1/31/1, Eth1/31/2
                                                Eth1/31/3, Eth1/31/4, Eth1/32/1
                                                Eth1/32/2, Eth1/32/3, Eth1/32/4
                                                Eth1/33/1, Eth1/33/2, Eth1/33/3
                                                Eth1/33/4, Eth1/34/1, Eth1/34/2
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
30   VLAN0030                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/19/1, Eth1/19/2
                                                Eth1/19/3, Eth1/19/4, Eth1/20/1
                                                Eth1/20/2, Eth1/20/3, Eth1/20/4
.
.
                                                Eth1/33/1, Eth1/33/2, Eth1/33/3
                                                Eth1/33/4, Eth1/34/1, Eth1/34/2
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
40   VLAN0040                         active    Po1, Eth1/1, Eth1/2, Eth1/3
                                                Eth1/4, Eth1/5, Eth1/6, Eth1/7
                                                Eth1/8, Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/36, Eth1/19/1
                                                Eth1/19/2, Eth1/19/3, Eth1/19/4
                                                Eth1/20/1, Eth1/20/2, Eth1/20/3
                                                Eth1/20/4, Eth1/21/1, Eth1/21/2
                                                Eth1/21/3, Eth1/21/4, Eth1/22/1
                                                Eth1/22/2, Eth1/22/3, Eth1/22/4
                                                Eth1/23/1, Eth1/23/2, Eth1/23/3
                                                Eth1/23/4, Eth1/24/1, Eth1/24/2
                                                Eth1/24/3, Eth1/24/4, Eth1/25/1
                                                Eth1/25/2, Eth1/25/3, Eth1/25/4
                                                Eth1/26/1, Eth1/26/2, Eth1/26/3
                                                Eth1/26/4, Eth1/27/1, Eth1/27/2
                                                Eth1/27/3, Eth1/27/4, Eth1/28/1
.
.
                                                Eth1/34/2, Eth1/34/3, Eth1/34/4
                                                Eth1/35/1, Eth1/35/2, Eth1/35/3
                                                Eth1/35/4

cs1# *show interface trunk*

--------------------------------------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
--------------------------------------------------------------------------------

Eth1/1        1       trunking      --
Eth1/2        1       trunking      --
Eth1/3        1       trunking      --
Eth1/4        1       trunking      --
Eth1/5        1       trunking      --
Eth1/6        1       trunking      --
Eth1/7        1       trunking      --
Eth1/8        1       trunking      --
Eth1/9        1       trunking      --
Eth1/10       1       trunking      --
.
.
.
Eth1/30/1     1       trunking      --
Eth1/30/2     1       trunking      --
Eth1/30/3     1       trunking      --
Eth1/30/4     1       trunking      --
Eth1/31/1     1       trunking      --
Eth1/31/2     1       trunking      --
Eth1/31/3     1       trunking      --
Eth1/31/4     1       trunking      --
Eth1/32/1     1       trunking      --
Eth1/32/2     1       trunking      --
Eth1/32/3     1       trunking      --
Eth1/32/4     1       trunking      --
Eth1/33/1     1       trunking      --
Eth1/33/2     1       trunking      --
Eth1/33/3     1       trunking      --
Eth1/33/4     1       trunking      --
Eth1/34/1     1       trunking      --
Eth1/34/2     1       trunking      --
Eth1/34/3     1       trunking      --
Eth1/34/4     1       trunking      --
Eth1/35/1     1       trunking      --
Eth1/35/2     1       trunking      --
Eth1/35/3     1       trunking      --
Eth1/35/4     1       trunking      --
Eth1/36       1       trnk-bndl     Po1
Po1           1       not-trunking  --


--------------------------------------------------------------------------------
Port          Vlans Allowed on Trunk
--------------------------------------------------------------------------------
Eth1/1        1,17-18,30,40
Eth1/2        1,17-18,30,40
Eth1/3        1,17-18,30,40
Eth1/4        1,17-18,30,40
Eth1/5        1,17-18,30,40
Eth1/6        1,17-18,30,40
Eth1/7        1,17-18,30,40
Eth1/8        1,17-18,30,40
Eth1/9        1,17-18,30,40
Eth1/10       1,17-18,30,40
Eth1/11       1,17-18,30,40
.
.
.
Eth1/30/1     1,17-18,30,40
Eth1/30/2     1,17-18,30,40
Eth1/30/3     1,17-18,30,40
Eth1/30/4     1,17-18,30,40
Eth1/31/1     1,17-18,30,40
Eth1/31/2     1,17-18,30,40
Eth1/31/3     1,17-18,30,40
Eth1/31/4     1,17-18,30,40
Eth1/32/1     1,17-18,30,40
Eth1/32/2     1,17-18,30,40
Eth1/32/3     1,17-18,30,40
Eth1/32/4     1,17-18,30,40
Eth1/33/1     1,17-18,30,40
Eth1/33/2     1,17-18,30,40
Eth1/33/3     1,17-18,30,40
Eth1/33/4     1,17-18,30,40
Eth1/34/1     1,17-18,30,40
Eth1/34/2     1,17-18,30,40
Eth1/34/3     1,17-18,30,40
Eth1/34/4     1,17-18,30,40
Eth1/35/1     1,17-18,30,40
Eth1/35/2     1,17-18,30,40
Eth1/35/3     1,17-18,30,40
Eth1/35/4     1,17-18,30,40
Eth1/36       1,40
Po1           1,40


--------------------------------------------------------------------------------
Port          Vlans Err-disabled on Trunk
--------------------------------------------------------------------------------
Eth1/1        none
Eth1/2        none
Eth1/3        none
Eth1/4        none
Eth1/5        none
Eth1/6        none
Eth1/7        none
Eth1/8        none
Eth1/9        none
Eth1/10       none
.
.
.
Eth1/30/1     none
Eth1/30/2     none
Eth1/30/3     none
Eth1/30/4     none
Eth1/31/1     none
Eth1/31/2     none
Eth1/31/3     none
Eth1/31/4     none
Eth1/32/1     none
Eth1/32/2     none
Eth1/32/3     none
Eth1/32/4     none
Eth1/33/1     none
Eth1/33/2     none
Eth1/33/3     none
Eth1/33/4     none
Eth1/34/1     none
Eth1/34/2     none
Eth1/34/3     none
Eth1/34/4     none
Eth1/35/1     none
Eth1/35/2     none
Eth1/35/3     none
Eth1/35/4     none
Eth1/36       none
Po1           none


--------------------------------------------------------------------------------
Port          STP Forwarding
--------------------------------------------------------------------------------
Eth1/1        1,17-18,30,40
Eth1/2        1,17-18,30,40
Eth1/3        1,17-18,30,40
Eth1/4        1,17-18,30,40
Eth1/5        1,17-18,30,40
Eth1/6        1,17-18,30,40
Eth1/7        1,17-18,30,40
Eth1/8        1,17-18,30,40
Eth1/9        none
Eth1/10       1,17-18,30,40
.
.
.
Eth1/30/1     none
Eth1/30/2     none
Eth1/30/3     none
Eth1/30/4     none
Eth1/31/1     none
Eth1/31/2     none
Eth1/31/3     none
Eth1/31/4     none
Eth1/32/1     none
Eth1/32/2     none
Eth1/32/3     none
Eth1/32/4     none
Eth1/33/1     none
Eth1/33/2     none
Eth1/33/3     none
Eth1/33/4     none
Eth1/34/1     none
Eth1/34/2     none
Eth1/34/3     none
Eth1/34/4     none
Eth1/35/1     none
Eth1/35/2     none
Eth1/35/3     none
Eth1/35/4     none
Eth1/36       none
Po1           none


--------------------------------------------------------------------------------
Port          Vlans in spanning tree forwarding state and not pruned
--------------------------------------------------------------------------------
Eth1/1        Feature VTP is not enabled 1,17-18,30,40
Eth1/2        Feature VTP is not enabled 1,17-18,30,40
Eth1/3        Feature VTP is not enabled 1,17-18,30,40
Eth1/4        Feature VTP is not enabled 1,17-18,30,40
Eth1/5        Feature VTP is not enabled 1,17-18,30,40
Eth1/6        Feature VTP is not enabled 1,17-18,30,40
Eth1/7        Feature VTP is not enabled 1,17-18,30,40
Eth1/8        Feature VTP is not enabled 1,17-18,30,40
Eth1/9        Feature VTP is not enabled 1,17-18,30,40
Eth1/10       Feature VTP is not enabled 1,17-18,30,40
.
.
.
Eth1/30/1     Feature VTP is not enabled none
Eth1/30/2     Feature VTP is not enabled none
Eth1/30/3     Feature VTP is not enabled none
Eth1/30/4     Feature VTP is not enabled none
Eth1/31/1     Feature VTP is not enabled none
Eth1/31/2     Feature VTP is not enabled none
Eth1/31/3     Feature VTP is not enabled none
Eth1/31/4     Feature VTP is not enabled none
Eth1/32/1     Feature VTP is not enabled none
Eth1/32/2     Feature VTP is not enabled none
Eth1/32/3     Feature VTP is not enabled none
Eth1/32/4     Feature VTP is not enabled none
Eth1/33/1     Feature VTP is not enabled none
Eth1/33/2     Feature VTP is not enabled none
Eth1/33/3     Feature VTP is not enabled none
Eth1/33/4     Feature VTP is not enabled none
Eth1/34/1     Feature VTP is not enabled none
Eth1/34/2     Feature VTP is not enabled none
Eth1/34/3     Feature VTP is not enabled none
Eth1/34/4     Feature VTP is not enabled none
Eth1/35/1     Feature VTP is not enabled none
Eth1/35/2     Feature VTP is not enabled none
Eth1/35/3     Feature VTP is not enabled none
Eth1/35/4     Feature VTP is not enabled none
Eth1/36       Feature VTP is not enabled none
Po1           Feature VTP is not enabled none
----
====
+

NOTE: 特定のポートと VLAN の使用法の詳細については、RCF のバナーと重要な注意事項のセクションを参照してください。

. スイッチのCLIを使用して、cs1とcs2間のISLが正常に機能していることを確認します。
+
[source, cli]
----
show port-channel summary
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SD)     Eth      LACP      Eth1/36(D)
998   Po998(SD)   Eth      NONE      --
999   Po999(SD)   Eth      NONE      --
----
====
. ONTAP CLIを使用して、クラスタLIFがホームポートに戻っていることを確認します。
+
[source, cli]
----
network interface show -role cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current     Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node        Port    Home
----------- --------------- ---------- ------------------ ----------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01    e2a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01    e2b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02    e2a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02    e2b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03    e2a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03    e2b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04    e2a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04    e2b     true
----
====
+
クラスタ LIF がホーム ポートに戻っていない場合は、ローカル ノードから手動で元に戻します。

+
`network interface revert -vserver vserver_name -lif <lif-name>`

. ONTAP CLI を使用して、クラスターが正常であることを確認します：
+
[source, cli]
----
cluster show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health  Eligibility   Epsilon
----------------- ------- ------------- -------
node1-01          true    true          false
node1-02          true    true          false
node1-03          true    true          true
node1-04          true    true          false
----
====
. ONTAP CLI を使用して、リモートクラスタインターフェースの接続性を確認します。
+
.. 使用することができます `network interface check cluster-connectivity show`クラスター接続のアクセシビリティ チェックの詳細を表示するコマンド:
+
[source, cli]
----
network interface check cluster-connectivity show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*

                                  Source           Destination     Packet
Node   Date                       LIF              LIF             Loss
------ -------------------------- ---------------- --------------- -----------
node1-01
       6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1   none
       6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus1   none


node1-02
       6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1   none
       6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2   none
.
.
.
----
====
.. あるいは、 `cluster ping-cluster -node <node-name>`接続を確認するコマンド:
+
[source, cli]
----
cluster ping-cluster -node <node-name>
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node1-04
Getting addresses from network interface table...
Cluster node1-01_clus1 169.254.36.44 node1-01 e7a
Cluster node1-01_clus2 169.254.7.5   node1-01 e7b
Cluster node1-02_clus1 169.254.197.206 node1-02 e7a
Cluster node1-02_clus2 169.254.195.186 node1-02 e7b
Cluster node1-03_clus1 169.254.192.49 node1-03 e7a
Cluster node1-03_clus2 169.254.182.76 node1-03 e7b
Cluster node1-04_clus1 169.254.59.49 node1-04 e7a
Cluster node1-04_clus2 169.254.62.244 node1-04 e7b
Local = 169.254.59.49 169.254.62.244
Remote = 169.254.36.44 169.254.7.5 169.254.197.206 169.254.195.186 169.254.192.49 169.254.182.76
Cluster Vserver Id = 4294967293
Ping status:
............
Basic connectivity succeeds on 12 path(s)
Basic connectivity fails on 0 path(s)
................................................
Detected 9000 byte MTU on 12 path(s):
    Local 169.254.59.49 to Remote 169.254.182.76
    Local 169.254.59.49 to Remote 169.254.192.49
    Local 169.254.59.49 to Remote 169.254.195.186
    Local 169.254.59.49 to Remote 169.254.197.206
    Local 169.254.59.49 to Remote 169.254.36.44
    Local 169.254.59.49 to Remote 169.254.7.5
    Local 169.254.62.244 to Remote 169.254.182.76
    Local 169.254.62.244 to Remote 169.254.192.49
    Local 169.254.62.244 to Remote 169.254.195.186
    Local 169.254.62.244 to Remote 169.254.197.206
    Local 169.254.62.244 to Remote 169.254.36.44
    Local 169.254.62.244 to Remote 169.254.7.5
Larger than PMTU communication succeeds on 12 path(s)
RPC status:
6 paths up, 0 paths down (tcp check)
6 paths up, 0 paths down (udp check)
----
====




.次の手順
スイッチの RCF をアップグレードしたら、link:configure-verify-ssh-9808.html["ログ収集のためにSSHを確認する"]。
