---
sidebar: sidebar 
permalink: switch-cisco-9808/install-prepare-9808.html 
keywords: shared storage cluster switch 
summary: 新しい AFX 2K システムの一部として Cisco Nexus 9808 スイッチをインストールする準備として、スイッチのドキュメント、サポートされている RCF バージョン、および Smart Call Home の要件を確認します。 
---
= AFX システムへの Cisco Nexus 9808 スイッチのインストール準備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
該当する Cisco スイッチのドキュメントを確認し、サポートされている RCF バージョンを理解し、Smart Call Home の設定を検討することで、新しい AFX 2K システムの一部として Cisco Nexus 9808 スイッチをインストールする準備を行います。



[[step-1-review-the-cisco-switch-documentation]]
=== ステップ 1：Cisco スイッチのドキュメントを確認する

以下の Cisco インストールおよびセットアップに関するドキュメントを参照して、スイッチのリリースノート、安全情報、インストールオプション、初期ソフトウェア構成、およびコマンドリファレンスについて理解を深めてください。

すべての Cisco ドキュメントは、link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 シリーズ スイッチのサポート"^] ページで入手できます。

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-release-notes-list.html["Cisco Nexus 9000 シリーズ NX-OS リリース ノート"^]（お使いのスイッチにインストールされている NX-OS リリースのリリースノートを選択してください）
* link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/hw/regulatory/compliance/RCSI.html?dtid=osscdc000283&linkclickid=srch["Cisco Nexus 9000 シリーズの規制コンプライアンスおよび安全性に関する情報"^]
* link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/hw/9800/9808/nx-os/cisco-nexus-9808-nx-os-mode-switch-hardware-installation-guide/m-8000-modular-overview-ph2.html?linkclickid=aisrch["Cisco Nexus 9808 NX-OS モードスイッチ ハードウェアインストールガイド"^]
* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-and-configuration-guides-list.html["Cisco Nexus 9000 シリーズ スイッチ ソフトウェア コンフィギュレーション ガイド"^](スイッチにインストールされている NX-OS リリースのガイドを選択してください)
* link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html["Cisco Nexus 9000 シリーズ NX-OS コマンド リファレンス"^] Cisco が提供するさまざまなコマンドリファレンスへのリンクを提供します。




[[step-2-review-the-netapp-systems-documentation]]
=== ステップ2：NetApp システムドキュメントを確認する

以下の NetApp システムドキュメントを確認し、AFX 2K システムのインストール、ONTAP リリース情報、ハードウェア構成および互換性要件について理解しておいてください。

* link:https://docs.netapp.com/us-en/ontap-afx/index.html["AFXシステムのドキュメント"^]NetApp ハードウェアのインストール方法について説明します。
* link:https://docs.netapp.com/us-en/ontap-family/["ONTAPのドキュメント"^] ONTAP リリースのあらゆる側面に関する詳細な情報を提供します。
* link:https://hwu.netapp.com["NetApp Hardware Universe"^] NetApp のハードウェア構成および互換性情報を提供します。
* link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["HWU にない機器をインストールするには、どのような追加情報が必要ですか?"^]ストレージシステムの設置要件に関する詳細情報を提供します。




[[step-3-understand-the-supported-rcf-versions]]
=== ステップ3：サポートされているRCFバージョンを理解する

お使いのAFXシステムで実行されているONTAPのバージョンとスイッチのNX-OSのバージョンによって、スイッチでサポートされるRCFのバージョンが決まります。RCFバージョンには、ブレークアウトモード（4x100GbE）と非ブレークアウトモードのスイッチポートの数を決定する、プリセットされたポート速度構成があります。

[NOTE]
====
現在サポートされている RCF バージョンの一覧については、link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["NetApp Cisco イーサネットスイッチ"^]ページを参照してください。

スイッチポート情報は、link:https://hwu.netapp.com["NetApp Hardware Universe"^]にも記載されています。

====
お使いのAFX 2Kシステムでは、RCF 10.1以降がサポートされています。

例えば、次の表は、RCF バージョン 10.1 に基づいた、スイッチポートのプリセットグループ、ポート速度、および使用状況を示しています。

[cols="1,2"]
|===
| スイッチポートグループ | ポートの速度と使用状況 


 a| 
Ethernet1/1/1-4 から Ethernet1/14/1-4 まで
 a| 
クラスター内接続、HA接続、およびストレージシェルフ接続用の4x100GbEモード



 a| 
Ethernet1/15からEthernet1/30
 a| 
クラスター内接続、HA接続、ストレージ接続用の400GbEモード



 a| 
イーサネット1/31、イーサネット1/32
 a| 
400GbE クラスタ内 ISL 接続

|===
[NOTE]
====
AFXシステムで異なるポート速度構成に対応する必要がある場合は、プリセットグループを変更して、ブレークアウトモード（4x100GbE）と400GbEモードのスイッチポート数を調整できます。

これは後で、RCFのインストール手順の一環として行います。

====


[[step-4-consider-using-smart-call-home]]
=== ステップ4：Smart Call Homeの使用を検討する

ONTAP は、AFX クラスタスイッチを監視するためのイーサネットスイッチヘルスモニタリング（CSHM）をサポートするとともに、スイッチ診断ログを収集する機能も備えています。

Cisco の Smart Call Home は、スイッチで発生する可能性のあるあらゆる問題を解決するために、プロアクティブなサポートを提供するオプションです。

Smart Call Home に関する詳細情報は、link:configure-smart-call-9808.html["スマートコールホームの設定"] のドキュメントをご参照ください。

.次の手順
スイッチの設置準備ができたら、link:install-switches-9808.html["スイッチを取り付けます"]。
