---
permalink: switch-cisco-9336c-fx2-shared/configure-switch-overview-9336c-shared.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Cisco Nexus 9336C-FX2共有スイッチのインストールと設定の概要 
---
= Cisco Nexus 9336C-FX2共有スイッチのインストールと設定の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9336C-FX2共有スイッチは、Cisco Nexus 9000プラットフォームの一部であり、ネットアップシステムキャビネットに設置できます。共有スイッチを使用すると、クラスタとストレージの機能を共有スイッチ構成に組み合わせることができ、共有クラスタとストレージリファレンス構成ファイルを使用できます。



== 初期設定の概要

ONTAP を実行しているシステムでCisco Nexus 9336C-FX2スイッチを初期設定するには、次の手順を実行します。

. link:cable-9336c-shared.html["ケーブル接続ワークシートに記入"]。
+
ケーブル接続の図を使用して、コントローラとスイッチをケーブル接続します。

. link:install-9336c-shared.html["スイッチを設置します"]。
. link:setup-and-configure-9336c-shared.html["スイッチを設定します"]。
. link:install-switch-and-passthrough-panel-9336c-shared.html["ネットアップキャビネットにスイッチを設置"]。
+
構成に応じて、Cisco Nexus 9336C-FX2スイッチとパススルーパネルは、スイッチに付属の標準ブラケットを使用してネットアップキャビネットに設置できます。

. link:prepare-nxos-rcf-9336c-shared.html["NX-OSおよびRCFのインストールを準備します"]。
. link:install-nxos-software-9336c-shared.html["NX-OS ソフトウェアをインストールします"]。
. link:install-nxos-rcf-9336c-shared.html["RCF構成ファイルをインストールします"]。
+
Nexus 9336C-FX2スイッチを初めてセットアップしたあとに、RCFをインストールします。この手順を使用して、 RCF のバージョンをアップグレードすることもできます。





== 追加情報

インストールまたはメンテナンスを開始する前に、次の点を確認してください。

* link:configure-reqs-9336c-shared.html["設定要件"]
* link:components-9336c-shared.html["コンポーネントとパーツ番号"]
* link:required-documentation-9336c-shared.html["必要なドキュメント"]

