---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/configure-reqs-9336c-shared.html 
keywords: shared storage cluster switch 
summary: ONTAP 9.9.1 以降では、 Cisco Nexus 9336C-FX2 スイッチを使用して、ストレージとクラスタ機能を共有スイッチ シナリオに組み合わせることができます。 
---
= Cisco Nexus 9336C-FX2 共有スイッチの構成要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9336C-FX2 スイッチのインストールとメンテナンスについては、構成とネットワーク要件を必ず確認してください。



== ONTAPのサポート

ONTAP 9.9.1 以降では、 Cisco Nexus 9336C-FX2 スイッチを使用して、ストレージとクラスタ機能を共有スイッチ構成に組み合わせることができます。

2 つ以上のノードを持つONTAPクラスターを構築する場合は、サポートされているネットワーク スイッチが 2 つ必要です。



== 構成要件

構成するには、スイッチに適した数と種類のケーブルおよびケーブル コネクタが必要です。

最初に設定するスイッチのタイプに応じて、付属のコンソール ケーブルを使用してスイッチのコンソール ポートに接続する必要があります。また、特定のネットワーク情報も提供する必要があります。



== ネットワーク要件

すべてのスイッチ構成には次のネットワーク情報が必要です。

* 管理ネットワークトラフィック用の IP サブネット
* 各ストレージ システム コントローラおよび該当するすべてのスイッチのホスト名と IP アドレス
* ほとんどのストレージ システム コントローラは、イーサネット サービス ポート (レンチ アイコン) に接続して e0M イ​​ンターフェイスを介して管理されます。  AFF A800およびAFF A700sシステムでは、e0M イ​​ンターフェイスは専用のイーサネット ポートを使用します。
* 参照 https://hwu.netapp.com["Hardware Universe"]最新情報についてはこちらをご覧ください。


スイッチの初期設定の詳細については、次のガイドを参照してください。 https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9336c-fx2-e/cisco-nexus-9336c-fx2-e-nx-os-mode-switch-hardware-installation-guide.html["Cisco Nexus 9336C-FX2 インストールおよびアップグレード ガイド"] 。

.次の手順
構成要件を確認した後、 link:components-9336c-shared.html["コンポーネントと部品番号"]。
