---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switchless-cluster-dat-storage.html 
keywords:  
summary:  
---
= 直接接続型ストレージを使用するスイッチレスクラスタから移行する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
2つの新しい共有スイッチを追加することで、直接接続ストレージを使用するスイッチレスクラスタから移行できます。

使用する手順は、各コントローラに 2 つの専用クラスタネットワークポートがあるか、 1 つのクラスタポートがあるかによって異なります。ここで説明するプロセスは、すべてのノードで光ポートまたはTwinaxポートを使用しているものの、ノードでクラスタネットワークポートにオンボード10Gb BASE-T RJ45ポートが使用されている場合は、このスイッチではサポートされません。

ほとんどのシステムでは、各コントローラに 2 つの専用クラスタネットワークポートが必要です。を参照してください https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco イーサネットスイッチ"] を参照してください。

既存の 2 ノードスイッチレスクラスタ環境を使用している場合は、 Cisco Nexus 9336C-FX2 スイッチを使用して 2 ノードスイッチクラスタ環境に移行し、 3 ノード以上にクラスタを拡張できます。



== 要件を確認

次の点を確認します

* 2ノードスイッチレス構成の場合：
+
** 2ノードスイッチレス構成が適切にセットアップされて機能しています。
** ノードでONTAP 9.8以降を実行している。
** すべてのクラスタポートが「稼働」状態です。
** すべてのクラスタLIF（論理インターフェイス）の状態が* up *になっていて、ホーム*ポートにあることを確認します。


* Cisco Nexus 9336C-FX2スイッチの構成の場合：
+
** 両方のスイッチに管理ネットワーク接続があります。
** クラスタスイッチへのコンソールアクセスがあります。
** Nexus 9336C-FX2ノード間スイッチおよびスイッチ間接続には、Twinaxケーブルまたはファイバケーブルを使用します。
** ネットアップ https://hwu.netapp.com["Hardware Universe"] ケーブル接続の詳細については、を参照してください。
** スイッチ間リンク（ISL）ケーブルは、9336C-FX2スイッチのポート1/35および1/36に接続されています。


* 9336C-FX2スイッチの初期カスタマイズが完了しました。次のようにします。
+
** 9336C-FX2 スイッチは最新バージョンのソフトウェアを実行しています
** リファレンス構成ファイル（ RCF ）がスイッチに適用されている場合
** SMTP、SNMP、SSHなどのサイトのカスタマイズは、新しいスイッチで設定されます。






== スイッチを移行します

.例について
この手順の例では、クラスタスイッチとノードで次の命名法を使用しています。

* 9336C-FX2 スイッチの名前は、 _CS1_および CS2__ です。
* クラスタ SVM の名前は、 _node1 と _node2 _ です。
* LIF の名前は、ノード 1 では _node1_clus1_AND _node1_clus2_on 、ノード 2 では _node2_clus1_and _node2_clus2_on です。
* cluster1 ： * > プロンプトは、クラスタの名前を示します。
* この手順で使用されているクラスタポートは、 AFF A400 コントローラに準拠した _e3a および _e3b です。。 https://hwu.netapp.com["Hardware Universe"] プラットフォームの実際のクラスタポートに関する最新情報が含まれます。




=== 手順1：直接接続型のスイッチレスクラスタから移行する

. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。「 system node AutoSupport invoke -node * -type all -message MAINT= xh 」
+
x は、メンテナンス時間の長さ（時間単位）です。




NOTE: AutoSupport メッセージはテクニカルサポートにこのメンテナンスタスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

. [step2]権限レベルをadvancedに変更します。続行するかどうかを尋ねられたら、「y」と入力します。
+
「 advanced 」の権限が必要です

+
advanced のプロンプト（ * > ）が表示されます。

. 新しいクラスタスイッチ cs1 と cs2 の両方で、すべてのノード側ポート（ ISL ポートではない）を無効にします。ISL ポートを無効にしないでください。
+
.例を示します
[%collapsible]
====
次の例は、スイッチ cs1 でノードに接続されたポート 1~34 が無効になっていることを示しています。

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *shutdown*
----
====


. [[step4] 2つの9336C-FX2スイッチcs1とcs2間のISLでISLポートと物理ポートがポート1/35および1/36で動作していることを確認します。
+
「ポートチャネルの概要」

+
.例を示します
[%collapsible]
====
次の例は、スイッチ cs1 上の ISL ポートが up になっていることを示しています。

[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
次の例は、スイッチ cs2 上の ISL ポートが up になっていることを示しています。

[listing, subs="+quotes"]
----
       cs2# *show port-channel summary*
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====


. [[step5]隣接デバイスのリストを表示します。
+
'How CDP Neighbors' を参照してください

+
このコマンドは、システムに接続されているデバイスに関する情報を提供します。

+
.例を示します
[%collapsible]
====
次の例は、スイッチ cs1 上の隣接デバイスを示しています。

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
次の例は、スイッチ cs2 上の隣接デバイスを表示します。

[listing, subs="+quotes"]
----
cs2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====


. [[step6]すべてのクラスタポートが稼働していることを確認します。
+
`network port show - ipspace Cluster`

+
各ポートで、Linkにはup、Health Statusにはhealthyと表示されるはずです。

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
====


. [[step7]すべてのクラスタLIFが稼働していることを確認します。
+
`network interface show - vserver Cluster`

+
各クラスタ LIF は 'Is Home' に true を表示し 'Status Admin/Oper は up/up と表示する必要があります

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
====


. [[step8]すべてのクラスタLIFで自動リバートが有効になっていることを確認します。
+
`network interface show - vserver Cluster -fields auto-revert`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
====


. [[step9] ：ノード 1 のクラスタポート e3a からケーブルを外し、クラスタスイッチ cs1 のポート 1 に e3a に接続します。これには、 9336C-FX2 スイッチでサポートされている適切なケーブル接続を使用します。
+
ネットアップ https://hwu.netapp.com["Hardware Universe"] ケーブル接続の詳細については、を参照してください。

. 9336C-FX2 スイッチでサポートされている適切なケーブル接続を使用して、ノード 2 のクラスタポート e3a からケーブルを外し、クラスタスイッチ cs1 のポート 2 に e3a を接続します。
. クラスタスイッチ cs1 のすべてのノード側ポートを有効にします。
+
.例を示します
[%collapsible]
====
次の例は、スイッチ cs1 でポート 1/1~1/34 が有効になっていることを示しています。

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *no shutdown*
----
====


. [[step12]]すべてのクラスタLIFが* up *、Operational、およびdisplay as true forであることを確認します `Is Home`：
+
`network interface show - vserver Cluster`

+
.例を示します
[%collapsible]
====
次の例は、ノード 1 とノード 2 のすべての LIF が * up * で、 Is Home の結果が * true であることを示しています。

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
====


. [[step13]]クラスタ内のノードのステータスに関する情報を表示します。
+
「 cluster show 」を参照してください

+
.例を示します
[%collapsible]
====
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====


. [[step14]] ノード 1 のクラスタポート e3b からケーブルを外し、 9336C-FX2 スイッチでサポートされている適切なケーブルを使用して、クラスタスイッチ cs2 のポート 1 に e3b を接続します。
. ノード 2 のクラスタポート e3b からケーブルを外し、 9336C-FX2 スイッチでサポートされている適切なケーブルを使用して、クラスタスイッチ cs2 のポート 2 に e3b を接続します。
. クラスタスイッチ cs2 のすべてのノード側ポートを有効にします。
+
.例を示します
[%collapsible]
====
次の例は、スイッチ cs2 でポート 1/1~1/34 が有効になっていることを示しています。

[listing, subs="+quotes"]
----
cs2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/1-34*
cs2(config-if-range)# *no shutdown*
----
====


. [[step17]]すべてのクラスタポートが稼働していることを確認します。
+
`network port show - ipspace Cluster`

+
.例を示します
[%collapsible]
====
次の例は、ノード 1 とノード 2 のすべてのクラスタポートが up になっていることを示しています。

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
====


. [[step18]]すべてのインターフェイスでtrueが表示されることを確認します `Is Home`：
+
`network interface show - vserver Cluster`

+

NOTE: この処理が完了するまでに数分かかることがあります。

+
.例を示します
[%collapsible]
====
次の例は、ノード 1 とノード 2 のすべての LIF が * up * であり、 Is Home の結果が true であることを示しています。

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
====


. [[step19]]両方のノードに各スイッチへの接続が1つあることを確認します。
+
'How CDP Neighbors' を参照してください

+
.例を示します
[%collapsible]
====
次の例は、両方のスイッチの該当する結果を示しています。

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====


. [[step20]]クラスタ内で検出されたネットワークデバイスに関する情報を表示します。
+
「 network device-discovery show -protocol cdp 」と入力します

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
====


. [[step21] HAペア1（およびHAペア2）のストレージ構成が正しいこととエラーがないことを確認します。
+
`system switch ethernet show`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====


. [[step22]]設定が無効になっていることを確認します。
+
network options switchless-cluster show

+

NOTE: コマンドが完了するまでに数分かかることがあります。3 分間の有効期間が終了することを通知するアナウンスが表示されるまで待ちます。

+
次の例では 'false' の出力は ' 構成設定が無効になっていることを示しています

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
====


. [[step23]]クラスタ内のノードメンバーのステータスを確認します。
+
「 cluster show 」を参照してください

+
.例を示します
[%collapsible]
====
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====


. [[step24]]クラスタネットワークが完全に接続されていることを確認します。
+
cluster ping-cluster -node node-name

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====


. [[step25]]権限レベルをadminに戻します。
+
「特権管理者」





=== 手順2：共有スイッチをセットアップします

この手順の例では、スイッチとノードで次の命名法を使用しています。

* 2 つの共有スイッチの名前は、 _sh1_AND _sh2__ です。
* ノードは、 _ node1 _ と _ node2 _ です。



NOTE: 手順 ONTAP では、特に記載がない限り、 ONTAP コマンドと Cisco Nexus 9000 シリーズスイッチコマンドの両方を使用する必要があります。

. HAペア1（およびHAペア2）のストレージ構成が正しいこと、およびエラーがないことを確認します。
+
`system switch ethernet show`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. ストレージノードポートが正常で動作していることを確認します。
+
storage port show -port-type enet

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
====


. [[step3]] HA ペア 1 、 NSM224 パス A のポートを sh1 ポート範囲 11-22 に移動します。
. HA ペア 1 の node1 のパス A から sh1 のポート範囲 11-22 にケーブルを接続します。たとえば、 AFF A400 のパス A のストレージポートは e0c です。
. HA ペア 1 、 node2 、パス A から sh1 のポート範囲 11-22 へケーブルを接続します。
. ノードポートが正常で動作していることを確認します。
+
storage port show -port-type enet

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. クラスタにストレージスイッチやケーブル接続の問題がないことを確認します。
+
`system health alert show -instance`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. HAペア1のNSM224パスBポートを、sh2ポート範囲11-22に移動します。
. HA ペア 1 、 node1 、パス B から sh2 のポート範囲 11-22 にケーブルを接続します。たとえば、 AFF A400 のパス B ストレージポートは e5b になります。
. HA ペア 1 、 node2 、パス B から sh2 のポート範囲 11-22 にケーブルを接続します。
. ノードポートが正常で動作していることを確認します。
+
storage port show -port-type enet

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. HAペア1のストレージ構成が正しいこと、およびエラーがないことを確認します。
+
`system switch ethernet show`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. HAペア1の未使用の（コントローラ）セカンダリストレージポートをストレージからネットワークに再設定します。複数の NS224 が直接接続されている場合は、ポートを再設定する必要があります。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
storage port modify –node [node name] –port [port name] –mode network
----
====
+
ストレージポートをブロードキャストドメインに配置するには、次の手順を実行します。

+
** 「 network port broadcast-domain create 」（必要に応じて新しいドメインを作成）
** 「 network port broadcast-domain add-ports 」（既存のドメインにポートを追加する）


. ケースの自動作成を抑制した場合は、 AutoSupport メッセージを呼び出して作成を再度有効にします。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます



.次の手順
link:../switch-cshm/config-overview.html["スイッチヘルス監視の設定"]です。
