---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switched-configuration-dat-storage.html 
keywords:  
summary:  
---
= 直接接続ストレージを使用したスイッチ構成からの移行
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
2 つの新しい共有スイッチを追加することで、直接接続ストレージを使用したスイッチ構成から移行できます。

.サポートされるスイッチ
次のスイッチがサポートされています。

* Nexus 9336C-FX2
* Nexus 3232C


この手順でサポートされているONTAPおよび NX-OS のバージョンについては、 Ciscoイーサネット スイッチ ページをご覧ください。見る https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネットスイッチ"]。

.接続ポート
スイッチは、次のポートを使用してノードに接続します。

* Nexus 9336C-FX2：
+
** ポート1～3：ブレークアウト モード（4x10G）クラスタ内ポート、int e1/1/1～4、e1/2/1～4、e1/3/1～4
** ポート4～6：ブレークアウト モード（4x25G）クラスタ内 / HAポート、int e1/4/1～4、e1/5/1～4、e1/6/1～4
** ポート7～34：40/100GbEクラスタ内 / HAポート、int e1/7～34


* Nexus 3232C：
+
** ポート1～30: 10/40/100 GbE


* スイッチは次のスイッチ間リンク (ISL) ポートを使用します。
+
** ポートint e1/35～36：Nexus 9336C-FX2
** ポート e1/31-32: Nexus 3232C




その https://hwu.netapp.com["Hardware Universe"]すべてのクラスタ スイッチでサポートされているケーブル接続に関する情報が含まれています。

.要件
* 次のタスクが完了していることを確認してください。
+
** Nexus 9336C-FX2 スイッチの一部のポートを 100 GbE で動作するように構成しました。
** ノードから Nexus 9336C-FX2 スイッチへの 100 GbE 接続を計画、移行、文書化しました。
** 他のCiscoクラスタ スイッチをONTAPクラスタからCisco Nexus 9336C-FX2 ネットワーク スイッチに無停止で移行しました。


* 既存のスイッチ ネットワークは適切に設定され、機能しています。
* 中断のない操作を保証するために、すべてのポートは *up* 状態になっています。
* Nexus 9336C-FX2 スイッチは、適切なバージョンの NX-OS がインストールされ、参照構成ファイル (RCF) が適用された状態で設定され、動作しています。
* 既存のネットワーク構成は次のとおりです。
+
** どちらも古いCiscoスイッチを両方使用する、完全に機能している冗長なNetAppクラスタ。
** 古いCiscoスイッチと新しいスイッチ両方への管理接続とコンソール アクセス。
** すべてのクラスタ LIF が *up* 状態にあり、クラスタ LIF がホーム ポート上にあります。
** ISL ポートが有効になり、他のCiscoスイッチ間および新しいスイッチ間でケーブル接続されます。




.例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 既存のCisco Nexus 3232C クラスタ スイッチは _c1_ と _c2_ です。
* 新しい Nexus 9336C-FX2 スイッチは _sh1_ と _sh2_ です。
* ノードは _node1_ と _node2_ です。
* クラスター LIF は、ノード 1 ではそれぞれ _node1_clus1_ と _node1_clus2_、ノード 2 では _node2_clus1_ と _node2_clus2_ です。
* 最初にスイッチc2をスイッチsh2に交換し、次にスイッチc1をスイッチsh1に交換します。


.手順
. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all -message MAINT=x h`

+
ここで、x はメンテナンス ウィンドウの期間 (時間単位) です。

. 各クラスタ ポートの管理ステータスと動作ステータスを確認します。
. すべてのクラスター ポートが正常な状態で稼働していることを確認します。
+
`network port show –role cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
====


. [[step4]]すべてのクラスタ インターフェイス (LIF) がホーム ポート上にあることを確認します。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
====


. [[step5]]クラスタが両方のクラスタスイッチの情報を表示することを確認します。
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
====


. [[step6]]クラスタLIFの自動復帰を無効にします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
====


. [[step7]]c2スイッチをシャットダウンします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
====


. [[step8]]クラスタLIFがクラスタスイッチsh1でホストされているポートに移行されたことを確認します。
+
`network interface show -role cluster`

+
数秒かかる場合があります。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
====


. [[step9]]スイッチc2を新しいスイッチsh2に交換し、新しいスイッチのケーブルを再接続します。
. sh2 でポートが復旧したことを確認します。  *注意* LIF はまだスイッチ c1 上に残っています。
. c1 スイッチをシャットダウンします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
====


. [[step12]]クラスタLIFがクラスタスイッチsh2でホストされているポートに移行されたことを確認します。数秒かかる場合があります。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
====


. [[step13]]スイッチc1を新しいスイッチsh1に交換し、新しいスイッチのケーブルを再接続します。
. sh1 でポートが復旧したことを確認します。  *注意* LIF はまだスイッチ c2 上に残っています。
. クラスタ LIF で自動復帰を有効にします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
====


. [[step16]]クラスターが正常であることを確認します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----
====

