---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switchless-cluster-dat-storage.html 
keywords:  
summary:  
---
= 直接接続ストレージを備えたスイッチレス クラスタからの移行
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
2 つの新しい共有スイッチを追加することで、直接接続ストレージを備えたスイッチレス クラスターから移行できます。

使用する手順は、各コントローラに2つの専用クラスタネットワーク ポートがあるか、1つのクラスタ ポートがあるかによって異なります。記載されているプロセスは、光ポートまたは Twinax ポートを使用するすべてのノードで機能しますが、ノードがクラスタ ネットワーク ポートにオンボード 10Gb BASE-T RJ45 ポートを使用している場合、このスイッチではサポートされません。

ほとんどのシステムでは、各コントローラに2つの専用クラスタネットワーク ポートが必要です。見る https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"]詳細についてはこちらをご覧ください。

既存の2ノード スイッチレス クラスタ環境を使用している場合は、Cisco Nexus 9336C-FX2スイッチを使用して2ノード スイッチ クラスタ環境に移行し、3ノード以上にクラスタを拡張できます。



== 要件の確認

次のことを確認してください。

* 2 ノードのスイッチレス構成の場合:
+
** 2 ノードのスイッチレス構成が適切にセットアップされ、機能しています。
** ノードはONTAP 9.8 以降を実行しています。
** すべてのクラスター ポートは *up* 状態です。
** すべてのクラスタ論理インターフェイス (LIF) は *up* 状態であり、*home* ポート上にあります。


* Cisco Nexus 9336C-FX2 スイッチ構成の場合:
+
** 両方のスイッチには管理ネットワーク接続があります。
** クラスター スイッチへのコンソール アクセスがあります。
** Nexus 9336C-FX2 のノード間スイッチおよびスイッチ間接続には、Twinax ケーブルまたは光ファイバー ケーブルが使用されます。
** NetApp https://hwu.netapp.com["Hardware Universe"]ケーブル接続に関する詳細情報が記載されています。
** 両方の 9336C-FX2 スイッチのポート 1/35 と 1/36 に Inter-Switch Link (ISL) ケーブルが接続されています。


* 9336C-FX2 スイッチの初期カスタマイズが完了しました。次の状況を確認します。
+
** 9336C-FX2スイッチは最新バージョンのソフトウェアを実行しています
** リファレンス構成ファイル（RCF）がスイッチに適用されている
** SMTP、SNMP、SSH などのサイトのカスタマイズはすべて新しいスイッチで構成されます。






== スイッチを移行する

.例について
この手順の例では、クラスタ スイッチとノードで次の命名法を使用しています。

* 9336C-FX2 スイッチの名前は _cs1_ と _cs2_ です。
* クラスター SVM の名前は _node1_ と _node2_ です。
* LIF の名前は、ノード 1 ではそれぞれ _node1_clus1_ と _node1_clus2_、ノード 2 ではそれぞれ _node2_clus1_ と _node2_clus2_ です。
* cluster1::*> プロンプトはクラスターの名前を示します。
* この手順で使用されるクラスタ ポートは、 AFF A400コントローラに応じて、_e3a_ と _e3b_ です。その https://hwu.netapp.com["Hardware Universe"]プラットフォームの実際のクラスター ポートに関する最新情報が含まれています。




=== ステップ1: 直接接続されたスイッチレスクラスタから移行する

. このクラスタでAutoSupportが有効になっている場合は、 AutoSupportメッセージを呼び出して自動ケース作成を抑制します。 `system node autosupport invoke -node * -type all -message MAINT=xh` 。
+
ここで、x はメンテナンス ウィンドウの期間 (時間単位) です。




NOTE: AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

. [[step2]]権限レベルを「advanced」に変更し、続行するかどうかを尋ねられたら「y」と入力します。
+
`set -privilege advanced`

+
advancedのプロンプト（*>）が表示されます。

. 新しいクラスタ スイッチcs1とcs2の両方で、すべてのノード側ポート（ISLポートではない）を無効にします。ISLポートを無効にしないでください。
+
.例を表示
[%collapsible]
====
次の例は、スイッチcs1でノード側のポート1～34が無効になっていることを示しています。

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *shutdown*
----
====


. [[step4]]2つの9336C-FX2スイッチcs1とcs2間のISLとISL上の物理ポートがポート1/35と1/36で起動していることを確認します。
+
`show port-channel summary`

+
.例を表示
[%collapsible]
====
次の例は、スイッチ cs1 で ISL ポートが起動していることを示しています。

[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
次の例は、スイッチ cs2 で ISL ポートが起動していることを示しています。

[listing, subs="+quotes"]
----
       cs2# *show port-channel summary*
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====


. [[step5]]近隣デバイスのリストを表示します。
+
`show cdp neighbors`

+
このコマンドは、システムに接続されているデバイスに関する情報を提供します。

+
.例を表示
[%collapsible]
====
次の例は、スイッチcs1上の隣接デバイスを示しています。

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
次の例は、スイッチcs2上の隣接デバイスを示しています。

[listing, subs="+quotes"]
----
cs2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====


. [[step6]]すべてのクラスターポートが稼働していることを確認します。
+
`network port show - ipspace Cluster`

+
各ポートのリンクは「アップ」、ヘルスステータスは「正常」と表示されます。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
====


. [[step7]]すべてのクラスタLIFが稼働していることを確認します。
+
`network interface show - vserver Cluster`

+
各クラスタLIFは、 `Is Home`管理者/オペレーターのステータスが up/up であること。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
====


. [[step8]]すべてのクラスタLIFで自動復帰が有効になっていることを確認します。
+
`network interface show - vserver Cluster -fields auto-revert`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
====


. [[step9]]ノード1のクラスタポートe3aからケーブルを外し、9336C-FX2スイッチでサポートされている適切なケーブルを使用して、e3aをクラスタスイッチcs1のポート1に接続します。
+
NetApp https://hwu.netapp.com["Hardware Universe"]ケーブル接続に関する詳細情報が記載されています。

. ノード 2 のクラスター ポート e3a からケーブルを外し、9336C-FX2 スイッチでサポートされている適切なケーブルを使用して、e3a をクラスター スイッチ cs1 のポート 2 に接続します。
. クラスタ スイッチcs1のすべてのノード側ポートを有効にします。
+
.例を表示
[%collapsible]
====
次の例は、スイッチcs1でポート1/1～1/34が有効になっていることを示しています。

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *no shutdown*
----
====


. [[step12]]すべてのクラスタLIFが*up*、動作可能であり、trueと表示されていることを確認します。 `Is Home` :
+
`network interface show - vserver Cluster`

+
.例を表示
[%collapsible]
====
次の例は、ノード1とノード2のすべてのLIFが*up*であり、 `Is Home`結果は*真*です:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
====


. [[step13]]クラスター内のノードのステータスに関する情報を表示します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====


. [[step14]]ノード1のクラスタポートe3bからケーブルを外し、9336C-FX2スイッチでサポートされている適切なケーブルを使用して、e3bをクラスタスイッチcs2のポート1に接続します。
. ノード 2 のクラスター ポート e3b からケーブルを外し、9336C-FX2 スイッチでサポートされている適切なケーブルを使用して、e3b をクラスター スイッチ cs2 のポート 2 に接続します。
. クラスタ スイッチcs2のすべてのノード側ポートを有効にします。
+
.例を表示
[%collapsible]
====
次の例は、スイッチcs2でポート1/1～1/34が有効になっていることを示しています。

[listing, subs="+quotes"]
----
cs2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/1-34*
cs2(config-if-range)# *no shutdown*
----
====


. [[step17]]すべてのクラスターポートが稼働していることを確認します。
+
`network port show - ipspace Cluster`

+
.例を表示
[%collapsible]
====
次の例は、ノード 1 とノード 2 のすべてのクラスター ポートが稼働していることを示しています。

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
====


. [[step18]]すべてのインターフェースがtrueになっていることを確認します。 `Is Home` :
+
`network interface show - vserver Cluster`

+

NOTE: 完了するまでに数分かかる場合があります。

+
.例を表示
[%collapsible]
====
次の例は、ノード1とノード2のすべてのLIFが*up*であり、 `Is Home`結果は真です:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
====


. [[step19]]両方のノードが各スイッチに1つずつ接続されていることを確認します。
+
`show cdp neighbors`

+
.例を表示
[%collapsible]
====
次の例は、両方のスイッチの適切な結果を示しています。

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====


. [[step20]]クラスター内で検出されたネットワークデバイスに関する情報を表示します。
+
`network device-discovery show -protocol cdp`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
====


. [[step21]]HAペア1（およびHAペア2）のストレージ構成が正しく、エラーがないことを確認します。
+
`system switch ethernet show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====


. [[step22]]設定が無効になっていることを確認します。
+
`network options switchless-cluster show`

+

NOTE: コマンドが完了するまでに数分かかる場合があります。「3 分間の有効期限が切れます」というアナウンスを待ちます。

+
その `false`次の例の出力は、構成設定が無効になっていることを示しています。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
====


. [[step23]]クラスタ内のノードメンバーのステータスを確認します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
次の例は、クラスタ内のノードの正常性と適格性に関する情報を示します。

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step25]] 権限レベルを管理者に戻します。
+
`set -privilege admin`





=== ステップ2: 共有スイッチを設定する

この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 2 つの共有スイッチの名前は _sh1_ と _sh2_ です。
* ノードは _node1_ と _node2_ です。



NOTE: この手順では、 ONTAPコマンドとCisco Nexus 9000 シリーズ スイッチ コマンドの両方を使用する必要がありますが、特に明記されていない限り、 ONTAPコマンドが使用されます。

. HA ペア 1 (および HA ペア 2) のストレージ構成が正しく、エラーがないことを確認します。
+
`system switch ethernet show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. ストレージ ノードのポートが正常で動作していることを確認します。
+
`storage port show -port-type ENET`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
====


. [[step3]]HAペア1、NSM224パスAポートをsh1ポート範囲11〜22に移動します。
. HA ペア 1、ノード 1、パス A から sh1 ポート範囲 11 ～ 22 にケーブルを接続します。たとえば、 AFF A400のパスの A ストレージ ポートは e0c です。
. HA ペア 1、ノード 2、パス A から sh1 ポート範囲 11 ～ 22 にケーブルを接続します。
. ノード ポートが正常で動作していることを確認します。
+
`storage port show -port-type ENET`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. クラスターにストレージ スイッチまたはケーブル接続の問題がないことを確認します。
+
`system health alert show -instance`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. HA ペア 1、NSM224 パス B ポートを sh2 ポート範囲 11 ～ 22 に移動します。
. HA ペア 1、ノード 1、パス B から sh2 ポート範囲 11 ～ 22 にケーブルをインストールします。たとえば、 AFF A400のパス B ストレージ ポートは e5b です。
. HA ペア 1、ノード 2、パス B から sh2 ポート範囲 11 ～ 22 にケーブルをインストールします。
. ノード ポートが正常で動作していることを確認します。
+
`storage port show -port-type ENET`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. HA ペア 1 のストレージ構成が正しく、エラーがないことを確認します。
+
`system switch ethernet show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. HA ペア 1 上の未使用の (コントローラ) セカンダリ ストレージ ポートをストレージからネットワークに再構成します。複数の NS224 が直接接続されていた場合、再構成する必要があるポートが存在します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage port modify –node [node name] –port [port name] –mode network
----
====
+
ストレージ ポートをブロードキャスト ドメインに配置するには、次の手順を実行します。

+
** `network port broadcast-domain create`（必要に応じて新しいドメインを作成する）
** `network port broadcast-domain add-ports`（既存のドメインにポートを追加する）


. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.次の手順
スイッチを移行した後は、 link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを設定する"]。
