---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/replace-9336c-fx2-shared.html 
keywords:  
summary:  
---
= Cisco Nexus 9336C-FX2共有スイッチの交換
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
故障した Nexus 9336C-FX2 共有スイッチを交換できます。これは非中断手順 (NDU) です。

.開始する前に
スイッチの交換を実行する前に、次の点を確認してください。

* 既存のクラスターおよびネットワーク インフラストラクチャの場合:
+
** 既存のクラスターは、少なくとも 1 つの完全接続されたクラスター スイッチを備え、完全に機能していることが検証されます。
** すべてのクラスター ポートが *稼働* しています。
** すべてのクラスタ論理インターフェイス (LIF) は *稼働* しており、ホーム ポート上にあります。
** ONTAP のcluster ping-cluster -node node1 コマンドは、すべてのパスで基本接続と PMTU より大きい通信が成功していることを示す必要があります。


* Nexus 9336C-FX2 交換スイッチの場合:
+
** 交換スイッチ上の管理ネットワーク接続は機能しています。
** 交換用スイッチへのコンソール アクセスが確立されています。
** ノード接続はポート 1/1 ～ 1/34 です。
** ポート 1/35 および 1/36 のすべての Inter-Switch Link (ISL) ポートが無効になっています。
** 必要な参照構成ファイル (RCF) と NX-OS オペレーティング システム イメージ スイッチがスイッチにロードされます。
** STP、SNMP、SSHなどの、以前に実施されたすべてのサイト カスタマイズを、新しいスイッチにコピーする必要があります。




.例について
クラスタLIFを移行するコマンドは、そのクラスタLIFがホストされているノードで実行する必要があります。

この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 既存の Nexus 9336C-FX2 スイッチの名前は _sh1_ と _sh2_ です。
* 新しい Nexus 9336C-FX2 スイッチの名前は _newsh1_ と _newsh2_ です。
* ノード名は _node1_ と _node2_ です。
* 各ノードのクラスター ポートの名前は _e3a_ と _e3b_ です。
* クラスタLIF名は `node1_clus1`そして `node1_clus2`ノード1の場合、 `node2_clus1`そして `node2_clus2`ノード2用。
* すべてのクラスター ノードへの変更のプロンプトは cluster1::*> です。
+

NOTE: 次の手順は、次のネットワーク トポロジに基づいています。



.トポロジ例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.


cluster1::*> *network interface show -vserver Cluster*
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.

cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e3a    sh1                       Eth1/2            N9K-C9336C
            e3b    sh2                       Eth1/2            N9K-C9336C

node1      /cdp
            e3a    sh1                       Eth1/1            N9K-C9336C
            e3b    sh2                       Eth1/1            N9K-C9336C
4 entries were displayed.

sh1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         144    H           FAS2980       e3a
node2              Eth1/2         145    H           FAS2980       e3a
sh2                Eth1/35        176    R S I s     N9K-C9336C    Eth1/35
sh2 (FDO220329V5)   Eth1/36       176    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4

sh2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         139    H           FAS2980       eb
node2              Eth1/2         124    H           FAS2980       eb
sh1                Eth1/35        178    R S I s     N9K-C9336C    Eth1/35
sh1                Eth1/36        178    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====
.手順
. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
ここで、x はメンテナンス ウィンドウの期間 (時間単位) です。

. オプション: スイッチ newsh2 に適切な RCF とイメージをインストールし、必要なサイトの準備を行います。
+
.. 必要に応じて、新しいスイッチ用に、RCFおよびNX-OSソフトウェアの適切なバージョンを確認、ダウンロード、およびインストールします。新しいスイッチが正しくセットアップされ、RCFおよびNX-OSソフトウェアのアップデートが必要ないことを確認した場合は、<<step3,ステップ3>> 。
.. NetAppサポート サイトのNetAppクラスタおよび管理ネットワーク スイッチのリファレンス構成ファイルの説明ページにアクセスします。
.. クラスタ ネットワークと管理ネットワークの互換性マトリックスのリンクをクリックし、必要なスイッチ ソフトウェアのバージョンをメモします。
.. ブラウザの戻る矢印をクリックして説明ページに戻り、「続行」をクリックしてライセンス契約に同意し、ダウンロード ページに進みます。
.. ダウンロード ページの手順に従って、インストールするONTAPソフトウェアのバージョンに適した RCF および NX-OS ファイルをダウンロードします。


. [[step3]]新しいスイッチで管理者としてログインし、ノード クラスタ インターフェイスに接続されるすべてのポート (ポート 1/1 ～ 1/34) をシャットダウンします。交換するスイッチが機能せず、電源がオフになっている場合は、<<step4,ステップ4>> 。クラスタ ノードのLIFは、各ノードのもう一方のクラスタ ポートにすでにフェイルオーバーされている必要があります。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
newsh2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
newsh2(config)# *interface e1/1-34*
newsh2(config-if-range)# *shutdown*
----
====


. [[step4]]すべてのクラスタLIFで自動復帰が有効になっていることを確認します。
+
`network interface show - vserver Cluster -fields auto-revert`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster -fields auto-revert*
             Logical
Vserver      Interface     Auto-revert
------------ ------------- -------------
Cluster      node1_clus1   true
Cluster      node1_clus2   true
Cluster      node2_clus1   true
Cluster      node2_clus2   true
4 entries were displayed.
----
====


. [[step5]] リモートクラスタインターフェースの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step6]]Nexus 9336C-FX2スイッチsh1のISLポート1/35と1/36をシャットダウンします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
sh1# *configure*
Enter configuration commands, one per line. End with CNTL/Z.
sh1(config)# *interface e1/35-36*
sh1(config-if-range)# *shutdown*
----
====


. [[step7]]Nexus 9336C-FX2 sh2 スイッチからすべてのケーブルを取り外し、Nexus C9336C-FX2 sh2 スイッチの同じポートに接続します。
. sh1スイッチとnewsh2スイッチ間でISLポート1/35と1/36を起動し、ポート チャネルの動作ステータスを確認します。
+
ポートチャネルはPo1（SU）を示し、メンバー ポートはEth1/35（P）およびEth1/36（P）を示している必要があります。

+
.例を表示
[%collapsible]
====
この例では、ISL ポート 1/35 および 1/36 を有効にし、スイッチ sh1 のポート チャネルの概要を表示します。

[listing, subs="+quotes"]
----
sh1# *configure*
Enter configuration commands, one per line. End with CNTL/Z.
sh1 (config)# *int e1/35-36*
sh1 (config-if-range)# *no shutdown*
sh1 (config-if-range)# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member       Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)

sh1 (config-if-range)#
----
====


. [[step9]]すべてのノードでポートe3bが稼働していることを確認します。
+
`network port show ipspace Cluster`

+
.例を表示
[%collapsible]
====
出力は次のようになります。

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                         Ignore
                                                   Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ----- ---------- - - -------- ----
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                         Ignore
                                                   Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ----- ----------- -  -------- ----
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/auto    -        false
4 entries were displayed.
----
====


. [[step10]]前の手順で使用したのと同じノードで、network interface revert コマンドを使用して、前の手順でポートに関連付けられたクラスタ LIF を元に戻します。
+
この例では、Home 値が true でポートが e3b の場合、node1 上の LIF node1_clus2 は正常に元に戻されます。

+
次のコマンドは、ノード 1 の LIF node1_clus2 をホーム ポート e3a に返し、両方のノードの LIF に関する情報を表示します。両方のクラスター インターフェイスの Is Home 列が *true* であり、正しいポート割り当て (この例ではノード 1 の e3a と e3b) が表示されている場合、最初のノードの起動は成功です。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current    Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node       Port    Home
----------- ------------ ---------- ------------------ ---------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
            node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
            node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
            node2_clus2  up/up      169.254.19.183/16  node2      e3a     false
4 entries were displayed.
----
====


. [[step11]]クラスター内のノードに関する情報を表示します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
この例では、このクラスター内の node1 と node2 のノード ヘルスが true であることを示しています。

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node          Health  Eligibility
------------- ------- ------------
node1         false   true
node2         true    true
----
====


. [[step12]]すべての物理クラスタポートが稼働していることを確認します。
+
`network port show ipspace Cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node node1                                                                Ignore
                                                    Speed(Mbps)  Health   Health
Port      IPspace     Broadcast Domain  Link  MTU   Admin/Oper   Status   Status
--------- ----------- ----------------- ----- ----- ------------ -------- ------
e3a       Cluster     Cluster           up    9000  auto/100000  healthy  false
e3b       Cluster     Cluster           up    9000  auto/100000  healthy  false

Node: node2
                                                                          Ignore
                                                    Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link  MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ----- ----- ------------ -------- ------
e3a       Cluster      Cluster          up    9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up    9000  auto/100000  healthy  false
4 entries were displayed.
----
====


. [[step13]] リモートクラスタインターフェースの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step14]]次のクラスターネットワーク構成を確認します。
+
`network port show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                       Speed(Mbps)             Health   Health
Port      IPspace     Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ----------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster     Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster     Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                        Ignore
                                        Speed(Mbps)            Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000 auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000 auto/100000  healthy  false
4 entries were displayed.

cluster1::*> *network interface show -vserver Cluster*
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.

cluster1::> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e3a    sh1    0/2               N9K-C9336C
            e3b    newsh2                    0/2               N9K-C9336C
node1      /cdp
            e3a    sh1                       0/1               N9K-C9336C
            e3b    newsh2                    0/1               N9K-C9336C
4 entries were displayed.

sh1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID            Local Intrfce  Hldtme Capability  Platform      Port ID
node1                Eth1/1         144    H           FAS2980       e3a
node2                Eth1/2         145    H           FAS2980       e3a
newsh2               Eth1/35        176    R S I s     N9K-C9336C    Eth1/35
newsh2               Eth1/36        176    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4

sh2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         139    H           FAS2980       e3b
node2              Eth1/2         124    H           FAS2980       eb
sh1                Eth1/35        178    R S I s     N9K-C9336C    Eth1/35
sh1                Eth1/36        178    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====


. [[step15]]ストレージ ポートを古いスイッチ sh2 から新しいスイッチ newsh2 に移動します。
. HA ペア 1、共有スイッチ newsh2 に接続されているストレージが正常であることを確認します。
. HA ペア 2 に接続されているストレージ、共有スイッチ newsh2 が正常であることを確認します。
+
`storage port show -port-type ENET`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                            VLAN
Node    Port    Type    Mode       (Gb/s)      State     Status       ID
------- ------- ------- ---------- ----------- --------- --------- -----
node1
        e3a     ENET    storage          100   enabled   online       30
        e3b     ENET    storage            0   enabled   offline      30
        e7a     ENET    storage            0   enabled   offline      30
        e7b     ENET    storage          100   enabled   online       30

node2
        e3a     ENET    storage          100   enabled   online       30
        e3b     ENET    storage            0   enabled   offline      30
        e7a     ENET    storage            0   enabled   offline      30
        e7b     ENET    storage          100   enabled   online       30
----
====


. [[step18]]棚が正しくケーブル接続されていることを確認します。
+
`storage shelf port show -fields remote- device,remote-port`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port*
shelf id remote-port  remote-device
----- -- ------------ ----------------------------
3.20  0  Ethernet1/13 sh1
3.20  1  Ethernet1/13 newsh2
3.20  2  Ethernet1/14 sh1
3.20  3  Ethernet1/14 newsh2
3.30  0  Ethernet1/15 sh1
3.30  1  Ethernet1/15 newsh2
3.30  2  Ethernet1/16 sh1
3.30  3  Ethernet1/16 newsh2
8 entries were displayed.
----
====


. [[step19]]古いスイッチsh2を取り外します。
. スイッチ sh1 と新しいスイッチ newsh1 に対してこれらの手順を繰り返します。
. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.次の手順
link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを構成する"] 。
