---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/setup-and-configure-9336c-shared.html 
keywords:  
summary:  
---
= Cisco Nexus 9336C-FX2共有スイッチを設定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cisco Nexus 9336C-FX2共有スイッチを設定するには、次の手順に従います。

.必要なもの
* 必要な共有スイッチのドキュメント、コントローラのドキュメント、およびONTAP のドキュメントを参照してください link:required-documentation-9336c-shared.html["Cisco Nexus 9336C-FX2共有スイッチのマニュアル要件"] および https://docs.netapp.com/us-en/ontap/index.html["NetApp ONTAP のドキュメント"^]。
* 該当するライセンス、ネットワークおよび設定情報、ケーブル。
* 記入済みのケーブル接続ワークシートを参照してください link:cable-9336c-shared.html["Cisco Nexus 9336C-FX2ケーブル接続ワークシートに記入します"]。ケーブル接続の詳細については、を参照してください https://hwu.netapp.com["Hardware Universe"]。


.手順
. [[step3]]スイッチの初期設定を実行します。
+
構成には、スイッチに適した数とタイプのケーブルとコネクタが必要です。

+
最初に設定するスイッチのタイプに応じて、付属のコンソールケーブルを使用してスイッチのコンソールポートに接続する必要があります。また、特定のネットワーク情報を指定する必要があります。

. スイッチをブートします。
+
スイッチの初回ブート時に、次の初期セットアップに関する質問に適切な回答を入力します。

+
サイトのセキュリティポリシーでは、有効にする応答とサービスを定義しています。

+
.. 自動プロビジョニングを中止して通常のセットアップを続行しますか？（はい / いいえ）
+
* yes * と応答します。デフォルトは no です

.. セキュアなパスワード標準を適用しますか？（はい / いいえ）
+
* yes * と応答します。デフォルトは yes です。

.. admin のパスワードを入力します。
+
デフォルトのパスワードは admin です。新しい強力なパスワードを作成する必要があります。

+
脆弱なパスワードは拒否される可能性があります。

.. 基本設定ダイアログを開きますか？（はい / いいえ）
+
スイッチの初期設定時に * yes * と応答します。

.. 別のログインアカウントを作成しますか？（はい / いいえ）
+
回答は、代替管理者に関するサイトのポリシーに依存します。デフォルトは no です

.. 読み取り専用の SNMP コミュニティストリングを設定しますか？（はい / いいえ）
+
* no * と応答します。デフォルトは no です

.. 読み取り / 書き込み SNMP コミュニティストリングを設定しますか？（はい / いいえ）
+
* no * と応答します。デフォルトは no です

.. スイッチ名を入力します。
+
スイッチ名は 63 文字までの英数字に制限されます。

.. アウトオブバンド（ mgmt0 ）管理構成で続行しますか。（はい / いいえ）
+
そのプロンプトで * yes * （デフォルト）と応答します。mgmt0 IPv4 address: プロンプトで、 IP アドレス ip_address を入力します

.. default-gateway を設定？（はい / いいえ）
+
* yes * と応答します。default-gateway: プロンプトの IPv4 アドレスに、 default_gateway と入力します。

.. IP の詳細オプションを設定しますか？（はい / いいえ）
+
* no * と応答します。デフォルトは no です

.. Telnet サービスを有効にしますか？（はい / いいえ）
+
* no * と応答します。デフォルトは no です

.. SSH サービスを有効にしますか？（はい / いいえ）
+
* yes * と応答します。デフォルトは yes です。

+

NOTE: ログ収集機能にクラスタスイッチヘルスモニタ（ CSHM ）を使用する場合は、 SSH が推奨されます。セキュリティを強化するには、 SSHv2 も推奨されます。

.. [[step14]] 生成する SSH キーの種類を入力します (DSA/RSA/rsa1) 。デフォルトは rsa です。
.. キービット数（ 1024~2048 ）を入力します。
.. NTP サーバを設定？（はい / いいえ）
+
* no * と応答します。デフォルトは no です

.. デフォルトのインターフェイスレイヤ（ L3/L2 ）を設定します。
+
* L2 * と応答します。デフォルトは L2 です。

.. デフォルトのスイッチポートインターフェイスステート（ shut / noshut ）を設定します。
+
noshut * と応答します。デフォルトは noshut です。

.. CoPP システムプロファイルを設定する（ strict/moderm/lenenter/dense ）：
+
* strict * と応答します。デフォルトは strict です。

.. 設定を編集しますか？（はい / いいえ）
+
この時点で新しい設定が表示されます。入力した設定を確認し、必要な変更を行います。設定に問題がなければ、プロンプトで no と応答します。設定を編集する場合は、 * yes * と応答します。

.. この設定を使用して保存しますか？（はい / いいえ）
+
* yes * と応答して、設定を保存します。これにより、キックスタートイメージとシステムイメージが自動的に更新されます。



. セットアップの最後に表示される画面で選択した設定を確認し、設定を保存します。
+

NOTE: この段階で設定を保存しないと、次回スイッチをリブートしたときに変更が有効になりません。

. スイッチのソフトウェアバージョンを確認し、必要に応じてネットアップ対応バージョンのソフトウェアをスイッチにダウンロードします。
+
ネットアップ対応バージョンのサポートソフトウェアをダウンロードする場合は、 NetApp Network Switch Reference Configuration File もダウンロードし、に保存した構成とマージする必要があります <<step3,手順 3>>。

+
ファイルと手順は、からダウンロードできます https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco イーサネットスイッチ"] ページ

+
独自のスイッチがある場合は、を参照してください http://www.cisco.com["シスコ"] サイト



.次の手順
構成に応じて、を実行できます link:install-switch-and-passthrough-panel-9336c-shared.html["ネットアップキャビネットにスイッチを設置"]。それ以外の場合は、に進みます link:install-nxos-overview-9336c-storage.html["NX-OSおよびRCFのインストールを準備します"]。
