---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/setup-and-configure-9336c-shared.html 
keywords:  
summary:  
---
= Cisco Nexus 9336C-FX2共有スイッチを構成する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9336C-FX2 共有スイッチを設定するには、次の手順に従います。

.開始する前に
以下のものがあることを確認してください。

* 必要な共有スイッチのドキュメント、コントローラのドキュメント、およびONTAP のドキュメント。見るlink:required-documentation-9336c-shared.html["Cisco Nexus 9336C-FX2 共有スイッチのドキュメント要件"]そして https://docs.netapp.com/us-en/ontap/index.html["NetApp ONTAP ドキュメント"^]。
* 適用可能なライセンス、ネットワークおよび構成情報、およびケーブル。
* 完成したケーブル配線ワークシート。見るlink:cable-9336c-shared.html["Cisco Nexus 9336C-FX2 配線ワークシートを完成させる"] 。ケーブル接続の詳細については、 https://hwu.netapp.com["Hardware Universe"] 。


.手順
. [[step3]]スイッチの初期設定を実行します。
+
構成するには、スイッチに適した数と種類のケーブルおよびケーブル コネクタが必要です。

+
最初に設定するスイッチのタイプに応じて、付属のコンソール ケーブルを使用してスイッチのコンソール ポートに接続する必要があります。また、特定のネットワーク情報も提供する必要があります。

. スイッチを起動します。
+
スイッチを初めて起動するときに、次の初期設定の質問に適切な回答を入力してください。

+
サイトのセキュリティ ポリシーによって、有効にする応答とサービスが定義されます。

+
.. 自動プロビジョニングを中止して通常のセットアップを続行しますか?  （はい/いいえ）
+
「はい」と答えます。デフォルトは「いいえ」です。

.. 安全なパスワード標準を強制しますか?  （はい/いいえ）
+
「はい」と答えます。デフォルトは「はい」です。

.. 管理者のパスワードを入力してください。
+
デフォルトのパスワードは admin です。新しい強力なパスワードを作成する必要があります。

+
弱いパスワードは拒否される可能性があります。

.. 基本設定ダイアログに入りますか?  （はい/いいえ）
+
スイッチの初期設定では「*はい*」と応答します。

.. 別のログインアカウントを作成しますか?  （はい/いいえ）
+
答えは、代替管理者に関するサイトのポリシーによって異なります。デフォルトは「いいえ」です。

.. 読み取り専用 SNMP コミュニティ文字列を構成しますか?  （はい/いいえ）
+
「いいえ」と答えます。デフォルトは「いいえ」です。

.. 読み取り/書き込み SNMP コミュニティ文字列を構成しますか?  （はい/いいえ）
+
「いいえ」と答えます。デフォルトは「いいえ」です。

.. スイッチ名を入力します。
+
スイッチ名は 63 文字の英数字に制限されます。

.. アウトオブバンド (mgmt0) 管理構成を続行しますか?  （はい/いいえ）
+
そのプロンプトに対して「*yes*」（デフォルト）と応答します。  mgmt0 IPv4アドレス:プロンプトで、IPアドレスを入力します: ip_address

.. デフォルトゲートウェイを設定しますか?  （はい/いいえ）
+
「はい」と答えます。  default-gateway: プロンプトの IPv4 アドレスに、default_gateway を入力します。

.. 高度な IP オプションを構成しますか?  （はい/いいえ）
+
「いいえ」と答えます。デフォルトは「いいえ」です。

.. Telnet サービスを有効にしますか?  （はい/いいえ）
+
「いいえ」と答えます。デフォルトは「いいえ」です。

.. SSH サービスを有効にしますか?  （はい/いいえ）
+
「はい」と答えます。デフォルトは「はい」です。

+

NOTE: ログ収集機能のために Ethernet Switch Health Monitor (CSHM) を使用する場合は、SSH が推奨されます。セキュリティを強化するには、SSHv2も推奨されます。

.. [[step14]]生成するSSHキーの種類（dsa/rsa/rsa1）を入力します。デフォルトは rsa です。
.. キービット数（1024〜2048）を入力します。
.. NTP サーバーを設定しますか?  （はい/いいえ）
+
「いいえ」と答えます。デフォルトは「いいえ」です。

.. デフォルトのインターフェース層（L3/L2）を設定します。
+
*L2*で応答します。デフォルトは L2 です。

.. デフォルトのスイッチ ポート インターフェイスの状態 (shut/noshut) を設定します。
+
*noshut* と応答します。デフォルトは noshut です。

.. CoPP システム プロファイル (厳密/中程度/寛容/高密度) を設定します。
+
*strict* で応答します。デフォルトは厳密です。

.. 設定を編集しますか?  （はい/いいえ）
+
この時点で新しい構成が表示されるはずです。入力した設定を確認し、必要な変更を加えます。構成に満足している場合は、プロンプトに対して「no」と応答します。構成設定を編集する場合は、「はい」と答えてください。

.. この設定を使用して保存しますか?  （はい/いいえ）
+
設定を保存するには、「*はい*」と応答します。これにより、キックスタート イメージとシステム イメージが自動的に更新されます。



. セットアップの最後に表示される画面で選択した構成を確認し、必ず構成を保存してください。
+

NOTE: この段階で設定を保存しないと、次回スイッチを再起動したときに変更は有効になりません。

. クラスタネットワークスイッチのバージョンを確認し、必要に応じて、 NetAppがサポートするバージョンのソフトウェアをスイッチにダウンロードします。 https://software.cisco.com/download/home["Ciscoソフトウェアのダウンロード"^]ページ。


.次の手順
link:prepare-nxos-rcf-9336c-shared.html["NX-OSとRCFのインストール準備"] 。
