---
permalink: switch-cisco-9364d-gx2a/configure-install-upgrade-rcf-overview-9364d.html 
sidebar: sidebar 
keywords: install, upgrade, cluster, switch, cisco 9364d-gx2a 
summary: Cisco Nexus 9364D-GX2A スイッチに RCF をインストールまたはアップグレードします。AFX 1K および AFX 2K システムのインストール、スイッチの交換、または新しいハードウェアや ONTAP バージョンのサポートに対応します。 
---
= Cisco Nexus 9364D-GX2A スイッチへの RCF のインストールまたはアップグレードについて
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9364D-GX2A スイッチに参照構成ファイル（RCF）をインストールまたはアップグレードします。AFX 1K または AFX 2K システムのインストールまたはスイッチの交換用に新しい RCF をインストールするか、新しいハードウェアまたは ONTAP バージョンをサポートするために既存の RCF をアップグレードします。


NOTE: RCFのインストールまたはアップグレードは、NX-OSのインストールまたはアップグレードとは独立しています。NX-OSとRCFの両方をインストールまたはアップグレードする場合は、先にNX-OSをインストールまたはアップグレードすることをお勧めします。



[[understand-the-supported-rcf-versions]]
=== サポートされているRCFバージョンを理解する

お使いのAFXシステムで実行されているONTAPのバージョンとスイッチのNX-OSのバージョンによって、スイッチでサポートされるRCFのバージョンが決まります。RCFバージョンには、ブレークアウトモード（4x100GbE）と非ブレークアウトモードのスイッチポートの数を決定する、プリセットされたポート速度構成があります。

[NOTE]
====
現在サポートされている RCF バージョンの一覧については、link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["NetApp Cisco イーサネットスイッチ"^]ページを参照してください。

スイッチポート情報は、 https://hwu.netapp.com["NetApp Hardware Universe"^]にも記載されています。

====
* AFX 1Kシステムをお持ちの場合は、RCF 10.0以降がサポートされています。
* AFX 2Kシステムをお持ちの場合は、RCF 10.1以降がサポートされています。
* RCF 10.0 には 1 つのファイルがあり、共有スイッチをサポートしています。 `Cluster-HA-Storage AFX RCF_10.0`
+
例えば、次の表は、この RCF ファイルにおけるスイッチポートのプリセットされたグループ分け、ポート速度、および使用状況を示しています。

+
[cols="1,2"]
|===
| スイッチポートグループ | ポートの速度と使用状況 


 a| 
Ethernet1/1/1-4 から Ethernet1/62/1-4
 a| 
クラスタ、HA、ストレージ接続用の4x100GbEモード



 a| 
イーサネット1/63、イーサネット1/64
 a| 
400GbE ISL

|===
* RCF 10.1には、AFX 1KシステムとAFX 2Kシステムそれぞれで、異なる使用事例に対応した異なるファイルが含まれています。AFX 1KまたはAFX 2Kシステム構成でスイッチをどのように使用するか（共有、ストレージ専用、クラスタおよびHA専用）に応じて、適切なRCFファイルを選択します。
+
例えば、AFX 2Kシステムでスイッチを共有スイッチとして使用する場合は、その使用状況に適したRCFファイルを使用します。適切なRCFファイルは、 `RCF-v10.1-NX9364D-GX2A-CL1-ST1-100GBR31-400G31.txt`のように命名される場合があります。以下の表は、このRCFファイルにおけるスイッチポートのプリセットグループ、ポート速度、および使用状況を示しています。

+
[cols="1,2"]
|===
| スイッチポートグループ | ポートの速度と使用状況 


 a| 
Ethernet1/1/1-4 から Ethernet1/31/1-4 まで
 a| 
クラスター内接続、HA接続、およびストレージシェルフ接続用の4x100GbEモード



 a| 
Ethernet1/32からEthernet1/62
 a| 
クラスター内接続、HA接続、ストレージ接続用の400GbEモード



 a| 
イーサネット1/63、イーサネット1/64
 a| 
400GbE クラスタ内 ISL 接続

|===
+
[NOTE]
====
AFXシステムで異なるポート速度構成に対応する必要がある場合は、プリセットグループを変更して、ブレークアウトモード（4x100GbE）と400GbEモードのスイッチポート数を調整できます。

これは後で、RCFのインストールまたはアップグレード手順の一環として行います。

====




[[change-port-speed-configuration]]
=== ポート速度設定を変更する

RCF 10.1以降を搭載したスイッチでは、AFXシステムに合わせて異なるポート速度構成に対応する必要がある場合、ポート速度設定を変更して、ブレークアウトモード（4x100GbE）と非ブレークアウトモード（400GbE）のスイッチポート数を調整できます。

この変更は、RCFのインストールまたはアップグレード手順の一環として実施します。手順には、このページにリンクするステップが含まれています。

両方のスイッチにコマンドを入力します。

[cols="1,2"]
|===
| ポート速度を変更する | 手順 


 a| 
非ブレークアウトポートをブレークアウトポートに変更する
 a| 
. CLIで設定モードに入ります。
. スイッチのポート速度とブレークアウトモードを変更します：
+
ブレークアウトポートを指定するには、 `interface breakout module`コマンドを使用します。

+
例えば、400GbE モードのポート 15～19 をブレークアウト（4x100GbE）ポートとして指定するには、以下を使用します。

+
`interface breakout module 1 port 15-19 map 100g-4x`

. 目的のポート速度を実現するためにポートプロファイルを使用する必要がある新しいポートをポートリストに追加して変更します。
+
例えば、100G スピードのポート プロファイル用に新しいポート 15～19 でポート リストを変更するには、以下を使用します。

+
`interface e1/15/1-4, e1/16/1-4, e1/17/1-4, e1/18/1-4, e1/19/1-4`

. スイッチのブレークアウトポート（4x100GbE）を100GbE用にハードコーディングします。速度をハードコーディングしない場合、ポートは起動せず、エラー無効状態になります。
+
`speed 100000`

+
`no negotiate auto`





 a| 
ブレークアウトポートを非ブレークアウトポートに戻す
 a| 
. CLIで設定モードに入ります。
. ブレークアウトポートを非ブレークアウトポートに戻すには、設定モードで `no interface breakout`コマンドを使用します。
+
例えば、ポート15～19を400GbEモードに戻すには、以下を使用します。

+
`no interface breakout module 1 port 15-19`



|===


[[suggested-documentation]]
=== 推奨ドキュメント

スイッチに RCF をインストールまたはアップグレードする前に、以下のドキュメントを確認することをお勧めします。

* RCF のインストールまたはアップグレードに関する詳細については、NetApp ナレッジベースの記事 link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["リモート接続を維持しながらCiscoインターコネクトスイッチの設定をクリアする方法"^] を参照してください。
*  https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^]を参照して、プラットフォームの正しいポートを確認してください。
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ (NSS)"^]
+
サポートされているONTAPおよび RCF バージョンについては、 NetAppサポート サイトのスイッチ互換性表を参照してください。  RCF のコマンド構文と特定のバージョンの NX-OS の構文の間にはコマンド依存関係がある可能性があることに注意してください。

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 シリーズ スイッチ"^]
+
Ciscoスイッチのアップグレードおよびダウングレード手順の完全なドキュメントについては、 Cisco Web サイトで入手可能な適切なソフトウェアおよびアップグレード ガイドを参照してください。



.次の手順
RCF のインストールまたはアップグレードの概要を確認したら、必要に応じてlink:configure-install-rcf-9364d.html["RCFをインストールする"]またはlink:configure-upgrade-rcf-9364d.html["RCFをアップグレードする"]を実行できます。
