---
permalink: switch-cisco-9364d-gx2a/configure-upgrade-nxos-9364d.html 
sidebar: sidebar 
keywords: procedure, install, nx-os, software, nexus, cluster, switch, install the nx-os software - cisco nexus 9364d-gx2a 
summary: Cisco Nexus 9364D-GX2A スイッチの NX-OS をアップグレードして、AFX 1K または AFX 2K システムで新しいハードウェアまたは新しい ONTAP バージョンをサポートします。 
---
= Cisco Nexus 9364D-GX2A スイッチの NX-OS をアップグレードする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9364D-GX2A スイッチの NX-OS をアップグレードして、AFX 1K または AFX 2K システムで新しいハードウェアまたは新しい ONTAP バージョンをサポートします。


NOTE: NetApp では、最初に ONTAP ソフトウェアのアップグレードを完了してから、スイッチのソフトウェアアップグレードを実行することをお勧めします。

.開始する前に
* スイッチの設定に関する最新のバックアップがあることを確認してください。
* クラスターが完全に機能していることを確認してください。つまり、ログにエラーや同様の問題がないことを確認してください。


.タスク概要
* 必要に応じて、詳細についてはlink:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/101x/upgrade/cisco-nexus-9000-nx-os-software-upgrade-downgrade-guide-101x.html["Cisco Nexus 9000 シリーズ NX-OS ソフトウェアのアップグレードおよびダウングレード ガイド"^]を参照してください。
* 必要に応じて、link:https://www.cisco.com/c/dam/en/us/td/docs/dcn/tools/nexus-9k3k-issu-matrix/index.html["Cisco Nexus 9000 および 3000 のアップグレードと ISSU マトリックス"^]を参照してください。これは、現在のリリースとターゲットリリースに基づいた Cisco Nexus 9000 シリーズスイッチのサービス中ソフトウェアアップグレード（ISSU）に関する情報を提供します。
+
このページで、「*Disruptive Upgrade*」を選択し、ドロップダウン リストから現在のリリースとターゲット リリースを選択します。

* お使いのAFXシステムで実行されているONTAPのバージョンによって、スイッチでサポートされるNX-OSのバージョンが決まります。
+
** AFX 1K システム内のスイッチの場合、サポートされているバージョンの ONTAP を実行していれば、NX-OS 10.4.2 以降がサポートされます。
** AFX 2K システム内のスイッチの場合、ONTAP 9.19.1GA 以降を実行している場合、NX-OS 10.6 以降がサポートされています。
+
サポートされている NX-OS バージョンの現在のリストについては、link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["NetApp Cisco イーサネットスイッチ"^]ページを参照してください。

+

NOTE: NX-OSのバージョンをサポートされていないバージョンにアップグレードまたはダウングレードしないでください。



* この手順では、ONTAP コマンドと Cisco Nexus 9000 シリーズスイッチのコマンドを使用するため、各手順にはコマンドを入力する際に使用する CLI が示されています。
* この手順の例で使用するスイッチとノードの名前は次のとおりです。
+
** 2 つのCiscoスイッチの名前は cs1 と cs2 です。
** ノード名は、node1-01、node1-02、node1-03、node1-04 です。
** クラスタ LIF 名は次のとおりです。
+
*** node1-01 の node1-01_clus1 と node1-01_clus2
*** node1-02 の node1-02_clus1 と node1-02_clus2
*** node1-03 の node1-03_clus1 と node1-03_clus2
*** node1-04 の node1-04_clus1 と node1-04_clus2


** その `cluster1::*>`プロンプトはクラスターの名前を示します。


* この手順で示す例は、RCF 10.0を実行しているスイッチを備えたAFX 1Kシステムを対象としています。AFX 2Kシステムをお持ちの場合、入力と出力は異なる場合があります。




[[step-1-prepare-to-upgrade-the-nx-os]]
== ステップ1：NX-OSのアップグレード準備

NX-OS のアップグレードに備えるには、各スイッチへの管理ネットワーク接続が確立されていることを確認し、NX-OS のバージョンをダウンロードし、クラスタ上のポートのステータスを確認し、クラスタ LIF の自動リバートを無効にしてください。

.手順
. 各スイッチを管理ネットワークに接続します。
. スイッチのCLIを使用して、NX-OSをホストしているサーバーへの接続を確認します。
+
`ping <IP address>`

+
.例を表示
[%collapsible]
====
次の例では、スイッチがIPアドレス172.19.2.1のサーバに接続できることを確認します。

[listing, subs="+quotes"]
----
cs1# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
.  https://software.cisco.com/download/home["Ciscoソフトウェアのダウンロード"^]ページからスイッチに適切なバージョンのNX-OSをダウンロードしてください。
. ONTAP CLI を使用して、クラスタスイッチに接続されている各ノードのクラスタポートを表示します：
+
[source, cli]
----
network device-discovery show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID) Interface         Platform
----------- ------ ------------------------ ----------------  ----------------
node1-01/cdp
            e10a   cs1(FLMXXXXXXXX)         Ethernet1/16/3    N9K-C9364D-GX2A
            e10b   cs2(FDOXXXXXXXX)         Ethernet1/13/3    N9K-C9364D-GX2A
            e11a   cs1(FLMXXXXXXXX)         Ethernet1/16/4    N9K-C9364D-GX2A
            e11b   cs2(FDOXXXXXXXX)         Ethernet1/13/4    N9K-C9364D-GX2A
            e1a    cs1(FLMXXXXXXXX)         Ethernet1/16/1    N9K-C9364D-GX2A
            e1b    cs2(FDOXXXXXXXX)         Ethernet1/13/1    N9K-C9364D-GX2A
            .
            .
            .

            e7a    cs1(FLMXXXXXXXX)         Ethernet1/16/2    N9K-C9364D-GX2A
            e7b    cs2(FDOXXXXXXXX)         Ethernet1/13/2    N9K-C9364D-GX2A

node1-01/lldp
            e10a   cs1 (c8:60:8f:xx:xx:xx)  Ethernet1/16/3    -
            e10b   cs2 (04:e3:87:xx:xx:xx)  Ethernet1/13/3    -
            e11a   cs1 (c8:60:8f:xx:xx:xx)  Ethernet1/16/4    -
            e11b   cs2 (04:e3:87:xx:xx:xx)  Ethernet1/13/4    -
            e1a    cs1 (c8:60:8f:xx:xx:xx)  Ethernet1/16/1    -
            e1b    cs2 (04:e3:87:xx:xx:xx)  Ethernet1/13/1    -
            .
            .
            .
            e7a    cs1 (c8:60:8f:xx:xx:xx)  Ethernet1/16/2    -
            e7b    cs2 (04:e3:87:xx:xx:xx)  Ethernet1/13/2    -
.
.
.
----
====
. ONTAP CLI を使用して、各ポートの管理ステータスと運用ステータスを確認します。
+
.. *クラスターポート*
+
... すべてのクラスター ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: node1-03

                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
... すべてのクラスタ インターフェイス (LIF) がホーム ポート上にあることを確認します。
+
[source, cli]
----
network interface show -role cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current   Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node      Port    Home
----------- --------------- ---------- ------------------ --------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01  e7a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01  e7b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02  e7a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02  e7b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03  e7a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03  e7b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04  e7a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04  e7b     true

8 entries were displayed.
----
====
... クラスターが両方のクラスター スイッチの情報を表示することを確認します。
+
[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs2(FDOXXXXXXXX)            cluster-network    10.228.137.233   N9K-C9364D-GX2A
     Serial Number: FDOXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP


cs1(FLMXXXXXXXX)             cluster-network   10.228.137.253   N9K-C9364D-GX2A
     Serial Number: FLMXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP

2 entries were displayed.
----
====


.. *HAポート*
+
... すべての HA ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
ha interconnect status show -node <node-name>
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====


.. *ストレージポート*
+
... すべてのストレージ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage port show -port-type ENET
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*

                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-02
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-03
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
node1-04
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
16 entries were displayed.
----
====


.. *ストレージシェルフポート*
+
... すべてのストレージ シェルフ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage shelf port show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.1
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false

16 entries were displayed.
----
====
... すべてのストレージ シェルフ ポートの接続ステータスを確認します。
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 CX9332D-cs1
1.1   1  connected       Ethernet1/15/1 CX9364D-cs1
1.1   2  connected       Ethernet1/17/2 CX9332D-cs1
1.1   3  connected       Ethernet1/15/2 CX9364D-cs1
1.1   4  connected       Ethernet1/17/3 CX9332D-cs1
1.1   5  connected       Ethernet1/15/3 CX9364D-cs1
1.1   6  connected       Ethernet1/17/4 CX9332D-cs1
1.1   7  connected       Ethernet1/15/4 CX9364D-cs1
1.1   8  connected       Ethernet1/19/1 CX9332D-cs1
1.1   9  connected       Ethernet1/17/1 CX9364D-cs1
1.1   10 connected       Ethernet1/19/2 CX9332D-cs1
1.1   11 connected       Ethernet1/17/2 CX9364D-cs1
1.1   12 connected       Ethernet1/19/3 CX9332D-cs1
1.1   13 connected       Ethernet1/17/3 CX9364D-cs1
1.1   14 connected       Ethernet1/19/4 CX9332D-cs1
1.1   15 connected       Ethernet1/17/4 CX9364D-cs1

16 entries were displayed.
----
====




. ONTAP CLIを使用して、クラスタLIFの自動リバートを無効にします。クラスタLIFはパートナークラスタスイッチにフェイルオーバーし、対象スイッチでこの手順を実行する間、そのままの状態を維持します。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----




[[step-2-install-the-nx-os-and-epld-image]]
== ステップ2：NX-OS と EPLD イメージをインストールする

最初のスイッチ（cs1）に NX-OS と EPLD イメージをインストールして確認し、クラスタのすべてのポートの健全性を検証してから、2 番目のスイッチ（cs2）で同じ手順を繰り返します。

. NX-OSとEPLDイメージをインストールします。手順は、現在の NX-OS バージョンとターゲットの NX-OS バージョンによって異なる場合があります。
+
ご自身の状況に該当するタブを選択してください。

+
** 10.4(2)Fから10.6(3)F以降へのアップグレード
** 10.6(3)Fからそれ以降のバージョンにアップグレードする




[role="tabbed-block"]
====
.10.4(2)Fから10.6(3)F以降へのアップグレード
--
以下の手順を実行するには、スイッチのCLIを使用してコマンドを入力します。

. [[stepa]] NX-OSとEPLDイメージを最初のスイッチにコピーします。
+
`copy <protocol>: bootflash: vrf management`

+
.例
[%collapsible]
=====
....
cs1# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.10.6.3.F.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> *progress*
Progress meter enabled
sftp> *get /code/nxos.10.6.3.F.bin /bootflash/nxos.10.6.3.F.bin*
/code/nxos.10.6.3.F.bin  100% 1261MB   9.3MB/s   02:15
sftp> *exit*
Copy complete, now saving to disk (please wait)...
Copy complete.


cs1# *copy sftp: bootflash: vrf management*
Enter source filename: */code/n9000-epld.10.6.3.F.img*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> *progress*
Progress meter enabled
sftp> *get /code/n9000-epld.10.6.3.F.img /bootflash/n9000-epld.10.6.3.F.img*
/code/n9000-epld.10.6.3.F.img  100%  161MB   9.5MB/s   00:16
sftp> *exit*
Copy complete, now saving to disk (please wait)...
Copy complete.
....
=====
. NX-OSの実行バージョンを確認します。
+
`show version`

+
.例
[%collapsible]
=====
....
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.38
  NXOS: version 10.6.3(F)
  BIOS compile time:  05/29/2020
  NXOS image file is: bootflash:///nxos.10.6.3.F.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 02:28:31]


Hardware
  cisco Nexus9000 C9336C-FX2 Chassis
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K

  Device name: cs1
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)


Last reset at 157524 usecs after Mon Nov  2 18:32:06 2020
  Reason: Reset Requested by CLI command reload
  System version: 9.3(4)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

cs1#
....
=====
. NX-OSおよびEPLDイメージをインストールします。
+
[NOTE]
====
NX-OS 10.6(3)F以降にアップグレードしても、EPLDイメージは自動的に更新されません。アップグレードが完了し、スイッチが再起動したら、同じアップグレード `install all`コマンドを再度実行する必要があります。

** 2回目のアップグレード処理では検証が行われますが、NX-OS のアップグレードはスキップされ、EPLD イメージのみが更新されます。
** 既にNX-OS 10.6(3)F以降にアップグレード済みの場合、両方のイメージが同時に更新されます。


====
+
イメージファイルをインストールすると、スイッチが再起動するたびにそのイメージファイルが読み込まれるようになります。

+
`install all nxos bootflash:nxos.<version number>.bin`

+
.例
[%collapsible]
=====
....
cs1# *install all nxos bootflash:nxos.10.6.3.F.bin*   <---- 1st pass updates NX-OS only

Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.10.6.3.F.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.10.6.3.F.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.10.6.3.F.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  Bootable  Impact          Install-type  Reason
------  --------  --------------- ------------  ---------
1       yes       Disruptive      Reset         Default upgrade is not hitless


Images will be upgraded according to following table:

Module   Image    Running-Version(pri:alt)                 New-Version          Upg-Required
------- --------- ---------------------------------------- -------------------- ------------ 
1        nxos     10.4(2)(F)                                10.6(3)(F)            yes
1        bios     v05.47(04/28/2022):v05.47(04/28/2022)    v05.53(01/22/2025)     yes

Switch will be reloaded for disruptive upgrade.

Do you want to continue with the installation (y/n)? [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS
[####################] 100% -- SUCCESS

Finishing the upgrade, switch will reboot in 10 seconds.

. Using the switch CLI, verify the new version of NX-OS after the switch reboots:
+
`show version`
+

.Example
[%collapsible]

....
=====


....
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 05.33
  NXOS: version 10.6.3(f)
  BIOS compile time:  09/08/2018
  NXOS image file is: bootflash:///nxos.10.6.3.F.bin
  NXOS compile time:  11/4/2018 21:00:00 [11/05/2018 06:11:06]


Hardware
  cisco Nexus9000 C9332C-GX2B Chassis
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K

  Device name: cs1
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)

Last reset at 277524 usecs after Mon Nov  2 22:45:12 2020
  Reason: Reset due to upgrade
  System version: 9.3(4)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):
....
[]
=====
. スイッチのリブート後に再度ログインし、新しいバージョンのEPLDが正常にロードされたことを確認します。
+
`show version module 1 epld`



=====
....
cs2# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI   FPGA                        0x7
IO   FPGA                        0x19
MI   FPGA2                       0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
....
[]
=====

=====
--
.10.6(3)Fからそれ以降のバージョンにアップグレードする
--
以下の手順を実行するには、スイッチのCLIを使用してコマンドを入力します。

. NX-OSとEPLDのイメージを最初のスイッチにコピーします。
+
`copy <protocol>: bootflash: vrf management`

+
.例
[%collapsible]
=====
この例では、sftp と NX-OS バージョン 10.6(4)M を使用しています。

....
cs1# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos64-cs.10.6.4.M.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> *progress*
Progress meter enabled
sftp> *get /code/nxos64-cs.10.6.4.M.bin /bootflash/nxos64-cs.10.6.4.M.bin*
/code/nxos64-cs.10.6.4.M.bin  100% 1261MB   9.3MB/s   02:15
sftp> *exit*
Copy complete, now saving to disk (please wait)...
Copy complete.
....
=====
. NX-OS の実行中のバージョンを確認します：
+
`show version`

+
.例
[%collapsible]
=====
....
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.6.4.M [Feature Release]
  Host NXOS: version 10.6.4.M
  BIOS compile time:  11/25/2026
  NXOS image file is: bootflash:///nxos.10.6.4.M.bin
  NXOS compile time:  02/27/2026 12:00:00 [03/14/2026 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco  Nexus9000 C9364D-GX2A Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs1
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Mar 5 15:55:08 2026
  Reason: Reset Requested by CLI command reload
  System version: 10.5.3(f)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs1#
....
=====
. NX-OSとEPLDイメージをインストールします。
+
イメージ ファイルをインストールすると、スイッチをリブートするたびにこのファイルがロードされます。

+
`install all nxos bootflash:nxos.<version number>.bin`

+
.例
[%collapsible]
=====
この例では、NX-OS バージョン 10.6(4)M を使用しています。

....
cs1# *install all nxos bootflash:/nxos64-cs.10.6.4.M.bin*

Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos64-cs.10.6.4.M.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos64-cs.10.6.4.M.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos64-cs.10.6.4.M.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  Bootable  Impact          Install-type  Reason
------  --------  --------------- ------------  ---------
  1     yes       Disruptive      Reset         Default upgrade is not hitless


Images will be upgraded according to following table:

Module   Image    Running-Version(pri:alt)            New-Version         Upg-Required
------- --------- ----------------------------------- ------------------- ------------
  1      nxos     10.4(2)(F)                          10.6(4)(M)          Yes
  1      bios     <current_version>                   <new_version>       No


Switch will be reloaded for disruptive upgrade.

Do you want to continue with the installation (y/n)? [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS

Finishing the upgrade, switch will reboot in 10 seconds.
....
=====
. スイッチの再起動後、NX-OS の新しいバージョンを確認します：
+
`show version`

+
.例
[%collapsible]
=====
....
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.6(4)(M) [Feature Release]
  Host NXOS: version 10.6(4)(M)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-cs.10.6.4.M.bin
  NXOS compile time:  05/30/2026 12:00:00 [06/14/2026 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9364D-GX2A Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs2
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Jun 5 15:55:08 2026
  Reason: Reset Requested by CLI command reload
  System version: 10.5(4)(M)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):
....
=====
. 新しいバージョンの EPLD が正常にロードされたことを確認します。
+
.例を表示
[%collapsible]
=====
この例では、EPLD バージョン 10.6(4)M を使用しています。

....
cs1# *show install epld status*

1) Module 2 upgraded on Mon May  4 09:17:08 2026 (631239  us)
EPLD Install Image: EPLD image file 10.6.4.M. built on Fri Apr 24 19:49:50 2026

Status: EPLD Upgrade was Successful

EPLD                             Curr Ver       Old Ver
-------------------------------------------------------
MI FPGA                         0x10014         0x1000b
IO FPGA                         0x10033         0x10006

2) Module 27 upgraded on Wed Apr  1 15:03:13 2026 (193093  us)
EPLD Install Image: EPLD image file 10.5.4.M. built on Mon Mar 16 03:28:47 2026

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
IO FPGA                         0x1002d         0x10020

3) Module 28 upgraded on Wed Apr  1 14:59:53 2026 (843907  us)
EPLD Install Image: EPLD image file 10.6.4.M. built on Mon Mar 16 03:28:47 2026

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
IO FPGA                         0x1002d         0x10020

4) Module 27 upgraded on Fri Mar 27 21:55:55 2026 (132290  us)
EPLD Install Image: EPLD image file 10.6.4.M. built on Fri Dec 12 11:15:18 2026

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

5) Module 27 upgraded on Fri Mar 27 21:50:16 2026 (  4899  us)
EPLD Install Image: EPLD image file 10.6.4.M. built on Fri Dec 12 11:15:18 2026

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

6) Module 27 upgraded on Fri Mar 27 21:44:36 2026 (775397  us)
EPLD Install Image: EPLD image file 10.6.4.M. built on Fri Dec 12 11:15:18 2026

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

7) Module 27 upgraded on Fri Mar 27 21:38:58 2026 (330582  us)
EPLD Install Image: EPLD image file 10.6.4.M. built on Fri Dec 12 11:15:18 2026

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

8) Module 27 upgraded on Fri Mar 27 21:33:19 2026 (112679  us)
EPLD Install Image: EPLD image file 10.6.4.M. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

9) Module 27 upgraded on Fri Mar 27 21:27:41 2026 (957182  us)
EPLD Install Image: EPLD image file 10.6.4.M. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

10) Module 27 upgraded on Fri Mar 27 21:22:03 2026 ( 90303  us)
EPLD Install Image: EPLD image file 10.6.4.M. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

11) Module 1 upgraded on Fri Mar 27 21:16:24 2026 (240369  us)
EPLD Install Image: EPLD image file 10.6.4.M. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
MI FPGA                         0x10014         0x1000b
IO FPGA                         0x10033         0x10006
....
=====


--
====
. ONTAP CLIを使用して、クラスタ上のすべてのポートの健全性を確認します。
+
.. *クラスターポート*
+
... クラスター内のすべてのノードでクラスター ポートが稼働しており正常であることを確認します。
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false
----
====
... クラスターからスイッチの健全性を確認します。
+
[source, cli]
----
network device-discovery show -protocol cdp
----
+
[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

node1-02/cdp
            e10a   cs1(FLMXXXXXXXX)         Ethernet1/16/3    N9K-C9364D-GX2A
            e10b   cs2(FDOXXXXXXXX)         Ethernet1/16/3    N9K-C9364D-GX2A
            e11a   cs1(FLMXXXXXXXX)         Ethernet1/16/4    N9K-C9364D-GX2A
            e11b   cs2(FDOXXXXXXXX)         Ethernet1/16/4    N9K-C9364D-GX2A
            e1a    cs1(FLMXXXXXXXX)         Ethernet1/16/1    N9K-C9364D-GX2A
            e1b    cs2(FDOXXXXXXXX)         Ethernet1/16/1    N9K-C9364D-GX2A
            .
            .
            .
            e7a    cs1(FLM284504N6)         Ethernet1/16/2    N9K-C9364D-GX2A
            e7b    cs2(FDO2846056X)         Ethernet1/16/2    N9K-C9364D-GX2A

node1-01/cdp
            e10a   cs1(FLMXXXXXXXX)         Ethernet1/16/3    N9K-C9364D-GX2A
            e10b   cs2(FDOXXXXXXXX)         Ethernet1/16/3    N9K-C9364D-GX2A
            e11a   cs1(FLMXXXXXXXX)         Ethernet1/16/4    N9K-C9364D-GX2A
            e11b   cs2(FDOXXXXXXXX)         Ethernet1/16/4    N9K-C9364D-GX2A
            e1a    cs1(FLMXXXXXXXX)         Ethernet1/16/1    N9K-C9364D-GX2A
            e1b    cs2(FDOXXXXXXXX)         Ethernet1/16/1    N9K-C9364D-GX2A
           .
           .
           .
            e7a    cs1(FLMXXXXXXXX)         Ethernet1/16/2    N9K-C9364D-GX2A
            e7b    cs2(FDOXXXXXXXX)         Ethernet1/16/2    N9K-C9364D-GX2A
.
.
.

cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs2(FDOXXXXXXXX)            cluster-network    10.228.137.233   N9K-C9364D-GX2A
     Serial Number: FDOXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP


cs1(FLMXXXXXXXX)             cluster-network   10.228.137.253   N9K-C9364D-GX2A
     Serial Number: FLMXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP
----
====


.. *HAポート*
+
... すべての HA ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
ha interconnect status show -node <node-name>
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====


.. *ストレージポート*
+
... すべてのストレージ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage port show -port-type ENET
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-02
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-03
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
node1-04
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
16 entries were displayed.
----
====


.. *ストレージシェルフポート*
+
... すべてのストレージ シェルフ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage shelf port show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.1
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false

16 entries were displayed.
----
====
... すべてのストレージ シェルフ ポートの接続ステータスを確認します。
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 CX9332D-cs1
1.1   1  connected       Ethernet1/15/1 CX9364D-cs1
1.1   2  connected       Ethernet1/17/2 CX9332D-cs1
1.1   3  connected       Ethernet1/15/2 CX9364D-cs1
1.1   4  connected       Ethernet1/17/3 CX9332D-cs1
1.1   5  connected       Ethernet1/15/3 CX9364D-cs1
1.1   6  connected       Ethernet1/17/4 CX9332D-cs1
1.1   7  connected       Ethernet1/15/4 CX9364D-cs1
1.1   8  connected       Ethernet1/19/1 CX9332D-cs1
1.1   9  connected       Ethernet1/17/1 CX9364D-cs1
1.1   10 connected       Ethernet1/19/2 CX9332D-cs1
1.1   11 connected       Ethernet1/17/2 CX9364D-cs1
1.1   12 connected       Ethernet1/19/3 CX9332D-cs1
1.1   13 connected       Ethernet1/17/3 CX9364D-cs1
1.1   14 connected       Ethernet1/19/4 CX9332D-cs1
1.1   15 connected       Ethernet1/17/4 CX9364D-cs1

16 entries were displayed.
----
====




. ONTAP CLI を使用して、クラスターが正常であることを確認します：
+
[source, cli]
----
cluster show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*


Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1-01             true    true          false
node1-02             true    true          false
node1-03             true    true          false
node1-04             true    true          true

4 entries were displayed.
----
====
. スイッチcs2にNX-OSおよびEPLDイメージをインストールするには、これらの手順を繰り返します。




[[step-3-complete-the-nx-os-upgrade]]
== ステップ3：NX-OSのアップグレードを完了する

ONTAP CLI を使用して、クラスタ LIF の自動復帰を再度有効にし、クラスタ LIF がホームポートに復帰したことを確認することで、NX-OS のアップグレードを完了します。

. クラスタLIFの自動リバートを再度有効にします。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. クラスタ LIF がホーム ポートに戻ったことを確認します。
+
[source, cli]
----
network interface show -role cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current     Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node        Port    Home
----------- --------------- ---------- ------------------ ----------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01    e7a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01    e7b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02    e7a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02    e7b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03    e7a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03    e7b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04    e7a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04    e7b     true
----
====
+
クラスタ LIF がホーム ポートに戻っていない場合は、ローカル ノードから手動で元に戻します。

+
[source, cli]
----
network interface revert -vserver Cluster -lif <lif-name>
----


.次の手順
スイッチの NX-OS をアップグレードしたら、link:configure-install-upgrade-rcf-overview-9364d.html["RCFの概要をインストールまたはアップグレードする"] から始めて RCF をアップグレードします。
