---
permalink: switch-cisco-9364d-gx2a/install-upgrade-rcf-overview-cluster.html 
sidebar: sidebar 
keywords: install, upgarde, cluster, switch, cisco 9364d-gx2a 
summary: Nexus 9364d-gx2a スイッチを初めてセットアップした後、RCF をインストールできます。この手順を使用して RCF をアップグレードすることもできます。 
---
= 参照構成ファイル（RCF）のインストールまたはアップグレードの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nexus 9364D-GX2A スイッチを初めてセットアップした後、リファレンス構成ファイル (RCF) をインストールします。スイッチに既存のバージョンの RCF ファイルがインストールされている場合は、RCF バージョンをアップグレードします。

ナレッジベースの記事を参照link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["リモート接続を維持しながらCiscoインターコネクトスイッチの設定をクリアする方法"^]RCF をインストールまたはアップグレードする際の詳細については、こちらをご覧ください。

.利用可能なRCF構成
* *クラスター-HA-ストレージ AFX* - すべてのポートは、AFX ノード クラスター、HA、ストレージ ポート、および NX224 ストレージ シェルフ ポートを普遍的にサポートする 4x100GbE ブレークアウト モードで構成されています。スイッチ間の 400GbE ISL。  (_Cluster-HA-Storage AFX RCF_vxx.x_)。


特定のポートと VLAN の使用法の詳細については、RCF のバナーと重要な注意事項のセクションを参照してください。見るlink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^]詳細についてはこちらをご覧ください。

.推奨ドキュメント
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ (NSS)"^]
+
サポートされているONTAPおよび RCF バージョンについては、 NetAppサポート サイトのスイッチ互換性表を参照してください。  RCF のコマンド構文と特定のバージョンの NX-OS の構文の間にはコマンド依存関係がある可能性があることに注意してください。

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-guides-list.html["Cisco Nexus 3=9000 シリーズ スイッチ"^]
+
Ciscoスイッチのアップグレードおよびダウングレード手順の完全なドキュメントについては、 Cisco Web サイトで入手可能な適切なソフトウェアおよびアップグレード ガイドを参照してください。



.例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 2 つのCiscoスイッチの名前は cs1 と cs2 です。
* ノード名は、node1-01、node1-02、node1-03、node1-04 です。
* クラスタ LIF 名は、node1-01_clus1、node1-01_clus2、node1-02_clus1、node1-02_clus2、node1-03_clus1、node1-03_clus2、node1-04_clus1、および node1-04_clus2 です。
* その `cluster1::*>`プロンプトはクラスターの名前を示します。


参照 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^]プラットフォーム上の正しいクラスター ポートを確認します。


NOTE: コマンド出力は、ONTAPのリリースによって異なる場合があります。

.使用されるコマンド
この手順では、ONTAPコマンドとCisco Nexus 9000シリーズ スイッチ コマンドの両方を使用する必要があります。特に明記されていないかぎり、ONTAPコマンドを使用します。

.次の手順
RCFのインストールまたはRCFのアップグレード手順を確認した後、link:install-rcf-software-9364d-cluster.html["RCFをインストールする"]またはlink:upgrade-rcf-software-9364d-cluster.html["RCFをアップグレードする"]必要に応じて。
