---
permalink: switch-cisco-9364d-gx2a/upgrade-rcf-software-9364d-cluster.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: この手順を使用して、RCF バージョンをアップグレードできます。 
---
= 参照構成ファイル (RCF) をアップグレードする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
運用スイッチに既存のバージョンの RCF ファイルがインストールされている場合は、RCF バージョンをアップグレードします。

.開始する前に
以下のものがあることを確認してください。

* スイッチ構成の現在のバックアップ。
* 完全に機能するクラスター (ログにエラーや同様の問題がない)。
* 現在のRCF。
* RCF バージョンを更新する場合は、必要なブート イメージを反映したブート構成が RCF 内に必要です。
+
現在のブート イメージを反映するようにブート設定を変更する必要がある場合は、あとでリブートしたときに正しいバージョンがインスタンス化されるように、RCFを再適用する前に変更する必要があります。




NOTE: この手順では、動作中のスイッチ間リンク (ISL) は必要ありません。これは、RCF バージョンの変更によって ISL 接続が一時的に影響を受ける可能性があるため、設計によるものです。クラスタ操作を中断せずに実行するために、次の手順では、ターゲット スイッチで手順を実行しながら、すべてのクラスタ LIF を動作中のパートナー スイッチに移行します。


CAUTION: 新しいスイッチ ソフトウェア バージョンと RCF をインストールする前に、スイッチの設定を消去し、基本設定を実行する必要があります。スイッチ設定を消去する前に、シリアル コンソールを使用してスイッチに接続するか、基本的な構成情報を保存しておく必要があります。



== ステップ1: アップグレードの準備

. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
ここで、_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

. 続行するかどうかを尋ねられたら *y* と入力して、権限レベルを「advanced」に変更します。
+
`set -privilege advanced`

+
advancedのプロンプト（*>）が表示されます。

. スイッチに接続されている各ノード上のクラスター ポートを表示します。
+
[source, cli]
----
network device-discovery show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
node1-01/cdp
            e10a   cs1(FLMXXXXXXXX)         Ethernet1/16/3    N9K-C9364D-GX2A
            e10b   cs1(FDOXXXXXXXX)         Ethernet1/13/3    N9K-C9364D-GX2A
            e11a   cs1(FLMXXXXXXXX)         Ethernet1/16/4    N9K-C9364D-GX2A
            e11b   cs1(FDOXXXXXXXX)         Ethernet1/13/4    N9K-C9364D-GX2A
            e1a    cs1(FLMXXXXXXXX)         Ethernet1/16/1    N9K-C9364D-GX2A
            e1b    cs1(FDOXXXXXXXX)         Ethernet1/13/1    N9K-C9364D-GX2A
            .
            .
            .
            e7a    cs1(FLMXXXXXXXX)         Ethernet1/16/2    N9K-C9364D-GX2A
            e7b    cs1(FDOXXXXXXXX)         Ethernet1/13/2    N9K-C9364D-GX2A
node1-01/lldp
            e10a   cs1 (c8:60:8f:xx:xx:xx)   Ethernet1/16/3    -
            e10b   cs2 (04:e3:87:xx:xx:xx)   Ethernet1/16/3    -
            e11a   cs1 (c8:60:8f:xx:xx:xx)   Ethernet1/16/4    -
            e11b   cs2 (04:e3:87:xx:xx:xx)   Ethernet1/16/4    -
            e1a    cs1 (c8:60:8f:xx:xx:xx)   Ethernet1/16/1    -
            e1b    cs2 (04:e3:87:xx:xx:xx)   Ethernet1/16/1    -
            .
            .
            .
            e7a    cs1 (c8:60:8f:xx:xx:xx)   Ethernet1/16/2    -
            e7b    cs2 (04:e3:87:xx:xx:xx)   Ethernet1/16/2    -
.
.
.
----
====
. 各ポートの管理および動作ステータスを確認します。
+
.. *クラスターポート*
+
... すべてのクラスター ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node:node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: node1-03

                                                                    Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false
cluster1::*>
----
====
... すべてのクラスタ インターフェイス (LIF) がホーム ポート上にあることを確認します。
+
[source, cli]
----
network interface show -role cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical          Status      Network           Current      Current Is
Vserver     Interface        Admin/Oper  Address/Mask      Node         Port    Home
----------- ---------------- ----------- ----------------- ------------ ------- ----
Cluster
            node1-01_clus1   up/up       169.254.3.4/23    node1-01     e7a     true
            node1-01_clus2   up/up       169.254.3.5/23    node1-01     e7b     true
            node1-02_clus1   up/up       169.254.3.8/23    node1-02     e7a     true
            node1-02_clus2   up/up       169.254.3.9/23    node1-02     e7b     true
            node1-03_clus1   up/up       169.254.1.3/23    node1-03     e7a     true
            node1-03_clus2   up/up       169.254.1.1/23    node1-03     e7b     true
            node1-04_clus1   up/up       169.254.1.6/23    node1-04     e7a     true
            node1-04_clus2   up/up       169.254.1.7/23    node1-04     e7b     true
8 entries were displayed.
----
====
... クラスターに両方のスイッチの情報が表示されることを確認します。
+
[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- -----
cs1(FDOXXXXXXXX)            cluster-network    10.228.137.233   N9K-C9364D-GX2A
     Serial Number: FDOXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP

cs2(FLMXXXXXXXX)            cluster-network    10.228.137.234   N9K-C9364D-GX2A
     Serial Number: FLMXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP
----
====


.. *HAポート*
+
... すべての HA ポートが正常な状態で稼働していることを確認します。
+
`ha interconnect status show -node <node-name>`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====


.. *ストレージポート*
+
... すべてのストレージ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage port show -port-type ENET
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-02
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-03
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
node1-04
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
16 entries were displayed.
----
====


.. *ストレージシェルフポート*
+
... すべてのストレージ シェルフ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage shelf port show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.1
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false

16 entries were displayed.
----
====
... すべてのストレージ シェルフ ポートの接続ステータスを確認します。
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 CX9332D-cs1
1.1   1  connected       Ethernet1/15/1 CX9364D-cs1
1.1   2  connected       Ethernet1/17/2 CX9332D-cs1
1.1   3  connected       Ethernet1/15/2 CX9364D-cs1
1.1   4  connected       Ethernet1/17/3 CX9332D-cs1
1.1   5  connected       Ethernet1/15/3 CX9364D-cs1
1.1   6  connected       Ethernet1/17/4 CX9332D-cs1
1.1   7  connected       Ethernet1/15/4 CX9364D-cs1
1.1   8  connected       Ethernet1/19/1 CX9332D-cs1
1.1   9  connected       Ethernet1/17/1 CX9364D-cs1
1.1   10 connected       Ethernet1/19/2 CX9332D-cs1
1.1   11 connected       Ethernet1/17/2 CX9364D-cs1
1.1   12 connected       Ethernet1/19/3 CX9332D-cs1
1.1   13 connected       Ethernet1/17/3 CX9364D-cs1
1.1   14 connected       Ethernet1/19/4 CX9332D-cs1
1.1   15 connected       Ethernet1/17/4 CX9364D-cs1

16 entries were displayed.
----
====




. クラスタ LIF の自動復帰を無効にします。
+
`network interface modify -vserver Cluster -lif * -auto-revert false`





== ステップ2: ポートを構成する

. スイッチ cs1 で、ノードのすべてのポートに接続されているポートをシャットダウンします。
+
[listing, subs="+quotes"]
----
cs1# *config*
cs1(config)# *interface e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7/1-4,e1/8/1-4*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/9/1-4,e1/10/1-4,e1/11/1-4,e1/12/1-4,e1/13/1-4,e1/14/1-4,e1/15/1-4,e1/16/1-4*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/17/1-4,e1/18/1-4,e1/19/1-4,e1/20/1-4,e1/21/1-4,e1/22/1-4,e1/23/1-4,e1/24/1-4*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/25/1-4,e1/26/1-4,e1/27/1-4,e1/28/1-4,e1/29/1-4,e1/30/1-4,e1/31/1-4,e1/32/1-4*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/33/1-4,e1/34/1-4,e1/35/1-4,e1/36/1-4,e1/37/1-4,e1/38/1-4,e1/39/1-4,e1/40/1-4*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/41/1-4,e1/42/1-4,e1/43/1-4,e1/44/1-4,e1/35/1-4,e1/46/1-4,e1/47/1-4,e1/48/1-4*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/49/1-4,e1/50/1-4,e1/51/1-4,e1/52/1-4,e1/53/1-4,e1/54/1-4,e1/55/1-4,e1/56/1-4*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/57/1-4,e1/58/1-4,e1/59/1-4,e1/60/1-4,e1/61/1-4,e1/62/1-4*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----
+

CAUTION: ネットワーク接続の問題を回避するために、接続されているすべてのポートをシャットダウンしてください。ナレッジベースの記事を参照 https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["スイッチ OS のアップグレード中にクラスタ LIF を移行するとノードがクォーラム外になる"^]詳細については、こちらをご覧ください。

. クラスタ LIF がクラスタ スイッチ cs1 でホストされているポートにフェイルオーバーされたことを確認します。数秒かかる場合があります。
+
[source, cli]
----
network interface show -role cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical           Status     Network            Current       Current Is
Vserver     Interface         Admin/Oper Address/Mask       Node          Port    Home
----------- ----------------- ---------- ------------------ ------------- ------- ----
Cluster
            node1-01_clus1    up/up      169.254.36.44/16   node1-01      e7a     true
            node1-01_clus2    up/up      169.254.7.5/16     node1-01      e7b     true
            node1-02_clus1    up/up      169.254.197.206/16 node1-02      e7a     true
            node1-02_clus2    up/up      169.254.195.186/16 node1-02      e7b     true
            node1-03_clus1    up/up      169.254.192.49/16  node1-03      e7a     true
            node1-03_clus2    up/up      169.254.182.76/16  node1-03      e7b     true
            node1-04_clus1    up/up      169.254.59.49/16   node1-04      e7a     true
            node1-04_clus2    up/up      169.254.62.244/16  node1-04      e7b     true
8 entries were displayed.
----
====
. クラスタが正常に動作していることを確認します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health  Eligibility   Epsilon
----------------- ------- ------------  -------
node1-01          true    true          false
node1-02          true    true          false
node1-03          true    true          true
node1-04          true    true          false
4 entries were displayed.
----
====
. まだ行っていない場合は、次のコマンドの出力をテキスト ファイルにコピーして、現在のスイッチ構成のコピーを保存します。
+
`show running-config`

+
.. 現在のカスタム追加を記録します `running-config`使用中の RCF ファイル (組織の SNMP 構成など)。
.. NX-OS 10.2以降では、 `show diff running-config`ブートフラッシュに保存されている RCF ファイルと比較するコマンド。それ以外の場合は、サードパーティの diff/comparative ツールを使用します。


. 基本的な設定の詳細を `write_erase.cfg`ブートフラッシュ上のファイル。
+
[NOTE]
====
必ず以下を設定してください。

** ユーザ名とパスワード
** 管理IPアドレス
** デフォルト ゲートウェイ
** スイッチ名


====
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1536" >> bootflash:write_erase.cfg`

+
ナレッジベースの記事を参照link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["リモート接続を維持しながらCiscoインターコネクトスイッチの設定をクリアする方法"^]詳細については、こちらをご覧ください。

. 確認するには `write_erase.cfg`ファイルは期待どおりに入力されます。
+
`*show file bootflash:write_erase.cfg*`

. 発行する `write erase`現在保存されている構成を消去するコマンド:
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. 以前に保存した基本設定をスタートアップ設定にコピーします。
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. スイッチをリブートします。
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 管理 IP アドレスに再度アクセスできるようになったら、SSH 経由でスイッチにログインします。
+
SSH キーに関連するホスト ファイル エントリを更新する必要がある場合があります。

. FTP、TFTP、SFTP、SCPのいずれかの転送プロトコルを使用して、スイッチcs1のブートフラッシュにRCFをコピーします。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 シリーズ NX-OS コマンド リファレンス"^]ガイド。

+
.例を表示
[%collapsible]
====
この例では、TFTPを使用してスイッチcs1のブートフラッシュにRCFをコピーしています。

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9364D-GX2A-RCF-v10.0-Shared.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 前の手順でブートフラッシュにダウンロードしたRCFを適用します。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 シリーズ NX-OS コマンド リファレンス"^]ガイド。

+
この例ではRCFファイルを示します `NX9364D-GX2A-RCF-v10.0-Shared.txt`スイッチ cs1 にインストールされます:

+
[listing, subs="+quotes"]
----
cs1# *copy NX9364D-GX2A-RCF-v10.0-Shared.txt running-config echo-commands*
----
+

CAUTION: RCF の *インストール ノート*、*重要ノート*、および *バナー* セクションを必ずよくお読みください。スイッチが正しく動作するように設定するためには、出力を確認し、その指示に従う必要があります。

. RCF ファイルが正しい新しいバージョンであることを確認します。
+
`show running-config`

+
次の情報が正しいことを確認してください。

+
** RCFのバナー
** ノードとポートの設定
** カスタマイズ
+
出力内容はサイトの構成によって異なります。ポートの設定を確認し、インストールしたRCFに固有の変更がないかリリース ノートを参照してください。



. 以前のカスタマイズをスイッチ構成に再適用します。
. RCF バージョン、カスタム追加、およびスイッチ設定が正しいことを確認したら、running-config ファイルを startup-config ファイルにコピーします。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 シリーズ NX-OS コマンド リファレンス"^]ガイド。

+
`cs1# copy running-config startup-config`

+
`[########################################] 100% Copy complete`

. スイッチcs1をリブートします。スイッチの再起動中にノードで報告される「`cluster switch health monitor`」アラートと「`cluster ports down`」イベントは無視できます。
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. クラスター上のポートの正常性を確認します。
+
.. *クラスターポート*
+
... クラスター内のすべてのノードでクラスター ポートが稼働しており正常であることを確認します。
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false
8 entries were displayed.
----
====
... クラスターからスイッチの健全性を確認します。
+
[source, cli]
----
network device-discovery show -protocol cdp
----
+
[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
node1-01/cdp
            e10a   cs1(FLMXXXXXXXX)          Ethernet1/16/3    N9K-C9364D-GX2A
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/13/3    N9K-C9364D-GX2A
            e11a   cs1(FLMXXXXXXXX)          Ethernet1/16/4    N9K-C9364D-GX2A
            e11b   cs2(FDOXXXXXXXX)          Ethernet1/13/4    N9K-C9364D-GX2A
            e1a    cs1(FLMXXXXXXXX)          Ethernet1/16/1    N9K-C9364D-GX2A
            e1b    cs2(FLMXXXXXXXX)          Ethernet1/13/1    N9K-C9364D-GX2A
            .
            .
            .
            e7a    cs1(FLMXXXXXXXX)          Ethernet1/16/2    N9K-C9364D-GX2A
            e7b    cs2(FDOXXXXXXXX)          Ethernet1/13/2    N9K-C9364D-GX2A
node1-02/cdp
.
.
.

cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- -----
cs2(FDOXXXXXXXX)            cluster-network    10.228.137.233   N9K-C9364D-GX2A
     Serial Number: FDOXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP

cs1(FLMXXXXXXXX)            cluster-network    10.228.137.234   N9K-C9364D-GX2A
     Serial Number: FLMXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP

2 entries were displayed.
----
====


.. *HAポート*
+
... すべての HA ポートが正常な状態で稼働していることを確認します。
+
`ha interconnect status show -node <node-name>`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====


.. *ストレージポート*
+
... すべてのストレージ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage port show -port-type ENET
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-02
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-03
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
node1-04
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
16 entries were displayed.
----
====


.. *ストレージシェルフポート*
+
... すべてのストレージ シェルフ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage shelf port show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.1
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false

16 entries were displayed.
----
====
... すべてのストレージ シェルフ ポートの接続ステータスを確認します。
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 CX9332D-cs1
1.1   1  connected       Ethernet1/15/1 CX9364D-cs1
1.1   2  connected       Ethernet1/17/2 CX9332D-cs1
1.1   3  connected       Ethernet1/15/2 CX9364D-cs1
1.1   4  connected       Ethernet1/17/3 CX9332D-cs1
1.1   5  connected       Ethernet1/15/3 CX9364D-cs1
1.1   6  connected       Ethernet1/17/4 CX9332D-cs1
1.1   7  connected       Ethernet1/15/4 CX9364D-cs1
1.1   8  connected       Ethernet1/19/1 CX9332D-cs1
1.1   9  connected       Ethernet1/17/1 CX9364D-cs1
1.1   10 connected       Ethernet1/19/2 CX9332D-cs1
1.1   11 connected       Ethernet1/17/2 CX9364D-cs1
1.1   12 connected       Ethernet1/19/3 CX9332D-cs1
1.1   13 connected       Ethernet1/17/3 CX9364D-cs1
1.1   14 connected       Ethernet1/19/4 CX9332D-cs1
1.1   15 connected       Ethernet1/17/4 CX9364D-cs1

16 entries were displayed.
----
====




. クラスタが正常に動作していることを確認します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health   Eligibility   Epsilon
----------------- -------- ------------- -------
node1-01          true     true          false
node1-02          true     true          false
node1-03          true     true          true
node1-04          true     true          false
4 entries were displayed.
----
====
. スイッチ cs2 で手順 4 ～ 18 を繰り返します。
. クラスタ LIF で自動復帰を有効にします。
+
`network interface modify -vserver Cluster -lif  * -auto-revert True`





== ステップ3: クラスターネットワーク構成とクラスターの健全性を確認する

. クラスタ ポートに接続されているスイッチ ポートが稼働していることを確認します。
+
`show interface brief`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
.
.
Eth1/9/3        1       eth  trunk  up      none                     100G(D) --
Eth1/9/4        1       eth  trunk  up      none                     100G(D) --
Eth1/15/1       1       eth  trunk  up      none                     100G(D) --
Eth1/15/2       1       eth  trunk  up      none                     100G(D) --
Eth1/15/3       1       eth  trunk  up      none                     100G(D) --
Eth1/15/4       1       eth  trunk  up      none                     100G(D) --
Eth1/16/1       1       eth  trunk  up      none                     100G(D) --
Eth1/16/2       1       eth  trunk  up      none                     100G(D) --
Eth1/16/3       1       eth  trunk  up      none                     100G(D) --
Eth1/16/4       1       eth  trunk  up      none                     100G(D) --
Eth1/17/1       1       eth  trunk  up      none                     100G(D) --
Eth1/17/2       1       eth  trunk  up      none                     100G(D) --
Eth1/17/3       1       eth  trunk  up      none                     100G(D) --
Eth1/17/4       1       eth  trunk  up      none                     100G(D) --
.
.
.
----
====
. 期待されるノードがまだ接続されていることを確認します。
+
`show cdp neighbors`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2(FDOXXXXXXXX)    Eth1/63        179    R S I s   N9K-C9332D-GX2B   Eth1/31
cs2(FDOXXXXXXXX)    Eth1/64        179    R S I s   N9K-C9332D-GX2B   Eth1/32
node1-01            Eth1/4/1       123    H         AFX-1K            e1a
node1-01            Eth1/4/2       123    H         AFX-1K            e7a
node1-01            Eth1/4/3       123    H         AFX-1K            e10a
node1-01            Eth1/4/4       123    H         AFX-1K            e11a
node1-02            Eth1/9/1       138    H         AFX-1K            e1a
node1-02            Eth1/9/2       138    H         AFX-1K            e7a
node1-02            Eth1/9/3       138    H         AFX-1K            e10a
node1-02            Eth1/9/4       138    H         AFX-1K            e11a
node1-03            Eth1/15/1      138    H         AFX-1K            e1a
node1-03            Eth1/15/2      138    H         AFX-1K            e7a
node1-03            Eth1/15/3      138    H         AFX-1K            e10a
node1-03            Eth1/15/4      138    H         AFX-1K            e11a
node1-04            Eth1/16/1      173    H         AFX-1K            e1a
node1-04            Eth1/16/2      173    H         AFX-1K            e7a
node1-04            Eth1/16/3      173    H         AFX-1K            e10a
node1-04            Eth1/16/4      173    H         AFX-1K            e11a

Total entries displayed: 18
----
====
. 次のコマンドを使用して、クラスタ ノードが正しいクラスタ VLAN 内にあることを確認します。
+
`show vlan brief`

+
`show interface trunk`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show vlan brief*

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po1, Po999, Eth1/63, Eth1/64
                                                Eth1/65, Eth1/66, Eth1/1/1
                                                Eth1/1/2, Eth1/1/3, Eth1/1/4
                                                Eth1/2/1, Eth1/2/2, Eth1/2/3
                                                Eth1/2/4, Eth1/3/1, Eth1/3/2
                                                Eth1/3/3, Eth1/3/4, Eth1/4/1
                                                Eth1/4/2, Eth1/4/3, Eth1/4/4
                                                Eth1/5/1, Eth1/5/2, Eth1/5/3
                                                Eth1/5/4, Eth1/6/1, Eth1/6/2
                                                Eth1/6/3, Eth1/6/4, Eth1/7/1
                                                Eth1/7/2, Eth1/7/3, Eth1/7/4
                                                Eth1/8/1, Eth1/8/2, Eth1/8/3
                                                Eth1/8/4, Eth1/9/1, Eth1/9/2
                                                Eth1/9/3, Eth1/9/4, Eth1/10/1
                                                Eth1/10/2, Eth1/10/3, Eth1/10/4
                                                Eth1/11/1, Eth1/11/2, Eth1/11/3
                                                Eth1/11/4, Eth1/12/1, Eth1/12/2
                                                Eth1/12/3, Eth1/12/4, Eth1/13/1
                                                Eth1/13/2, Eth1/13/3, Eth1/13/4
                                                Eth1/14/1, Eth1/14/2, Eth1/14/3
                                                Eth1/14/4, Eth1/15/1, Eth1/15/2
                                                Eth1/15/3, Eth1/15/4, Eth1/16/1
                                                Eth1/16/2, Eth1/16/3, Eth1/16/4
                                                Eth1/17/1, Eth1/17/2, Eth1/17/3
                                                Eth1/17/4, Eth1/18/1, Eth1/18/2
                                                Eth1/18/3, Eth1/18/4, Eth1/19/1
                                                Eth1/19/2, Eth1/19/3, Eth1/19/4
                                                Eth1/20/1, Eth1/20/2, Eth1/20/3
                                                Eth1/20/4, Eth1/21/1, Eth1/21/2
                                                Eth1/21/3, Eth1/21/4, Eth1/22/1
                                                Eth1/22/2, Eth1/22/3, Eth1/22/4
                                                Eth1/23/1, Eth1/23/2, Eth1/23/3
                                                Eth1/23/4, Eth1/24/1, Eth1/24/2
                                                Eth1/24/3, Eth1/24/4, Eth1/25/1
                                                Eth1/25/2, Eth1/25/3, Eth1/25/4
                                                Eth1/26/1, Eth1/26/2, Eth1/26/3
                                                Eth1/26/4, Eth1/27/1, Eth1/27/2
                                                Eth1/27/3, Eth1/27/4, Eth1/28/1
                                                Eth1/28/2, Eth1/28/3, Eth1/28/4
                                                Eth1/29/1, Eth1/29/2, Eth1/29/3
                                                Eth1/29/4, Eth1/30/1, Eth1/30/2
                                                Eth1/30/3, Eth1/30/4, Eth1/31/1
                                                Eth1/31/2, Eth1/31/3, Eth1/31/4
                                                Eth1/32/1, Eth1/32/2, Eth1/32/3
                                                Eth1/32/4, Eth1/33/1, Eth1/33/2
                                                Eth1/33/3, Eth1/33/4, Eth1/34/1
                                                Eth1/34/2, Eth1/34/3, Eth1/34/4
                                                Eth1/35/1, Eth1/35/2, Eth1/35/3
                                                Eth1/35/4, Eth1/36/1, Eth1/36/2
                                                Eth1/36/3, Eth1/36/4, Eth1/37/1
                                                Eth1/37/2, Eth1/37/3, Eth1/37/4
                                                Eth1/38/1, Eth1/38/2, Eth1/38/3
                                                Eth1/38/4, Eth1/39/1, Eth1/39/2
                                                Eth1/39/3, Eth1/39/4, Eth1/40/1
                                                Eth1/40/2, Eth1/40/3, Eth1/40/4
                                                Eth1/41/1, Eth1/41/2, Eth1/41/3
                                                Eth1/41/4, Eth1/42/1, Eth1/42/2
                                                Eth1/42/3, Eth1/42/4, Eth1/43/1
                                                Eth1/43/2, Eth1/43/3, Eth1/43/4
                                                Eth1/44/1, Eth1/44/2, Eth1/44/3
                                                Eth1/44/4, Eth1/45/1, Eth1/45/2
                                                Eth1/45/3, Eth1/45/4, Eth1/46/1
                                                Eth1/46/2, Eth1/46/3, Eth1/46/4
                                                Eth1/47/1, Eth1/47/2, Eth1/47/3
                                                Eth1/47/4, Eth1/48/1, Eth1/48/2
                                                Eth1/48/3, Eth1/48/4, Eth1/49/1
                                                Eth1/49/2, Eth1/49/3, Eth1/49/4
                                                Eth1/50/1, Eth1/50/2, Eth1/50/3
                                                Eth1/50/4, Eth1/51/1, Eth1/51/2
                                                Eth1/51/3, Eth1/51/4, Eth1/52/1
                                                Eth1/52/2, Eth1/52/3, Eth1/52/4
                                                Eth1/53/1, Eth1/53/2, Eth1/53/3
                                                Eth1/53/4, Eth1/54/1, Eth1/54/2
                                                Eth1/54/3, Eth1/54/4, Eth1/55/1
                                                Eth1/55/2, Eth1/55/3, Eth1/55/4
                                                Eth1/56/1, Eth1/56/2, Eth1/56/3
                                                Eth1/56/4, Eth1/57/1, Eth1/57/2
                                                Eth1/57/3, Eth1/57/4, Eth1/58/1
                                                Eth1/58/2, Eth1/58/3, Eth1/58/4
                                                Eth1/59/1, Eth1/59/2, Eth1/59/3
                                                Eth1/59/4, Eth1/60/1, Eth1/60/2
                                                Eth1/60/3, Eth1/60/4, Eth1/61/1
                                                Eth1/61/2, Eth1/61/3, Eth1/61/4
                                                Eth1/62/1, Eth1/62/2, Eth1/62/3
                                                Eth1/62/4
17   VLAN0017                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
                                                Eth1/31/1, Eth1/31/2, Eth1/31/3
                                                Eth1/31/4, Eth1/32/1, Eth1/32/2
                                                Eth1/32/3, Eth1/32/4, Eth1/33/1
                                                Eth1/33/2, Eth1/33/3, Eth1/33/4
                                                Eth1/34/1, Eth1/34/2, Eth1/34/3
                                                Eth1/34/4, Eth1/35/1, Eth1/35/2
                                                Eth1/35/3, Eth1/35/4, Eth1/36/1
                                                Eth1/36/2, Eth1/36/3, Eth1/36/4
                                                Eth1/37/1, Eth1/37/2, Eth1/37/3
                                                Eth1/37/4, Eth1/38/1, Eth1/38/2
                                                Eth1/38/3, Eth1/38/4, Eth1/39/1
                                                Eth1/39/2, Eth1/39/3, Eth1/39/4
                                                Eth1/40/1, Eth1/40/2, Eth1/40/3
                                                Eth1/40/4, Eth1/41/1, Eth1/41/2
                                                Eth1/41/3, Eth1/41/4, Eth1/42/1
                                                Eth1/42/2, Eth1/42/3, Eth1/42/4
                                                Eth1/43/1, Eth1/43/2, Eth1/43/3
                                                Eth1/43/4, Eth1/44/1, Eth1/44/2
                                                Eth1/44/3, Eth1/44/4, Eth1/45/1
                                                Eth1/45/2, Eth1/45/3, Eth1/45/4
                                                Eth1/46/1, Eth1/46/2, Eth1/46/3
                                                Eth1/46/4, Eth1/47/1, Eth1/47/2
                                                Eth1/47/3, Eth1/47/4, Eth1/48/1
                                                Eth1/48/2, Eth1/48/3, Eth1/48/4
                                                Eth1/49/1, Eth1/49/2, Eth1/49/3
                                                Eth1/49/4, Eth1/50/1, Eth1/50/2
                                                Eth1/50/3, Eth1/50/4, Eth1/51/1
                                                Eth1/51/2, Eth1/51/3, Eth1/51/4
                                                Eth1/52/1, Eth1/52/2, Eth1/52/3
                                                Eth1/52/4, Eth1/53/1, Eth1/53/2
                                                Eth1/53/3, Eth1/53/4, Eth1/54/1
                                                Eth1/54/2, Eth1/54/3, Eth1/54/4
                                                Eth1/55/1, Eth1/55/2, Eth1/55/3
                                                Eth1/55/4, Eth1/56/1, Eth1/56/2
                                                Eth1/56/3, Eth1/56/4, Eth1/57/1
                                                Eth1/57/2, Eth1/57/3, Eth1/57/4
                                                Eth1/58/1, Eth1/58/2, Eth1/58/3
                                                Eth1/58/4, Eth1/59/1, Eth1/59/2
                                                Eth1/59/3, Eth1/59/4, Eth1/60/1
                                                Eth1/60/2, Eth1/60/3, Eth1/60/4
                                                Eth1/61/1, Eth1/61/2, Eth1/61/3
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4
18   VLAN0018                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
                                                Eth1/31/1, Eth1/31/2, Eth1/31/3
                                                Eth1/31/4, Eth1/32/1, Eth1/32/2
                                                Eth1/32/3, Eth1/32/4, Eth1/33/1
                                                Eth1/33/2, Eth1/33/3, Eth1/33/4
                                                Eth1/34/1, Eth1/34/2, Eth1/34/3
                                                Eth1/34/4, Eth1/35/1, Eth1/35/2
                                                Eth1/35/3, Eth1/35/4, Eth1/36/1
                                                Eth1/36/2, Eth1/36/3, Eth1/36/4
                                                Eth1/37/1, Eth1/37/2, Eth1/37/3
                                                Eth1/37/4, Eth1/38/1, Eth1/38/2
                                                Eth1/38/3, Eth1/38/4, Eth1/39/1
                                                Eth1/39/2, Eth1/39/3, Eth1/39/4
                                                Eth1/40/1, Eth1/40/2, Eth1/40/3
                                                Eth1/40/4, Eth1/41/1, Eth1/41/2
                                                Eth1/41/3, Eth1/41/4, Eth1/42/1
                                                Eth1/42/2, Eth1/42/3, Eth1/42/4
                                                Eth1/43/1, Eth1/43/2, Eth1/43/3
                                                Eth1/43/4, Eth1/44/1, Eth1/44/2
                                                Eth1/44/3, Eth1/44/4, Eth1/45/1
                                                Eth1/45/2, Eth1/45/3, Eth1/45/4
                                                Eth1/46/1, Eth1/46/2, Eth1/46/3
                                                Eth1/46/4, Eth1/47/1, Eth1/47/2
                                                Eth1/47/3, Eth1/47/4, Eth1/48/1
                                                Eth1/48/2, Eth1/48/3, Eth1/48/4
                                                Eth1/49/1, Eth1/49/2, Eth1/49/3
                                                Eth1/49/4, Eth1/50/1, Eth1/50/2
                                                Eth1/50/3, Eth1/50/4, Eth1/51/1
                                                Eth1/51/2, Eth1/51/3, Eth1/51/4
                                                Eth1/52/1, Eth1/52/2, Eth1/52/3
                                                Eth1/52/4, Eth1/53/1, Eth1/53/2
                                                Eth1/53/3, Eth1/53/4, Eth1/54/1
                                                Eth1/54/2, Eth1/54/3, Eth1/54/4
                                                Eth1/55/1, Eth1/55/2, Eth1/55/3
                                                Eth1/55/4, Eth1/56/1, Eth1/56/2
                                                Eth1/56/3, Eth1/56/4, Eth1/57/1
                                                Eth1/57/2, Eth1/57/3, Eth1/57/4
                                                Eth1/58/1, Eth1/58/2, Eth1/58/3
                                                Eth1/58/4, Eth1/59/1, Eth1/59/2
                                                Eth1/59/3, Eth1/59/4, Eth1/60/1
                                                Eth1/60/2, Eth1/60/3, Eth1/60/4
                                                Eth1/61/1, Eth1/61/2, Eth1/61/3
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4
30   VLAN0030                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
                                                Eth1/31/1, Eth1/31/2, Eth1/31/3
                                                Eth1/31/4, Eth1/32/1, Eth1/32/2
                                                Eth1/32/3, Eth1/32/4, Eth1/33/1
                                                Eth1/33/2, Eth1/33/3, Eth1/33/4
                                                Eth1/34/1, Eth1/34/2, Eth1/34/3
                                                Eth1/34/4, Eth1/35/1, Eth1/35/2
                                                Eth1/35/3, Eth1/35/4, Eth1/36/1
                                                Eth1/36/2, Eth1/36/3, Eth1/36/4
                                                Eth1/37/1, Eth1/37/2, Eth1/37/3
                                                Eth1/37/4, Eth1/38/1, Eth1/38/2
                                                Eth1/38/3, Eth1/38/4, Eth1/39/1
                                                Eth1/39/2, Eth1/39/3, Eth1/39/4
                                                Eth1/40/1, Eth1/40/2, Eth1/40/3
                                                Eth1/40/4, Eth1/41/1, Eth1/41/2
                                                Eth1/41/3, Eth1/41/4, Eth1/42/1
                                                Eth1/42/2, Eth1/42/3, Eth1/42/4
                                                Eth1/43/1, Eth1/43/2, Eth1/43/3
                                                Eth1/43/4, Eth1/44/1, Eth1/44/2
                                                Eth1/44/3, Eth1/44/4, Eth1/45/1
                                                Eth1/45/2, Eth1/45/3, Eth1/45/4
                                                Eth1/46/1, Eth1/46/2, Eth1/46/3
                                                Eth1/46/4, Eth1/47/1, Eth1/47/2
                                                Eth1/47/3, Eth1/47/4, Eth1/48/1
                                                Eth1/48/2, Eth1/48/3, Eth1/48/4
                                                Eth1/49/1, Eth1/49/2, Eth1/49/3
                                                Eth1/49/4, Eth1/50/1, Eth1/50/2
                                                Eth1/50/3, Eth1/50/4, Eth1/51/1
                                                Eth1/51/2, Eth1/51/3, Eth1/51/4
                                                Eth1/52/1, Eth1/52/2, Eth1/52/3
                                                Eth1/52/4, Eth1/53/1, Eth1/53/2
                                                Eth1/53/3, Eth1/53/4, Eth1/54/1
                                                Eth1/54/2, Eth1/54/3, Eth1/54/4
                                                Eth1/55/1, Eth1/55/2, Eth1/55/3
                                                Eth1/55/4, Eth1/56/1, Eth1/56/2
                                                Eth1/56/3, Eth1/56/4, Eth1/57/1
                                                Eth1/57/2, Eth1/57/3, Eth1/57/4
                                                Eth1/58/1, Eth1/58/2, Eth1/58/3
                                                Eth1/58/4, Eth1/59/1, Eth1/59/2
                                                Eth1/59/3, Eth1/59/4, Eth1/60/1
                                                Eth1/60/2, Eth1/60/3, Eth1/60/4
                                                Eth1/61/1, Eth1/61/2, Eth1/61/3
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4
40   VLAN0040                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
                                                Eth1/31/1, Eth1/31/2, Eth1/31/3
                                                Eth1/31/4, Eth1/32/1, Eth1/32/2
                                                Eth1/32/3, Eth1/32/4, Eth1/33/1
                                                Eth1/33/2, Eth1/33/3, Eth1/33/4
                                                Eth1/34/1, Eth1/34/2, Eth1/34/3
                                                Eth1/34/4, Eth1/35/1, Eth1/35/2
                                                Eth1/35/3, Eth1/35/4, Eth1/36/1
                                                Eth1/36/2, Eth1/36/3, Eth1/36/4
                                                Eth1/37/1, Eth1/37/2, Eth1/37/3
                                                Eth1/37/4, Eth1/38/1, Eth1/38/2
                                                Eth1/38/3, Eth1/38/4, Eth1/39/1
                                                Eth1/39/2, Eth1/39/3, Eth1/39/4
                                                Eth1/40/1, Eth1/40/2, Eth1/40/3
                                                Eth1/40/4, Eth1/41/1, Eth1/41/2
                                                Eth1/41/3, Eth1/41/4, Eth1/42/1
                                                Eth1/42/2, Eth1/42/3, Eth1/42/4
                                                Eth1/43/1, Eth1/43/2, Eth1/43/3
                                                Eth1/43/4, Eth1/44/1, Eth1/44/2
                                                Eth1/44/3, Eth1/44/4, Eth1/45/1
                                                Eth1/45/2, Eth1/45/3, Eth1/45/4
                                                Eth1/46/1, Eth1/46/2, Eth1/46/3
                                                Eth1/46/4, Eth1/47/1, Eth1/47/2
                                                Eth1/47/3, Eth1/47/4, Eth1/48/1
                                                Eth1/48/2, Eth1/48/3, Eth1/48/4
                                                Eth1/49/1, Eth1/49/2, Eth1/49/3
                                                Eth1/49/4, Eth1/50/1, Eth1/50/2
                                                Eth1/50/3, Eth1/50/4, Eth1/51/1
                                                Eth1/51/2, Eth1/51/3, Eth1/51/4
                                                Eth1/52/1, Eth1/52/2, Eth1/52/3
                                                Eth1/52/4, Eth1/53/1, Eth1/53/2
                                                Eth1/53/3, Eth1/53/4, Eth1/54/1
                                                Eth1/54/2, Eth1/54/3, Eth1/54/4
                                                Eth1/55/1, Eth1/55/2, Eth1/55/3
                                                Eth1/55/4, Eth1/56/1, Eth1/56/2
                                                Eth1/56/3, Eth1/56/4, Eth1/57/1
                                                Eth1/57/2, Eth1/57/3, Eth1/57/4
                                                Eth1/58/1, Eth1/58/2, Eth1/58/3
                                                Eth1/58/4, Eth1/59/1, Eth1/59/2
                                                Eth1/59/3, Eth1/59/4, Eth1/60/1
                                                Eth1/60/2, Eth1/60/3, Eth1/60/4
                                                Eth1/61/1, Eth1/61/2, Eth1/61/3
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4

cs1# *show interface trunk*

-----------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
-----------------------------------------------------
Eth1/1/1      1       trunking      --
Eth1/1/2      1       trunking      --
Eth1/1/3      1       trunking      --
Eth1/1/4      1       trunking      --
Eth1/2/1      1       trunking      --
Eth1/2/2      1       trunking      --
Eth1/2/3      1       trunking      --
Eth1/2/4      1       trunking      --
.
.
.
Eth1/62/2     none
Eth1/62/3     none
Eth1/62/4     none
Eth1/63       none
Eth1/64       none
Po1           1
----
====
+

NOTE: 特定のポートと VLAN の使用法の詳細については、RCF のバナーと重要な注意事項のセクションを参照してください。

. cs1 と cs2 間の ISL が機能していることを確認します。
+
[source, cli]
----
show port-channel summary
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/63(P)   Eth1/64(P)
999   Po999(SD)   Eth      NONE      --
cs1#
----
====
. クラスタ LIF がホーム ポートに戻ったことを確認します。
+
[source, cli]
----
network interface show -role cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network            Current      Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node         Port    Home
----------- ------------------ ---------- ------------------ ------------ ------- ----
Cluster
            node1-01_clus1     up/up      169.254.36.44/16   node1-01     e7a     true
            node1-01_clus2     up/up      169.254.7.5/16     node1-01     e7b     true
            node1-02_clus1     up/up      169.254.197.206/16 node1-02     e7a     true
            node1-02_clus2     up/up      169.254.195.186/16 node1-02     e7b     true
            node1-03_clus1     up/up      169.254.192.49/16  node1-03     e7a     true
            node1-03_clus2     up/up      169.254.182.76/16  node1-03     e7b     true
            node1-04_clus1     up/up      169.254.59.49/16   node1-04     e7a     true
            node1-04_clus2     up/up      169.254.62.244/16  node1-04     e7b     true

8 entries were displayed.
----
====
+
クラスタ LIF がホーム ポートに戻っていない場合は、ローカル ノードから手動で元に戻します。

+
`network interface revert -vserver vserver_name -lif <lif-name>`

. クラスタが正常に動作していることを確認します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health  Eligibility   Epsilon
----------------- ------- ------------- -------
node1-01          true    true          false
node1-02          true    true          false
node1-03          true    true          true
node1-04          true    true          false
----
====
. リモート クラスタ インターフェイスの接続を確認します。
+
.. 使用することができます `network interface check cluster-connectivity show`クラスター接続のアクセシビリティ チェックの詳細を表示するコマンド:
+
[source, cli]
----
network interface check cluster-connectivity show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*

                                  Source           Destination     Packet
Node   Date                       LIF              LIF             Loss
------ -------------------------- ---------------- --------------- -----------
node1-01
       6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1   none
       6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus1   none


node1-02
       6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1   none
       6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2   none
.
.
.
----
====
.. あるいは、 `cluster ping-cluster -node <node-name>`接続を確認するコマンド:
+
`cluster ping-cluster -node <node-name>`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node1-04
Getting addresses from network interface table...
Cluster node1-01_clus1 169.254.36.44 node1-01 e7a
Cluster node1-01_clus2 169.254.7.5   node1-01 e7b
Cluster node1-02_clus1 169.254.197.206 node1-02 e7a
Cluster node1-02_clus2 169.254.195.186 node1-02 e7b
Cluster node1-03_clus1 169.254.192.49 node1-03 e7a
Cluster node1-03_clus2 169.254.182.76 node1-03 e7b
Cluster node1-04_clus1 169.254.59.49 node1-04 e7a
Cluster node1-04_clus2 169.254.62.244 node1-04 e7b
Local = 169.254.59.49 169.254.62.244
Remote = 169.254.36.44 169.254.7.5 169.254.197.206 169.254.195.186 169.254.192.49 169.254.182.76
Cluster Vserver Id = 4294967293
Ping status:
............
Basic connectivity succeeds on 12 path(s)
Basic connectivity fails on 0 path(s)
................................................
Detected 9000 byte MTU on 12 path(s):
    Local 169.254.59.49 to Remote 169.254.182.76
    Local 169.254.59.49 to Remote 169.254.192.49
    Local 169.254.59.49 to Remote 169.254.195.186
    Local 169.254.59.49 to Remote 169.254.197.206
    Local 169.254.59.49 to Remote 169.254.36.44
    Local 169.254.59.49 to Remote 169.254.7.5
    Local 169.254.62.244 to Remote 169.254.182.76
    Local 169.254.62.244 to Remote 169.254.192.49
    Local 169.254.62.244 to Remote 169.254.195.186
    Local 169.254.62.244 to Remote 169.254.197.206
    Local 169.254.62.244 to Remote 169.254.36.44
    Local 169.254.62.244 to Remote 169.254.7.5
Larger than PMTU communication succeeds on 12 path(s)
RPC status:
6 paths up, 0 paths down (tcp check)
6 paths up, 0 paths down (udp check)
----
====




.次の手順
RCFをアップグレードしたら、link:configure-ssh-keys.html["SSH設定を確認する"] 。
