= 開始する前に
:allow-uri-read: 


イーサネット スイッチ ヘルス モニター (CSHM) は、クラスターおよびストレージ ネットワーク スイッチの動作の健全性を確認し、デバッグのためにスイッチ ログを収集する役割を担います。この手順では、収集の設定、詳細な *サポート* ログの要求、およびAutoSupportによって収集される *定期的* データの 1 時間ごとの収集の有効化のプロセスについて説明します。

*注意:* FIPS モードを有効にする場合は、次の手順を完了する必要があります。

[NOTE]
====
. ベンダーの指示に従ってスイッチ上の SSH キーを再生成します。
. ONTAPでSSHキーを再生成するには `debug system regenerate-systemshell-key-pair`
. ログ収集セットアップルーチンを再実行します。 `system switch ethernet log setup-password`指示


====


== 開始する前に

* ユーザーはスイッチにアクセスできる必要があります `show`コマンド。これらが利用できない場合は、新しいユーザーを作成し、そのユーザーに必要な権限を付与します。
* スイッチのヘルス モニタリングを有効にする必要があります。これを確かめるためには、 `Is Monitored:`フィールドが*true*に設定されている場合は、 `system switch ethernet show`指示。
* Broadcom およびCiscoスイッチによるログ収集の場合:
+
** ローカル ユーザーにはネットワーク管理者権限が必要です。
** ログ収集が有効になっているクラスタ設定ごとに、スイッチ上に新しいユーザーを作成する必要があります。これらのスイッチは、同じユーザーに対して複数の SSH キーをサポートしません。追加のログ収集設定を実行すると、ユーザーの既存の SSH キーが上書きされます。


* NVIDIAスイッチによるログ収集をサポートするには、ログ収集の_ユーザー_に実行を許可する必要があります。 `cl-support`パスワードを入力しなくてもコマンドを実行できます。この使用を許可するには、次のコマンドを実行します。
+
`echo '_<user>_ ALL = NOPASSWD: /usr/cumulus/bin/cl-support' | sudo EDITOR='tee -a' visudo -f /etc/sudoers.d/cumulus`





== 手順

[role="tabbed-block"]
====
.ONTAP 9.15.1以降
--
. ログ収集を設定するには、スイッチごとに次のコマンドを実行します。ログ収集用のスイッチ名、ユーザー名、およびパスワードの入力を求められます。
+
*注意:* ユーザー指定プロンプトに *y* と答える場合は、ユーザーが以下の必要な権限を持っていることを確認してください。<<開始する前に>> 。

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: CL 5.11.1 の場合、ユーザー *cumulus* を作成し、次のプロンプトに *y* と応答します: ログ収集に admin 以外のユーザーを指定しますか?  {y|n}: *y*

. [[step2]]定期的なログ収集を有効にする:
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -periodic-enabled true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs1*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log modify -device cs2 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs2*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log show*
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       true        scheduled   never-run
cs2                                       true        scheduled   never-run
2 entries were displayed.
----
. サポートログ収集をリクエスト:
+
[source, cli]
----
system switch ethernet log collect-support-log -device <switch-name>
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log collect-support-log -device cs1*

*cs1*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log collect-support-log -device cs2*

*cs2*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log show
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       false       halted      initiated
cs2                                       true        scheduled   initiated
2 entries were displayed.
----
. 定期的な収集の有効化、ステータス メッセージ、前回のタイムスタンプとファイル名、サポート収集の要求ステータス、ステータス メッセージ、前回のタイムスタンプとファイル名など、ログ収集のすべての詳細を表示するには、以下を使用します。
+
[source, cli]
----
system switch ethernet log show -instance
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show -instance*

                    Switch Name: cs1
           Periodic Log Enabled: true
            Periodic Log Status: Periodic log collection has been scheduled to run every hour.
    Last Periodic Log Timestamp: 3/11/2024 11:02:59
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:14:20
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz

                    Switch Name: cs2
           Periodic Log Enabled: false
            Periodic Log Status: Periodic collection has been halted.
    Last Periodic Log Timestamp: 3/11/2024 11:05:18
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:18:54
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz
2 entries were displayed.
----


--
.ONTAP 9.14.1以前
--
. ログ収集を設定するには、スイッチごとに次のコマンドを実行します。ログ収集用のスイッチ名、ユーザー名、およびパスワードの入力を求められます。
+
*注:* 回答する場合 `y`ユーザー指定プロンプトが表示されたら、ユーザーが以下の必要な権限を持っていることを確認してください。<<開始する前に>> 。

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: CL 5.11.1 の場合、ユーザー *cumulus* を作成し、次のプロンプトに *y* と応答します: ログ収集に admin 以外のユーザーを指定しますか?  {y|n}: *y*

. [[step2]] サポートログの収集を要求し、定期的な収集を有効にするには、次のコマンドを実行します。これにより、詳細なログ収集と、 `Support`ログと1時間ごとの収集 `Periodic`データ。
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -log-request true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
+
10 分待ってから、ログ収集が完了したことを確認します。

+
[source, cli]
----
system switch ethernet log show
----


--
====