= 2026年7月
:allow-uri-read: 




[[july-2026]]
== 2026年7月



[[new-cisco-nexus-9808-switch-for-afx-2k]]
=== 新しい Cisco Nexus 9808 スイッチ（AFX 2K 用）

新しい Cisco 9808 スイッチは、ストレージ シェルフを備えた AFX 2K コントローラ ノードに接続します。この新しいスイッチを使用すると、2 つ以上のノードを持つ ONTAP クラスタを構築できます。高度なプロトコルを使用してパフォーマンスを最適化します。この設計は、複数のネットワーク パスを備えた VLAN タギングと、テクノロジ更新構成に基づいており、継続的な運用とアップグレードの容易さを保証します。

これらは、1 つのスーパーバイザーモジュール、7 つのファブリックモジュール、および 4 つの電源ユニット （PSU） （X-N9K-C9808-B1-A） を搭載した 36 ポートの 400GbE Cisco スイッチであり、ONTAP 9.19.1 以降をサポートしています。



[[2025-releases]]
== 2025リリース

.2025年10月
[%collapsible]
====
.Cisco Nexus 9332D-GX2B および 9364D-GX2A スイッチ（AFF 1K 対応）
Cisco 9364D-GX2A および Cisco 9332D-GX2B スイッチを使用すると、2つ以上のノードを持つ ONTAP クラスターを構築できます。高度なプロトコルを使用してパフォーマンスを最適化します。この設計は、複数のネットワーク パスを備えた VLAN タギングと、テクノロジー更新構成に基づいており、継続的な運用と容易なアップグレードを実現します。

これらは、ONTAP 9.17.1以降をサポートする32ポートおよび64ポートの400GbE Cisco スイッチ（X190300-CS-PI、X190300-PE、X190310-CS-PI）です。

新しい NetApp AFX ストレージシステムは、AI/ML アプリケーションを含むハイパフォーマンス NAS および S3 ワークロードの厳しい要件を満たすように設計された分散型ソリューションを提供します。AFX システムは、スケーラブルで高スループットのファイルおよびオブジェクトストレージを必要とするお客様向けに、専門的な機能を提供します。

====
.2025年5月
[%collapsible]
====
.Cisco Nexus 9336C-FX2-T ストレージ スイッチ
これらは、ONTAP 9.10.1 以降をサポートする 12 ポートの 10/25/40/100GbE Cisco ストレージ スイッチ（X190212-CS-PE および X190212-CS-PI）です。これらは 100GbE ストレージ（スイッチ接続型ストレージ）構成をサポートしています。

====


[[2023-release]]
== 2023リリース

.2023年5月
[%collapsible]
====
.Cisco Nexus 9336C-FX2-T クラスタ スイッチ
これらは、ONTAP 9.10.1以降をサポートする12ポートの10/25/40/100GbE Ciscoクラスタ スイッチ（X190212-CS-PEおよびX190212-CS-PI）です。10/25/40/100GbEのクラスタ構成をサポートしています。

====


[[2022-release]]
== 2022リリース

.2022年10月
[%collapsible]
====
.NVIDIA SN2100スイッチ
NVIDIA SN2100は、16ポートの100GbE NVIDIAスイッチ（X190006-PEおよびX190006-PI）であり、ONTAP 9.10.1以降をサポートする2つ以上のノードを持つONTAPクラスタを構築できます。これは、NVIDIA SN2100クラスタ インターコネクトスイッチおよびストレージ ネットワークスイッチであり、MetroCluster IP構成のサポートも含まれています。

====


[[2021-release]]
== 2021リリース

.2021年5月
[%collapsible]
====
.Cisco Nexus 9336C-FX2 スイッチ
Cisco Nexus 9336C-FX2は、36ポートの100GbE Ciscoスイッチ（X190200-CS-PEおよびX190200-CS-PI）です。同じペアのCisco Nexus 9336C-FX2スイッチで、MetroCluster IP構成のサポートを含む共有インフラ（クラスタ、HA、およびスイッチ接続ストレージ）をサポートし、ONTAP 9.9.1以降に対応しています。

====


[[2019-release]]
== 2019リリース

.2019年5月
[%collapsible]
====
.Broadcom BES-53248 スイッチ
Broadcom BES-53248 スイッチ （X190005 および X190005R） は、10/25GbE および 40/100GbE ポートを備えた AFF/FAS コントローラをサポートし、ONTAP 9.8 以降をサポートします。

====
.2019年3月
[%collapsible]
====
.Cisco Nexus 3232C クラスタおよびストレージ スイッチ
Cisco Nexus 3232C スイッチは、36 ポート 100GbE Cisco スイッチ（X190200）および 32 ポート 100GbE Cisco スイッチ（X190100 および X190100R）です。Cisco Nexus 3232C ストレージ ネットワーク スイッチは、以下の NS224 NVMe ドライブシェルフへの接続をサポートしています。AFF および ASA ストレージ システム：

* AFF A800/ AFF ASA A800
* AFF A700/ AFF ASA A700
* AFF A400/ AFF ASA A400


これらはONTAP 9.8以降をサポートしています。

====