= 
:allow-uri-read: 


お使いのAFXシステムで実行されているONTAPのバージョンとスイッチのNX-OSのバージョンによって、スイッチでサポートされるRCFのバージョンが決まります。RCFバージョンには、ブレークアウトモード（4x100GbE）と非ブレークアウトモードのスイッチポートの数を決定する、プリセットされたポート速度構成があります。

[NOTE]
====
現在サポートされている RCF バージョンの一覧については、link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["NetApp Cisco イーサネットスイッチ"^]ページを参照してください。

スイッチポート情報は、 https://hwu.netapp.com["NetApp Hardware Universe"^]にも記載されています。

====
* AFX 1Kシステムをお持ちの場合は、RCF 10.0以降がサポートされています。
* AFX 2Kシステムをお持ちの場合は、RCF 10.1以降がサポートされています。
* RCF 10.0 には 1 つのファイルがあり、共有スイッチをサポートしています。 `Cluster-HA-Storage AFX RCF_10.0`
+
例えば、次の表は、この RCF ファイルにおけるスイッチポートのプリセットされたグループ分け、ポート速度、および使用状況を示しています。

+
[cols="1,2"]
|===
| スイッチポートグループ | ポートの速度と使用状況 


 a| 
Ethernet1/1/1-4 から Ethernet1/62/1-4
 a| 
クラスタ、HA、ストレージ接続用の4x100GbEモード



 a| 
イーサネット1/63、イーサネット1/64
 a| 
400GbE ISL

|===
* RCF 10.1には、AFX 1KシステムとAFX 2Kシステムそれぞれで、異なる使用事例に対応した異なるファイルが含まれています。AFX 1KまたはAFX 2Kシステム構成でスイッチをどのように使用するか（共有、ストレージ専用、クラスタおよびHA専用）に応じて、適切なRCFファイルを選択します。
+
例えば、AFX 2Kシステムでスイッチを共有スイッチとして使用する場合は、その使用状況に適したRCFファイルを使用します。適切なRCFファイルは、 `RCF-v10.1-NX9364D-GX2A-CL1-ST1-100GBR31-400G31.txt`のように命名される場合があります。以下の表は、このRCFファイルにおけるスイッチポートのプリセットグループ、ポート速度、および使用状況を示しています。

+
[cols="1,2"]
|===
| スイッチポートグループ | ポートの速度と使用状況 


 a| 
Ethernet1/1/1-4 から Ethernet1/31/1-4 まで
 a| 
クラスター内接続、HA接続、およびストレージシェルフ接続用の4x100GbEモード



 a| 
Ethernet1/32からEthernet1/62
 a| 
クラスター内接続、HA接続、ストレージ接続用の400GbEモード



 a| 
イーサネット1/63、イーサネット1/64
 a| 
400GbE クラスタ内 ISL 接続

|===

