---
permalink: switch-cisco-9332d-gx2b/configure-install-rcf-9332d.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: RCF を新しい Cisco Nexus 9332D-GX2B スイッチにインストールします。これは、新しい AFX 1K または AFX 2K システムのインストールとセットアップの一部として、故障したスイッチを交換する場合、またはスイッチを工場出荷時のデフォルト設定にリセットする場合に行います。 
---
= RCF のインストール - Cisco Nexus 9332D-GX2B
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RCF を新しい Cisco Nexus 9332D-GX2B スイッチにインストールします。これは、新しい AFX 1K または AFX 2K システムのインストールの一部として、スイッチの交換、またはスイッチを工場出荷時のデフォルト設定にリセットする場合に行います。

.開始する前に
* スイッチの電源をオンにし、link:configure-complete-initial-setup-9332d.html["スイッチの初期設定を完了する"]の手順を完了している必要があります。
* 目的の NX-OS バージョンを link:configure-install-nxos-9332d.html["NX-OSをインストールします"] の手順を使用してインストールしておく必要があります。
* link:configure-install-upgrade-rcf-overview-9332d.html["RCF のインストールまたはアップグレードの概要"]ページを読んでいる必要があります。
* スイッチの交換や工場出荷時のデフォルト設定へのリセットの一環として RCF をスイッチにインストールする場合は、クラスターが完全に機能していることを確認してください。つまり、ログにエラーや同様の問題がないことを確認してください。



NOTE: RCFを新しいAFXシステムのインストールの一部としてインストールする場合は、この要件をスキップできます。AFXシステムのインストールとセットアップのこの段階では、AFXシステムのコントローラの電源がまだ入っていないためです。

.タスク概要
* AFX 1KまたはAFX 2Kシステムの新規インストールの一環としてスイッチをインストールした場合、この手順ではまず最初のスイッチ（cs1）にRCFをインストールし、次に2番目のスイッチ（cs2）に対して同じ手順を繰り返します。
* この手順では、Cisco Nexus 9000 シリーズスイッチのコマンドのみを使用します。
* この手順の例では、最初のスイッチをcs1、2番目のスイッチをcs2と表記します。
* この手順で示す例は、RCF 10.0を実行しているスイッチを備えたAFX 1Kシステムを対象としています。AFX 2Kシステムをお持ちの場合、入力と出力は異なる場合があります。




[[step-1-prepare-to-install-the-rcf]]
== ステップ1：RCFのインストール準備

スイッチにRCFをインストールする準備として、RCFのダウンロードに必要な接続が揃っていることを確認し、RCFをダウンロードしてください。

.手順
. HTTP、FTP、またはTFTPサーバーへのアクセス権が必要です。これらのサーバーのいずれかにアクセスすることで、サポートされているバージョンのRCFをダウンロードできます。
. お使いのAFXシステムの種類に対応したRCFを、NetApp Support Site（ http://mysupport.netapp.com/["mysupport.netapp.com"^]）からダウンロードしてください。
+

NOTE: 新しいスイッチにはRCFはインストールされていません。スイッチにRCFをインストールする必要があります。

. 各スイッチはコンソールに接続されているか、各スイッチへのリモートアクセスが可能である必要があります。




[[step-2-install-the-rcf]]
== ステップ2：RCFをインストールする

最初のスイッチ（cs1）にRCFをインストールするには、RCFをbootflashにコピーして適用し、バナー出力を確認し、RCFのバージョンが正しいことを確認し、カスタム追加を記録し、基本構成の詳細を保存し、write_erase.cfgファイルが正しく書き込まれていることを確認し、現在保存されている構成を消去し、以前に保存した基本構成をスタートアップ構成にコピーし、最後にスイッチを再起動します。RCFを新しいAFXシステムのインストールの一部としてインストールする場合は、2番目のスイッチ（cs2）でもこれらの手順を繰り返します。

. SSH またはシリアル コンソールを使用してスイッチ cs1 にログインします。
. FTP、TFTP、SFTP、SCPのいずれかの転送プロトコルを使用して、スイッチcs1のブートフラッシュにRCFをコピーします。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html["Cisco Nexus 9000 シリーズ NX-OS コマンド リファレンス"^]の適切なガイドを参照してください。

+
`copy <protocol>: bootflash: vrf management`

+
.例を表示
[%collapsible]
====
この例では、TFTPを使用してスイッチcs1のブートフラッシュにRCFをコピーしています。

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9332D-GX2B-RCF-v10.0-Shared.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 以前にコピーしたRCFファイルをブートフラッシュに適用します。
+
Ciscoコマンドの詳細については、link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html["Cisco Nexus 9000 シリーズ NX-OS コマンド リファレンス"^]の適切なガイドを参照してください。

+
次のコマンドは、スイッチcs1にインストールされているRCFファイル `NX9332D-GX2B-RCF-v10.0-Shared.txt`を示しています：

+
[listing, subs="+quotes"]
----
cs1# *copy NX9332D-GX2B-RCF-v10.0-Shared.txt running-config echo-commands*
----
+

NOTE: RCF 10.1以降では、ファイル名の形式が異なります。例えば、 `RCF-v10.1-NX9332D-GX2B-CL1-ST1-100GB15-400G15.txt`は、ブレークアウトおよび400GbE用のポートが指定された共有スイッチ用です。

. バナー出力を調べる `show banner motd`指示。スイッチが正しく動作するように設定するためには、出力を確認し、その指示に従う必要があります。
+
.例を表示
[%collapsible]
====
[listing]
----
cs1# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : NX9332D-GX2B
* Filename : NX9332D-GX2B-RCF-v10.0-Shared.txt
* Date     : 05-09-2025
* Version  : v10.0
* Port Usage:
* Ports  1-30: 100GbE Intra-Cluster/HA/Storage Ports, int e1/{1-30}/1-4
* Ports 31-32: Intra-Cluster ISL Ports, int e1/31-32
*
* IMPORTANT NOTES
* Interface port-channel999 is reserved to identify the version of this file.
******************************************************************************
----
====
. RCFファイルが正しいバージョンであることを確認します。
+
`show running-config`

+
次の情報が正しいことを確認してください。

+
** RCFのバナー
** ノードとポートの設定
** カスタマイズ
+
出力内容はサイトの構成によって異なります。ポートの設定を確認し、インストールしたRCFに固有の変更がないかリリース ノートを参照してください。



. 現在実行中の設定をスタートアップ設定にコピーして、永続化します。
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. スイッチをリブートします。
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. RCFを新しいAFXシステムインストールの一部としてインストールする場合は、スイッチcs2でこれらの手順を繰り返してください。


.次の手順
RCFをスイッチにインストールしたら、link:configure-verify-ssh-9332d.html["ログ収集のためにSSHを確認する"]。
