---
permalink: switch-cisco-9332d-gx2b/install-rcf-software-9332d-cluster.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: Nexus 9332D-GX2B スイッチを初めてセットアップした後、RCF をインストールできます。 
---
= 参照構成ファイル（RCF）をインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nexus 9332D-GX2B スイッチを初めてセットアップした後、リファレンス構成ファイル (RCF) をインストールします。

.開始する前に
次のインストールと接続を確認します。

* スイッチへのコンソール接続。スイッチにリモートアクセスできる場合、コンソール接続はオプションです。
* スイッチ cs1 とスイッチ cs2 の電源がオンになり、スイッチの初期セットアップが完了します (管理 IP アドレスと SSH がセットアップされています)。
* 必要な NX-OS バージョンがインストールされました。
* スイッチ間の ISL 接続が接続されています。




== ステップ1: スイッチにRCFをインストールする

. SSH またはシリアル コンソールを使用してスイッチ cs1 にログインします。
. FTP、TFTP、SFTP、SCPのいずれかの転送プロトコルを使用して、スイッチcs1のブートフラッシュにRCFをコピーします。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 シリーズ NX-OS コマンド リファレンス"^]ガイド。

+
.例を表示
[%collapsible]
====
この例では、TFTPを使用してスイッチcs1のブートフラッシュにRCFをコピーしています。

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9332D-GX2B-RCF-v10.0-Shared.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 前の手順でブートフラッシュにダウンロードしたRCFを適用します。
+
Ciscoコマンドの詳細については、 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 シリーズ NX-OS コマンド リファレンス"^]ガイド。

+
この例ではRCFファイルを示します `NX9332D-GX2B-RCF-v10.0-Shared.txt`スイッチ cs1 にインストールされます:

+
[listing, subs="+quotes"]
----
cs1# *copy NX9332D-GX2B-RCF-v10.0-Shared.txt running-config echo-commands*
----
. バナー出力を調べる `show banner motd`指示。スイッチが正しく動作するように設定するためには、出力を確認し、その指示に従う必要があります。
+
.例を表示
[%collapsible]
====
[listing]
----
cs1# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : NX9332D-GX2B
* Filename : NX9332D-GX2B-RCF-v10.0-Shared.txt
* Date     : 05-09-2025
* Version  : v10.0
* Port Usage:
* Ports  1-30: 100GbE Intra-Cluster/HA/Storage Ports, int e1/{1-30}/1-4
* Ports 31-32: Intra-Cluster ISL Ports, int e1/31-32
*
* IMPORTANT NOTES
* Interface port-channel999 is reserved to identify the version of this file.
******************************************************************************
----
====
. RCF ファイルが正しい新しいバージョンであることを確認します。
+
`show running-config`

+
次の情報が正しいことを確認してください。

+
** RCFのバナー
** ノードとポートの設定
** カスタマイズ
+
出力内容はサイトの構成によって異なります。ポートの設定を確認し、インストールしたRCFに固有の変更がないかリリース ノートを参照してください。



. 基本的な設定の詳細を `write_erase.cfg`ブートフラッシュ上のファイル。
+
[NOTE]
====
必ず以下を設定してください。

** ユーザ名とパスワード
** 管理IPアドレス
** デフォルト ゲートウェイ
** スイッチ名


====
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1536" >> bootflash:write_erase.cfg`

+
ナレッジベースの記事を参照link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["リモート接続を維持しながらCiscoインターコネクトスイッチの設定をクリアする方法"^]詳細については、こちらをご覧ください。

. 確認するには `write_erase.cfg`ファイルは期待どおりに入力されます。
+
`*show file bootflash:write_erase.cfg*`

. 発行する `write erase`現在保存されている構成を消去するコマンド:
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. 以前に保存した基本設定をスタートアップ設定にコピーします。
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. スイッチをリブートします。
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. スイッチ cs2 で手順 1 ～ 10 を繰り返します。
. ONTAPクラスタ内のすべてのノードのポートをスイッチ cs1 および cs2 に接続します。




== ステップ2: スイッチの接続を確認する

. クラスタ ポートに接続されているスイッチ ポートが稼働していることを確認します。
+
`show interface brief`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
.
.
Eth1/9/3        1       eth  trunk  up      none                     100G(D) --
Eth1/9/4        1       eth  trunk  up      none                     100G(D) --
Eth1/15/1       1       eth  trunk  up      none                     100G(D) --
Eth1/15/2       1       eth  trunk  up      none                     100G(D) --
Eth1/15/3       1       eth  trunk  up      none                     100G(D) --
Eth1/15/4       1       eth  trunk  up      none                     100G(D) --
Eth1/16/1       1       eth  trunk  up      none                     100G(D) --
Eth1/16/2       1       eth  trunk  up      none                     100G(D) --
Eth1/16/3       1       eth  trunk  up      none                     100G(D) --
Eth1/16/4       1       eth  trunk  up      none                     100G(D) --
Eth1/17/1       1       eth  trunk  up      none                     100G(D) --
Eth1/17/2       1       eth  trunk  up      none                     100G(D) --
Eth1/17/3       1       eth  trunk  up      none                     100G(D) --
Eth1/17/4       1       eth  trunk  up      none                     100G(D) --
.
.
----
====
. 次のコマンドを使用して、クラスタ ノードが正しいクラスタ VLAN 内にあることを確認します。
+
`show vlan brief`

+
`show interface trunk`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show vlan brief*
VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po1, Po999, Eth1/31, Eth1/32
                                                Eth1/33, Eth1/34, Eth1/1/1
                                                Eth1/1/2, Eth1/1/3, Eth1/1/4
                                                Eth1/2/1, Eth1/2/2, Eth1/2/3
                                                Eth1/2/4, Eth1/3/1, Eth1/3/2
                                                Eth1/3/3, Eth1/3/4, Eth1/4/1
                                                Eth1/4/2, Eth1/4/3, Eth1/4/4
                                                Eth1/5/1, Eth1/5/2, Eth1/5/3
                                                Eth1/5/4, Eth1/6/1, Eth1/6/2
                                                Eth1/6/3, Eth1/6/4, Eth1/7/1
                                                Eth1/7/2, Eth1/7/3, Eth1/7/4
                                                Eth1/8/1, Eth1/8/2, Eth1/8/3
                                                Eth1/8/4, Eth1/9/1, Eth1/9/2
                                                Eth1/9/3, Eth1/9/4, Eth1/10/1
                                                Eth1/10/2, Eth1/10/3, Eth1/10/4
                                                Eth1/11/1, Eth1/11/2, Eth1/11/3
                                                Eth1/11/4, Eth1/12/1, Eth1/12/2
                                                Eth1/12/3, Eth1/12/4, Eth1/13/1
                                                Eth1/13/2, Eth1/13/3, Eth1/13/4
                                                Eth1/14/1, Eth1/14/2, Eth1/14/3
                                                Eth1/14/4, Eth1/15/1, Eth1/15/2
                                                Eth1/15/3, Eth1/15/4, Eth1/16/1
                                                Eth1/16/2, Eth1/16/3, Eth1/16/4
                                                Eth1/17/1, Eth1/17/2, Eth1/17/3
                                                Eth1/17/4, Eth1/18/1, Eth1/18/2
                                                Eth1/18/3, Eth1/18/4, Eth1/19/1
                                                Eth1/19/2, Eth1/19/3, Eth1/19/4
                                                Eth1/20/1, Eth1/20/2, Eth1/20/3
                                                Eth1/20/4, Eth1/21/1, Eth1/21/2
                                                Eth1/21/3, Eth1/21/4, Eth1/22/1
                                                Eth1/22/2, Eth1/22/3, Eth1/22/4
                                                Eth1/23/1, Eth1/23/2, Eth1/23/3
                                                Eth1/23/4, Eth1/24/1, Eth1/24/2
                                                Eth1/24/3, Eth1/24/4, Eth1/25/1
                                                Eth1/25/2, Eth1/25/3, Eth1/25/4
                                                Eth1/26/1, Eth1/26/2, Eth1/26/3
                                                Eth1/26/4, Eth1/27/1, Eth1/27/2
                                                Eth1/27/3, Eth1/27/4, Eth1/28/1
                                                Eth1/28/2, Eth1/28/3, Eth1/28/4
                                                Eth1/29/1, Eth1/29/2, Eth1/29/3
                                                Eth1/29/4, Eth1/30/1, Eth1/30/2
                                                Eth1/30/3, Eth1/30/4
17   VLAN0017                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
18   VLAN0018                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
30   VLAN0030                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
40   VLAN0040                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4

cs1# *show interface trunk*
--------------------------------------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
--------------------------------------------------------------------------------
Eth1/1/1      1       trunking      --
Eth1/1/2      1       trunking      --
Eth1/1/3      1       trunking      --
Eth1/1/4      1       trunking      --
Eth1/2/1      1       trunking      --
Eth1/2/2      1       trunking      --
Eth1/2/3      1       trunking      --
Eth1/2/4      1       trunking      --
.
.
.
Eth1/30/1     none
Eth1/30/2     none
Eth1/30/3     none
Eth1/30/4     none
Eth1/31       none
Eth1/32       none
Po1           1
----
====
+

NOTE: 特定のポートと VLAN の使用法の詳細については、RCF のバナーと重要な注意事項のセクションを参照してください。

. cs1 と cs2 間の ISL が機能していることを確認します。
+
[source, cli]
----
show port-channel summary
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
999   Po999(SD)   Eth      NONE      --
cs1#
----
====




== ステップ3: ONTAPクラスタをセットアップする

NetApp、 System Manager を使用して新しいクラスタを設定することをお勧めします。

System Managerを使用すれば、ノード管理IPアドレスの割り当て、クラスタの初期化、ローカル階層の作成、プロトコルの設定、初期ストレージのプロビジョニングなど、クラスタのセットアップと設定をシンプルで簡単なワークフローで実行できます。

へ移動 https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["System Managerを使用した新しいクラスタでのONTAPの設定"]セットアップ手順についてはこちらをご覧ください。

.次の手順
RCFをインストールしたら、 link:configure-ssh-keys.html["SSH設定を確認する"]。
