---
permalink: switch-cisco-9332d-gx2b/replace-9332d-cluster.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9332d-gx2b cluster switch - cisco nexus 9332d-gx2b 
summary: 'クラスタ ネットワーク内の故障した Nexus 9332D-GX2B スイッチを交換することは、無停止の手順 (NDU) です。' 
---
= Cisco Nexus 9332D-GX2Bスイッチを交換する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
共有ネットワーク内の故障した Nexus 9332D-GX2B スイッチを交換するには、次の手順に従います。これは非中断手順 (NDU) です。



== 要件の確認

スイッチの交換を実行する前に、次の点を確認してください。

* 正しいスイッチが交換されたことを確認するために、スイッチのシリアル番号を確認しました。
* 既存のクラスターおよびネットワーク インフラストラクチャの場合:
+
** 既存のクラスターは、少なくとも 1 つの完全接続されたクラスター スイッチを備え、完全に機能していることが検証されます。
** すべてのクラスター ポートが稼働しています。
** すべてのクラスタ論理インターフェイス (LIF) が起動しており、ホーム ポート上にあります。
** ONTAP `cluster ping-cluster -node <node-name>`コマンドは、すべてのパスで基本的な接続と PMTU より大きい通信が成功していることを示す必要があります。


* Nexus 9332D-GX2B 交換スイッチの場合:
+
** 交換スイッチ上の管理ネットワーク接続は機能しています。
** 交換用スイッチへのコンソール アクセスが確立されています。
** ノード接続はポート1/1～1/30です。
** ポート 1/31 および 1/32 のすべての Inter-Switch Link (ISL) ポートが無効になっています。
** 必要な参照構成ファイル (RCF) と NX-OS オペレーティング システム イメージ スイッチがスイッチにロードされます。
** スイッチの初期カスタマイズは完了しました。詳細はlink:setup-switch-9332d-cluster.html["9332D-GX2Bクラスタスイッチを構成する"]。
+
STP、SNMP、SSH などの以前のサイトのカスタマイズは、新しいスイッチにコピーされます。



* クラスタ LIF がホストされているノードからクラスタ LIF を移行するためのコマンドを実行しました。




== コンソールログを有効にする

NetApp、使用しているデバイスでコンソール ログを有効にし、スイッチを交換するときに次のアクションを実行することを強くお勧めします。

* メンテナンス中はAutoSupport を有効のままにしておきます。
* メンテナンスの前後にメンテナンスAutoSupport をトリガーして、メンテナンス期間中のケース作成を無効にします。このナレッジベースの記事を参照してください https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: スケジュールされたメンテナンス期間中の自動ケース作成を抑制する方法"^]詳細については、こちらをご覧ください。
* すべての CLI セッションのセッション ログを有効にします。セッションログを有効にする方法については、このナレッジベースの記事の「セッション出力のログ記録」セクションを参照してください。 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAPシステムへの最適な接続を実現するための PuTTY の設定方法"^] 。




== スイッチを交換する

.例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 既存の Nexus 9332D-GX2B スイッチの名前は cs1 と cs2 です。
* 新しい Nexus 9332D-GX2B スイッチの名前は newcs2 です。
* ノード名は、node1-01、node1-02、node1-03、node1-04 です。
* クラスタ LIF 名は、node1-01 の場合は node1-01_clus1 と node1-01_clus2、node1-02 の場合は node1-02_clus1 と node1-02_clus2、node1-03 の場合は node1-03_clus1 と node1-03_clus2、node1-04 の場合は node1-04_clus1 と node1-04_clus2 です。
* すべてのクラスタノードへの変更のプロンプトはcluster1::*>です。


.タスク概要
次の手順は、次のクラスタ ネットワーク トポロジに基づいています。

.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

8 entries were displayed.


cluster1::*> *network interface show -vserver Cluster*
            Logical    Status     Network            Current     Current   Is
Vserver     Interface  Admin/Oper Address/Mask       Node        Port      Home
----------- ---------- ---------- ------------------ ----------- --------- ----
Cluster
            node1-01_clus1 up/up  169.254.36.44/16    node1-01    e7a      true
            node1-01_clus2 up/up  169.254.7.5/16      node1-01    e7b      true
            node1-02_clus1 up/up  169.254.197.206/16  node1-02    e7a      true
            node1-02_clus2 up/up  169.254.195.186/16  node1-02    e7b      true
            node1-03_clus1 up/up  169.254.192.49/16   node1-03    e7a      true
            node1-03_clus2 up/up  169.254.182.76/16   node1-03    e7b      true
            node1-04_clus1 up/up  169.254.59.49/16    node1-04    e7a      true
            node1-04_clus2 up/up  169.254.62.244/16   node1-04    e7b      true

8 entries were displayed.

cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FLMXXXXXXXX)          Ethernet1/16/3    N9K-C9332D-GX2B
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/16/3    N9K-C9332D-GX2B
            e11a   cs1(FLMXXXXXXXX)          Ethernet1/16/4    N9K-C9332D-GX2B
            e11b   cs2(FDOXXXXXXXX)          Ethernet1/16/4    N9K-C9332D-GX2B
            e1a    cs1(FLMXXXXXXXX)          Ethernet1/16/1    N9K-C9332D-GX2B
            e1b    cs2(FDOXXXXXXXX)          Ethernet1/16/1    N9K-C9332D-GX2B
            .
            .
            .
            e7a    cs1(FLMXXXXXXXX)          Ethernet1/16/2    N9K-C9332D-GX2B
            e7b    cs2(FDOXXXXXXXX)          Ethernet1/16/2    N9K-C9332D-GX2B

cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
Device-ID          Local Intrfce  Hldtme Capability  Platform         Port ID
cs2(FDOXXXXXXXX)    Eth1/31        179    R S I s   N9K-C9364D-GX2A   Eth1/63
cs2(FDOXXXXXXXX)    Eth1/32        179    R S I s   N9K-C9364D-GX2A   Eth1/64
node1-01            Eth1/4/1       123    H         AFX-1K            e1a
node1-01            Eth1/4/2       123    H         AFX-1K            e7a
node1-01            Eth1/4/3       123    H         AFX-1K            e10a
node1-01            Eth1/4/4       123    H         AFX-1K            e11a
node1-02            Eth1/9/1       138    H         AFX-1K            e1a
node1-02            Eth1/9/2       138    H         AFX-1K            e7a
node1-02            Eth1/9/3       138    H         AFX-1K            e10a
node1-02            Eth1/9/4       138    H         AFX-1K            e11a
node1-03            Eth1/15/1      138    H         AFX-1K            e1a
node1-03            Eth1/15/2      138    H         AFX-1K            e7a
node1-03            Eth1/15/3      138    H         AFX-1K            e10a
node1-03            Eth1/15/4      138    H         AFX-1K            e11a
node1-04            Eth1/16/1      173    H         AFX-1K            e1a
node1-04            Eth1/16/2      173    H         AFX-1K            e7a
node1-04            Eth1/16/3      173    H         AFX-1K            e10a
node1-04            Eth1/16/4      173    H         AFX-1K            e11a

Total entries displayed: 18

cs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
Device-ID          Local Intrfce  Hldtme Capability  Platform         Port ID
cs1(FLMXXXXXXXX)    Eth1/31        179    R S I s   N9K-C9364D-GX2A   Eth1/63
cs1(FLMXXXXXXXX)    Eth1/32        179    R S I s   N9K-C9364D-GX2A   Eth1/64
node1-01            Eth1/4/1       123    H         AFX-1K            e1a
node1-01            Eth1/4/2       123    H         AFX-1K            e7a
node1-01            Eth1/4/3       123    H         AFX-1K            e10a
node1-01            Eth1/4/4       123    H         AFX-1K            e11a
node1-02            Eth1/9/1       138    H         AFX-1K            e1a
node1-02            Eth1/9/2       138    H         AFX-1K            e7a
node1-02            Eth1/9/3       138    H         AFX-1K            e10a
node1-02            Eth1/9/4       138    H         AFX-1K            e11a
node1-03            Eth1/15/1      138    H         AFX-1K            e1a
node1-03            Eth1/15/2      138    H         AFX-1K            e7a
node1-03            Eth1/15/3      138    H         AFX-1K            e10a
node1-03            Eth1/15/4      138    H         AFX-1K            e11a
node1-04            Eth1/16/1      173    H         AFX-1K            e1a
node1-04            Eth1/16/2      173    H         AFX-1K            e7a
node1-04            Eth1/16/3      173    H         AFX-1K            e10a
node1-04            Eth1/16/4      173    H         AFX-1K            e11a

Total entries displayed: 18
----
====


=== ステップ1: 交換の準備

. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
ここで、x はメンテナンス ウィンドウの期間 (時間単位) です。

+

NOTE: AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

. 適切なRCFとイメージをスイッチnewcs2にインストールし、必要なサイトの準備を行います。
+
必要に応じて、新しいスイッチ用に、RCFおよびNX-OSソフトウェアの適切なバージョンを確認、ダウンロード、およびインストールします。新しいスイッチが正しくセットアップされており、RCFおよびNX-OSソフトウェアのアップデートが不要であることを確認した場合は、手順2に進みます。

+
.. NetAppサポート サイトの「NetApp クラスタおよび管理ネットワーク スイッチ リファレンス構成ファイルの説明ページ」にアクセスします。
.. _クラスタ ネットワークおよび管理ネットワークの互換性マトリックス_ のリンクをクリックし、必要なスイッチ ソフトウェアのバージョンをメモします。
.. ブラウザの戻る矢印をクリックして説明ページに戻り、[*続行*] をクリックしてライセンス契約に同意し、ダウンロード ページに進みます。
.. ダウンロード ページの手順に従って、インストールするONTAPソフトウェアのバージョンに適した RCF および NX-OS ファイルをダウンロードします。


. 新しいスイッチにadminとしてログインし、ノード クラスタ インターフェイス（ポート1/1～1/30）に接続するすべてのポートをシャットダウンします。
+
交換するスイッチが機能せず、電源がオフになっている場合は、手順4に進みます。クラスタ ノードのLIFは、各ノードのもう一方のクラスタ ポートにすでにフェイルオーバーされている必要があります。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
newcs2# *config*
newcs2(config)# *interface e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7/1-4,e1/8/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config)# *interface e1/9/1-4,e1/10/1-4,e1/11/1-4,e1/12/1-4,e1/13/1-4,e1/14/1-4,e1/15/1-4,e1/16/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config)# *interface e1/17/1-4,e1/18/1-4,e1/19/1-4,e1/20/1-4,e1/21/1-4,e1/22/1-44,e1/23/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config)# *interface e1/24/1-,e1/25/1-4,e1/26/1-4,e1/27/1-4,e1/28/1-4,e1/29/1-4,e1/30/1-44*
newcs2(config-if-range)# *shutdown*
newcs2(config-if-range)# exit
newcs2(config)# exit
----
====
. すべてのクラスタ LIF で自動復帰が有効になっていることを確認します。
+
[source, cli]
----
network interface show -vserver Cluster -fields auto-revert
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster -fields auto-revert*

             Logical
Vserver      Interface        Auto-revert
------------ ---------------- -------------
Cluster      node1-01_clus1   true
Cluster      node1-02_clus2   true
Cluster      node1-03_clus1   true
Cluster      node1-04_clus2   true

4 entries were displayed.
----
====
. リモート クラスタ インターフェイスの接続を確認します。
+
.. 使用することができます `network interface check cluster-connectivity show`クラスター接続のアクセシビリティ チェックの詳細を表示するコマンド:
+
[source, cli]
----
network interface check cluster-connectivity show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                     Source          Destination     Packet
Node      Date                       LIF             LIF             Loss
--------- -------------------------- --------------- --------------- -----------
node1-01
          6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1  none
          6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus2  none
node1-02
          6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1  none
          6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2  none
.
.
.
----
====
.. あるいは、 `cluster ping-cluster -node <node-name>`接続を確認するコマンド:
+
`cluster ping-cluster -node <node-name>`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====






=== ステップ2: ケーブルとポートを構成する

. Nexus 9332D-GX2B スイッチ cs1 の ISL ポート Eth1/31 と Eth1/32 をシャットダウンします。
+
[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/31-32*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# exit
cs1(config)# exit
----
. Nexus 9332D-GX2B cs2 スイッチからすべてのケーブルを取り外し、それらを 9332D-GX2B newcs2 スイッチの同じポートに接続します。
. cs1 スイッチと newcs2 スイッチ間の ISL ポート Eth1/31 と Eth1/32 を起動し、ポート チャネルの動作ステータスを確認します。
+
ポートチャネルはPo1（SU）を示し、メンバー ポートはEth1/31（P）およびEth1/32（P）を示している必要があります。

+
.例を表示
[%collapsible]
====
この例では、ISL ポート Eth1/31 と Eth1/32 を有効にし、スイッチ cs1 のポート チャネルの概要を表示します。

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *int e1/31-32*
cs1(config-if-range)# *no shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
cs1#
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
999   Po999(SD)   Eth      NONE      --
----
====
. すべてのノードでポート e7b が稼働していることを確認します。
+
[source, cli]
----
network port show ipspace Cluster
----
+
.例を表示
[%collapsible]
====
次のような出力が表示されます。

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

8 entries were displayed.
----
====
. 前の手順で使用したのと同じノードで、network interface revert コマンドを使用して、前の手順でポートに関連付けられたクラスタ LIF を元に戻します。
+
.例を表示
[%collapsible]
====
この例では、Home 値が true でポートが e7b の場合、node1-01 上の LIF node1-01_clus2 は正常に元に戻されます。

次のコマンドはLIFを返します `node1-01_clus2`の上 `node1-01`母港へ `e7a`両方のノードの LIF に関する情報を表示します。両方のクラスタインターフェースのIs Home列がtrueで、正しいポート割り当てが表示されている場合、最初のノードの起動は成功です。この例では、 `e7a`そして `e7b`node1-01 上。

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

          Logical        Status     Network            Current    Current Is
Vserver   Interface      Admin/Oper Address/Mask       Node       Port    Home
--------- -------------- ---------- ------------------ ---------- ------- -----
Cluster
          node1-01_clus1  up/up     169.254.209.69/16  node1-01   e7a     true
          node1-01_clus2  up/up     169.254.49.125/16  node1-01   e7b     true
          node1-02_clus1  up/up     169.254.47.194/16  node1-02   e7b     true
          node1-02_clus2  up/up     169.254.19.183/16  node1-02   e7a     false
          .
          .
          .
----
====
. クラスター内のノードに関する情報を表示します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
この例では、このクラスター内の node1 と node2 のノード ヘルスが true であることを示しています。

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node           Health  Eligibility
-------------- ------- ------------
node1-01       false   true
node1-02       true    true
node1-03       true    true
node1-04       true    true
----
====
. すべての物理クラスター ポートが稼働していることを確認します。
+
[source, cli]
----
network port show ipspace Cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false
.
.
.
----
====
. リモート クラスタ インターフェイスの接続を確認します。
+
.. 使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックの詳細を表示するコマンド:
+
[source, cli]
----
network interface check cluster-connectivity start
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                     Source          Destination     Packet
Node      Date                       LIF             LIF             Loss
--------- -------------------------- --------------- --------------- -----------
node1-01
          6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1  none
          6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus2  none
node1-02
          6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1  none
          6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2  none
.
.
.
----
====
.. あるいは、 `cluster ping-cluster -node <node-name>`接続を確認するコマンド:
+
`cluster ping-cluster -node <node-name>`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====






=== ステップ3: 構成を確認する

. クラスター上のすべてのポートの正常性を確認します。
+
.. *クラスターポート*
+
... クラスター内のすべてのノードでクラスター ポートが稼働しており正常であることを確認します。
+
[source, cli]
----
network port show ipspace Cluster
----
+
[source, cli]
----
network interface show -vserver Cluster
----
+
[source, cli]
----
network device-discovery show -protocol cdp
----
+
[source, cli]
----
show cdp neighbors
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*
Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

8 entries were displayed.

cluster1::*> *network interface show -vserver Cluster*

          Logical       Status     Network            Current    Current Is
Vserver   Interface     Admin/Oper Address/Mask       Node       Port    Home
--------- ------------- ---------- ------------------ ---------- ------- ----
Cluster
          node1-01_clus1  up/up    169.254.209.69/16  node1-01   e7a     true
          node1-01_clus2  up/up    169.254.49.125/16  node1-01   e7b     true
          node1-02_clus1  up/up    169.254.47.194/16  node1-02   e7b     true
          node1-02_clus2  up/up    169.254.19.183/16  node1-02   e7a     true
          node1-03_clus1  up/up    169.254.209.69/16  node1-03   e7a     true
          node1-03_clus2  up/up    169.254.49.125/16  node1-03   e7b     true
          node1-04_clus1  up/up    169.254.47.194/16  node1-04   e7b     true
          node1-04_clus2  up/up    169.254.19.183/16  node1-04   e7a     false

8 entries were displayed.

cluster1::> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FLMXXXXXXXX)          Ethernet1/16/3    N9K-C9332D-GX2B
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/16/3    N9K-C9332D-GX2B
            e11a   cs1(FLMXXXXXXXX)          Ethernet1/16/4    N9K-C9332D-GX2B
            e11b   cs2(FDOXXXXXXXX)          Ethernet1/16/4    N9K-C9332D-GX2B
            e1a    cs1(FLMXXXXXXXX)          Ethernet1/16/1    N9K-C9332D-GX2B
            e1b    cs2(FDOXXXXXXXX)          Ethernet1/16/1    N9K-C9332D-GX2B
            .
            .
            .
            e7a    cs1(FLMXXXXXXXX)          Ethernet1/16/2    N9K-C9332D-GX2B
            e7b    cs2(FDOXXXXXXXX)          Ethernet1/16/2    N9K-C9332D-GX2B
.
.
.

cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID             Local Intrfce  Hldtme Capability  Platform          Port ID
newcs2(FDOXXXXXXXX)   Eth1/31        179    R S I s     N9K-C9364D-GX2A   Eth1/63
newcs2(FDOXXXXXXXX)   Eth1/32        179    R S I s     N9K-C9364D-GX2A   Eth1/64
node1-01              Eth1/4/1       123    H           AFX-1K            e1a
node1-01              Eth1/4/2       123    H           AFX-1K            e7a
node1-01              Eth1/4/3       123    H           AFX-1K            e10a
node1-01              Eth1/4/4       123    H           AFX-1K            e11a
node1-02              Eth1/9/1       138    H           AFX-1K            e1a
node1-02              Eth1/9/2       138    H           AFX-1K            e7a
node1-02              Eth1/9/3       138    H           AFX-1K            e10a
node1-02              Eth1/9/4       138    H           AFX-1K            e11a
node1-03              Eth1/15/1      138    H           AFX-1K            e1a
node1-03              Eth1/15/2      138    H           AFX-1K            e7a
node1-03              Eth1/15/3      138    H           AFX-1K            e10a
node1-03              Eth1/15/4      138    H           AFX-1K            e11a
node1-04              Eth1/16/1      173    H           AFX-1K            e1a
node1-04              Eth1/16/2      173    H           AFX-1K            e7a
node1-04              Eth1/16/3      173    H           AFX-1K            e10a
node1-04              Eth1/16/4      173    H           AFX-1K            e11a

Total entries displayed: 18


newcs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform          Port ID
cs1(FDOXXXXXXXX)   Eth1/31        179    R S I s     N9K-C9364D-GX2A   Eth1/63
cs1(FDOXXXXXXXX)   Eth1/32        179    R S I s     N9K-C9364D-GX2A   Eth1/64
node1-01           Eth1/4/1       123    H           AFX-1K            e1a
node1-01           Eth1/4/2       123    H           AFX-1K            e7a
node1-01           Eth1/4/3       123    H           AFX-1K            e10a
node1-01           Eth1/4/4       123    H           AFX-1K            e11a
node1-02           Eth1/9/1       138    H           AFX-1K            e1a
node1-02           Eth1/9/2       138    H           AFX-1K            e7a
node1-02           Eth1/9/3       138    H           AFX-1K            e10a
node1-02           Eth1/9/4       138    H           AFX-1K            e11a
node1-03           Eth1/15/1      138    H           AFX-1K            e1a
node1-03           Eth1/15/2      138    H           AFX-1K            e7a
node1-03           Eth1/15/3      138    H           AFX-1K            e10a
node1-03           Eth1/15/4      138    H           AFX-1K            e11a
node1-04           Eth1/16/1      173    H           AFX-1K            e1a
node1-04           Eth1/16/2      173    H           AFX-1K            e7a
node1-04           Eth1/16/3      173    H           AFX-1K            e10a
node1-04           Eth1/16/4      173    H           AFX-1K            e11a

Total entries displayed: 18
----
====


.. *HAポート*
+
... すべての HA ポートが正常な状態で稼働していることを確認します。
+
`ha interconnect status show -node <node-name>`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====


.. *ストレージポート*
+
... すべてのストレージ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage port show -port-type ENET
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-02
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-03
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
node1-04
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
16 entries were displayed.
----
====


.. *ストレージシェルフポート*
+
... すべてのストレージ シェルフ ポートが正常な状態で稼働していることを確認します。
+
[source, cli]
----
storage shelf port show
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.1
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false

16 entries were displayed.
----
====
... すべてのストレージ シェルフ ポートの接続ステータスを確認します。
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 CX9332D-cs1
1.1   1  connected       Ethernet1/15/1 CX9364D-cs1
1.1   2  connected       Ethernet1/17/2 CX9332D-cs1
1.1   3  connected       Ethernet1/15/2 CX9364D-cs1
1.1   4  connected       Ethernet1/17/3 CX9332D-cs1
1.1   5  connected       Ethernet1/15/3 CX9364D-cs1
1.1   6  connected       Ethernet1/17/4 CX9332D-cs1
1.1   7  connected       Ethernet1/15/4 CX9364D-cs1
1.1   8  connected       Ethernet1/19/1 CX9332D-cs1
1.1   9  connected       Ethernet1/17/1 CX9364D-cs1
1.1   10 connected       Ethernet1/19/2 CX9332D-cs1
1.1   11 connected       Ethernet1/17/2 CX9364D-cs1
1.1   12 connected       Ethernet1/19/3 CX9332D-cs1
1.1   13 connected       Ethernet1/17/3 CX9364D-cs1
1.1   14 connected       Ethernet1/19/4 CX9332D-cs1
1.1   15 connected       Ethernet1/17/4 CX9364D-cs1

16 entries were displayed.
----
====




. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.次の手順
スイッチを交換したら、link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを設定する"] 。
