---
permalink: switch-cisco-9332d-gx2b/setup-switch-9332d-cluster.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9332d-gx2b 
summary: Cisco Nexus 9332D-GX2B スイッチを設定するには、次の手順に従います。 
---
= 9332D-GX2Bスイッチを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9332D-GX2B スイッチを設定するには、次の手順に従います。

.開始する前に
以下のものを用意してください:

* スイッチの電源がオンになりました。
* 該当する NX-OS およびリファレンス コンフィギュレーション ファイル (RCF) リリースをダウンロードするために、インストール サイトの HTTP、FTP、または TFTP サーバーにアクセスします。
* 該当するNX-OSバージョンは、 https://software.cisco.com/download/home["Ciscoソフトウェアのダウンロード"^]ページ。


[IMPORTANT]
====
* NX-OS 10.4.2 は、 ONTAPクラスタ内のCisco Nexus 9332D-GX2B スイッチでサポートされている唯一のバージョンです。
* NX-OS バージョンをサポートされていないバージョンにアップグレードまたはダウングレードしないでください。現在サポートされているのは 10.4.2 のみです。


====
* 適用可能なライセンス、ネットワークおよび構成情報、およびケーブル。
* 適用可能なNetApp共有ネットワークおよび管理ネットワークRCFは、 NetAppサポートサイトからダウンロードできます。 http://mysupport.netapp.com/["mysupport.netapp.com"^] 。すべてのCisco共有ネットワーク スイッチおよび管理ネットワーク スイッチは、標準のCisco工場出荷時のデフォルト設定で出荷されます。これらのスイッチにも NX-OS ソフトウェアの最新バージョンが搭載されていますが、RCF はロードされていません。
* link:required-documentation-9332d-cluster.html["必要なスイッチとONTAPのドキュメント"] 。


.手順
. 共有ネットワーク スイッチの初期構成を実行します。
+
スイッチを初めて起動するときに、次の初期設定の質問に適切な回答を入力してください。サイトのセキュリティ ポリシーによって、有効にする応答とサービスが定義されます。

+
[cols="1,2"]
|===
| プロンプト | 応答 


 a| 
自動プロビジョニングを中止して通常のセットアップを続行しますか?  （はい/いいえ）
 a| 
「はい」と答えます。デフォルトは「いいえ」です。



 a| 
安全なパスワード標準を強制しますか?  （はい/いいえ）
 a| 
「はい」と答えます。デフォルトは「はい」です。



 a| 
管理者のパスワードを入力してください。
 a| 
デフォルトのパスワードは「`admin`」です。新しい強力なパスワードを作成する必要があります。弱いパスワードは拒否される可能性があります。



 a| 
基本設定ダイアログに入りますか?  （はい/いいえ）
 a| 
スイッチの初期設定では「*はい*」と応答します。



 a| 
別のログインアカウントを作成しますか?  （はい/いいえ）
 a| 
答えは、代替管理者に関するサイトのポリシーによって異なります。デフォルトは*いいえ*です。



 a| 
読み取り専用 SNMP コミュニティ文字列を構成しますか?  （はい/いいえ）
 a| 
「いいえ」と答えます。デフォルトは「いいえ」です。



 a| 
読み取り/書き込み SNMP コミュニティ文字列を構成しますか?  （はい/いいえ）
 a| 
「いいえ」と答えます。デフォルトは「いいえ」です。



 a| 
スイッチ名を入力します。
 a| 
スイッチ名を入力します。スイッチ名は 63 文字の英数字に制限されます。



 a| 
アウトオブバンド (mgmt0) 管理構成を続行しますか?  （はい/いいえ）
 a| 
そのプロンプトに対して「*yes*」（デフォルト）と応答します。  mgmt0 IPv4 アドレス: プロンプトで、IP アドレス ip_address を入力します。



 a| 
デフォルトゲートウェイを設定しますか?  （はい/いいえ）
 a| 
「はい」と答えます。  default-gateway: プロンプトの IPv4 アドレスに、default_gateway を入力します。



 a| 
高度な IP オプションを構成しますか?  （はい/いいえ）
 a| 
「いいえ」と答えます。デフォルトは「いいえ」です。



 a| 
Telnet サービスを有効にしますか?  （はい/いいえ）
 a| 
「いいえ」と答えます。デフォルトは「いいえ」です。



 a| 
SSH サービスを有効にしましたか?  （はい/いいえ）
 a| 
「はい」と答えます。デフォルトは「はい」です。


NOTE: ログ収集機能のために Ethernet Switch Health Monitor (CSHM) を使用する場合は、SSH が推奨されます。セキュリティを強化するには、SSHv2も推奨されます。



 a| 
生成する SSH キーのタイプ (dsa/rsa/rsa1) を入力します。
 a| 
デフォルトは *rsa* です。



 a| 
キービット数（1024～2048）を入力します。
 a| 
1024 から 2048 までのキー ビット数を入力します。



 a| 
NTP サーバーを設定しますか?  （はい/いいえ）
 a| 
「いいえ」と答えます。デフォルトは「いいえ」です。



 a| 
デフォルトのインターフェース層（L3/L2）を構成する
 a| 
*L2*で応答します。デフォルトは L2 です。



 a| 
デフォルトのスイッチポートインターフェース状態（shut/noshut）を設定する
 a| 
*noshut* と応答します。デフォルトは noshut です。



 a| 
CoPP システム プロファイルを構成する (厳密/中程度/寛容/高密度)
 a| 
*strict* で応答します。デフォルトは厳密です。



 a| 
設定を編集しますか?  （はい/いいえ）
 a| 
この時点で新しい構成が表示されるはずです。入力した設定を確認し、必要な変更を加えます。構成に満足している場合は、プロンプトに対して「*no*」と応答します。構成設定を編集する場合は、「はい」と答えてください。



 a| 
この設定を使用して保存しますか?  （はい/いいえ）
 a| 
設定を保存するには、「*はい*」と応答します。これにより、キックスタート イメージとシステム イメージが自動的に更新されます。


NOTE: この段階で設定を保存しないと、次回スイッチを再起動したときに変更は有効になりません。

|===
. セットアップの最後に表示される画面で選択した構成を確認し、必ず構成を保存してください。
. 共有ネットワークスイッチのバージョンを確認し、必要に応じて、 NetAppがサポートするバージョンのソフトウェアをスイッチにダウンロードします。 https://software.cisco.com/download/home["Ciscoソフトウェアのダウンロード"^]ページ。


.次の手順
スイッチの設定が完了したら、link:install-nxos-overview-9332d-cluster.html["NX-OSソフトウェアとRCFのインストールの準備"] 。
