---
permalink: switch-cisco-9336c-fx2/configure-software-overview-9336c-cluster.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Cisco Nexus 9336C-FX2クラスタスイッチのソフトウェア設定の概要 
---
= Cisco Nexus 9336C-FX2クラスタスイッチのソフトウェアインストールワークフロー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9336C-FX2スイッチのソフトウェアをインストールおよび設定するには、次の手順を実行します。

. link:install-nxos-overview-9336c-cluster.html["NX-OSソフトウェアとRCFをインストールするための準備をします"]。
. link:install-nxos-software-9336c-cluster.html["NX-OS ソフトウェアをインストールします"]。
. link:install-nxos-rcf-9336c-cluster.html["リファレンス構成ファイル（ RCF ）のインストール"]。
+
Nexus 9336C-FX2スイッチを初めてセットアップしたあとに、RCFをインストールします。この手順を使用して、 RCF のバージョンをアップグレードすることもできます。

+
.使用可能なRCF構成
次の表に、さまざまな構成で使用できるRCFを示します。使用している構成に該当するRCFを選択します。

+
特定のポートおよびVLANの使用方法の詳細については、RCFのバナーおよび重要な注意事項のセクションを参照してください。

+
[cols="1,2"]
|===
| RCF名 | 説明 


 a| 
2クラスタHA構成-ブレークアウト
 a| 
は、クラスタとHAの共有ポートを使用するノードを含め、8ノード以上で構成される2つのONTAPクラスタをサポートします。



 a| 
4クラスタHA構成（ブレークアウト）
 a| 
クラスタとHAの共有ポートを使用するノードを含め、4つ以上のノードで構成される4つのONTAPクラスタをサポートします。



 a| 
1-クラスタHA
 a| 
すべてのポートが40 / 100GbE用に構成されています。ポートで共有クラスタ/ HAトラフィックをサポートします。AFF A320、AFF A250、およびFAS500fシステムに必要です。また、すべてのポートを専用のクラスタポートとして使用できます。



 a| 
1-クラスタHA構成-ブレークアウト
 a| 
ポートは、10GbEブレークアウト×4、25GbEブレークアウト×4（100GbEスイッチではRCF 1.6+）、および40 / 100GbE用に構成されています。共有クラスタ/ HAポートを使用するノード（AFF A320、AFF A250、およびFAS500fシステム）のポートでクラスタ/ HAトラフィックの共有をサポートします。また、すべてのポートを専用のクラスタポートとして使用できます。



 a| 
クラスタHAストレージ
 a| 
ポートは、クラスタ+ HAの場合は40 / 100GbE、クラスタの場合は4×10GbEブレークアウト、クラスタ+ HAの場合は4×25GbEブレークアウト、ストレージHAペアごとに100GbE用に構成されます。



 a| 
クラスタ
 a| 
4x10GbEポート（ブレークアウト）と40/100GbEポートの割り当てが異なる2種類のRCFAFF A320、AFF A250、FAS500fシステムを除く、すべてのFAS / AFFノードがサポートされます。



 a| 
ストレージ
 a| 
すべてのポートが100GbE NVMeストレージ接続用に設定されています。

|===

