---
permalink: switch-cisco-9336c-fx2/configure-software-overview-9336c-cluster.html 
sidebar: sidebar 
keywords: switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Cisco Nexus 9336C-FX2クラスタスイッチのソフトウェア設定の概要 
---
= Cisco Nexus 9336C-FX2クラスタスイッチのソフトウェアインストールワークフロー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9336C-FX2スイッチ用のソフトウェアをインストールおよび設定し、リファレンス構成ファイル（RCF）をインストールまたはアップグレードする手順は、次のとおりです。

. link:install-nxos-overview-9336c-cluster.html["NX-OSソフトウェアとRCFのインストールの準備"]です。
+
Cisco NX-OSソフトウェアとリファレンス構成ファイル（RCF）をCisco Nexus 9336C-FX2クラスタスイッチにインストールする必要があります。

. link:install-nxos-software-9336c-cluster.html["NX-OSソフトウェアのインストールまたはアップグレード"]です。
+
Cisco Nexus 9336C-FX2クラスタスイッチでNX-OSソフトウェアをダウンロードし、インストールまたはアップグレードします。

. link:install-nxos-rcf-9336c-cluster.html["RCFのインストールまたはアップグレード"]です。
+
Cisco Nexus 9336C-FX2スイッチの初回セットアップ後にRCFをインストールまたはアップグレードします。この手順を使用して、 RCF のバージョンをアップグレードすることもできます。

. link:configure-ssh-keys.html["Nexus 9336C-FX2クラスタスイッチのSSH設定の確認"]です。
+
イーサネットスイッチヘルスモニタ（CSHM）およびログ収集機能を使用する場合は、スイッチでSSHが有効になっていることを確認します。


