---
permalink: switch-cisco-9336c-fx2/install-upgrade-rcf-overview-cluster.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9336c-fx2 
summary: クラスタスイッチヘルスモニタ（ CSHM ）およびログ収集機能を使用する場合、 SSH は要件です。Cisco 9336c-FX2クラスタスイッチでSSHを有効にするには、まずSSHキーを生成してからSSHを有効にします。 
---
= リファレンス構成ファイル（RCF）のインストールまたはアップグレードの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nexus 9336C-FX2 および 9336C-FX2-T スイッチを初めてセットアップした後、リファレンス コンフィギュレーション ファイル (RCF) をインストールします。スイッチに既存のバージョンの RCF ファイルがインストールされている場合は、RCF バージョンをアップグレードします。

RCFをインストールまたはアップグレードする場合の詳細については、技術情報アーティクルを参照してlink:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["リモート接続を維持したままCiscoインターコネクトスイッチの設定をクリアする方法"^]ください。

.使用可能なRCF構成
次の表に、さまざまな構成で使用できるRCFを示します。使用している構成に該当するRCFを選択します。

特定のポートおよびVLANの使用方法の詳細については、RCFのバナーおよび重要な注意事項のセクションを参照してください。

[cols="1,2"]
|===
| RCF名 | 説明 


 a| 
2クラスタHA構成-ブレークアウト
 a| 
は、クラスタとHAの共有ポートを使用するノードを含め、8ノード以上で構成される2つのONTAPクラスタをサポートします。



 a| 
4クラスタHA構成（ブレークアウト）
 a| 
クラスタとHAの共有ポートを使用するノードを含め、4つ以上のノードで構成される4つのONTAPクラスタをサポートします。



 a| 
1-クラスタHA
 a| 
すべてのポートが40 / 100GbE用に構成されています。ポートで共有クラスタ/ HAトラフィックをサポートします。AFF A320、AFF A250、およびFAS500fシステムに必要です。また、すべてのポートを専用のクラスタポートとして使用できます。



 a| 
1-クラスタHA構成-ブレークアウト
 a| 
ポートは、10GbEブレークアウト×4、25GbEブレークアウト×4（100GbEスイッチではRCF 1.6+）、および40 / 100GbE用に構成されています。共有クラスタ/ HAポートを使用するノード（AFF A320、AFF A250、およびFAS500fシステム）のポートでクラスタ/ HAトラフィックの共有をサポートします。また、すべてのポートを専用のクラスタポートとして使用できます。



 a| 
クラスタHAストレージ
 a| 
ポートは、クラスタ+ HAでは40 / 100GbE、クラスタでは4×10GbEブレークアウト、クラスタ+ HAでは4×25GbEブレークアウト、ストレージHAペアごとに100GbE用に構成されます。



 a| 
クラスタ
 a| 
4x10GbEポート（ブレークアウト）と40/100GbEポートの割り当てが異なる2種類のRCFAFF A320、AFF A250、FAS500fシステムを除く、すべてのFAS / AFFノードがサポートされます。



 a| 
ストレージ
 a| 
すべてのポートが100GbE NVMeストレージ接続用に設定されています。

|===
.推奨されるドキュメント
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネットスイッチ（NSS）"^]
+
NetApp Support SiteでサポートされているONTAPとRCFのバージョンについては、スイッチの互換性の表を参照してください。RCFのコマンド構文と特定のバージョンのNX-OSの構文との間には、コマンドの依存関係が存在することに注意してください。

* link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000 シリーズスイッチ"^]
+
Ciscoスイッチのアップグレードおよびダウングレード手順の完全なマニュアルについては、シスコのWebサイトで入手可能な該当するソフトウェアおよびアップグレードガイドを参照してください。



.例について
この手順の例では、スイッチとノードで次の命名法を使用しています。

* 2つのCiscoスイッチの名前は* CS1 *および* CS2 *です。
* ノード名は* cluster1-01 *、* cluster1-02 *、* cluster1-03 *、および* cluster1-04 *です。
* クラスタLIFの名前は、* cluster1-01_clus1 *、* cluster1-01_clus2 *、* cluster1-02_clus1 *、* cluster1-02_clus2 *、* cluster1-03_clus2 *、* cluster1-03_clus2 *、* cluster1-04_clus1 *、および* cluster1-04_clus2 *です。
* 「 cluster1 ：： * > 」プロンプトは、クラスタの名前を示します。


この手順 の例では 4 ノードを使用します。これらのノードは、2つの10GbEクラスタインターコネクトポート* e0a *と* e0b *を使用します。を参照し https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^]て、プラットフォームのクラスタポートが正しいことを確認します。


NOTE: コマンド出力は、 ONTAP のリリースによって異なる場合があります。

使用可能なRCF構成の詳細については、を参照してください。 link:configure-software-overview-9336c-cluster.html["ソフトウェアのインストールワークフロー"]。

.使用するコマンド
手順では、 ONTAP コマンドと Cisco Nexus 9000 シリーズスイッチコマンドの両方を使用する必要があります。特に明記されていないかぎり、 ONTAP コマンドを使用します。

.次の手順
RCFのインストールまたはRCFのアップグレード手順を確認した後、link:install-rcf-software-9336c-cluster.html["RCFをインストールする"]またはlink:upgrade-rcf-software-9336c-cluster.html["RCFをアップグレードする"]必要に応じて。
