---
permalink: switch-cisco-9336c-fx2/setup-switch-9336c-cluster.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: Cisco Nexus 9336C-FX2スイッチをセットアップおよび設定するには、次の手順 に従います。 
---
= 9336C-FX2クラスタスイッチを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9336C-FX2スイッチを設定するには、次の手順 に従います。

.必要なもの
* インストールサイトのHTTPサーバ、FTPサーバ、またはTFTPサーバにアクセスし、該当するNX-OSおよびRCFリリースをダウンロードします。
* 該当するライセンス、ネットワークおよび設定情報、ケーブル。
* 完了しました link:setup-worksheet-9336c-cluster.html["ケーブル接続ワークシート"]。
* 該当するネットアップクラスタネットワークと管理ネットワークのRCFをNetApp Support Site からダウンロードしました http://mysupport.netapp.com/["mysupport.netapp.com"^]。すべての Cisco クラスタネットワークスイッチおよび管理ネットワークスイッチは、シスコの工場出荷時のデフォルト設定で出荷されます。これらのスイッチには、 NX-OS ソフトウェアの最新バージョンもありますが、 RCF はロードされていません。
* link:required-documentation-9336c-cluster.html["必要なスイッチとONTAP のドキュメント"]。


.手順
. クラスタネットワークスイッチの初期設定を実行する。
+
スイッチの初回ブート時に、次の初期セットアップに関する質問に適切な回答を入力します。サイトのセキュリティポリシーでは、有効にする応答とサービスを定義しています。

+
[cols="1,2"]
|===
| プロンプト | 応答 


 a| 
自動プロビジョニングを中止して通常のセットアップを続行しますか？（はい / いいえ）
 a| 
* yes * と応答します。デフォルトは no です



 a| 
セキュアなパスワード標準を適用しますか？（はい / いいえ）
 a| 
* yes * と応答します。デフォルトは yes です。



 a| 
admin のパスワードを入力します。
 a| 
デフォルトのパスワードは「 admin 」です。新しい強力なパスワードを作成する必要があります。脆弱なパスワードは拒否される可能性があります。



 a| 
基本設定ダイアログを開きますか？（はい / いいえ）
 a| 
スイッチの初期設定時に * yes * と応答します。



 a| 
別のログインアカウントを作成しますか？（はい / いいえ）
 a| 
回答は、代替管理者に関するサイトのポリシーに依存します。デフォルトは * no * です。



 a| 
読み取り専用の SNMP コミュニティストリングを設定しますか？（はい / いいえ）
 a| 
* no * と応答します。デフォルトは no です



 a| 
読み取り / 書き込み SNMP コミュニティストリングを設定しますか？（はい / いいえ）
 a| 
* no * と応答します。デフォルトは no です



 a| 
スイッチ名を入力します。
 a| 
スイッチ名を63文字以内の英数字で入力します。



 a| 
アウトオブバンド（ mgmt0 ）管理構成で続行しますか。（はい / いいえ）
 a| 
そのプロンプトで * yes * （デフォルト）と応答します。mgmt0 IPv4 address: プロンプトで、 IP アドレス ip_address を入力します



 a| 
default-gateway を設定？（はい / いいえ）
 a| 
* yes * と応答します。default-gateway: プロンプトの IPv4 アドレスに、 default_gateway と入力します。



 a| 
IP の詳細オプションを設定しますか？（はい / いいえ）
 a| 
* no * と応答します。デフォルトは no です



 a| 
Telnet サービスを有効にしますか？（はい / いいえ）
 a| 
* no * と応答します。デフォルトは no です



 a| 
SSH サービスを有効にしたか？（はい / いいえ）
 a| 
* yes * と応答します。デフォルトは yes です。


NOTE: ログ収集機能にクラスタスイッチヘルスモニタ（ CSHM ）を使用する場合は、 SSH が推奨されます。セキュリティを強化するには、 SSHv2 も推奨されます。



 a| 
生成する SSH キーのタイプを入力します（ DSA/RSA/rsa1 ）。
 a| 
デフォルトは * rsa* です。



 a| 
キービット数（ 1024~2048 ）を入力します。
 a| 
1024～2048のキービット数を入力します。



 a| 
NTP サーバを設定？（はい / いいえ）
 a| 
* no * と応答します。デフォルトは no です



 a| 
デフォルトのインターフェイスレイヤの設定（L3/L2）
 a| 
* L2 * と応答します。デフォルトは L2 です。



 a| 
デフォルトのスイッチポートインターフェイスステートの設定（shut / noshut）
 a| 
noshut * と応答します。デフォルトは noshut です。



 a| 
CoPPシステムプロファイルの設定（strict/moderm/lenenter/dense）
 a| 
* strict * と応答します。デフォルトは strict です。



 a| 
設定を編集しますか？（はい / いいえ）
 a| 
この時点で新しい設定が表示されます。入力した設定を確認し、必要な変更を行います。設定に問題がなければ、プロンプトで「 * no * 」と応答します。設定を編集する場合は、 * yes * と応答します。



 a| 
この設定を使用して保存しますか？（はい / いいえ）
 a| 
* yes * と応答して、設定を保存します。これにより、キックスタートイメージとシステムイメージが自動的に更新されます。


NOTE: この段階で設定を保存しないと、次回スイッチをリブートしたときに変更が有効になりません。

|===
. セットアップの最後に表示される画面で選択した設定を確認し、設定を保存します。
. クラスタネットワークスイッチのバージョンを確認し、必要に応じてネットアップ対応バージョンのソフトウェアをスイッチにダウンロードします。
+
ネットアップ対応バージョンのサポートソフトウェアをダウンロードする場合は、 _NetApp Cluster Network Switch Reference Configuration File_ もダウンロードし、手順 5 で保存した構成とマージする必要があります。ファイルと手順は、からダウンロードできます https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco イーサネットスイッチ"^] ページ

. ネットワークスイッチのソフトウェアバージョンを確認し、必要に応じてネットアップ対応バージョンのソフトウェアをスイッチにダウンロードします。独自のスイッチがある場合は、を参照してください https://cisco.com["シスコサイト"^]。
+
ネットアップ対応バージョンのサポートソフトウェアをダウンロードする場合は、_NetApp Management Network Switch Reference Configuration File_もダウンロードし、以前に保存した構成とマージする必要があります。ファイルと手順は、からダウンロードできます https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco イーサネットスイッチ"^] ページ



.次の手順
必要に応じて、を実行できます link:install-switch-and-passthrough-panel-9336c-cluster.html["Cisco Nexus 9336C-FX2スイッチをネットアップキャビネットに設置します"]。それ以外の場合は、に進みます link:install-nxos-overview-9336c-cluster.html["NX-OSおよびRCFのインストールを準備します"]。
