---
permalink: switch-cisco-9336c-fx2/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, nexus, ontap, install the cluster switch health monitor (csm) configuration file for 92300yc switches - cisco nexus 9336c-fx2' 
summary: この手順を使用して、Nexus 92300YC クラスタ スイッチのクラスタ スイッチ ヘルス モニタリングに適した構成ファイルをインストールできます。 
---
= クラスタスイッチヘルスモニタ（SHM）構成ファイルをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nexus 9336C-FX2 クラスタ スイッチのクラスタ スイッチ ヘルス モニタリング (SHM) に適した構成ファイルをインストールするには、次の手順に従います。

.要件
9336C-FX2 クラスタ スイッチの SHM を設定する前に、 ONTAPクラスタが起動して実行されていることを確認してください。


NOTE: SHM で利用可能なすべての機能を使用するには、SSH も有効にする必要があります。

.手順
. 対応するONTAPリリース バージョンに基づいて、クラスタ SHM 構成 zip ファイルをダウンロードします。このファイルは、 https://mysupport.netapp.com/NOW/cgi-bin/software/["NetAppソフトウェアのダウンロード"^]ページ。
+
.. ソフトウェアダウンロードページで、*スイッチヘルスモニター設定ファイル*を選択します。
.. プラットフォーム = * ONTAP* を選択し、* Go! * を選択します。
.. ONTAPのスイッチヘルスモニタ設定ファイルページで、*表示とダウンロード*を選択します。
.. ONTAPのスイッチヘルスモニタ設定ファイル > 説明ページで、該当するクラスタスイッチモデルの*ダウンロード*を選択します（例：* Cisco Nexus 9336C-FX2*）。
.. エンドユーザー使用許諾契約書ページで、「同意する」を選択します。
.. ONTAPのスイッチヘルスモニタ設定ファイル > ダウンロードページで、該当する設定ファイル（例：*Cisco_Nexus_9336C-FX2.zip*）を選択します。


. 該当するzipファイルを、IPアドレスがXXXXである社内Webサーバーにアップロードします。
+
内部 Web サーバーの IP アドレスが 192.168.2.20 で、/usr/download ディレクトリが存在すると仮定すると、scp を使用して zip ファイルを Web サーバーにアップロードできます。

+
[listing]
----
% scp Cisco_Nexus_9336C-FX2.zip admin@192.168.2.20:/usr/download/Cisco_Nexus_9336C-FX2.zip
----
. クラスタ内のいずれかのONTAPシステムから詳細モード設定にアクセスします。
+
`set-privilege advanced`

+
[listing]
----
cluster1::> set -privilege advanced
----
. スイッチヘルスモニターの設定コマンドを実行する `system cluster-switch configure-health-monitor -node * -package-url X.X.X.X/location_to_download_zip_file`:
+
[listing]
----
cluster1::> system cluster-switch configure-health-monitor -node * -package-url 192.168.2.20/usr/download/Cisco_Nexus_9336C-FX2.zip
----
. コマンド出力に「ダウンロードされたパッケージが正常に処理されました」というテキスト文字列が含まれていることを確認します。エラーが発生した場合は、NetAppサポートにお問い合わせください。
. コマンドを実行する `system cluster-switch show`ONTAPシステムで、監視対象フィールドが「True」に設定された状態でクラスタ スイッチが検出されていることを確認します。
+
[listing]
----
cluster1::> system cluster-switch show
----
+

NOTE: いつでもONTAPの以前のバージョンに戻す場合は、9336C-FX2 クラスタ スイッチの SHM を有効にするために、SHM 構成ファイルを再度インストールする必要があります。


