---
permalink: switch-bes-53248/configure-health-monitor.html 
sidebar: sidebar 
keywords: CSHM,initial setup,configuration file,cshm,enable SSH 
summary: この手順を使用して、 BES-53248 クラスタスイッチのクラスタスイッチヘルスモニタに適用可能な構成ファイルをインストールできます。ONTAP リリース 9.5P7 以前および 9.6P2 以前では、クラスタスイッチヘルスモニタの構成ファイルを個別にダウンロードする必要があります。ONTAP リリース 9.5P8 以降、 9.6P3 以降、および 9.7 以降では、クラスタスイッチヘルスモニタの構成ファイルが ONTAP にバンドルされています。 
---
= クラスタスイッチヘルスモニタ（ CSHM ）構成ファイルをインストールします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この手順を使用して、 BES-53248 クラスタスイッチのクラスタスイッチヘルスモニタに適用可能な構成ファイルをインストールできます。ONTAP リリース 9.5P7 以前および 9.6P2 以前では、クラスタスイッチヘルスモニタの構成ファイルを個別にダウンロードする必要があります。ONTAP リリース 9.5P8 以降、 9.6P3 以降、および 9.7 以降では、クラスタスイッチヘルスモニタの構成ファイルが ONTAP にバンドルされています。

BES-53248 クラスタスイッチのスイッチヘルスモニタを設定する前に、 ONTAP クラスタが稼働していることを確認する必要があります。


NOTE: CSHM で利用可能なすべての機能を使用するには、 SSH を有効にすることを推奨します。

.手順
. 対応する ONTAP リリースバージョンに基づいて、クラスタスイッチヘルスモニタ構成の zip ファイルをダウンロードします。このファイルは、次のページから入手できます。 https://mysupport.netapp.com/NOW/cgi-bin/software/["ネットアップソフトウェアのダウンロード"^]
+
.. ソフトウェアのダウンロードページで、 * スイッチヘルスモニタ構成ファイル * を選択します
.. Platform = * ONTAP * を選択し、 * Go ！ * をクリックします
.. Switch Health Monitor Configuration Files for ONTAP ページで、 * View & Download * をクリックします
.. Switch Health Monitor Configuration Files for ONTAP - 概要ページで、該当するクラスタスイッチモデルの * Download * をクリックします（例： * Broadcom-supported BES-53248 * ）
.. [End User License Agreement] ページで、 [*Accept*] をクリックします
.. Switch Health Monitor Configuration Files for ONTAP - Download ページで、適切な構成ファイル（例： * Broadcom_BES-53248 .zip * ）を選択します


. IP アドレスが X.X.X.X.X の内部 Web サーバに、該当する zip ファイルをアップロードします
+
内部 Web サーバの IP アドレスが 192.168.2.20 であり、 /usr/download ディレクトリが存在する場合は、 scp を使用して zip ファイルを Web サーバにアップロードできます。

+
[listing, subs="+quotes"]
----
% *scp Broadcom_BES-53248.zip admin@192.168.2.20:/usr/download/Broadcom_BES-53248.zip*
----
. コマンド「 set -privilege advanced 」を使用して、クラスタ内のいずれかの ONTAP システムから advanced モード設定にアクセスします。
+
[listing, subs="+quotes"]
----
cluster1::> *set -privilege advanced*
----
. スイッチヘルスモニタ設定コマンド「 system cluster-switch configure -health-monitor -node * -package url 」 http://server/file-location`: を実行します
+
[listing, subs="+quotes"]
----
cluster1::> *system cluster-switch configure-health-monitor -node * -package-url
http://192.168.2.20/usr/download/Broadcom_BES-53248.zip*
----
. コマンド出力に、ダウンロードされたパッケージが正常に処理されたことを示すテキスト文字列が含まれていることを確認します。エラーが発生した場合は、ネットアップサポートにお問い合わせください。
. ONTAP システムで「 system cluster-switch show 」コマンドを実行し、監視対象フィールドが「 True 」に設定された状態でクラスタスイッチが検出されたことを確認します。
+
[listing, subs="+quotes"]
----
cluster1::> *system cluster-switch show*
----
+

NOTE: 以前のバージョンの ONTAP に戻す場合は、 CSHM 構成ファイルを再度インストールして、 BES-53248 クラスタスイッチのスイッチヘルスモニタを有効にする必要があります。


