---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: この手順を使用して、 BES-53248 クラスタスイッチに EFOS ソフトウェアをインストールできます。クラスタスイッチに対応する Broadcom EFOS ソフトウェアを Broadcom イーサネットスイッチサポートサイトからダウンロードできます。 
---
= EFOS ソフトウェアをインストールします
:icons: font
:imagesdir: ../media/


[role="lead"]
この手順を使用して、 BES-53248 クラスタスイッチに EFOS ソフトウェアをインストールできます。クラスタスイッチに対応する Broadcom EFOS ソフトウェアを Broadcom イーサネットスイッチサポートサイトからダウンロードできます。

.手順
. BES-53248 クラスタスイッチを管理ネットワークに接続します。
. 「 ping 」コマンドを使用して、 EFOS 、ライセンス、 RCF ファイルをホストするサーバへの接続を確認します。
+
次の例では、スイッチが IP アドレス 172.19.2.1 のサーバに接続されていることを確認します。

+
[listing]
----
(cs2) # **ping 172.19.2.1**
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. cs2 で現在アクティブなイメージをバックアップします。
+
'How bootvar'

+
[listing]
----
(cs2) # **show bootvar**

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------

    1      3.4.3.3     Q.10.22.1     3.4.3.3           3.4.3.3
(cs2) # **copy active backup**
Copying active to backup
Management access will be blocked for the duration of the operation
Copy operation successful

(cs2) # **show bootvar**

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------

    1      3.4.3.3     3.4.3.3     3.4.3.3           3.4.3.3
(cs2) #
----
. 実行中の EFOS ソフトウェアのバージョンを確認します。
+
'how version （バージョンの表示） '

+
[listing]
----
(cs2) # **show version**

Switch: 1

System Description............................. Quanta IX8-B 48x25GB SFP 8x100GB QSFP, 3.4.3.3, Linux 4.4.117-ceeeb99d, 2016.05.00.04
Machine Type................................... Quanta IX8-B 48x25GB SFP 8x100GB QSFP
Machine Model.................................. IX8-B
Serial Number.................................. QTFCU38260014
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:12:3D
Software Version............................... 3.4.3.3
Operating System............................... Linux 4.4.117-ceeeb99d
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
. スイッチにイメージファイルをダウンロードします。
+
イメージファイルをアクティブイメージにコピーすると、リブート時にそのイメージによって実行中の EFOS バージョンが確立されます。以前のイメージはバックアップとして使用できます。

+
[listing]
----
(cs2) # **copy sftp://root@172.19.2.1//tmp/EFOS-3.4.4.6.stk active**
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.4.4.6.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) **y**
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. アクティブ構成とバックアップ構成のブートイメージを表示します。
+
'How bootvar'

+
[listing]
----
(cs2) # **show bootvar**

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     3.4.3.3     3.4.3.3            3.4.3.3            3.4.4.6
----
. スイッチをリブートします。
+
「再ロード」

+
[listing]
----
(cs2) # **reload**

The system has unsaved changes.
Would you like to save them now? (y/n) **y**

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
. 再度ログインして、新しいバージョンの EFOS ソフトウェアを確認します。
+
'how version （バージョンの表示） '

+
[listing]
----
(cs2) # **show version**

Switch: 1

System Description............................. x86_64-quanta_common_rglbmc-r0, 3.4.4.6, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... x86_64-quanta_common_rglbmc-r0
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.4.4.6
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----


* 関連情報 *

https://www.broadcom.com/support/bes-switch["Broadcom Ethernet Switch のサポート"]
