---
permalink: switch-bes-53248/configure-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: クラスタスイッチヘルスモニタログ収集機能は、 ONTAP でスイッチ関連のログファイルを収集するために使用します。ここで説明するように、 BES-53248 クラスタスイッチ CLI を使用して環境をセットアップしておく必要があります。 
---
= クラスタスイッチのログ収集機能を設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタスイッチヘルスモニタログ収集機能は、 ONTAP でスイッチ関連のログファイルを収集するために使用します。ここで説明するように、 BES-53248 クラスタスイッチ CLI を使用して環境をセットアップしておく必要があります。

.手順
. ONTAP 9.8 以降では、次のコマンドを使用して、クラスタスイッチヘルスモニタログ収集機能を有効にして、スイッチ関連のログファイルを収集します。
+
'system switch ethernet log setup-password 'および'system switch ethernet log enable-colion

+
「 system switch ethernet log setup -password 」と入力します

+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
+
次に 'system switch ethernet log enable-colion' を実行します

+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
. ONTAP 9.5P15 、 9.6P11 、 9.7P8 、およびそれ以降のパッチリリースでは、次のコマンドを使用して、スイッチ関連のログファイルを収集するためのクラスタスイッチヘルスモニタログ収集機能を有効にします。
+
'system cluster-switch log setup-password ' および 'system cluster-switch log enable-collection

+
「 system cluster-switch log setup -password 」と入力します

+
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
+
次に 'system cluster-switch log enable-collection' を指定します

+
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.
----



NOTE: 現時点では、log collectコマンドは使用できません。を参照してください link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1225042["バグ1225042"^] を参照してください。


CAUTION: これらのコマンドのいずれかでエラーが返される場合は、ネットアップサポートにお問い合わせください。
