---
permalink: switch-bes-53248/configure-reqs-bes53248.html 
sidebar: sidebar 
keywords: bes, cluster, switch, port, assignment, table, configure, bes-53428 cluster switch port assignments - bes-53428 switches 
summary: BES-53248 クラスタスイッチポート割り当て表を参考にして、クラスタを設定できます。 
---
= BES-53248クラスタスイッチの構成要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248スイッチの設置とメンテナンスについては、EFOSとONTAP のサポートと設定の要件を確認してください。



== EFOSとONTAP のサポート

を参照してください https://["NetApp Hardware Universe の略"^] および https://["Broadcomスイッチの互換性マトリックス"^] BES-53248スイッチとのEFOSおよびONTAP の互換性情報については、を参照してください。EFOSとONTAP のサポートは、BES-53248スイッチのマシンタイプによって異なります。すべてのBES-52348スイッチマシンタイプの詳細については、を参照してください link:components-bes53248.html["BES-53248クラスタスイッチのコンポーネントとパーツ番号"]。



== 設定要件

クラスタを設定するには、クラスタスイッチに適切な数とタイプのケーブルとコネクタが必要です。最初に設定するクラスタスイッチのタイプに応じて、付属のコンソールケーブルを使用してスイッチのコンソールポートに接続する必要があります。



=== クラスタスイッチのポート割り当て

Broadcom対応BES-53248クラスタスイッチポート割り当て表を参考にして、クラスタを設定できます。

[cols="1,2"]
|===
| スイッチポート | 使用するポート 


 a| 
01-16
 a| 
10 / 25GbEクラスタポートノード、基本設定



 a| 
17-48
 a| 
10 / 25GbEクラスタポートノード、ライセンスあり



 a| 
49-54
 a| 
40 / 100GbEクラスタポートノード（ライセンスあり）を右から左に追加



 a| 
55～56
 a| 
100GbE クラスタスイッチ間リンク（ ISL ）ポート、基本設定

|===
を参照してください https://["Hardware Universe"] スイッチポートの詳細については、を参照してください。



=== ポートグループの速度制限

* BES-53248クラスタスイッチでは、48個の10 / 25GbE（SFP28 / SFP+）ポートが12個の4ポートグループに結合されます。ポート1~4、5 ~ 8、9 ~ 12、13 ~ 16、17 ~ 20、21～24、25～28、29～32、33～36、37～40、41-44および45-48。
* SFP28 / SFP+ ポート速度は、 4 ポートグループのすべてのポートで同じ（ 10GbE または 25GbE ）でなければなりません。




=== その他の要件

* 追加のライセンスを購入する場合は、を参照してください link:configure-licenses.html["新しいライセンスポートをアクティブ化します"] を参照してください。
* SSHがアクティブな場合は、コマンドの実行後にSSHを手動で再度有効にする必要があります `erase startup-config` スイッチを再起動します。

