---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: 次の手順に従って、BES-53248クラスタスイッチにイーサネットファブリックOS（EFOS）ソフトウェアをインストールします。 
---
= EFOS ソフトウェアをインストールします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の手順に従って、BES-53248クラスタスイッチにイーサネットファブリックOS（EFOS）ソフトウェアをインストールします。

EFOSソフトウェアには、イーサネットシステムおよびIPインフラシステムを開発するための高度なネットワーク機能とプロトコルのセットが含まれています。このソフトウェアアーキテクチャは、パケットの検査や分離を完全に行う必要があるアプリケーションを使用するあらゆるネットワーク組織のデバイスに適しています。



== 設置を準備

.作業を開始する前に
* この手順は新規インストールにのみ適しています。
* クラスタスイッチに対応するBroadcom EFOSソフトウェアをからダウンロードします https://www.broadcom.com/support/bes-switch["Broadcom Ethernet Switch のサポート"^] サイト
* を確認します。 link:configure-install-initial.html["BES-53248クラスタスイッチが設定されている"]。




== ソフトウェアをインストールします

次のいずれかの方法を使用してEFOSソフトウェアをインストールします。

* <<方法1：EFOSをインストールする>>。ほとんどの場合に使用します。
* <<方法2：ONIEモードでEFOSをインストールする>>。一方のEFOSバージョンがFIPSに準拠しており、もう一方のEFOSバージョンがFIPSに準拠していない場合に使用します。




=== 方法1：EFOSをインストールする

EFOSソフトウェアをインストールするには、次の手順を実行します。

.手順
. スイッチのシリアルコンソールポートにログインするか、SSHで接続します。
. 「 ping 」コマンドを使用して、 EFOS 、ライセンス、 RCF ファイルをホストするサーバへの接続を確認します。
+
.例を示します
[%collapsible]
====
次の例では、スイッチが IP アドレス 172.19.2.1 のサーバに接続されていることを確認します。

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. スイッチにイメージファイルをダウンロードします。
+
サポートされているコピープロトコルについては、次の表を参照してください。

+
|===


| *プロトコル* | *前提条件* 


 a| 
Trivial File Transfer Protocol（TFTP；簡易ファイル転送プロトコル）
 a| 
なし



 a| 
SSH File Transfer Protocol（SFTP；ファイル転送プロトコル）
 a| 
ソフトウェアパッケージがセキュアな管理をサポートしている必要がある



 a| 
FTP
 a| 
パスワードは必須です



 a| 
Xmodem
 a| 
なし



 a| 
Yモデム
 a| 
なし



 a| 
Zmodem
 a| 
なし



 a| 
Secure Copy Protocol（SCP）
 a| 
ソフトウェアパッケージがセキュアな管理をサポートしている必要がある



 a| 
HTTP
 a| 
ネイティブのwgetユーティリティが使用可能な場合、選択したプラットフォームでCLIベースのファイル転送がサポートされる



 a| 
HTTPS
 a| 
ネイティブのwgetユーティリティが使用可能な場合、選択したプラットフォームでCLIベースのファイル転送がサポートされる

|===
+
イメージファイルをアクティブイメージにコピーすると、リブート時にそのイメージによって実行中の EFOS バージョンが確立されます。以前のイメージはバックアップとして使用できます。

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. アクティブ構成とバックアップ構成のブートイメージを表示します。
+
'How bootvar'

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. スイッチをリブートします。
+
「再ロード」

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
====
. 再度ログインして、新しいバージョンの EFOS ソフトウェアを確認します。
+
'how version （バージョンの表示） '

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. インストールを完了します。
スイッチを再設定するには、次の5つの手順を実行します。
+
.. link:configure-licenses.html["ライセンスをインストール"]
.. link:configure-install-rcf.html["RCFファイルをインストールする"]
.. link:configure-ssh.html["SSH を有効にします。"]
.. link:CSHM_log_collection.html["ログ収集を有効にします"]
.. link:CSHM_snmpv3.html["監視のためのSNMPv3の設定"]


. パートナースイッチで手順1~7を繰り返します。




=== 方法2：ONIEモードでEFOSをインストールする

一方の EFOS バージョンが FIPS に準拠していて、もう一方の EFOS バージョンが FIPS に準拠していない場合は、次の手順を実行できます。次の手順は、スイッチがブートに失敗した場合に、 ONIE から FIPS 非準拠または FIPS 準拠の EFOS 3.x.x イメージをインストールするために使用できます。

.手順
. スイッチのシリアルポートに接続されているコンソールに接続します。
. スイッチを ONIE インストールモードで起動します。
+
起動中に、プロンプトが表示されたらONIEを選択します。

+
.例を示します
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
*ONIE*を選択すると、スイッチがロードされ、いくつかの選択肢が表示されます。「OSのインストール」を選択します。

+
.例を示します
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
スイッチがONIEインストールモードで起動します。

. ONIE の検出を停止し、イーサネットインターフェイスを設定します。
+
次のメッセージが表示されたら、*Enter*キーを押してONIEコンソールを起動します。

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIEの検出が続行され、メッセージがコンソールに出力されます。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. スイッチ管理ポートのイーサネットインターフェイスを設定し、次のコマンドを使用してルートを追加します。 `ifconfig eth0 <ipAddress> netmask <netmask> up` および `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. ONIE インストールファイルをホストしているサーバにアクセスできることを確認します。
+
`ping`

+
.例を示します
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. 新しいスイッチソフトウェアをインストールします。
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.例を示します
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
ソフトウェアがインストールされ、スイッチがリブートされます。スイッチを通常どおりにリブートして新しい EFOS バージョンにします。

. ログインし、新しいスイッチソフトウェアがインストールされたことを確認します。
+
'How bootvar'

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
 1      3.7.0.4     3.7.0.4    3.7.0.4        3.10.0.3
(cs2) #
----
====
. インストールを完了します。
設定を適用せずにスイッチがリブートし、工場出荷時のデフォルトにリセットされます。スイッチを再設定するには、次の6つの手順を実行します。
+
.. link:configure-install-initial.html["スイッチを設定します"]
.. link:configure-licenses.html["ライセンスをインストール"]
.. link:configure-install-rcf.html["RCFファイルをインストールする"]
.. link:configure-ssh.html["SSH を有効にします。"]
.. link:CSHM_log_collection.html["ログ収集を有効にします"]
.. link:CSHM_snmpv3.html["監視のためのSNMPv3の設定"]


. パートナースイッチで手順1~8を繰り返します。

