---
permalink: switch-bes-53248/configure-restrictions.html 
sidebar: sidebar 
keywords: problem, arise, install, license, debug, command, copy, restriction, limitation, restrictions and limitations - bes-53248 
summary: ライセンスのインストール時に問題が発生した場合は、 copy コマンドを再度実行してライセンスをインストールする前に、次の debug コマンドを実行する必要があります。 
---
= 制限事項と制限事項 - BES-53248 スイッチ
:icons: font
:imagesdir: ../media/


[role="lead"]
ライセンスのインストール時に問題が発生した場合は ' ライセンスをインストールするために 'copy' コマンドを再度実行する前に ' 次のデバッグコマンドを実行する必要があります

使用するデバッグコマンド：

+ 「バグ転送デバッグライセンス」

[listing]
----
(cs2) # debug transfer
Debug transfer output is enabled.
(cs2) # debug license
Enabled capability licensing debugging.
----
「バグ転送」および「バグライセンス」オプションを有効にして「 copy 」コマンドを実行すると、次のログ出力が返されます。

[listing]
----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----
デバッグ出力で、次の点を確認します。

* シリアル番号が「シリアル番号 QTFCU38290012 が一致していることを確認してください。
* スイッチのモデルが「 M odel BES-53248 matched 」であることを確認します
* 指定したライセンスインデックスが以前に使用されていないことを確認します。ライセンス・インデックスがすでに使用されている場合 ' 次のエラーが返されます License file /mnt/download/ license.dat.1 already exists.`
* ポートライセンスは機能ライセンスではありません。したがって ' 次の文が想定されています 'Feature not found in license file with index=1 .


ポート・ライセンスをサーバにバックアップするには 'copy コマンドを使用します

[listing]
----
(cs2) # copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat
----
を参照してください link:configure-licenses.html["BES-53248 クラスタスイッチのライセンスをインストールします"] 使用可能なライセンスでサポートされているファームウェアバージョンの詳細については、を参照してください。


CAUTION: スイッチソフトウェアをバージョン 3.4.4.6 からダウングレードする必要がある場合は、ライセンスが削除されます。これは想定される動作です。

以前のバージョンのソフトウェアにリバートする前に、適切な古いライセンスをインストールする必要があります。
