---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: 'BES-53248 クラスタ スイッチに Ethernet Fabric OS (EFOS) ソフトウェアをインストールするには、次の手順に従います。' 
---
= EFOSソフトウェアをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 クラスタ スイッチに Ethernet Fabric OS (EFOS) ソフトウェアをインストールするには、次の手順に従います。

EFOS ソフトウェアには、イーサネットおよび IP インフラストラクチャ システムを開発するための高度なネットワーク機能とプロトコルのセットが含まれています。このソフトウェア アーキテクチャは、徹底したパケット検査または分離を必要とするアプリケーションを使用するあらゆるネットワーク組織デバイスに適しています。



== 設置を準備

.開始する前に
* この手順は新規インストールにのみ適しています。
* クラスタスイッチに適したBroadcom EFOSソフトウェアを以下のサイトからダウンロードしてください。 https://www.broadcom.com/support/bes-switch["Broadcomイーサネット スイッチのサポート"^]サイト。
* 確実にlink:configure-install-initial.html["BES-53248クラスタスイッチが構成されている"]。




== ソフトウェアをインストールする

EFOS ソフトウェアをインストールするには、次のいずれかの方法を使用します。

* <<方法1: EFOSをインストールする>>。ほとんどの場合に使用します。
* <<方法2: EFOSをONIEモードでインストールする>>。一方の EFOS バージョンが FIPS 準拠であり、もう一方の EFOS バージョンが FIPS 非準拠である場合に使用します。




=== 方法1: EFOSをインストールする

EFOS ソフトウェアをインストールするには、次の手順を実行します。

.手順
. スイッチのシリアル コンソール ポートにログインするか、SSH で接続します。
. 使用 `ping`EFOS、ライセンス、および RCF ファイルをホストしているサーバーへの接続を確認するコマンド。
+
.例を表示
[%collapsible]
====
次の例では、スイッチがIPアドレス172.19.2.1のサーバに接続されていることを確認します。

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. スイッチにイメージ ファイルをダウンロードします。
+
サポートされているコピー プロトコルの詳細については、次の表を確認してください。

+
|===


| *プロトコル* | *前提条件* 


 a| 
簡易ファイル転送プロトコル (TFTP)
 a| 
なし



 a| 
SSH ファイル転送プロトコル (SFTP)
 a| 
ソフトウェアパッケージは安全な管理をサポートする必要があります



 a| 
FTP
 a| 
パスワードが必要です



 a| 
Xモデム
 a| 
なし



 a| 
Yモデム
 a| 
なし



 a| 
Zモデム
 a| 
なし



 a| 
セキュア コピー プロトコル (SCP)
 a| 
ソフトウェアパッケージは安全な管理をサポートする必要があります



 a| 
HTTP
 a| 
ネイティブ WGET ユーティリティが利用可能な場合、選択されたプラットフォームで CLI ベースのファイル転送がサポートされます。



 a| 
HTTPS
 a| 
ネイティブ WGET ユーティリティが利用可能な場合、選択されたプラットフォームで CLI ベースのファイル転送がサポートされます。

|===
+
イメージ ファイルをアクティブ イメージにコピーすると、再起動時にそのイメージによって実行中の EFOS バージョンが確立されます。以前のイメージはバックアップとして使用できます。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. アクティブ構成とバックアップ構成のブート イメージを表示します。
+
`show bootvar`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. スイッチをリブートします。
+
`reload`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
====
. 再度ログインし、EFOS ソフトウェアの新しいバージョンを確認します。
+
`show version`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. インストールを完了します。スイッチを再構成するには、次の 5 つの手順に従います。
+
.. link:configure-licenses.html["ライセンスをインストールする"]
.. link:configure-install-rcf.html["RCFファイルをインストールする"]
.. link:configure-ssh.html["SSH を有効にする"]
.. link:CSHM_log_collection.html["ログ収集を有効にする"]
.. link:CSHM_snmpv3.html["監視用にSNMPv3を構成する"]


. パートナー スイッチで手順 1 ～ 7 を繰り返します。




=== 方法2: EFOSをONIEモードでインストールする

次の手順は、一方のEFOSバージョンがFIPS準拠で、もう一方のEFOSバージョンがFIPS非準拠の場合に実行できます。これらの手順は、スイッチをブートできない場合に、FIPS非準拠またはFIPS準拠のEFOS 3.7.x.xイメージをONIEからインストールするためにも使用できます。

.手順
. スイッチのシリアル ポートに接続されているコンソールに接続します。
. スイッチをONIEインストール モードで起動します。
+
起動中にプロンプトが表示されたら ONIE を選択します。

+
.例を表示
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
*ONIE* を選択すると、スイッチが読み込まれ、いくつかの選択肢が表示されます。  *OSのインストール*を選択します。

+
.例を表示
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
スイッチは ONIE インストール モードで起動します。

. ONIE 検出を停止し、イーサネット インターフェイスを構成します。
+
次のメッセージが表示されたら、*Enter* を押して ONIE コンソールを起動します。

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE 検出が続行され、メッセージがコンソールに出力されます。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. スイッチ管理ポートのイーサネットインターフェースを設定し、ルートを追加します。 `ifconfig eth0 <ipAddress> netmask <netmask> up`そして `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. ONIEインストール ファイルをホストしているサーバにアクセスできることを確認します。
+
`ping`

+
.例を表示
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. 新しいスイッチ ソフトウェアをインストールします。
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.例を表示
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
ソフトウェアがインストールされ、スイッチが再起動します。スイッチが新しいEFOSバージョンで正常にリブートするのを待ちます。

. ログインして、新しいスイッチ ソフトウェアがインストールされていることを確認します。
+
`show bootvar`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
 1      3.7.0.4     3.7.0.4    3.7.0.4        3.10.0.3
(cs2) #
----
====
. インストールを完了します。スイッチは設定が適用されずに再起動し、工場出荷時のデフォルトにリセットされます。スイッチを再構成するには、次の 6 つの手順に従います。
+
.. link:configure-install-initial.html["スイッチの設定"]
.. link:configure-licenses.html["ライセンスをインストールする"]
.. link:configure-install-rcf.html["RCFファイルをインストールする"]
.. link:configure-ssh.html["SSH を有効にする"]
.. link:CSHM_log_collection.html["ログ収集を有効にする"]
.. link:CSHM_snmpv3.html["監視用にSNMPv3を構成する"]


. パートナー スイッチで手順 1 ～ 8 を繰り返します。


.次の手順
EFOSソフトウェアをインストールしたら、 link:configure-licenses.html["ライセンスをインストールする"]。
