---
permalink: switch-bes-53248/configure-reqs-bes53248.html 
sidebar: sidebar 
keywords: bes, cluster, switch, port, assignment, table, configure, bes-53428 cluster switch port assignments - bes-53428 switches 
summary: BES-53248 クラスタスイッチポート割り当て表を参考にして、クラスタを設定できます。 
---
= BES-53248クラスタスイッチの構成要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248スイッチの設置とメンテナンスについては、OSのサポート要件と構成要件を確認してください。



== オペレーティングシステム（OS）のサポート

BES-53248スイッチでは次の機能がサポートされます。

* * EFOSファームウェア3.4.4.6以降*。BES-53248スイッチは、イーサネットファブリックOS（EFOS）と呼ばれるBroadcom組み込みOSで実行されます。40/100GbE クラスタポートのサポートは、 EFOS ファームウェアバージョン 3.4.4.6 以降から開始されます。
* * ONTAP 9.5P8以降*。Broadcom対応BES-53248クラスタスイッチは、ONTAP 9.5P8以降では2~24ノードのサイズのクラスタで動作するように設計されています。




== 設定要件

クラスタを設定するには、クラスタスイッチに適切な数とタイプのケーブルとコネクタが必要です。最初に設定するクラスタスイッチのタイプに応じて、付属のコンソールケーブルを使用してスイッチのコンソールポートに接続する必要があります。



=== クラスタスイッチのポート割り当て

Broadcom対応BES-53248クラスタスイッチポート割り当て表を参考にして、クラスタを設定できます。

[cols="1,2"]
|===
| スイッチポート | 使用するポート 


 a| 
01-16
 a| 
10 / 25GbEクラスタポートノード、基本設定



 a| 
17-48
 a| 
10 / 25GbEクラスタポートノード、ライセンスあり



 a| 
49-54
 a| 
100GbEクラスタポートノード、ライセンスあり、右から左に追加



 a| 
55～56
 a| 
100GbE クラスタスイッチ間リンク（ ISL ）ポート、基本設定

|===
を参照してください https://hwu.netapp.com/Switch/Index["Hardware Universe"] スイッチポートの詳細については、を参照してください。



=== ポートグループの速度制限

BES-53248クラスタスイッチでは、48個の10 / 25GbE（SFP28 / SFP+）ポートが12個の4ポートグループに結合されます。ポート1~4、5 ~ 8、9 ~ 12、13 ~ 16、17 ~ 20、21～24、25～28、29～32、33～36、37～40、41-44および45-48。

SFP28 / SFP+ ポート速度は、 4 ポートグループのすべてのポートで同じ（ 10GbE または 25GbE ）でなければなりません。
