---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: BES-53248クラスタ スイッチ ベース モデルは、16個の10GbEまたは25GbEポートと、2個の100GbEポートに対してライセンスされています。ライセンスを新たに購入すると、新しいポートを追加できます。 
---
= BES-53248 クラスタスイッチのライセンスをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248クラスタ スイッチ ベース モデルは、16個の10GbEまたは25GbEポートと、2個の100GbEポートに対してライセンスされています。ライセンスを追加購入することで、新しいポートを追加できます。


CAUTION: EFOS 3.12以降の場合は、次のインストール手順に従ってください。link:efos-install-rcf-license-file.html["リファレンス構成ファイル（RCF）とライセンスファイルをインストールする"] 。



== 利用可能なライセンスを確認する

BES-53248クラスタ スイッチでは、以下のライセンスを使用できます。

[cols="1,2,3"]
|===
| ライセンス タイプ | ライセンスの詳細 | サポート対象のファームウェア バージョン 


 a| 
SW-BES-53248A2-8P-2P
 a| 
Broadcom 8PT-10G25G + 2PT-40G100G ライセンスキー、X190005/R
 a| 
EFOS 3.4.4.6以降



 a| 
SW-BES-53248A2-8P-1025G
 a| 
Broadcom 8 ポート 10G25G ライセンスキー、X190005/R
 a| 
EFOS 3.4.4.6以降



 a| 
SW-BES53248A2-6P-40-100G
 a| 
Broadcom 6 ポート 40G100G ライセンスキー、X190005/R
 a| 
EFOS 3.4.4.6以降

|===


== レガシーライセンス

次の表は、BES-53248 クラスタ スイッチで使用できたレガシー ライセンスの一覧です。

[cols="1,2,3"]
|===
| ライセンス タイプ | ライセンスの詳細 | サポート対象のファームウェア バージョン 


 a| 
SW-BES-53248A1-G1-8P-LIC
 a| 
Broadcom 8P 10-25、2P40-100ライセンス キー、X190005/R
 a| 
EFOS 3.4.3.3以降



 a| 
SW-BES-53248A1-G1-16P-LIC
 a| 
Broadcom 16P 10-25、4P40-100ライセンス キー、X190005/R
 a| 
EFOS 3.4.3.3以降



 a| 
SW-BES-53248A1-G1-24P-LIC
 a| 
Broadcom 24P 10-25、6P40-100ライセンス キー、X190005/R
 a| 
EFOS 3.4.3.3以降



 a| 
SW-BES54248-40-100G-LIC
 a| 
Broadcom 6ポート40G100Gライセンス キー、X190005/R
 a| 
EFOS 3.4.4.6以降



 a| 
SW-BES53248-8P-10G25G-LIC
 a| 
Broadcom 8ポート10G25Gライセンス キー、X190005/R
 a| 
EFOS 3.4.4.6以降



 a| 
SW-BES53248-16P-1025G-LIC
 a| 
Broadcom 16ポート10G25Gライセンス キー、X190005/R
 a| 
EFOS 3.4.4.6以降



 a| 
SW-BES53248-24P-1025G-LIC
 a| 
Broadcom 24ポート10G25Gライセンス キー、X190005/R
 a| 
EFOS 3.4.4.6以降

|===

NOTE: 基本構成ではライセンスは必要ありません。



== ライセンスファイルをインストールする

BES-53248 クラスタ スイッチのライセンスをインストールするには、次の手順に従います。

.手順
. クラスタ スイッチを管理ネットワークに接続します。
. 使用 `ping`EFOS、ライセンス、および RCF ファイルをホストしているサーバーへの接続を確認するコマンド。
+
.例を表示
[%collapsible]
====
次の例では、スイッチがIPアドレス172.19.2.1のサーバに接続されていることを確認します。

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. スイッチ cs2 の現在のライセンス使用状況を確認します。
+
`show license`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
====
. ライセンス ファイルをインストールします。
+
さらにライセンスをロードし、異なるキーインデックス番号を使用するには、この手順を繰り返します。

+
.例を表示
[%collapsible]
====
次の例では、SFTP を使用してライセンス ファイルをキー インデックス 1 にコピーします。

[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
====
. スイッチ cs2 を再起動する前に、現在のライセンス情報をすべて表示し、ライセンス ステータスをメモします。
+
`show license`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
====
. ライセンスされているすべてのポートを表示します。
+
`show port all | exclude Detach`

+
追加のライセンス ファイルのポートは、スイッチが再起動されるまで表示されません。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
====
. スイッチをリブートします。
+
`reload`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
====
. 新しいライセンスがアクティブであることを確認し、ライセンスが適用されていることを確認します。
+
`show license`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
====
. すべての新しいポートが利用可能であることを確認します。
+
`show port all | exclude Detach`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----
====



CAUTION: 追加のライセンスをインストールする場合は、新しいインターフェイスを手動で構成する必要があります。動作中の既存の本番スイッチに RCF を再適用しないでください。



== インストールの問題のトラブルシューティング

ライセンスのインストール時に問題が発生した場合は、次のデバッグコマンドを実行してから、 `copy`再度コマンドを実行します。

使用するデバッグ コマンド: `debug transfer`そして `debug license`

.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *debug transfer*
Debug transfer output is enabled.
(cs2)# *debug license*
Enabled capability licensing debugging.
----
====
実行すると `copy`コマンドを `debug transfer`そして `debug license`オプションを有効にすると、ログ出力が返されます。

.例を表示
[%collapsible]
====
[listing]
----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----
====
デバッグ出力で以下の項目を確認します。

* シリアル番号が一致していることを確認します: `Serial number QTFCU38290012 matched.`
* スイッチモデルが一致していることを確認します。 `Model BES-53248 matched.`
* 指定したライセンス インデックスが以前に使用されていないこと。ライセンス インデックスがすでに使用されている場合は、次のエラーが返されます。 `License file /mnt/download//license.dat.1 already exists.`
* ポート ライセンスが機能ライセンスではないこと。したがって、次のステートメントが予想されます。 `Feature not found in license file with index = 1.`


使用 `copy`ポートライセンスをサーバーにバックアップするコマンド:

[listing, subs="+quotes"]
----
(cs2)# *copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat*
----

CAUTION: スイッチ ソフトウェアをバージョン3.4.4.6からダウングレードする必要がある場合、ライセンスは削除されます。これは想定される動作です。

古いバージョンのソフトウェアにリバートする前に、対応する古いライセンスをインストールしておく必要があります。



== 新しくライセンスされたポートをアクティブ化する

新しくライセンスされたポートをアクティブ化するには、RCF の最新バージョンを編集し、該当するポートの詳細のコメントを解除する必要があります。

デフォルト ライセンスはポート0/1～0/16および0/55～0/56をアクティブ化しますが、新しくライセンスされたポートは使用可能なライセンスのタイプと数に応じてポート0/17～0/54のいずれかです。たとえば、SW-BES54248-40-100G-LIC ライセンスをアクティブ化するには、RCF の次のセクションのコメントを解除する必要があります。

.例を表示
[%collapsible]
====
[listing]
----
.
.
!
! 2-port or 6-port 40/100GbE node port license block
!
interface 0/49
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/50
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/51
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/52
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/53
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/54
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
.
.
----
====

NOTE: 0/49 から 0/54 までの高速ポートについては、各ポートのコメントを解除しますが、例に示すように、各ポートの RCF で 1 つの *speed* 行のみをコメント解除します (*speed 100G full-duplex* または *speed 40G full-duplex*)。0/17～0/48の低速ポートについては、適切なライセンスがアクティブ化されていれば、8ポート セクション全体のコメントを解除します。

.次の手順
ライセンスをインストールしたら、 link:configure-install-rcf.html["参照構成ファイル（RCF）をインストールする"] または link:upgrade-rcf.html["RCFをアップグレードする"]。
