---
permalink: switch-bes-53248/configure-ssh.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, bes, enable ssh on bes-53248 cluster switches - bes-53248 switches 
summary: 'クラスタ スイッチ ヘルス モニタ (CSHM) およびログ収集機能を使用する場合は、SSH が必須です。BES-53248クラスタ スイッチでSSHを有効にするには、まずSSHキーを生成してからSSHを有効にします。' 
---
= BES-53248 クラスタスイッチで SSH を有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イーサネット スイッチ ヘルス モニタ (CSHM) とログ収集機能を使用している場合は、SSH キーを生成し、クラスタ スイッチで SSH を有効にする必要があります。

.手順
. SSH が無効になっていることを確認します。
+
`show ip ssh`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Disabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Disabled
SCP server Administrative Mode: ............... Disabled
----
====
+
** SSH が無効になっていない場合は、次のように無効にします。
+
`no ip ssh server enable`

+
`no ip scp server enable`

+
[NOTE]
====
*** EFOS 3.12 以降では、SSH が無効になっているとアクティブな SSH セッションが失われるため、コンソール アクセスが必要になります。
*** EFOS 3.11 以前では、SSH サーバーを無効にした後も現在の SSH セッションは開いたままになります。


====
+

WARNING: キーを変更する前に必ず SSH を無効にしてください。そうしないと、スイッチで警告が報告されます。



. 設定モードで、SSH キーを生成します。
+
`crypto key generate`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *config*

(switch) (Config)# *crypto key generate rsa*

Do you want to overwrite the existing RSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate dsa*

Do you want to overwrite the existing DSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate ecdsa 521*

Do you want to overwrite the existing ECDSA keys? (y/n): *y*
----
====
. 設定モードで、 ONTAPログ収集の AAA 認証を設定します。
+
`aaa authorization commands "noCmdAuthList" none`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch) (Config)# *aaa authorization commands "noCmdAuthList" none*
(switch) (Config)# *exit*
----
====
. SSH/SCP を再度有効にします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *ip ssh server enable*
(switch)# *ip scp server enable*
(switch)# *ip ssh pubkey-auth*
----
====
. これらの変更をスタートアップ コンフィギュレーションに保存します。
+
`write memory`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. SSH キーを暗号化します (FIPS モードのみ)。
+

CAUTION: FIPS モードでは、セキュリティのためにキーをパスフレーズで暗号化する必要があります。暗号化されたキーがない場合、アプリケーションは起動に失敗します。キーは次のコマンドを使用して作成および暗号化されます。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch) *configure*
(switch) (Config)# *crypto key encrypt write rsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch) (Config)# *crypto key encrypt write dsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch)(Config)# *crypto key encrypt write ecdsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch) (Config)# *end*
(switch)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. スイッチをリブートします。
+
`reload`

. SSH が有効になっていることを確認します。
+
`show ip ssh`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Enabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Enabled
SCP server Administrative Mode: ............... Enabled
----
====


.次の手順
link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを構成する"] 。
