---
permalink: switch-bes-53248/configure-software-overview-bes53248.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure new bes-53248 switch 
summary: ソフトウェアの概要を確認します。 
---
= BES-53248スイッチのソフトウェアインストールワークフロー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248クラスタスイッチのソフトウェアを最初にインストールして設定するには、次の手順を実行します。

. link:configure-efos-software.html["EFOS ソフトウェアをインストールします"]。
+
イーサネットファブリックOS（EFOS）ソフトウェアをBES-53248クラスタスイッチにダウンロードしてインストールします。

. link:configure-licenses.html["BES-53248 クラスタスイッチのライセンスをインストールします"]。
+
必要に応じて、ライセンスを購入してインストールすることで新しいポートを追加します。スイッチベースモデルには、16個の10GbEまたは25GbEポートと2個の100GbEポートがライセンスされています。

. link:configure-install-rcf.html["リファレンス構成ファイル（ RCF ）のインストール"]。
+
BES-53248クラスタスイッチにRCFをインストールし、RCFを適用したあとにポートで追加ライセンスの有無を確認します。

. link:configure-ssh.html["BES-53248 クラスタスイッチで SSH を有効にします"]。
+
クラスタスイッチヘルスモニタ（CSHM）およびログ収集機能を使用する場合は、スイッチでSSHを有効にします。

. link:CSHM_log_collection.html["ログ収集機能を有効にします"]。
+
ONTAP でスイッチ関連のログファイルを収集するには、ログ収集機能を使用します。

. link:CSHM_snmpv3.html["監視のためのSNMPv3の設定"]。
+
クラスタスイッチヘルスモニタ（CSHM）機能を使用する場合は、イーサネットスイッチヘルスモニタ（CSHM）をサポートするSNMPv3を設定します。


