---
permalink: switch-bes-53248/configure-install-initial.html 
sidebar: sidebar 
keywords: switches initial setup,initial setup,efos download 
summary: この手順を使用して、BES-53248クラスタ スイッチの初期取り付けを実行できます。 
---
= BES-53248クラスタスイッチを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 クラスタ スイッチの初期セットアップを実行するには、次の手順に従います。

.開始する前に
* ハードウェアは、link:install-hardware-bes53248.html["ハードウェアをインストールする"] 。
* 以下の点を確認しました:
+
** link:configure-reqs-bes53248.html["構成要件"]
** link:components-bes53248.html["コンポーネントと部品番号"]
** link:required-documentation-bes53248.html["文書化要件"]




.例について
設定手順の例では、次のスイッチおよびノードの命名法を使用します。

* NetAppスイッチの名前は `cs1`そして `cs2`。アップグレードは 2 番目のスイッチ _cs2_ から開始されます。
* クラスタLIF名は `node1_clus1`そして `node1_clus2`ノード1の場合、 `node2_clus1`そして `node2_clus2`ノード2用。
* IPspaceの名前はClusterです。
* その `cluster1::>`プロンプトはクラスターの名前を示します。
* 各ノードのクラスタポートの名前は `e0a`そして `e0b`。参照 https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^]プラットフォームでサポートされている実際のクラスター ポート。
* NetAppスイッチでサポートされているスイッチ間リンク (ISL) は、ポート 0/55 と 0/56 です。
* NetAppスイッチでサポートされるノード接続は、デフォルトのライセンスを持つポート 0/1 ～ 0/16 です。
* 例では 2 つのノードを使用していますが、クラスターには最大 24 個のノードを含めることができます。


.手順
. シリアル ポートをホストまたはシリアル ポートに接続します。
. 管理ポート（スイッチの左側にあるRJ-45レンチ ポート）を、TFTPサーバが配置されているネットワークと同じネットワークに接続します。
. コンソールで、ホスト側のシリアル設定を設定します。
+
** 115200ボー
** 8データ ビット
** 1ストップ ビット
** パリティ：なし
** フロー制御：なし


. スイッチにログインするには `admin`パスワードの入力を求められた場合は、*Enter* を押します。デフォルトのスイッチ名は *routing* です。プロンプトで次のように入力します `enable`。これにより、スイッチ構成の特権EXECモードにアクセスできます。
+
[listing, subs="+quotes"]
----
User: *admin*
Password:
(Routing)> *enable*
Password:
(Routing)#
----
. スイッチ名を*cs2*に変更します。
+
[listing, subs="+quotes"]
----
(Routing)# *hostname cs2*
(cs2)#
----
. スイッチのサービス ポートに静的 IPv4 または IPv6 管理アドレスを設定するには、次の手順を実行します。


[role="tabbed-block"]
====
.IPv4
--
デフォルトでは、サービスポートはDHCPを使用するように設定されています。IPアドレス、サブネット マスク、デフォルト ゲートウェイ アドレスが自動的に割り当てられます。

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ip <ip-address> <netmask> <gateway>*
----
--
.IPv6
--
デフォルトでは、サービスポートはDHCPを使用するように設定されています。IPアドレス、サブネット マスク、デフォルト ゲートウェイ アドレスが自動的に割り当てられます。

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ipv6 <address>*
(cs2)# *serviceport ipv6 <gateway>*
----
--
====
. [[step7]]次のコマンドを使用して結果を確認します。
+
`show serviceport`

+
[listing, subs="+quotes"]
----
(cs2)# *show serviceport*
Interface Status............................... Up
IP Address..................................... 172.19.2.2
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 172.19.2.254
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe71:123c/64
IPv6 Default Router............................ fe80::20b:45ff:fea9:5dc0
Configured IPv4 Protocol....................... DHCP
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:71:12:3C
----
. ドメインとネームサーバーを設定します。
+
[source, cli]
----
ip domain name <domain_name>
ip name server <server_name>
----
+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ip domain name company.com*
(cs2)(Config)# *ip name server 10.10.99.1 10.10.99.2*
(cs2)(Config)# *exit*
(cs2)#
----
. NTPサーバを設定します。


[role="tabbed-block"]
====
.EFOS 3.10.0.3 以降
--
タイムゾーンと時刻同期 (NTP) を構成します。

[source, cli]
----
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 以前
--
タイムゾーンと時刻同期 (SNTP) を構成します。

[source, cli]
----
sntp client mode <client_mode>
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *sntp client mode unicast*
(cs2)(Config)# *sntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[step10]]前の手順でNTPサーバーを設定しなかった場合は、時間を手動で設定します。


[role="tabbed-block"]
====
.EFOS 3.10.0.3 以降
--
時間を手動で設定します。

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 以前
--
時間を手動で設定します。

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *no sntp client mode*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[step11]]実行中の設定をスタートアップ設定に保存します。
+
`write memory`

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----


.次の手順
link:configure-efos-software.html["EFOSソフトウェアをインストールする"] 。
