---
permalink: switch-bes-53248/configure-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: クラスタスイッチヘルスモニタログ収集機能は、 ONTAP でスイッチ関連のログファイルを収集するために使用します。ここで説明するように、 BES-53248 クラスタスイッチ CLI を使用して環境をセットアップしておく必要があります。 
---
= ログ収集機能を有効にします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ログ収集機能を使用して、ONTAP でスイッチ関連のログファイルを収集できます。


IMPORTANT: ログ収集機能を有効にするには、ONTAP バージョン9.12.1以降およびEFOS 3.8.0.2以降を実行している必要があります。

BES-53248クラスタスイッチ* CLI *を使用して環境がセットアップされていることを確認します。

.手順
. 次のコマンドを使用して、イーサネットスイッチヘルスモニタのログ収集機能を有効にし、スイッチに関連するログファイルを収集します。
+
「system switch ethernet log setup -password」およびを入力します

+
「システムスイッチのイーサネットログの有効化」

+
.. 「 system switch ethernet log setup -password 」と入力します
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
.. 入力するコマンド `system switch ethernet log enable-collection`
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system  switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
====


. スイッチログ収集機能を開始します。
+
`system switch ethernet log collect -device *`

+
10分待ってから、次のコマンドを使用してログ収集が成功したことを確認します。

+
`system switch ethernet log show`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> system switch ethernet log show
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------  ---------
1      cs1 (b8:ce:f6:19:1b:42)      4/29/2022 03:05:25   complete
2      cs2 (b8:ce:f6:19:1b:96)      4/29/2022 03:07:42   complete
----

CAUTION: これらのコマンドのいずれかでエラーが返される場合は、ネットアップサポートにお問い合わせください。

.次の手順
スイッチをアップグレードする場合は、に進みます link:replace-verify.html["アップグレード設定を確認します"]。

====

