---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: BES-53248 クラスタスイッチの基本モデルには、 16 個の 10GbE ポートまたは 25GbE ポートと 2 個の 100GbE ポートがライセンスされています。ライセンスを追加購入すると、新しいポートを追加できます。 
---
= BES-53248 クラスタスイッチのライセンスをインストールします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 クラスタスイッチの基本モデルには、 16 個の 10GbE ポートまたは 25GbE ポートと 2 個の 100GbE ポートがライセンスされています。ライセンスを追加購入すると、新しいポートを追加できます。


CAUTION: EFOS 3.12以降の場合は、のインストール手順に従いますlink:efos-install-rcf-license-file.html["リファレンス構成ファイル（RCF）とライセンスファイルのインストール"]。



== 使用可能なライセンスを確認します

BES-53248 クラスタスイッチでは次のライセンスを使用できます。

[cols="1,2,3"]
|===
| ライセンスタイプ | ライセンスの詳細 | サポートされているファームウェアバージョン 


 a| 
SW-BES-53248A2-8P-2P
 a| 
Broadcom 8PT-10G25G+2PT-40G100Gライセンスキー、X190005/R
 a| 
EFOS 3.4.4.6 以降



 a| 
SW-BES-53248A2-8P-1025G
 a| 
Broadcom 8ポート10G25Gライセンスキー、X190005/R
 a| 
EFOS 3.4.4.6 以降



 a| 
SW-BES53248A2-6P-40-100G
 a| 
Broadcom 6ポート40G100Gライセンスキー、X190005/R
 a| 
EFOS 3.4.4.6 以降

|===


== レガシーライセンス

次の表に、BES-53248クラスタスイッチで使用できる従来のライセンスを示します。

[cols="1,2,3"]
|===
| ライセンスタイプ | ライセンスの詳細 | サポートされているファームウェアバージョン 


 a| 
sw-BES - 53248A1-G1-8P-LIC
 a| 
Broadcom 8P 10/252P40-100 ライセンスキー、 X190005/R
 a| 
EFOS 3.4.3.3 以降



 a| 
sw-BES - 53248A1-G1-16P-LIC
 a| 
Broadcom 16P 10-M254P40-100 ライセンスキー、 X190005/R
 a| 
EFOS 3.4.3.3 以降



 a| 
sw-BES - 53248A1-G1-24P-LIC
 a| 
Broadcom 24P 10-M256P40-100 ライセンスキー、 X190005/R
 a| 
EFOS 3.4.3.3 以降



 a| 
SW-BES54248-40-100G-LIC
 a| 
Broadcom 6Port 40G100G ライセンスキー、 X190005/R
 a| 
EFOS 3.4.4.6 以降



 a| 
SW-BESG538-8P-10G25G-LIC
 a| 
Broadcom 8 ポート 10G25G ライセンスキー、 X190005/R
 a| 
EFOS 3.4.4.6 以降



 a| 
SW-BESBES-53248 16P-1025G - LIC
 a| 
Broadcom 16Port 10G25G ライセンスキー、 X190005/R
 a| 
EFOS 3.4.4.6 以降



 a| 
SW-BESG5-24P-1025G-LIC
 a| 
Broadcom 24Port 10G25G ライセンスキー、 X190005/R
 a| 
EFOS 3.4.4.6 以降

|===

NOTE: 基本構成にライセンスは必要ありません。



== ライセンスファイルをインストール

BES-53248クラスタスイッチのライセンスをインストールするには、次の手順を実行します。

.手順
. クラスタスイッチを管理ネットワークに接続します。
. 「 ping 」コマンドを使用して、 EFOS 、ライセンス、 RCF ファイルをホストするサーバへの接続を確認します。
+
.例を示します
[%collapsible]
====
次の例では、スイッチが IP アドレス 172.19.2.1 のサーバに接続されていることを確認します。

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. スイッチ cs2 の現在のライセンス使用状況を確認します。
+
'How license'

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
====
. ライセンスファイルをインストールします。
+
この手順を繰り返して、ライセンスを追加ロードし、異なるキーインデックス番号を使用します。

+
.例を示します
[%collapsible]
====
次の例では、 SFTP を使用してライセンスファイルをキーインデックス 1 にコピーします。

[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
====
. スイッチ cs2 をリブートする前に、現在のライセンス情報をすべて表示し、ライセンスのステータスをメモします。
+
'How license'

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
====
. すべてのライセンスポートを表示します。
+
'How port All | exclude Detach'

+
追加のライセンスファイルのポートは、スイッチをリブートするまで表示されません。

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
====
. スイッチをリブートします。
+
「再ロード」

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
====
. 新しいライセンスがアクティブになっていること、およびライセンスが適用されていることを確認します。
+
'How license'

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
====
. 新しいポートがすべて使用可能であることを確認します。
+
'How port All | exclude Detach'

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----
====



CAUTION: 追加ライセンスをインストールする場合は、新しいインターフェイスを手動で設定する必要があります。稼働中の既存の本番用スイッチにRCFを再適用しないでください。



== インストールに関する問題のトラブルシューティングを行う

ライセンスのインストール時に問題が発生した場合は、を実行する前に、次のdebugコマンドを実行してください `copy` コマンドをもう一度実行します。

使用するデバッグコマンド: debug transferおよびdebug license(ライセンスのデバッグ

.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *debug transfer*
Debug transfer output is enabled.
(cs2)# *debug license*
Enabled capability licensing debugging.
----
====
を実行すると `copy` コマンドにを指定します `debug transfer` および `debug license` 有効なオプションを指定すると、ログ出力が返されます。

.例を示します
[%collapsible]
====
[listing]
----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----
====
デバッグ出力で、次の点を確認します。

* シリアル番号が「シリアル番号 QTFCU38290012 が一致していることを確認してください。
* スイッチのモデルが「 M odel BES-53248 matched 」であることを確認します
* 指定したライセンスインデックスが以前に使用されていないことを確認します。ライセンス・インデックスがすでに使用されている場合 ' 次のエラーが返されます License file /mnt/download/ license.dat.1 already exists.`
* ポートライセンスは機能ライセンスではありません。したがって ' 次の文が想定されています 'Feature not found in license file with index=1 .


を使用します `copy` ポートライセンスをサーバにバックアップするコマンド：

[listing, subs="+quotes"]
----
(cs2)# *copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat*
----

CAUTION: スイッチソフトウェアをバージョン 3.4.4.6 からダウングレードする必要がある場合は、ライセンスが削除されます。これは想定される動作です。

以前のバージョンのソフトウェアにリバートする前に、適切な古いライセンスをインストールする必要があります。



== 新たにライセンスされたポートをアクティブにし

新しくライセンスされたポートをアクティブ化するには、RCFの最新バージョンを編集し、該当するポートの詳細をコメント解除する必要があります。

デフォルトライセンスは、ポート 0/1~0/16 および 0/55 ～ 0/56 をアクティブにします。また、新しくライセンスされたポートは、使用可能なライセンスのタイプと数に応じて、ポート 0/17 ～ 0/54 の間になります。たとえば、SW-BES54248-40-100G-LICライセンスをアクティブにするには、RCFの次のセクションのコメントを解除する必要があります。

.例を示します
[%collapsible]
====
[listing]
----
.
.
!
! 2-port or 6-port 40/100GbE node port license block
!
interface 0/49
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/50
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/51
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/52
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/53
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/54
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
.
.
----
====

NOTE: 0/49～0/54以上の高速ポートの場合は、各ポートのコメントを解除しますが、次の例に示すように、各ポートのRCFでは1つの* speed *行のみコメントを解除します。* speed 100G full-duplex *または* speed 40G full-duplex *のいずれかです。0/17 ～ 0/48 以上の低速ポートの場合は、適切なライセンスがアクティブ化されているときに 8 ポートセクション全体のコメントを解除します。

.次の手順
link:configure-install-rcf.html["リファレンス構成ファイル（ RCF ）のインストール"] または link:upgrade-rcf.html["RCFのアップグレード"]。
