---
permalink: switch-bes-53248/configure-reqs-bes53248.html 
sidebar: sidebar 
keywords: bes, cluster, switch, port, assignment, table, configure, bes-53428 cluster switch port assignments - bes-53428 switches 
summary: BES-53248クラスタ スイッチ ポート割り当て表を参考にして、クラスタを設定できます。 
---
= BES-53248 クラスタスイッチの構成要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 スイッチのインストールとメンテナンスについては、EFOS およびONTAP のサポートと構成の要件を必ず確認してください。



== EFOS およびONTAP のサポート

参照 https://hwu.netapp.com/Switch/Index["NetApp Hardware Universe"^]そして https://mysupport.netapp.com/site/info/broadcom-cluster-switch["Broadcomスイッチの互換性マトリックス"^]BES-53248 スイッチとの EFOS およびONTAP の互換性情報については、こちらをご覧ください。  EFOS およびONTAP のサポートは、BES-53248 スイッチの特定のマシン タイプによって異なる場合があります。  BES-52348スイッチマシンの全タイプの詳細については、link:components-bes53248.html["BES-53248 クラスタスイッチのコンポーネントと部品番号"] 。



== 構成要件

クラスタを構成するには、クラスタ スイッチに適した数と種類のケーブルおよびケーブル コネクタが必要です。最初に設定するクラスタ スイッチのタイプに応じて、付属のコンソール ケーブルを使用してスイッチ コンソール ポートに接続する必要があります。



=== クラスタスイッチポートの割り当て

Broadcom がサポートする BES-53248 クラスタ スイッチのポート割り当て表を、クラスタを構成するためのガイドとして使用できます。

[cols="1,2"]
|===
| スイッチ ポート | 使用するポート 


 a| 
01-16
 a| 
10/25GbE クラスタ ポート ノード、基本構成



 a| 
17-48
 a| 
10/25GbE クラスタ ポート ノード（ライセンス付き）



 a| 
49-54
 a| 
40/100GbE クラスタ ポート ノード（ライセンス付き）を右から左に追加



 a| 
55-56
 a| 
100GbEクラスタ スイッチ間リンク（ISL）ポート、基本設定

|===
参照 https://hwu.netapp.com/Switch/Index["Hardware Universe"]スイッチ ポートの詳細については、こちらをご覧ください。



=== ポート グループの速度制限

* BES-53248 クラスター スイッチでは、48 個の 10/25GbE (SFP28/SFP+) ポートが次のように 12 x 4 ポート グループに結合されます: ポート 1 ～ 4、5 ～ 8、9 ～ 12、13 ～ 16、17 ～ 20、21 ～ 24、25 ～ 28、29 ～ 32、33 ～ 36、37 ～ 40、41 ～ 44、および 45 ～ 48。
* SFP28 / SFP+ポートの速度は、グループ内のすべてのポートで同じ（10GbEまたは25GbE）でなければなりません。




=== その他の要件

* 追加のライセンスを購入する場合は、link:configure-licenses.html["新規ライセンスポートを有効化"]有効化する方法の詳細については、こちらをご覧ください。
* SSHが有効な場合は、コマンドを実行した後に手動で再度有効にする必要があります。 `erase startup-config`スイッチを再起動します。


.次の手順
構成要件を確認した後、 link:components-bes53248.html["コンポーネントと部品番号"]。
