---
permalink: switch-bes-53248/CSHM_log_collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation,BES-53248 Broadcom setup,BES-53248 switches configuration,EFOS 
summary: 'イーサネット スイッチ ヘルス モニタ (CSHM) ログ収集機能は、 ONTAPのクラスタまたはストレージ ネットワーク スイッチからログを収集するために使用されます。' 
---
= イーサネットスイッチヘルスモニタリングログ収集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イーサネット スイッチ ヘルス モニター (CSHM) は、クラスターおよびストレージ ネットワーク スイッチの動作の健全性を確認し、デバッグのためにスイッチ ログを収集する役割を担います。この手順では、スイッチからの詳細な *サポート* ログの収集を設定および開始するプロセスをガイドし、 AutoSupportによって収集される *定期的* データの 1 時間ごとの収集を開始します。

.開始する前に
* ログ収集機能を有効にするには、 ONTAPバージョン 9.10.1P15、9.11.1P12、または 9.12.1 以降と EFOS 3.8.0.2 以降を実行している必要があります。
* スイッチのヘルス モニタリングを有効にする必要があります。これを確かめるためには、 `Is Monitored:`フィールドが*true*に設定されている場合は、 `system switch ethernet show`指示。


.手順
. ログ収集を設定するには、スイッチごとに次のコマンドを実行します。ログ収集用のスイッチ名、ユーザー名、およびパスワードの入力を求められます。
+
`system switch ethernet log setup-password`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. ログ収集を開始するには、DEVICE を前のコマンドで使用したスイッチに置き換えて、次のコマンドを実行します。これにより、詳細な *サポート* ログと 1 時間ごとの *定期的* データの収集の両方の種類のログ収集が開始されます。
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
10 分待ってから、ログ収集が完了したことを確認します。

+
`system switch ethernet log show`

+

CAUTION: これらのコマンドのいずれかがエラーを返す場合、またはログ収集が完了しない場合は、 NetAppサポートにお問い合わせください。



.トラブルシューティング
ログ収集機能によって報告される以下のエラーステータス（ `system switch ethernet log show` ) の場合は、対応するデバッグ手順を試してください。

|===


| *ログ収集エラーステータス* | *解決* 


 a| 
*RSAキーが存在しません*
 a| 
ONTAP SSH キーを再生成します。  NetAppサポートにお問い合わせください。



 a| 
*スイッチパスワードエラー*
 a| 
資格情報を確認し、SSH 接続をテストし、 ONTAP SSH キーを再生成します。スイッチのドキュメントを確認するか、 NetAppサポートに問い合わせて手順を確認してください。



 a| 
*FIPS では ECDSA キーは存在しません*
 a| 
FIPS モードが有効になっている場合は、再試行する前にスイッチで ECDSA キーを生成する必要があります。



 a| 
*既存のログが見つかりました*
 a| 
スイッチ上の以前のログ収集ファイルを削除します。



 a| 
*スイッチダンプログエラー*
 a| 
スイッチ ユーザーにログ収集権限があることを確認します。上記の前提条件を参照してください。

|===