---
permalink: switch-bes-53248/index.html 
sidebar: sidebar 
keywords: broadcom, support, bes, cluster, switch, broadcam-supported bes-53248 cluster switches 
summary: BES-53248スイッチの設置とメンテナンスについては、OSのサポート、パーツ番号、構成要件、およびドキュメントの要件を確認してください。 
---
= 概要と要件：BES-53248スイッチ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248スイッチの設置とメンテナンスについては、OSのサポート、パーツ番号、構成要件、およびドキュメントの要件を確認してください。



== オペレーティングシステム（OS）のサポート

BES-53248スイッチでは次の機能がサポートされます。

* * EFOSファームウェア3.4.4.6以降*。BES-53248スイッチは、イーサネットファブリックOS（EFOS）と呼ばれるBroadcom組み込みOSで実行されます。40/100GbE クラスタポートのサポートは、 EFOS ファームウェアバージョン 3.4.4.6 以降から開始されます。
* * ONTAP 9.5P8以降*。Broadcom対応BES-53248クラスタスイッチは、ONTAP 9.5P8以降では2~24ノードのサイズのクラスタで動作するように設計されています。




== コンポーネントのパーツ番号を切り替えます

次の表に、ラックマウントレールキット、ファン、電源装置を含むBES-53248クラスタスイッチコンポーネントのパーツ番号と概要 を示します。

[cols="1,2"]
|===
| パーツ番号 | 説明 


 a| 
X190005
 a| 
BES-53248 、 CLSW 、 16Pt10/25GB 、 PTSX 、 BRDCM SUPP （ PTSX はポート側排気）



 a| 
X190005R
 a| 
BES-53248 、 CLSW 、 16Pt10/25GB 、 PSIN 、 BRDCM SUPP （ PSIN はポート側吸気）



 a| 
X-LEray-4POST-190005
 a| 
ラックマウントレールキット Ozeki 4 ポスト 19 インチ



 a| 
X-FAN-190005-R
 a| 
ファン、ポート側吸気 X190005



 a| 
X-FAN-190001-F
 a| 
ファン、ポート側排気 X190005



 a| 
X-PSA-190005-R
 a| 
電源装置、ポート側吸気 X190005

ポート側吸気（リバースエア）：冷気はコールドアイル内のポート側からシャーシに入り、ホットアイル内のファンモジュールと電源装置モジュールから排気されます。



 a| 
X-PSA-190001-F
 a| 
電源装置、ポート側排気 X190005

ポート側排気（標準エア）：冷気はコールドアイル内のファンモジュールと電源装置モジュールを介してシャーシに入り、ホットアイル内のシャーシのポート側から排気されます。ポート側排気は青色で示されています。これが最も一般的なオプションです。

|===


== 設定要件

クラスタを設定するには、クラスタスイッチに適切な数とタイプのケーブルとコネクタが必要です。最初に設定するクラスタスイッチのタイプに応じて、付属のコンソールケーブルを使用してスイッチのコンソールポートに接続する必要があります。また、特定のネットワーク情報が必要です。

.クラスタスイッチのポート割り当て
Broadcom対応BES-53248クラスタスイッチポート割り当て表を参考にして、クラスタを設定できます。

[cols="1,2"]
|===
| スイッチポート | 使用するポート 


 a| 
01-16
 a| 
10 / 25GbEクラスタポートノード、基本設定



 a| 
17-48
 a| 
10 / 25GbEクラスタポートノード、ライセンスあり



 a| 
49-54
 a| 
100GbEクラスタポートノード、ライセンスあり、右から左に追加



 a| 
55～56
 a| 
100GbE クラスタスイッチ間リンク（ ISL ）ポート、基本設定

|===
.ポートグループの速度制限
BES-53248クラスタスイッチでは、48個の10 / 25GbE（SFP28 / SFP+）ポートが12個の4ポートグループに結合されます。ポート1~4、5 ~ 8、9 ~ 12、13 ~ 16、17 ~ 20、21～24、25～28、29～32、33～36、37～40、41-44および45-48。

SFP28 / SFP+ ポート速度は、 4 ポートグループのすべてのポートで同じ（ 10GbE または 25GbE ）でなければなりません。



== ドキュメントの要件

BES-53248クラスタスイッチとONTAP クラスタをセットアップするには、特定のスイッチとコントローラのドキュメントが必要です。



=== Broadcomのドキュメント

BES-53248 クラスタスイッチをセットアップするには、 Broadcom サポートサイトから次のドキュメントを入手する必要があります。 https://www.broadcom.com/support/bes-switch["Broadcom Ethernet Switch 製品ライン"^]

[cols="1,2"]
|===
| ドキュメントタイトル | 説明 


 a| 
_ EFOS 管理者ガイド v3.4.3_
 a| 
一般的なネットワークで BES-53248 スイッチを使用する方法の例を示します。



 a| 
_ EFOS CLI コマンドリファレンス v3.4.3_
 a| 
BES-53248 ソフトウェアの表示と設定に使用するコマンドラインインターフェイス（ CLI ）コマンドについて説明します。



 a| 
_ EFOS セットアップガイド v3.4.3_
 a| 
BES-53248 スイッチの詳細情報を提供します。



 a| 
_ EFOS SNMP リファレンスガイド v3.4.3_
 a| 
一般的なネットワークで BES-53248 スイッチを使用する方法の例を示します。



 a| 
_ EFOS スケーリングパラメータと値 v3.4.3_
 a| 
EFOS ソフトウェアと一緒に提供され、サポート対象プラットフォームで検証済みのデフォルトのスケールパラメータについて説明します。



 a| 
_ EFOS 機能仕様 v3.4.3_
 a| 
サポート対象プラットフォームでの EFOS ソフトウェアの仕様を示します。



 a| 
_ EFOS リリースノート v3.4.3_
 a| 
BES-53248 ソフトウェアに関するリリース固有の情報を示します。



 a| 
_クラスタネットワークおよび管理ネットワーク互換性マトリックス_
 a| 
ネットワークの互換性に関する情報を提供します。マトリックスは、BES-53248スイッチのダウンロードサイトから入手できます https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom クラスタスイッチ"^]。

|===


=== ONTAP システムのドキュメントおよび技術情報

ONTAP システムをセットアップするには、NetApp Support Siteから次のドキュメントを入手する必要があります http://mysupport.netapp.com/["mysupport.netapp.com"^] またはKnowledgebase（KB）サイト（）を参照してください https://kb.netapp.com/["kb.netapp.com"^]。

[cols="1,2"]
|===
| 名前 | 説明 


 a| 
https://hwu.netapp.com/Home/Index["NetApp Hardware Universe の略"^]
 a| 
システムキャビネットを含むすべてのネットアップハードウェアの電源要件とサイト要件について説明し、関連するコネクタおよびケーブルオプションの情報とパーツ番号を記載します。



 a| 
コントローラ固有の設置およびセットアップ手順 _
 a| 
ネットアップハードウェアの設置方法について説明します。



 a| 
ONTAP 9
 a| 
ONTAP 9 リリースのすべての側面に関する詳細情報を提供します。



 a| 
Broadcom対応BES-53248スイッチ_のポートライセンスを追加する方法
 a| 
ポートライセンスの追加に関する詳細情報を提供します。にアクセスします https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["こちらの技術情報アーティクル"^]。

|===