---
permalink: switch-bes-53248/migrate-to-2n-switched.html 
sidebar: sidebar 
keywords: two-node switchless clusters, migrating to a two-node switched BES-53248 cluster environment,BES-53248 switches, migrating two-node switched clusters,2-node 
summary: 2ノードのスイッチレスクラスタをお持ちの場合は、BroadcomがサポートするBES-53248クラスタスイッチを含む2ノードのスイッチクラスタに無停止で移行できます。 
---
= スイッチ型NetAppクラスタ環境への移行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存の 2 ノードのスイッチレス クラスタ環境がある場合は、Broadcom がサポートする BES-53248 クラスタ スイッチを使用して 2 ノードのスイッチ クラスタ環境に移行できます。これにより、クラスタ内の 2 ノードを超えて拡張できるようになります。

移行プロセスは、光ポートまたは Twinax ポートを使用するすべてのクラスタ ノード ポートで機能しますが、ノードがクラスタ ネットワーク ポートにオンボード 10GBASE-T RJ45 ポートを使用している場合、このスイッチではサポートされません。



== 要件の確認

クラスター環境の次の要件を確認します。

* ほとんどのシステムでは、各コントローラに 2 つの専用クラスター ネットワーク ポートが必要であることに注意してください。
* BES-53248クラスタスイッチが説明どおりに設定されていることを確認してください。link:replace-switch-reqs.html["要件を置き換える"]この移行プロセスを開始する前に。
* 2 ノードのスイッチレス構成の場合は、次の点を確認してください。
+
** 2 ノードのスイッチレス構成が適切にセットアップされ、機能しています。
** ノードはONTAP 9.5P8 以降を実行しています。40 / 100GbEクラスタ ポートは、EFOSファームウェア バージョン3.4.4.6以降でサポートされます。
** すべてのクラスター ポートは *up* 状態です。
** すべてのクラスタ論理インターフェイス (LIF) は *up* 状態であり、ホーム ポート上にあります。


* Broadcom がサポートする BES-53248 クラスタ スイッチ構成の場合は、次の点を確認してください。
+
** BES-53248 クラスタ スイッチは、両方のスイッチで完全に機能します。
** 両方のスイッチには管理ネットワーク接続があります。
** クラスター スイッチへのコンソール アクセスがあります。
** BES-53248 ノード間スイッチおよびスイッチ間接続には、Twinax または光ファイバー ケーブルが使用されます。
+
その link:https://hwu.netapp.com/Home/Index["_NetApp ハードウェア ユニバース_"^] ONTAP の互換性、サポートされている EFOS ファームウェア、および BES-53248 スイッチへのケーブル接続に関する情報が含まれています。見る link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["HWU にない機器をインストールするには、どのような追加情報が必要ですか?"^] スイッチのインストール要件の詳細については、こちらをご覧ください。



* スイッチ間リンク (ISL) ケーブルは、両方の BES-53248 スイッチのポート 0/55 と 0/56 に接続されています。
* 両方の BES-53248 スイッチの初期カスタマイズが完了し、次のようになりました。
+
** BES-53248 スイッチは最新バージョンのソフトウェアを実行しています。
** BES-53248 スイッチには、購入した場合、オプションのポート ライセンスがインストールされます。
** 参照構成ファイル (RCF) がスイッチに適用されます。


* 新しいスイッチでは、サイトのカスタマイズ (SMTP、SNMP、SSH) がすべて設定されます。


.ポートグループの速度制約
* 48 個の 10/25GbE (SFP28/SFP+) ポートは、次のように 12 x 4 ポート グループに結合されます: ポート 1 ～ 4、5 ～ 8、9 ～ 12、13 ～ 16、17 ～ 20、21 ～ 24、25 ～ 28、29 ～ 32、33 ～ 36、37 ～ 40、41 ～ 44、および 45 ～ 48。
* SFP28 / SFP+ポートの速度は、グループ内のすべてのポートで同じ（10GbEまたは25GbE）でなければなりません。
* 4 ポート グループ内の速度が異なる場合、スイッチ ポートは正しく動作しません。




== クラスタ環境への移行

.例について
この手順の例では、クラスタ スイッチとノードで次の命名法を使用しています。

* BES-53248スイッチの名前は `cs1`そして `cs2`。
* クラスタSVMの名前は `node1`そして `node2`。
* LIFの名前は `node1_clus1`そして `node1_clus2`ノード1で、 `node2_clus1`そして `node2_clus2`それぞれノード 2 で。
* その `cluster1::*>`プロンプトはクラスターの名前を示します。
* この手順で使用されるクラスタポートは `e0a`そして `e0b`。
+
その https://hwu.netapp.com/Home/Index["_NetApp ハードウェア ユニバース_"^]プラットフォームの実際のクラスター ポートに関する最新情報が含まれています。





=== ステップ1: 移行の準備

. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
ここで、x はメンテナンス ウィンドウの期間 (時間単位) です。

+

NOTE: AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

+
次のコマンドは、自動ケース作成を 2 時間抑制します。

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. 続行するかどうかを尋ねられたら *y* と入力して、権限レベルを「advanced」に変更します。
+
`set -privilege advanced`

+
高度なプロンプト(`*>`）が表示されます。





=== ステップ2: ポートとケーブルを構成する

. 新しいクラスタ スイッチ cs1 と cs2 の両方で、アクティブ化されたノード側のポート (ISL ポートではない) をすべて無効にします。
+

NOTE: ISLポートを無効にしないでください。

+
次の例は、スイッチcs1でノード側のポート1～16が無効になっていることを示しています。

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. 2 つの BES-53248 スイッチ cs1 と cs2 間の ISL と ISL 上の物理ポートが稼働していることを確認します。
+
`show port-channel`

+
.例を表示
[%collapsible]
====
次の例は、スイッチ cs1 で ISL ポートが起動していることを示しています。

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
次の例は、スイッチ cs2 で ISL ポートが起動していることを示しています。

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 近隣デバイスのリストを表示します。
+
`show isdp neighbors`

+
このコマンドは、システムに接続されているデバイスに関する情報を提供します。

+
.例を表示
[%collapsible]
====
次の例は、スイッチcs1上の隣接デバイスを示しています。

[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
次の例は、スイッチcs2上の隣接デバイスを示しています。

[listing, subs="+quotes"]
----
(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
====
. すべてのクラスタ ポートが動作していることを確認します。
+
`network port show -ipspace Cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy
----
====
. すべてのクラスタLIFが動作していることを確認します。
+
`network interface show -vserver Cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. クラスタLIFで自動リバートを無効にします。
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. ノード1のクラスタ ポートe0aからケーブルを外し、BES-53248スイッチでサポートされている適切なケーブル接続に従って、クラスタ スイッチcs1のポート1に接続します。
+
その https://hwu.netapp.com/Home/Index["_NetApp ハードウェア ユニバース_"^]ケーブル接続に関する詳細情報が記載されています。

. ノード2のクラスタ ポートe0aからケーブルを外し、BES-53248スイッチでサポートされている適切なケーブル接続に従って、クラスタ スイッチcs1のポート2に接続します。
. クラスタ スイッチcs1のすべてのノード側ポートを有効にします。
+
次の例は、スイッチ cs1 でポート 1 ～ 16 が有効になっていることを示しています。

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *no shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. すべてのクラスタ ポートが動作していることを確認します。
+
`network port show -ipspace Cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. すべてのクラスタLIFが動作していることを確認します。
+
`network interface show -vserver Cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true
----
====
. クラスター内のノードのステータスに関する情報を表示します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. ノード1のクラスタ ポートe0bからケーブルを外し、BES-53248スイッチでサポートされている適切なケーブル接続に従って、クラスタ スイッチcs2のポート1に接続します。
. ノード2のクラスタ ポートe0bからケーブルを外し、BES-53248スイッチでサポートされている適切なケーブル接続に従って、クラスタ スイッチcs2のポート2に接続します。
. クラスタ スイッチcs2のすべてのノード側ポートを有効にします。
+
次の例は、スイッチ cs2 でポート 1 ～ 16 が有効になっていることを示しています。

+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *no shutdown*
(cs2)(Interface 0/1-0/16)# *exit*
(cs2)(Config)# *exit*
----
. すべてのクラスタ ポートが動作していることを確認します。
+
`network port show -ipspace Cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====




=== ステップ3: 構成を確認する

. クラスタLIFで自動リバートを有効にします。
+
[listing, subs="+quotes"]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true
----
. スイッチ cs2 で、すべてのクラスタ ポートをシャットダウンして再起動し、ホーム ポートにないすべてのクラスタ LIF の自動復帰をトリガーします。
+
[listing, subs="+quotes"]
----
cs2> *enable*
cs2# *configure*
cs2(config)# *interface 0/1-0/16*
cs2(config-if-range)# *shutdown*

(Wait for 5-10 seconds before re-enabling the ports)

cs2(config-if-range)# *no shutdown*

(After executing the no shutdown command, the nodes detect the change and begin to auto-revert the cluster LIFs to their home ports)

cs2(config-if-range)# *exit*
cs2(config)# *exit*
cs2#
----
. クラスタ LIF がホーム ポートに戻ったことを確認します (これには 1 分ほどかかる場合があります)。
+
`network interface show -vserver Cluster`

+
いずれかのクラスタ LIF がホーム ポートに戻っていない場合は、手動で戻します。LIF を所有するローカル ノードの各ノード管理 LIF またはSP/ BMCシステム コンソールに接続する必要があります。

+
`network interface revert -vserver Cluster -lif *`

. すべてのインターフェースが表示されていることを確認する `true`のために `Is Home`:
+
`network interface show -vserver Cluster`

+

NOTE: 完了するまでに数分かかる場合があります。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true
----
====
. 両方のノードが各スイッチにそれぞれ 1 つの接続を持っていることを確認します。
+
`show isdp neighbors`

+
.例を表示
[%collapsible]
====
次の例は、両方のスイッチの適切な結果を示しています。

[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform -- Port ID
-------------- ------------ --------- ------------ ----------- ----------
node1          0/1          175       H            FAS2750     e0a
node2          0/2          157       H            FAS2750     e0a
cs2            0/55         178       R            BES-53248   0/55
cs2            0/56         178       R            BES-53248   0/56


(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform    Port ID
-------------- ------------ --------- ------------ ----------- ------------
node1          0/1          137       H            FAS2750     e0b
node2          0/2          179       H            FAS2750     e0b
cs1            0/55         175       R            BES-53248   0/55
cs1            0/56         175       R            BES-53248   0/56
----
====
. クラスター内で検出されたネットワーク デバイスに関する情報を表示します。
+
`network device-discovery show -protocol cdp`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
====
. 設定が無効になっていることを確認します。
+
`network options switchless-cluster show`

+

NOTE: コマンドが完了するまでに数分かかる場合があります。3分間の有効期間が終了することを通知するアナウンスが表示されるまで待ちます。

+
その `false`次の例の出力は、構成設定が無効になっていることを示しています。

+
[listing, subs="+quotes"]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: *false*
----
. クラスター内のノード メンバーのステータスを確認します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
次の例は、クラスタ内のノードの正常性と適格性に関する情報を示します。

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2_clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none

node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step10]]権限レベルを管理者に戻します。
+
`set -privilege admin`

. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
+
詳細については、以下を参照してください。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetAppの技術情報アーティクル：「How to suppress automatic case creation during scheduled maintenance windows」"^]



.次の手順
スイッチを移行した後は、 link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを設定する"]。
