---
permalink: switch-bes-53248/migrate-cn1610.html 
sidebar: sidebar 
keywords: CN1610, CN1610 replacing, migrate from CN1610 
summary: クラスタ内の既存の CN1610 クラスタスイッチを Broadcom 対応 BES-53248 クラスタスイッチに交換するには、特定の順序でタスクを実行する必要があります。 
---
= CN1610クラスタスイッチをBES-53248クラスタスイッチに移行します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ内のCN1610クラスタスイッチをBroadcom対応BES-53248クラスタスイッチに移行するには、移行要件を確認し、移行手順 に従います。

次のクラスタスイッチがサポートされます。

* CN1610
* BES-53248 の場合




== 要件を確認

構成が次の要件を満たしていることを確認します。

* BES-53248スイッチの一部のポートは、10GbEまたは40GbEで実行するように設定されています。
* ノードからBES-53248クラスタスイッチへの10GbEおよび40GbE接続は、計画、移行、文書化されています。
* クラスタは完全に機能しています（ログにエラーがないか、または同様の問題が発生していない必要があります）。
* BES-53248スイッチの初期カスタマイズが完了し、次のようになります。
+
** BES-53248スイッチで、推奨される最新バージョンのEFOSソフトウェアが実行されている。
** リファレンス構成ファイル（RCF）がスイッチに適用されている場合。
** DNS、NTP、SMTP、SNMPなどのサイトのカスタマイズSSHは新しいスイッチに設定します。






=== ノード接続

クラスタスイッチは、次のノード接続をサポートします。

* NetApp CN1610：ポート0/1~0/12（10GbE）
* BES-53248：ポート0/1~0/16（10GbE / 25GbE）
+

NOTE: ポートライセンスを購入すると、追加のポートをアクティブ化できます。





=== ISL ポート数

クラスタスイッチは、次のスイッチ間リンク（ ISL ）ポートを使用します。

* NetApp CN1610：ポート0/13~0/16（10GbE）
* BES-53248：ポート0/55~0/56（100GbE）


。 https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe _"^] ONTAP の互換性、サポートされているEFOSファームウェア、BES-53248クラスタスイッチへのケーブル接続に関する情報が含まれています。



=== ISLのケーブル接続

適切な ISL ケーブル接続は次のとおりです。

* * 初期： CN1610 から CN1610 （ SFP+ から SFP+ ）の場合は、 SFP+ 光ファイバケーブルまたは銅線直接接続ケーブル 4 本。
* * 最終： BES-53248 から BES-53248 （ QSFP28 から QSFP28 ）の場合は、 QSFP28 光トランシーバ / ファイバケーブルまたは銅線直接接続ケーブル 2 本。




== スイッチを移行します

この手順 に従って、CN1610クラスタスイッチをBES-53248クラスタスイッチに移行します。

.例について
この手順の例では、スイッチとノードで次の命名法を使用しています。

* この例では、2つのノードを使用し、それぞれに2つの10GbEクラスタインターコネクトポートを導入しています。 `e0a` および `e0b`。
* コマンド出力は、 ONTAP ソフトウェアのリリースによって異なる場合があります。
* 交換する CN1610 スイッチは CL1 と CL2 です
* CN1610 スイッチを交換する BES-53248 スイッチは「 cs1 」と「 cs2 」です。
* ノードは 'node1 と node2 です
* まずスイッチ CL2 が cs2 に置き換えられ、次に CL1 が cs1 に置き換えられます。
* BES-53248 スイッチには、サポートされているバージョンのリファレンス構成ファイル（ RCF ）とイーサネットファブリック OS （ EFOS ）が事前にロードされており、 ISL ケーブルがポート 55 と 56 に接続されています。
* クラスタ LIF 名は、 node1 の場合は「 node1_clus1' 」、ノード 1 の場合は「 node1_clus1' 」、 node2 の場合は「 node2 _ clus2 」です。


.このタスクについて
この手順では、次のシナリオについて説明します。

* 2 つの CN1610 クラスタスイッチに接続された 2 つのノードからクラスタを開始します。
* CN1610 スイッチ CL2 が BES-53248 スイッチ cs2 に交換されます。
+
** CL2 に接続されているすべてのノードのすべてのクラスタポートからケーブルを外し、サポートされているケーブルを使用してポートを新しいクラスタスイッチ cs2 に再接続します。


* CN1610 スイッチ CL1 を BES-53248 スイッチ cs1 に置き換えます。
+
** CL1 に接続されているすべてのノードのすべてのクラスタポートからケーブルを外し、サポートされているケーブルを使用してポートを新しいクラスタスイッチ cs1 に再接続します。





NOTE: この手順 では、動作可能なInter-Switch Link（ISL；スイッチ間リンク）は必要ありません。RCFのバージョンを変更するとISL接続に一時的に影響する可能性があるため、これは設計上の変更です。クラスタのノンストップオペレーションを実現するために、次の手順 は、ターゲットスイッチでの手順の実行中に、すべてのクラスタLIFを動作しているパートナースイッチに移行します。



=== 手順1：移行の準備

. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= xh 」というメッセージが表示されます

+
x は、メンテナンス時間の長さ（時間単位）です。

+

NOTE: AutoSupport メッセージはテクニカルサポートにこのメンテナンスタスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

+
次のコマンドは、ケースの自動作成を 2 時間停止します。

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. 権限レベルを advanced に変更します。続行するかどうかを尋ねられたら、「 * y * 」と入力します。
+
「 advanced 」の権限が必要です

+
advanced のプロンプト（ * > ）が表示されます。





=== 手順2：ポートとケーブルを設定する

. 新しいスイッチで、スイッチcs1とcs2間のISLがケーブル接続され、正常に機能していることを確認します。
+
「ポートチャネルの概要」

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/55(P)   Eth1/56(P)

cs2# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/55(P)   Eth1/56(P)
----
====
. 既存のクラスタスイッチに接続されている各ノードのクラスタポートを表示します。
+
「 network device-discovery show -protocol cdp 」と入力します

+
.例を示します
[%collapsible]
====
次の例は、各クラスタインターコネクトスイッチの各ノードに設定されているクラスタインターコネクトインターフェイスの数を示しています。

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL2                       0/2               CN1610
            e0b    CL1                       0/2               CN1610
node1      /cdp
            e0a    CL2                       0/1               CN1610
            e0b    CL1                       0/1               CN1610
----
====
. 各クラスタインターフェイスの管理ステータスまたは動作ステータスを確認します。
+
.. すべてのクラスタポートが `up` を使用 `healthy` ステータス：
+
「 network port show -ipspace cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
.. すべてのクラスタインターフェイス（LIF）がそれぞれのホームポートにあることを確認します。
+
「 network interface show -vserver Cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
----
====


. クラスタが両方のクラスタスイッチの情報を表示していることを確認します。


[role="tabbed-block"]
====
.ONTAP 9.8 以降
--
ONTAP 9.8以降では、次のコマンドを使用します。 `system switch ethernet show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
.ONTAP 9.7 以前
--
ONTAP 9.7以前の場合は、次のコマンドを使用します。 `system cluster-switch show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
====
. [[step5]]クラスタLIFで自動リバートを無効にします。
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. クラスタスイッチCL1で、ノードのクラスタポートに接続されているポートをシャットダウンします。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/13-0/16*
(CL1)(Interface 0/13-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. クラスタスイッチCL1でホストされているポートにクラスタLIFが移行されたことを確認します。これには数秒かかることがあります。
+
「 network interface show -vserver Cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     false
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     false
----
====
. クラスタが正常であることを確認します。
+
「 cluster show 」を参照してください

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. すべてのクラスタノード接続ケーブルを古いcs2スイッチから新しいcs2スイッチに移動します。
. cs2に移動したネットワーク接続の健全性を確認します。
+
「 network port show -ipspace cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
移動したすべてのクラスタポートは `up`。

. クラスタポートのネイバー情報を確認します。
+
「 network device-discovery show -protocol cdp 」と入力します

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    cs1                       0/2               BES-53248
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    cs1                       0/1               BES-53248
----
====
. コマンドを使用して、スイッチcs2から見たスイッチポートの接続を確認します。
+
[listing, subs="+quotes"]
----
cs2# *show interface brief*
cs2# *show cdp neighbors*
----
. クラスタスイッチCL2で、ノードのクラスタポートに接続されているポートをシャットダウンします。
+
[listing, subs="+quotes"]
----
(CL2)# *configure*
(CL2)(Config)# *interface 0/1-0/16*
(CL2)(Interface 0/1-0/16)# *shutdown*
(CL2)(Interface 0/13-0/16)# *exit*
(CL2)(Config)# *exit*
(CL2)#
----
+
すべてのクラスタLIFがcs2スイッチに移動します。

. クラスタ LIF がスイッチ cs2 でホストされているポートに移行されたことを確認します。この処理には数秒かかることがあります。
+
「 network interface show -vserver Cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. クラスタが正常であることを確認します。
+
「 cluster show 」を参照してください

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. クラスタノード接続ケーブルをCL1から新しいcs1スイッチに移動します。
. CS1に移動したネットワーク接続の健全性を確認します。
+
「 network port show -ipspace cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
移動したすべてのクラスタポートは `up`。

. クラスタポートのネイバー情報を確認します。
+
「 network device-discovery show 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    cs2                       0/1               BES-53248
            e0b    cs1                       0/1               BES-53248
node2      /cdp
            e0a    cs2                       0/2               BES-53248
            e0b    cs1                       0/2               BES-53248
----
====
. コマンドを使用して、スイッチcs1から見たスイッチポートの接続を確認します。
+
[listing, subs="+quotes"]
----
cs1# *show interface brief*
cs1# *show cdp neighbors*
----
. cs1とcs2間のISLが動作していることを確認します。
+
「ポートチャネルの概要」

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/55(P)   Eth1/56(P)

cs2# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/55(P)   Eth1/56(P)
----
====
. 交換した CN1610 スイッチが自動的に削除されていない場合は、これらを削除します。


[role="tabbed-block"]
====
.ONTAP 9.8 以降
--
ONTAP 9.8以降では、次のコマンドを使用します。 `system switch ethernet delete -device _device-name_`

[listing]
----
cluster::*> system switch ethernet delete -device CL2
cluster::*> system switch ethernet delete -device CL1
----
--
.ONTAP 9.4以前
--
ONTAP 9.4以前の場合は、次のコマンドを使用します。 `system cluster-switch delete -device _device-name_`

[listing]
----
cluster::*> system cluster-switch delete -device CL2
cluster::*> system cluster-switch delete -device CL1
----
--
====


=== 手順3：構成を確認します

. クラスタ LIF で自動リバートを有効にします。
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert true*
----
. クラスタLIFがホームポートにリバートされたことを確認します（数分かかる場合があります）。
+
「 network interface show -vserver Cluster 」のように表示されます

+
クラスタLIFがホームポートにリバートされていない場合は、手動でリバートします。

+
network interface revert -vserver Cluster -lif *

. クラスタが正常であることを確認します。
+
「 cluster show 」を参照してください

. リモートクラスタインターフェイスに ping を実行して接続を確認します。
+
`cluster ping-cluster -node <name>`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69  node1     e0a
Cluster node1_clus2 169.254.49.125  node1     e0b
Cluster node2_clus1 169.254.47.194  node2     e0a
Cluster node2_clus2 169.254.19.183  node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====
. イーサネットスイッチヘルスモニタのログ収集機能のパスワードを作成します。
+

IMPORTANT: ログ収集機能を有効にするには、ONTAP 9.12.1以降およびEFOS 3.8.0.2以降を実行している必要があります。

+
「システムスイッチイーサネットログセットアップ - パスワード」

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. イーサネットスイッチヘルスモニタのログ収集機能を有効にします。
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration?
{y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
10分待ってから、ログ収集が完了したことを確認します。

+
`system switch ethernet log show`

+

CAUTION: これらのコマンドのいずれかでエラーが返された場合、またはログの収集が完了しない場合は、NetAppサポートにお問い合わせください。

. ケースの自動作成を抑制した場合は、 AutoSupport メッセージを呼び出して作成を再度有効にします。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます

+
[listing, subs="+quotes"]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----


.次の手順
移行が完了したら、 BES-53248 クラスタスイッチのクラスタスイッチヘルスモニタ（ CSHM ）をサポートするために必要な構成ファイルのインストールが必要になる場合があります。を参照してください link:configure-health-monitor.html["クラスタスイッチヘルスモニタ（ CSHM ）構成ファイルをインストールします"] および link:configure-log-collection.html["ログ収集機能を有効にします"]。
