---
permalink: switch-bes-53248/migrate-cn1610-overview.html 
sidebar: sidebar 
keywords: BES-53248 switches,replacing with BES-53248 switches, migrate cluster switches 
summary: CN1610 クラスタスイッチを Broadcom 対応 BES-53248 クラスタスイッチに移行する場合は、特定の構成情報、ポート接続、およびケーブル接続要件に注意する必要があります。 
---
= CN1610 クラスタスイッチを Broadcom 対応 BES-53248 スイッチに移行します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CN1610 クラスタスイッチを Broadcom 対応 BES-53248 クラスタスイッチに移行する場合は、特定の構成情報、ポート接続、およびケーブル接続要件に注意する必要があります。

* 次のクラスタスイッチがサポートされます。
+
** CN1610
** BES-53248 の場合


* クラスタスイッチは、次のノード接続をサポートします。
+
** NetApp CN1610 ：ポート 0/1~0/12 （ 10GbE ）
** BES-53248 ：ポート 0/1~0/16 （ 10/25GbE ）
+

NOTE: ポートライセンスを購入すると、追加のポートをアクティブ化できます。



* クラスタスイッチは、次のスイッチ間リンク（ ISL ）ポートを使用します。
+
** NetApp CN1610 ：ポート 0/13~0/16 （ 10GbE ）
** BES-53248 ：ポート 0/55~0/56 （ 100GbE ）


* 。 https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe _"^] ONTAP の互換性、サポートされているEFOSファームウェア、BES-53248クラスタスイッチへのケーブル接続に関する情報が含まれています。
* 適切な ISL ケーブル接続は次のとおりです。
+
** * 初期： CN1610 から CN1610 （ SFP+ から SFP+ ）の場合は、 SFP+ 光ファイバケーブルまたは銅線直接接続ケーブル 4 本。
** * 中間： CN1610 から BES-53248 （ SFP+ から SFP28 ）の場合は、 10G SFP+ 光トランシーバ / ファイバケーブルまたは銅線直接接続ケーブル 4 本。
** * 最終： BES-53248 から BES-53248 （ QSFP28 から QSFP28 ）の場合は、 QSFP28 光トランシーバ / ファイバケーブルまたは銅線直接接続ケーブル 2 本。





NOTE: 移行が完了したら、 BES-53248 クラスタスイッチのクラスタスイッチヘルスモニタ（ CSHM ）をサポートするために必要な構成ファイルのインストールが必要になる場合があります。

を参照してください link:configure-health-monitor.html["クラスタスイッチヘルスモニタ（ CSHM ）構成ファイルをインストールします"] および link:configure-log-collection["クラスタスイッチのログ収集機能を設定します"] スイッチ関連のログファイルの収集に使用されるクラスタ健常性スイッチのログ収集を有効にするために必要な手順については、を参照してください。
