---
permalink: switch-bes-53248/migrate-cn1610.html 
sidebar: sidebar 
keywords: CN1610, CN1610 replacing, migrate from CN1610 
summary: クラスタ内の既存の CN1610 クラスタ スイッチを Broadcom 対応の BES-53248 クラスタ スイッチに置き換えるには、特定の一連のタスクを実行する必要があります。 
---
= CN1610クラスタスイッチをBES-53248クラスタスイッチに移行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ内の CN1610 クラスタ スイッチを Broadcom 対応の BES-53248 クラスタ スイッチに移行するには、移行要件を確認し、移行手順に従います。

次のクラスタ スイッチがサポートされます。

* CN1610
* BES-53248




== 要件の確認

構成が次の要件を満たしていることを確認します。

* BES-53248 スイッチの一部のポートは、10GbE で動作するように構成されています。
* ノードから BES-53248 クラスター スイッチへの 10GbE 接続が計画、移行、および文書化されました。
* クラスターは完全に機能しています (ログにエラーや同様の問題は発生しないはずです)。
* BES-53248 スイッチの初期カスタマイズが完了し、次のようになりました。
+
** BES-53248 スイッチは、EFOS ソフトウェアの最新の推奨バージョンを実行しています。
** 参照構成ファイル (RCF) がスイッチに適用されています。
** DNS、NTP、SMTP、SNMP、SSH などのサイトのカスタマイズはすべて新しいスイッチで構成されます。






=== ノード接続

クラスター スイッチは次のノード接続をサポートします。

* NetApp CN1610: ポート 0/1 ～ 0/12 (10GbE)
* BES-53248: ポート 0/1-0/16 (10GbE/25GbE)
+

NOTE: ポート ライセンスを購入することで、追加のポートをアクティブ化できます。





=== ISLポート数

クラスタ スイッチは、次のスイッチ間リンク (ISL) ポートを使用します。

* NetApp CN1610: ポート 0/13 ～ 0/16 (10GbE)
* BES-53248: ポート 0/55-0/56 (100GbE)


その https://hwu.netapp.com/Home/Index["_NetApp ハードウェア ユニバース_"^]ONTAP の互換性、サポートされている EFOS ファームウェア、および BES-53248 クラスタ スイッチへのケーブル接続に関する情報が含まれています。



=== ISL接続用のケーブル配線

適切な ISL ケーブル接続は次のとおりです。

* *開始:* CN1610 から CN1610 (SFP+ から SFP+) の場合、4 本の SFP+ 光ファイバー ケーブルまたは銅線直接接続ケーブル。
* *最終:* BES-53248 から BES-53248 (QSFP28 から QSFP28) の場合、2 つの QSFP28 光トランシーバー/ファイバーまたは銅線の直接接続ケーブル。




== スイッチを移行する

CN1610 クラスタ スイッチを BES-53248 クラスタ スイッチに移行するには、次の手順に従います。

.例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* この例では、2 つのノードが使用され、各ノードには 2 つの 10 GbE クラスタ相互接続ポートが展開されています。 `e0a`そして `e0b`。
* コマンド出力は、 ONTAPソフトウェアのリリースによって異なる場合があります。
* 交換対象となるCN1610スイッチは `CL1`そして `CL2`。
* CN1610スイッチの代替となるBES-53248スイッチは `cs1`そして `cs2`。
* ノードは `node1`そして `node2`。
* まずスイッチ CL2 が cs2 に置き換えられ、次にスイッチ CL1 が cs1 に置き換えられます。
* BES-53248 スイッチには、ポート 55 および 56 に ISL ケーブルが接続された、サポートされているバージョンのリファレンス構成ファイル (RCF) と Ethernet Fabric OS (EFOS) がプリロードされています。
* クラスタLIF名は `node1_clus1`そして `node1_clus2`ノード1の場合、 `node2_clus1`そして `node2_clus2`ノード2用。


.タスク概要
この手順では、次のシナリオについて説明します。

* クラスターは、2 つの CN1610 クラスター スイッチに接続された 2 つのノードで開始されます。
* CN1610スイッチCL2をBES-53248スイッチcs2に置き換えます。
+
** クラスター ノードへのポートをシャットダウンします。クラスターの不安定性を回避するには、すべてのポートを同時にシャットダウンする必要があります。
** CL2 に接続されているすべてのノードのすべてのクラスタ ポートからケーブルを外し、サポートされているケーブルを使用してポートを新しいクラスタ スイッチ cs2 に再接続します。


* CN1610スイッチCL1をBES-53248スイッチcs1に置き換えます。
+
** クラスター ノードへのポートをシャットダウンします。クラスターの不安定性を回避するには、すべてのポートを同時にシャットダウンする必要があります。
** CL1 に接続されているすべてのノードのすべてのクラスタ ポートからケーブルを外し、サポートされているケーブルを使用してポートを新しいクラスタ スイッチ cs1 に再接続します。





NOTE: この手順では、動作中のスイッチ間リンク (ISL) は必要ありません。これは、RCF バージョンの変更によって ISL 接続が一時的に影響を受ける可能性があるため、設計によるものです。クラスタ操作を中断せずに実行するために、次の手順では、ターゲット スイッチで手順を実行しながら、すべてのクラスタ LIF を動作中のパートナー スイッチに移行します。



=== ステップ1: 移行の準備

. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
ここで、x はメンテナンス ウィンドウの期間 (時間単位) です。

+

NOTE: AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

+
次のコマンドは、自動ケース作成を 2 時間抑制します。

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. 続行するかどうかを尋ねられたら *y* と入力して、権限レベルを「advanced」に変更します。
+
`set -privilege advanced`

+
advancedのプロンプト（*>）が表示されます。





=== ステップ2: ポートとケーブルを構成する

. 新しいスイッチで、スイッチ cs1 と cs2 間の ISL がケーブル接続され、正常であることを確認します。
+
`show port-channel`

+
.例を表示
[%collapsible]
====
次の例は、スイッチ cs1 の ISL ポートが *up* であることを示しています。

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
次の例は、スイッチ cs2 の ISL ポートが *アップ* していることを示しています。

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 既存のクラスター スイッチに接続されている各ノード上のクラスター ポートを表示します。
+
`network device-discovery show -protocol cdp`

+
.例を表示
[%collapsible]
====
次の例では、各クラスタ相互接続スイッチの各ノードに設定されているクラスタ相互接続インターフェイスの数を表示します。

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    CL2                       0/2               CN1610
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    CL2                       0/1               CN1610
----
====
. 各クラスタ インターフェイスの管理ステータスまたは動作ステータスを決定します。
+
.. すべてのクラスタポートが `up`と `healthy`状態：
+
`network port show -ipspace Cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
.. すべてのクラスタ インターフェイス (LIF) がホーム ポート上にあることを確認します。
+
`network interface show -vserver Cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
----
====


. クラスターが両方のクラスター スイッチの情報を表示することを確認します。


[role="tabbed-block"]
====
.ONTAP 9.8以降
--
ONTAP 9.8 以降では、次のコマンドを使用します。 `system switch ethernet show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
.ONTAP 9.7以前
--
ONTAP 9.7 以前の場合は、次のコマンドを使用します。 `system cluster-switch show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
====
. [[step5]]クラスタLIFの自動復帰を無効にします。
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. クラスタ スイッチ CL2 で、クラスタ LIF をフェイルオーバーするために、ノードのクラスタ ポートに接続されているポートをシャットダウンします。
+
[listing, subs="+quotes"]
----
(CL2)# *configure*
(CL2)(Config)# *interface 0/1-0/16*
(CL2)(Interface 0/1-0/16)# *shutdown*
(CL2)(Interface 0/1-0/16)# *exit*
(CL2)(Config)# *exit*
(CL2)#
----
. クラスタ LIF がクラスタ スイッチ CL1 でホストされているポートにフェイルオーバーされたことを確認します。数秒かかる場合があります。
+
`network interface show -vserver Cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0a     false
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0a     false
----
====
. クラスタが正常に動作していることを確認します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. すべてのクラスター ノード接続ケーブルを古い CL2 スイッチから新しい cs2 スイッチに移動します。
. cs2 に移動されたネットワーク接続の健全性を確認します。
+
`network port show -ipspace Cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
移動されたすべてのクラスタポートは `up`。

. クラスター ポートのネイバー情報を確認します。
+
`network device-discovery show -protocol cdp`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    cs2                       0/1               BES-53248
----
====
. スイッチ cs2 の観点からスイッチ ポート接続が正常であることを確認します。
+
[listing, subs="+quotes"]
----
cs2# *show interface all*
cs2# *show isdp neighbors*
----
. クラスタ スイッチ CL1 で、クラスタ LIF をフェイルオーバーするために、ノードのクラスタ ポートに接続されているポートをシャットダウンします。
+
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/1-0/16*
(CL1)(Interface 0/1-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
+
すべてのクラスタ LIF は cs2 スイッチにフェイルオーバーします。

. クラスタ LIF がスイッチ cs2 でホストされているポートにフェイルオーバーされたことを確認します。これには数秒かかる場合があります。
+
`network interface show -vserver Cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0b     false
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0b     false
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. クラスタが正常に動作していることを確認します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. クラスタ ノード接続ケーブルを CL1 から新しい cs1 スイッチに移動します。
. cs1 に移動されたネットワーク接続の健全性を確認します。
+
`network port show -ipspace Cluster`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
移動されたすべてのクラスタポートは `up`。

. クラスター ポートのネイバー情報を確認します。
+
`network device-discovery show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
----
====
. スイッチ cs1 の観点から、スイッチ ポート接続が正常であることを確認します。
+
[listing, subs="+quotes"]
----
cs1# *show interface all*
cs1# *show isdp neighbors*
----
. cs1 と cs2 間の ISL がまだ動作していることを確認します。
+
`show port-channel`

+
.例を表示
[%collapsible]
====
次の例は、スイッチ cs1 の ISL ポートが *up* であることを示しています。

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
次の例は、スイッチ cs2 の ISL ポートが *アップ* していることを示しています。

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 交換した CN1610 スイッチが自動的に削除されない場合は、クラスタのスイッチ テーブルから削除します。


[role="tabbed-block"]
====
.ONTAP 9.8以降
--
ONTAP 9.8 以降では、次のコマンドを使用します。 `system switch ethernet delete -device _device-name_`

[listing]
----
cluster::*> system switch ethernet delete -device CL1
cluster::*> system switch ethernet delete -device CL2
----
--
.ONTAP 9.7以前
--
ONTAP 9.7 以前の場合は、次のコマンドを使用します。 `system cluster-switch delete -device _device-name_`

[listing]
----
cluster::*> system cluster-switch delete -device CL1
cluster::*> system cluster-switch delete -device CL2
----
--
====


=== ステップ3: 構成を確認する

. クラスタLIFで自動リバートを有効にします。
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert true*
----
. クラスタ LIF がホーム ポートに戻ったことを確認します (これには 1 分ほどかかる場合があります)。
+
`network interface show -vserver Cluster`

+
クラスタ LIF がホーム ポートに戻っていない場合は、手動で戻します。

+
`network interface revert -vserver Cluster -lif *`

. クラスタが正常に動作していることを確認します。
+
`cluster show`

. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2_clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none

node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step5]]自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
[listing, subs="+quotes"]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----


.次の手順
スイッチを移行した後は、 link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを設定する"]。
