---
permalink: switch-bes-53248/overview-bes53248.html 
sidebar: sidebar 
keywords: cluster-mode,supported versions,switches supported,cluster network,efos 
summary: Broadcom 対応 BES-53248 クラスタスイッチは、 ONTAP 9.5P8 以降では 2~24 ノードのサイズのクラスタで動作するように設計されています。40/100GbE クラスタポートのサポートは、 EFOS ファームウェアバージョン 3.4.4.6 以降から開始されます。 
---
= Broadcom対応BES-53248クラスタスイッチの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Broadcom 対応 BES-53248 クラスタスイッチは、 ONTAP 9.5P8 以降では 2~24 ノードのサイズのクラスタで動作するように設計されています。40/100GbE クラスタポートのサポートは、 EFOS ファームウェアバージョン 3.4.4.6 以降から開始されます。

BES-53248 は、イーサネットファブリック OS （ EFOS ）と呼ばれる Broadcom 組み込み OS で動作するスイッチです。

次の表に、 BES-53248 クラスタスイッチ、ラックマウントレールキット、ファン、および電源装置のパーツ番号と概要を示します。

[cols="1,2"]
|===
| パーツ番号 | 説明 


 a| 
X190005
 a| 
BES-53248 、 CLSW 、 16Pt10/25GB 、 PTSX 、 BRDCM SUPP （ PTSX はポート側排気）



 a| 
X190005R
 a| 
BES-53248 、 CLSW 、 16Pt10/25GB 、 PSIN 、 BRDCM SUPP （ PSIN はポート側吸気）



 a| 
X-LEray-4POST-190005
 a| 
ラックマウントレールキット Ozeki 4 ポスト 19 インチ



 a| 
X-FAN-190005-R
 a| 
ファン、ポート側吸気 X190005



 a| 
X-FAN-190001-F
 a| 
ファン、ポート側排気 X190005



 a| 
X-PSA-190005-R
 a| 
電源装置、ポート側吸気 X190005



 a| 
X-PSA-190001-F
 a| 
電源装置、ポート側排気 X190005

|===
提供される 2 つのモデルに基づく通気の概要：

* ポート側排気（標準エア）：冷気はコールドアイル内のファンモジュールと電源装置モジュールを介してシャーシに入り、ホットアイル内のシャーシのポート側から排気されます。ポート側排気は青色で示されています。これが最も一般的なオプションです。
* ポート側吸気（リバースエア）：冷気はコールドアイル内のポート側からシャーシに入り、ホットアイル内のファンモジュールと電源装置モジュールから排気されます。


を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["ネットアップの技術情報アーティクル：「 How to add additional port licensing for the Broadcom-supported BES-53248 switch."^] ポートライセンスの追加の詳細については、を参照してください。

関連するコネクタおよびケーブルオプションとそれらの部品番号については、を参照してください https://hwu.netapp.com/Home/Index["NetApp Hardware Universe の略"^]。

詳細については、 BES-53248 スイッチのダウンロードサイトから _Cluster Network and Management Network Compatibility Matrix_available を参照してください https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom クラスタスイッチ"^]。
