---
permalink: switch-bes-53248/replace-upgrade.html 
sidebar: sidebar 
keywords: BES-53248 switches,upgrading,BES-53248 switches 
summary: BES-53248 クラスタスイッチをアップグレードするには、アップグレードのためのコントローラの準備、 EFOS ソフトウェア、ライセンス、リファレンス構成ファイル \ （ RCF \ ）のインストールを開始します。インストールが完了したら、無停止アップグレード（ NDU ）および無停止運用（ NDO ）環境でコントローラ構成をリストアできます。 
---
= NDO / NDU 環境で BES-53248 クラスタスイッチをアップグレードします
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 クラスタスイッチをアップグレードするには、アップグレードのためのコントローラの準備、 EFOS ソフトウェア、ライセンス、リファレンス構成ファイル（ RCF ）のインストールが必要です。インストールが完了したら、無停止アップグレード（ NDU ）および無停止運用（ NDO ）環境でコントローラ構成をリストアできます。

既存の NetApp BES-53248 クラスタスイッチに EFOS ソフトウェア、ライセンス、 RCF ファイルをインストールする前に、次の条件が満たされている必要があります。

* クラスタは完全に機能している必要があります（エラーログメッセージやその他の問題がない）。
* クラスタには欠陥のあるクラスタネットワークインターフェイスカード（ NIC ）が含まれていない状態である必要があります。
* 両方のクラスタスイッチで接続されているすべてのポートが機能している必要があります。
* すべてのクラスタポートが稼働している必要があります。
* すべてのクラスタ LIF が、管理上および運用上稼働した状態でホームポートにある必要があります。
* ONTAP の cluster ping-cluster -node node1 advanced 権限コマンドは 'larger than PMTU communication がすべてのパスで成功したことを示す必要があります
* RCF バージョンと EFOS バージョンのコマンド構文の間に、コマンドの依存関係がある場合があります。


サポートされている EFOS 、 RCF 、 ONTAP のバージョンについて、 NetApp BES-53248 スイッチのページにあるスイッチ互換性の表を参照する必要があります。 http://mysupport.netapp.com/site["NetApp BES-53248 スイッチ"^]。

この手順環境は正常に機能しているクラスタで、 NDU と NDO が可能です。この手順の例では、スイッチとノードで次の命名法を使用しています。

* ネットアップのスイッチ名は「 cs1 」と「 cs2 」です。
* この手順で使用している例では、 2 番目のスイッチ _cs2 でアップグレードが開始されます。 _
* クラスタ LIF 名は、 node1 の場合は「 node1_clus1' 」、ノード 1 の場合は「 node1_clus1' 」、 node2 の場合は「 node2 _ clus2 」です。
* IPspace 名は Cluster です。
* 「 cluster1 ：： > 」プロンプトは、クラスタの名前を示します。
* 各ノードのクラスタ・ポートの名前は 'e0a' および e0b です
+
プラットフォームでサポートされている実際のクラスタポートについては、 __ Hardware Universe __ を参照してください。

+
https://hwu.netapp.com/Home/Index["NetApp Hardware Universe の略"^]

* ネットアップクラスタスイッチでサポートされるスイッチ間リンク（ ISL ）は、ポート 0/55 と 0/56 です。
* ネットアップクラスタスイッチでサポートされるノード接続は、デフォルトのライセンスでポート 0/1~0/16 です。
* この手順の例では 2 つのノードを使用していますが、 1 つのクラスタには最大 24 のノードを含めることができます。
* このセクションのすべての手順を繰り返して、もう一方のスイッチ * cs1 * に EFOS ソフトウェアと RCF ファイルをアップグレードします。

