---
permalink: switch-bes-53248/replace-verify.html 
sidebar: sidebar 
keywords: command, verify, operational, bes, cluster, switch, upgrade, verify the configuration after a cluster switch upgrade - bes-53428 switches 
summary: ここに示すコマンドを使用して、 BES-53248 クラスタスイッチのアップグレード後にすべてが動作していることを確認できます。 
---
= BES-53248クラスタスイッチのEFOSソフトウェアまたはRCFアップグレード後のONTAPクラスタネットワークの確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EFOSソフトウェアまたはBES-53248クラスタスイッチのRCFをアップグレードしたあとに、次のコマンドを使用してONTAPクラスタネットワークの健全性を確認できます。

.手順
. コマンドを使用して、クラスタのネットワークポートに関する情報を表示します。
+
[source, cli]
----
network port show -ipspace Cluster
----
+
「 Link 」の値は「 up 」で、「 Health Status 」の値は「 healthy 」である必要があります。

+
.例を示します
[%collapsible]
====
次の例は、コマンドからの出力例を示しています。

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. それぞれのLIFについて、を確認します `Is Home` はです `true` および `Status Admin/Oper` はです `up` 両方のノードで、コマンドを使用します。
+
[source, cli]
----
network interface show -vserver Cluster
----
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.217.125/16 node1         e0a     true
            node1_clus2  up/up    169.254.205.88/16  node1         e0b     true
            node2_clus1  up/up    169.254.252.125/16 node2         e0a     true
            node2_clus2  up/up    169.254.110.131/16 node2         e0b     true
----
====
. を確認します `Health Status` 各ノードのはです `true` コマンドを使用します。
+
「 cluster show 」を参照してください

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====


.次の手順
link:../switch-cshm/config-overview.html["スイッチヘルス監視の設定"]です。
