---
permalink: switch-bes-53248/replace-install.html 
sidebar: sidebar 
keywords: procedure, perform, initial, installation, bes, cluster, switch, initial installation of the bes-53428 cluster switch - bes-53428 switches 
summary: この手順を使用して、 BES-53248 クラスタスイッチの初期取り付けを実行できます。 
---
= BES-53248 クラスタスイッチの初期取り付け
:icons: font
:imagesdir: ../media/


[role="lead"]
この手順を使用して、 BES-53248 クラスタスイッチの初期取り付けを実行できます。

クラスタスイッチに適用可能な Broadcom EFOS ソフトウェアをからダウンロードできます https://www.broadcom.com/support/bes-switch["Broadcom Ethernet Switch のサポート"^] サイト

EFOS は、データセンターアプリケーション向けにさまざまなイーサネットシステムおよび IP インフラシステムを開発するために必要な、高度なネットワーク機能とプロトコルの広範なソフトウェアセットです。EFOS ソフトウェアは、パケットの検査や分離を完全に行う必要がある最先端のアプリケーションを使用しているネットワーク組織のあらゆるデバイスに適したアーキテクチャです。

この手順には、スイッチを設置して稼働させるためのプロセスの概要が記載されています。

.手順
. シリアルポートを任意のホストまたはシリアルポートに接続します。
. 管理ポート（スイッチの左側にある RJ-45 レンチポート）を、 TFTP サーバが配置されているネットワークと同じネットワークに接続します。
. コンソールで、ホスト側のシリアル設定を行います。
+
** 115200 ボー
** 8 データビット
** 1 ストップビット
** パリティ：なし
** フロー制御：なし


. スイッチに admin としてログインし、パスワードの入力を求められたら Enter キーを押します。デフォルトのスイッチ名は routing です。プロンプトで 'enable' と入力しますこれにより、スイッチ設定の特権 EXEC モードにアクセスできます。
+
[listing]
----
User: admin
Password:
(Routing)> enable
Password:
(Routing) #
----
. スイッチ名を cs2 に変更します。
+
[listing]
----
(Routing) # hostname cs2
(cs2) #
----
. 静的 IP アドレスを設定するには、次の例に示すように、 serviceport protocol コマンド、 network protocol コマンド、および serviceport IP コマンドを使用します。
+
デフォルトでは、サービスポートは DHCP を使用するように設定されています。IP アドレス、サブネットマスク、およびデフォルトゲートウェイアドレスが自動的に割り当てられます。

+
[listing]
----
(cs2) # serviceport protocol none
(cs2) # network protocol none
(cs2) # serviceport ip ipaddr netmask gateway
----
. 次のコマンドを使用して結果を確認します。
+
'How serviceport

+
次の例は、 DHCP サーバから提供される IP 情報を示しています。

+
[listing]
----
(cs2) # show serviceport
Interface Status............................... Up
IP Address..................................... 172.19.2.2
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 172.19.2.254
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe71:123c/64
IPv6 Default Router............................ fe80::20b:45ff:fea9:5dc0
Configured IPv4 Protocol....................... DHCP
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:71:12:3C
----
. ドメインとネームサーバを設定します。
+
「 configure 」を実行します

+
[listing]
----
(cs2) # configure
(cs2) (Config)#ip domain name company.com
(cs2) (Config)#ip name server 10.10.99.1 10.10.99.2
(cs2) (Config)#exit
(cs2) (Config)#
----
. NTP サーバを設定？
+
.. タイムゾーンと時刻の同期（ SNTP ）を設定します。
+
「 NTP 」

+
[listing]
----
(cs2) #
(cs2) (Config)#sntp client mode unicast
(cs2) (Config)#sntp server 10.99.99.5
(cs2) (Config)#clock timezone -7
(cs2) (Config)#exit
(cs2) (Config)#
----
.. 時間を手動で設定します。
+
「 clock 」

+
[listing]
----
(cs2) #config
(cs2) (Config)#no sntp client mode
(cs2) (Config)#clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST
(cs2) (Config)#clock timezone -5 zone EST
(cs2) (Config)#clock set 07:00:00
(cs2) (Config)#clock set 10/20/2020

(cs2) (Config)#show clock

07:00:11 EST(UTC-5:00) Oct 20 2020
No time source

(cs2) (Config)#exit

(cs2) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) **y**

Config file 'startup-config' created successfully .

Configuration Saved!
----



