---
permalink: switch-bes-53248/replace-switch.html 
sidebar: sidebar 
keywords: replace, replacing, defective, broadcom-supported, bes, cluster, switch, network, nondisruptive, procedure, ndu, replace a broadcom-supported bes-53428 cluster switch - bes-53428 switches 
summary: クラスタネットワーク内での、障害のある Broadcom 対応 BES-53248 クラスタスイッチの交換は、無停止手順（ NDU ）です。 
---
= Broadcom 対応 BES-53248 クラスタスイッチ BES-53248 スイッチを交換します
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタネットワーク内での、障害のある Broadcom 対応 BES-53248 クラスタスイッチの交換は、無停止手順（ NDU ）です。

現在の環境および交換用スイッチでスイッチの交換を実行する前に、次の条件が満たされている必要があります。

* 既存のクラスタとネットワークインフラ：
+
** 既存のクラスタで、少なくとも 1 つのクラスタスイッチが完全に接続されており、完全に機能することを確認する必要があります。
** すべてのクラスタポートが稼働している必要があります。
** すべてのクラスタ LIF が、管理上および運用上稼働した状態でホームポートにある必要があります。
** ONTAP の cluster ping-cluster -node node1 コマンドは 'basic connectivity' および larger than PMTU communication がすべてのパスで成功したことを示す必要があります


* BES-53248 の交換用クラスタスイッチ：
+
** 交換用スイッチの管理ネットワーク接続が機能している必要があります。
** 交換用スイッチへのコンソールアクセスが確立されている必要があります。
** ノード接続は、デフォルトのライセンスを使用したポート 0/1~0/16 です。
** ポート 0/55 および 0/56. では、すべてのスイッチ間リンク（ ISL ）ポートを無効にする必要があります。
** 目的のリファレンス構成ファイル（「 RCF 」）と「 EFOS 」オペレーティングシステムスイッチイメージをスイッチにロードする必要があります。
** スイッチの初期カスタマイズが完了している必要があります。詳細については、を参照してください xref:configure-new-switch.adoc[Broadcom 対応の新しい BES-53248 スイッチの構成]。
+
STP 、 SNMP 、 SSH などの以前のサイトのカスタマイズは、すべて新しいスイッチにコピーする必要があります。





この手順の例では、スイッチとノードで次の命名法を使用しています。

* 既存の BES-53248 スイッチの名前は「 cs1 」と「 cs2 」です。
* 新しい BES-53248 スイッチの名前は「 newcs2 」です。
* ノード名は 'node1 と node2 です
* 各ノードのクラスタ・ポートの名前は 'e0a' および e0b です
* クラスタ LIF 名は、 node1 の場合は「 node1_clus1' 」、ノード 1 の場合は「 node1_clus1' 」、 node2 の場合は「 node2 _ clus2 」です。
* すべてのクラスタ・ノードへの変更を求めるプロンプトは 'cluster1 ： > です



NOTE: 次の手順は、次のクラスタネットワークトポロジに基づいています。

[listing]
----
cluster1::> **network port show -ipspace Cluster**

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.


cluster1::> **network interface show -vserver Cluster**
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true

4 entries were displayed.



cluster1::> **network device-discovery show -protocol cdp**
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248

4 entries were displayed.


(cs1) # **show isdp neighbors**

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       175       H          FAS2750          e0a
node2                    0/2       152       H          FAS2750          e0a
cs2                      0/55      179       R          BES-53248        0/55
cs2                      0/56      179       R          BES-53248        0/56


(cs2) # **show isdp neighbors**

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       129       H          FAS2750          e0b
node2                    0/2       165       H          FAS2750          e0b
cs1                      0/55      179       R          BES-53248        0/55
cs1                      0/56      179       R          BES-53248        0/56
----
.手順
. 適切な RCF とイメージをスイッチ newcs2 にインストールし、必要なサイトの準備を行います。
+
必要に応じて、新しいスイッチ用に、 RCF および EFOS ソフトウェアの適切なバージョンを確認、ダウンロード、およびインストールします。新しいスイッチが正しくセットアップされており、 RCF および EFOS ソフトウェアのアップデートが不要であることを確認した場合は、手順 2 に進みます。

+
.. クラスタスイッチに適用可能な Broadcom EFOS ソフトウェアをからダウンロードできます https://www.broadcom.com/support/bes-switch["Broadcom Ethernet Switch のサポート"] サイトダウンロードページの手順に従って、インストールする ONTAP ソフトウェアのバージョンに対応する EFOS ファイルをダウンロードします。
.. 適切な RCF はから入手できます https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom クラスタスイッチ"] ページダウンロードページの手順に従って、インストールする ONTAP ソフトウェアのバージョンに対応する正しい RCF をダウンロードします。


. 新しいスイッチに admin としてログインし、ノードクラスタインターフェイス（ポート 1~16 ）に接続するすべてのポートをシャットダウンします。
+

NOTE: 追加ポート用の追加ライセンスを購入した場合は、それらのポートもシャットダウンします。

+
交換するスイッチが機能しておらず、電源がオフになっている場合は、クラスタノードの LIF が、各ノードのもう一方のクラスタポートにすでにフェイルオーバーされている必要があります。

+

NOTE: 「 enable 」モードを開始するためにパスワードは必要ありません。

+
[listing]
----
User:**admin**
Password:
(newcs2) >**enable**
(newcs2) #**config**
(newcs2)(config)#**interface 0/1-0/16**
(newcs2)(interface 0/1-0/16)#**shutdown**
(newcs2)(interface 0/1-0/16)#exit
(newcs2)(config)#exit
----
. すべてのクラスタ LIF で「 auto-revert 」が有効になっていることを確認します。
+
network interface show -vserver Cluster -fields auto-revert を実行します

+
[listing]
----

cluster1::> **network interface show -vserver Cluster -fields auto-revert**

Logical
Vserver   Interface    Auto-revert
--------- ------------ ------------
Cluster   node1_clus1  true
Cluster   node1_clus2  true
Cluster   node2_clus1  true
Cluster			node2_clus2		true

4 entries were displayed.
----
. BES-53248 スイッチ cs1 の ISL ポート 0/55 と 0/56 をシャットダウンします。
+
[listing]
----
(cs1) #**config**
(cs1)(config)#**interface 0/55-0/56**
(cs1)(interface 0/55-0/56)#**shutdown**
----
. すべてのケーブルを BES-53248 cs2 スイッチから取り外し、 BES-53248 newcs2 スイッチの同じポートに接続します。
. cs1 スイッチと newcs2 スイッチ間で ISL ポート 0/55 と 0/56 を起動し、ポートチャネルの動作ステータスを確認します。
+
ポートチャネル 1/1 のリンク状態は up になり、すべてのメンバーポートは Port Active ヘッダーで True になるはずです。

+
次に、 ISL ポート 0/55 および 0/56 を有効にし、スイッチ cs1 のポートチャネル 1/1 のリンク状態を表示する例を示します。

+
[listing]
----
(cs1) # **config**
(cs1)(config)# **interface 0/55-0/56**
(cs1)(interface 0/55-0/56)# **no shutdown**
(cs1) # **show port-channel 1/1**


Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port-channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------- -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
. 新しいスイッチ newcs2 で、ノードクラスタインターフェイス（ポート 1~16 ）に接続されているすべてのポートを再度有効にします。
+

NOTE: 追加ポート用の追加ライセンスを購入した場合は、それらのポートもシャットダウンします。

+
[listing]
----
User:admin
Password:
(newcs2) >enable
(newcs2) #config
(newcs2)(config)#interface 0/1-0/16
(newcs2)(interface 0/1-0/16)#no shutdown
(newcs2)(interface 0/1-0/16)#exit
(newcs2)(config)#exit
----
. ポート e0b が「 up 」になっていることを確認します。
+
「 network port show -ipspace cluster 」のように表示されます

+
次のような出力が表示されます。

+
[listing]
----
cluster1::> **network port show -ipspace Cluster**

Node: node1
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/auto   -        false

4 entries were displayed.
----
. 前の手順で使用したのと同じノードで、ノード 1 のクラスタ LIF node1_clus2 が自動リバートするまで待ちます。
+
この例では、「 Is Home 」が「 true 」でポートが e0b の場合、ノード 1 の LIF node1_clus2 は正常にリバートされています。

+
次のコマンドは、両方のノードの LIF に関する情報を表示します。両方のクラスタ・インターフェイスの Is Home が true の場合 ' 最初のノードの起動は成功し ' 正しいポート・アサインメントが表示されますこの例では 'e0a' と node1 の e0b を示します

+
[listing]
----
cluster::> **network interface show -vserver Cluster**

            Logical      Status     Network            Current    Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node       Port    Home
----------- ------------ ---------- ------------------ ---------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2      e0a     false

4 entries were displayed.
----
. クラスタ内のノードに関する情報を表示します cluster show
+
次の例では ' このクラスタの node1 と node2 のノードの正常性が true であることを示します

+
[listing]
----
cluster1::> **cluster show**
Node                   Health Eligibility    Epsilon
--------------------   ------- ------------  --------
node1                   true    true           true
node2                   true    true           true
----
. 次のクラスタネットワーク構成を確認します。
+
「 network port show 」のように表示されます

+
[listing]
----
cluster1::> **network port show -ipspace Cluster**
Node: node1
                                                                       Ignore
                                       Speed(Mbps)            Health   Health
Port      IPspace     Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ----------- ---------------- ---- ----- ----------- -------- ------
e0a       Cluster     Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster     Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                       Ignore
                                        Speed(Mbps)           Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000 auto/10000  healthy  false

4 entries were displayed.


cluster1::> **network interface show -vserver Cluster**

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.



cs1# **show cdp neighbors**

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID            Local Intrfce  Hldtme Capability  Platform      Port ID
node1                Eth1/1         144    H           FAS2980       e0a
node2                Eth1/2         145    H           FAS2980       e0a
newcs2(FDO296348FU)  Eth1/65        176    R S I s     N9K-C92300YC  Eth1/65
newcs2(FDO296348FU)  Eth1/66        176    R S I s     N9K-C92300YC  Eth1/66


Total entries displayed: 4


cs2# **show cdp neighbors**

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         139    H           FAS2980       e0b
node2              Eth1/2         124    H           FAS2980       e0b
cs1(FDO220329KU)   Eth1/65        178    R S I s     N9K-C92300YC  Eth1/65
cs1(FDO220329KU)   Eth1/66        178    R S I s     N9K-C92300YC  Eth1/66

Total entries displayed: 4
----
. クラスタネットワークが正常であることを確認します。
+
「 isdp 隣人」

+
[listing]
----
(cs1) # show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater
Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     175         H             FAS2750     e0a
node2        0/2     152         H             FAS2750     e0a
newcs2       0/55    179         R             BES-53248   0/55
newcs2       0/56    179         R             BES-53248   0/56

(newcs2) # show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater

Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     129         H             FAS2750     e0b
node2        0/2     165         H             FAS2750     e0b
cs1          0/55    179         R             BES-53248   0/55
cs1          0/56    179         R             BES-53248   0/56
----


を参照してください link:configure-log-collection.html["クラスタスイッチのログ収集機能を設定しています"] スイッチ関連のログファイルの収集に使用されるクラスタ健常性スイッチのログ収集を有効にするために必要な手順については、を参照してください。

* 関連情報 *

https://mysupport.netapp.com/["ネットアップサポートサイト"]

https://hwu.netapp.com/["NetApp Hardware Universe の略"]

http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-sw-ix8-setup/home.html["『 Switch Setup and Configuration Guide for Broadcom Supported BES-53248 switches 』を参照してください"]
