---
permalink: switch-bes-53248/replace-switch.html 
sidebar: sidebar 
keywords: replace, replacing, defective, broadcom-supported, bes, cluster, switch, network, nondisruptive, procedure, ndu, replace a broadcom-supported bes-53428 cluster switch - bes-53428 switches 
summary: 'クラスタ ネットワーク内の障害のある Broadcom 対応 BES-53248 クラスタ スイッチを交換することは、無停止の手順 (NDU) です。' 
---
= Broadcom対応のBES-53248クラスタスイッチを交換する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ ネットワーク内の障害のある Broadcom 対応 BES-53248 クラスタ スイッチを交換するには、次の手順に従います。これは非中断手順 (NDU) です。

.例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 既存のBES-53248スイッチの名前は `cs1`そして `cs2`。
* 新しいBES-53248スイッチの名前は `newcs2`。
* ノード名は `node1`そして `node2`。
* 各ノードのクラスタポートの名前は `e0a`そして `e0b`。
* クラスタLIF名は `node1_clus1`そして `node1_clus2`ノード1の場合、 `node2_clus1`そして `node2_clus2`ノード2用。
* すべてのクラスタノードへの変更を求めるプロンプトは `cluster1::>`


.トポロジについて
この手順は、次のクラスター ネットワーク トポロジに基づいています。

.トポロジ例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


cluster1::> *network interface show -vserver Cluster*
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true


cluster1::> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       175       H          FAS2750          e0a
node2                    0/2       152       H          FAS2750          e0a
cs2                      0/55      179       R          BES-53248        0/55
cs2                      0/56      179       R          BES-53248        0/56


(cs2)# show isdp neighbors

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       129       H          FAS2750          e0b
node2                    0/2       165       H          FAS2750          e0b
cs1                      0/55      179       R          BES-53248        0/55
cs1                      0/56      179       R          BES-53248        0/56
----
====
.手順
. レビューlink:replace-switch-reqs.html["交換要件"]。
. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
ここで、_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

+

NOTE: AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

. 適切なリファレンス コンフィギュレーション ファイル (RCF) とイメージをスイッチ newcs2 にインストールし、必要なサイトの準備を行います。
+
必要に応じて、新しいスイッチに適したバージョンの RCF および EFOS ソフトウェアを確認し、ダウンロードしてインストールします。新しいスイッチが正しくセットアップされ、RCF および EFOS ソフトウェアの更新が必要ないことを確認した場合は、手順 2 に進みます。

+
.. クラスタスイッチに適したBroadcom EFOSソフトウェアは、次のサイトからダウンロードできます。 https://www.broadcom.com/support/bes-switch["Broadcomイーサネット スイッチのサポート"^]サイト。[Download]ページの手順に従って、インストールするONTAPソフトウェアのバージョンに対応したEFOSファイルをダウンロードします。
.. 適切なRCFは、 https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom クラスタスイッチ"^]ページ。[Download]ページの手順に従って、インストールするONTAPソフトウェアのバージョンに対応したRCFをダウンロードします。


. 新しいスイッチで、 `admin`ノード クラスタ インターフェイスに接続されるすべてのポート (ポート 1 ～ 16) をシャットダウンします。
+

NOTE: 追加ポート用のライセンスを購入した場合は、それらのポートもシャットダウンします。

+
交換するスイッチが機能しておらず、電源がオフになっている場合は、各クラスタ ノードのLIFはもう一方のクラスタ ポートにすでにフェイルオーバーされています。

+

NOTE: パスワードは必要ありません `enable`モード。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
User: *admin*
Password:
(newcs2)> *enable*
(newcs2)# *config*
(newcs2)(config)# *interface 0/1-0/16*
(newcs2)(interface 0/1-0/16)# *shutdown*
(newcs2)(interface 0/1-0/16)# *exit*
(newcs2)(config)# *exit*
(newcs2)#
----
====
. すべてのクラスタLIFが `auto-revert`有効:
+
`network interface show -vserver Cluster -fields auto-revert`

+
.トポロジ例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster -fields auto-revert*

Logical
Vserver   Interface    Auto-revert
--------- ------------ ------------
Cluster   node1_clus1  true
Cluster   node1_clus2  true
Cluster   node2_clus1  true
Cluster   node2_clus2  true
----
====
. BES-53248 スイッチ cs1 の ISL ポート 0/55 と 0/56 をシャットダウンします。
+
.トポロジ例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *config*
(cs1)(config)# *interface 0/55-0/56*
(cs1)(interface 0/55-0/56)# *shutdown*
----
====
. BES-53248 cs2 スイッチからすべてのケーブルを取り外し、それらを BES-53248 newcs2 スイッチの同じポートに接続します。
. cs1スイッチとnewcs2スイッチ間でISLポート0/55と0/56を起動し、ポート チャネルの動作ステータスを確認します。
+
ポート チャネル 1/1 のリンク状態は *up* で、Port Active 見出しの下にあるすべてのメンバー ポートが True になっている必要があります。

+
.例を表示
[%collapsible]
====
この例では、ISL ポート 0/55 および 0/56 を有効にし、スイッチ cs1 のポート チャネル 1/1 のリンク状態を表示します。

[listing, subs="+quotes"]
----
(cs1)# *config*
(cs1)(config)# *interface 0/55-0/56*
(cs1)(interface 0/55-0/56)# *no shutdown*
(cs1)(interface 0/55-0/56)# *exit*
(cs1)# *show port-channel 1/1*

Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port-channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------- -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 新しいnewcs2スイッチで、ノード クラスタ インターフェイス（ポート1～16）に接続されているすべてのポートを再度有効にします。
+

NOTE: 追加ポート用のライセンスを購入した場合は、それらのポートもシャットダウンします。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
User:admin
Password:
(newcs2)> *enable*
(newcs2)# *config*
(newcs2)(config)# *interface 0/1-0/16*
(newcs2)(interface 0/1-0/16)# *no shutdown*
(newcs2)(interface 0/1-0/16)# *exit*
(newcs2)(config)# *exit*
----
====
. ポート e0b が *up* であることを確認します。
+
`network port show -ipspace Cluster`

+
.例を表示
[%collapsible]
====
次のような出力が表示されます。

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/auto   -        false
----
====
. 前の手順で使用したのと同じノードで、node1 のクラスター LIF node1_clus2 が自動的に元に戻るまで待機します。
+
.例を表示
[%collapsible]
====
この例では、ノード1のLIF node1_clus2は、 `Is Home`は `true`ポートは e0b です。

次のコマンドは、両方のノードの LIF に関する情報を表示します。最初のノードの起動が成功した場合、 `Is Home`は `true`両方のクラスタインターフェースで正しいポート割り当てが表示されています。この例では `e0a`そして `e0b`ノード1上。

[listing, subs="+quotes"]
----
cluster::> *network interface show -vserver Cluster*

            Logical      Status     Network            Current    Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node       Port    Home
----------- ------------ ---------- ------------------ ---------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2      e0a     false
----
====
. クラスター内のノードに関する情報を表示します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
この例では、 `node1`そして `node2`このクラスターでは `true`:

[listing, subs="+quotes"]
----
cluster1::> *cluster show*
Node   Health   Eligibility   Epsilon
------ -------- ------------  --------
node1  true     true          true
node2  true     true          true
----
====
. 次のクラスター ネットワーク構成を確認します。
+
`network port show`

+
`network interface show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*
Node: node1
                                                                       Ignore
                                       Speed(Mbps)            Health   Health
Port      IPspace     Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ----------- ---------------- ---- ----- ----------- -------- ------
e0a       Cluster     Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster     Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                       Ignore
                                        Speed(Mbps)           Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000 auto/10000  healthy  false


cluster1::> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
====
. クラスター ネットワークが正常であることを確認します。
+
`show isdp neighbors`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater
Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     175         H             FAS2750     e0a
node2        0/2     152         H             FAS2750     e0a
newcs2       0/55    179         R             BES-53248   0/55
newcs2       0/56    179         R             BES-53248   0/56

(newcs2)# *show isdp neighbors*
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater

Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     129         H             FAS2750     e0b
node2        0/2     165         H             FAS2750     e0b
cs1          0/55    179         R             BES-53248   0/55
cs1          0/56    179         R             BES-53248   0/56
----
====
. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.次の手順
スイッチを交換したら、 link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを設定する"]。
