---
permalink: switch-bes-53248/replace-install-rcf.html 
sidebar: sidebar 
keywords: rcf,install rcf,bes-53248 switch 
summary: RCF は、 BES-53248 クラスタスイッチを初めてセットアップしたあとと、新しいライセンスを適用したあとにインストールできます。古いバージョンから RCF をアップグレードする場合、ファイルは効果的にマージされ、ここで説明する手順を実行します。 
---
= リファレンス構成ファイル（ RCF ）のインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RCF は、 BES-53248 クラスタスイッチを初めてセットアップしたあとと、新しいライセンスを適用したあとにインストールできます。古いバージョンから RCF をアップグレードする場合は、 Broadcom スイッチの設定をリセットし、基本的な設定を行って RCF を再適用する必要があります。この処理は、 RCF をアップグレードまたは変更するたびに実行する必要があります。以下を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/Error!_in_configuration_script_file_at_line_number_XX_when_applying_a_new_RCF["こちらの技術情報アーティクル"^] を参照してください。



== Broadcom IP スイッチを工場出荷時のデフォルトにリセットします

新しいバージョンのスイッチソフトウェアと RCF をインストールする前に、 Broadcom スイッチの設定を消去し、基本的な設定を完了する必要があります。

.このタスクについて
* この手順は各クラスタスイッチで実行する必要があります。
* シリアルコンソールを使用してスイッチに接続する必要があります。
* このタスクでは、管理ネットワークの設定をリセットします。


.手順
. 昇格されたコマンドプロンプト (`#`):'enable' に変更します
+
[listing]
----
(cs2)> enable
(cs2) #
----
. スタートアップコンフィギュレーションを消去し、バナーを削除します
+
.. スタートアップ設定を消去します。
+
*`erase startup-config *

+
[listing]
----
(cs2) #erase startup-config
Are you sure you want to clear the configuration? (y/n) y
(cs2) #
----
+
このコマンドでは、バナーは消去されません。

.. バナーを削除します。
+
*`no set clibanner`*

+
[listing]
----
(cs2) #configure
(cs2)(Config) # no set clibanner
(cs2)(Config) #
----


. スイッチを再起動します *`(CS2)#reload*`
+
[listing]
----
Are you sure you would like to reset the system? (y/n) y
----
+

NOTE: スイッチをリロードする前に、未保存または変更された設定を保存するかどうかを確認するメッセージが表示された場合は、 *No* を選択します。

. スイッチがリロードされるまで待ってから、スイッチにログインします。
+
デフォルトのユーザは「 admin 」で、パスワードは設定されていません。次のようなプロンプトが表示されます。

+
[listing]
----
(Routing)>
----
. 管理者特権のコマンドプロンプトに切り替えます。
+
「 enable 」を選択します

+
[listing]
----
Routing)> enable
(Routing) #
----
. サービスポートプロトコルを「 none 」に設定します。
+
「サービスポートプロトコルなし」

+
[listing]
----
(Routing) #serviceport protocol none
Changing protocol mode will reset ip configuration.
Are you sure you want to continue? (y/n) y

(Routing) #
----
. サービスポートに IP アドレスを割り当てます。
+
'erviceport IP_address__netmask__ gateway_

+
次の例では、サービスポートに IP アドレス「 10.10.10.10 」が割り当てられています。サブネットは「 255.255.255.0 」、ゲートウェイは「 10.10.10.1 」です。

+
[listing]
----
(Routing) #serviceport ip 10.10.10.10 255.255.255.0 10.10.10.1
----
. サービスポートが正しく設定されていることを確認します。
+
'How serviceport

+
次の例は、ポートが稼働しており、正しいアドレスが割り当てられていることを示しています。

+
[listing]
----
(Routing) #show serviceport

Interface Status............................... Up
IP Address..................................... 10.10.10.10
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 10.10.10.1
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe56:87d7/64
IPv6 Default Router............................ fe80::222:bdff:fef8:19ff
Configured IPv4 Protocol....................... None
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:56:87:D7

(Routing) #
----
. 必要に応じて、 SSH サーバを設定します。
+

NOTE: RCF ファイルで Telnet プロトコルが無効になります。SSH サーバを設定しない場合は、シリアルポート接続を使用してブリッジにアクセスする必要があります。

+
.. RSA キーを生成します。
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate rsa
----
.. DSA キーの生成（オプション）
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate dsa
----
.. FIPS 準拠バージョンの EFOS を使用している場合は、 ECDSA キーを生成します。次の例では、長さ 256 のキーを作成します。有効な値は、 256 、 384 、または 521 です。
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate ecdsa 256
----
.. SSH サーバを有効にします。
+
必要に応じて、設定コンテキストを終了します。

+
[listing]
----
(Routing) (Config)#end
(Routing) #ip ssh server enable
----
+

NOTE: キーがすでに存在する場合は、それらを上書きするように求められることがあります。



. 必要に応じて、ドメインとネームサーバを設定します。
+
「 configure 」を実行します

+
次に 'ip domain' コマンドと 'ip name server' コマンドの例を示します

+
[listing]
----
(Routing) # configure
(Routing) (Config)#ip domain name lab.netapp.com
(Routing) (Config)#ip name server 10.99.99.1 10.99.99.2
(Routing) (Config)#exit
(Routing) (Config)#
----
. 必要に応じて、タイムゾーンと時刻の同期（ SNTP ）を設定します。
+
次に 'ntp' コマンドの例を示しますこの例では 'sntp サーバの IP アドレスと相対タイム・ゾーンを指定します

+
[listing]
----
(Routing) #
(Routing) (Config)#sntp client mode unicast
(Routing) (Config)#sntp server 10.99.99.5
(Routing) (Config)#clock timezone -7
(Routing) (Config)#exit
(Routing) (Config)#
----
. スイッチ名を設定します。
+
ホスト名 CS2

+
スイッチのプロンプトに新しい名前が表示されます。

+
[listing]
----
(Routing) # hostname cs2

(cs2) #
----
. 設定を保存します。
+
「メモリの書き込み」

+
次の例のようなプロンプトと出力が表示されます。

+
[listing]
----
(cs2) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .


Configuration Saved!

(cs2) #
----
. もう一方のクラスタスイッチで、上記の手順を繰り返します。




== リファレンス構成ファイル（ RCF ）のインストール

.手順
. クラスタスイッチを管理ネットワークに接続します。
. ping コマンドを使用して、 EFOS 、ライセンス、 RCF をホストするサーバへの接続を確認します。
+
接続が問題の場合は、ルーティングされていないネットワークを使用し、 IP アドレス 192.168.x または 172.19.x を使用してサービスポートを設定しますサービスポートは、あとで本番用の管理 IP アドレスに再設定できます。

+
次の例では、スイッチが IP アドレス 172.19.2.1 のサーバに接続されていることを確認します。

+
[listing]
----
(cs2) # ping 172.19.2.1
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. copy コマンドを使用して、 BES-53248 クラスタスイッチに RCF をインストールします。
+
[listing]
----
(cs2) # copy http://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr

Remote Password ********

Mode........................................... HTTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... BES-53248_RCF_v1.6-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_RCF_v1.6-Cluster-HA.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...

Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
+

NOTE: 環境によっては '+copy のように 'copy コマンドで二重スラッシュを使用する必要があります http://172.19.2.1//tmp/BES-53248_RCF_v1.6-Cluster-HA.txt[] NVRAM ：スクリプト BES-53248 RCF_v1.6 - Cluster-HA.scr +` 。

+

NOTE: スクリプトを呼び出す前に '.scr 拡張子をファイル名の一部として設定する必要がありますこれは、 EFOS オペレーティングシステムの拡張子です。スクリプトがスイッチにダウンロードされると、スイッチはスクリプトを自動的に検証し、コンソールに出力が表示されます。また ' 読みやすくするために '.scr の名前をコンソール画面に合わせて変更することもできますたとえば '+copy のようにします http://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt[] NVRAM ：スクリプト rcf_v1.6 - Cluster-HA.scr +` 。

. スクリプトがダウンロードされ、指定したファイル名で保存されていることを確認します。
+
「原稿リスト」

+
[listing]
----
(cs2) # script list

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
BES-53248_RCF_v1.6-Cluster-HA.scr        2241         2020 09 30 05:41:00

1 configuration script(s) found.
----
. スクリプトをスイッチに適用します。
+
「原稿」が適用されます

+
[listing]
----
(cs2) # script apply BES-53248_RCF_v1.6-Cluster-HA.scr

Are you sure you want to apply the configuration script? (y/n) y

The system has unsaved changes.
Would you like to save them now? (y/n) y
Config file 'startup-config' created successfully .
Configuration Saved!

Configuration script 'BES-53248_RCF_v1.6-Cluster-HA.scr' applied.
----
. RCF を適用したあとに、追加ライセンスのポートを確認します。
+
'How port All | exclude Detach'

+
[listing]
----
(cs2) # show port all \| exclude Detach

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----
. スイッチで変更が行われたことを確認します。
+
'how running-config'

+
[listing]
----
(cs2) # show running-config
----
. スイッチをリブートしたときにスタートアップコンフィギュレーションになるように、実行コンフィギュレーションを保存します。
+
「メモリの書き込み」

+
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
. スイッチをリブートし、実行コンフィギュレーションが正しいことを確認します。
+
「再ロード」

+
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n) y

System will now restart!
----

