---
permalink: switch-bes-53248/replace-switch.html 
sidebar: sidebar 
keywords: replace, replacing, defective, broadcom-supported, bes, cluster, switch, network, nondisruptive, procedure, ndu, replace a broadcom-supported bes-53428 cluster switch - bes-53428 switches 
summary: クラスタネットワーク内での、障害のある Broadcom 対応 BES-53248 クラスタスイッチの交換は、無停止手順（ NDU ）です。 
---
= Broadcom対応BES-53248クラスタスイッチを交換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタネットワーク内の障害のあるBroadcom対応BES-53248クラスタスイッチを交換するには、次の手順を実行します。これは、無停止の手順 （NDU；非停止アップグレード）です。

.例について
この手順の例では、スイッチとノードで次の命名法を使用しています。

* 既存の BES-53248 スイッチの名前は「 cs1 」と「 cs2 」です。
* 新しい BES-53248 スイッチの名前は「 newcs2 」です。
* ノード名は 'node1 と node2 です
* 各ノードのクラスタ・ポートの名前は 'e0a' および e0b です
* クラスタ LIF 名は、 node1 の場合は「 node1_clus1' 」、ノード 1 の場合は「 node1_clus1' 」、 node2 の場合は「 node2 _ clus2 」です。
* すべてのクラスタ・ノードへの変更を求めるプロンプトは 'cluster1 ： > です


.トポロジについて
この手順 は、次のクラスタネットワークトポロジに基づいています。

.トポロジの例を表示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


cluster1::> *network interface show -vserver Cluster*
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true


cluster1::> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       175       H          FAS2750          e0a
node2                    0/2       152       H          FAS2750          e0a
cs2                      0/55      179       R          BES-53248        0/55
cs2                      0/56      179       R          BES-53248        0/56


(cs2)# show isdp neighbors

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       129       H          FAS2750          e0b
node2                    0/2       165       H          FAS2750          e0b
cs1                      0/55      179       R          BES-53248        0/55
cs1                      0/56      179       R          BES-53248        0/56
----
====
.手順
. を確認します link:replace-switch-reqs.html["交換に際しての要件"]。
. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= xh 」というメッセージが表示されます

+
ここで、 _ x _ はメンテナンス時間の長さ（時間）です。

+

NOTE: AutoSupport メッセージはテクニカルサポートにこのメンテナンスタスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

. 適切なリファレンス構成ファイル（RCF）とイメージをスイッチnewcs2にインストールし、必要なサイトの準備を行います。
+
必要に応じて、新しいスイッチ用に、 RCF および EFOS ソフトウェアの適切なバージョンを確認、ダウンロード、およびインストールします。新しいスイッチが正しくセットアップされており、 RCF および EFOS ソフトウェアのアップデートが不要であることを確認した場合は、手順 2 に進みます。

+
.. クラスタスイッチに適用可能な Broadcom EFOS ソフトウェアをからダウンロードできます https://www.broadcom.com/support/bes-switch["Broadcom Ethernet Switch のサポート"^] サイトダウンロードページの手順に従って、インストールする ONTAP ソフトウェアのバージョンに対応する EFOS ファイルをダウンロードします。
.. 適切な RCF はから入手できます https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom クラスタスイッチ"^] ページダウンロードページの手順に従って、インストールする ONTAP ソフトウェアのバージョンに対応する正しい RCF をダウンロードします。


. 新しいスイッチに、としてログインします `admin` ノードクラスタインターフェイス（ポート1~16）に接続するすべてのポートをシャットダウンします。
+

NOTE: 追加ポート用の追加ライセンスを購入した場合は、それらのポートもシャットダウンします。

+
交換するスイッチが機能しておらず、電源がオフになっている場合は、クラスタノードの LIF が、各ノードのもう一方のクラスタポートにすでにフェイルオーバーされている必要があります。

+

NOTE: 「 enable 」モードを開始するためにパスワードは必要ありません。

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
User: *admin*
Password:
(newcs2)> *enable*
(newcs2)# *config*
(newcs2)(config)# *interface 0/1-0/16*
(newcs2)(interface 0/1-0/16)# *shutdown*
(newcs2)(interface 0/1-0/16)# *exit*
(newcs2)(config)# *exit*
(newcs2)#
----
====
. すべてのクラスタ LIF で「 auto-revert 」が有効になっていることを確認します。
+
network interface show -vserver Cluster -fields auto-revert を実行します

+
.トポロジの例を表示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster -fields auto-revert*

Logical
Vserver   Interface    Auto-revert
--------- ------------ ------------
Cluster   node1_clus1  true
Cluster   node1_clus2  true
Cluster   node2_clus1  true
Cluster   node2_clus2  true
----
====
. BES-53248 スイッチ cs1 の ISL ポート 0/55 と 0/56 をシャットダウンします。
+
.トポロジの例を表示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *config*
(cs1)(config)# *interface 0/55-0/56*
(cs1)(interface 0/55-0/56)# *shutdown*
----
====
. すべてのケーブルを BES-53248 cs2 スイッチから取り外し、 BES-53248 newcs2 スイッチの同じポートに接続します。
. cs1 スイッチと newcs2 スイッチ間で ISL ポート 0/55 と 0/56 を起動し、ポートチャネルの動作ステータスを確認します。
+
ポートチャネル1/1のリンク状態は* up *になり、すべてのメンバーポートはPort ActiveヘッダーでTrueになるはずです。

+
.例を示します
[%collapsible]
====
次に、 ISL ポート 0/55 および 0/56 を有効にし、スイッチ cs1 のポートチャネル 1/1 のリンク状態を表示する例を示します。

[listing, subs="+quotes"]
----
(cs1)# *config*
(cs1)(config)# *interface 0/55-0/56*
(cs1)(interface 0/55-0/56)# *no shutdown*
(cs1)(interface 0/55-0/56)# *exit*
(cs1)# *show port-channel 1/1*

Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port-channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------- -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 新しいスイッチ newcs2 で、ノードクラスタインターフェイス（ポート 1~16 ）に接続されているすべてのポートを再度有効にします。
+

NOTE: 追加ポート用の追加ライセンスを購入した場合は、それらのポートもシャットダウンします。

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
User:admin
Password:
(newcs2)> *enable*
(newcs2)# *config*
(newcs2)(config)# *interface 0/1-0/16*
(newcs2)(interface 0/1-0/16)# *no shutdown*
(newcs2)(interface 0/1-0/16)# *exit*
(newcs2)(config)# *exit*
----
====
. ポートe0bが* up *になっていることを確認します。
+
「 network port show -ipspace cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
次のような出力が表示されます。

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/auto   -        false
----
====
. 前の手順で使用したのと同じノードで、ノード 1 のクラスタ LIF node1_clus2 が自動リバートするまで待ちます。
+
.例を示します
[%collapsible]
====
この例では、「 Is Home 」が「 true 」でポートが e0b の場合、ノード 1 の LIF node1_clus2 は正常にリバートされています。

次のコマンドは、両方のノードの LIF に関する情報を表示します。両方のクラスタ・インターフェイスの Is Home が true の場合 ' 最初のノードの起動は成功し ' 正しいポート・アサインメントが表示されますこの例では 'e0a' と node1 の e0b を示します

[listing, subs="+quotes"]
----
cluster::> *network interface show -vserver Cluster*

            Logical      Status     Network            Current    Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node       Port    Home
----------- ------------ ---------- ------------------ ---------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2      e0a     false
----
====
. クラスタ内のノードに関する情報を表示します。
+
「 cluster show 」を参照してください

+
.例を示します
[%collapsible]
====
次の例では ' このクラスタの node1 と node2 のノードの正常性が true であることを示します

[listing, subs="+quotes"]
----
cluster1::> *cluster show*
Node   Health   Eligibility   Epsilon
------ -------- ------------  --------
node1  true     true          true
node2  true     true          true
----
====
. 次のクラスタネットワーク構成を確認します。
+
「 network port show 」のように表示されます

+
「 network interface show 」を参照してください

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*
Node: node1
                                                                       Ignore
                                       Speed(Mbps)            Health   Health
Port      IPspace     Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ----------- ---------------- ---- ----- ----------- -------- ------
e0a       Cluster     Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster     Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                       Ignore
                                        Speed(Mbps)           Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000 auto/10000  healthy  false


cluster1::> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
====
. クラスタネットワークが正常であることを確認します。
+
「 isdp 隣人」

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater
Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     175         H             FAS2750     e0a
node2        0/2     152         H             FAS2750     e0a
newcs2       0/55    179         R             BES-53248   0/55
newcs2       0/56    179         R             BES-53248   0/56

(newcs2)# *show isdp neighbors*
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater

Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     129         H             FAS2750     e0b
node2        0/2     165         H             FAS2750     e0b
cs1          0/55    179         R             BES-53248   0/55
cs1          0/56    179         R             BES-53248   0/56
----
====
. ケースの自動作成を抑制した場合は、 AutoSupport メッセージを呼び出して作成を再度有効にします。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます



.次の手順
を参照してください link:configure-log-collection.html["ログ収集機能を有効にします"] スイッチ関連のログファイルの収集に使用されるクラスタ健常性スイッチのログ収集を有効にするために必要な手順については、を参照してください。
