---
permalink: switch-bes-53248/replace-configure-new-switch.html 
sidebar: sidebar 
keywords: BES-53248 switches,initial installation,new install 
summary: この章で説明する手順を実行すると、新しい BES-53248 クラスタスイッチを構成できます。 
---
= 新しい BES-53248 クラスタスイッチを構成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この章で説明する手順を実行すると、新しい BES-53248 クラスタスイッチを構成できます。

ONTAP を実行しているシステムに BES-53248 クラスタスイッチを取り付けるには、まず IP アドレスと構成を設定して、スイッチが管理インターフェイスを介して通信できるようにします。次に、イーサネットファブリック OS （ EFOS ）ソフトウェア、リファレンス構成ファイル（ RCF ）、およびその他のライセンスを必要に応じてインストールできます。この手順は、コントローラを追加する前に BES-53248 スイッチを準備するためのものです。さらに、 BES-53248 クラスタスイッチのクラスタスイッチヘルスモニタ（ CSHM ）をサポートするために必要な構成ファイルのインストールが必要になる場合があります。を参照してください link:replace_install_cshm_file.md#GUID-53ED7CFF-35AD-4D01-BDAF-CA17ABF3AD4E["クラスタスイッチヘルスモニタ（ CSHM ）構成ファイルのインストール"] 詳細：

この手順の例では、スイッチとノードで次の命名法を使用しています。

* ネットアップのスイッチ名は cs1 と cs2 です。
* この手順で使用している例では、 2 番目のスイッチ _cs2 でアップグレードが開始されます。 _
* クラスタ LIF の名前は、ノード 1 では node1_clus1 と node1_clus2 、ノード 2 では node2_clus1 と node2_clus2 です。
* IPspace 名は Cluster です。
* 「 cluster1 ：： > 」プロンプトは、クラスタの名前を示します。
* 各ノードのクラスタポートの名前は e0a および e0b です。
+
プラットフォームでサポートされている実際のクラスタポートについては、 Hardware Universe を参照してください。

+
https://hwu.netapp.com/Home/Index["NetApp Hardware Universe の略"^]

* ネットアップのスイッチでサポートされているスイッチ間リンク（ ISL ）は、ポート 0/55 と 0/56 です。
* ネットアップのスイッチでサポートされているノード接続は、デフォルトのライセンスを使用したポート 0/1~0/16 です。
* この手順の例では 2 つのノードを使用していますが、 1 つのクラスタには最大 24 のノードを含めることができます。

