---
permalink: switch-bes-53248/replace-required-documentation.html 
sidebar: sidebar 
keywords: documentation requirements, BES-53248 switches,cluster switches 
summary: clustered Data ONTAP 構成をセットアップするには、特定のスイッチとコントローラに関するドキュメントが必要です。 
---
= BES-53248 クラスタスイッチにはドキュメントが必要です
:icons: font
:imagesdir: ../media/


[role="lead"]
clustered Data ONTAP 構成をセットアップするには、特定のスイッチとコントローラに関するドキュメントが必要です。



== BES-53248 クラスタスイッチに必要なドキュメント

BES-53248 クラスタスイッチをセットアップするには、 Broadcom サポートサイトから次のドキュメントを入手する必要があります。 https://www.broadcom.com/support/bes-switch["Broadcom Ethernet Switch 製品ライン"^]

[cols="1,2"]
|===
| ドキュメントタイトル | 説明 


 a| 
_ EFOS 管理者ガイド v3.4.3_
 a| 
一般的なネットワークで BES-53248 スイッチを使用する方法の例を示します。



 a| 
_ EFOS CLI コマンドリファレンス v3.4.3_
 a| 
BES-53248 ソフトウェアの表示と設定に使用するコマンドラインインターフェイス（ CLI ）コマンドについて説明します。



 a| 
_ EFOS セットアップガイド v3.4.3_
 a| 
BES-53248 スイッチの詳細情報を提供します。



 a| 
_ EFOS SNMP リファレンスガイド v3.4.3_
 a| 
一般的なネットワークで BES-53248 スイッチを使用する方法の例を示します。



 a| 
_ EFOS スケーリングパラメータと値 v3.4.3_
 a| 
EFOS ソフトウェアと一緒に提供され、サポート対象プラットフォームで検証済みのデフォルトのスケールパラメータについて説明します。



 a| 
_ EFOS 機能仕様 v3.4.3_
 a| 
サポート対象プラットフォームでの EFOS ソフトウェアの仕様を示します。



 a| 
_ EFOS リリースノート v3.4.3_
 a| 
BES-53248 ソフトウェアに関するリリース固有の情報を示します。

|===


== サポートされている ONTAP システムに必要なドキュメント

ONTAP システムをセットアップするには、ネットアップサポートサイトから次のドキュメントを入手する必要があります http://mysupport.netapp.com/["mysupport.netapp.com"^]

[cols="1,2"]
|===
| 名前 | 説明 


 a| 
_ Hardware Universe _
 a| 
システムキャビネットを含むすべてのネットアップハードウェアの電源要件とサイト要件について説明します。



 a| 
コントローラ固有の設置およびセットアップ手順 _
 a| 
ネットアップハードウェアの設置方法について説明します。



 a| 
ONTAP 9
 a| 
ONTAP 9 リリースのすべての側面に関する詳細情報を提供します。

|===