---
permalink: switch-bes-53248/replace-upgrade.html 
sidebar: sidebar 
keywords: BES-53248 switches,upgrading,BES-53248 switches 
summary: BES-53248 クラスタスイッチをアップグレードするには、アップグレードのためのコントローラの準備、 EFOS ソフトウェア、ライセンス、リファレンス構成ファイル \ （ RCF \ ）のインストールを開始します。インストールが完了したら、無停止アップグレード（ NDU ）および無停止運用（ NDO ）環境でコントローラ構成をリストアできます。 
---
= BES-53248クラスタスイッチをアップグレードします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248クラスタスイッチをアップグレードするには、次の手順を実行します。

この 手順 環境 は正常に動作しているクラスタであり、無停止アップグレード（NDU）およびノンストップオペレーション（NDO）環境を実現します。



== 要件を確認

既存のNetApp BES-53248クラスタスイッチにEFOSソフトウェア、ライセンス、RCFファイルをインストールする前に、次の点を確認します。

* クラスタは完全に機能している（エラーログメッセージやその他の問題がない）。
* クラスタには欠陥のあるクラスタネットワークインターフェイスカード（NIC）がありません。
* 両方のクラスタスイッチで接続されているすべてのポートが機能しています。
* すべてのクラスタポートが稼働している必要があります
* すべてのクラスタLIFが、管理上および運用上稼働した状態でホームポートにあること。
* 各ノードの最初の2つのクラスタLIFは別 々 のNICに設定されており、別 々 のクラスタスイッチポートに接続されています。
* ONTAP `cluster ping-cluster -node node1` advanced権限のコマンドは、を示します `larger than PMTU communication` はすべてのパスで成功しています。



NOTE: RCF バージョンと EFOS バージョンのコマンド構文の間に、コマンドの依存関係がある場合があります。


NOTE: スイッチの互換性については、の互換性の表を参照してください https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom クラスタスイッチ"^] サポートされているEFOS、RCF、ONTAP のバージョンに関するページです。



== コントローラを準備

この手順 に従って、BES-53248クラスタスイッチのアップグレード用にコントローラを準備します。

.手順
. クラスタスイッチを管理ネットワークに接続します。
. ping コマンドを使用して、 EFOS 、ライセンス、 RCF をホストするサーバへの接続を確認します。
+
問題の場合は、ルーティングされていないネットワークを使用し、 IP アドレス 192.168.x または 172.19.x を使用してサービスポートを設定しますサービスポートは、あとで本番用の管理 IP アドレスに再設定できます。

+
.例を示します
[%collapsible]
====
次の例では、スイッチが IP アドレス 172.19.2.1 のサーバに接続されていることを確認します。

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 次のコマンドを使用して、クラスタポートが正常であり、リンクがあることを確認します。
+
「 network port show -ipspace cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例は ' すべてのポートの Link 値が up で Health Status が healthy である出力のタイプを示しています

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. コマンドを使用して、クラスタ LIF が管理上および運用上稼働した状態でホームポートにあることを確認します。
+
「 network interface show -vserver Cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
この例では、「 -vserver 」パラメータは、クラスタポートに関連付けられている LIF に関する情報を表示します。'tatus Admin/Oper' は up であり 'Is Home' は true である必要があります

[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster*

          Logical      Status     Network             Current       Current Is
Vserver   Interface    Admin/Oper Address/Mask        Node          Port    Home
--------- ----------   ---------- ------------------  ------------- ------- ----
Cluster
          node1_clus1
                       up/up      169.254.217.125/16  node1         e0a     true
          node1_clus2
                       up/up      169.254.205.88/16   node1         e0b     true
          node2_clus1
                       up/up      169.254.252.125/16  node2         e0a     true
          node2_clus2
                       up/up      169.254.110.131/16  node2         e0b     true
----
====




== ソフトウェアをインストールします

以下の手順に従って、ソフトウェアをインストールします。

. link:configure-efos-software.html["EFOS ソフトウェアをインストールします"]。イーサネットファブリックOS（EFOS）ソフトウェアをBES-53248クラスタスイッチにダウンロードしてインストールします。
. link:configure-licenses.html["BES-53248 クラスタスイッチのライセンスをインストールします"]。必要に応じて、ライセンスを購入してインストールすることで新しいポートを追加します。スイッチベースモデルには、16個の10GbEまたは25GbEポートと2個の100GbEポートがライセンスされています。
. link:configure-install-rcf.html["リファレンス構成ファイル（ RCF ）のインストール"]。BES-53248クラスタスイッチにRCFをインストールまたはアップグレードし、RCFを適用したあとに追加ライセンスのポートを確認します。
. link:configure-health-monitor.html["クラスタスイッチヘルスモニタ（ CSHM ）構成ファイルをインストールします"]。クラスタスイッチの健常性監視用に適切な構成ファイルをインストールします。
. link:configure-ssh.html["BES-53248 クラスタスイッチで SSH を有効にします"]。クラスタスイッチヘルスモニタ（CSHM）およびログ収集機能を使用する場合は、スイッチでSSHを有効にします。
. link:configure-log-collection.html["ログ収集機能を有効にします"]。この機能は、ONTAP でスイッチ関連のログファイルを収集する場合に使用します。

