---
permalink: switch-bes-53248/replace-verify.html 
sidebar: sidebar 
keywords: command, verify, operational, bes, cluster, switch, upgrade, verify the configuration after a cluster switch upgrade - bes-53428 switches 
summary: ここで提供されるコマンドを使用して、BES-53248 クラスタ スイッチのアップグレード後にすべてが動作していることを確認できます。 
---
= BES-53248クラスタスイッチのEFOSソフトウェアまたはRCFアップグレード後のONTAPクラスタネットワークを検証します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EFOS ソフトウェアまたは BES-53248 クラスタ スイッチの RCF をアップグレードした後、次のコマンドを使用してONTAPクラスタ ネットワークの健全性を確認できます。

.手順
. 次のコマンドを使用して、クラスター上のネットワーク ポートに関する情報を表示します。
+
[source, cli]
----
network port show -ipspace Cluster
----
+
`Link`価値を持たなければならない `up`そして `Health Status`でなければなりません `healthy`。

+
.例を表示
[%collapsible]
====
次の例は、コマンドからの出力例を示しています。

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. 各LIFについて、次の点を確認します。 `Is Home`は `true`そして `Status Admin/Oper`は `up`両方のノードで次のコマンドを使用します。
+
[source, cli]
----
network interface show -vserver Cluster
----
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.217.125/16 node1         e0a     true
            node1_clus2  up/up    169.254.205.88/16  node1         e0b     true
            node2_clus1  up/up    169.254.252.125/16 node2         e0a     true
            node2_clus2  up/up    169.254.110.131/16 node2         e0b     true
----
====
. 確認するには `Health Status`各ノードは `true`次のコマンドを使用します:
+
`cluster show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====


.次の手順
EFOSソフトウェアまたはRCFのアップグレードを確認したら、 link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを設定する"]。
