---
permalink: switch-bes-53248/required-documentation-bes53248.html 
sidebar: sidebar 
keywords: documentation requirements, BES-53248 switches,cluster switches 
summary: clustered Data ONTAP構成をセットアップするには、特定のスイッチとコントローラに関するドキュメントが必要です。 
---
= BES-53248 クラスタスイッチのドキュメント要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 スイッチの設置については、必ずスイッチおよびコントローラの関連ドキュメントを確認してください。



== Broadcomのドキュメント

BES-53248クラスタスイッチをセットアップするには、Broadcomサポートサイトから入手できる以下のドキュメントが必要ですlink:https://www.broadcom.com/support/bes-switch["Broadcom イーサネットスイッチ製品ライン"^]。

[cols="1,2"]
|===
| ドキュメント タイトル | 説明 


 a| 
_EFOS 管理者ガイド v3.4.3_
 a| 
一般的なネットワークでのBES-53248スイッチの使用方法の例を示します。



 a| 
_EFOS CLI コマンドリファレンス v3.4.3_
 a| 
BES-53248ソフトウェアの表示と設定に使用するコマンドライン インターフェイス（CLI）コマンドについて説明します。



 a| 
_EFOS スタートガイド v3.4.3_
 a| 
BES-53248スイッチの詳細情報を提供します。



 a| 
_EFOS SNMPリファレンスガイドv3.4.3_
 a| 
一般的なネットワークでのBES-53248スイッチの使用方法の例を示します。



 a| 
_EFOS スケーリングパラメータと値 v3.4.3_
 a| 
EFOSソフトウェアと一緒に提供され、サポート対象プラットフォームで検証済みのデフォルトのスケール パラメータについて説明します。



 a| 
_EFOS 機能仕様 v3.4.3_
 a| 
サポート対象プラットフォームでのEFOSソフトウェアの仕様を示します。



 a| 
_EFOS リリースノート v3.4.3_
 a| 
BES-53248ソフトウェアに関するリリース固有の情報を示します。



 a| 
_クラスタネットワークと管理ネットワークの互換性マトリックス_
 a| 
ネットワークの互換性に関する情報を提供します。マトリックスは、BES-53248スイッチのダウンロードサイトlink:https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom クラスタスイッチ"^]から入手できます。

|===


== ONTAPシステムのドキュメントと KB 記事

ONTAP システムをセットアップするには、NetApp Support Site（link:http://mysupport.netapp.com/["mysupport.netapp.com"^]）またはナレッジベース（KB）サイト（link:https://kb.netapp.com/["kb.netapp.com"^]）から以下のドキュメントが必要です。

[cols="1,2"]
|===
| Name | 説明 


 a| 
https://hwu.netapp.com/Home/Index["Hardware Universe"^]
 a| 
システム キャビネットを含むすべてのNetAppハードウェアの電源とサイトの要件について説明し、使用する関連コネクタとケーブル オプションとその部品番号に関する情報を提供します。



 a| 
コントローラ固有の_インストールおよびセットアップ手順_
 a| 
NetAppハードウェアのインストール方法について説明します。



 a| 
link:https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^]
 a| 
ONTAP 9 リリースのあらゆる側面に関する詳細情報を提供します。



 a| 
_Broadcom 対応 BES-53248 スイッチに追加ポートライセンスを追加する方法_
 a| 
ポートライセンスの追加に関する詳細情報を提供します。こちらを参照してくださいlink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["技術情報"^]。

|===