---
permalink: switch-bes-53248/upgrade-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,upgrading EFOS software 
summary: 'BES-53248 クラスタ スイッチ上の Ethernet Fabric OS (EFOS) ソフトウェアをアップグレードするには、次の手順に従います。' 
---
= EFOSソフトウェアをアップグレードします。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 クラスター スイッチ上の EFOS ソフトウェアをアップグレードするには、次の手順に従います。

EFOS ソフトウェアには、イーサネットおよび IP インフラストラクチャ システムを開発するための高度なネットワーク機能とプロトコルのセットが含まれています。このソフトウェア アーキテクチャは、徹底したパケット検査または分離を必要とするアプリケーションを使用するあらゆるネットワーク組織デバイスに適しています。



== アップグレードの準備

.開始する前に
* クラスタスイッチに適したBroadcom EFOSソフトウェアを以下のサイトからダウンロードしてください。 https://www.broadcom.com/support/bes-switch["Broadcomイーサネット スイッチのサポート"^]サイト。
* EFOS バージョンに関する次の注意事項を確認してください。


[]
====
*以下の点にご注意ください:*

* EFOS 3.4.x.xからEFOS 3.7.x.x以降にアップグレードする場合は、スイッチでEFOS 3.4.4.6（またはそれ以降の3.4.x.xリリース）が実行されている必要があります。それよりも前のリリースが実行されている場合は、まずスイッチをEFOS 3.4.4.6（またはそれ以降の3.4.x.xリリース）にアップグレードしてから、スイッチをEFOS 3.7.x.x以降にアップグレードします。
* EFOS 3.4.x.xと3.7.x.x以降では、設定が異なります。EFOSバージョンを3.4.x.xから3.7.x.x以降（またはその逆）に変更するには、スイッチを工場出荷時のデフォルトにリセットし、そのEFOSのバージョンに対応するRCFファイルを（再）適用する必要があります。この手順は、シリアル コンソール ポート経由でアクセスして実行する必要があります。
* EFOSバージョン3.7.x.x以降では、FIPS非準拠バージョンとFIPS準拠バージョンを使用できます。FIPS 非準拠バージョンから FIPS 準拠バージョンに移行する場合、またはその逆の場合、異なる手順が適用されます。EFOSをFIPS非準拠バージョンからFIPS準拠バージョン（またはその逆）に変更すると、スイッチは工場出荷時のデフォルトにリセットされます。この手順は、シリアル コンソール ポート経由でアクセスして実行する必要があります。


====
|===


| *手順* | *現在のEFOSバージョン* | *新しいEFOSバージョン* | *大まかな手順* 


 a| 
2つの（非）FIPS準拠バージョン間でEFOSをアップグレードする手順
 a| 
3.4.xx
 a| 
3.4.xx
 a| 
新しいEFOSイメージをアップグレードするには<<方法1: EFOSをアップグレードする>>。構成とライセンス情報は保持されます。



 a| 
3.4.4.6 (または 3.4.xx 以降)
 a| 
3.7.xx 以降は FIPS 非準拠
 a| 
EFOSをアップグレードするには<<方法1: EFOSをアップグレードする>>。スイッチを工場出荷時の設定にリセットし、EFOS 3.7.xx 以降の RCF ファイルを適用します。



.2+| 3.7.xx 以降は FIPS 非準拠  a| 
3.4.4.6 (または 3.4.xx 以降)
 a| 
EFOSをダウングレードするには<<方法1: EFOSをアップグレードする>>。スイッチを工場出荷時のデフォルトにリセットし、EFOS 3.4.x.xのRCFファイルを適用します。



 a| 
3.7.xx 以降は FIPS 非準拠
 a| 
新しいEFOSイメージをアップグレードするには<<方法1: EFOSをアップグレードする>>。構成とライセンス情報は保持されます。



 a| 
3.7.xx以降 FIPS準拠
 a| 
3.7.xx以降 FIPS準拠
 a| 
新しいEFOSイメージをアップグレードするには<<方法1: EFOSをアップグレードする>>。構成とライセンス情報は保持されます。



 a| 
FIPS準拠のEFOSバージョンへのアップグレード手順
 a| 
FIPS非準拠
 a| 
FIPS準拠
 a| 
EFOSイメージのアップグレード<<方法2: ONIE OSインストールを使用してEFOSをアップグレードする>>。スイッチの設定とライセンス情報は失われます。



 a| 
FIPS準拠
 a| 
FIPS非準拠

|===
[IMPORTANT]
====
EFOSのバージョンがFIPS準拠か非準拠かを確認するには、 `show fips status`指示。次の例では、*IP_switch_a1* は FIPS 準拠の EFOS を使用し、*IP_switch_a2* は FIPS 非準拠の EFOS を使用しています。

* スイッチ IP_switch_a1 (FIPS 準拠 EFOS) の場合:
+
[listing, subs="+quotes"]
----
IP_switch_a1 # *show fips status*

System running in FIPS mode
----
* スイッチ IP_switch_a2 (FIPS 非準拠 EFOS) の場合:
+
[listing, subs="+quotes"]
----
IP_switch_a2 # *show fips status*
                     ^
% Invalid input detected at ^ marker.
----


====


== ソフトウェアをアップグレードする

次のいずれかの方法を使用します。

* <<方法1: EFOSをアップグレードする>>。ほとんどの場合に使用します (上記の表を参照)。
* <<方法2: ONIE OSインストールを使用してEFOSをアップグレードする>>。一方の EFOS バージョンが FIPS 準拠であり、もう一方の EFOS バージョンが FIPS 非準拠である場合に使用します。



NOTE: クラスター ネットワークの継続的な運用を確保するには、一度に 1 つのスイッチで EFOS をアップグレードします。



=== 方法1: EFOSをアップグレードする

EFOS ソフトウェアをアップグレードするには、次の手順を実行します。


IMPORTANT: BES-53248 クラスター スイッチを EFOS 3.3.xx または 3.4.xx から EFOS 3.7.0.4 または 3.8.0.2 にアップグレードすると、スイッチ間リンク (ISL) とポート チャネルが *ダウン* 状態にマークされることに注意してください。これは想定された動作であり、LIF の自動復元に関する問題が発生していない限り、アップグレードを続行しても安全です。ナレッジベースの記事を参照してください: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["BES-53248 クラスタスイッチNDUがEFOS 3.7.0.4以降へのアップグレードに失敗しました"^]詳細については、こちらをご覧ください。

.手順
. BES-53248クラスタ スイッチを管理ネットワークに接続します。
. 使用 `ping`EFOS、ライセンス、および RCF ファイルをホストしているサーバーへの接続を確認するコマンド。
+
次の例では、スイッチがIPアドレス172.19.2.1のサーバに接続されていることを確認します。

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. クラスタLIFで自動リバートを無効にします。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. アクティブ構成とバックアップ構成のブート イメージを表示します。
+
`show bootvar`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6              3.7.0.4        3.7.0.4

----
====
. スイッチにイメージ ファイルをダウンロードします。
+
イメージ ファイルをバックアップ イメージにコピーすると、再起動時にそのイメージによって実行中の EFOS バージョンが確立され、更新が完了します。

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk backup*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. アクティブ構成とバックアップ構成のブート イメージを表示します。
+
`show bootvar`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1      3.7.0.4    3.7.0.4             3.7.0.4       3.10.0.3
----
====
. バックアップ構成からシステムを起動します。
+
`boot system backup`

+
[listing, subs="+quotes"]
----
(cs2)# *boot system backup*
Activating image backup ..
----
. アクティブ構成とバックアップ構成のブート イメージを表示します。
+
`show bootvar`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1    3.10.0.3    3.10.0.3            3.10.0.3       3.10.0.3
----
====
. 実行中の設定をスタートアップ コンフィギュレーションに保存します。
+
`write memory`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.

Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
====
. スイッチをリブートします。
+
`reload`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. 再度ログインし、EFOS ソフトウェアの新しいバージョンを確認します。
+
`show version`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. スイッチ cs1 で手順 5 から 11 を繰り返します。
. クラスタLIFで自動リバートを有効にします。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. クラスタ LIF がホーム ポートに戻ったことを確認します。
+
[source, cli]
----
network interface show -vserver Cluster
----
+
詳細については、link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["ホーム ポートへのLIFのリバート"] 。





=== 方法2: ONIE OSインストールを使用してEFOSをアップグレードする

次の手順は、一方のEFOSバージョンがFIPS準拠で、もう一方のEFOSバージョンがFIPS非準拠の場合に実行できます。スイッチの起動に失敗した場合は、次の手順を使用して、ONIE から FIPS 非準拠または FIPS 準拠の EFOS 3.7.xx イメージをアップグレードできます。


NOTE: この機能は、FIPS 非準拠の EFOS 3.7.xx 以降でのみ使用できます。


CAUTION: ONIE OS インストールを使用して EFOS をアップグレードすると、構成は工場出荷時のデフォルトにリセットされ、ライセンスは削除されます。スイッチを通常の動作に戻すには、スイッチをセットアップし、ライセンスとサポートされている RCF をインストールする必要があります。

.手順
. クラスタLIFで自動リバートを無効にします。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. スイッチをONIEインストール モードで起動します。
+
起動中にプロンプトが表示されたら、ONIE を選択します。

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
*ONIE* を選択すると、スイッチが読み込まれ、いくつかの選択肢が表示されます。  *OSのインストール*を選択します。

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
スイッチは ONIE インストール モードで起動します。

. ONIE 検出を停止し、イーサネット インターフェイスを構成します。
+
次のメッセージが表示されたら、*Enter* を押して ONIE コンソールを起動します。

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE 検出が続行され、メッセージがコンソールに出力されます。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. イーサネットインターフェースを設定し、ルートを追加します。 `ifconfig eth0 <ipAddress> netmask <netmask> up`そして `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. ONIEインストール ファイルをホストしているサーバにアクセスできることを確認します。
+
`ping`

+
.例を表示
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. 新しいスイッチ ソフトウェアをインストールします。
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.例を表示
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
ソフトウェアがインストールされ、スイッチが再起動します。スイッチが新しいEFOSバージョンで正常にリブートするのを待ちます。

. 新しいスイッチ ソフトウェアがインストールされていることを確認します。
+
`show bootvar`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
   1    3.7.0.4     3.7.0.4  3.7.0.4         3.10.0.3
(cs2) #
----
====
. インストールを完了します。スイッチは設定が適用されずに再起動し、工場出荷時のデフォルトにリセットされます。スイッチを再構成するには、次の手順を実行します。
+
.. link:configure-licenses.html["ライセンスをインストールする"]
.. link:configure-install-rcf.html["RCFのインストール"]
.. link:configure-ssh.html["SSH を有効にする"]
.. link:CSHM_log_collection.html["ログ収集を有効にする"]
.. link:CSHM_snmpv3.html["監視用にSNMPv3を構成する"]


. スイッチ cs1 で手順 2 から 8 を繰り返します。
. クラスタLIFで自動リバートを有効にします。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. クラスタ LIF がホーム ポートに戻ったことを確認します。
+
[source, cli]
----
network interface show -vserver Cluster
----
+
詳細については、link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["ホーム ポートへのLIFのリバート"] 。


