---
permalink: switch-bes-53248/upgrade-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,upgrading EFOS software 
summary: BES-53248クラスタスイッチのイーサネットファブリックOS（EFOS）ソフトウェアをアップグレードする手順は、次のとおりです。 
---
= EFOSソフトウェアのアップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248クラスタスイッチのEFOSソフトウェアをアップグレードする手順は、次のとおりです。

EFOSソフトウェアには、イーサネットシステムおよびIPインフラシステムを開発するための高度なネットワーク機能とプロトコルのセットが含まれています。このソフトウェアアーキテクチャは、パケットの検査や分離を完全に行う必要があるアプリケーションを使用するあらゆるネットワーク組織のデバイスに適しています。



== アップグレードを準備

.作業を開始する前に
* クラスタスイッチに対応するBroadcom EFOSソフトウェアをからダウンロードします https://www.broadcom.com/support/bes-switch["Broadcom Ethernet Switch のサポート"^] サイト
* EFOSバージョンに関する次の注意事項を確認します。


[]
====
* 次の点に注意してください。 *

* EFOS 3.x.x から EFOS 3.x.x 以降にアップグレードするときは、スイッチが EFOS 3.4.4.6 （または 3.4.x.x 以降のリリース）を実行している必要があります。それよりも前のリリースを実行している場合は、まずスイッチを EFOS 3.4.4.6 （または 3.4.x.x 以降のリリース）にアップグレードしてから、スイッチを EFOS 3.x.x 以降にアップグレードします。
* EFOS 3.x.x と 3.7.x.x 以降の設定は異なります。EFOS バージョンを 3.4.x.x から 3.7.x.x 以降、またはその逆に変更する場合は、スイッチを工場出荷時のデフォルトにリセットする必要があり、対応する EFOS バージョンの RCF ファイルが適用される（再適用される）必要があります。この手順には、シリアルコンソールポート経由でアクセスする必要があります。
* EFOS バージョン 3.7.x.x 以降では、 FIPS に準拠していないバージョンと FIPS に準拠したバージョンが提供されています。FIPSに準拠していないバージョンからFIPSに準拠したバージョンに移行する場合とFIPSに準拠していないバージョンからFIPSに準拠したバージョンに移行する場合は、EFOS を FIPS 非準拠バージョンから FIPS 準拠バージョンに変更するか、その逆に変更すると、スイッチが工場出荷時のデフォルトにリセットされます。この手順には、シリアルコンソールポート経由でアクセスする必要があります。


====
|===


| * 手順 * | * 現在の EFOS バージョン * | * 新しい EFOS バージョン * | * 高レベルステップ * 


 a| 
FIPS に準拠している 2 つのバージョン間で EFOS をアップグレードする手順
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
次を使用して新しいEFOSイメージをアップグレードします： <<方法1：EFOSをアップグレードする>>。
構成とライセンスの情報は保持されます。



 a| 
3.4.4.6 （または 3.4.x.x 以降）
 a| 
3.7.x.x 以降の非 FIPS 準拠
 a| 
を使用してEFOSをアップグレードする <<方法1：EFOSをアップグレードする>>。
スイッチを工場出荷時のデフォルトにリセットして、EFOS 3.x.x以降のRCFファイルを適用します。



.2+| 3.7.x.x 以降の非 FIPS 準拠  a| 
3.4.4.6 （または 3.4.x.x 以降）
 a| 
を使用してEFOSをダウングレードし <<方法1：EFOSをアップグレードする>>。
スイッチを工場出荷時のデフォルトにリセットして、 EFOS 3.x.x の RCF ファイルを適用します



 a| 
3.7.x.x 以降の非 FIPS 準拠
 a| 
次を使用して新しいEFOSイメージをアップグレードします： <<方法1：EFOSをアップグレードする>>。構成とライセンスの情報は保持されます。



 a| 
3.7.x.x 以降の FIPS に準拠しています
 a| 
3.7.x.x 以降の FIPS に準拠しています
 a| 
次を使用して新しいEFOSイメージをアップグレードします： <<方法1：EFOSをアップグレードする>>。
構成とライセンスの情報は保持されます。



 a| 
FIPS 準拠の EFOS バージョンへのアップグレード手順
 a| 
FIPS に準拠していません
 a| 
FIPS に準拠している
 a| 
次を使用したEFOSイメージのアップグレード： <<方法2：ONIE OSインストールを使用してEFOSをアップグレードします>>。スイッチの設定とライセンス情報が失われます。



 a| 
FIPS に準拠している
 a| 
FIPS に準拠していません

|===
[IMPORTANT]
====
EFOSのバージョンがFIPSに準拠しているかどうかを確認するには、を使用します `show fips status` コマンドを実行します次の例では、* IP_switch_a1 *はFIPS準拠のEFOSを使用し、* IP_switch_a2 *はFIPS非準拠のEFOSを使用しています。

* スイッチIP_switch_A1（FIPS準拠のEFOS）：
+
[listing, subs="+quotes"]
----
IP_switch_a1 # *show fips status*

System running in FIPS mode
----
* スイッチIP_switch_A2（FIPS非準拠EFOS）：
+
[listing, subs="+quotes"]
----
IP_switch_a2 # *show fips status*
                     ^
% Invalid input detected at ^ marker.
----


====


== ソフトウェアのアップグレード

次のいずれかの方法を使用します。

* <<方法1：EFOSをアップグレードする>>。ほとんどの場合に使用します（上の表を参照）。
* <<方法2：ONIE OSインストールを使用してEFOSをアップグレードします>>。一方のEFOSバージョンがFIPSに準拠しており、もう一方のEFOSバージョンがFIPSに準拠していない場合に使用します。



NOTE: クラスタネットワークの運用を継続するには、一度に1つのスイッチでEFOSをアップグレードしてください。



=== 方法1：EFOSをアップグレードする

EFOSソフトウェアをアップグレードするには、次の手順を実行します。


IMPORTANT: BES-53248 クラスタスイッチを EFOS 3.x.x または 3.4.x.x から EFOS 3.7.0.4 または 3.8.0.2 にアップグレードしたあと、 Inter-Switch Link （ ISL ；スイッチ間リンク）とポートチャネルが「 Down 」状態でマークされることに注意してください。これは想定された動作であり、自動リバートLIFで問題がないかぎりアップグレードを続行しても問題ありません。詳細については、ナレッジベースの記事を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["BES-53248クラスタスイッチNDUをEFOS 3.7.0.4以降にアップグレードできませんでした"^]。

.手順
. BES-53248 クラスタスイッチを管理ネットワークに接続します。
. 「 ping 」コマンドを使用して、 EFOS 、ライセンス、 RCF ファイルをホストするサーバへの接続を確認します。
+
次の例では、スイッチが IP アドレス 172.19.2.1 のサーバに接続されていることを確認します。

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. クラスタ LIF で自動リバートを無効にします。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. アクティブ構成とバックアップ構成のブートイメージを表示します。
+
'How bootvar'

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6              3.7.0.4        3.7.0.4

----
====
. スイッチにイメージファイルをダウンロードします。
+
イメージファイルをアクティブイメージにコピーすると、リブート時にそのイメージによって実行中の EFOS バージョンが確立されます。以前のイメージはバックアップとして使用できます。

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk backup*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. アクティブ構成とバックアップ構成のブートイメージを表示します。
+
'How bootvar'

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1      3.7.0.4    3.7.0.4             3.7.0.4       3.10.0.3
----
====
. バックアップ構成からシステムをブートします。
+
`boot system backup`

+
[listing, subs="+quotes"]
----
(cs2)# *boot system backup*
Activating image backup ..
----
. アクティブ構成とバックアップ構成のブートイメージを表示します。
+
'How bootvar'

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1    3.10.0.3    3.10.0.3            3.10.0.3       3.11.0.2
----
====
. 実行コンフィギュレーションをスタートアップコンフィギュレーションに保存します。
+
「メモリの書き込み」

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.

Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
====
. スイッチをリブートします。
+
「再ロード」

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. 再度ログインして、新しいバージョンの EFOS ソフトウェアを確認します。
+
'how version （バージョンの表示） '

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. スイッチcs1で手順5~11を繰り返します。
. クラスタ LIF で自動リバートを有効にします。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. クラスタ LIF がホームポートにリバートされたことを確認します。
+
[source, cli]
----
network interface show -role Cluster
----
+
詳細については、を参照してください link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["LIF をホームポートにリバートする"]。





=== 方法2：ONIE OSインストールを使用してEFOSをアップグレードします

一方の EFOS バージョンが FIPS に準拠していて、もう一方の EFOS バージョンが FIPS に準拠していない場合は、次の手順を実行できます。スイッチをブートできない場合は、次の手順を使用して、FIPSまたはFIPSに準拠していないEFOS 3.7.x.xイメージをONIEからアップグレードできます。


NOTE: この機能は、 EFOS 3.x.x 以降の非 FIPS 準拠に対してのみ使用できます。


CAUTION: ONIE OSインストールを使用してEFOSをアップグレードすると、設定が工場出荷時のデフォルトにリセットされ、ライセンスが削除されます。スイッチを通常動作に戻すには、スイッチをセットアップし、ライセンスとサポートされているRCFをインストールする必要があります。

.手順
. クラスタ LIF で自動リバートを無効にします。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. スイッチを ONIE インストールモードで起動します。
+
ブート中に次のプロンプトが表示されたら、ONIEを選択します。

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
*ONIE*を選択すると、スイッチがロードされ、いくつかの選択肢が表示されます。「OSのインストール」を選択します。

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
スイッチがONIEインストールモードで起動します。

. ONIE の検出を停止し、イーサネットインターフェイスを設定します。
+
次のメッセージが表示されたら、*Enter*キーを押してONIEコンソールを起動します。

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIEの検出が続行され、メッセージがコンソールに出力されます。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. イーサネットインターフェイスを設定し、「 ifconfig eth0 <ipAddress> netmask <netmask> up 」および「 route add default gw <gatewayAddress> 」を使用してルートを追加します
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. ONIE インストールファイルをホストしているサーバにアクセスできることを確認します。
+
`ping`

+
.例を示します
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. 新しいスイッチソフトウェアをインストールします。
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.例を示します
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
ソフトウェアがインストールされ、スイッチがリブートされます。スイッチを通常どおりにリブートして新しい EFOS バージョンにします。

. 新しいスイッチソフトウェアがインストールされたことを確認します。
+
'How bootvar'

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
   1    3.7.0.4     3.7.0.4  3.7.0.4         3.10.0.3
(cs2) #
----
====
. インストールを完了します。設定を適用せずにスイッチがリブートし、工場出荷時のデフォルトにリセットされます。スイッチを再設定するには、次の手順を実行します。
+
.. link:configure-licenses.html["ライセンスをインストール"]
.. link:configure-install-rcf.html["RCFをインストールします"]
.. link:configure-ssh.html["SSH を有効にします。"]
.. link:CSHM_log_collection.html["ログ収集を有効にします"]
.. link:CSHM_snmpv3.html["監視のためのSNMPv3の設定"]


. スイッチcs1で手順2~8を繰り返します。
. クラスタ LIF で自動リバートを有効にします。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. クラスタ LIF がホームポートにリバートされたことを確認します。
+
[source, cli]
----
network interface show -role Cluster
----
+
詳細については、を参照してください link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["LIF をホームポートにリバートする"]。


