---
permalink: switch-cisco-3132q-v/cn1610-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Cisco Nexus 3132q-v スイッチを構成する前に、プロセスと命名法の概要を確認してください。 
---
= 移行要件
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3132Q-V スイッチは、 AFFまたはFASクラスタ内のクラスタ スイッチとして使用できます。クラスタ スイッチを使用すると、2 つ以上のノードを持つONTAPクラスタを構築できます。

[NOTE]
====
この手順では、ONTAPコマンドとCisco Nexus 3000シリーズ スイッチ コマンドの両方を使用する必要があります。特に明記されていないかぎり、ONTAPコマンドを使用します。

====
詳細については、以下を参照してください。

* https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601およびCN1610の説明ページ"^]
* https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチの説明ページ"^]
* http://hwu.netapp.com["Hardware Universe"^]




== CN1610の要件

次のクラスタ スイッチがサポートされます。

* NetApp CN1610
* Cisco Nexus 3132Q-V


クラスター スイッチは次のノード接続をサポートします。

* NetApp CN1610: ポート 0/1 ～ 0/12 (10 GbE)
* Cisco Nexus 3132Q-V: ポート e1/1-30 (40/100 GbE)


クラスタ スイッチは、次のスイッチ間リンク (ISL) ポートを使用します。

* NetApp CN1610: ポート 0/13 ～ 0/16 (10 GbE)
* Cisco Nexus 3132Q-V: ポート e1/31-32 (40/100 GbE)
+
そのlink:https://hwu.netapp.com/["Hardware Universe"^]Nexus 3132Q-V スイッチへのサポートされているケーブル接続に関する情報が含まれています。

* 10 GbE クラスタ接続のノードには、QSFP から SFP+ への光ファイバブレークアウトケーブルまたは QSFP から SFP+ への銅線ブレークアウトケーブルが必要です。
* 40/100 GbE クラスタ接続を備えたノードには、光ファイバーケーブルまたは QSFP/QSFP28 銅線直接接続ケーブルを備えたサポートされている QSFP/QSFP28 光モジュールが必要です。


適切な ISL ケーブル接続は次のとおりです。

* 開始: CN1610からCN1610 (SFP+からSFP+)の場合、4本のSFP+光ファイバーまたは銅線直接接続ケーブル
* 暫定：CN1610からNexus 3132Q-V（QSFPから4つのSFP+ブレークアウト）の場合、1本のQSFPからSFP+への光ファイバーまたは銅ブレークアウトケーブル
* 最終：Nexus 3132Q-VからNexus 3132Q-V（QSFP28からQSFP28）の場合、2本のQSFP28光ファイバーまたは銅線直接接続ケーブル


NetApp Twinax ケーブルは、 Cisco Nexus 3132Q-V スイッチと互換性がありません。

現在の CN1610 構成でクラスタ ノードとスイッチ間の接続または ISL 接続にNetApp Twinax ケーブルを使用しており、環境内で Twinax を引き続き使用する場合は、 Cisco Twinax ケーブルを入手する必要があります。あるいは、ISL 接続とクラスター ノードとスイッチ間の接続の両方に光ファイバー ケーブルを使用することもできます。

.使用された例について
この手順の例では、CN1610 スイッチをCisco Nexus 3132Q-V スイッチに置き換える方法について説明します。これらの手順は、（変更を加えて）他の古いCiscoスイッチにも使用できます。

この手順では、次のスイッチとノードの命名法も使用します。

* コマンド出力は、ONTAPのリリースによって異なる場合があります。
* 交換する CN1610 スイッチは *CL1* と *CL2* です。
* CN1610 スイッチを置き換える Nexus 3132Q-V スイッチは *C1* と *C2* です。
* *n1_clus1* は、ノード *n1* のクラスタ スイッチ 1 (CL1 または C1) に接続された最初のクラスタ論理インターフェイス (LIF) です。
* *n1_clus2* は、ノード *n1* のクラスタ スイッチ 2 (CL2 または C2) に接続された最初のクラスタ LIF です。
* *n1_clus3* は、ノード *n1* のクラスタ スイッチ 2 (CL2 または C2) に接続された 2 番目の LIF です。
* *n1_clus4* は、ノード *n1* のクラスタ スイッチ 1 (CL1 または C1) に接続された 2 番目の LIF です。
* 10 GbEおよび40/100 GbEポートの数は、 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco® クラスタ ネットワーク スイッチ リファレンス コンフィギュレーション ファイルのダウンロード"^]ページ。
* ノードは *n1*、*n2*、*n3*、*n4* です。


この手順の例では、次の 4 つのノードを使用します。

* 2 つのノードは、4 つの 10 GbE クラスター相互接続ポート *e0a*、*e0b*、*e0c*、および *e0d* を使用します。
* 他の 2 つのノードは、2 つの 40 GbE クラスター相互接続ポート *e4a* と *e4e* を使用します。
+
そのlink:https://hwu.netapp.com/["Hardware Universe"^]プラットフォーム上の実際のクラスター ポートを一覧表示します。



.次の手順
link:cn5596-prepare-to-migrate.html["移行の準備"]。
