---
permalink: switch-cisco-3132q-v/cn5596-configure-ports.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: Cisco Nexus 3132q-Vスイッチは、AFFまたはFASクラスタのクラスタスイッチとして使用できます。 
---
= 5596スイッチから3132Q-Vスイッチに移行するためのポートの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nexus 5596スイッチから新しいNexus 3132Q-Vスイッチに移行するようにポートを設定する手順は、次のとおりです。

.手順
. すべてのノードで、 Nexus 5596 スイッチ CL2 に接続されているすべてのケーブルを外します。
+
サポートされているケーブル接続を使用して、すべてのノード上の切断されているポートを Nexus 3132Q-V スイッチ C2 に再接続します。

. Nexus 5596 スイッチ CL2 からすべてのケーブルを取り外します。
+
新しい Cisco 3132Q-V スイッチ c2 のポート 1/24 を既存の Nexus 5596 、 CL1 のポート 45 ~ 48 に接続する適切な Cisco QSFP / SFP+ ブレークアウトケーブルを接続します。

. インターフェイス Eth1/45-48 の実行コンフィギュレーションにすでに「 channel-group 1 mode active 」が含まれていることを確認します。
. アクティブな Nexus 5596 スイッチ CL1 で ISL ポート 45~48 を起動します。
+
.例を示します
[%collapsible]
====
次の例は、 ISL ポート 45~48 を起動します。

[listing]
----
(CL1)# configure
(CL1)(Config)# interface e1/45-48
(CL1)(config-if-range)# no shutdown
(CL1)(config-if-range)# exit
(CL1)(Config)# exit
(CL1)#
----
====
. Nexus 5596 スイッチ CL1 の ISL が「 up 」であることを確認します。
+
「ポートチャネルの概要」

+
.例を示します
[%collapsible]
====
ポート Eth1/45 ～ Eth1/48 は、（ P ）を示している必要があります。これは、 ISL ポートがポートチャネル内で「アップ」であることを意味します。

[listing]
----
Example
CL1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/41(D)   Eth1/42(D)   Eth1/43(D)
                                    Eth1/44(D)   Eth1/45(P)   Eth1/46(P)
                                    Eth1/47(P)   Eth1/48(P)
----
====
. 3132Q-V スイッチ C2 上の ISL が「 up 」であることを確認します。
+
「ポートチャネルの概要」

+
.例を示します
[%collapsible]
====
ポート Eth1/24/1 、 Eth1/24/2 、 Eth1/24/3 、および Eth1/24/4 は、ポートチャネル内の ISL ポートが「アップ」であることを意味している必要があります。

[listing]
----
C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(D)   Eth1/32(D)
2     Po2(SU)      Eth    LACP      Eth1/24/1(P)  Eth1/24/2(P)  Eth1/24/3(P)
                                    Eth1/24/4(P)
----
====
. すべてのノードで、 3132Q-V スイッチ C2 に接続されているすべてのクラスタインターコネクトポートを起動します。
+
「 network port modify 」を参照してください

+
.例を示します
[%collapsible]
====
次の例は、ノード n1 および n2 で指定されたポートが起動されていることを示しています。

[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin true
cluster::*> network port modify -node n1 -port e0c -up-admin true
cluster::*> network port modify -node n2 -port e0b -up-admin true
cluster::*> network port modify -node n2 -port e0c -up-admin true
----
====
. すべてのノードで、 C2 に接続されている移行済みのクラスタインターコネクト LIF をすべてリバートします。
+
「 network interface revert 」の略

+
.例を示します
[%collapsible]
====
次の例は、ノード n1 および n2 のホームポートに移行したクラスタ LIF をリバートしています。

[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n1_clus3
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus3
----
====
. すべてのクラスタインターコネクトポートがホームにリバートされたことを確認します。
+
「 network interface show 」を参照してください

+
.例を示します
[%collapsible]
====
次の例は、 clus2 の LIF がそれぞれのホームポートにリバートされたことを示しています。「 Is Home 」列の「 Current Port 」列のポートのステータスが「 true 」の場合、 LIF が正常にリバートされたことを示しています。Is Home の値が false の場合、 LIF はリバートされていません。

[listing]
----
cluster::*> network interface show -role cluster
(network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
. クラスタポートが接続されたことを確認します。
+
「 network port show 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例は ' 前の network port modify コマンドの結果を示しており ' すべてのクラスタ・インターコネクトが up であることを確認しています

[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
. リモートクラスタインターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
を使用できます `network interface check cluster-connectivity` コマンドを使用してクラスタ接続のアクセスチェックを開始し、詳細を表示します。

`network interface check cluster-connectivity start` および `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注：* showコマンドを実行して詳細を表示する前に、数秒待ってください。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2        n2_clus1      none
       3/5/2022 19:21:20 -06:00   n1_clus2        n2_clus2      none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2        n1_clus1      none
       3/5/2022 19:21:20 -06:00   n2_clus2        n1_clus2      none
----
--
.すべてのONTAPリリース
--
すべてのONTAPリリースで、 `cluster ping-cluster -node <name>` 接続を確認するコマンド：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e0a	10.10.0.1
Cluster n1_clus2 n1		e0b	10.10.0.2
Cluster n1_clus3 n1		e0c	10.10.0.3
Cluster n1_clus4 n1		e0d	10.10.0.4
Cluster n2_clus1 n2		e0a	10.10.0.5
Cluster n2_clus2 n2		e0b	10.10.0.6
Cluster n2_clus3 n2		e0c	10.10.0.7
Cluster n2_clus4 n2		e0d	10.10.0.8

Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step12]]クラスタ内の各ノードで、交換する最初のNexus 5596スイッチCL1に関連付けられているインターフェイスを移行します。
+
「ネットワーク・インターフェイス移行」

+
.例を示します
[%collapsible]
====
次の例は、ノード n1 および n2 で移行するポートまたは LIF を示しています。

[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus1 -source-node n1 -
destination-node n1 -destination-port e0b
cluster::*> network interface migrate -vserver Cluster -lif n1_clus4 -source-node n1 -
destination-node n1 -destination-port e0c
cluster::*> network interface migrate -vserver Cluster -lif n2_clus1 -source-node n2 -
destination-node n2 -destination-port e0b
cluster::*> network interface migrate -vserver Cluster -lif n2_clus4 -source-node n2 -
destination-node n2 -destination-port e0c
----
====
. クラスタのステータスを確認します。
+
「 network interface show 」を参照してください

+
.例を示します
[%collapsible]
====
次の例は、必要なクラスタ LIF が、クラスタスイッチ C2 でホストされている適切なクラスタポートに移行されたことを示しています。

[listing]
----
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0b     false
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0c     false
            n2_clus1   up/up      10.10.0.5/24       n2            e0b     false
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0c     false
8 entries were displayed.

----- ------- ----
----
====
. すべてのノードで、 CL1 に接続されているノードポートをシャットダウンします。
+
「 network port modify 」を参照してください

+
.例を示します
[%collapsible]
====
次の例は、ノード n1 および n2 で指定されたポートをシャットダウンしている状態を示しています。

[listing]
----
cluster::*> network port modify -node n1 -port e0a -up-admin false
cluster::*> network port modify -node n1 -port e0d -up-admin false
cluster::*> network port modify -node n2 -port e0a -up-admin false
cluster::*> network port modify -node n2 -port e0d -up-admin false
----
====
. アクティブな3132Q-VスイッチC2のISLポート24、31、32をシャットダウンします。
+
「ダウンタイム」

+
.例を示します
[%collapsible]
====
次の例は、 ISL 24 、 31 、および 32 をシャットダウンする方法を示しています。

[listing]
----
C2# configure
C2(Config)# interface e1/24/1-4
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# interface 1/31-32
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config-if)# exit
C2#
----
====
. すべてのノードで、 Nexus 5596 スイッチ CL1 に接続されているすべてのケーブルを取り外します。
+
サポートされているケーブル接続を使用して、すべてのノード上の切断されているポートを Nexus 3132Q-V スイッチ C1 に再接続します。

. Nexus 3132Q-V C2 ポート e1/24 から QSFP ブレークアウトケーブルを取り外します。
+
サポートされている Cisco QSFP 光ファイバケーブルまたは直接接続ケーブルを使用して、 C1 のポート e1/31 および e1/32 を c2 のポート e1/31 および e1/32 に接続します。

. ポート24の設定をリストアし、C2の一時ポートチャネル2を削除します。
+
[listing]
----
C2# configure
C2(config)# no interface breakout module 1 port 24 map 10g-4x
C2(config)# no interface port-channel 2
C2(config-if)# int e1/24
C2(config-if)# description 40GbE Node Port
C2(config-if)# spanning-tree port type edge
C2(config-if)# spanning-tree bpduguard enable
C2(config-if)# mtu 9216
C2(config-if-range)# exit
C2(config)# exit
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
. c2 の ISL ポート 31 および 32 をアクティブな 3132Q-V スイッチ「 no shutdown 」で起動します
+
.例を示します
[%collapsible]
====
次の例は、 3132Q-V スイッチ C2 の ISL 31 と 32 を up にする方法を示しています。

[listing]
----
C2# configure
C2(config)# interface ethernet 1/31-32
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====


.次の手順
link:cn5596-complete-migration.html["移行の完了"]です。
