---
permalink: switch-cisco-3132q-v/concept-replace-cisco-nexus-3132q-v-cluster-switches.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3132q-v cluster switches 
summary: Cisco Nexus 3132Q-V クラスタスイッチを交換する場合は、特定の設定情報、ポート接続、およびケーブル接続要件に注意する必要があります。 
---
= Cisco Nexus 3132Q-V クラスタスイッチを交換します
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3132Q-V クラスタスイッチを交換する場合は、特定の設定情報、ポート接続、およびケーブル接続要件に注意する必要があります。

* Cisco Nexus 3132Q-V クラスタスイッチがサポートされています。
* 10GbE ポートと 40 / 100GbE ポートの数は、で使用可能なリファレンス構成ファイル（ RCF ）に定義されています link:https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® Cluster Network Switch Reference Configuration File Download （ Cisco ® クラスタネットワークスイッチリファレンス構成ファイルのダウンロード"^] ページ
* クラスタスイッチは、 Inter-Switch Link （ ISL ；スイッチ間リンク）ポート e1/31~32 を使用します。
* 。 link:https://hwu.netapp.com["Hardware Universe"^] Nexus 3132Q-V スイッチでサポートされているケーブル接続に関する情報が含まれています。
+
** 10GbE クラスタ接続のノードには、ブレークアウト光ケーブルを備えた QSFP 光モジュールまたは QSFP-SFP+ 銅線ブレークアウトケーブルが必要です。
** 40/100GbE クラスタ接続が確立されているノードには、サポートされている QSFP/QSFP28 光モジュール（ファイバケーブルまたは QSFP/QSFP28 銅線直接接続ケーブル）が必要です。
** クラスタスイッチでは、適切な ISL ケーブルを使用します。 QSFP28 ファイバケーブルまたは銅線直接接続ケーブル × 2


* Nexus 3132Q-V では、 QSFP ポートは 40/100Gb イーサネットモードまたは 4 × 10Gb イーサネットモードのどちらかとして動作できます。
+
デフォルトでは、 40/100Gb イーサネットモードには 32 個のポートがあります。これらの 40 Gb イーサネットポートには、 2 タプルの命名規則で番号が付けられます。たとえば、 2 番目の 40 Gb イーサネットポートには、 1/2 という番号が付けられます。構成を 40 Gb イーサネットから 10 Gb イーサネットに変更するプロセスは _ ブレークアウト _ と呼ばれ、構成を 10 Gb イーサネットから 40 Gb イーサネットに変更するプロセスは _ ブレークイン _ と呼ばれます。40/100Gb イーサネットポートを 10Gb イーサネットポートに分割すると、結果として生成されるポートには 3 組の命名規則に従って番号が付けられます。たとえば、 2 番目の 40/100Gb イーサネットポートのブレークアウトポートには、 1/2/1 、 1/2 、 1/2/3 、 1/2/4 の番号が付けられます。

* Nexus 3132Q-V の左側には、 4 つの SFP+ ポートが 1 つ目の QSFP ポートに多重化されたセットがあります。
+
デフォルトでは、 RCF は最初の QSFP ポートを使用するように構成されています。

+
Nexus 3132Q-V の QSFP ポートの代わりに 4 つの SFP+ ポートをアクティブにするには、「 hardware profile front portmode sf-plus 」コマンドを使用します。同様に、「 hardware profile front portmode QSFP 」コマンドを使用すると、 Nexus 3132Q-V をリセットして、 4 つの SFP+ ポートの代わりに QSFP ポートを使用できます。

* 10GbE または 40/100GbE で実行するように Nexus 3132Q-V のポートを設定しておく必要があります。
+
最初の 6 つのポートを 4x10 GbE モードに分割するには、「 interface breakout module 1 port 1-6 map 10g-4x 」コマンドを使用します。同様に、 no interface breakout module 1 port 1-6 map 10g-4x コマンドを使用して、ブレークアウト構成から最初の 6 つの QSFP+ ポートをグループ化し直すことができます。

* ノードから Nexus 3132Q-V クラスタスイッチへの 10GbE および 40/100GbE 接続に関する必要なドキュメントを計画、移行しておく必要があります。
+
。 link:http://mysupport.netapp.com/NOW/download/software/cm_switches/["Cisco イーサネットスイッチ"^] この手順 でサポートされている ONTAP および NX-OS のバージョンについては、ページを参照してください。


