---
permalink: switch-cisco-3132q-v/index.html 
sidebar: sidebar 
keywords: Cisco, 3132Q-V 
summary: 2 ノードスイッチクラスタへの移行 
---
= 概要と要件：Cisco Nexus 3132Q-Vスイッチ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3132Q-Vスイッチの設置とメンテナンスについては、すべての要件と推奨されるドキュメントを確認してください。



== タスクの概要

AFF クラスタまたは FAS クラスタでは、 Cisco Nexus 3132Q-V スイッチをクラスタスイッチとして使用できます。インストールとメンテナンスには、次の作業が含まれます

* Cisco Nexus 3132Q-VクラスタスイッチへのNX-OSとReference Configuration File（RCF；参照構成ファイル）のインストール
* Cisco Nexus 3132Q-Vクラスタスイッチを使用した2ノードスイッチレスクラスタ環境から2ノードスイッチ環境への移行
* クラスタ内の障害のあるCisco Nexus 3132Q-Vスイッチの交換とスイッチのオペレーティングシステムとリファレンス構成ファイルのダウンロード
* Cisco Nexus 5596、Nexus 5020、またはNexus 5010クラスタスイッチのCisco Nexus 3132Q-Vスイッチへの交換
* NetApp CN1610スイッチのCisco Nexus 3132Q-Vクラスタスイッチへの交換




== 設定要件

クラスタを設定するには、スイッチに適切な数とタイプのケーブルとコネクタが必要です。最初に設定するスイッチのタイプに応じて、付属のコンソールケーブルを使用してスイッチのコンソールポートに接続する必要があります。また、特定のネットワーク情報を指定する必要があります。



== ネットワーク要件

すべてのスイッチ設定には、次のネットワーク情報が必要です。

* 管理ネットワークトラフィック用のIPサブネット。
* 各ストレージシステムコントローラおよび該当するすべてのスイッチのホスト名とIPアドレス。
* ほとんどのストレージシステムコントローラは、イーサネットサービスポート（レンチマーク）に接続することで、 e0M インターフェイスを介して管理されます。AFF A800 システムおよび AFF A700 システムでは、 e0M インターフェイスは専用のイーサネットポートを使用します。


を参照してください https://hwu.netapp.com["Hardware Universe"^] 最新情報については、



== Smart Call Homeの要件

Smart Call Home は、ネットワーク上のハードウェアおよびソフトウェアコンポーネントを監視し、重大なシステム状態に関する電子メールベースの通知を生成します。デバイスでイベントが発生すると、 Smart Call Home は宛先プロファイルで設定されているすべての受信者にアラートを送信します。

E メールを使用して Smart Call Home システムと通信するように、クラスタネットワークスイッチを設定する必要があります。必要に応じて、 Cisco の組み込み Smart Call Home サポート機能を利用するように、クラスタネットワークスイッチをセットアップできます。

Smart Call Home機能を使用する前に、次の点を考慮してください。

* E メールサーバが配置されている必要があります。
* スイッチは、 E メールサーバに IP 接続されている必要があります。
* 連絡先名（ SNMP サーバの連絡先）、電話番号、住所情報が設定されている必要があります。これは、受信したメッセージの送信元を判別するために必要です。
* 会社の適切な Cisco SMARTnet サービス契約に、 CCO ID を関連付ける必要があります。
* デバイスを登録するには、 Cisco SMARTnet サービスが導入されている必要があります。


。 http://www.cisco.com/c/en/us/products/switches/index.html["シスコサポートサイト"^] Smart Call Homeを設定するコマンドについて説明します。



== ドキュメントの要件

3132Q-VスイッチおよびONTAP クラスタを設定するには、特定のスイッチとコントローラのドキュメントが必要です。



=== スイッチのドキュメント

Cisco Nexus 3132Q-Vスイッチを設定するには、から次のドキュメントを入手する必要があります https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Cisco Nexus 3000 シリーズスイッチのサポート"^] ページ

[cols="1,2"]
|===
| ドキュメントタイトル | 説明 


 a| 
_ Nexus 3000 シリーズハードウェアインストレーションガイド _
 a| 
サイト要件、スイッチハードウェアの詳細、およびインストールオプションに関する詳細情報を提供します。



 a| 
_Cisco Nexus 3000 Series Switch Software Configuration Guides _ （スイッチにインストールされている NX-OS リリースのガイドを選択）
 a| 
スイッチを ONTAP 動作用に設定する前に必要なスイッチの初期設定に関する情報を提供します。



 a| 
_Cisco Nexus 3000 シリーズ NX-OS ソフトウェアアップグレードおよびダウングレードガイド _ （スイッチにインストールされている NX-OS リリースのガイドを選択）
 a| 
必要に応じてスイッチを ONTAP 対応スイッチソフトウェアにダウングレードする方法について説明します。



 a| 
_Cisco Nexus 3000 シリーズ NX-OS コマンドリファレンスマスターインデックス _
 a| 
シスコが提供するさまざまなコマンドリファレンスへのリンクを示します。



 a| 
_Cisco Nexus 3000 MIB リファレンス _
 a| 
Nexus 3000 スイッチの管理情報ベース（ MIB ）ファイルについて説明します。



 a| 
_Nexus 3000 シリーズ NX-OS システムメッセージリファレンス _
 a| 
Cisco Nexus 3000 シリーズスイッチのシステムメッセージ、情報メッセージ、およびリンク、内部ハードウェア、またはシステムソフトウェアの問題の診断に役立つその他のメッセージについて説明します。



 a| 
_Cisco Nexus 3000 Series NX-OS Release Notes （スイッチにインストールされている NX-OS リリースのノートを選択） _
 a| 
Cisco Nexus 3000 シリーズの機能、バグ、および制限事項について説明します。



 a| 
Cisco Nexus 6000 、 Cisco Nexus 5000 シリーズ、 Cisco Nexus 3000 シリーズ、および Cisco Nexus 2000 シリーズの規制、コンプライアンス、および安全性に関する情報
 a| 
Nexus 3000 シリーズスイッチの国際的な適合規格、安全性、および法令に関する情報を提供します。

|===


=== ONTAP システムのドキュメント

ONTAP システムをセットアップするには、使用しているオペレーティングシステムのバージョンに応じて、で次のドキュメントを参照する必要があります https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 ドキュメンテーション・センター"^]。

[cols="1,2"]
|===
| 名前 | 説明 


 a| 
コントローラ固有の設置およびセットアップ手順 _
 a| 
ネットアップハードウェアの設置方法について説明します。



 a| 
ONTAP のドキュメント
 a| 
ONTAP リリースのすべての側面に関する詳細情報を提供します。



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
ネットアップハードウェアの構成と互換性に関する情報を提供します。

|===


=== レールキットおよびキャビネットのドキュメント

3132Q-V Ciscoスイッチをネットアップキャビネットに設置するには、次のハードウェアに関するドキュメントを参照してください。

[cols="1,2"]
|===
| 名前 | 説明 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["『 42U System Cabinet 、 Deep Guide 』を参照してください"^]
 a| 
42U システムキャビネットに関連する FRU について説明し、メンテナンスおよび FRU の交換手順を示します。



 a| 
link:task-install-a-cisco-nexus-3232c-cluster-switch-and-pass-through-panel-in-a-netapp-cabinet.html["Cisco Nexus 3132Q-Vスイッチをネットアップキャビネットに設置します"^]
 a| 
4 ポストのネットアップキャビネットに Cisco Nexus 3132Q-V スイッチを設置する方法について説明します。

|===