---
permalink: switch-cisco-3132q-v/install-switch-3132qv.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 3132q-v 
summary: Cisco Nexus 3132Q-V スイッチをインストールするには、次の手順に従ってください。 
---
= 3132Q-Vクラスタスイッチをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3132Q-V スイッチをセットアップおよび構成するには、次の手順に従ってください。

.作業を開始する前に
次のものがあることを確認します。

* インストールサイトのHTTPサーバ、FTPサーバ、またはTFTPサーバにアクセスし、該当するNX-OSおよびRCFリリースをダウンロードします。
* 該当するNX-OSバージョン（からダウンロード） https://software.cisco.com/download/home["シスコソフトウェアのダウンロード"^] ページ
* 該当するライセンス、ネットワークおよび設定情報、ケーブル。
* 完了link:setup_worksheet_3132q.html["ケーブル接続ワークシート"]。
* 該当するネットアップクラスタネットワークと管理ネットワークのRCFをNetApp Support Site からダウンロードしました http://mysupport.netapp.com/["mysupport.netapp.com"^]。すべての Cisco クラスタネットワークスイッチおよび管理ネットワークスイッチは、シスコの工場出荷時のデフォルト設定で出荷されます。これらのスイッチには、 NX-OS ソフトウェアの最新バージョンもありますが、 RCF はロードされていません。
* link:required-documentation-3132q.html["必要なスイッチとONTAP のドキュメント"] 。


.手順
. クラスタネットワークと管理ネットワークのスイッチとコントローラをラックに設置します。
+
[cols="1,2"]
|===
| インストール対象 | 作業 


 a| 
NetApp システムキャビネット内の Cisco Nexus 9336C-FX2
 a| 
スイッチをネットアップキャビネットに設置する手順については、 NetApp cabinet Guide の Installing a Cisco Nexus 3132Q-V cluster switch and pass-through panel in a NetApp cabinet を参照してください。



 a| 
Telco ラック内の機器
 a| 
スイッチのハードウェア設置ガイド、およびネットアップのセットアップガイドに記載されている手順を参照してください。

|===
. 入力済みのケーブル接続ワークシートを使用して、クラスタネットワークスイッチと管理ネットワークスイッチをコントローラにケーブル接続します。
. クラスタネットワークと管理ネットワークのスイッチとコントローラの電源をオンにします。


.次の手順
オプションとして、link:install-cisco-nexus-3132qv.html["NetAppキャビネットにCisco Nexus 3132Q-Vスイッチをインストールする"] 。それ以外の場合は、link:cabling-considerations-3132q-v.html["ケーブル接続と構成を確認"] 。
