---
permalink: switch-cisco-3132q-v/migrate-from-switchless-cluster-to-cisco-nexus-3132q-v.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, cisco nexus 3132q-v 
summary: 2 ノードのスイッチレスクラスタを使用している場合は、 Cisco Nexus 3132Q-V クラスタネットワークスイッチを含む 2 ノードのスイッチクラスタに無停止で移行できます。 
---
= スイッチレスクラスタから2ノードスイッチクラスタに移行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
2ノードのスイッチレスクラスタを使用している場合は、この手順 に従って、Cisco Nexus 3132Q-Vクラスタネットワークスイッチを含む2ノードのスイッチクラスタに移行できます。交換用手順 は、無停止手順 （NDO；ノンストップオペレーション）です。



== 要件を確認

.ポートとノードの接続
Cisco Nexus 3132Q-Vクラスタスイッチを使用する2ノードスイッチクラスタに移行する場合は、ポートとノードの接続とケーブル接続の要件を確認しておく必要があります。

* クラスタスイッチは、 Inter-Switch Link （ ISL ；スイッチ間リンク）ポート e1/31~32 を使用します。
* 。 link:https://hwu.netapp.com/["Hardware Universe"^] Nexus 3132Q-V スイッチでサポートされているケーブル接続に関する情報が含まれています。
+
** 10GbE クラスタ接続のノードには、ブレークアウト光ケーブルを備えた QSFP 光モジュールまたは QSFP-SFP+ 銅線ブレークアウトケーブルが必要です。
** 40/100GbE クラスタ接続が確立されているノードには、サポートされている QSFP/QSFP28 光モジュール（ファイバケーブルまたは QSFP/QSFP28 銅線直接接続ケーブル）が必要です。
** クラスタスイッチでは、適切な ISL ケーブルを使用します。 QSFP28 ファイバケーブルまたは銅線直接接続ケーブル × 2


* Nexus 3132Q-V では、 QSFP ポートは 40/100Gb イーサネットモードまたは 4 × 10Gb イーサネットモードのどちらかとして動作できます。
+
デフォルトでは、 40/100Gb イーサネットモードには 32 個のポートがあります。これらの 40 Gb イーサネットポートには、 2 タプルの命名規則で番号が付けられます。たとえば、 2 番目の 40 Gb イーサネットポートには、 1/2 という番号が付けられます。構成を 40 Gb イーサネットから 10 Gb イーサネットに変更するプロセスは _ ブレークアウト _ と呼ばれ、構成を 10 Gb イーサネットから 40 Gb イーサネットに変更するプロセスは _ ブレークイン _ と呼ばれます。40/100Gb イーサネットポートを 10Gb イーサネットポートに分割すると、結果として生成されるポートには 3 組の命名規則に従って番号が付けられます。たとえば、 2 番目の 40/100Gb イーサネットポートのブレークアウトポートには、 1/2/1 、 1/2 、 1/2/3 、 1/2/4 の番号が付けられます。

* Nexus 3132Q-V の左側には、 4 つの SFP+ ポートが 1 つ目の QSFP ポートに多重化されたセットがあります。
+
デフォルトでは、 RCF は最初の QSFP ポートを使用するように構成されています。

+
Nexus 3132Q-V の QSFP ポートの代わりに 4 つの SFP+ ポートをアクティブにするには、「 hardware profile front portmode sf-plus 」コマンドを使用します。同様に、「 hardware profile front portmode QSFP 」コマンドを使用すると、 Nexus 3132Q-V をリセットして、 4 つの SFP+ ポートの代わりに QSFP ポートを使用できます。

* Nexus 3132Q-V上の一部のポートを10GbEまたは40/100GbEで実行するように設定していることを確認します。
+
最初の 6 つのポートを 4x10 GbE モードに分割するには、「 interface breakout module 1 port 1-6 map 10g-4x 」コマンドを使用します。同様に、 no interface breakout module 1 port 1-6 map 10g-4x コマンドを使用して、ブレークアウト構成から最初の 6 つの QSFP+ ポートをグループ化し直すことができます。

* 10GbE ポートと 40 / 100GbE ポートの数は、で使用可能なリファレンス構成ファイル（ RCF ）に定義されています https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® Cluster Network Switch Reference Configuration File Download （ Cisco ® クラスタネットワークスイッチリファレンス構成ファイルのダウンロード"^] ページ


.必要なもの
* 構成が適切にセットアップされ、機能している。
* ONTAP 9.4以降を実行しているノード。
* のすべてのクラスタポート `up` 状態。
* Cisco Nexus 3132Q-V クラスタスイッチがサポートされています。
* 既存のクラスタネットワーク構成には次のものがあります。
+
** 両方のスイッチで冗長性があり、完全に機能する Nexus 3132 クラスタインフラ。
** スイッチにインストールされている最新の RCF および NX-OS バージョン
+
。 link:http://mysupport.netapp.com/NOW/download/software/cm_switches/["Cisco イーサネットスイッチ"^] この手順 でサポートされている ONTAP および NX-OS のバージョンについては、ページを参照してください。

** 両方のスイッチで管理接続を使用します。
** 両方のスイッチへのコンソールアクセス
** すべてのクラスタ LIF （論理インターフェイス）は、「 up 」状態のまま移行されません。
** スイッチの初期カスタマイズ。
** すべての ISL ポートが有効でケーブル接続されている。




また、ノードからNexus 3132Q-Vクラスタスイッチへの10GbEおよび40/100GbE接続に必要なドキュメントを計画、移行、および読み取る必要があります。



== スイッチを移行します

.例について
この手順の例では、スイッチとノードで次の命名法を使用しています。

* Nexus3132Q-V クラスタスイツチ、 C1 ト C2 。
* ノードが n1 と n2 です。


[NOTE]
====
この手順 の例では、 2 つのノードを使用し、それぞれ 40/100GbE クラスタインターコネクトポート e4A と e4e を使用しています。。 link:https://hwu.netapp.com/["Hardware Universe"^] プラットフォームのクラスタポートに関する詳細が表示されます。

====
.このタスクについて
この手順 では、次のシナリオについて説明します。

* n1_clus1 は、ノード n1 のクラスタスイッチ C1 に接続する最初のクラスタ論理インターフェイス（ LIF ）です。
* n1_clus2 は、ノード n1 のクラスタスイッチ C2 に接続する最初のクラスタ LIF です。
* n2_clus1 は、ノード n2 のクラスタスイッチ C1 に接続する最初のクラスタ LIF です。
* n2_clus2 は、ノード n2 のクラスタスイッチ C2 に接続する 2 番目のクラスタ LIF です。
* 10GbE ポートと 40 / 100GbE ポートの数は、で使用可能なリファレンス構成ファイル（ RCF ）に定義されています https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® Cluster Network Switch Reference Configuration File Download （ Cisco ® クラスタネットワークスイッチリファレンス構成ファイルのダウンロード"^] ページ


[NOTE]
====
手順 では、 ONTAP コマンドと Cisco Nexus 3000 シリーズスイッチコマンドの両方を使用する必要があります。特に明記されていないかぎり、 ONTAP コマンドを使用します。

====
* 2 ノードスイッチレスクラスタ設定で、 2 つのノードが接続されて機能している状態からクラスタを開始します。
* 最初のクラスタポートはC1に移動する。
* 2番目のクラスタポートはC2に移動されます。
* 2ノードスイッチレスクラスタオプションは無効になっています。




=== 手順1：移行の準備

. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。
+
'system node AutoSupport invoke -node * -type all -message MAINT=xh`

+
_x_ は、メンテナンス時間の長さ（時間単位）です。

+
[NOTE]
====
AutoSupport メッセージはテクニカルサポートにこのメンテナンスタスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

====
. 各クラスタインターフェイスの管理ステータスまたは動作ステータスを確認します。
+
.. ネットワークポートの属性を表示します。
+
「 network port show 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====
.. 論理インターフェイスに関する情報を表示します。
+
「 network interface show 」を参照してください

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====


. 必要に応じて、新しい 3132Q-V スイッチに適切な RCF とイメージがインストールされていることを確認し、ユーザとパスワード、ネットワークアドレスなどの基本的なサイトのカスタマイズを行います。
+
この時点で両方のスイッチを準備する必要があります。RCF とイメージソフトウェアをアップグレードする必要がある場合は、次の手順を実行する必要があります。

+
.. にアクセスします link:http://support.netapp.com/NOW/download/software/cm_switches/["Cisco イーサネットスイッチ"^] ネットアップサポートサイトのページを参照してください。
.. 使用しているスイッチおよび必要なソフトウェアバージョンを、このページの表に記載します。
.. 適切なバージョンの RCF をダウンロードします。
.. 概要 * ページで * continue * をクリックし、ライセンス契約に同意して、 * Download * ページの手順に従ってをダウンロードします。
.. 適切なバージョンのイメージソフトウェアをダウンロードします。


. 概要 * ページで * continue * をクリックし、ライセンス契約に同意して、 * Download * ページの手順に従ってをダウンロードします。




=== 手順2：最初のクラスタポートをC1に移動する

. Nexus 3132Q-V スイッチ C1 および C2 では、ノードに接続されたすべてのポート C1 と C2 を無効にするが、 ISL ポートは無効にしない。
+
.例を示します
[%collapsible]
====
次の例は、 RCF でサポートされている設定を使用して Nexus 3132Q-V クラスタスイッチ C1 と C2 のポート 1~30 を無効にします `NX3132_RCF_v1.1_24p10g_26p40g.txt`：

[listing]
----
C1# copy running-config startup-config
[########################################] 100%
Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit

C2# copy running-config startup-config
[########################################] 100%
Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. サポートされているケーブル配線を使用して、 C1 のポート 1/31 および 1/32 を C2 の同じポートに接続します。
. C1 と C2 で ISL ポートが動作していることを確認します。
+
「ポートチャネルの概要」

+
.例を示します
[%collapsible]
====
[listing]
----
C1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. スイッチ上の隣接デバイスのリストを表示します。
+
'How CDP Neighbors' を参照してください

+
.例を示します
[%collapsible]
====
[listing]
----
C1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3132Q-V  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3132Q-V  Eth1/32

Total entries displayed: 2

C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3132Q-V  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3132Q-V  Eth1/32

Total entries displayed: 2
----
====
. 各ノードのクラスタポート接続を表示します。
+
「 network device-discovery show 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例は、 2 ノードスイッチレスクラスタ構成を示しています。

[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====
. clus1 インターフェイスを、 clus2 をホストする物理ポートに移行します。
+
「ネットワーク・インターフェイス移行」

+
このコマンドは各ローカルノードから実行します。

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus1 -source-node n1
–destination-node n1 -destination-port e4e
cluster::*> network interface migrate -vserver Cluster -lif n2_clus1 -source-node n2
–destination-node n2 -destination-port e4e
----
====
. クラスタインターフェイスの移行を確認します。
+
「 network interface show 」を参照してください

+
.例を示します
[%collapsible]
====
[listing]
----

cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 両方のノードでクラスタポート clus1 LIF をシャットダウンします。
+
「 network port modify 」を参照してください

+
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin false
cluster::*> network port modify -node n2 -port e4a -up-admin false
----
. リモートクラスタインターフェイスに ping を実行し、 RPC サーバチェックを実行します。
+
「 cluster ping-cluster 」を参照してください

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> cluster ping-cluster -node n1
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e4a	10.10.0.1
Cluster n1_clus2 n1		e4e	10.10.0.2
Cluster n2_clus1 n2		e4a	10.10.0.3
Cluster n2_clus2 n2		e4e	10.10.0.4

Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
====
. ノード n1 の e4A からケーブルを外します。
+
実行コンフィギュレーションを参照し、 Nexus 3132Q-V でサポートされているケーブル接続を使用して、スイッチ C1 （この例ではポート 1/7 ）の最初の 40 GbE ポートを n1 の e4A に接続します

+

NOTE: 新しい Cisco クラスタスイッチにケーブルを再接続する場合は、使用するケーブルがシスコによってサポートされているファイバまたはケーブルである必要があります。

. ノード n2 の e4A からケーブルを外します。
+
サポートされているケーブルを使用して、実行構成を参照し、 C1 のポート 1/8 で使用可能な次の 40GbE ポートに e4A を接続します。

. C1 ですべてのノード側ポートを有効にします。
+
.例を示します
[%collapsible]
====
次の例は、 RCF でサポートされている設定を使用して、 Nexus 3132Q-V クラスタスイッチ C1 と C2 でポート 1~30 を有効にします `NX3132_RCF_v1.1_24p10g_26p40g.txt`：

[listing]
----
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# no shutdown
C1(config-if-range)# exit
C1(config)# exit
----
====
. 各ノードで、最初のクラスタポート e4A を有効にします。
+
「 network port modify 」を参照してください

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin true
cluster::*> network port modify -node n2 -port e4a -up-admin true
----
====
. 両方のノードでクラスタが動作していることを確認します。
+
「 network port show 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====
. 各ノードについて、移行したすべてのクラスタインターコネクト LIF をリバートします。
+
「 network interface revert 」の略

+
.例を示します
[%collapsible]
====
次の例は、移行された LIF をホームポートにリバートする方法を示しています。

[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus1
cluster::*> network interface revert -vserver Cluster -lif n2_clus1
----
====
. すべてのクラスタインターコネクトポートがホームポートにリバートされたことを確認します。
+
「 network interface show 」を参照してください

+
Is Home カラムには ' Current Port カラムに一覧表示されているすべてのポートの値 'true' が表示されます表示された値が「 false 」の場合、ポートはリバートされていません。

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====




=== 手順3：2つ目のクラスタポートをc2に移動します

. 各ノードのクラスタポート接続を表示します。
+
「 network device-discovery show 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3132Q-V
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3132Q-V
            e4e    n1                  e4e              FAS9000
----
====
. 各ノードのコンソールで、 clus2 をポート e4A に移行します。
+
「ネットワーク・インターフェイス移行」

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1
–destination-node n1 -destination-port e4a
cluster::*> network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2
–destination-node n2 -destination-port e4a
----
====
. 両方のノードでクラスタポート clus2 LIF をシャットダウンします。
+
「 network port modify 」を参照してください

+
次の例は、指定したポートを両方のノードでシャットダウンしています。

+
[listing]
----
	cluster::*> network port modify -node n1 -port e4e -up-admin false
	cluster::*> network port modify -node n2 -port e4e -up-admin false
----
. クラスタの LIF のステータスを確認します。
+
「 network interface show 」を参照してください

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. ノード n1 の e4e からケーブルを外します。
+
Nexus 3132Q-V でサポートされているケーブル接続を使用して、スイッチ c2 の最初の 40GbE ポート（この例ではポート 1/7 ）を e4e に接続します

. ノード n2 の e4e からケーブルを外します。
+
サポートされているケーブル接続を使用して、実行構成を参照し、 c2 のポート 1 / 8 に次に使用可能な 40GbE ポートに e4e を接続します。

. C2 のすべてのノード側ポートを有効にします。
+
.例を示します
[%collapsible]
====
次の例は、 RCF でサポートされている設定を使用して Nexus 3132Q-V クラスタスイッチ C1 と C2 のポート 1~30 を有効にします `NX3132_RCF_v1.1_24p10g_26p40g.txt`：

[listing]
----
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. 各ノードで 2 つ目のクラスタポート e4e を有効にします。
+
「 network port modify 」を参照してください

+
次の例は、指定したポートを起動します。

+
[listing]
----
	cluster::*> network port modify -node n1 -port e4e -up-admin true
	cluster::*> network port modify -node n2 -port e4e -up-admin true
----
. 各ノードについて、移行したすべてのクラスタインターコネクト LIF をリバートします。
+
「 network interface revert 」の略

+
次の例は、移行された LIF をホームポートにリバートする方法を示しています。

+
[listing]
----
	cluster::*> network interface revert -vserver Cluster -lif n1_clus2
	cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
. すべてのクラスタインターコネクトポートがホームポートにリバートされたことを確認します。
+
「 network interface show 」を参照してください

+
Is Home カラムには ' Current Port カラムに一覧表示されているすべてのポートの値 'true' が表示されます表示された値が「 false 」の場合、ポートはリバートされていません。

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. すべてのクラスタ・インターコネクト・ポートが up 状態になっていることを確認します。
+
`network port show –role cluster`

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====




=== 手順4：2ノードスイッチレスクラスタオプションを無効にします

. 各クラスタポートが各ノードで接続されているクラスタスイッチのポート番号を表示します。
+
「 network device-discovery show 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing]
----
	cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3132Q-V
            e4e    C2                  Ethernet1/7      N3K-C3132Q-V
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3132Q-V
            e4e    C2                  Ethernet1/8      N3K-C3132Q-V
----
====
. 検出された監視対象のクラスタスイッチを表示します。
+
「 system cluster-switch show

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                         cluster-network     10.10.1.101      NX3132V
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network     10.10.1.102      NX3132V
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
====
. 任意のノードで 2 ノードスイッチレス構成を無効にします。
+
「 network options switchless-cluster 」を参照してください

+
[listing]
----
network options switchless-cluster modify -enabled false
----
. を確認します `switchless-cluster` オプションが無効になりました。
+
[listing]
----
network options switchless-cluster show
----




=== 手順5：設定を確認します

. リモートクラスタインターフェイスに ping を実行し、 RPC サーバチェックを実行します。
+
「 cluster ping-cluster 」を参照してください

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> cluster ping-cluster -node n1
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e4a	10.10.0.1
Cluster n1_clus2 n1		e4e	10.10.0.2
Cluster n2_clus1 n2		e4a	10.10.0.3
Cluster n2_clus2 n2		e4e	10.10.0.4

Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
====
. スイッチ関連のログファイルを収集するために、クラスタスイッチヘルスモニタのログ収集機能を有効にします。
+
「 system cluster-switch log setup -password 」と入力します

+
'system cluster-switch log enable-colion

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> **system cluster-switch log setup-password**
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
C1
C2

cluster::*> system cluster-switch log setup-password

Enter the switch name: C1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster::*> system cluster-switch log setup-password

Enter the switch name: C2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster::*> system cluster-switch log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster::*>
----
====
+

NOTE: これらのコマンドのいずれかでエラーが返される場合は、ネットアップサポートにお問い合わせください。

. ケースの自動作成を抑制した場合は、 AutoSupport メッセージを呼び出して作成を再度有効にします。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます


