---
permalink: switch-cisco-3132q-v/migrate-switchless-to-switched-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Cisco Nexus 3132q-v スイッチを構成する前に、プロセスと命名法の概要を確認してください。 
---
= 移行要件
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
2 ノードのスイッチレス クラスターがある場合は、2 ノードのスイッチ クラスターに移行するための適用可能な要件については、この手順を確認してください。

[NOTE]
====
この手順では、ONTAPコマンドとCisco Nexus 3000シリーズ スイッチ コマンドの両方を使用する必要があります。特に明記されていないかぎり、ONTAPコマンドを使用します。

====
詳細については、以下を参照してください。

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 および CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^]
* link:http://hwu.netapp.com["Hardware Universe"^]


.ポートとノードの接続
Cisco Nexus 3132Q-V クラスタ スイッチを使用した 2 ノード スイッチ クラスタに移行する場合は、ポートとノードの接続およびケーブル接続の要件を理解していることを確認してください。

* クラスタ スイッチは、スイッチ間リンク (ISL) ポート e1/31-32 を使用します。
* そのlink:https://hwu.netapp.com/["Hardware Universe"^]Nexus 3132Q-V スイッチへのサポートされているケーブル接続に関する情報が含まれています。
+
** 10 GbE クラスター接続を持つノードには、ブレークアウト ファイバー ケーブル付きの QSFP 光モジュール、または QSFP から SFP+ への銅ブレークアウト ケーブルが必要です。
** 40 GbE クラスター接続を持つノードには、ファイバー ケーブルまたは QSFP/QSFP28 銅線直接接続ケーブルを備えたサポートされている QSFP/QSFP28 光モジュールが必要です。
** クラスター スイッチでは、適切な ISL ケーブル (2 本の QSFP28 ファイバー ケーブルまたは銅線直接接続ケーブル) が使用されます。


* Nexus 3132Q-V では、QSFP ポートを 40 Gb イーサネット モードまたは 4x10 Gb イーサネット モードのいずれかで動作させることができます。
+
デフォルトでは、40 Gb イーサネット モードには 32 個のポートがあります。これらの 40 Gb イーサネット ポートは、2 タプルの命名規則に従って番号が付けられます。たとえば、2 番目の 40 Gb イーサネット ポートの番号は 1/2 になります。  40 Gb イーサネットから 10 Gb イーサネットに構成を変更するプロセスは _breakout_ と呼ばれ、10 Gb イーサネットから 40 Gb イーサネットに構成を変更するプロセスは _breakin_ と呼ばれます。 40 Gb イーサネット ポートを 10 Gb イーサネット ポートに分割すると、結果のポートは 3 タプルの命名規則を使用して番号が付けられます。たとえば、2 番目の 40 Gb イーサネット ポートのブレークアウト ポートには、1/2/1、1/2/2、1/2/3、1/2/4 という番号が付けられます。

* Nexus 3132Q-V の左側には、最初の QSFP ポートに多重化された 4 つの SFP+ ポートのセットがあります。
+
デフォルトでは、RCF は最初の QSFP ポートを使用するように構成されています。

+
Nexus 3132Q-VのQSFPポートの代わりに4つのSFP+ポートをアクティブにするには、 `hardware profile front portmode sfp-plus`指示。同様に、Nexus 3132Q-Vを4つのSFP+ポートの代わりにQSFPポートを使用するようにリセットすることもできます。 `hardware profile front portmode qsfp`指示。

* Nexus 3132Q-V の一部のポートが 10 GbE または 40 GbE で動作するように設定されていることを確認してください。
+
最初の6つのポートを4x10 GbEモードにブレークアウトするには、 `interface breakout module 1 port 1-6 map 10g-4x`指示。同様に、最初の6つのQSFP+ポートをブレイクアウト構成から再グループ化するには、 `no interface breakout module 1 port 1-6 map 10g-4x`指示。

* 10 GbEおよび40 GbEポートの数は、次のURLで入手可能なリファレンス構成ファイル（RCF）で定義されています。link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco ® クラスタ ネットワーク スイッチ リファレンス コンフィギュレーション ファイルのダウンロード"^] 。


.開始する前に
* 構成が適切に設定され、機能しています。
* ONTAP 9.4 以降を実行しているノード。
* すべてのクラスタポート `up`州。
* Cisco Nexus 3132Q-V クラスタ スイッチがサポートされています。
* 既存のクラスター ネットワーク構成は次のとおりです。
+
** 両方のスイッチで冗長化され、完全に機能する Nexus 3132 クラスタ インフラストラクチャ。
** スイッチ上の最新の RCF および NX-OS バージョン。
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^]この手順でサポートされているONTAPおよび NX-OS のバージョンに関する情報が記載されています。

** 両方のスイッチでの管理接続。
** 両方のスイッチへのコンソール アクセス。
** すべてのクラスタ論理インターフェース（LIF）は、 `up`移行されない状態。
** スイッチの初期カスタマイズ。
** すべての ISL ポートが有効になり、ケーブル接続されています。




さらに、ノードから Nexus 3132Q-V クラスタ スイッチへの 10 GbE および 40 GbE 接続を計画し、移行し、必要なドキュメントを読む必要があります。

.使用された例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* Nexus 3132Q-V クラスタ スイッチ、C1 および C2。
* ノードは n1 と n2 です。


[NOTE]
====
この手順の例では、2 つのノードを使用し、各ノードで 2 つの 40 GbE クラスタ相互接続ポート *e4a* と *e4e* を使用します。そのlink:https://hwu.netapp.com/["Hardware Universe"^]プラットフォーム上のクラスター ポートに関する詳細が記載されています。

====
この手順では、次のシナリオについて説明します。

* *n1_clus1* は、ノード *n1* のクラスタ スイッチ C1 に接続される最初のクラスタ論理インターフェイス (LIF) です。
* *n1_clus2* は、ノード *n1* のクラスタ スイッチ C2 に接続される最初のクラスタ LIF です。
* *n2_clus1* は、ノード *n2* のクラスタ スイッチ C1 に接続される最初のクラスタ LIF です。
* *n2_clus2* は、ノード *n2* のクラスタ スイッチ C2 に接続される 2 番目のクラスタ LIF です。
* 10 GbEおよび40 GbEポートの数は、次のURLで入手可能なリファレンス構成ファイル（RCF）で定義されています。link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco ® クラスタ ネットワーク スイッチ リファレンス コンフィギュレーション ファイルのダウンロード"^] 。


[NOTE]
====
この手順では、ONTAPコマンドとCisco Nexus 3000シリーズ スイッチ コマンドの両方を使用する必要があります。特に明記されていないかぎり、ONTAPコマンドを使用します。

====
* クラスターは、2 つのノードが接続され、2 ノード スイッチレス クラスター設定で機能している状態で起動します。
* 最初のクラスター ポートは C1 に移動されます。
* 2 番目のクラスター ポートは C2 に移動されます。
* 2 ノード スイッチレス クラスター オプションは無効になっています。


.次の手順
移行要件を確認したら、link:migrate-switchless-prepare-to-migrate.html["スイッチの移行を準備する"] 。
