---
permalink: switch-cisco-3132q-v/migrate-switchless-configure-ports.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: Cisco Nexus 3132q-v スイッチを、 AFFまたはFASクラスタ内のクラスタ スイッチとして使用できます。 
---
= スイッチレス クラスタからスイッチ クラスタへの移行用にポートを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
2 ノード スイッチレス クラスターから 2 ノード スイッチ クラスターへの移行用にポートを構成するには、次の手順に従います。

.手順
. Nexus 3132Q-V スイッチ C1 および C2 で、ノード側のポート C1 および C2 をすべて無効にしますが、ISL ポートは無効にしないでください。
+
.例を表示
[%collapsible]
====
次の例は、RCFでサポートされている設定を使用して、Nexus 3132Q-VクラスタスイッチC1とC2のポート1～30が無効になっていることを示しています。 `NX3132_RCF_v1.1_24p10g_26p40g.txt` :

[listing]
----
C1# copy running-config startup-config
[########################################] 100%
Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit

C2# copy running-config startup-config
[########################################] 100%
Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. サポートされているケーブルを使用して、C1 のポート 1/31 と 1/32 を C2 の同じポートに接続します。
. C1 および C2 で ISL ポートが動作していることを確認します。
+
`show port-channel summary`

+
.例を表示
[%collapsible]
====
[listing]
----
C1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. スイッチ上の隣接デバイスのリストを表示します。
+
`show cdp neighbors`

+
.例を表示
[%collapsible]
====
[listing]
----
C1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3132Q-V  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3132Q-V  Eth1/32

Total entries displayed: 2

C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3132Q-V  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3132Q-V  Eth1/32

Total entries displayed: 2
----
====
. 各ノードのクラスター ポートの接続を表示します。
+
`network device-discovery show`

+
.例を表示
[%collapsible]
====
次の例は、2 ノードのスイッチレス クラスター構成を示しています。

[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====
. clus1 インターフェイスを clus2 をホストする物理ポートに移行します。
+
`network interface migrate`

+
各ローカルノードからこのコマンドを実行します。

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e4e
cluster::*> network interface migrate -vserver Cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e4e
----
====
. クラスタ インターフェースの移行を確認します。
+
`network interface show`

+
.例を表示
[%collapsible]
====
[listing]
----

cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 両方のノードでクラスタ ポート clus1 LIF をシャットダウンします。
+
`network port modify`

+
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin false
cluster::*> network port modify -node n2 -port e4a -up-admin false
----
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 詳細を表示するには、show コマンドを実行する前に数秒待ってください。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2        n2_clus1      none
       3/5/2022 19:21:20 -06:00   n1_clus2        n2_clus2      none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2        n1_clus1      none
       3/5/2022 19:21:20 -06:00   n2_clus2        n1_clus2      none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e4a	10.10.0.1
Cluster n1_clus2 n1		e4e	10.10.0.2
Cluster n2_clus1 n2		e4a	10.10.0.3
Cluster n2_clus2 n2		e4e	10.10.0.4

Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step10]]ノードn1のe4aからケーブルを外します。
+
実行中の設定を参照し、Nexus 3132Q-V でサポートされているケーブルを使用して、スイッチ C1 の最初の 40 GbE ポート (この例ではポート 1/7) を n1 の e4a に接続できます。

+

NOTE: 新しいCiscoクラスタ スイッチにケーブルを再接続する場合、使用するケーブルは、 Ciscoがサポートする光ファイバーまたはケーブルである必要があります。

. ノード n2 の e4a からケーブルを外します。
+
実行中の設定を参照し、サポートされているケーブルを使用して、e4a を C1 の次の使用可能な 40 GbE ポート (ポート 1/8) に接続できます。

. C1 上のすべてのノード向けポートを有効にします。
+
.例を表示
[%collapsible]
====
次の例は、RCFでサポートされている設定を使用して、Nexus 3132Q-VクラスタスイッチC1とC2でポート1～30が有効になっていることを示しています。 `NX3132_RCF_v1.1_24p10g_26p40g.txt` :

[listing]
----
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# no shutdown
C1(config-if-range)# exit
C1(config)# exit
----
====
. 各ノードで最初のクラスター ポート e4a を有効にします。
+
`network port modify`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin true
cluster::*> network port modify -node n2 -port e4a -up-admin true
----
====
. 両方のノードでクラスターが起動していることを確認します。
+
`network port show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====
. 各ノードについて、移行されたすべてのクラスタ相互接続 LIF を元に戻します。
+
`network interface revert`

+
.例を表示
[%collapsible]
====
次の例は、移行された LIF がホーム ポートに戻されることを示しています。

[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus1
cluster::*> network interface revert -vserver Cluster -lif n2_clus1
----
====
. すべてのクラスタ相互接続ポートがホーム ポートに戻っていることを確認します。
+
`network interface show`

+
その `Is Home`列には次の値が表示されます `true`に記載されているすべてのポートについて `Current Port`カラム。表示されている値が `false`ポートは元に戻されていません。

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 各ノードのクラスター ポートの接続を表示します。
+
`network device-discovery show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3132Q-V
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3132Q-V
            e4e    n1                  e4e              FAS9000
----
====
. 各ノードのコンソールで、clus2 をポート e4a に移行します。
+
`network interface migrate`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1
-destination-node n1 -destination-port e4a
cluster::*> network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2
-destination-node n2 -destination-port e4a
----
====
. 両方のノードでクラスター ポート clus2 LIF をシャットダウンします。
+
`network port modify`

+
次の例では、両方のノードで指定されたポートがシャットダウンされています。

+
[listing]
----
cluster::*> network port modify -node n1 -port e4e -up-admin false
cluster::*> network port modify -node n2 -port e4e -up-admin false
----
. クラスタ LIF のステータスを確認します。
+
`network interface show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. ノード n1 の e4e からケーブルを外します。
+
実行中の設定を参照し、Nexus 3132Q-V でサポートされているケーブルを使用して、スイッチ C2 の最初の 40 GbE ポート (この例ではポート 1/7) を n1 の e4e に接続できます。

. ノード n2 の e4e からケーブルを外します。
+
実行中の設定を参照し、サポートされているケーブルを使用して、e4e を C2 の次の使用可能な 40 GbE ポート (ポート 1/8) に接続できます。

. C2 上のすべてのノード向けポートを有効にします。
+
.例を表示
[%collapsible]
====
次の例は、RCFでサポートされている設定を使用して、Nexus 3132Q-VクラスタスイッチC1とC2でポート1～30が有効になっていることを示しています。 `NX3132_RCF_v1.1_24p10g_26p40g.txt` :

[listing]
----
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. 各ノードで 2 番目のクラスター ポート e4e を有効にします。
+
`network port modify`

+
次の例では、指定されたポートが起動される様子を示しています。

+
[listing]
----
cluster::*> network port modify -node n1 -port e4e -up-admin true
cluster::*> network port modify -node n2 -port e4e -up-admin true
----
. 各ノードについて、移行されたすべてのクラスタ相互接続 LIF を元に戻します。
+
`network interface revert`

+
次の例は、移行された LIF がホーム ポートに戻されることを示しています。

+
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
. すべてのクラスタ相互接続ポートがホーム ポートに戻っていることを確認します。
+
`network interface show`

+
その `Is Home`列には次の値が表示されます `true`に記載されているすべてのポートについて `Current Port`カラム。表示されている値が `false`ポートは元に戻されていません。

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. すべてのクラスタ相互接続ポートが `up`州。
+
`network port show -role cluster`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====


.次の手順
link:migrate-switchless-complete-migration.html["移行を完了する"] 。
