---
permalink: switch-cisco-3132q-v/migrate-switchless-configure-ports.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: Cisco Nexus 3132q-Vスイッチは、AFFまたはFASクラスタのクラスタスイッチとして使用できます。 
---
= スイッチレスクラスタからスイッチクラスタへ移行するためのポートの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
2ノードスイッチレスクラスタから2ノードスイッチクラスタに移行するためにポートを設定するには、次の手順を実行します。

.手順
. Nexus 3132Q-V スイッチ C1 および C2 では、ノードに接続されたすべてのポート C1 と C2 を無効にするが、 ISL ポートは無効にしない。
+
.例を示します
[%collapsible]
====
次の例は、 RCF でサポートされている設定を使用して Nexus 3132Q-V クラスタスイッチ C1 と C2 のポート 1~30 を無効にします `NX3132_RCF_v1.1_24p10g_26p40g.txt`：

[listing]
----
C1# copy running-config startup-config
[########################################] 100%
Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit

C2# copy running-config startup-config
[########################################] 100%
Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. サポートされているケーブル配線を使用して、 C1 のポート 1/31 および 1/32 を C2 の同じポートに接続します。
. C1 と C2 で ISL ポートが動作していることを確認します。
+
「ポートチャネルの概要」

+
.例を示します
[%collapsible]
====
[listing]
----
C1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. スイッチ上の隣接デバイスのリストを表示します。
+
'How CDP Neighbors' を参照してください

+
.例を示します
[%collapsible]
====
[listing]
----
C1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3132Q-V  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3132Q-V  Eth1/32

Total entries displayed: 2

C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3132Q-V  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3132Q-V  Eth1/32

Total entries displayed: 2
----
====
. 各ノードのクラスタポート接続を表示します。
+
「 network device-discovery show 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例は、 2 ノードスイッチレスクラスタ構成を示しています。

[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====
. clus1 インターフェイスを、 clus2 をホストする物理ポートに移行します。
+
「ネットワーク・インターフェイス移行」

+
このコマンドは各ローカルノードから実行します。

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e4e
cluster::*> network interface migrate -vserver Cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e4e
----
====
. クラスタインターフェイスの移行を確認します。
+
「 network interface show 」を参照してください

+
.例を示します
[%collapsible]
====
[listing]
----

cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 両方のノードでクラスタポート clus1 LIF をシャットダウンします。
+
「 network port modify 」を参照してください

+
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin false
cluster::*> network port modify -node n2 -port e4a -up-admin false
----
. リモートクラスタインターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
を使用できます `network interface check cluster-connectivity` コマンドを使用してクラスタ接続のアクセスチェックを開始し、詳細を表示します。

`network interface check cluster-connectivity start` および `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注：* showコマンドを実行して詳細を表示する前に、数秒待ってください。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2        n2_clus1      none
       3/5/2022 19:21:20 -06:00   n1_clus2        n2_clus2      none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2        n1_clus1      none
       3/5/2022 19:21:20 -06:00   n2_clus2        n1_clus2      none
----
--
.すべてのONTAPリリース
--
すべてのONTAPリリースで、 `cluster ping-cluster -node <name>` 接続を確認するコマンド：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e4a	10.10.0.1
Cluster n1_clus2 n1		e4e	10.10.0.2
Cluster n2_clus1 n2		e4a	10.10.0.3
Cluster n2_clus2 n2		e4e	10.10.0.4

Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step10]]ノードn1のE4Aからケーブルを外します。
+
実行コンフィギュレーションを参照し、 Nexus 3132Q-V でサポートされているケーブル接続を使用して、スイッチ C1 （この例ではポート 1/7 ）の最初の 40 GbE ポートを n1 の e4A に接続します

+

NOTE: 新しい Cisco クラスタスイッチにケーブルを再接続する場合は、使用するケーブルがシスコによってサポートされているファイバまたはケーブルである必要があります。

. ノード n2 の e4A からケーブルを外します。
+
サポートされているケーブルを使用して、実行構成を参照し、 C1 のポート 1/8 で使用可能な次の 40GbE ポートに e4A を接続します。

. C1 ですべてのノード側ポートを有効にします。
+
.例を示します
[%collapsible]
====
次の例は、 RCF でサポートされている設定を使用して、 Nexus 3132Q-V クラスタスイッチ C1 と C2 でポート 1~30 を有効にします `NX3132_RCF_v1.1_24p10g_26p40g.txt`：

[listing]
----
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# no shutdown
C1(config-if-range)# exit
C1(config)# exit
----
====
. 各ノードで、最初のクラスタポート e4A を有効にします。
+
「 network port modify 」を参照してください

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin true
cluster::*> network port modify -node n2 -port e4a -up-admin true
----
====
. 両方のノードでクラスタが動作していることを確認します。
+
「 network port show 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====
. 各ノードについて、移行したすべてのクラスタインターコネクト LIF をリバートします。
+
「 network interface revert 」の略

+
.例を示します
[%collapsible]
====
次の例は、移行された LIF をホームポートにリバートする方法を示しています。

[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus1
cluster::*> network interface revert -vserver Cluster -lif n2_clus1
----
====
. すべてのクラスタインターコネクトポートがホームポートにリバートされたことを確認します。
+
「 network interface show 」を参照してください

+
Is Home カラムには ' Current Port カラムに一覧表示されているすべてのポートの値 'true' が表示されます表示された値が「 false 」の場合、ポートはリバートされていません。

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 各ノードのクラスタポート接続を表示します。
+
「 network device-discovery show 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3132Q-V
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3132Q-V
            e4e    n1                  e4e              FAS9000
----
====
. 各ノードのコンソールで、 clus2 をポート e4A に移行します。
+
「ネットワーク・インターフェイス移行」

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1
-destination-node n1 -destination-port e4a
cluster::*> network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2
-destination-node n2 -destination-port e4a
----
====
. 両方のノードでクラスタポート clus2 LIF をシャットダウンします。
+
「 network port modify 」を参照してください

+
次の例は、指定したポートを両方のノードでシャットダウンしています。

+
[listing]
----
cluster::*> network port modify -node n1 -port e4e -up-admin false
cluster::*> network port modify -node n2 -port e4e -up-admin false
----
. クラスタの LIF のステータスを確認します。
+
「 network interface show 」を参照してください

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. ノード n1 の e4e からケーブルを外します。
+
Nexus 3132Q-V でサポートされているケーブル接続を使用して、スイッチ c2 の最初の 40GbE ポート（この例ではポート 1/7 ）を e4e に接続します

. ノード n2 の e4e からケーブルを外します。
+
サポートされているケーブル接続を使用して、実行構成を参照し、 c2 のポート 1 / 8 に次に使用可能な 40GbE ポートに e4e を接続します。

. C2 のすべてのノード側ポートを有効にします。
+
.例を示します
[%collapsible]
====
次の例は、 RCF でサポートされている設定を使用して Nexus 3132Q-V クラスタスイッチ C1 と C2 のポート 1~30 を有効にします `NX3132_RCF_v1.1_24p10g_26p40g.txt`：

[listing]
----
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. 各ノードで 2 つ目のクラスタポート e4e を有効にします。
+
「 network port modify 」を参照してください

+
次の例は、指定したポートを起動します。

+
[listing]
----
cluster::*> network port modify -node n1 -port e4e -up-admin true
cluster::*> network port modify -node n2 -port e4e -up-admin true
----
. 各ノードについて、移行したすべてのクラスタインターコネクト LIF をリバートします。
+
「 network interface revert 」の略

+
次の例は、移行された LIF をホームポートにリバートする方法を示しています。

+
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
. すべてのクラスタインターコネクトポートがホームポートにリバートされたことを確認します。
+
「 network interface show 」を参照してください

+
Is Home カラムには ' Current Port カラムに一覧表示されているすべてのポートの値 'true' が表示されます表示された値が「 false 」の場合、ポートはリバートされていません。

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. すべてのクラスタ・インターコネクト・ポートが up 状態になっていることを確認します。
+
「 network port show -role cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====


.次の手順
link:migrate-switchless-complete-migration.html["移行の完了"]です。
