---
permalink: switch-cisco-3132q-v/migrate-switchless-to-switched-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Cisco Nexus 3132q-Vスイッチを設定する前に、プロセスの概要と命名法を確認してください。 
---
= 移行の要件
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
2ノードスイッチレスクラスタの場合は、以下の手順を参照して、2ノードスイッチクラスタに移行するための該当する要件を確認してください。

[NOTE]
====
手順 では、 ONTAP コマンドと Cisco Nexus 3000 シリーズスイッチコマンドの両方を使用する必要があります。特に明記されていないかぎり、 ONTAP コマンドを使用します。

====
詳細については、を参照してください

* http://support.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 / CN1610 の概要 ページ"^]
* http://support.netapp.com/NOW/download/software/cm_switches/["Cisco Ethernet Switch 概要 ページ"^]
* http://hwu.netapp.com["Hardware Universe"^]


.ポートとノードの接続
Cisco Nexus 3132Q-Vクラスタスイッチを使用する2ノードスイッチクラスタに移行する場合は、ポートとノードの接続とケーブル接続の要件を確認しておく必要があります。

* クラスタスイッチは、 Inter-Switch Link （ ISL ；スイッチ間リンク）ポート e1/31~32 を使用します。
* 。 link:https://hwu.netapp.com/["Hardware Universe"^] Nexus 3132Q-V スイッチでサポートされているケーブル接続に関する情報が含まれています。
+
** 10GbE クラスタ接続のノードには、ブレークアウト光ケーブルを備えた QSFP 光モジュールまたは QSFP-SFP+ 銅線ブレークアウトケーブルが必要です。
** 40GbEクラスタ接続を使用するノードには、ファイバケーブルまたはQSFP / QSFP28銅線直接接続ケーブルを備えた、サポートされているQSFP / QSFP28光モジュールが必要です。
** クラスタスイッチでは、適切な ISL ケーブルを使用します。 QSFP28 ファイバケーブルまたは銅線直接接続ケーブル × 2


* Nexus 3132Q-Vでは、QSFPポートを40 Gbイーサネットモードまたは4×10 Gbイーサネットモードとして動作できます。
+
デフォルトでは、40 Gbイーサネットモードには32個のポートがあります。これらの 40 Gb イーサネットポートには、 2 タプルの命名規則で番号が付けられます。たとえば、 2 番目の 40 Gb イーサネットポートには、 1/2 という番号が付けられます。構成を 40 Gb イーサネットから 10 Gb イーサネットに変更するプロセスは _ ブレークアウト _ と呼ばれ、構成を 10 Gb イーサネットから 40 Gb イーサネットに変更するプロセスは _ ブレークイン _ と呼ばれます。40Gbイーサネットポートを10Gbイーサネットポートに分割すると、作成されたポートに3タプルの命名規則を使用して番号が付けられます。たとえば、 2 番目の 40 Gb イーサネットポートのブレークアウトポートには、 1/2/1 、 1/2/2 、 1/2/3 、および 1/2/4 の番号が付けられます。

* Nexus 3132Q-V の左側には、 4 つの SFP+ ポートが 1 つ目の QSFP ポートに多重化されたセットがあります。
+
デフォルトでは、 RCF は最初の QSFP ポートを使用するように構成されています。

+
Nexus 3132Q-V の QSFP ポートの代わりに 4 つの SFP+ ポートをアクティブにするには、「 hardware profile front portmode sf-plus 」コマンドを使用します。同様に、「 hardware profile front portmode QSFP 」コマンドを使用すると、 Nexus 3132Q-V をリセットして、 4 つの SFP+ ポートの代わりに QSFP ポートを使用できます。

* Nexus 3132Q-Vの一部のポートが10GbEまたは40GbEで動作するように設定されていることを確認します。
+
最初の 6 つのポートを 4x10 GbE モードに分割するには、「 interface breakout module 1 port 1-6 map 10g-4x 」コマンドを使用します。同様に、 no interface breakout module 1 port 1-6 map 10g-4x コマンドを使用して、ブレークアウト構成から最初の 6 つの QSFP+ ポートをグループ化し直すことができます。

* 10GbEポートと40GbEポートの数は、ページで入手できるリファレンス構成ファイル（RCF）で定義し https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® Cluster Network Switch Reference Configuration File Download （ Cisco ® クラスタネットワークスイッチリファレンス構成ファイルのダウンロード"^]ます。


.作業を開始する前に
* 構成が適切にセットアップされ、機能している。
* ONTAP 9.4以降を実行しているノード。
* のすべてのクラスタポート `up` 状態。
* Cisco Nexus 3132Q-V クラスタスイッチがサポートされています。
* 既存のクラスタネットワーク構成には次のものがあります。
+
** 両方のスイッチで冗長性があり、完全に機能する Nexus 3132 クラスタインフラ。
** スイッチにインストールされている最新の RCF および NX-OS バージョン
+
。 link:http://mysupport.netapp.com/NOW/download/software/cm_switches/["Cisco イーサネットスイッチ"^] この手順 でサポートされている ONTAP および NX-OS のバージョンについては、ページを参照してください。

** 両方のスイッチで管理接続を使用します。
** 両方のスイッチへのコンソールアクセス
** すべてのクラスタ LIF （論理インターフェイス）は、「 up 」状態のまま移行されません。
** スイッチの初期カスタマイズ。
** すべての ISL ポートが有効でケーブル接続されている。




また、ノードからNexus 3132Q-Vクラスタスイッチへの10GbEおよび40GbE接続について計画し、必要なドキュメントを移行して読む必要があります。

.使用例について
この手順の例では、スイッチとノードで次の命名法を使用しています。

* Nexus3132Q-V クラスタスイツチ、 C1 ト C2 。
* ノードが n1 と n2 です。


[NOTE]
====
この手順の例では、2つのノードを使用し、それぞれに2つの40GbEクラスタインターコネクトポート* e4a *と* e4e *を使用します。にlink:https://hwu.netapp.com/["Hardware Universe"^]は、プラットフォームのクラスタポートに関する詳細が記載されています。

====
この手順 では、次のシナリオについて説明します。

* * n1_clus1 *は、ノード* n1 *のクラスタスイッチC1に接続される最初のクラスタ論理インターフェイス（LIF）です。
* * n1_clus2 *は、ノード* n1 *のクラスタスイッチc2に接続される最初のクラスタLIFです。
* * n2_clus1 *は、ノード* n2 *のクラスタスイッチC1に接続される最初のクラスタLIFです。
* * n2_clus2 *は、ノード* n2 *のクラスタスイッチc2に接続する2番目のクラスタLIFです。
* 10GbEポートと40GbEポートの数は、ページで入手できるリファレンス構成ファイル（RCF）で定義し https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® Cluster Network Switch Reference Configuration File Download （ Cisco ® クラスタネットワークスイッチリファレンス構成ファイルのダウンロード"^]ます。


[NOTE]
====
手順 では、 ONTAP コマンドと Cisco Nexus 3000 シリーズスイッチコマンドの両方を使用する必要があります。特に明記されていないかぎり、 ONTAP コマンドを使用します。

====
* 2 ノードスイッチレスクラスタ設定で、 2 つのノードが接続されて機能している状態からクラスタを開始します。
* 最初のクラスタポートはC1に移動する。
* 2番目のクラスタポートはC2に移動されます。
* 2ノードスイッチレスクラスタオプションは無効になっています。


.次の手順
link:migrate-switchless-prepare-to-migrate.html["移行を準備"]です。
