---
permalink: switch-cisco-3132q-v/migrate-switchless-to-switched-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Cisco Nexus 3132Q-V スイッチを設定する前に、プロセスと用語の概要を確認してください。 
---
= 移行要件
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
2ノードのスイッチレスクラスタを使用している場合は、2ノードのスイッチドクラスタに移行するための適用要件について、この手順を確認してください。

[NOTE]
====
この手順では、ONTAPコマンドとCisco Nexus 3000シリーズ スイッチ コマンドの両方を使用する必要があります。特に明記されていないかぎり、ONTAPコマンドを使用します。

====
詳細については、次を参照してください。

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 と CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^]
* link:http://hwu.netapp.com["Hardware Universe"^]


.ポートとノードの接続
Cisco Nexus 3132Q-V クラスタスイッチを使用する2ノードスイッチドクラスタに移行する際は、ポートとノードの接続およびケーブル配線の要件を十分に理解しておいてください。

* クラスタスイッチは、Inter-Switch Link（ISL）ポートe1/31-32を使用します。
* link:https://hwu.netapp.com/["Hardware Universe"^]には、Nexus 3132Q-Vスイッチへのサポートされているケーブル接続に関する情報が含まれています。
+
** 10 GbE クラスタ接続を備えたノードには、ブレークアウトファイバーケーブル付きの QSFP 光モジュール、または QSFP から SFP+ への銅線ブレークアウトケーブルが必要です。
** 40 GbE クラスタ接続を備えたノードには、ファイバーケーブルを使用するサポート対象の QSFP/QSFP28 光モジュール、または QSFP/QSFP28 銅線ダイレクトアタッチケーブルが必要です。
** クラスタスイッチは、適切なISLケーブル（2x QSFP28光ファイバーまたは銅線ダイレクトアタッチケーブル）を使用します。


* Nexus 3132Q-Vでは、QSFPポートを40 Gbイーサネットモードまたは4x10 Gbイーサネットモードのいずれかで動作させることができます。
+
デフォルトでは、40 Gb イーサネットモードには32個のポートがあります。これらの40 Gb イーサネットポートは、2タプルの命名規則を使用して番号が付けられています。例えば、2番目の40 Gb イーサネットポートは1/2と番号付けされます。40 Gb Ethernetから10 Gb Ethernetへの構成変更のプロセスは「ブレークアウト」と呼ばれ、10 Gb Ethernetから40 Gb Ethernetへの構成変更のプロセスは「ブレークイン」と呼ばれます。40 Gb Ethernetポートを10 Gb Ethernetポートに分割すると、結果として得られるポートは3タプルの命名規則を使用して番号付けされます。例えば、2番目の40 Gb イーサネットポートのブレークアウトポートは、1/2/1、1/2/2、1/2/3、および1/2/4と番号付けされます。

* Nexus 3132Q-Vの左側面には、最初のQSFPポートに多重化された4つのSFP+ポートが配置されています。
+
デフォルトでは、RCFは最初のQSFPポートを使用するように構成されています。

+
Nexus 3132Q-V では、 `hardware profile front portmode sfp-plus`コマンドを使用して、QSFP ポートの代わりに 4 つの SFP+ ポートをアクティブにすることができます。同様に、 `hardware profile front portmode qsfp`コマンドを使用して、Nexus 3132Q-V をリセットし、4 つの SFP+ ポートの代わりに QSFP ポートを使用するように設定することができます。

* Nexus 3132Q-V の一部のポートが 10 GbE または 40 GbE で動作するように設定されていることを確認してください。
+
最初の 6 つのポートを 4x10 GbE モードに分割するには、 `interface breakout module 1 port 1-6 map 10g-4x`コマンドを使用します。同様に、ブレークアウト構成から最初の 6 つの QSFP+ ポートを再グループ化するには、 `no interface breakout module 1 port 1-6 map 10g-4x`コマンドを使用します。

* 10 GbE および 40 GbE ポートの数は、link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® クラスタ ネットワークスイッチリファレンス設定ファイルのダウンロード"^] で入手可能な参照構成ファイル（RCF）で定義されています。


.開始する前に
* 設定は正しく行われ、正常に機能しています。
* ONTAP 9.4以降を実行しているノード。
* すべてのクラスタポートが `up`状態です。
* Cisco Nexus 3132Q-V クラスタスイッチがサポートされています。
* 既存のクラスタネットワーク構成は以下のとおりです。
+
** Nexus 3132クラスタインフラストラクチャは、冗長構成となっており、両方のスイッチで完全に機能します。
** お使いのスイッチに最新のRCFおよびNX-OSバージョンがインストールされています。
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^]には、この手順でサポートされている ONTAP および NX-OS のバージョンに関する情報が記載されています。

** 両方のスイッチに管理接続機能があります。
** 両方のスイッチへのコンソールアクセス。
** すべてのクラスタ論理インターフェイス（LIF）は、移行されることなく `up`状態にあります。
** スイッチの初期カスタマイズ。
** すべてのISLポートが有効化され、ケーブル接続済みです。




さらに、ノードからNexus 3132Q-Vクラスタスイッチへの10GbEおよび40GbE接続に関する計画、移行、および必要なドキュメントの確認を行う必要があります。

.使用されている例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* Nexus 3132Q-V クラスタスイッチ、C1 および C2。
* ノードはn1とn2です。


[NOTE]
====
この手順の例では、2つのノードを使用し、それぞれが2つの40 GbEクラスタ インターコネクトポート *e4a* と *e4e* を使用します。link:https://hwu.netapp.com/["Hardware Universe"^]には、お使いのプラットフォームのクラスタポートに関する詳細情報が記載されています。

====
この手順は、以下のシナリオを対象としています：

* *n1_clus1* は、ノード *n1* のクラスタスイッチ C1 に接続される最初のクラスタ論理インターフェイス （LIF） です。
* *n1_clus2* は、ノード *n1* のクラスタスイッチ C2 に接続される最初のクラスタ LIF です。
* *n2_clus1* は、ノード *n2* のクラスタスイッチ C1 に接続される最初のクラスタ LIF です。
* *n2_clus2* は、ノード *n2* のクラスタスイッチ C2 に接続される 2 番目のクラスタ LIF です。
* 10 GbE および 40 GbE ポートの数は、link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® クラスタ ネットワークスイッチリファレンス設定ファイルのダウンロード"^] で入手可能な参照構成ファイル（RCF）で定義されています。


[NOTE]
====
この手順では、ONTAPコマンドとCisco Nexus 3000シリーズ スイッチ コマンドの両方を使用する必要があります。特に明記されていないかぎり、ONTAPコマンドを使用します。

====
* クラスタは、2つのノードが接続され、スイッチレスの2ノードクラスタ構成で動作する状態で開始されます。
* 最初のクラスタポートがC1に移動されました。
* 2番目のクラスタポートはC2に移動されます。
* 2ノード構成のスイッチレスクラスタオプションは無効になっています。


.次の手順
移行要件を確認したら、link:migrate-switchless-prepare-to-migrate.html["スイッチの移行準備"]。
