---
permalink: switch-cisco-3132q-v/setup-switch.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: 必要な設定情報とドキュメントをまだ入手していない場合は、クラスタおよび管理ネットワークスイッチをセットアップする前に、その情報を収集する必要があります。 
---
= Cisco Nexus 3132Q-Vスイッチを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3132Q-Vスイッチを設定するには、この手順 に従います。

.必要なもの
* インストールサイトでHTTP、FTP、またはTFTPサーバにアクセスし、該当するNX-OSおよびリファレンス構成ファイル（RCF）リリースをダウンロードします。
* 必要なネットワークスイッチのドキュメント、コントローラのドキュメント、およびONTAP のドキュメント詳細については、を参照してください link:required-documentation-3132q.html["必要なドキュメント"]。
* 該当するライセンス、ネットワークおよび設定情報、ケーブル。
* 記入済みのケーブル接続ワークシートを参照してください link:setup_worksheet_3132q.html["Cisco Nexus 3132Q-Vケーブル接続ワークシートの記入"]。
* 該当するネットアップクラスタネットワークと管理ネットワークのRCFは、NetApp Support Site からダウンロードできます http://mysupport.netapp.com/["mysupport.netapp.com"^] 受信したスイッチの場合。すべての Cisco クラスタネットワークスイッチおよび管理ネットワークスイッチは、シスコの工場出荷時のデフォルト設定で出荷されます。これらのスイッチには、NX-OSソフトウェアの最新バージョンもありますが、RCFはロードされていません。


.手順
. クラスタネットワークと管理ネットワークのスイッチとコントローラをラックに設置します。
+
[cols="1,2"]
|===
| 設置対象 | 作業 


 a| 
ネットアップシステムキャビネット内の Cisco Nexus 3132Q-V
 a| 
スイッチをネットアップキャビネットに設置する手順については、 NetApp cabinet Guide の Installing a Cisco Nexus 3132Q-V cluster switch and pass-through panel in a NetApp cabinet を参照してください。



 a| 
Telco ラック内の機器
 a| 
スイッチのハードウェア設置ガイド、およびネットアップのセットアップガイドに記載されている手順を参照してください。

|===
. の説明に従って、記入済みのケーブル接続ワークシートを使用して、クラスタネットワークスイッチと管理ネットワークスイッチをコントローラにケーブル接続します link:setup_worksheet_3132q.html["Cisco Nexus 3132Q-Vケーブル接続ワークシートの記入"]。
. クラスタネットワークと管理ネットワークのスイッチとコントローラの電源をオンにします。
. クラスタネットワークスイッチの初期設定を実行する。
+
スイッチの初回ブート時に、次の初期セットアップに関する質問に適切な回答を入力します。サイトのセキュリティポリシーでは、有効にする応答とサービスを定義しています。

+
[cols="1,2"]
|===
| プロンプト | 応答 


 a| 
自動プロビジョニングを中止して通常のセットアップを続行しますか？（はい / いいえ）
 a| 
* yes * と応答します。デフォルトは no です



 a| 
セキュアなパスワード標準を適用しますか？（はい / いいえ）
 a| 
* yes * と応答します。デフォルトは yes です。



 a| 
admin のパスワードを入力します。
 a| 
デフォルトのパスワードは「 admin 」です。新しい強力なパスワードを作成する必要があります。脆弱なパスワードは拒否される可能性があります。



 a| 
基本設定ダイアログを開きますか？（はい / いいえ）
 a| 
スイッチの初期設定時に * yes * と応答します。



 a| 
別のログインアカウントを作成しますか？（はい / いいえ）
 a| 
回答は、代替管理者に関するサイトのポリシーに依存します。デフォルトは * no * です。



 a| 
読み取り専用の SNMP コミュニティストリングを設定しますか？（はい / いいえ）
 a| 
* no * と応答します。デフォルトは no です



 a| 
読み取り / 書き込み SNMP コミュニティストリングを設定しますか？（はい / いいえ）
 a| 
* no * と応答します。デフォルトは no です



 a| 
スイッチ名を入力します。
 a| 
スイッチ名は 63 文字までの英数字に制限されます。



 a| 
アウトオブバンド（ mgmt0 ）管理構成で続行しますか。（はい / いいえ）
 a| 
そのプロンプトで * yes * （デフォルト）と応答します。mgmt0 IPv4 address: プロンプトで、 IP アドレス ip_address を入力します



 a| 
default-gateway を設定？（はい / いいえ）
 a| 
* yes * と応答します。default-gateway: プロンプトの IPv4 アドレスに、 default_gateway と入力します。



 a| 
IP の詳細オプションを設定しますか？（はい / いいえ）
 a| 
* no * と応答します。デフォルトは no です



 a| 
Telnet サービスを有効にしますか？（はい / いいえ）
 a| 
* no * と応答します。デフォルトは no です



 a| 
SSH サービスを有効にしたか？（はい / いいえ）
 a| 
* yes * と応答します。デフォルトは yes です。


NOTE: ログ収集機能にクラスタスイッチヘルスモニタ（ CSHM ）を使用する場合は、 SSH が推奨されます。セキュリティを強化するには、 SSHv2 も推奨されます。



 a| 
生成する SSH キーのタイプを入力します（ DSA/RSA/rsa1 ）。
 a| 
デフォルトは * rsa* です。



 a| 
キービット数（ 1024~2048 ）を入力します。
 a| 
1024～2048のキービットを入力します。



 a| 
NTP サーバを設定？（はい / いいえ）
 a| 
* no * と応答します。デフォルトは no です



 a| 
デフォルトのインターフェイスレイヤ（ L3/L2 ）を設定します。
 a| 
* L2 * と応答します。デフォルトは L2 です。



 a| 
デフォルトのスイッチポートインターフェイスステート（ shut / noshut ）を設定します。
 a| 
noshut * と応答します。デフォルトは noshut です。



 a| 
CoPP システムプロファイルを設定する（ strict/moderm/lenenter/dense ）：
 a| 
* strict * と応答します。デフォルトは strict です。



 a| 
設定を編集しますか？（はい / いいえ）
 a| 
この時点で新しい設定が表示されます。入力した設定を確認し、必要な変更を行います。設定に問題がなければ、プロンプトで「 * no * 」と応答します。設定を編集する場合は、 * yes * と応答します。



 a| 
この設定を使用して保存しますか？（はい / いいえ）
 a| 
* yes * と応答して、設定を保存します。これにより、キックスタートイメージとシステムイメージが自動的に更新されます。


NOTE: この段階で設定を保存しないと、次回スイッチをリブートしたときに変更が有効になりません。

|===
. セットアップの最後に表示される画面で選択した設定を確認し、設定を保存します。
. クラスタネットワークスイッチのバージョンを確認し、必要に応じてネットアップ対応バージョンのソフトウェアをスイッチにダウンロードします。
+
ネットアップ対応バージョンのサポートソフトウェアをダウンロードする場合は、 _NetApp Cluster Network Switch Reference Configuration File_ もダウンロードし、手順 5 で保存した構成とマージする必要があります。ファイルと手順は、からダウンロードできます https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco イーサネットスイッチ"^] ページ

. ネットワークスイッチのソフトウェアバージョンを確認し、必要に応じてネットアップ対応バージョンのソフトウェアをスイッチにダウンロードします。独自のスイッチがある場合は、を参照してください https://cisco.com["シスコサイト"^]。
+
ネットアップ対応バージョンのサポートソフトウェアをダウンロードする場合は、 _NetApp Management Network Switch Reference Configuration File_ もダウンロードし、手順 5 で保存した構成とマージする必要があります。ファイルと手順は、からダウンロードできます https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco イーサネットスイッチ"^] ページ



.次の手順
link:prepare-install-cisco-nexus-3132q.html["NX-OSおよびRCFのインストールを準備します"]。
