---
permalink: switch-cisco-3132q-v/switch-requirements.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3132q-v cluster switches 
summary: Cisco Nexus 3132Q-V クラスタ スイッチを交換する場合は、特定の構成情報、ポート接続、およびケーブル接続の要件に注意する必要があります。 
---
= Cisco Nexus 3132Q-V クラスタ スイッチの交換要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ スイッチを交換するときは、構成要件、ポート接続、およびケーブル接続要件を理解していることを確認してください。



== Cisco Nexus 3132Q-V の要件

* Cisco Nexus 3132Q-V クラスタ スイッチがサポートされています。
* 10 GbEおよび40 GbEポートの数は、次のURLで入手可能なリファレンス構成ファイル（RCF）で定義されています。link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® クラスタ ネットワーク スイッチ リファレンス コンフィギュレーション ファイルのダウンロード"^] 。
* クラスタ スイッチは、スイッチ間リンク (ISL) ポート e1/31-32 を使用します。
* そのlink:https://hwu.netapp.com["Hardware Universe"^]Nexus 3132Q-V スイッチへのサポートされているケーブル接続に関する情報が含まれています。
+
** 10 GbE クラスター接続を持つノードには、ブレークアウト ファイバー ケーブル付きの QSFP 光モジュール、または QSFP から SFP+ への銅ブレークアウト ケーブルが必要です。
** 40 GbE クラスター接続を持つノードには、ファイバー ケーブルまたは QSFP/QSFP28 銅線直接接続ケーブルを備えたサポートされている QSFP/QSFP28 光モジュールが必要です。
** クラスター スイッチでは、適切な ISL ケーブル (2 本の QSFP28 ファイバー ケーブルまたは銅線直接接続ケーブル) が使用されます。


* Nexus 3132Q-V では、QSFP ポートを 40 Gb イーサネット モードまたは 4x10 Gb イーサネット モードのいずれかで動作させることができます。
+
デフォルトでは、40 Gb イーサネット モードには 32 個のポートがあります。これらの 40 Gb イーサネット ポートは、2 タプルの命名規則に従って番号が付けられます。たとえば、2 番目の 40 Gb イーサネット ポートの番号は 1/2 になります。  40 Gb イーサネットから 10 Gb イーサネットに構成を変更するプロセスは _breakout_ と呼ばれ、10 Gb イーサネットから 40 Gb イーサネットに構成を変更するプロセスは _breakin_ と呼ばれます。 40 Gb イーサネット ポートを 10 Gb イーサネット ポートに分割すると、結果のポートは 3 タプルの命名規則を使用して番号が付けられます。たとえば、2 番目の 40 Gb イーサネット ポートのブレークアウト ポートには、1/2/1、1/2/2、1/2/3、1/2/4 という番号が付けられます。

* Nexus 3132Q-V の左側には、最初の QSFP ポートに多重化された 4 つの SFP+ ポートのセットがあります。
+
デフォルトでは、RCF は最初の QSFP ポートを使用するように構成されています。

+
Nexus 3132Q-VのQSFPポートの代わりに4つのSFP+ポートをアクティブにするには、 `hardware profile front portmode sfp-plus`指示。同様に、Nexus 3132Q-Vを4つのSFP+ポートの代わりにQSFPポートを使用するようにリセットすることもできます。 `hardware profile front portmode qsfp`指示。

* Nexus 3132Q-V の一部のポートを 10 GbE または 40 GbE で実行するように設定する必要があります。
+
最初の6つのポートを4x10 GbEモードにブレークアウトするには、 `interface breakout module 1 port 1-6 map 10g-4x`指示。同様に、最初の6つのQSFP+ポートをブレイクアウト構成から再グループ化するには、 `no interface breakout module 1 port 1-6 map 10g-4x`指示。

* ノードから Nexus 3132Q-V クラスタ スイッチへの 10 GbE および 40 GbE 接続の計画と移行が完了し、必要なドキュメントを読んでいる必要があります。
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^]この手順でサポートされているONTAPおよび NX-OS のバージョンに関する情報が記載されています。





== Cisco Nexus 5596の要件

* 次のクラスタ スイッチがサポートされます。
+
** ネクサス5596
** Nexus 3132Q-V


* 10 GbEおよび40 GbEポートの数は、次のURLで入手可能なリファレンス構成ファイル（RCF）で定義されています。link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® クラスタ ネットワーク スイッチ リファレンス コンフィギュレーション ファイルのダウンロード"^] 。
* クラスタ スイッチは、ノードへの接続に次のポートを使用します。
+
** ポート e1/1-40 (10 GbE): Nexus 5596
** ポート e1/1-30 (40 GbE): Nexus 3132Q-V


* クラスタ スイッチは、次のスイッチ間リンク（ISL）ポートを使用します。
+
** ポート e1/41-48 (10 GbE): Nexus 5596
** ポート e1/31-32 (40 GbE): Nexus 3132Q-V


* そのlink:https://hwu.netapp.com/["Hardware Universe"^]Nexus 3132Q-V スイッチへのサポートされているケーブル接続に関する情報が含まれています。
+
** 10 GbE クラスタ接続を持つノードには、QSFP から SFP+ への光ファイバー ブレークアウト ケーブルまたは QSFP から SFP+ への銅線ブレークアウト ケーブルが必要です。
** 40 GbE クラスター接続を持つノードには、ファイバー ケーブルまたは QSFP/QSFP28 銅線直接接続ケーブルを備えたサポートされている QSFP/QSFP28 光モジュールが必要です。


* クラスタ スイッチは適切な ISL ケーブルを使用します。
+
** 開始: Nexus 5596 から Nexus 5596 (SFP+ から SFP+)
+
*** 8本のSFP+ファイバーまたは銅線直接接続ケーブル


** 暫定: Nexus 5596 から Nexus 3132Q-V (QSFP から 4xSFP+ ブレークアウト)
+
*** 1本のQSFPからSFP+へのファイバーブレイクアウトケーブルまたは銅線ブレイクアウトケーブル


** 最終: Nexus 3132Q-V から Nexus 3132Q-V (QSFP28 から QSFP28)
+
*** 2本のQSFP28光ファイバーまたは銅線直接接続ケーブル




* Nexus 3132Q-V スイッチでは、QSFP/QSFP28 ポートを 40 ギガビット イーサネット モードまたは 4 x10 ギガビット イーサネット モードとして動作させることができます。
+
デフォルトでは、40 ギガビット イーサネット モードには 32 個のポートがあります。これらの 40 ギガビット イーサネット ポートには、2 タプルの命名規則に従って番号が付けられます。たとえば、2 番目の 40 ギガビット イーサネット ポートの番号は 1/2 になります。  40 ギガビット イーサネットから 10 ギガビット イーサネットに構成を変更するプロセスは _ブレイクアウト_ と呼ばれ、10 ギガビット イーサネットから 40 ギガビット イーサネットに構成を変更するプロセスは _ブレイクイン_ と呼ばれます。 40 ギガビット イーサネット ポートを 10 ギガビット イーサネット ポートに分割すると、結果のポートは 3 タプルの命名規則を使用して番号が付けられます。たとえば、2 番目の 40 ギガビット イーサネット ポートのブレークアウト ポートには、1/2/1、1/2/2、1/2/3、1/2/4 という番号が付けられます。

* Nexus 3132Q-V スイッチの左側には、QSFP28 ポートに多重化された 4 つの SFP+ ポートのセットがあります。
+
デフォルトでは、RCF は QSFP28 ポートを使用するように構成されています。

+

NOTE: Nexus 3132Q-VスイッチのQSFPポートの代わりに4つのSFP+ポートをアクティブにするには、 `hardware profile front portmode sfp-plus`指示。同様に、Nexus 3132Q-Vスイッチを4x SFP+ポートの代わりにQSFPポートを使用するようにリセットするには、 `hardware profile front portmode qsfp`指示。

* Nexus 3132Q-Vスイッチの一部のポートを10GbEまたは40GbEで実行するように設定しておく必要があります。
+

NOTE: 最初の6つのポートを4x10 GbEモードにするには、 `interface breakout module 1 port 1-6 map 10g-4x`指示。同様に、最初の6つのQSFP+ポートをブレイクアウト構成から再グループ化するには、 `no interface breakout module 1 port 1-6 map 10g-4x`指示。

* ノードから Nexus 3132Q-V クラスタ スイッチへの 10 GbE および 40 GbE 接続の計画と移行が完了し、必要なドキュメントを読みました。
* この手順でサポートされているONTAPおよびNX-OSのバージョンは次のとおりです。link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^] 。




== NetApp CN1610の要件

* 次のクラスタ スイッチがサポートされます。
+
** NetApp CN1610
** Cisco Nexus 3132Q-V


* クラスター スイッチは次のノード接続をサポートします。
+
** NetApp CN1610: ポート 0/1 ～ 0/12 (10 GbE)
** Cisco Nexus 3132Q-V: ポート e1/1-30 (40 GbE)


* クラスタ スイッチは、次のスイッチ間リンク (ISL) ポートを使用します。
+
** NetApp CN1610: ポート 0/13 ～ 0/16 (10 GbE)
** Cisco Nexus 3132Q-V: ポート e1/31-32 (40 GbE)


* そのlink:https://hwu.netapp.com/["Hardware Universe"^]Nexus 3132Q-V スイッチへのサポートされているケーブル接続に関する情報が含まれています。
+
** 10 GbE クラスタ接続のノードには、QSFP から SFP+ への光ファイバブレークアウトケーブルまたは QSFP から SFP+ への銅線ブレークアウトケーブルが必要です。
** 40 GbE クラスタ接続を備えたノードには、光ファイバーケーブルまたは QSFP/QSFP28 銅線直接接続ケーブルを備えたサポートされている QSFP/QSFP28 光モジュールが必要です。


* 適切な ISL ケーブル接続は次のとおりです。
+
** 開始: CN1610からCN1610 (SFP+からSFP+)の場合、4本のSFP+光ファイバーまたは銅線直接接続ケーブル
** 暫定：CN1610からNexus 3132Q-V（QSFPから4つのSFP+ブレークアウト）の場合、1本のQSFPからSFP+への光ファイバーまたは銅ブレークアウトケーブル
** 最終：Nexus 3132Q-VからNexus 3132Q-V（QSFP28からQSFP28）の場合、2本のQSFP28光ファイバーまたは銅線直接接続ケーブル


* NetApp Twinax ケーブルは、 Cisco Nexus 3132Q-V スイッチと互換性がありません。
+
現在の CN1610 構成でクラスタ ノードとスイッチ間の接続または ISL 接続にNetApp Twinax ケーブルを使用しており、環境内で Twinax を引き続き使用する場合は、 Cisco Twinax ケーブルを入手する必要があります。あるいは、ISL 接続とクラスター ノードとスイッチ間の接続の両方に光ファイバー ケーブルを使用することもできます。

* Nexus 3132Q-V スイッチでは、QSFP/QSFP28 ポートを 40 Gb イーサネット モードまたは 4x 10 Gb イーサネット モードとして動作させることができます。
+
デフォルトでは、40 Gb イーサネット モードには 32 個のポートがあります。これらの 40 Gb イーサネット ポートは、2 タプルの命名規則に従って番号が付けられます。たとえば、2 番目の 40 Gb イーサネット ポートの番号は 1/2 になります。  40 Gb イーサネットから 10 Gb イーサネットに構成を変更するプロセスは _breakout_ と呼ばれ、10 Gb イーサネットから 40 Gb イーサネットに構成を変更するプロセスは _breakin_ と呼ばれます。 40 Gb イーサネット ポートを 10 Gb イーサネット ポートに分割すると、結果のポートは 3 タプルの命名規則を使用して番号が付けられます。たとえば、2 番目の 40 Gb イーサネット ポートのブレークアウト ポートには、1/2/1、1/2/2、1/2/3、1/2/4 という番号が付けられます。

* Nexus 3132Q-V スイッチの左側には、最初の QSFP ポートに多重化された 4 つの SFP+ ポートのセットがあります。
+
デフォルトでは、リファレンス構成ファイル (RCF) は最初の QSFP ポートを使用するように構成されています。

+
Nexus 3132Q-VスイッチのQSFPポートの代わりに4つのSFP+ポートをアクティブにするには、 `hardware profile front portmode sfp-plus`指示。同様に、Nexus 3132Q-Vスイッチを4つのSFP+ポートの代わりにQSFPポートを使用するようにリセットすることもできます。 `hardware profile front portmode qsfp`指示。

+

NOTE: 最初の 4 つの SFP+ ポートを使用すると、最初の 40GbE QSFP ポートが無効になります。

* Nexus 3132Q-V スイッチの一部のポートを 10 GbE または 40 GbE で実行するように設定する必要があります。
+
最初の6つのポートを4x10 GbEモードにするには、 `interface breakout module 1 port 1-6 map 10g-4x`指示。同様に、最初の6つのQSFP+ポートを_breakout_構成から再グループ化するには、 `no interface breakout module 1 port 1-6 map 10g-4x`指示。

* ノードから Nexus 3132Q-V クラスタ スイッチへの 10 GbE および 40 GbE 接続の計画と移行が完了し、必要なドキュメントを読んでいる必要があります。
* この手順でサポートされているONTAPおよびNX-OSのバージョンは、link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Ciscoイーサネット スイッチ"^] 。
* この手順でサポートされているONTAPおよびFASTPATHのバージョンは、link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601およびCN1610スイッチ"^] 。

