---
permalink: switch-cisco-3132q-v/switch-requirements.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3132q-v cluster switches 
summary: Cisco Nexus 3132Q-V クラスタスイッチを交換する場合は、特定の設定情報、ポート接続、およびケーブル接続要件に注意する必要があります。 
---
= Cisco Nexus 3132Q-Vクラスタスイッチの交換に際しての要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタスイッチを交換するときは、構成要件、ポート接続、およびケーブル接続要件を理解しておく必要があります。



== Cisco Nexus 3132Q-Vの要件

* Cisco Nexus 3132Q-V クラスタスイッチがサポートされています。
* 10GbEポートと40GbEポートの数は、ページで入手できるリファレンス構成ファイル（RCF）で定義しlink:https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® Cluster Network Switch Reference Configuration File Download （ Cisco ® クラスタネットワークスイッチリファレンス構成ファイルのダウンロード"^]ます。
* クラスタスイッチは、 Inter-Switch Link （ ISL ；スイッチ間リンク）ポート e1/31~32 を使用します。
* 。 link:https://hwu.netapp.com["Hardware Universe"^] Nexus 3132Q-V スイッチでサポートされているケーブル接続に関する情報が含まれています。
+
** 10GbE クラスタ接続のノードには、ブレークアウト光ケーブルを備えた QSFP 光モジュールまたは QSFP-SFP+ 銅線ブレークアウトケーブルが必要です。
** 40GbEクラスタ接続を使用するノードには、ファイバケーブルまたはQSFP / QSFP28銅線直接接続ケーブルを備えた、サポートされているQSFP / QSFP28光モジュールが必要です。
** クラスタスイッチでは、適切な ISL ケーブルを使用します。 QSFP28 ファイバケーブルまたは銅線直接接続ケーブル × 2


* Nexus 3132Q-Vでは、QSFPポートを40 Gbイーサネットモードまたは4×10 Gbイーサネットモードとして動作できます。
+
デフォルトでは、40 Gbイーサネットモードには32個のポートがあります。これらの 40 Gb イーサネットポートには、 2 タプルの命名規則で番号が付けられます。たとえば、 2 番目の 40 Gb イーサネットポートには、 1/2 という番号が付けられます。構成を 40 Gb イーサネットから 10 Gb イーサネットに変更するプロセスは _ ブレークアウト _ と呼ばれ、構成を 10 Gb イーサネットから 40 Gb イーサネットに変更するプロセスは _ ブレークイン _ と呼ばれます。40Gbイーサネットポートを10Gbイーサネットポートに分割すると、作成されたポートに3タプルの命名規則を使用して番号が付けられます。たとえば、 2 番目の 40 Gb イーサネットポートのブレークアウトポートには、 1/2/1 、 1/2/2 、 1/2/3 、および 1/2/4 の番号が付けられます。

* Nexus 3132Q-V の左側には、 4 つの SFP+ ポートが 1 つ目の QSFP ポートに多重化されたセットがあります。
+
デフォルトでは、 RCF は最初の QSFP ポートを使用するように構成されています。

+
Nexus 3132Q-V の QSFP ポートの代わりに 4 つの SFP+ ポートをアクティブにするには、「 hardware profile front portmode sf-plus 」コマンドを使用します。同様に、「 hardware profile front portmode QSFP 」コマンドを使用すると、 Nexus 3132Q-V をリセットして、 4 つの SFP+ ポートの代わりに QSFP ポートを使用できます。

* Nexus 3132Q-Vの一部のポートを10GbEまたは40GbEで実行するように設定しておく必要があります。
+
最初の 6 つのポートを 4x10 GbE モードに分割するには、「 interface breakout module 1 port 1-6 map 10g-4x 」コマンドを使用します。同様に、 no interface breakout module 1 port 1-6 map 10g-4x コマンドを使用して、ブレークアウト構成から最初の 6 つの QSFP+ ポートをグループ化し直すことができます。

* ノードからNexus 3132Q-Vクラスタスイッチへの10GbEおよび40GbE接続について、計画、移行を完了し、必要なドキュメントを読んでおく必要があります。
+
。 link:http://mysupport.netapp.com/NOW/download/software/cm_switches/["Cisco イーサネットスイッチ"^] この手順 でサポートされている ONTAP および NX-OS のバージョンについては、ページを参照してください。





== Cisco Nexus 5596の要件

* 次のクラスタスイッチがサポートされます。
+
** Nexus 5596
** Nexus3132Q-V


* 10GbEポートと40GbEポートの数は、ページで入手できるリファレンス構成ファイル（RCF）で定義し https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® Cluster Network Switch Reference Configuration File Download （ Cisco ® クラスタネットワークスイッチリファレンス構成ファイルのダウンロード"^]ます。
* クラスタスイッチは、ノードへの接続に次のポートを使用します。
+
** ポート e1/1~40 （ 10GbE ）： Nexus 5596
** ポートe1/1~30（40GbE）：Nexus 3132Q-V


* クラスタスイッチは、次のスイッチ間リンク（ ISL ）ポートを使用します。
+
** ポート e1/41~48 （ 10GbE ）： Nexus 5596
** ポートe1/31~32（40GbE）：Nexus 3132Q-V


* 。 link:https://hwu.netapp.com/["Hardware Universe"^] Nexus 3132Q-V スイッチでサポートされているケーブル接続に関する情報が含まれています。
+
** 10GbE クラスタ接続のノードには、 QSFP-SFP+ 光ファイバブレークアウトケーブルまたは QSFP+ 銅線ブレークアウトケーブルが必要です。
** 40GbEクラスタ接続を使用するノードには、ファイバケーブルまたはQSFP / QSFP28銅線直接接続ケーブルを備えた、サポートされているQSFP / QSFP28光モジュールが必要です。


* クラスタスイッチは、適切な ISL ケーブル接続を使用します。
+
** 開始： Nexus 5596 から Nexus 5596 （ SFP+ から SFP+ ）
+
*** SFP+ ファイバケーブルまたは銅線直接接続ケーブル × 8


** 中間： Nexus 5596 から Nexus 3132Q-V （ QSFP から 4xSFP+ へのブレークアウト）
+
*** QSFP / SFP+ ファイバブレークアウトケーブルまたは銅線ブレークアウトケーブル × 1


** 最終： Nexus 3132Q-V から Nexus 3132Q-V （ QSFP28 から QSFP28 ）
+
*** QSFP28 ファイバケーブルまたは銅線直接接続ケーブル × 2




* Nexus 3132Q-Vスイッチでは、QSFP / QSFP28ポートを40ギガビットイーサネットモードまたは4×10ギガビットイーサネットモードのいずれかとして動作できます。
+
デフォルトでは、40ギガビットイーサネットモードには32個のポートがあります。これらの 40 ギガビットイーサネットポートには、 2 タプルの命名規則で番号が付けられます。たとえば、 2 番目の 40 ギガビットイーサネットポートには、 1/2 という番号が付けられます。設定を 40 ギガビットイーサネットから 10 ギガビットイーサネットに変更するプロセスは _ ブレークアウト _ と呼ばれ、設定を 10 ギガビットイーサネットから 40 ギガビットイーサネットに変更するプロセスは _ ブレークイン _ と呼ばれます。40ギガビットイーサネットポートを10ギガビットイーサネットポートに分割すると、作成されたポートに3タプルの命名規則を使用して番号が付けられます。たとえば、 2 番めの 40 ギガビットイーサネットポートのブレークアウトポートには、 1/2/1 、 1/2/2 、 1/2/3 、および 1/2/4 の番号が付けられます。

* Nexus 3132Q-V スイッチの左側には、 4 つの SFP+ ポートがこの QSFP28 ポートに多重化されています。
+
デフォルトでは、 RCF は QSFP28 ポートを使用するように構成されています。

+

NOTE: Nexus 3132Q-V スイッチの QSFP ポートの代わりに 4 個の SFP+ ポートをアクティブにするには、「 hardware profile front portmode sf-plus 」コマンドを使用します。同様に、「 hardware profile front portmode QSFP 」コマンドを使用すると、 Nexus 3132Q-V スイッチをリセットして、 SFP+ ポートを 4 個ではなく QSFP ポートを使用できます。

* Nexus 3132Q-Vスイッチの一部のポートを10GbEまたは40GbEで動作するように設定しておきます。
+

NOTE: 最初の 6 つのポートを 4x10 GbE モードに分割するには、「 interface breakout module 1 port 1-6 map 10g-4x 」コマンドを使用します。同様に、 no interface breakout module 1 port 1-6 map 10g-4x コマンドを使用して、ブレークアウト構成から最初の 6 つの QSFP+ ポートをグループ化し直すことができます。

* ノードからNexus 3132Q-Vクラスタスイッチへの10GbEおよび40GbE接続について、計画、移行を完了し、必要なドキュメントをお読みください。
* この手順 でサポートされている ONTAP と NX-OS のバージョンはにあります link:http://support.netapp.com/NOW/download/software/cm_switches/["Cisco イーサネットスイッチ"^] ページ




== NetApp CN1610の要件

* 次のクラスタスイッチがサポートされます。
+
** NetApp CN1610
** Cisco Nexus 3132Q-V の 2 つのポートを設定します


* クラスタスイッチは、次のノード接続をサポートします。
+
** NetApp CN1610 ：ポート 0/1~0/12 （ 10GbE ）
** Cisco Nexus 3132Q-V：ポートe1/1~30（40GbE）


* クラスタスイッチは、次のスイッチ間リンク（ ISL ）ポートを使用します。
+
** NetApp CN1610 ：ポート 0/13~0/16 （ 10GbE ）
** Cisco Nexus 3132Q-V：ポートe1/31-32（40GbE）


* 。 link:https://hwu.netapp.com/["Hardware Universe"^] Nexus 3132Q-V スイッチでサポートされているケーブル接続に関する情報が含まれています。
+
** 10GbE クラスタ接続のノードには、 QSFP-SFP+ 光ファイバブレークアウトケーブルまたは QSFP+ 銅線ブレークアウトケーブルが必要です
** 40GbEクラスタ接続を使用するノードには、光ファイバケーブルまたはQSFP / QSFP28銅線直接接続ケーブルを備えたサポート対象のQSFP / QSFP28光モジュールが必要です。


* 適切な ISL ケーブル接続は次のとおりです。
+
** 初期： CN1610 から CN1610 （ SFP+ から SFP+ ）の場合は、 SFP+ 光ファイバケーブルまたは銅線直接接続ケーブル 4 本
** 中間： CN1610 から Nexus 3132Q-V （ QSFP から 4 SFP+ ブレークアウト）の場合は、 QSFP から SFP+ 光ファイバまたは銅線ブレークアウトケーブル × 1
** 最終： Nexus 3132Q-V から Nexus 3132Q-V （ QSFP28 から QSFP28 ）の場合は、 QSFP28 光ファイバケーブルまたは銅線直接接続ケーブル 2 本


* NetApp Twinax ケーブルは、 Cisco Nexus 3132Q-V スイッチには対応していません。
+
現在の CN1610 構成で、クラスタノード間の接続または ISL 接続に NetApp Twinax ケーブルを使用しており、ご使用の環境で Twinax を引き続き使用する場合は、 Cisco Twinax ケーブルを使用する必要があります。または、 ISL 接続とクラスタノード / スイッチ間の接続に光ファイバケーブルを使用することもできます。

* Nexus 3132Q-Vスイッチでは、QSFP / QSFP28ポートを40Gbイーサネットモードまたは4x10Gbイーサネットモードとして運用できます。
+
デフォルトでは、40 Gbイーサネットモードには32個のポートがあります。これらの 40 Gb イーサネットポートには、 2 タプルの命名規則で番号が付けられます。たとえば、 2 番目の 40 Gb イーサネットポートには、 1/2 という番号が付けられます。構成を 40 Gb イーサネットから 10 Gb イーサネットに変更するプロセスは _ ブレークアウト _ と呼ばれ、構成を 10 Gb イーサネットから 40 Gb イーサネットに変更するプロセスは _ ブレークイン _ と呼ばれます。40Gbイーサネットポートを10Gbイーサネットポートに分割すると、作成されたポートに3タプルの命名規則を使用して番号が付けられます。たとえば、 2 番目の 40 Gb イーサネットポートのブレークアウトポートには、 1/2/1 、 1/2/2 、 1/2/3 、および 1/2/4 の番号が付けられます。

* Nexus 3132Q-V スイッチの左側には、 4 つの SFP+ ポートが 1 つ目の QSFP ポートに多重化されています。
+
デフォルトでは、 Reference Configuration File （ RCF ；リファレンス構成ファイル）は最初の QSFP ポートを使用するように構成されています。

+
「 hardware profile front portmode sf-plus 」コマンドを使用すると、 Nexus 3132Q-V スイッチの QSFP ポートの代わりに 4 つの SFP+ ポートをアクティブにできます。同様に、「 hardware profile front portmode QSFP 」コマンドを使用すると、 Nexus 3132Q-V スイッチをリセットして、 4 つの SFP+ ポートではなく QSFP ポートを使用できます。

+

NOTE: 最初の 4 つの SFP+ ポートを使用すると、最初の 40GbE QSFP ポートは無効になります。

* Nexus 3132Q-Vスイッチの一部のポートを10GbEまたは40GbEで実行するように設定しておく必要があります。
+
コマンドを使用すると、最初の6つのポートを4x10GbEモードに分割できます `interface breakout module 1 port 1-6 map 10g-4x`。同様に、コマンドを使用して、_breakout_configurationから最初の6つのQSFP+ポートを再グループ化できます `no interface breakout module 1 port 1-6 map 10g-4x`。

* ノードからNexus 3132Q-Vクラスタスイッチへの10GbEおよび40GbE接続について、計画、移行を完了し、必要なドキュメントを読んでおく必要があります。
* この手順 でサポートされている ONTAP と NX-OS のバージョンをに示します link:http://support.netapp.com/NOW/download/software/cm_switches/["Cisco イーサネットスイッチ"^] ページ
* この手順 でサポートされている ONTAP および FastPath のバージョンをに示します link:http://support.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 / CN1610 スイッチ"^] ページ

