---
permalink: switch-cisco-3232c-storage/replace-storage-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus, 3232c storage switch 
summary: 特定の一連のタスクを実行することで、障害のあるCisco Nexus 3232C ストレージ スイッチを中断せずに交換できます。 
---
= Cisco Nexus 3232Cストレージスイッチを交換する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
故障したCisco Nexus 3232C ストレージ スイッチを交換するには、次の手順に従います。これは中断を伴わない手順です。



== 要件の確認

既存のネットワーク構成には、次の特性が必要です。

* Ciscoイーサネット スイッチ ページには、スイッチの最新の RCF および NX-OS バージョンが記載されています。
* 両方のスイッチに管理接続が存在する必要があります。
+
[NOTE]
====
すべてのトラブルシューティング手順が完了していることを確認して、スイッチを交換する必要があるかどうかを確認してください。

====


交換用のCisco Nexus 3232C スイッチには、次の特性が必要です。

* 管理ネットワーク接続が機能している必要があります。
* 交換用スイッチへのコンソール アクセスが適切に行われている必要があります。
* 適切な RCF および NX-OS オペレーティング システム イメージをスイッチにロードする必要があります。
* スイッチの初期カスタマイズが完了している必要があります。




== スイッチを交換する

この手順では、2 番目の Nexus 3232C ストレージ スイッチ s2 を新しい 3232C スイッチ ns2 に置き換えます。2 つのノードは cluster1-01 と cluster1-02 です。



=== ステップ1：交換するスイッチがs2であることを確認する

. このクラスタでAutoSupportが有効になっている場合は、 AutoSupportメッセージを呼び出して自動ケース作成を抑制します。
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

+
[NOTE]
====
AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

====
. ストレージ ノード ポートのヘルス ステータスを確認して、ストレージ スイッチ s1 への接続があることを確認します：
+
`storage port show -port-type ENET`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                     VLAN
Node               Port Type  Mode    (Gb/s) State    Status      ID
------------------ ---- ----- ------- ------ -------- --------- ----
cluster1-01
                   e5a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
cluster1-02
                   e5a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
----
====
. ストレージ スイッチ s1 が使用可能であることを確認します：
+
`network device-discovery show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- ----------------
cluster1-01/cdp
            e5a    s1                        Ethernet1/1       NX3232C
            e4a    cluster1-02                     e4a               AFF-A700
            e4e    cluster1-02                     e4e               AFF-A700
cluster1-01/lldp
            e5a    s1                        Ethernet1/1       -
            e4a    cluster1-02                     e4a               -
            e4e    cluster1-02                     e4e               -
cluster1-02/cdp
            e3a    s1                        Ethernet1/2       NX3232C
            e4a    cluster1-01                     e4a               AFF-A700
            e4e    cluster1-01                     e4e               AFF-A700
cluster1-02/lldp
            e3a    s1                        Ethernet1/2       -
            e4a    cluster1-01                     e4a               -
            e4e    cluster1-01                     e4e               -
.
.
----
====
. 実行 `show lldp neighbors`動作中のスイッチでコマンドを実行して、両方のノードとすべてのシェルフが表示されることを確認します。
+
`show lldp neighbors`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
s1# *show lldp neighbors*
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID               Local Intf      Hold-time  Capability  Port ID
cluster1-01             Eth1/1          121        S           e5a
cluster1-02             Eth1/2          121        S           e5a
SHFGD2008000011         Eth1/5          121        S           e0a
SHFGD2008000011         Eth1/6          120        S           e0a
SHFGD2008000022         Eth1/7          120        S           e0a
SHFGD2008000022         Eth1/8          120        S           e0a
----
====




=== ステップ2: ケーブル配線を構成する

. [[5]]ストレージシステムのシェルフポートを確認します。
+
`storage shelf port show -fields remote-device,remote-port`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*

shelf  id  remote-port  remote-device
-----  --  -----------  -------------
3.20   0   Ethernet1/5  s1
3.20   1   -            -
3.20   2   Ethernet1/6  s1
3.20   3   -            -
3.30   0   Ethernet1/7  s1
3.20   1   -            -
3.30   2   Ethernet1/8  s1
3.20   3   -            -
----
====
. ストレージ スイッチ s2 に接続されているすべてのケーブルを取り外します。
. すべてのケーブルを交換用スイッチ ns2 に再接続します。




=== ステップ3：スイッチns2のすべてのデバイス構成を確認する

. ストレージ ノード ポートのヘルス ステータスを確認します。
+
`storage port show -port-type ENET`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ------------ ---
cluster1-01
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
cluster1-02
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30

.
.
----
====
. 両方のスイッチが使用可能であることを確認します。
+
`network device-discovery show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
cluster1-01/cdp
            e5a    s1                        Ethernet1/1       NX3232C
            e4a    cluster1-02               e4a               AFF-A700
            e4e    cluster1-02               e4e               AFF-A700
            e7b    ns2                       Ethernet1/1       NX3232C
cluster1-01/lldp
            e5a    s1                        Ethernet1/1       -
            e4a    cluster1-02               e4a               -
            e4e    cluster1-02               e4e               -
            e7b    ns2                       Ethernet1/1       -
cluster1-02/cdp
            e5a    s1                        Ethernet1/2       NX3232C
            e4a    cluster1-01               e4a               AFF-A700
            e4e    cluster1-01               e4e               AFF-A700
            e7b    ns2                       Ethernet1/2       NX3232C
cluster1-02/lldp
            e5a    s1                        Ethernet1/2       -
            e4a    cluster1-01               e4a               -
            e4e    cluster1-01               e4e               -
            e7b    ns2                       Ethernet1/2       -
.
.
----
====
. ストレージ システムのシェルフ ポートを確認します。
+
`storage shelf port show -fields remote-device,remote-port`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*
shelf id remote-port remote-device
----- -- ----------- -------------
3.20  0  Ethernet1/5 s1
3.20  1  Ethernet1/5 ns2
3.20  2  Ethernet1/6 s1
3.20  3  Ethernet1/6 ns2
3.30  0  Ethernet1/7 s1
3.20  1  Ethernet1/7 ns2
3.30  2  Ethernet1/8 s1
3.20  3  Ethernet1/8 ns2
.
.
----
====
. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.次の手順
スイッチを交換したら、link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを設定する"]できます。
