---
permalink: switch-netapp-cn1610/install-fastpath-rcf-831.html 
sidebar: sidebar 
keywords: fastpath, software, install, netapp cluster switches, rcfs, ontap 
summary: インストール手順は、 ONTAP 8.3.1 以降を実行しているNetApp CN1601 管理スイッチと CN1610 クラスタ スイッチの両方で同じです。ただし、2 つのモデルには異なるソフトウェアと RCF が必要です。 
---
= ONTAP 8.3.1以降用のFASTPATHソフトウェアとRCFをインストールします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 8.3.1 以降の FASTPATH ソフトウェアと RCF をインストールするには、次の手順に従ってください。

インストール手順は、 ONTAP 8.3.1 以降を実行しているNetApp CN1601 管理スイッチと CN1610 クラスタ スイッチの両方で同じです。ただし、2 つのモデルには異なるソフトウェアと RCF が必要です。



== 要件の確認

.開始する前に
以下のものがあることを確認してください。

* スイッチ構成の現在のバックアップ。
* 完全に機能しているクラスター (ログにエラーがなく、クラスター ネットワーク インターフェイス カード (NIC) に欠陥がなく、同様の問題もありません)。
* クラスター スイッチ上の完全に機能するポート接続。
* すべてのクラスター ポートが設定されました。
* すべてのクラスタ論理インターフェイス (LIF) がセットアップされている (移行されていないこと)。
* 成功した通信パス: ONTAP (権限: 上級) `cluster ping-cluster -node node1`コマンドは以下を示す必要があります `larger than PMTU communication`すべてのパスで成功します。
* サポートされている FASTPATH、RCF、およびONTAPのバージョン。
+
スイッチの互換性表を必ず参照してください。 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601およびCN1610スイッチ"^]サポートされている FASTPATH、RCF、およびONTAPバージョンについては、こちらのページをご覧ください。





== FASTPATHソフトウェアをインストールする

次の手順では、clustered Data ONTAP 8.2 構文を使用します。その結果、クラスタ Vserver、LIF 名、および CLI 出力は、 Data ONTAP 8.3 のものとは異なります。

RCF バージョンと FASTPATH バージョンのコマンド構文間にはコマンド依存関係が存在する場合があります。


NOTE: RCF バージョン 1.2 では、セキュリティ上の懸念から、Telnet のサポートが明示的に無効になっています。 RCF 1.2 のインストール中に接続の問題を回避するには、Secure Shell (SSH) が有効になっていることを確認してください。その https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610 スイッチ管理者ガイド"^]SSH に関する詳細情報は、こちらを参照してください。

.例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 2 つのNetAppスイッチ名は cs1 と cs2 です。
* クラスタ論理インターフェイス (LIF) 名は、node1 の場合は node1_clus1 と node1_clus2、node2 の場合は node2_clus1 と node2_clus2 です。  (クラスターには最大 24 個のノードを含めることができます。)
* ストレージ仮想マシン (SVM) の名前は Cluster です。
* その `cluster1::*>`プロンプトはクラスターの名前を示します。
* 各ノードのクラスタ ポートの名前はe0aおよびe0bです。
+
https://hwu.netapp.com/["Hardware Universe"^]プラットフォームでサポートされている実際のクラスター ポートに関する詳細情報は、こちらをご覧ください。

* サポートされているスイッチ間リンク (ISL) は、ポート 0/13 ～ 0/16 です。
* サポートされるノード接続はポート 0/1 ～ 0/12 です。




=== ステップ1: クラスターの移行

. クラスター上のネットワーク ポートに関する情報を表示します。
+
`network port show -_ipspace cluster_`

+
.例を表示
[%collapsible]
====
次の例は、コマンドからの出力のタイプを示しています。

[listing]
----
cluster1::> network port show -ipspace cluster
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. クラスタ上の LIF に関する情報を表示します。
+
`network interface show -_role cluster_`

+
.例を表示
[%collapsible]
====
次の例は、クラスター上の論理インターフェイスを示しています。この例では、 `-role`パラメータは、クラスタ ポートに関連付けられている LIF に関する情報を表示します。

[listing]
----
cluster1::> network interface show -role cluster
  (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16    node1         e0a     true
            node1_clus2  up/up    10.254.206.128/16  node1         e0b     true
            node2_clus1  up/up    10.254.48.152/16   node2         e0a     true
            node2_clus2  up/up    10.254.42.74/16    node2         e0b     true
4 entries were displayed.
----
====
. 各ノードで、ノード管理 LIF を使用して、node1 の node1_clus2 を e0a に移行し、node2 の node2_clus2 を e0a に移行します。
+
`network interface migrate`

+
それぞれのクラスタ LIF を所有するコントローラ コンソールでコマンドを入力する必要があります。

+
.例を表示
[%collapsible]
====
[listing]
----
cluster1::> network interface migrate -vserver Cluster -lif node1_clus2 -destination-node node1 -destination-port e0a
cluster1::> network interface migrate -vserver Cluster -lif node2_clus2 -destination-node node2 -destination-port e0a
----
====
+

NOTE: このコマンドでは、クラスターの名前の大文字と小文字が区別され、各ノードでコマンドを実行する必要があります。このコマンドを一般的なクラスタ LIF で実行することはできません。

. 移行が行われたことを確認するには、 `network interface show`ノード上のコマンド。
+
.例を表示
[%collapsible]
====
次の例は、clus2 がノード node1 および node2 のポート e0a に移行したことを示しています。

[listing]
----
cluster1::> **network interface show -role cluster**
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16   node1          e0a     true
            node1_clus2  up/up    10.254.206.128/16 node1          e0a     false
            node2_clus1  up/up    10.254.48.152/16  node2          e0a     true
            node2_clus2  up/up    10.254.42.74/16   node2          e0a     false
4 entries were displayed.
----
====
. 権限レベルを「advanced」に変更し、続行するかどうかを尋ねられたら y を入力します。
+
`set -privilege advanced`

+
advancedのプロンプト（*>）が表示されます。

. 両方のノードでクラスター ポート e0b をシャットダウンします。
+
`network port modify -node _node_name_ -port _port_name_ -up-admin false`

+
それぞれのクラスタ LIF を所有するコントローラ コンソールでコマンドを入力する必要があります。

+
.例を表示
[%collapsible]
====
次の例は、すべてのノードのポート e0b をシャットダウンするコマンドを示しています。

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin false
cluster1::*> network port modify -node node2 -port e0b -up-admin false
----
====
. 両方のノードでポート e0b がシャットダウンされていることを確認します。
+
`network port show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster1::*> network port show -role cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
4 entries were displayed.
----
====
. cs1 の Inter-Switch Link (ISL) ポートをシャットダウンします。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config)#interface 0/13-0/16
(cs1) (Interface 0/13-0/16)#shutdown
(cs1) (Interface 0/13-0/16)#exit
(cs1) (Config)#exit
----
====
. cs2 上の現在のアクティブ イメージをバックアップします。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.5     1.1.0.3            1.1.0.5            1.1.0.5

(cs2) # copy active backup
Copying active to backup
Copy operation successful
----
====




=== ステップ2: FASTPATHソフトウェアとRCFをインストールする

. 実行中の FASTPATH ソフトウェアのバージョンを確認します。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. NetApp CN1610, 1.1.0.5, Linux
                                                2.6.21.7
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.1.0.5
Operating System............................... Linux 2.6.21.7
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893

--More-- or (q)uit


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
. スイッチにイメージ ファイルをダウンロードします。
+
イメージ ファイルをアクティブ イメージにコピーすると、再起動時にそのイメージによって実行中の FASTPATH バージョンが確立されます。以前のイメージはバックアップとして使用できます。

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #copy sftp://root@10.22.201.50//tftpboot/NetApp_CN1610_1.2.0.7.stk active
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /tftpboot/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. 現在のアクティブ ブート イメージ バージョンと次にアクティブなブート イメージ バージョンを確認します。
+
`show bootvar`

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.8     1.1.0.8            1.1.0.8            1.2.0.7
----
====
. 新しいイメージ バージョンと互換性のある RCF をスイッチにインストールします。
+
RCF バージョンがすでに正しい場合は、ISL ポートを起動します。

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #copy tftp://10.22.201.50//CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr

Mode........................................... TFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.


Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y


Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
====
+

NOTE: その `.scr`スクリプトを呼び出す前に、ファイル名の一部として拡張子を設定する必要があります。この拡張機能は、FASTPATH オペレーティング システム用です。

+
スイッチは、スクリプトがスイッチにダウンロードされると自動的にそれを検証します。出力はコンソールに送られます。

. スクリプトがダウンロードされ、指定したファイル名で保存されたことを確認します。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #script list

Configuration Script Name        Size(Bytes)
-------------------------------- -----------
CN1610_CS_RCF_v1.2.scr                  2191

1 configuration script(s) found.
2541 Kbytes free.
----
====
. スクリプトをスイッチに適用します。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.2.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.2.scr' applied.
----
====
. 変更がスイッチに適用されたことを確認し、保存します。
+
`show running-config`

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #show running-config
----
====
. 実行中のコンフィギュレーションを保存して、スイッチを再起動したときにそれがスタートアップ コンフィギュレーションになるようにします。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. スイッチをリブートします。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #reload

The system has unsaved changes.
Would you like to save them now? (y/n) y

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====




=== ステップ3: インストールの検証

. 再度ログインし、スイッチが新しいバージョンの FASTPATH ソフトウェアを実行していることを確認します。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #show version

Switch: 1

System Description............................. NetApp CN1610, 1.2.0.7,Linux
                                                3.8.13-4ce360e8
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.2.0.7
Operating System............................... Linux 3.8.13-4ce360e8
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893
CPLD version................................... 0x5


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
+
再起動が完了したら、ログインしてイメージのバージョンを確認し、実行中の設定を表示し、RCF のバージョン ラベルであるインターフェイス 3/64 の説明を探す必要があります。

. アクティブ スイッチである cs1 の ISL ポートを起動します。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config) #interface 0/13-0/16
(cs1) (Interface 0/13-0/16) #no shutdown
(cs1) (Interface 0/13-0/16) #exit
(cs1) (Config) #exit
----
====
. ISL が動作していることを確認します。
+
`show port-channel 3/1`

+
リンク状態フィールドは以下を示す必要があります `Up`。

+
.例を表示
[%collapsible]
====
[listing]
----
(cs1) #show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  False
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. すべてのノードでクラスター ポート e0b を起動します。
+
`network port modify`

+
それぞれのクラスタ LIF を所有するコントローラ コンソールでコマンドを入力する必要があります。

+
.例を表示
[%collapsible]
====
次の例は、ノード 1 とノード 2 でポート e0b が起動されることを示しています。

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin true
cluster1::*> network port modify -node node2 -port e0b -up-admin true
----
====
. すべてのノードでポート e0b が稼働していることを確認します。
+
`network port show -ipspace cluster`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster1::*> network port show -ipspace cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. LIFがホームになっていることを確認する(`true`) を両方のノードで実行します。
+
`network interface show -_role cluster_`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -role cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.66.82/16   node1         e0a     true
            node1_clus2  up/up    169.254.206.128/16 node1         e0b     true
            node2_clus1  up/up    169.254.48.152/16  node2         e0a     true
            node2_clus2  up/up    169.254.42.74/16   node2         e0b     true
4 entries were displayed.
----
====
. ノード メンバーのステータスを表示します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====
. admin権限レベルに戻ります。
+
`set -privilege admin`

. 前の手順を繰り返して、他のスイッチ cs1 に FASTPATH ソフトウェアと RCF をインストールします。

