---
permalink: switch-netapp-cn1610/install-rcf-file.html 
sidebar: sidebar 
keywords: reference configuration, file ,install, cn1610, switch, install rcf 
summary: '参照構成ファイル (RCF) をインストールする場合は、まずクラスタ LIF をスイッチ cs2 から移行する必要があります。  RCF がインストールされ検証されたら、LIF を元に戻すことができます。' 
---
= CN1610スイッチにリファレンス設定ファイルをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
参照構成ファイル (RCF) をインストールするには、次の手順に従います。

RCF をインストールする前に、まずクラスタ LIF をスイッチ cs2 から移行する必要があります。  RCF がインストールされ検証されたら、LIF を元に戻すことができます。



== 要件の確認

.開始する前に
以下のものがあることを確認してください。

* スイッチ構成の現在のバックアップ。
* 完全に機能しているクラスター (ログにエラーがなく、クラスター ネットワーク インターフェイス カード (NIC) に欠陥がなく、同様の問題もありません)。
* クラスター スイッチ上の完全に機能するポート接続。
* すべてのクラスター ポートが設定されました。
* すべてのクラスタ論理インターフェイス (LIF) が設定されました。
* 成功した通信パス: ONTAP (権限: 上級) `cluster ping-cluster -node node1`コマンドは以下を示す必要があります `larger than PMTU communication`すべてのパスで成功します。
* サポートされている RCF およびONTAPのバージョン。
+
スイッチの互換性表を必ず参照してください。 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601およびCN1610スイッチ"^]サポートされている RCF およびONTAPバージョンについては、ページをご覧ください。





== RCFのインストール

次の手順では、clustered Data ONTAP 8.2 構文を使用します。その結果、クラスタ Vserver、LIF 名、および CLI 出力は、 Data ONTAP 8.3 のものとは異なります。

RCF バージョンと FASTPATH バージョンのコマンド構文間にはコマンド依存関係が存在する場合があります。


NOTE: RCF バージョン 1.2 では、セキュリティ上の懸念から、Telnet のサポートが明示的に無効になっています。 RCF 1.2 のインストール中に接続の問題を回避するには、Secure Shell (SSH) が有効になっていることを確認してください。その https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610 スイッチ管理者ガイド"^]SSH に関する詳細情報は、こちらを参照してください。

.例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 2 つのNetAppスイッチは cs1 と cs2 です。
* 2 つのクラスター LIF は clus1 と clus2 です。
* Vserver は vs1 と vs2 です。
* その `cluster::*>`プロンプトはクラスターの名前を示します。
* 各ノードのクラスタ ポートの名前はe1aおよびe2aです。
+
https://hwu.netapp.com/["Hardware Universe"^]プラットフォームでサポートされている実際のクラスター ポートに関する詳細情報は、こちらをご覧ください。

* サポートされているスイッチ間リンク (ISL) は、ポート 0/13 ～ 0/16 です。
* サポートされるノード接続はポート 0/1 ～ 0/12 です。
* サポートされている FASTPATH、RCF、およびONTAPのバージョン。
+
スイッチの互換性表を必ず参照してください。 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601およびCN1610スイッチ"^]サポートされている FASTPATH、RCF、およびONTAPバージョンについては、こちらのページをご覧ください。





=== ステップ1: クラスターの移行

. 現在のスイッチ構成情報を保存します。
+
`write memory`

+
.例を表示
[%collapsible]
====
次の例は、現在のスイッチ構成がスタートアップ構成に保存されていることを示しています。(`startup-config` ) スイッチ cs2 上のファイル:

[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 各ノードのコンソールで、clus2 をポート e1a に移行します。
+
`network interface migrate`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -source-node node1 -destnode node1 -dest-port e1a

cluster::*> network interface migrate -vserver vs2 -lif clus2 -source-node node2 -destnode node2 -dest-port e1a
----
====
. 各ノードのコンソールで、移行が行われたことを確認します。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
次の例は、clus2 が両方のノードのポート e1a に移行したことを示しています。

[listing]
----
cluster::*> network port show -role cluster
         clus1      up/up      10.10.10.1/16   node2    e1a     true
         clus2      up/up      10.10.10.2/16   node2    e1a     false
----
====
. 両方のノードでポート e2a をシャットダウンします。
+
`network port modify`

+
.例を表示
[%collapsible]
====
次の例では、両方のノードでポート e2a がシャットダウンされています。

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 両方のノードでポート e2a がシャットダウンされていることを確認します。
+
`network port show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                  Auto-Negot  Duplex      Speed (Mbps)
Node   Port   Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ------ -------- ---- ----- ----------- ----------  -----------
node1
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
node2
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
----
====
. アクティブなNetAppスイッチである cs1 の ISL ポートをシャットダウンします。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (interface 0/13-0/16) # shutdown
(cs1) (interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====




=== ステップ2: RCFをインストールする

. RCF をスイッチにコピーします。
+

NOTE: 設定する必要があります `.scr`スクリプトを呼び出す前に、ファイル名の一部として拡張子を追加します。この拡張機能は、FASTPATH オペレーティング システムの拡張機能です。

+
スクリプトがスイッチにダウンロードされると、スイッチはスクリプトを自動的に検証し、出力はコンソールに送信されます。

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.10.0.1/CN1610_CS_RCF_v1.1.txt nvram:script CN1610_CS_RCF_v1.1.scr

[the script is now displayed line by line]
Configuration script validated.
File transfer operation completed successfully.
----
====
. スクリプトがダウンロードされ、指定したファイル名で保存されたことを確認します。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # script list
Configuration Script Name        Size(Bytes)
-------------------------------- -----------
running-config.scr               6960
CN1610_CS_RCF_v1.1.scr           2199

2 configuration script(s) found.
6038 Kbytes free.
----
====
. スクリプトを検証します。
+

NOTE: スクリプトはダウンロード中に検証され、各行が有効なスイッチ コマンド ラインであるかどうかが確認されます。

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # script validate CN1610_CS_RCF_v1.1.scr
[the script is now displayed line by line]
Configuration script 'CN1610_CS_RCF_v1.1.scr' validated.
----
====
. スクリプトをスイッチに適用します。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.1.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.1.scr' applied.
----
====
. 変更がスイッチに実装されていることを確認します。
+
[listing]
----
(cs2) # show running-config
----
+
この例では、 `running-config`スイッチ上のファイル。設定したパラメータが期待どおりであることを確認するには、ファイルを RCF と比較する必要があります。

. 変更を保存します。
. 設定する `running-config`ファイルを標準のものにします。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.
----
====
. スイッチを再起動して、 `running-config`ファイルは正しいです。
+
再起動が完了したら、ログインして、 `running-config`ファイルを開き、RCF のバージョン ラベルであるインターフェイス 3/64 の説明を探します。

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y


Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. アクティブ スイッチである cs1 の ISL ポートを起動します。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config)# interface 0/13-0/16
(cs1) (Interface 0/13-0/16)# no shutdown
(cs1) (Interface 0/13-0/16)# exit
(cs1) (config)# exit
----
====
. ISL が動作していることを確認します。
+
`show port-channel 3/1`

+
リンク状態フィールドは以下を示す必要があります `Up`。

+
.例を表示
[%collapsible]
====
[listing]
----

(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 両方のノードでクラスター ポート e2a を起動します。
+
`network port modify`

+
.例を表示
[%collapsible]
====
次の例は、ノード 1 とノード 2 でポート e2a が起動されることを示しています。

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====




=== ステップ3: インストールの検証

. 両方のノードでポート e2a が稼働していることを確認します。
+
`network port show -_role cluster_`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- ----  ----------- ----------  ------------
node1
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
----
====
. 両方のノードで、ポート e2a に関連付けられている clus2 を元に戻します。
+
`network interface revert`

+
ONTAPのバージョンによっては、LIF が自動的に元に戻る場合があります。

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
. LIFがホームになっていることを確認する(`true`) を両方のノードで実行します。
+
`network interface show -_role cluster_`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

        Logical    Status     Network        Current  Current Is
Vserver Interface  Admin/Oper Address/Mask   Node     Port    Home
------- ---------- ---------- -------------- -------- ------- ----
vs1
        clus1      up/up      10.10.10.1/24  node1    e1a     true
        clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
        clus1      up/up      10.10.10.1/24  node2    e1a     true
        clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. ノード メンバーのステータスを表示します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node           Health  Eligibility
-------------- ------- ------------
node1
               true    true
node2
               true    true
----
====
. コピー `running-config`ファイルに `startup-config`ソフトウェアのバージョンとスイッチの設定に満足したら、ファイルを保存します。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 前の手順を繰り返して、他のスイッチ cs1 に RCF をインストールします。


.次の手順
link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを構成する"]
