---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: ネットアップのスイッチに FastPath ソフトウェアをインストールするときは、 2 つ目のスイッチ cs2 でアップグレードを開始する必要があります。 
---
= FastPath ソフトウェアをインストールします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットアップのスイッチに FastPath ソフトウェアをインストールするときは、 2 番目のスイッチである _CS2_へ のアップグレードを開始する必要があります。



== 要件を確認

.作業を開始する前に
次のものがあることを確認します。

* スイッチ設定の現在のバックアップ。
* クラスタが完全に機能している（ログにエラーは記録されず、クラスタネットワークインターフェイスカード（NIC）の欠陥や同様の問題はない）。
* クラスタスイッチ上の完全に機能するポート接続。
* すべてのクラスタポートが設定されています。
* すべてのクラスタ論理インターフェイス（LIF）がセットアップされている（移行されていない）。
* 通信パスが成功した場合：ONTAP （権限：advanced） `cluster ping-cluster -node node1` コマンドは、を示す必要があります `larger than PMTU communication` はすべてのパスで成功しています。
* FastPathおよびONTAP のサポートされているバージョン。
+
のスイッチ互換性の表を参照してください http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 / CN1610 スイッチ"^] サポートされているFastPathおよびONTAP のバージョンについては、ページを参照してください。





== FastPathをインストールします

次の手順 では、clustered Data ONTAP 8.2の構文を使用します。そのため、クラスタSVM、LIF名、CLIの出力がData ONTAP 8.3の出力と異なります。

RCF バージョンと FastPath バージョンでは、コマンド構文間にコマンドの依存関係が存在する場合があります。

.例について
この手順の例では、スイッチとノードで次の命名法を使用しています。

* 2 つのネットアップスイッチは cs1 と cs2 です。
* 2 つのクラスタ LIF は clus1 と clus2 です。
* SVM は vs1 および vs2 です。
* 'cluster::*>' プロンプトは ' クラスタの名前を示します
* 各ノードのクラスタポートには、 e1a および e2a という名前が付けられます。
+
https://hwu.netapp.com/["Hardware Universe"^] 使用しているプラットフォームでサポートされている実際のクラスタポートに関する詳細情報が表示されます。

* サポートされているスイッチ間リンク（ISL）は、ポート0/13~0/16です。
* サポートされるノード接続はポート0/1~0/12です。




=== 手順1：クラスタを移行する

. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。
+
'system node AutoSupport invoke -node * -type all -message MAINT=xh`

+
_x_ は、メンテナンス時間の長さ（時間単位）です。

+

NOTE: AutoSupport メッセージはテクニカルサポートにこのメンテナンスタスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

. スイッチに admin としてログインします。デフォルトではパスワードはありません。'(CS2)#' プロンプトで 'enable` コマンドを入力しますここでも、デフォルトではパスワードはありません。これにより、ネットワークインターフェイスを設定できる特権 EXEC モードにアクセスできます。
+
.例を示します
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. 各ノードのコンソールで、clus2をポートe1aに移行します。
+
「ネットワーク・インターフェイス移行」

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. 各ノードのコンソールで、移行が実行されたことを確認します。
+
「 network interface show 」を参照してください

+
次の例では、 clus2 が両方のノードのポート e1a に移行されています。

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




=== 手順2：FastPathソフトウェアをインストールします

. 両方のノードで、クラスタポートe2aをシャットダウンします。
+
「 network port modify 」を参照してください

+
.例を示します
[%collapsible]
====
次の例は、両方のノードでポート e2a がシャットダウンされていることを示しています。

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 両方のノードでポートe2aがシャットダウンされていることを確認します。
+
「 network port show 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. アクティブなネットアップスイッチ cs1 のスイッチ間リンク（ ISL ）ポートをシャットダウンします。
+
.例を示します
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. cs2 で現在アクティブなイメージをバックアップします。
+
.例を示します
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. スイッチにイメージファイルをダウンロードします。
+
イメージファイルをアクティブイメージにコピーすると、リブート時にそのイメージによって FastPath バージョンが確立されます。以前のイメージはバックアップとして使用できます。

+
.例を示します
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. FastPath ソフトウェアの実行中のバージョンを確認します。
+
'how version （バージョンの表示） '

+
.例を示します
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. アクティブ構成とバックアップ構成のブートイメージを表示します。
+
'How bootvar'

+
.例を示します
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. スイッチをリブートします。
+
「再ロード」

+
.例を示します
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




=== 手順3：インストールを検証する

. もう一度ログインし、 FastPath ソフトウェアの新しいバージョンを確認します。
+
'how version （バージョンの表示） '

+
.例を示します
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. アクティブなスイッチ cs1 の ISL ポートを起動します。
+
「 configure 」を実行します

+
.例を示します
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. ISL が動作していることを確認します。
+
「 show port-channel 3/1 」

+
Link State フィールドには 'up' と表示されます

+
.例を示します
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. ソフトウェアのバージョンとスイッチの設定に問題がなければ 'running-config ファイルを 'startup-config ファイルにコピーします
+
.例を示します
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. 各ノードで2つ目のクラスタポートe2aを有効にします。
+
「 network port modify 」を参照してください

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. ポートe2aに関連付けられているclus2をリバートします。
+
「 network interface revert 」の略

+
ONTAP ソフトウェアのバージョンによっては、 LIF が自動的にリバートされる場合があります。

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. 両方のノードで LIF がホームになったことを確認します（「 true 」）。
+
'network interface show --_role cluster_`

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. ノードのステータスを表示します。
+
「 cluster show 」を参照してください

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. 上記の手順を繰り返して、もう一方のスイッチcs1にFastPathソフトウェアをインストールします。
. ケースの自動作成を抑制した場合は、 AutoSupport メッセージを呼び出して作成を再度有効にします。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます


