---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: FASTPATHソフトウェアをNetAppスイッチにインストールする場合、アップグレードは2番目のスイッチcs2から開始する必要があります。 
---
= FASTPATHソフトウェアのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FASTPATHソフトウェアをNetAppスイッチにインストールする場合は、2番目のスイッチである _cs2_ からアップグレードを開始する必要があります。



[[review-requirements]]
== 要件の確認

.開始する前に
以下のものがあることを確認してください。

* スイッチ構成の現在のバックアップ。
* 完全に機能するクラスター（ログにエラーがなく、クラスターネットワークインターフェースカード（NIC）の不具合や同様の問題がない）。
* クラスタスイッチ上のポート接続はすべて正常に機能しています。
* クラスタポートの設定が完了しました。
* すべてのクラスタ論理インターフェース（LIF）が設定されていること（移行されていないこと）。
* 通信パスが正常であること：ONTAP （privilege: advanced） `cluster ping-cluster -node node1`コマンドは、すべてのパスで `larger than PMTU communication`が成功していることを示す必要があります。
* FASTPATH および ONTAP のサポート対象バージョン。
+
サポートされている FASTPATH および ONTAP バージョンについては、 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601およびCN1610スイッチ"^] ページのスイッチ互換性表を必ず参照してください。





[[install-fastpath]]
== FASTPATHをインストールする

以下の手順では、クラスタ化された Data ONTAP 8.2 の構文を使用します。そのため、クラスタ Vserver、LIF 名、および CLI 出力は Data ONTAP 8.3 のものとは異なります。

RCF バージョンと FASTPATH バージョンのコマンド構文には、コマンド間の依存関係が存在する場合があります。

.例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 2つのNetAppスイッチはcs1とcs2です。
* 2つのクラスターLIFはclus1とclus2です。
* Vserverはvs1とvs2です。
*  `cluster::*>`プロンプトはクラスター名を示します。
* 各ノードのクラスタ ポートの名前はe1aおよびe2aです。
+
link:https://hwu.netapp.com/["Hardware Universe"^]には、お使いのプラットフォームでサポートされている実際のクラスタポートに関する詳細情報が記載されています。

* サポートされているスイッチ間リンク（ISL）は、ポート0/13～0/16です。
* サポートされているノード接続は、ポート0/1から0/12までです。




[[step-1-migrate-cluster]]
=== ステップ1：クラスターを移行する

. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

+

NOTE: AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

. 管理者としてスイッチにログインしてください。デフォルトではパスワードは設定されていません。 `(cs2) #`プロンプトで、 `enable`コマンドを入力してください。こちらも、デフォルトではパスワードは設定されていません。これにより、特権EXECモードにアクセスできるようになり、ネットワークインターフェースの設定が可能になります。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. 各ノードのコンソールで、clus2をポートe1aに移行します。
+
`network interface migrate`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. 各ノードのコンソールで、移行が完了したことを確認します。
+
`network interface show`

+
以下の例は、clus2が両方のノードでポートe1aに移行したことを示しています。

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




[[step-2-install-fastpath-software]]
=== ステップ2：FASTPATHソフトウェアをインストールする

. 両方のノードでクラスタポートe2aをシャットダウンします：
+
`network port modify`

+
.例を表示
[%collapsible]
====
以下の例は、両方のノードでポート e2a がシャットダウンされる様子を示しています。

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 両方のノードでポートe2aがシャットダウンされていることを確認します。
+
`network port show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. アクティブな NetApp スイッチcs1のインタースイッチリンク（ISL）ポートをシャットダウンします：
+
.例を表示
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. cs2 上の現在アクティブなイメージをバックアップします。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. スイッチにイメージ ファイルをダウンロードします。
+
イメージファイルをアクティブイメージにコピーすることで、再起動時にそのイメージが実行中のFASTPATHバージョンとして確立されます。以前のイメージはバックアップとして引き続き利用可能です。

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. FASTPATHソフトウェアの現在のバージョンを確認してください。
+
`show version`

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. アクティブ構成とバックアップ構成のブートイメージを表示します。
+
`show bootvar`

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. スイッチをリブートします。
+
`reload`

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




[[step-3-validate-installation]]
=== ステップ3：インストールの検証

. 再度ログインして、FASTPATHソフトウェアの新しいバージョンを確認してください。
+
`show version`

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. アクティブスイッチであるcs1のISLポートを起動します。
+
`configure`

+
.例を表示
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. ISLが正常に動作していることを確認してください。
+
`show port-channel 3/1`

+
リンク状態フィールドには、 `Up`と表示されます。

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
.  `running-config`ファイルを `startup-config`ファイルにコピーするのは、ソフトウェアのバージョンとスイッチの設定に問題がないことを確認してからにしてください。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. 各ノードで、2番目のクラスタポートであるe2aを有効にします。
+
`network port modify`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. ポートe2aに関連付けられているclus2を元に戻す：
+
`network interface revert`

+
LIF は、お使いの ONTAP ソフトウェアのバージョンによっては、自動的に元に戻る場合があります。

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. LIFが現在ホーム（(`true`）にあることを両方のノードで確認します：
+
`network interface show -_role cluster_`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. ノードのステータスを表示する：
+
`cluster show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. 前述の手順を繰り返して、もう一方のスイッチcs1にもFASTPATHソフトウェアをインストールします。
. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`


