---
permalink: switch-netapp-cn1610/install-fastpath-rcf-831.html 
sidebar: sidebar 
keywords: fastpath, software, install, netapp cluster switches, rcfs, ontap 
summary: FASTPATH ソフトウェアと参照構成ファイル（RCF）を NetApp CN1610 クラスタスイッチに ONTAP 8.3.1 以降でインストールします。 
---
= FASTPATH ソフトウェアと RCF を NetApp CN1610 クラスタスイッチにインストールする（ONTAP 8.3.1 以降）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FASTPATH ソフトウェアと参照構成ファイル（RCF）を NetApp CN1610 クラスタスイッチに ONTAP 8.3.1 以降でインストールします。

インストール手順は、ONTAP 8.3.1以降を実行しているNetApp CN1601管理スイッチとCN1610クラスタスイッチの両方で同じです。ただし、この2つのモデルでは異なるソフトウェアとRCFが必要です。



[[review-requirements]]
== 要件の確認

.開始する前に
以下のものがあることを確認してください。

* スイッチ構成の現在のバックアップ。
* 完全に機能するクラスター（ログにエラーがなく、クラスターネットワークインターフェースカード（NIC）の不具合や同様の問題がない）。
* クラスタスイッチ上のポート接続はすべて正常に機能しています。
* クラスタポートの設定が完了しました。
* すべてのクラスタ論理インターフェース（LIF）が設定されていること（移行されていないこと）。
* 通信パスが正常であること：ONTAP （privilege: advanced） `cluster ping-cluster -node node1`コマンドは、すべてのパスで `larger than PMTU communication`が成功していることを示す必要があります。
* サポートされているバージョンの FASTPATH、RCF、および ONTAP。
+
サポートされている FASTPATH、RCF、および ONTAP バージョンについては、 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601およびCN1610スイッチ"^]ページのスイッチ互換性表を必ず参照してください。





[[install-the-fastpath-software]]
== FASTPATHソフトウェアをインストールする

以下の手順では、クラスタ化された Data ONTAP 8.2 の構文を使用します。そのため、クラスタ Vserver、LIF 名、および CLI 出力は Data ONTAP 8.3 のものとは異なります。

RCF バージョンと FASTPATH バージョンのコマンド構文には、コマンド間の依存関係が存在する場合があります。


NOTE: RCFバージョン1.2では、セキュリティ上の懸念からTelnetのサポートが明示的に無効化されています。RCF 1.2のインストール中に接続の問題を回避するには、Secure Shell（SSH）が有効になっていることを確認してください。 https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610スイッチ管理者ガイド"^]には、SSHに関する詳細情報が記載されています。

.例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 2つのNetAppスイッチ名はcs1とcs2です。
* クラスタの論理インターフェース（LIF）名は、node1 の場合は node1_clus1 と node1_clus2、node2 の場合は node2_clus1 と node2_clus2 です。（クラスターには最大 24 個のノードを含めることができます。）
* ストレージ仮想マシン（SVM）の名前は Cluster です。
* その `cluster1::*>`プロンプトはクラスターの名前を示します。
* 各ノードのクラスタ ポートの名前はe0aおよびe0bです。
+
link:https://hwu.netapp.com/["Hardware Universe"^]には、お使いのプラットフォームでサポートされている実際のクラスタポートに関する詳細情報が記載されています。

* サポートされているスイッチ間リンク（ISL）は、ポート0/13～0/16です。
* サポートされているノード接続は、ポート0/1から0/12までです。




[[step-1-migrate-cluster]]
=== ステップ1：クラスターを移行する

. クラスタ上のネットワークポートに関する情報を表示します。
+
`network port show -_ipspace cluster_`

+
.例を表示
[%collapsible]
====
以下の例は、コマンドの出力タイプを示しています。

[listing]
----
cluster1::> network port show -ipspace cluster
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. クラスター上のLIFに関する情報を表示します。
+
`network interface show -_role cluster_`

+
.例を表示
[%collapsible]
====
以下の例は、クラスタ上の論理インターフェースを示しています。この例では、 `-role`パラメータはクラスタポートに関連付けられているLIFに関する情報を表示します。

[listing]
----
cluster1::> network interface show -role cluster
  (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16    node1         e0a     true
            node1_clus2  up/up    10.254.206.128/16  node1         e0b     true
            node2_clus1  up/up    10.254.48.152/16   node2         e0a     true
            node2_clus2  up/up    10.254.42.74/16    node2         e0b     true
4 entries were displayed.
----
====
. 各ノードにおいて、ノード管理LIFを使用して、node1上のnode1_clus2をe0aに、node2上のnode2_clus2をe0aに移行します：
+
`network interface migrate`

+
それぞれのクラスタLIFを所有するコントローラコンソールでコマンドを入力する必要があります。

+
.例を表示
[%collapsible]
====
[listing]
----
cluster1::> network interface migrate -vserver Cluster -lif node1_clus2 -destination-node node1 -destination-port e0a
cluster1::> network interface migrate -vserver Cluster -lif node2_clus2 -destination-node node2 -destination-port e0a
----
====
+

NOTE: このコマンドでは、クラスター名は大文字と小文字を区別します。また、このコマンドは各ノードで実行する必要があります。このコマンドは、一般的なクラスターLIFでは実行できません。

. ノードで `network interface show`コマンドを使用して、移行が実行されたことを確認します。
+
.例を表示
[%collapsible]
====
以下の例は、clus2がノード node1 と node2 のポート e0a に移行したことを示しています。

[listing]
----
cluster1::> **network interface show -role cluster**
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16   node1          e0a     true
            node1_clus2  up/up    10.254.206.128/16 node1          e0a     false
            node2_clus1  up/up    10.254.48.152/16  node2          e0a     true
            node2_clus2  up/up    10.254.42.74/16   node2          e0a     false
4 entries were displayed.
----
====
. 権限レベルをadvancedに変更し、続行するかどうかを尋ねられたら「y」と入力します：
+
`set -privilege advanced`

+
advancedのプロンプト（*>）が表示されます。

. 両方のノードでクラスタポートe0bをシャットダウンします：
+
`network port modify -node _node_name_ -port _port_name_ -up-admin false`

+
それぞれのクラスタLIFを所有するコントローラコンソールでコマンドを入力する必要があります。

+
.例を表示
[%collapsible]
====
以下の例は、すべてのノードでポート e0b をシャットダウンするコマンドを示しています。

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin false
cluster1::*> network port modify -node node2 -port e0b -up-admin false
----
====
. 両方のノードでポート e0b がシャットダウンされていることを確認してください。
+
`network port show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster1::*> network port show -role cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
4 entries were displayed.
----
====
. cs1のインタースイッチリンク（ISL）ポートをシャットダウンします。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config)#interface 0/13-0/16
(cs1) (Interface 0/13-0/16)#shutdown
(cs1) (Interface 0/13-0/16)#exit
(cs1) (Config)#exit
----
====
. cs2 上の現在アクティブなイメージをバックアップします。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.5     1.1.0.3            1.1.0.5            1.1.0.5

(cs2) # copy active backup
Copying active to backup
Copy operation successful
----
====




[[step-2-install-the-fastpath-software-and-rcf]]
=== ステップ2：FASTPATHソフトウェアとRCFをインストールする

. FASTPATHソフトウェアの現在のバージョンを確認してください。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. NetApp CN1610, 1.1.0.5, Linux
                                                2.6.21.7
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.1.0.5
Operating System............................... Linux 2.6.21.7
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893

--More-- or (q)uit


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
. スイッチにイメージ ファイルをダウンロードします。
+
イメージファイルをアクティブイメージにコピーすることで、再起動時にそのイメージが実行中のFASTPATHバージョンとして確立されます。以前のイメージはバックアップとして引き続き利用可能です。

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #copy sftp://root@10.22.201.50//tftpboot/NetApp_CN1610_1.2.0.7.stk active
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /tftpboot/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. 現在および次にアクティブになるブートイメージのバージョンを確認します。
+
`show bootvar`

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.8     1.1.0.8            1.1.0.8            1.2.0.7
----
====
. 新しいイメージバージョンに対応したRCFファイルをスイッチにインストールします。
+
RCFのバージョンがすでに正しい場合は、ISLポートを起動してください。

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #copy tftp://10.22.201.50//CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr

Mode........................................... TFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.


Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y


Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
====
+

NOTE: この `.scr`拡張子は、スクリプトを実行する前にファイル名の一部として設定する必要があります。この拡張子は、FASTPATH オペレーティングシステム用です。

+
スイッチは、スクリプトがスイッチにダウンロードされる際に、自動的にスクリプトを検証します。出力はコンソールに表示されます。

. スクリプトがダウンロードされ、指定したファイル名で保存されたことを確認してください。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #script list

Configuration Script Name        Size(Bytes)
-------------------------------- -----------
CN1610_CS_RCF_v1.2.scr                  2191

1 configuration script(s) found.
2541 Kbytes free.
----
====
. スクリプトをスイッチに適用します。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.2.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.2.scr' applied.
----
====
. 変更がスイッチに適用されたことを確認し、保存してください。
+
`show running-config`

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #show running-config
----
====
. 実行中の設定を保存しておくと、スイッチを再起動した際に起動設定として使用されます。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. スイッチをリブートします。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #reload

The system has unsaved changes.
Would you like to save them now? (y/n) y

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====




[[step-3-validate-installation]]
=== ステップ3：インストールの検証

. 再度ログインし、スイッチに新しいバージョンの FASTPATH ソフトウェアが実行されていることを確認してください。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) #show version

Switch: 1

System Description............................. NetApp CN1610, 1.2.0.7,Linux
                                                3.8.13-4ce360e8
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.2.0.7
Operating System............................... Linux 3.8.13-4ce360e8
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893
CPLD version................................... 0x5


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
+
再起動が完了したら、ログインしてイメージのバージョンを確認し、実行中の構成を表示して、インターフェース3/64の説明を確認してください。これがRCFのバージョンラベルです。

. アクティブスイッチであるcs1のISLポートを起動します。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config) #interface 0/13-0/16
(cs1) (Interface 0/13-0/16) #no shutdown
(cs1) (Interface 0/13-0/16) #exit
(cs1) (Config) #exit
----
====
. ISLが正常に動作していることを確認してください。
+
`show port-channel 3/1`

+
リンク状態フィールドには、 `Up`と表示されます。

+
.例を表示
[%collapsible]
====
[listing]
----
(cs1) #show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  False
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. すべてのノードでクラスタポートe0bを起動します。
+
`network port modify`

+
それぞれのクラスタLIFを所有するコントローラコンソールでコマンドを入力する必要があります。

+
.例を表示
[%collapsible]
====
以下の例は、node1とnode2でポートe0bが起動される様子を示しています。

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin true
cluster1::*> network port modify -node node2 -port e0b -up-admin true
----
====
. すべてのノードでポート e0b が稼働していることを確認します。
+
`network port show -ipspace cluster`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster1::*> network port show -ipspace cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. LIFが現在ホーム（(`true`）にあることを両方のノードで確認します：
+
`network interface show -_role cluster_`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -role cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.66.82/16   node1         e0a     true
            node1_clus2  up/up    169.254.206.128/16 node1         e0b     true
            node2_clus1  up/up    169.254.48.152/16  node2         e0a     true
            node2_clus2  up/up    169.254.42.74/16   node2         e0b     true
4 entries were displayed.
----
====
. ノードメンバーの状態を表示します：
+
`cluster show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====
. admin権限レベルに戻ります。
+
`set -privilege admin`

. 前述の手順を繰り返して、もう一方のスイッチ cs1 に FASTPATH ソフトウェアと RCF をインストールします。

