---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: NetAppスイッチに FASTPATH ソフトウェアをインストールする場合は、2 番目のスイッチ cs2 からアップグレードを開始する必要があります。 
---
= FASTPATHソフトウェアをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetAppスイッチに FASTPATH ソフトウェアをインストールする場合は、2 番目のスイッチ _cs2_ からアップグレードを開始する必要があります。



== 要件の確認

.開始する前に
以下のものがあることを確認してください。

* スイッチ構成の現在のバックアップ。
* 完全に機能しているクラスター (ログにエラーがなく、クラスター ネットワーク インターフェイス カード (NIC) に欠陥がなく、同様の問題もありません)。
* クラスター スイッチ上の完全に機能するポート接続。
* すべてのクラスター ポートが設定されました。
* すべてのクラスタ論理インターフェイス (LIF) がセットアップされている (移行されていないこと)。
* 成功した通信パス: ONTAP (権限: 上級) `cluster ping-cluster -node node1`コマンドは以下を示す必要があります `larger than PMTU communication`すべてのパスで成功します。
* サポートされている FASTPATH およびONTAPのバージョン。
+
スイッチの互換性表を必ず参照してください。 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601およびCN1610スイッチ"^]サポートされている FASTPATH およびONTAPバージョンについては、こちらのページをご覧ください。





== FASTPATHをインストールする

次の手順では、clustered Data ONTAP 8.2 構文を使用します。その結果、クラスタ Vserver、LIF 名、および CLI 出力は、 Data ONTAP 8.3 のものとは異なります。

RCF バージョンと FASTPATH バージョンのコマンド構文間にはコマンド依存関係が存在する場合があります。

.例について
この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 2 つのNetAppスイッチは cs1 と cs2 です。
* 2 つのクラスター LIF は clus1 と clus2 です。
* Vserver は vs1 と vs2 です。
* その `cluster::*>`プロンプトはクラスターの名前を示します。
* 各ノードのクラスタ ポートの名前はe1aおよびe2aです。
+
https://hwu.netapp.com/["Hardware Universe"^]プラットフォームでサポートされている実際のクラスター ポートに関する詳細情報は、こちらをご覧ください。

* サポートされているスイッチ間リンク (ISL) は、ポート 0/13 ～ 0/16 です。
* サポートされるノード接続はポート 0/1 ～ 0/12 です。




=== ステップ1: クラスターの移行

. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

+

NOTE: AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

. スイッチに管理者としてログインします。デフォルトではパスワードはありません。で `(cs2) #`プロンプトに入力してください `enable`指示。繰り返しますが、デフォルトではパスワードはありません。これにより、特権 EXEC モードにアクセスして、ネットワーク インターフェイスを設定できるようになります。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. 各ノードのコンソールで、clus2 をポート e1a に移行します。
+
`network interface migrate`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. 各ノードのコンソールで、移行が行われたことを確認します。
+
`network interface show`

+
次の例は、clus2 が両方のノードのポート e1a に移行したことを示しています。

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




=== ステップ2: FASTPATHソフトウェアをインストールする

. 両方のノードでクラスター ポート e2a をシャットダウンします。
+
`network port modify`

+
.例を表示
[%collapsible]
====
次の例では、両方のノードでポート e2a がシャットダウンされています。

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 両方のノードでポート e2a がシャットダウンされていることを確認します。
+
`network port show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. アクティブなNetAppスイッチである cs1 の Inter-Switch Link (ISL) ポートをシャットダウンします。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. cs2 上の現在のアクティブ イメージをバックアップします。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. スイッチにイメージ ファイルをダウンロードします。
+
イメージ ファイルをアクティブ イメージにコピーすると、再起動時にそのイメージによって実行中の FASTPATH バージョンが確立されます。以前のイメージはバックアップとして使用できます。

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. 実行中の FASTPATH ソフトウェアのバージョンを確認します。
+
`show version`

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. アクティブ構成とバックアップ構成のブート イメージを表示します。
+
`show bootvar`

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. スイッチをリブートします。
+
`reload`

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




=== ステップ3: インストールの検証

. 再度ログインし、FASTPATH ソフトウェアの新しいバージョンを確認します。
+
`show version`

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. アクティブ スイッチである cs1 の ISL ポートを起動します。
+
`configure`

+
.例を表示
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. ISL が動作していることを確認します。
+
`show port-channel 3/1`

+
リンク状態フィールドは以下を示す必要があります `Up`。

+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. コピー `running-config`ファイルに `startup-config`ソフトウェアのバージョンとスイッチの設定に満足したら、ファイルを保存します。
+
.例を表示
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. 各ノードで 2 番目のクラスター ポート e2a を有効にします。
+
`network port modify`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. ポート e2a に関連付けられている clus2 を元に戻します。
+
`network interface revert`

+
ONTAPソフトウェアのバージョンによっては、LIF が自動的に元に戻る場合があります。

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. LIFがホームになっていることを確認する(`true`) を両方のノードで実行します。
+
`network interface show -_role cluster_`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. ノードのステータスを表示します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. 前の手順を繰り返して、他のスイッチ cs1 に FASTPATH ソフトウェアをインストールします。
. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`


