---
permalink: switch-netapp-cn1610/migrate-switched-netapp-cn1610.html 
sidebar: sidebar 
keywords: migrate, switchless cluster environment, switched netapp cn1610 
summary: 既存の 2 ノードスイッチレスクラスタ環境を使用している場合は、 CN1610 クラスタネットワークスイッチを使用して 2 ノードスイッチクラスタ環境に移行し、 3 ノード以上に拡張することができます。 
---
= スイッチレスクラスタ環境から、スイッチを使用している NetApp CN1610 クラスタ環境への移行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存の 2 ノードスイッチレスクラスタ環境を使用している場合は、 CN1610 クラスタネットワークスイッチを使用して 2 ノードスイッチクラスタ環境に移行し、 3 ノード以上に拡張することができます。



== 要件を確認

.作業を開始する前に
次のものがあることを確認します。

2ノードスイッチレス構成の場合は、次の点を確認します。

* 2ノードスイッチレス構成が適切にセットアップされて機能しています。
* ノードでONTAP 8.2以降を実行している。
* すべてのクラスタポートがにあります `up` 状態。
* すべてのクラスタLIFがに含まれている必要があります `up` 状態とホームポートを確認します。


CN1610クラスタスイッチ構成の場合：

* 両方のスイッチでCN1610クラスタスイッチインフラが完全に機能するようになりました。
* 両方のスイッチに管理ネットワーク接続があります。
* クラスタスイッチへのコンソールアクセスがあります。
* CN1610ノード間スイッチおよびスイッチ間接続では、Twinaxケーブルまたはファイバケーブルを使用します。
+
。 https://hwu.netapp.com/["Hardware Universe"^] ケーブル接続の詳細については、を参照してください。

* スイッチ間リンク（ISL）ケーブルは、両方のCN1610スイッチのポート13~16に接続されます。
* 両方のCN1610スイッチの初期カスタマイズが完了しました。
+
SMTP 、 SNMP 、 SSH など、以前のサイトのカスタマイズを新しいスイッチにコピーする必要があります。



.関連情報
* http://hwu.netapp.com["Hardware Universe"^]
* http://support.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 / CN1610 の概要 ページ"^]
* https://library.netapp.com/ecm/ecm_download_file/ECMP1118645["『 CN1601 and CN1610 Switch Setup and Configuration Guide 』"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["ネットアップの技術情報アーティクル 1010449 ：「 How to suppress automatic case creation during scheduled maintenance windows"^]




== スイッチを移行します

.例について
この手順の例では、クラスタスイッチとノードで次の命名法を使用しています。

* CN1610 スイッチの名前は cs1 と cs2 です。
* LIF の名前は clus1 と clus2 です。
* ノードの名前は node1 と node2 になります。
* 'cluster::*>' プロンプトは ' クラスタの名前を示します
* この手順 で使用されるクラスタポートは、 e1a および e2a です。
+
。 https://hwu.netapp.com/["Hardware Universe"^] プラットフォームの実際のクラスタポートに関する最新情報が含まれます。





=== 手順1：移行の準備

. 権限レベルを advanced に変更します。続行するかどうかを尋ねられたら、「 y 」と入力します。
+
「 advanced 」の権限が必要です

+
advanced のプロンプト（ * > ）が表示されます。

. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= xh 」というメッセージが表示されます

+
_x_ は、メンテナンス時間の長さ（時間単位）です。

+

NOTE: AutoSupport メッセージはテクニカルサポートにこのメンテナンスタスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

+
.例を示します
[%collapsible]
====
次のコマンドは、ケースの自動作成を 2 時間停止します。

[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
====




=== 手順2：ポートを設定する

. 新しいクラスタスイッチ cs1 と cs2 の両方で、すべてのノード側ポート（ ISL ポートではない）を無効にします。
+
ISL ポートを無効にしないでください。

+
.例を示します
[%collapsible]
====
次の例は、スイッチ cs1 でノードに接続されたポート 1~12 が無効になっていることを示しています。

[listing]
----

(cs1)> enable
(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
次の例は、スイッチ cs2 でノード側のポート 1~12 が無効になっていることを示しています。

[listing]
----

(c2)> enable
(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
====
. 2つのCN1610クラスタスイッチcs1とcs2間のISLでISLポートと物理ポートがcs2であることを確認します `up`：
+
'how port-channel

+
.例を示します
[%collapsible]
====
次の例は、スイッチ cs1 上の ISL ポートが「 up 」になっていることを示しています。

[listing]
----

(cs1)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
次の例は、スイッチ cs2 上の ISL ポートが up になっていることを示しています。

[listing]
----

(cs2)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 隣接デバイスのリストを表示します。
+
「 isdp 隣人」

+
このコマンドは、システムに接続されているデバイスに関する情報を提供します。

+
.例を示します
[%collapsible]
====
次の例は、スイッチ cs1 上の隣接デバイスを示しています。

[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16
----
次の例は、スイッチ cs2 上の隣接デバイスを表示します。

[listing]
----

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
====
. クラスタポートのリストを表示します。
+
「 network port show 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例は、使用可能なクラスタポートを示しています。

[listing]
----

cluster::*> network port show -ipspace Cluster
Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false
12 entries were displayed.
----
====
. 各クラスタポートがパートナークラスタノードの対応するポートに接続されていることを確認します。
+
`run * cdpd show-neighbors`

+
.例を示します
[%collapsible]
====
次の例は、クラスタポート e1a と e2a が、クラスタパートナーノードの同じポートに接続されていることを示しています。

[listing]
----

cluster::*> run * cdpd show-neighbors
2 entries were acted on.

Node: node1
Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node2           e1a                    FAS3270           137   H
e2a    node2           e2a                    FAS3270           137   H


Node: node2

Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node1           e1a                    FAS3270           161   H
e2a    node1           e2a                    FAS3270           161   H
----
====
. すべてのクラスタLIFがであることを確認します `up` 運用面のメリット：
+
「 network interface show -vserver Cluster 」のように表示されます

+
各クラスタ LIF の列には 'Is Home` が表示されます

+
.例を示します
[%collapsible]
====
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up      10.10.10.1/16 node1         e1a     true
            clus2      up/up      10.10.10.2/16 node1         e2a     true
node2
            clus1      up/up      10.10.11.1/16 node2         e1a     true
            clus2      up/up      10.10.11.2/16 node2         e2a     true

4 entries were displayed.
----
====
+

NOTE: 手順 10~13 の変更コマンドと移行コマンドはローカルノードで実行する必要があります。

. すべてのクラスタポートが「 up 」になっていることを確認します。
+
「 network port show -ipspace cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> network port show -ipspace Cluster

                                       Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link  MTU   Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ----- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. 両方のノードで、クラスタ LIF clus1 および clus2 の「 -auto-revert 」パラメータを「 false 」に設定します。
+
「 network interface modify 」を参照してください

+
.例を示します
[%collapsible]
====
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert false
----
====
+

NOTE: リリース 8.3 以降では、次のコマンドを使用します。 network interface modify -vserver Cluster -lif * -auto-giveback false

. リモートクラスタインターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
を使用できます `network interface check cluster-connectivity` コマンドを使用してクラスタ接続のアクセスチェックを開始し、詳細を表示します。

`network interface check cluster-connectivity start` および `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注：*数秒待ってからコマンドを実行して `show`詳細を表示してください。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.すべてのONTAPリリース
--
すべてのONTAPリリースで、 `cluster ping-cluster -node <name>` 接続を確認するコマンド：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step10]] clus1を各ノードのコンソールのポートe2aに移行します。
+
「ネットワーク・インターフェイス移行」

+
.例を示します
[%collapsible]
====
次の例は、 node1 と node2 のポート e2a に clus1 を移行するプロセスを示しています。

[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus1 -source-node node1 -dest-node node1 -dest-port e2a
cluster::*> network interface migrate -vserver node2 -lif clus1 -source-node node2 -dest-node node2 -dest-port e2a
----
====
+

NOTE: リリース 8.3 以降では、次のコマンドを使用します。 network interface migrate -vserver Cluster -lif clus1 -destination-node node1 -destination-port e2a

. 移行が実行されたことを確認します。
+
「 network interface show -vserver Cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例は、 clus1 が node1 と node2 のポート e2a に移行されていることを確認します。

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e2a     false
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e2a     false
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
====
. 両方のノードのクラスタポートe1aをシャットダウンします。
+
「 network port modify 」を参照してください

+
.例を示します
[%collapsible]
====
次の例は、 node1 と node2 のポート e1a をシャットダウンします。

[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin false
cluster::*> network port modify -node node2 -port e1a -up-admin false
----
====
. ポートのステータスを確認します。
+
「 network port show 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例では、ポート e1a が node1 と node2 の「 down 」状態になっています。

[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. ノード 1 のクラスタポート e1a からケーブルを外し、 e1a をクラスタスイッチ cs1 のポート 1 に接続します。 CN1610 スイッチでサポートされている適切なケーブル接続を使用します。
+
。 link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^] ケーブル接続の詳細については、を参照してください。

. ノード 2 のクラスタポート e1a からケーブルを外し、次に e1a をクラスタスイッチ cs1 のポート 2 に接続します。 CN1610 スイッチでサポートされている適切なケーブル接続を使用します。
. クラスタスイッチ cs1 のすべてのノード側ポートを有効にします。
+
.例を示します
[%collapsible]
====
次の例は、スイッチ cs1 でポート 1~12 が有効になっていることを示しています。

[listing]
----

(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# no shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
====
. 各ノードの最初のクラスタポートe1aを有効にします。
+
「 network port modify 」を参照してください

+
.例を示します
[%collapsible]
====
次の例は、 node1 と node2 のポート e1a を有効にします。

[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin true
cluster::*> network port modify -node node2 -port e1a -up-admin true
----
====
. すべてのクラスタポートがであることを確認します `up`：
+
「 network port show -ipspace cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例は、ノード 1 とノード 2 のすべてのクラスタポートが「 up 」になっていることを示しています。

[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. clus1（以前に移行したもの）を両方のノードのe1aにリバートします。
+
「 network interface revert 」の略

+
.例を示します
[%collapsible]
====
次の例は、 clus1 をノード 1 とノード 2 のポート e1a にリバートする方法を示しています。

[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus1
cluster::*> network interface revert -vserver node2 -lif clus1
----
====
+

NOTE: リリース 8.3 以降では、次のコマンドを使用します。 network interface revert -vserver Cluster -lif <nodename_clus<N>`

. すべてのクラスタLIFがであることを確認します `up`、動作可能、として表示されます `true` Is Home列で、次の手順を実行します。
+
「 network interface show -vserver Cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例では、すべての LIF がノード 1 とノード 2 で「 up 」であり、「 Is Home 」列の結果が「 true 」であることを示します。

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
====
. クラスタ内のノードのステータスに関する情報を表示します。
+
「 cluster show 」を参照してください

+
.例を示します
[%collapsible]
====
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. clus2を各ノードのコンソールのポートe1aに移行します。
+
「ネットワーク・インターフェイス移行」

+
.例を示します
[%collapsible]
====
次の例は、 clus2 をノード 1 とノード 2 のポート e1a に移行するプロセスを示しています。

[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus2 -source-node node1 -dest-node node1 -dest-port e1a
cluster::*> network interface migrate -vserver node2 -lif clus2 -source-node node2 -dest-node node2 -dest-port e1a
----
====
+

NOTE: リリース 8.3 以降の場合は、次のコマンドを使用します。 network interface migrate -vserver Cluster -lif node1_clus2 -dest-node node1 -dest-port e1a

. 移行が実行されたことを確認します。
+
「 network interface show -vserver Cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例では、 clus2 が node1 と node2 のポート e1a に移行されていることを確認しています。

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e1a     false
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e1a     false

4 entries were displayed.
----
====
. 両方のノードで、クラスタポートe2aをシャットダウンします。
+
「 network port modify 」を参照してください

+
.例を示します
[%collapsible]
====
次の例は、 node1 と node2 のポート e2a をシャットダウンする方法を示しています。

[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. ポートのステータスを確認します。
+
「 network port show 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例は、 node1 と node2 のポート e2a が「 down 」になっていることを示しています。

[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. ノード 1 のクラスタポート e2a からケーブルを外し、 CN1610 スイッチでサポートされている適切なケーブル接続に従って、クラスタスイッチ cs2 のポート 1 に e2a を接続します。
. ノード 2 のクラスタポート e2a からケーブルを外し、 CN1610 スイッチでサポートされている適切なケーブル接続に従って、クラスタスイッチ cs2 のポート 2 に e2a を接続します。
. クラスタスイッチ cs2 のすべてのノード側ポートを有効にします。
+
.例を示します
[%collapsible]
====
次の例は、スイッチ cs2 でポート 1~12 が有効になっていることを示しています。

[listing]
----

(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# no shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
====
. 各ノードで2つ目のクラスタポートe2aを有効にします。
+
.例を示します
[%collapsible]
====
次の例は、 node1 と node2 のポート e2a を有効にする方法を示しています。

[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====
. すべてのクラスタポートがであることを確認します `up`：
+
「 network port show -ipspace cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例は、ノード 1 とノード 2 のすべてのクラスタポートが「 up 」になっていることを示しています。

[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. clus2（以前に移行されたもの）を両方のノードのe2aにリバートします。
+
「 network interface revert 」の略

+
.例を示します
[%collapsible]
====
次の例は、 node1 と node2 のポート e2a に clus2 をリバートする方法を示しています。

[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
+

NOTE: リリース 8.3 以降のコマンドは、「 cluster ：： * > network interface revert -vserver Cluster -lif node1_clus2 」および「 cluster ： * > network interface revert -vserver Cluster -lif node2_clus2 」です





=== 手順3：設定を完了します

. すべてのインターフェイスが表示されていることを確認します `true` Is Home列で、次の手順を実行します。
+
「 network interface show -vserver Cluster 」のように表示されます

+
.例を示します
[%collapsible]
====
次の例では、すべての LIF がノード 1 とノード 2 で「 up 」であり、「 Is Home 」列の結果が「 true 」であることを示します。

[listing]
----

cluster::*> network interface show -vserver Cluster

             Logical    Status     Network            Current     Current Is
Vserver      Interface  Admin/Oper Address/Mask       Node        Port    Home
-----------  ---------- ---------- ------------------ ----------- ------- ----
node1
             clus1      up/up      10.10.10.1/16      node1       e1a     true
             clus2      up/up      10.10.10.2/16      node1       e2a     true
node2
             clus1      up/up      10.10.11.1/16      node2       e1a     true
             clus2      up/up      10.10.11.2/16      node2       e2a     true
----
====
. リモートクラスタインターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
を使用できます `network interface check cluster-connectivity` コマンドを使用してクラスタ接続のアクセスチェックを開始し、詳細を表示します。

`network interface check cluster-connectivity start` および `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注：*数秒待ってからコマンドを実行して `show`詳細を表示してください。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.すべてのONTAPリリース
--
すべてのONTAPリリースで、 `cluster ping-cluster -node <name>` 接続を確認するコマンド：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step3]]両方のノードが各スイッチに2つの接続を持っていることを確認します。
+
「 isdp 隣人」

+
.例を示します
[%collapsible]
====
次の例は、両方のスイッチの該当する結果を示しています。

[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e1a
node2                  0/2          163       H            FAS3270   e1a
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e2a
node2                  0/2          163       H            FAS3270   e2a
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
====
. 構成に含まれるデバイスに関する情報を表示します。
+
`network device discovery show`

. advanced権限のコマンドを使用して、両方のノードで2ノードスイッチレス構成の設定を無効にします。
+
`network options detect-switchless modify`

+
.例を示します
[%collapsible]
====
次に、スイッチレスコンフィギュレーション設定をディセーブルにする例を示します。

[listing]
----

cluster::*> network options detect-switchless modify -enabled false
----
====
+

NOTE: リリース 9.2 以降では、設定が自動的に変換されるため、この手順は省略してください。

. 設定が無効になっていることを確認します。
+
「network options detect-switchless -cluster show」を参照してください

+
.例を示します
[%collapsible]
====
次の例では 'false' の出力は ' 構成設定が無効になっていることを示しています

[listing]
----

cluster::*> network options detect-switchless-cluster show
Enable Switchless Cluster Detection: false
----
====
+

NOTE: リリース 9.2 以降では 'Enable Switchless Cluster' が false に設定されるまで待ちますこれには 3 分程度かかる場合があります。

. 各ノードでクラスタclus1とclus2を自動リバートするように設定し、確認します。
+
.例を示します
[%collapsible]
====
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert true
----
====
+

NOTE: リリース 8.3 以降では、次のコマンドを使用します。 network interface modify -vserver Cluster -lif * -auto-revert true クラスタ内のすべてのノードで自動リバートを有効にします。

. クラスタ内のノードメンバーのステータスを確認します。
+
「 cluster show 」を参照してください

+
.例を示します
[%collapsible]
====
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. ケースの自動作成を抑制した場合は、 AutoSupport メッセージを呼び出して作成を再度有効にします。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
. 権限レベルを admin に戻します。
+
「特権管理者」


