---
permalink: switch-netapp-cn1610/migrate-fas22xx-systems.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, fas22xx systems, single, network connection 
summary: 単一のクラスタネットワーク接続を持つスイッチレスクラスタから、NetApp CN1610 クラスタスイッチを使用するスイッチ付きクラスタに FAS22xx システムを移行します。 
---
= FAS22xx システムを NetApp CN1610 クラスタスイッチを使用してスイッチドクラスタに移行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS22xx システムを、コントローラごとに 1 つの 10 GbE 接続を持つ 2 ノードのスイッチレス クラスタから、NetApp CN1610 クラスタスイッチを使用したスイッチクラスタに移行します。



[[review-requirements]]
== 要件の確認

.開始する前に
以下のものがあることを確認してください。

* スイッチレス構成からスイッチ構成へ移行するための2つのクラスタ接続。
* クラスターは正常であり、スイッチを介さずに直接接続された 2 つのノードで構成されています。
* ノードでONTAP 8.2以降が実行されています。
* スイッチレスクラスタ機能は、2ノードを超える構成では使用できません。
* すべてのクラスタポートが `up`状態です。


.関連情報
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetAppの技術情報アーティクル1010449：「How to suppress automatic case creation during scheduled maintenance windows」"^]



[[migrate-the-switches]]
== スイッチを移行する

この手順は、スイッチレス環境でのクラスタへの直接接続を削除し、スイッチへの各接続をパートナーノードへの接続に置き換える、無停止の手順です。



[[step-1-prepare-for-migration]]
=== ステップ1: 移行の準備

. 権限レベルを上級に変更するには、次のように入力します。 `y`続行するように求められたら:
+
`set -privilege advanced`

+
高度なプロンプト(`*>`）が表示されます。

. いずれかのノードのシステムコンソールで、ノードのクラスタのステータスを確認します：
+
`cluster show`

+
.例を表示
[%collapsible]
====
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. いずれかのノードのシステムコンソールでHAペアのステータスを確認します： `storage failover show`
+
.例を表示
[%collapsible]
====
以下の例は、node1とnode2のクラスタのステータスを示しています。

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
`x`はメンテナンス期間（時間単位）です。

+

NOTE: このメッセージは、このメンテナンス作業についてテクニカルサポートに通知し、メンテナンス期間中は自動的なケース作成が抑制されるようにするものです。

+
.例を表示
[%collapsible]
====
次のコマンドは、自動ケース作成を 2 時間抑制します。

[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
====
. スイッチレスクラスタの現在の状態が `true`であることを確認し、スイッチレスクラスタモードを無効にします。
+
`network options switchless-cluster modify -enabled false`

. ターゲットノードをテイクオーバーします：
+
`storage failover takeover -ofnode _target_node_name_`

+
どのノードがターゲットノードであるかは問題ではありません。テイクオーバーされると、ターゲットノードは自動的に再起動し、 `Waiting for giveback...`メッセージが表示されます。

+
現在アクティブなノードは、テイクオーバーされたパートナー（ターゲット）ノードのデータを提供しています。

. 障害が発生したノードのテイクオーバー後、2分間待って、テイクオーバーが正常に完了したことを確認してください。
. ターゲットノードに `Waiting for giveback...`メッセージが表示されたら、シャットダウンします。
+
ノードをシャットダウンする方法は、ノードの Service Processor （SP）を介したリモート管理を使用するかどうかによって異なります。

+
|===
| SPの場合 | 操作 


 a| 
設定済み
 a| 
障害が発生したノードの SP にログインし、システムの電源をオフにします： `system power off`



 a| 
設定されていません
 a| 
障害ノードのプロンプトで `Ctrl-C`を押し、 `y`と応答してノードを停止します。

|===




[[step-2-configure-cables-and-ports]]
=== ステップ2: ケーブルとポートを構成する

. 各コントローラモジュールで、10 GbEクラスタポートとスイッチレスクラスタを接続しているケーブルを外します。
. 両方のコントローラモジュールで、10GbEクラスタポートをスイッチに接続します。
. スイッチに接続されている10 GbEクラスタポートが、同じVLANに属するように設定されていることを確認してください。
+
各コントローラモジュールのクラスタポートを異なるスイッチに接続する予定の場合は、各スイッチでクラスタポートが接続されているポートが同じ VLAN 用に構成されており、トランキングが両方のスイッチで正しく設定されていることを確認する必要があります。

. ストレージをターゲットノードに返却します：
+
`storage failover giveback -ofnode node2`

. ギブバック操作の進捗状況を監視します：
+
`storage failover show-giveback`

. ギブバック操作が完了したら、HAペアが正常であり、テイクオーバーが可能であることを確認します。
+
`storage failover show`

+
.例を表示
[%collapsible]
====
次のような出力が表示されます。

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. クラスタポートのLIFが正しく動作していることを確認してください。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
次の例は、LIFが `up`node1とnode2にあり、「Is Home」列の結果が `true`であることを示しています：

[listing]
----

cluster::*> network interface show -role cluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
node1
            clus1        up/up    192.168.177.121/24  node1        e1a     true
node2
            clus1        up/up    192.168.177.123/24  node2        e1a     true

2 entries were displayed.
----
====
. いずれかのノードのシステムコンソールで、ノードのクラスタのステータスを確認します：
+
`cluster show`

+
.例を表示
[%collapsible]
====
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====


[[step-3-complete-the-procedure]]
=== ステップ3: 手順を完了する

. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
. 権限レベルを管理者に戻します。
+
`set -privilege admin`


