---
permalink: switch-netapp-cn1610/migrate-fas22xx-systems.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, fas22xx systems, single, network connection 
summary: 既存の 2 ノード スイッチレス クラスターに FAS22xx システムがあり、各コントローラー モジュールにクラスター接続用の単一のバックツーバック 10 GbE 接続がある場合は、スイッチレス クラスター ネットワーク オプションを使用して、直接のバックツーバック接続をスイッチ接続に置き換えることができます。 
---
= 単一のクラスタネットワーク接続を持つFAS22xxシステムの2ノードスイッチクラスタに移行します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存の 2 ノード スイッチレス クラスターに FAS22xx システムがあり、各コントローラー モジュールにクラスター接続用の単一のバックツーバック 10 GbE 接続がある場合は、スイッチレス クラスター ネットワーク オプションを使用して、直接のバックツーバック接続をスイッチ接続に置き換えることができます。



== 要件の確認

.開始する前に
以下のものがあることを確認してください。

* スイッチレス構成からスイッチ構成に移行するための 2 つのクラスター接続。
* クラスターは正常であり、バックツーバック接続で接続された 2 つのノードで構成されています。
* ノードはONTAP 8.2 以降を実行しています。
* スイッチレス クラスター機能は、2 つ以上のノードでは使用できません。
* すべてのクラスタポートは `up`州。


.関連情報
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetAppの技術情報アーティクル1010449：「How to suppress automatic case creation during scheduled maintenance windows」"^]



== スイッチを移行する

この手順は、スイッチレス環境での直接的なクラスタ接続を削除し、スイッチへの各接続をパートナー ノードへの接続に置き換える、中断を伴わない手順です。



=== ステップ1: 移行の準備

. 権限レベルを上級に変更するには、次のように入力します。 `y`続行するように求められたら:
+
`set -privilege advanced`

+
高度なプロンプト(`*>`）が表示されます。

. いずれかのノードのシステム コンソールでノードのクラスター ステータスを確認します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. どちらかのノードのシステム コンソールで HA ペアのステータスを確認します。 `storage failover show`
+
.例を表示
[%collapsible]
====
次の例は、node1 と node2 のステータスを示しています。

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
`x`メンテナンス ウィンドウの期間 (時間単位) です。

+

NOTE: このメッセージは、このメンテナンス タスクをテクニカル サポートに通知し、メンテナンス ウィンドウ中の自動ケース作成を抑制します。

+
.例を表示
[%collapsible]
====
次のコマンドは、自動ケース作成を 2 時間抑制します。

[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
====
. スイッチレスクラスタの現在の状態を確認します。 `true` 、スイッチレス クラスター モードを無効にします。
+
`network options switchless-cluster modify -enabled false`

. ターゲットノードを乗っ取ります。
+
`storage failover takeover -ofnode _target_node_name_`

+
どのノードがターゲット ノードであるかは関係ありません。引き継がれると、ターゲットノードは自動的に再起動し、 `Waiting for giveback...`メッセージ。

+
アクティブ ノードは現在、引き継がれたパートナー (ターゲット) ノードにデータを提供しています。

. 障害が発生したノードの引き継ぎ後、引き継ぎが正常に完了したことを確認するために 2 分間待ちます。
. ターゲットノードに `Waiting for giveback...`メッセージが表示されたら、シャットダウンします。
+
ノードをシャットダウンする方法は、ノードのサービス プロセッサ (SP) を介してリモート管理を使用するかどうかによって異なります。

+
|===
| SPの場合 | 操作 


 a| 
設定されている
 a| 
障害が発生したノードSPにログインし、システムの電源をオフにします。 `system power off`



 a| 
設定されていません
 a| 
障害ノードのプロンプトで、 `Ctrl-C` 、そして応答する `y`ノードを停止します。

|===




=== ステップ2: ケーブルとポートを構成する

. 各コントローラー モジュールで、10 GbE クラスター ポートをスイッチレス クラスターに接続しているケーブルを外します。
. 10 GbE クラスター ポートを両方のコントローラー モジュールのスイッチに接続します。
. スイッチに接続された 10 GbE クラスター ポートが同じ VLAN の一部として構成されていることを確認します。
+
各コントローラ モジュールのクラスタ ポートを異なるスイッチに接続する予定の場合は、各スイッチ上のクラスタ ポートが接続されているポートが同じ VLAN に設定され、両方のスイッチでトランキングが適切に設定されていることを確認する必要があります。

. ストレージをターゲットノードに戻します。
+
`storage failover giveback -ofnode node2`

. ギブバック操作の進行状況を監視します。
+
`storage failover show-giveback`

. ギブバック操作が完了したら、HA ペアが正常であり、テイクオーバーが可能であることを確認します。
+
`storage failover show`

+
.例を表示
[%collapsible]
====
次のような出力が表示されます。

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. クラスタ ポート LIF が正しく動作していることを確認します。
+
`network interface show -role cluster`

+
.例を表示
[%collapsible]
====
次の例は、LIFが `up`ノード1とノード2で「Is Home」列の結果が `true`:

[listing]
----

cluster::*> network interface show -role cluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
node1
            clus1        up/up    192.168.177.121/24  node1        e1a     true
node2
            clus1        up/up    192.168.177.123/24  node2        e1a     true

2 entries were displayed.
----
====
. いずれかのノードのシステム コンソールでノードのクラスター ステータスを確認します。
+
`cluster show`

+
.例を表示
[%collapsible]
====
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. リモート クラスタ インターフェイスの接続を確認します。


[role="tabbed-block"]
====
.ONTAP 9.9.1以降
--
使用することができます `network interface check cluster-connectivity`クラスター接続のアクセシビリティ チェックを開始し、詳細を表示するコマンド:

`network interface check cluster-connectivity start`そして `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意:* 実行する前に数秒待ってください `show`詳細を表示するコマンド。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.ONTAPのすべてのリリース
--
すべてのONTAPリリースでは、 `cluster ping-cluster -node <name>`接続を確認するコマンド:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====


=== ステップ3: 手順を完了する

. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.例を表示
[%collapsible]
====
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
. 権限レベルを管理者に戻します。
+
`set -privilege admin`


