---
permalink: switch-netapp-cn1610/replace-cn1610-switch.html 
sidebar: sidebar 
keywords: replace, netapp cn1610, cluster switch 
summary: 特定の一連のタスクを実行することで、障害のあるNetApp CN1610 クラスタ スイッチを中断することなく交換できます。 
---
= NetApp CN1610クラスタスイッチの交換
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ ネットワーク内の故障したNetApp CN1610 スイッチを交換するには、次の手順に従います。これは非中断手順 (NDU) です。



== 要件の確認

.開始する前に
スイッチの交換を実行する前に、現在の環境と既存のクラスタおよびネットワーク インフラストラクチャの交換用スイッチでスイッチの交換を実行する前に、次の条件が満たされている必要があります。

* 既存のクラスタで、少なくとも1つのクラスタ スイッチが完全に接続されており、完全に機能できる状態であることを確認する必要があります。
* すべてのクラスター ポートが *アップ* になっている必要があります。
* すべてのクラスタ論理インターフェイス (LIF) が起動しており、移行されていないことが必要です。
* ONTAPクラスタ `ping-cluster -node node1`コマンドは、すべてのパスで基本的な接続と PMTU より大きい通信が成功していることを示す必要があります。




== コンソールログを有効にする

NetApp、使用しているデバイスでコンソール ログを有効にし、スイッチを交換するときに次のアクションを実行することを強くお勧めします。

* メンテナンス中はAutoSupport を有効のままにしておきます。
* メンテナンスの前後にメンテナンスAutoSupportをトリガーして、メンテナンス期間中のケース作成を無効にします。このナレッジベースの記事を参照してください https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: スケジュールされたメンテナンス期間中の自動ケース作成を抑制する方法"^]詳細については、こちらをご覧ください。
* すべての CLI セッションのセッション ログを有効にします。セッションログを有効にする方法については、このナレッジベースの記事の「セッション出力のログ記録」セクションを参照してください。 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAPシステムへの最適な接続を実現するための PuTTY の設定方法"^] 。




== スイッチを交換する

.タスク概要
クラスタLIFを移行するコマンドは、そのクラスタLIFがホストされているノードで実行する必要があります。

この手順の例では、クラスタ スイッチとノードで次の命名法を使用しています。

* 2台のCN1610クラスタスイッチの名前は `cs1`そして `cs2`。
* 交換対象となるCN1610スイッチ（故障スイッチ）の名前は `old_cs1`。
* 新しいCN1610スイッチ（交換スイッチ）の名前は `new_cs1`。
* 交換されないパートナースイッチの名前は `cs2`。


.手順
. スタートアップ コンフィギュレーション ファイルが実行コンフィギュレーション ファイルと一致していることを確認します。置換時に使用するために、これらのファイルをローカルに保存する必要があります。
+
次の例の設定コマンドは、FASTPATH 1.2.0.7 用です。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)> *enable*
(old_cs1)# *show running-config*
(old_cs1)# *show startup-config*
----
====
. 実行中の構成ファイルのコピーを作成します。
+
次の例のコマンドは、FASTPATH 1.2.0.7 用です。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *show running-config filename.scr*
Config script created successfully.
----
====



NOTE: ファイル名は任意ですが、 `CN1610_CS_RCF_v1.2.scr` 。ファイル名には *.scr* 拡張子が必要です。

. [[step3]]交換に備えて、スイッチの実行コンフィギュレーションファイルを外部ホストに保存します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *copy nvram:script filename.scr scp://<Username>@<remote_IP_address>/path_to_file/filename.scr*
----
====
. 互換性マトリックスでスイッチとONTAP のバージョンが一致していることを確認します。参照 https://mysupport.netapp.com/site/info/netapp-cluster-switch["NetApp CN1601およびCN1610スイッチ"^]詳細についてはページをご覧ください。
. から https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/downloads-tab["ソフトウェアダウンロードページ"^]NetAppサポート サイトで、 NetApp Cluster Switches を選択し、適切な RCF および FASTPATH バージョンをダウンロードします。
. FASTPATH、RCF、および保存された構成を使用してTFTP（Trivial File Transfer Protocol）サーバーをセットアップします。 `.scr`新しいスイッチで使用するためのファイル。
. シリアル ポート (スイッチの右側にある「IOIOI」というラベルの付いた RJ-45 コネクタ) を、端末エミュレーションを備えた使用可能なホストに接続します。
. ホストで、シリアル端末の接続設定を設定します。
+
.. 9600ボー
.. 8データ ビット
.. 1ストップ ビット
.. パリティ：なし
.. フロー制御：なし


. 管理ポート（スイッチの左側にあるRJ-45レンチ ポート）を、TFTPサーバが配置されているネットワークと同じネットワークに接続します。
. TFTP サーバーを使用してネットワークに接続する準備をします。
+
ダイナミック ホスト コンフィギュレーション プロトコル (DHCP) を使用している場合は、この時点でスイッチの IP アドレスを設定する必要はありません。サービス ポートは、デフォルトで DHCP を使用するように設定されています。 IPv4 および IPv6 プロトコル設定では、ネットワーク管理ポートは「なし」に設定されています。レンチ ポートが DHCP サーバーがあるネットワークに接続されている場合、サーバー設定は自動的に構成されます。

+
静的 IP アドレスを設定するには、serviceport protocol、network protocol、および serviceport ip コマンドを使用する必要があります。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *serviceport ip <ipaddr> <netmask> <gateway>*
----
====
. オプションとして、TFTP サーバーがラップトップ上にある場合は、標準のイーサネット ケーブルを使用して CN1610 スイッチをラップトップに接続し、同じネットワーク内のネットワーク ポートを代替 IP アドレスで構成します。
+
使用することができます `ping`アドレスを確認するコマンド。接続を確立できない場合は、ルーティングされていないネットワークを使用し、IP 192.168.x または 172.16.x を使用してサービス ポートを構成する必要があります。後日、サービス ポートを本番管理 IP アドレスに再構成できます。

. 必要に応じて、新しいスイッチに適したバージョンの RCF および FASTPATH ソフトウェアを確認してインストールします。新しいスイッチが正しく設定され、RCF および FASTPATH ソフトウェアの更新が必要ないことを確認した場合は、手順 13 に進みます。
+
.. 新しいスイッチの設定を確認します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show version*
----
====
.. RCF を新しいスイッチにダウンロードします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr*
Mode.	TFTP
Set Server IP.	172.22.201.50
Path.	/
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr
File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. please wait...
Validating configuration script...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script validated.
File transfer operation completed successfully.
----
====
.. RCF がスイッチにダウンロードされていることを確認します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script list*
Configuration Script Nam   Size(Bytes)
-------------------------- -----------
CN1610_CS_RCF_v1.1.scr            2191
CN1610_CS_RCF_v1.2.scr            2240
latest_config.scr                 2356

4 configuration script(s) found.
2039 Kbytes free.
----
====


. RCF を CN1610 スイッチに適用します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply CN1610_CS_RCF_v1.2.scr*
Are you sure you want to apply the configuration script? (y/n) *y*
...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script 'CN1610_CS_RCF_v1.2.scr' applied. Note that the script output will go to the console.
After the script is applied, those settings will be active in the running-config file. To save them to the startup-config file, you must use the write memory command, or if you used the reload answer yes when asked if you want to save the changes.
----
====
+
.. 実行コンフィギュレーション ファイルを保存して、スイッチを再起動したときにスタートアップ コンフィギュレーション ファイルになるようにします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. イメージを CN1610 スイッチにダウンロードします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/NetApp_CN1610_1.2.0.7.stk active*
Mode.	TFTP
Set Server IP.	tftp_server_ip_address
Path.	/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type.	Code
Destination Filename.	active

Management access will be blocked for the duration of the transfer

Are you sure you want to start? (y/n) *y*

TFTP Code transfer starting...

File transfer operation completed successfully.
----
====
.. スイッチを再起動して、新しいアクティブ ブート イメージを実行します。
+
手順 6 のコマンドで新しいイメージを反映するには、スイッチを再起動する必要があります。  reload コマンドを入力した後に表示される応答には、2 つのビューがあります。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *reload*
The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved! System will now restart!
.
.
.
Cluster Interconnect Infrastructure

User:admin Password: (new_cs1) >*enable*
----
====
.. 保存した設定ファイルを古いスイッチから新しいスイッチにコピーします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/<filename>.scr nvram:script <filename>.scr*
----
====
.. 以前に保存した設定を新しいスイッチに適用します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply <filename>.scr*
Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. 実行中の構成ファイルをスタートアップ構成ファイルに保存します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
----
====


. このクラスタでAutoSupportが有効になっている場合は、 AutoSupportメッセージを呼び出して自動ケース作成を抑制します。
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

+
[NOTE]
====
AutoSupportメッセージはテクニカル サポートにこのメンテナンス タスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

====
. 新しいスイッチ new_cs1 で、管理者ユーザーとしてログインし、ノード クラスタ インターフェイスに接続されているすべてのポート (ポート 1 ～ 12) をシャットダウンします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
User:*admin*
Password:
(new_cs1)> *enable*
(new_cs1)#
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/1-0/12)# *shutdown*
(new_cs1)(interface 0/1-0/12)# *exit*
(new_cs1)# *write memory*
----
====
. old_cs1 スイッチに接続されているポートからクラスター LIF を移行します。
+
各クラスタ LIF を現在のノードの管理インターフェイスから移行する必要があります。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *set -privilege advanced*
cluster::> *network interface migrate -vserver <vserver_name> -lif <Cluster_LIF_to_be_moved> - sourcenode <current_node> -dest-node <current_node> -dest-port <cluster_port_that_is_UP>*
----
====
. すべてのクラスタ LIF が各ノードの適切なクラスタ ポートに移動されていることを確認します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network interface show -role cluster*
----
====
. 交換したスイッチに接続されているクラスター ポートをシャットダウンします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node <node_name> -port <port_to_admin_down> -up-admin false*
----
====
. クラスターの健全性を確認します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. ポートがダウンしていることを確認します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node <node_name>*
----
====
. スイッチ cs2 で、ISL ポート 13 ～ 16 をシャットダウンします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *shutdown*
(cs2)# *show port-channel 3/1*
----
====
. ストレージ管理者がスイッチの交換の準備ができているかどうかを確認します。
. old_cs1 スイッチからすべてのケーブルを取り外し、それらのケーブルを new_cs1 スイッチの同じポートに接続します。
. cs2 スイッチで、ISL ポート 13 ～ 16 を起動します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *no shutdown*
----
====
. クラスター ノードに関連付けられている新しいスイッチ上のポートを起動します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/13-0/16)# *no shutdown*
----
====
. 単一ノードで、交換したスイッチに接続されているクラスター ノード ポートを起動し、リンクがアップしていることを確認します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node node1 -port <port_to_be_onlined> -up-admin true*
cluster::*> *network port show -role cluster*
----
====
. 同じノード上の手順 25 でポートに関連付けられているクラスタ LIF を元に戻します。
+
この例では、「Is Home」列が true の場合、node1 上の LIF は正常に元に戻されます。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver node1 -lif <cluster_lif_to_be_reverted>*
cluster::*> *network interface show -role cluster*
----
====
. 最初のノードのクラスタ LIF が起動し、ホーム ポートに戻されている場合は、手順 25 と 26 を繰り返して、クラスタ ポートを起動し、クラスタ内の他のノードのクラスタ LIF を元に戻します。
. クラスター内のノードに関する情報を表示します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. 交換したスイッチのスタートアップ コンフィギュレーション ファイルと実行コンフィギュレーション ファイルが正しいことを確認します。この構成ファイルは手順 1 の出力と一致する必要があります。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show running-config*
(new_cs1)# *show startup-config*
----
====
. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`


