---
permalink: switch-netapp-cn1610/replace-cn1610-switch.html 
sidebar: sidebar 
keywords: replace, netapp cn1610, cluster switch 
summary: 障害が発生したNetApp CN1610クラスタスイッチは、特定の順序でタスクを実行することで無停止で交換できます。 
---
= NetApp CN1610クラスタスイッチを交換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタネットワーク内の故障したNetApp CN1610スイッチを交換するには、次の手順を実行します。これは無停止手順（NDU）です。



== 要件を確認

.必要なもの
スイッチを交換する前に、現在の環境および既存のクラスタおよびネットワークインフラの交換用スイッチでスイッチを交換する前に、次の条件が満たされている必要があります。

* 既存のクラスタで、少なくとも 1 つのクラスタスイッチが完全に接続されており、完全に機能することを確認する必要があります。
* すべてのクラスタポートが* up *になっている必要があります。
* すべてのクラスタ論理インターフェイス（LIF）が稼働していて、移行されていない必要があります。
* ONTAPクラスタ `ping-cluster -node node1` コマンドは、すべてのパスで基本的な接続とPMTUを超える通信が成功したことを示す必要があります。




== コンソールログを有効にする

NetAppでは、使用しているデバイスでコンソールロギングをイネーブルにし、スイッチを交換するときに次のアクションを実行することを強く推奨します。

* メンテナンス中はAutoSupportを有効のままにします。
* メンテナンスの前後にメンテナンスAutoSupportをトリガーして、メンテナンス中のケースの作成を無効にします。このナレッジベースの記事を参照 https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92:スケジュールされたメンテナンス時間中にケースが自動作成されないようにする方法"^] を参照してください。
* CLIセッションのセッションロギングをイネーブルにします。セッションログを有効にする方法については、このナレッジベースの記事の「セッション出力のログ」セクションを参照してください。 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAPシステムへの接続を最適化するためのPuTTYの設定方法"^]。




== スイッチを交換します

.このタスクについて
クラスタ LIF を移行するコマンドは、そのクラスタ LIF がホストされているノードで実行する必要があります。

この手順の例では、クラスタスイッチとノードで次の命名法を使用しています。

* 2つのCN1610クラスタスイッチの名前はです `cs1` および `cs2`。
* 交換するCN1610スイッチ（故障したスイッチ）の名前はです `old_cs1`。
* 新しいCN1610スイッチ（交換用スイッチ）の名前はです `new_cs1`。
* 交換しないパートナースイッチの名前はです `cs2`。


.手順
. スタートアップコンフィギュレーションファイルが実行コンフィギュレーションファイルと一致することを確認します。これらのファイルは、交換時に使用するためにローカルに保存する必要があります。
+
次の例のコンフィギュレーションコマンドは、FastPath 1.2.0.7用です。

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1) *>enable*
(old_cs1) *#show running-config*
(old_cs1) *#show startup-config*
----
====
. 実行コンフィギュレーションファイルのコピーを作成します。
+
次の例のコマンドは、FastPath 1.2.0.7に対するものです。

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1) *#show running-config filename.scr*
Config script created successfully.
----
====



NOTE: 以外の任意のファイル名を使用できます `CN1610_CS_RCF_v1.2.scr`。ファイル名の拡張子は*。scr *である必要があります。

. [[step3]]交換に備えて、スイッチの実行コンフィギュレーションファイルを外部ホストに保存します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1) #*copy nvram:script filename.scr scp://<Username>@<remote_IP_address>/path_to_file/filename.scr*
----
====
. スイッチとONTAPのバージョンが互換性マトリックスで一致していることを確認します。を参照してください https://mysupport.netapp.com/site/info/netapp-cluster-switch["NetApp CN1601 / CN1610 スイッチ"^] ページを参照してください。
. から https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/downloads-tab["ソフトウェアのダウンロードページ"^] NetApp Support Siteで、[NetApp Cluster Switches]を選択して、適切なバージョンのRCFとFastPathをダウンロードします。
. FastPath、RCF、および保存されている設定を使用して、Trivial File Transfer Protocol（TFTP）サーバをセットアップします `.scr` 新しいスイッチで使用するファイル。
. シリアルポート（スイッチの右側にある「IOIOI」というラベルの付いたRJ-45コネクタ）を、ターミナルエミュレーションを備えた使用可能なホストに接続します。
. ホストで、シリアルターミナル接続を設定します。
+
.. 9600 ボー
.. 8 データビット
.. 1 ストップビット
.. パリティ：なし
.. フロー制御：なし


. 管理ポート（スイッチの左側にある RJ-45 レンチポート）を、 TFTP サーバが配置されているネットワークと同じネットワークに接続します。
. TFTPサーバを使用してネットワークに接続する準備をします。
+
Dynamic Host Configuration Protocol（DHCP；動的ホスト構成プロトコル）を使用している場合は、この時点でスイッチのIPアドレスを設定する必要はありません。サービスポートは、デフォルトでDHCPを使用するように設定されています。IPv4プロトコルとIPv6プロトコルの設定では、ネットワーク管理ポートがnoneに設定されます。レンチマークのポートがDHCPサーバがあるネットワークに接続されている場合は、サーバ設定が自動的に設定されます。

+
静的IPアドレスを設定するには、serviceport protocol、network protocol、およびserviceport ipコマンドを使用する必要があります。

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*serviceport ip <ipaddr> <netmask> <gateway>*
----
====
. 必要に応じて、TFTPサーバがラップトップ上にある場合は、標準のイーサネットケーブルを使用してCN1610スイッチをラップトップに接続し、別のIPアドレスを使用して同じネットワーク内のネットワークポートを設定します。
+
を使用できます `ping` アドレスを確認するコマンド。接続を確立できない場合は、ルーティングされていないネットワークを使用し、IP 192.168.xまたは172.16.xを使用してサービスポートを設定する必要がありますサービスポートは、後日本番管理IPアドレスに再設定できます。

. 必要に応じて、新しいスイッチに対応するバージョンのRCFおよびFastPathソフトウェアを確認してインストールします。新しいスイッチが正しくセットアップされており、RCFおよびFastPathソフトウェアの更新が不要であることを確認した場合は、ステップ13に進みます。
+
.. 新しいスイッチの設定を確認します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) >*enable*
(new_cs1) #*show version*
----
====
.. RCFを新しいスイッチにダウンロードします。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*copy tftp://<server_ip_address>/CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr*
Mode.	TFTP
Set Server IP.	172.22.201.50
Path.	/
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr
File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. please wait...
Validating configuration script...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script validated.
File transfer operation completed successfully.
----
====
.. RCFがスイッチにダウンロードされたことを確認します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*script list*
Configuration Script Nam   Size(Bytes)
-------------------------- -----------
CN1610_CS_RCF_v1.1.scr            2191
CN1610_CS_RCF_v1.2.scr            2240
latest_config.scr                 2356

4 configuration script(s) found.
2039 Kbytes free.
----
====


. RCFをCN1610スイッチに適用します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*script apply CN1610_CS_RCF_v1.2.scr*
Are you sure you want to apply the configuration script? (y/n) *y*
...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script 'CN1610_CS_RCF_v1.2.scr' applied. Note that the script output will go to the console.
After the script is applied, those settings will be active in the running-config file. To save them to the startup-config file, you must use the write memory command, or if you used the reload answer yes when asked if you want to save the changes.
----
====
+
.. スイッチをリブートしたときにスタートアップコンフィギュレーションファイルになるように、実行コンフィギュレーションファイルを保存します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. イメージをCN1610スイッチにダウンロードします。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*copy tftp://<server_ip_address>/NetApp_CN1610_1.2.0.7.stk active*
Mode.	TFTP
Set Server IP.	tftp_server_ip_address
Path.	/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type.	Code
Destination Filename.	active

Management access will be blocked for the duration of the transfer

Are you sure you want to start? (y/n) *y*

TFTP Code transfer starting...

File transfer operation completed successfully.
----
====
.. スイッチをリブートして、新しいアクティブブートイメージを実行します。
+
手順6のコマンドで新しいイメージを反映するには、スイッチをリブートする必要があります。reloadコマンドを入力したあとに表示される応答には、2つのビューがあります。

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*reload*
The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved! System will now restart!
.
.
.
Cluster Interconnect Infrastructure

User:admin Password: (new_cs1) >*enable*
----
====
.. 保存したコンフィギュレーションファイルを古いスイッチから新しいスイッチにコピーします。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*copy tftp://<server_ip_address>/<filename>.scr nvram:script <filename>.scr*
----
====
.. 以前に保存した設定を新しいスイッチに適用します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*script apply <filename>.scr*
Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. 実行コンフィギュレーションファイルをスタートアップコンフィギュレーションファイルに保存します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) #*write memory*
----
====


. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。「 system node AutoSupport invoke -node * -type all -message MAINT= xh
+
_x_ は、メンテナンス時間の長さ（時間単位）です。

+
[NOTE]
====
AutoSupport メッセージはテクニカルサポートにこのメンテナンスタスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

====
. 新しいスイッチnew_cs1にadminユーザとしてログインし、ノードクラスタインターフェイス（ポート1~12）に接続されているすべてのポートをシャットダウンします。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
User:*admin*
Password:
(new_cs1) >*enable*
(new_cs1) #

(new_cs1) #*config*
(new_cs1)(config)#*interface 0/1-0/12*
(new_cs1)(interface 0/1-0/12)#*shutdown*
(new_cs1)(interface 0/1-0/12)#*exit*
(new_cs1) #*write memory*
----
====
. old_cs1スイッチに接続されているポートからクラスタLIFを移行します。
+
各クラスタLIFを現在のノードの管理インターフェイスから移行する必要があります。

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *set -privilege advanced*
cluster::> *network interface migrate -vserver <vserver_name> -lif <Cluster_LIF_to_be_moved> - sourcenode <current_node> -dest-node <current_node> -dest-port <cluster_port_that_is_UP>*
----
====
. すべてのクラスタLIFが各ノードの適切なクラスタポートに移動されていることを確認します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network interface show -role cluster*
----
====
. 交換したスイッチに接続されているクラスタポートをシャットダウンします。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node <node_name> -port <port_to_admin_down> -up-admin false*
----
====
. クラスタの健常性を確認
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. ポートが停止していることを確認します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node <node_name>*
----
====
. スイッチcs2で、ISLポート13~16をシャットダウンします。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2) #*config*
(cs2)(config)#*interface 0/13-0/16*
(cs2)(interface 0/13-0/16)#*shutdown*
(cs2) #*show port-channel 3/1*
----
====
. ストレージ管理者がスイッチを交換する準備ができているかどうかを確認します。
. すべてのケーブルをold_cs1スイッチから取り外し、new_cs1スイッチの同じポートに接続します。
. cs2スイッチで、ISLポート13~16を起動します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2) #*config*
(cs2)(config)#*interface 0/13-0/16*
(cs2)(interface 0/13-0/16)#*no shutdown*
----
====
. クラスタノードに関連付けられた新しいスイッチのポートを起動します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2) #*config*
(cs2)(config)#*interface 0/1-0/12*
(cs2)(interface 0/13-0/16)#*no shutdown*
----
====
. 単一のノードで、交換したスイッチに接続されているクラスタノードポートを起動し、リンクが稼働していることを確認します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node node1 -port <port_to_be_onlined> -up-admin true*
cluster::*> *network port show -role cluster*
----
====
. 同じノードで、手順25でポートに関連付けられているクラスタLIFをリバートします。
+
この例では、「Is Home」列がtrueの場合、node1のLIFが正常にリバートされています。

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver node1 -lif <cluster_lif_to_be_reverted>*
cluster::*> *network interface show -role cluster*
----
====
. 最初のノードのクラスタLIFが稼働していてホームポートにリバートされている場合は、手順25と26を繰り返してクラスタポートを起動し、クラスタ内の他のノードのクラスタLIFをリバートします。
. クラスタ内のノードに関する情報を表示します。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. 交換したスイッチのスタートアップコンフィギュレーションファイルと実行コンフィギュレーションファイルが正しいことを確認します。この構成ファイルは、手順1の出力と一致している必要があります。
+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1) >*enable*
(new_cs1) #*show running-config*
(new_cs1) #*show startup-config*
----
====
. ケースの自動作成を抑制した場合は、 AutoSupport メッセージを呼び出して作成を再度有効にします。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます


