---
permalink: switch-netapp-cn1610/task-migrate-from-a-switchless-cluster-fas22xx-systems-with-a-single-cluster-network-connection.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, fas22xx systems, single, network connection 
summary: FAS22xx システムが既存の 2 ノードスイッチレスクラスタにある場合、各コントローラモジュールにクラスタ接続用の単一のバックツーバック 10GbE 接続があるときは、スイッチレスクラスタネットワークオプションを使用して、スイッチ接続に直接バックツーバック接続を置き換えることができます。 
---
= 単一のクラスタネットワーク接続を使用して、 FAS22xx システムの 2 ノードスイッチクラスタに移行する
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS22xx システムが既存の 2 ノードスイッチレスクラスタにある場合、各コントローラモジュールにクラスタ接続用の単一のバックツーバック 10GbE 接続があるときは、スイッチレスクラスタネットワークオプションを使用して、スイッチ接続に直接バックツーバック接続を置き換えることができます。

.作業を開始する前に
* スイッチレス構成からスイッチを使用する構成に移行するには、 2 つのクラスタ接続が必要です。
* クラスタが正常に動作しており、バックツーバック接続で接続された 2 つのノードで構成されている必要があります。
* ノードで ONTAP 8.2 以降が実行されている必要があります。
* スイッチレスクラスタ機能は、ノードが 3 つ以上の場合は使用できません。
* すべてのクラスタポートは「 up 」状態である必要があります。


この手順 は無停止の手順 であり、スイッチレス環境における直接クラスタ接続を削除し、各スイッチへの接続をパートナーノードへの接続に置き換えます。

.手順
. 権限レベルを advanced に変更します。続行するかどうかを尋ねられたら、「 y 」と入力します。「 set -privilege advanced 」
+
詳細プロンプト (`*>') が表示されます

. どちらかのノードのシステム・コンソールで ' ノードのクラスタ・ステータスを確認します cluster show
+
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

+
[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
. いずれかのノードのシステム・コンソールで HA ペアのステータスを確認します storage failover show
+
次の例では、ノード 1 とノード 2 のステータスを表示します。

+
[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。「 system node AutoSupport invoke -node * -type all -message MAINT= xh
+
「 x 」は、メンテナンス時間の長さ（時間単位）です。

+

NOTE: このメンテナンスタスクについてテクニカルサポートに通知し、メンテナンス時間中はケースの自動作成が停止されます。

+
次のコマンドは、ケースの自動作成を 2 時間停止します。

+
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. スイッチレスクラスタの現在の状態が「 true 」であることを確認してから、スイッチレスクラスタモードを無効にします。「 network options switchless-cluster modify -enabled false
. ターゲットノードをテイクオーバーします。「 storage failover takeover -ofnode _target_node_name _ 」
+
どちらのノードがターゲットノードであるかは関係ありません。テイクオーバーされると ' ターゲット・ノードは自動的に再起動し ' Waiting for giveback... というメッセージが表示されます

+
テイクオーバーされたパートナー（ターゲット）ノードのデータをアクティブノードが提供しています。

. 障害ノードのテイクオーバー後 2 分待ち、テイクオーバーが完了したことを確認します。
. ターゲット・ノードに「 Waiting for giveback... 」というメッセージが表示された状態でシャットダウンします。
+
ノードをシャットダウンする方法は、ノードのサービスプロセッサ（ SP ）を使用したリモート管理を使用するかどうかによって異なります。

+
|===
| SP の場合 | 作業 


 a| 
が設定されている
 a| 
障害のあるノード SP にログインし ' システムの電源をオフにしますシステムの電源はオフにします



 a| 
が設定されていません
 a| 
障害ノードのプロンプトで 'Ctrl-C を押し 'y と入力してノードを停止します

|===
. 各コントローラモジュールで、 10GbE クラスタポートをスイッチレスクラスタに接続するケーブルを外します。
. 10GbE クラスタポートを両方のコントローラモジュールのスイッチに接続します。
. スイッチに接続されている 10GbE クラスタポートが同じ VLAN に含まれるように設定されていることを確認してください。
+
各コントローラモジュールのクラスタポートを異なるスイッチに接続する場合は、クラスタポートが各スイッチで接続されているポートが同じ VLAN に設定されていて、両方のスイッチでトランキングが適切に設定されていることを確認する必要があります。

. ターゲットノードにストレージをギブバックします。「 storage failover giveback -ofnode node2
. ギブバック操作の進行状況を監視します storage failover show-giveback
. ギブバック処理が完了したら、 HA ペアが正常で、テイクオーバーが可能であることを確認します。 storage failover show
+
次のような出力が表示されます。

+
[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
. クラスタポート LIF が正しく動作していることを確認します。「 network interface show -role cluster 」
+
次の例では、 LIF がノード 1 とノード 2 で「 up 」になっていて、「 Is Home 」列の結果が「 true 」であることを示します。

+
[listing]
----

cluster::*> network interface show -role cluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
node1
            clus1        up/up    192.168.177.121/24  node1        e1a     true
node2
            clus1        up/up    192.168.177.123/24  node2        e1a     true

2 entries were displayed.
----
. どちらかのノードのシステム・コンソールで ' ノードのクラスタ・ステータスを確認します cluster show
+
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

+
[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
. クラスタ・ポートに ping を実行し、クラスタ接続を確認します。「 cluster ping-cluster local 」
+
コマンドの出力には、すべてのクラスタポート間の接続が表示されます。

. ケースの自動作成を抑制した場合は、 AutoSupport メッセージを呼び出して作成を再度有効にします。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます

+
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
. 特権レベルを admin に戻します。 'et -privilege admin'


* 関連情報 *

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["ネットアップの技術情報アーティクル 1010449 ：「 How to suppress automatic case creation during scheduled maintenance windows"^]
