---
permalink: switch-netapp-cn1610/task-install-fastpath-software-and-rcfs-on-netapp-cluster-switch.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs, netapp cluster switch 
summary: NetApp CN1610 クラスタスイッチに FastPath ソフトウェアとリファレンス構成ファイル（ RCF ）をインストールする必要があります。 
---
= ネットアップクラスタスイッチに FastPath ソフトウェアと RCF をインストールします
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp CN1610 クラスタスイッチに FastPath ソフトウェアとリファレンス構成ファイル（ RCF ）をインストールする必要があります。

.作業を開始する前に
* クラスタが完全に機能している必要があります。
* クラスタネットワークインターフェイスカード（ NIC ）に欠陥がないこと、およびクラスタスイッチで接続されているすべてのポートが機能していることが必要です。
* すべてのクラスタポートが稼働している必要があります。
* クラスタのすべての論理インターフェイス（ LIF ）が稼働していて、移行されていない必要があります。
* ONTAP (privilege ： advanced ） 'cluster ping-cluster -node node1 コマンドは 'larger than PMTU communication がすべてのパスで成功したことを示す必要があります
* のスイッチ互換性の表を参照する必要があります http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 / CN1610 スイッチ"^] サポートされている FastPath 、 RCF 、および ONTAP のバージョンについては、ページを参照してください。
+
RCF バージョンと FastPath バージョンでは、コマンド構文間にコマンドの依存関係が存在する場合があります。




NOTE: RCF バージョン 1.2 では、セキュリティ上の理由から、 Telnet のサポートが明示的に無効になっています。RCF 1.2 のインストール時の接続の問題を回避するには、 Secure Shell （ SSH ）が有効になっていることを確認する必要があります。。 https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["『 NetApp ® CN1610 Switch Administrator's Guide 』"^] SSH の詳細については、を参照してください。

この手順の例では、スイッチとノードで次の命名法を使用しています。

* このドキュメントの手順では、 clustered Data ONTAP 8.2 の構文を使用しています。そのため、クラスタ SVM 、 LIF 名、および CLI 出力は Data ONTAP 8.3 の出力とは異なります。
* 2 つのネットアップスイッチは cs1 と cs2 です。
* 2 つのクラスタ LIF は clus1 と clus2 です。
* SVM は vs1 および vs2 です。
* 'cluster::*>' プロンプトは ' クラスタの名前を示します
* 各ノードのクラスタポートには、 e1a および e2a という名前が付けられます。
+
。 https://hwu.netapp.com/["Hardware Universe"^] 使用しているプラットフォームでサポートされている実際のクラスタポートに関する詳細情報が表示されます。

* ネットアップクラスタスイッチでサポートされているスイッチ間リンク（ ISL ）は、ポート 0/13~0/16 です。
* ネットアップクラスタスイッチでサポートされるノード接続は、ポート 0/1~0/12 です。


この手順 には 2 つの部分があります。

* link:task-install-fastpath-software.html["FastPath ソフトウェアをインストールします"] FastPath ソフトウェアのインストール方法について説明します。
* link:task-install-an-rcf-on-a-cn1610-switch.html["RCF を CN1610 スイッチにインストールします"] RCF のインストール方法について説明します。

