---
permalink: switch-netapp-cn1610/task-migrate-from-a-switchless-cluster-to-a-switched-netapp-cn1610-cluster-environment.html 
sidebar: sidebar 
keywords: migrate, switchless cluster environment, switched netapp cn1610 
summary: 既存の 2 ノードスイッチレスクラスタ環境を使用している場合は、 CN1610 クラスタネットワークスイッチを使用して 2 ノードスイッチクラスタ環境に移行し、 3 ノード以上に拡張することができます。 
---
= スイッチレスクラスタ環境から、スイッチを使用している NetApp CN1610 クラスタ環境への移行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存の 2 ノードスイッチレスクラスタ環境を使用している場合は、 CN1610 クラスタネットワークスイッチを使用して 2 ノードスイッチクラスタ環境に移行し、 3 ノード以上に拡張することができます。

.作業を開始する前に
2 ノードスイッチレス構成：

* 2 ノードスイッチレス構成が適切にセットアップされて機能している必要があります。
* ノードで ONTAP 8.2 以降が実行されている必要があります。
* すべてのクラスタポートは「 up 」状態である必要があります。
* すべてのクラスタ LIF は、 up 状態でホームポートにある必要があります。


CN1610 クラスタスイッチの構成：

* 両方のスイッチで CN1610 クラスタスイッチインフラが正常に機能していること。
* 両方のスイッチに管理ネットワーク接続が必要です。
* クラスタスイッチへのコンソールアクセスが必要です。
* CN1610 ノード間スイッチおよびスイッチ間接続では、 Twinax ケーブルまたはファイバケーブルを使用する必要があります。
+
。 https://hwu.netapp.com/["Hardware Universe"^] ケーブル接続の詳細については、を参照してください。

* スイッチ間リンク（ ISL ）ケーブルが、両方の CN1610 スイッチのポート 13~16 に接続されている必要があります。
* 両方の CN1610 スイッチの初期カスタマイズを完了しておく必要があります。
+
SMTP 、 SNMP 、 SSH など、以前のサイトのカスタマイズを新しいスイッチにコピーする必要があります。



.このタスクについて
この手順の例では、クラスタスイッチとノードで次の命名法を使用しています。

* CN1610 スイッチの名前は cs1 と cs2 です。
* LIF の名前は clus1 と clus2 です。
* ノードの名前は node1 と node2 になります。
* 'cluster::*>' プロンプトは ' クラスタの名前を示します
* この手順 で使用されるクラスタポートは、 e1a および e2a です。
+
。 https://hwu.netapp.com/["Hardware Universe"^] プラットフォームの実際のクラスタポートに関する最新情報が含まれます。



.手順
. 権限レベルを advanced に変更します。続行するかどうかを尋ねられたら、「 y 」と入力します。「 set -privilege advanced 」
+
advanced のプロンプト（ * > ）が表示されます。

. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。「 system node AutoSupport invoke -node * -type all -message MAINT= xh
+
_x_ は、メンテナンス時間の長さ（時間単位）です。

+

NOTE: AutoSupport メッセージはテクニカルサポートにこのメンテナンスタスクについて通知し、メンテナンス時間中はケースの自動作成が停止されます。

+
次のコマンドは、ケースの自動作成を 2 時間停止します。

+
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. 新しいクラスタスイッチ cs1 と cs2 の両方で、すべてのノード側ポート（ ISL ポートではない）を無効にします。
+
ISL ポートを無効にしないでください。

+
次の例は、スイッチ cs1 でノードに接続されたポート 1~12 が無効になっていることを示しています。

+
[listing]
----

(cs1)> enable
(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
+
次の例は、スイッチ cs2 でノード側のポート 1~12 が無効になっていることを示しています。

+
[listing]
----

(c2)> enable
(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
. 2 つの CN1610 クラスタスイッチ cs1 と cs2 間の ISL 上の ISL ポートと物理ポートが up になっていることを確認します：「 show port-channel'
+
次の例は、スイッチ cs1 上の ISL ポートが「 up 」になっていることを示しています。

+
[listing]
----

(cs1)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
+
次の例は、スイッチ cs2 上の ISL ポートが up になっていることを示しています。

+
[listing]
----

(cs2)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
. 隣接デバイスのリストを表示します。「 show isdpneighbors
+
このコマンドは、システムに接続されているデバイスに関する情報を提供します。

+
次の例は、スイッチ cs1 上の隣接デバイスを示しています。

+
[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16
----
+
次の例は、スイッチ cs2 上の隣接デバイスを表示します。

+
[listing]
----

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
. クラスタ・ポートの一覧を表示します。「 network port show 」を参照してください
+
次の例は、使用可能なクラスタポートを示しています。

+
[listing]
----

cluster::*> network port show -ipspace Cluster
Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false
12 entries were displayed.
----
. 各クラスタポートがパートナークラスタノードの対応するポートに接続されていることを確認します。「 run * cdpd show-neighbors
+
次の例は、クラスタポート e1a と e2a が、クラスタパートナーノードの同じポートに接続されていることを示しています。

+
[listing]
----

cluster::*> run * cdpd show-neighbors
2 entries were acted on.

Node: node1
Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node2           e1a                    FAS3270           137   H
e2a    node2           e2a                    FAS3270           137   H


Node: node2

Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node1           e1a                    FAS3270           161   H
e2a    node1           e2a                    FAS3270           161   H
----
. すべてのクラスタ LIF が「 up 」で動作していることを確認します。「 network interface show -vserver Cluster
+
各クラスタ LIF の列には 'Is Home` が表示されます

+
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up      10.10.10.1/16 node1         e1a     true
            clus2      up/up      10.10.10.2/16 node1         e2a     true
node2
            clus1      up/up      10.10.11.1/16 node2         e1a     true
            clus2      up/up      10.10.11.2/16 node2         e2a     true

4 entries were displayed.
----
+

NOTE: 手順 10~13 の変更コマンドと移行コマンドはローカルノードで実行する必要があります。

. すべてのクラスタ・ポートが up になっていることを確認します network port show -ipspace Cluster
+
[listing]
----
cluster::*> network port show -ipspace Cluster

                                       Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link  MTU   Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ----- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. クラスタ LIF clus1 では「 -auto-revert 」パラメータを「 false 」に設定し、両方のノードでは clus2 を「 network interface modify 」に設定します
+
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert false
----
+

NOTE: リリース 8.3 以降では、次のコマンドを使用します。 network interface modify -vserver Cluster -lif * -auto-giveback false

. クラスタ・ポートに ping を実行し、クラスタ接続を確認します。「 cluster ping-cluster local 」
+
コマンドの出力には、すべてのクラスタポート間の接続が表示されます。

. 各ノードのコンソールで、 clus1 をポート e2a に移行します。「 network interface migrate
+
次の例は、 node1 と node2 のポート e2a に clus1 を移行するプロセスを示しています。

+
[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus1 -source-node node1 -dest-node node1 -dest-port e2a
cluster::*> network interface migrate -vserver node2 -lif clus1 -source-node node2 -dest-node node2 -dest-port e2a
----
+

NOTE: リリース 8.3 以降では、次のコマンドを使用します。 network interface migrate -vserver Cluster -lif clus1 -destination-node node1 -destination-port e2a

. 移行が実行されたことを確認します。「 network interface show -vserver Cluster 」
+
次の例は、 clus1 が node1 と node2 のポート e2a に移行されていることを確認します。

+
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e2a     false
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e2a     false
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
. 両方のノードのクラスタ・ポート e1a をシャットダウンします： network port modify
+
次の例は、 node1 と node2 のポート e1a をシャットダウンします。

+
[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin false
cluster::*> network port modify -node node2 -port e1a -up-admin false
----
. ポートのステータスを確認します。「 network port show 」
+
次の例では、ポート e1a が node1 と node2 の「 down 」状態になっています。

+
[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. ノード 1 のクラスタポート e1a からケーブルを外し、 e1a をクラスタスイッチ cs1 のポート 1 に接続します。 CN1610 スイッチでサポートされている適切なケーブル接続を使用します。
+
。 link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^] ケーブル接続の詳細については、を参照してください。

. ノード 2 のクラスタポート e1a からケーブルを外し、次に e1a をクラスタスイッチ cs1 のポート 2 に接続します。 CN1610 スイッチでサポートされている適切なケーブル接続を使用します。
. クラスタスイッチ cs1 のすべてのノード側ポートを有効にします。
+
次の例は、スイッチ cs1 でポート 1~12 が有効になっていることを示しています。

+
[listing]
----

(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# no shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
. 各ノードの最初のクラスタポート e1a を有効にします。「 network port modify 」
+
次の例は、 node1 と node2 のポート e1a を有効にします。

+
[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin true
cluster::*> network port modify -node node2 -port e1a -up-admin true
----
. すべてのクラスタ・ポートが up になっていることを確認します： network port show -ipspace Cluster
+
次の例は、ノード 1 とノード 2 のすべてのクラスタポートが「 up 」になっていることを示しています。

+
[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. clus1 （以前に移行したもの）を両方のノードの e1a にリバートします。「 network interface revert
+
次の例は、 clus1 をノード 1 とノード 2 のポート e1a にリバートする方法を示しています。

+
[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus1
cluster::*> network interface revert -vserver node2 -lif clus1
----
+

NOTE: リリース 8.3 以降では、次のコマンドを使用します。 network interface revert -vserver Cluster -lif <nodename_clus<N>`

. すべてのクラスタ LIF が「 Is Home 」列に「 up 」であり、運用可能で、「 true 」と表示されていることを確認します。「 network interface show -vserver Cluster
+
次の例では、すべての LIF がノード 1 とノード 2 で「 up 」であり、「 Is Home 」列の結果が「 true 」であることを示します。

+
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
. クラスタ内のノードのステータスに関する情報を表示します
+
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

+
[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
. 各ノードのコンソールで、 clus2 をポート e1a に移行します。「 network interface migrate
+
次の例は、 clus2 をノード 1 とノード 2 のポート e1a に移行するプロセスを示しています。

+
[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus2 -source-node node1 -dest-node node1 -dest-port e1a
cluster::*> network interface migrate -vserver node2 -lif clus2 -source-node node2 -dest-node node2 -dest-port e1a
----
+

NOTE: リリース 8.3 以降の場合は、次のコマンドを使用します。 network interface migrate -vserver Cluster -lif node1_clus2 -dest-node node1 -dest-port e1a

. 移行が実行されたことを確認します。「 network interface show -vserver Cluster 」
+
次の例では、 clus2 が node1 と node2 のポート e1a に移行されていることを確認しています。

+
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e1a     false
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e1a     false

4 entries were displayed.
----
. 両方のノードで、クラスタポート e2a をシャットダウンします。「 network port modify 」
+
次の例は、 node1 と node2 のポート e2a をシャットダウンする方法を示しています。

+
[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
. ポートのステータスを確認します。「 network port show 」
+
次の例は、 node1 と node2 のポート e2a が「 down 」になっていることを示しています。

+
[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. ノード 1 のクラスタポート e2a からケーブルを外し、 CN1610 スイッチでサポートされている適切なケーブル接続に従って、クラスタスイッチ cs2 のポート 1 に e2a を接続します。
. ノード 2 のクラスタポート e2a からケーブルを外し、 CN1610 スイッチでサポートされている適切なケーブル接続に従って、クラスタスイッチ cs2 のポート 2 に e2a を接続します。
. クラスタスイッチ cs2 のすべてのノード側ポートを有効にします。
+
次の例は、スイッチ cs2 でポート 1~12 が有効になっていることを示しています。

+
[listing]
----

(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# no shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
. 各ノードで 2 つ目のクラスタポート e2a を有効にします。
+
次の例は、 node1 と node2 のポート e2a を有効にする方法を示しています。

+
[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
. すべてのクラスタ・ポートが up になっていることを確認します： network port show -ipspace Cluster
+
次の例は、ノード 1 とノード 2 のすべてのクラスタポートが「 up 」になっていることを示しています。

+
[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. clus2 （以前に移行されたもの）を両方のノードの e2a にリバートします。「 network interface revert
+
次の例は、 node1 と node2 のポート e2a に clus2 をリバートする方法を示しています。

+
[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
+

NOTE: リリース 8.3 以降のコマンドは、「 cluster ：： * > network interface revert -vserver Cluster -lif node1_clus2 」および「 cluster ： * > network interface revert -vserver Cluster -lif node2_clus2 」です

. すべてのインターフェイスで、 Is Home 列に「 true 」と表示されていることを確認します。「 network interface show -vserver Cluster
+
次の例では、すべての LIF がノード 1 とノード 2 で「 up 」であり、「 Is Home 」列の結果が「 true 」であることを示します。

+
[listing]
----

cluster::*> network interface show -vserver Cluster

             Logical    Status     Network            Current     Current Is
Vserver      Interface  Admin/Oper Address/Mask       Node        Port    Home
-----------  ---------- ---------- ------------------ ----------- ------- ----
node1
             clus1      up/up      10.10.10.1/16      node1       e1a     true
             clus2      up/up      10.10.10.2/16      node1       e2a     true
node2
             clus1      up/up      10.10.11.1/16      node2       e1a     true
             clus2      up/up      10.10.11.2/16      node2       e2a     true
----
. クラスタ・ポートに ping を実行し、クラスタ接続を確認します。「 cluster ping-cluster local 」
+
コマンドの出力には、すべてのクラスタポート間の接続が表示されます。

. 両方のノードがそれぞれのスイッチに 2 つの接続されていることを確認します。「 show isdpneighbors 」
+
次の例は、両方のスイッチの該当する結果を示しています。

+
[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e1a
node2                  0/2          163       H            FAS3270   e1a
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e2a
node2                  0/2          163       H            FAS3270   e2a
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
. 構成内のデバイスに関する情報を表示します。「 network device discovery show
. advanced 権限のコマンド「 network options detect-switchless modify 」を使用して、両方のノードで 2 ノードのスイッチレス構成設定を無効にします
+
次に、スイッチレスコンフィギュレーション設定をディセーブルにする例を示します。

+
[listing]
----

cluster::*> network options detect-switchless modify -enabled false
----
+

NOTE: リリース 9.2 以降では、設定が自動的に変換されるため、この手順は省略してください。

. 設定が無効になっていることを確認します。「 network options detect-switchless -cluster show 」
+
次の例では 'false' の出力は ' 構成設定が無効になっていることを示しています

+
[listing]
----

cluster::*> network options detect-switchless-cluster show
Enable Switchless Cluster Detection: false
----
+

NOTE: リリース 9.2 以降では 'Enable Switchless Cluster' が false に設定されるまで待ちますこれには 3 分程度かかる場合があります。

. 各ノードでクラスタ clus1 と clus2 を自動リバートするように設定し、確認します。
+
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert true
----
+

NOTE: リリース 8.3 以降では、次のコマンドを使用します。 network interface modify -vserver Cluster -lif * -auto-revert true クラスタ内のすべてのノードで自動リバートを有効にします。

. クラスタ内のノード・メンバーのステータスを確認します cluster show
+
次の例は、クラスタ内のノードの健全性と参加資格に関する情報を表示します。

+
[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
. ケースの自動作成を抑制した場合は、 AutoSupport メッセージを呼び出して作成を再度有効にします。
+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます

+
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
. 特権レベルを admin に戻します。 'et -privilege admin'


* 関連情報 *

http://hwu.netapp.com["Hardware Universe"^]

http://support.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 / CN1610 の概要 ページ"^]

https://library.netapp.com/ecm/ecm_download_file/ECMP1118645["『 CN1601 and CN1610 Switch Setup and Configuration Guide 』"^]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["ネットアップの技術情報アーティクル 1010449 ：「 How to suppress automatic case creation during scheduled maintenance windows"^]
