---
permalink: get-started/learn-switch-concept.html 
sidebar: sidebar 
keywords:  
summary: クラスター、ストレージ、共有スイッチについて学習します。 
---
= ONTAPシステムスイッチについて
:allow-uri-read: 


[role="lead"]
ONTAPは、AFXシステム、クラスタ、ストレージ、および共有スイッチを提供し、クラスタ全体でデータやネットワークインターフェースを無停止で移動できる内部通信を実現します。

「フロントエンド」スイッチはホスト ストレージへの接続を提供し、「バックエンド」クラスタ スイッチは 2 つ以上のNetAppコントローラ間の接続を提供します。


NOTE: NetApp認定のバックエンド スイッチ ( NetAppから注文) のみがサポートされます。


CAUTION: スイッチをアップグレードする場合は、NetApp では、最初に ONTAP ソフトウェアのアップグレードを完了してから、スイッチのソフトウェアアップグレードを実行することをお勧めします。



[[afx-systems-switches]]
== AFXシステムスイッチ

AFXシステムスイッチを使用すると、高速でエネルギー効率が高く、省スペースなネットワーク スイッチを構築できます。小型でポート密度が高いため、大規模ネットワークの処理に最適です。これらのポートは様々な速度に対応しており、複数の接続に分割することも可能です。NetAppがサポートするAFXシステムスイッチは以下のとおりです：

* Cisco Nexus 9808
* Cisco Nexus 9332D-GX2B
* Cisco Nexus 9364D-GX2A




[[cluster-switches]]
== クラスタースイッチ

クラスタ スイッチを使用すると、2 つ以上のノードを持つONTAPクラスタを構築できます。NetAppがサポートするクラスタ スイッチには次のものがあります。

* Broadcom BES-53248
* Cisco Nexus 9336C-FX2




[[storage-switches]]
== ストレージ スイッチ

ストレージ スイッチを使用すると、ストレージ エリア ネットワーク (SAN) 内のサーバーとストレージ アレイ間でデータをルーティングできます。  NetAppがサポートするストレージ スイッチには次のものがあります。

* Cisco Nexus 9336C-FX2




[[shared-switches]]
== 共有スイッチ

共有スイッチでは、共有クラスタおよびストレージ RCF の使用をサポートすることで、クラスタとストレージの機能を共有スイッチ構成に組み合わせることができます。  NetAppがサポートする共有スイッチは次のとおりです。

* Cisco Nexus 9336C-FX2




[[end-of-availability-switches]]
== 販売終了スイッチ

販売終了となったものの、引き続きサポート対象となっているスイッチの一覧については、link:../eoa/index.html["販売終了スイッチ"]を参照してください。
