---
permalink: get-started/learn-switch-concept.html 
sidebar: sidebar 
keywords:  
summary: クラスター、ストレージ、共有スイッチについて学習します。 
---
= クラスタ、ストレージ、共有スイッチについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp は、クラスタ全体でデータとネットワーク インターフェイスを中断なく移動できる機能を備えた内部通信を実現するクラスタ、ストレージ、共有スイッチを提供します。

「フロントエンド」スイッチはホスト ストレージへの接続を提供し、「バックエンド」クラスタ スイッチは 2 つ以上のNetAppコントローラ間の接続を提供します。


NOTE: NetApp認定のバックエンド スイッチ ( NetAppから注文) のみがサポートされます。



== クラスタースイッチ

クラスタ スイッチを使用すると、2 つ以上のノードを持つONTAPクラスタを構築できます。NetAppがサポートするクラスタ スイッチには次のものがあります。

* Broadcom BES-53248
* Cisco Nexus 9336C-FX2
* NVIDIA SN2100




== ストレージ スイッチ

ストレージ スイッチを使用すると、ストレージ エリア ネットワーク (SAN) 内のサーバーとストレージ アレイ間でデータをルーティングできます。  NetAppがサポートするストレージ スイッチには次のものがあります。

* Cisco Nexus 9336C-FX2
* NVIDIA SN2100




== 共有スイッチ

共有スイッチでは、共有クラスタおよびストレージ RCF の使用をサポートすることで、クラスタとストレージの機能を共有スイッチ構成に組み合わせることができます。  NetAppがサポートする共有スイッチは次のとおりです。

* Cisco Nexus 9336C-FX2




== 販売終了

次のストレージ スイッチは購入できなくなりましたが、引き続きサポートされています。

* Cisco Nexus 3232C
* Cisco Nexus 3132Q-V
* Cisco Nexus 92300YC
* NetApp CN1610

