---
permalink: get-started/learn-switch-concept.html 
sidebar: sidebar 
keywords:  
summary: クラスタ、ストレージ、および共有スイッチについて説明します。 
---
= クラスタスイッチ、ストレージスイッチ、共有スイッチについて説明します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットアップでは、クラスタ、ストレージ、および共有スイッチを提供し、クラスタ内でデータやネットワークインターフェイスを無停止で移動できます。

「フロントエンド」スイッチはホストストレージへの接続を提供し、「バックエンド」クラスタスイッチは2台以上のネットアップコントローラ間の接続を提供します。


NOTE: ネットアップが検証したバックエンドスイッチ（NetAppから発注）のみがサポートされます。



== クラスタスイッチ

クラスタスイッチでは、3つ以上のノードでONTAP クラスタを構築できます。ネットアップがサポートしているクラスタスイッチは次のとおりです。

* Broadcom BES-53248 の場合
* Cisco Nexus 9336C-FX2
* NVIDIA SN2100




== ストレージスイッチ

ストレージスイッチを使用すると、SAN（ストレージエリアネットワーク）内のサーバとストレージアレイの間でデータをルーティングできます。ネットアップがサポートしているクラスタスイッチは次のとおりです。

* Cisco Nexus 9336C-FX2
* NVIDIA SN2100




== 共有スイッチ

共有スイッチを使用すると、クラスタとストレージの機能を共有スイッチ構成に組み合わせることができ、共有クラスタとストレージのRCFを使用できます。ネットアップがサポートする共有スイッチは次のとおりです。

* Cisco Nexus 9336C-FX2




== 販売終了

次のストレージスイッチは、購入できなくなりましたが、引き続きサポートされます。

* Cisco Nexus 3232C
* Cisco Nexus 3132Q-V の 2 つのポートを設定します
* Cisco Nexus 92300YC
* NetApp CN1610

