---
permalink: switch-cisco-92300/92300-overview.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: 3 つ以上のノードで ONTAP クラスタを構築する場合は、サポートされている 2 つのクラスタネットワークスイッチが必要です。オプションとして、追加の管理スイッチを使用できます。 
---
= Cisco Nexus 92300YC スイッチの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
3 つ以上のノードで ONTAP クラスタを構築する場合は、サポートされている 2 つのクラスタネットワークスイッチが必要です。オプションとして、追加の管理スイッチを使用できます。

Cisco Nexus 92300YC スイッチ（ X190003/R ）は、スイッチに付属の標準ブラケットを使用して、ネットアップシステムキャビネットまたはサードパーティ製キャビネットに設置できます。

次の表に、 92300YC スイッチ、ファン、および電源装置のパーツ番号と概要を示します。

[cols="1,2"]
|===
| パーツ番号 | 説明 


 a| 
190003
 a| 
Cisco 92300YC 、 CLSW 、 48Pt10/25GB 、 18Pt100G 、 PTSX （ PTSX はポート側排気）



 a| 
190003R
 a| 
Cisco 92300YC 、 CLSW 、 48Pt10/25GB 、 18Pt100G 、 PSIN （ PSIN はポート側吸気）



 a| 
X-NXA-FAN-35CFM-B
 a| 
ファン、 Cisco N9K ポート側吸気



 a| 
X-NXA-FAN-35CFF-F
 a| 
ファン、 Cisco N9K ポート側排気



 a| 
X-NXA-PAC-650W-B
 a| 
電源装置、 Cisco 650W ポート側吸気



 a| 
X-NXA-PAC-650W-F
 a| 
電源装置、 Cisco 650W ポート側排気

|===
Cisco Nexus 92300YC スイッチの通気の詳細：

* ポート側排気（標準エア） - 冷気はコールドアイル内のファンモジュールと電源装置モジュールを介してシャーシに入り、ホットアイル内のシャーシのポート側から排気されます。ポート側排気は青色で示されています。
* ポート側吸気（リバースエア） - 冷気はコールドアイル内のポート側からシャーシに入り、ホットアイル内のファンモジュールと電源装置モジュールから排気されます。ポート側吸気は赤紫色で示されています。


.参照可能なドキュメント
次の表に、 Cisco Nexus 92300YC スイッチで使用できるドキュメントを示します。

|===


| タイトル | 説明 


 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-overview-cisco-92300.html["_ Cisco ® Nexus 92300YC クラスタスイッチをセットアップします"^]
 a| 
Cisco Nexus 92300YC クラスタスイッチをセットアップおよび設定する方法について説明します。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-nxos-overview.html["NX-OS および RCF をインストールします _"^]
 a| 
Nexus 92300YC クラスタスイッチに NX-OS とリファレンス構成ファイル（ RCF ）をインストールする方法について説明します。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/configure-install-initial.html["新しい Cisco Nexus 92300YC スイッチを構成 _"^]
 a| 
古い Cisco スイッチを使用する環境から Cisco 92300YC スイッチを使用する環境に移行する方法について説明します。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-92300yc-overview.html["_ 古い Cisco スイッチから Cisco Nexus 92300YC スイッチに移行 _"^]
 a| 
古い Cisco スイッチを Cisco Nexus 92300YC クラスタスイッチに交換する手順 について説明します。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-2n-switched.html["_ 2 ノードスイッチレスクラスタからの移行 _"^]
 a| 
2 ノードスイッチレスクラスタ環境から Cisco Nexus 92300YC クラスタスイッチを使用した 2 ノードスイッチ環境に移行する方法について説明します。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/replace-92300yc.html["_ Cisco Nexus 92300YC クラスタスイッチを交換します _"^]
 a| 
クラスタ内の障害のある Cisco Nexus 92300YC スイッチを交換し、スイッチのオペレーティングシステムとリファレンス構成ファイルをダウンロードするための手順 について説明します。

|===