---
permalink: switch-cisco-92300/92300-overview.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: 2 つ以上のノードを持つONTAPクラスターを構築する場合は、サポートされているクラスター ネットワーク スイッチが 2 つ必要です。オプションとして追加の管理スイッチを使用することもできます。 
---
= Cisco Nexus 92300YC スイッチの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
2 つ以上のノードを持つONTAPクラスターを構築する場合は、サポートされているクラスター ネットワーク スイッチが 2 つ必要です。オプションとして追加の管理スイッチを使用することもできます。

Cisco Nexus 92300YC スイッチ (X190003/R) は、スイッチに付属の標準ブラケットを使用して、 NetAppシステム キャビネットまたはサードパーティ製キャビネットに設置できます。

次の表に、92300YC スイッチ、ファン、および電源装置の部品番号と説明を示します。

[cols="1,2"]
|===
| 部品番号 | 説明 


 a| 
190003
 a| 
Cisco 92300YC、CLSW、48Pt10/25GB、18Pt100G、PTSX（PTSX = ポート側排気）



 a| 
190003R
 a| 
Cisco 92300YC、CLSW、48Pt10/25GB、18Pt100G、PSIN（PSIN = ポート側吸気）



 a| 
X-NXA-ファン-35CFM-B
 a| 
ファン、 Cisco N9K ポート側吸気エアフロー



 a| 
X-NXA-ファン-35CFM-F
 a| 
ファン、 Cisco N9K ポート側排気エアフロー



 a| 
X-NXA-PAC-650W-B
 a| 
電源、 Cisco 650W - ポート側吸気



 a| 
X-NXA-PAC-650W-F
 a| 
電源、 Cisco 650W - ポート側排気

|===
Cisco Nexus 92300YC スイッチのエアフローの詳細:

* ポート側排気エアフロー (標準空気) - 冷気はコールドアイルのファンと電源モジュールからシャーシ内に入り、ホットアイルのシャーシのポート端から排出されます。青色の左舷排気流。
* ポート側吸気エアーフロー (逆流) - 冷気はコールドアイルのポート端からシャーシに入り、ホットアイルのファンと電源モジュールから排出されます。バーガンディ色のポート側吸気エアフロー。


.利用可能なドキュメント
次の表に、 Cisco Nexus 92300YC スイッチに関するドキュメントを示します。

|===


| タイトル | 説明 


 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-overview-cisco-92300.html["Cisco® Nexus 92300YC クラスタ スイッチのセットアップ_"^]
 a| 
Cisco Nexus 92300YC クラスタ スイッチをセットアップおよび構成する方法について説明します。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-nxos-overview.html["_NX-OS とリファレンス コンフィギュレーション ファイル (RCF) のインストール_"^]
 a| 
Nexus 92300YC クラスタ スイッチに NX-OS と参照構成ファイル (RCF) をインストールする方法について説明します。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/configure-install-initial.html["_新しいCisco Nexus 92300YCスイッチの設定_"^]
 a| 
古いCiscoスイッチを使用している環境からCisco 92300YC スイッチを使用している環境に移行する方法について説明します。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-92300yc.html["_古いCiscoスイッチからCisco Nexus 92300YC スイッチへの移行_"^]
 a| 
古いCiscoスイッチをCisco Nexus 92300YC クラスタ スイッチに置き換える手順について説明します。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-2n-switched.html["_2ノードのスイッチレス クラスタからの移行_"^]
 a| 
Cisco Nexus 92300YC クラスタ スイッチを使用して、2 ノード スイッチレス クラスタ環境から 2 ノード スイッチ環境に移行する方法について説明します。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/replace-92300yc.html["Cisco Nexus 92300YC クラスタ スイッチの交換_"^]
 a| 
クラスタ内の故障したCisco Nexus 92300YC スイッチを交換し、スイッチのオペレーティング システムと参照設定ファイルをダウンロードする手順について説明します。

|===