---
permalink: switch-cisco-92300/components-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Cisco Nexus 92300YC クラスタスイッチのコンポーネントと部品番号を特定し、ハードウェアの設置および継続的なメンテナンスをサポートします。 
---
= Cisco Nexus 92300YC クラスタスイッチのコンポーネントと部品番号を確認してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ハードウェアの設置および継続的なメンテナンスをサポートするために、Cisco Nexus 92300YC クラスタスイッチのコンポーネントと部品番号を確認してください。詳細については、link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^]を参照してください。スイッチの設置要件の詳細については、link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["HWU にない機器をインストールするには、どのような追加情報が必要ですか?"^]を参照してください。

以下の表は、92300YC スイッチ、ファン、および電源装置の部品番号と説明を示しています。

[cols="1,2"]
|===
| 部品番号 | 説明 


 a| 
190003
 a| 
Cisco 92300YC、CLSW、48Pt10/25GB、18Pt100G、PTSX（PTSX = Port Side Exhaust）



 a| 
190003Rを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
Cisco 92300YC、CLSW、48Pt10/25GB、18Pt100G、PSIN (PSIN = Port Side Intake)



 a| 
X-NXA-FAN-35CFM-Bを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
ファン、Cisco N9K ポート側吸気エアフロー



 a| 
X-NXA-FAN-35CFM-Fを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
ファン、Cisco N9K ポート側排気エアフロー



 a| 
X-NXA-PAC-650W-Bを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
電源、Cisco 650W - ポート側吸気



 a| 
X-NXA-PAC-650W-Fを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
電源、Cisco 650W - ポート側排気

|===
Cisco Nexus 92300YC スイッチのエアフローの詳細：

* ポート側排気気流（標準空気）-- 冷たい空気は、コールドアイルのファンおよび電源モジュールを通じてシャーシ内に流入し、ホットアイルのシャーシのポート端から排気されます。青色で示されたポート側排気気流。
* ポート側吸気流（逆流） — 冷たい空気は、コールドアイルのポート端からシャーシに入り、ホットアイルのファンと電源モジュールから排出されます。バーガンディ色のポート側吸気流。


.次の手順
コンポーネントと部品番号を確認したら、link:required-documentation-92300.html["必要な書類"]を確認できます。
