---
permalink: switch-cisco-92300/components-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: 2 つ以上のノードを持つONTAPクラスターを構築する場合は、サポートされているクラスター ネットワーク スイッチが 2 つ必要です。オプションとして追加の管理スイッチを使用することもできます。 
---
= Cisco Nexus 92300YC スイッチのコンポーネントと部品番号
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 92300YC スイッチのインストールとメンテナンスについては、すべてのスイッチ コンポーネントと部品番号を必ず確認してください。参照 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^]詳細については。見る link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["HWU にない機器をインストールするには、どのような追加情報が必要ですか?"^] スイッチのインストール要件の詳細については、こちらをご覧ください。

次の表に、92300YC スイッチ、ファン、および電源装置の部品番号と説明を示します。

[cols="1,2"]
|===
| 部品番号 | 説明 


 a| 
190003
 a| 
Cisco 92300YC、CLSW、48Pt10/25GB、18Pt100G、PTSX（PTSX = ポート側排気）



 a| 
190003R
 a| 
Cisco 92300YC、CLSW、48Pt10/25GB、18Pt100G、PSIN（PSIN = ポート側吸気）



 a| 
X-NXA-ファン-35CFM-B
 a| 
ファン、 Cisco N9K ポート側吸気エアフロー



 a| 
X-NXA-ファン-35CFM-F
 a| 
ファン、 Cisco N9K ポート側排気エアフロー



 a| 
X-NXA-PAC-650W-B
 a| 
電源、 Cisco 650W - ポート側吸気



 a| 
X-NXA-PAC-650W-F
 a| 
電源、 Cisco 650W - ポート側排気

|===
Cisco Nexus 92300YC スイッチのエアフローの詳細:

* ポート側排気気流 (標準空気) - 冷気はコールドアイルのファンと電源モジュールからシャーシ内に入り、ホットアイルのシャーシのポート端から排出されます。青色の左舷排気流。
* ポート側吸気エアーフロー (逆流) - 冷気はコールドアイルのポート端からシャーシに入り、ホットアイルのファンと電源モジュールから排出されます。バーガンディ色のポート側吸気エアフロー。


.次の手順
コンポーネントと部品番号を確認したら、 link:required-documentation-92300.html["必要な書類"]。
