---
permalink: switch-cisco-92300/configure-reqs-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: インストールまたはアップグレードの前に、Cisco Nexus 92300YC クラスタスイッチの構成要件を確認してください。 
---
= Cisco Nexus 92300YC クラスタスイッチの構成要件を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インストールまたはアップグレードの前に、Cisco Nexus 92300YC クラスタスイッチの構成要件を確認してください。

2 つ以上のノードを持つONTAPクラスターを構築する場合は、サポートされているクラスター ネットワーク スイッチが 2 つ必要です。オプションとして追加の管理スイッチを使用することもできます。



[[configuration-requirements]]
== 構成要件

クラスターを構成するには、スイッチに適した本数と種類のケーブルおよびケーブルコネクタが必要です。最初に設定するスイッチの種類に応じて、付属のコンソールケーブルを使用してスイッチのコンソールポートに接続する必要があります。また、特定のネットワーク情報も提供する必要があります。



[[network-requirements]]
== ネットワーク要件

すべてのスイッチ構成には、以下のネットワーク情報が必要です。

* 管理ネットワークトラフィック用の IP サブネット
* 各ストレージ システム コントローラおよび該当するすべてのスイッチのホスト名と IP アドレス
* ほとんどのストレージシステムコントローラは、イーサネットサービスポート（レンチのアイコン）に接続することで、e0Mインターフェースを介して管理されます。AFF A800 および AFF A700 システムでは、e0Mインターフェースは専用のイーサネットポートを使用します。


.関連情報
* スイッチポートの詳細については、link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^]を参照してください。
* スイッチの設置要件の詳細については、link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["HWU にない機器をインストールするには、どのような追加情報が必要ですか?"^]を参照してください。


.次の手順
構成要件を確認したら、link:components-92300.html["コンポーネントと部品番号"]を確定できます。
