---
permalink: switch-cisco-92300/configure-reqs-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: 2 つ以上のノードを持つONTAPクラスターを構築する場合は、サポートされているクラスター ネットワーク スイッチが 2 つ必要です。オプションとして追加の管理スイッチを使用することもできます。 
---
= Cisco Nexus 92300YCスイッチの構成要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 92300YC スイッチのインストールとメンテナンスについては、すべての構成とネットワーク要件を必ず確認してください。

2 つ以上のノードを持つONTAPクラスターを構築する場合は、サポートされているクラスター ネットワーク スイッチが 2 つ必要です。オプションとして追加の管理スイッチを使用することもできます。



== 構成要件

クラスターを構成するには、スイッチに適した数と種類のケーブルおよびケーブル コネクタが必要です。最初に設定するスイッチのタイプに応じて、付属のコンソール ケーブルを使用してスイッチのコンソール ポートに接続する必要があります。また、特定のネットワーク情報も提供する必要があります。



== ネットワーク要件

すべてのスイッチ構成には次のネットワーク情報が必要です。

* 管理ネットワークトラフィック用の IP サブネット
* 各ストレージ システム コントローラおよび該当するすべてのスイッチのホスト名と IP アドレス
* ほとんどのストレージ システム コントローラは、イーサネット サービス ポート (レンチ アイコン) に接続して e0M インターフェイスを介して管理されます。AFF A800およびAFF A700システムでは、e0M イ​​ンターフェイスは専用のイーサネット ポートを使用します。


参照 https://hwu.netapp.com["Hardware Universe"^]最新情報についてはこちらをご覧ください。見る link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["HWU にない機器をインストールするには、どのような追加情報が必要ですか?"^] スイッチのインストール要件の詳細については、こちらをご覧ください。

.次の手順
構成要件を確認した後、 link:components-92300.html["コンポーネントと部品番号"]。
