---
permalink: switch-cisco-92300/install-switch-92300yc.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 92300YC 
summary: Cisco Nexus 92300YC スイッチをインストールするには、次の手順に従ってください。 
---
= 92300YCクラスタスイッチをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この手順 に従って、Cisco Nexus 92300YCスイッチをセットアップおよび設定します。

.作業を開始する前に
次のものがあることを確認します。

* インストールサイトのHTTPサーバ、FTPサーバ、またはTFTPサーバにアクセスし、該当するNX-OSおよびRCFリリースをダウンロードします。
* 該当するNX-OSバージョン（からダウンロード） https://software.cisco.com/download/home["シスコソフトウェアのダウンロード"^] ページ
* 該当するライセンス、ネットワークおよび設定情報、ケーブル。
* 完了link:setup-worksheet-92300yc.html["ケーブル接続ワークシート"]。
* 該当するネットアップクラスタネットワークと管理ネットワークのRCFをNetApp Support Site からダウンロードしました http://mysupport.netapp.com/["mysupport.netapp.com"^]。すべての Cisco クラスタネットワークスイッチおよび管理ネットワークスイッチは、シスコの工場出荷時のデフォルト設定で出荷されます。これらのスイッチには、 NX-OS ソフトウェアの最新バージョンもありますが、 RCF はロードされていません。
* link:required-documentation-92300.html["必要なスイッチとONTAP のドキュメント"] 。


.手順
. クラスタネットワークと管理ネットワークのスイッチとコントローラをラックに設置します。
+
[cols="1,2"]
|===
| インストール対象 | 作業 


 a| 
NetAppシステムキャビネット内のCisco Nexus 92300YC
 a| 
NetAppキャビネットにスイッチをインストールする手順については、『 NetAppキャビネットへのCisco Nexus 92300YC クラスタ スイッチとパススルー パネルのインストール』ガイドを参照してください。



 a| 
Telco ラック内の機器
 a| 
スイッチのハードウェア設置ガイド、およびネットアップのセットアップガイドに記載されている手順を参照してください。

|===
. 入力済みのケーブル接続ワークシートを使用して、クラスタネットワークスイッチと管理ネットワークスイッチをコントローラにケーブル接続します。
. クラスタネットワークと管理ネットワークのスイッチとコントローラの電源をオンにします。


.次の手順
オプションとして、link:install-switch-netapp-cabinet-92300yc.html["NetAppキャビネットにCisco Nexus 3223Cスイッチをインストールする"] 。それ以外の場合は、link:cabling-considerations-92300.html["ケーブル接続と構成を確認"] 。
