---
permalink: switch-cisco-92300/install-switch-92300yc.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 92300YC 
summary: Cisco Nexus 92300YC クラスタスイッチをインストールして、ネットワーク運用に向けて準備します。 
---
= Cisco Nexus 92300YC クラスタスイッチのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 92300YC クラスタスイッチをインストールおよびセットアップして、ネットワーク運用に向けて準備します。

.開始する前に
以下のものがあることを確認してください。

* 該当する NX-OS およびリファレンス コンフィギュレーション ファイル (RCF) リリースをダウンロードするために、インストール サイトの HTTP、FTP、または TFTP サーバーにアクセスします。
* 該当するNX-OSバージョンは、 https://software.cisco.com/download/home["Ciscoソフトウェアのダウンロード"^]ページ。
* 適用可能なライセンス、ネットワークおよび構成情報、およびケーブル。
* 完了 link:setup-worksheet-92300yc.html["配線ワークシート"]。
* 適用可能なNetAppクラスタネットワークおよび管理ネットワークRCFは、 NetAppサポートサイトからダウンロードできます。 http://mysupport.netapp.com/["mysupport.netapp.com"^] 。すべてのCiscoクラスタ ネットワークおよび管理ネットワーク スイッチは、標準のCisco工場出荷時のデフォルト構成で出荷されます。これらのスイッチにも NX-OS ソフトウェアの最新バージョンが搭載されていますが、RCF はロードされていません。
* link:required-documentation-92300.html["必要なスイッチとONTAPのドキュメント"]。


.手順
. クラスター ネットワークと管理ネットワーク スイッチおよびコントローラーをラックに設置します。
+
[cols="1,2"]
|===
| ...をインストールする場合 | 操作 


 a| 
Cisco Nexus 92300YC（NetAppシステムキャビネット）
 a| 
スイッチをNetAppキャビネットに設置する手順については、『Cisco Nexus 92300YCクラスタスイッチとパススルーパネルのNetAppキャビネットへの設置』ガイドを参照してください。



 a| 
通信ラック内の機器
 a| 
スイッチ ハードウェアのインストール ガイドおよびNetAppのインストールおよびセットアップ手順に記載されている手順を参照してください。

|===
. 完成した配線ワークシートを使用して、クラスター ネットワークと管理ネットワーク スイッチをコントローラーに配線します。
. クラスター ネットワークと管理ネットワークのスイッチとコントローラーの電源をオンにします。


.次の手順
オプションで、link:install-switch-netapp-cabinet-92300yc.html["Cisco Nexus 3223C スイッチを NetApp キャビネットに設置する"]。それ以外の場合は、link:cabling-considerations-92300.html["ケーブル配線と構成を確認する"]。
