---
permalink: switch-cisco-92300/required-documentation-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Cisco Nexus 92300YC スイッチのインストールとメンテナンスについては、推奨されるすべてのドキュメントを必ず確認してください。 
---
= Cisco Nexus 92300YCスイッチのドキュメント要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 92300YC スイッチのインストールとメンテナンスについては、推奨されるすべてのドキュメントを必ず確認してください。



== スイッチのドキュメント

Cisco Nexus 92300YCスイッチをセットアップするには、次のドキュメントが必要です。 https://www.cisco.com/site/us/en/products/networking/cloud-networking-switches/nexus-9200-series-switches/index.html["Cisco Nexus 9000 シリーズ スイッチのサポート"^]ページ：

[cols="1,2"]
|===
| ドキュメント タイトル | 説明 


 a| 
_Nexus 9000 シリーズ ハードウェア インストール ガイド_
 a| 
サイト要件、スイッチ ハードウェアの詳細、およびインストール オプションに関する詳細情報を提供します。



 a| 
_Cisco Nexus 9000 シリーズ スイッチ ソフトウェア コンフィギュレーション ガイド_ (スイッチにインストールされている NX-OS リリースのガイドを選択してください)
 a| 
ONTAP操作用にスイッチを構成する前に必要な初期スイッチ構成情報を提供します。



 a| 
_Cisco Nexus 9000 シリーズ NX-OS ソフトウェア アップグレードおよびダウングレード ガイド_ (スイッチにインストールされている NX-OS リリースのガイドを選択してください)
 a| 
必要に応じて、スイッチをONTAP対応スイッチ ソフトウェアにダウングレードする方法に関する情報を提供します。



 a| 
_Cisco Nexus 9000 シリーズ NX-OS コマンドリファレンス マスターインデックス_
 a| 
Ciscoが提供するさまざまなコマンド リファレンスへのリンクを提供します。



 a| 
_Cisco Nexus 9000 MIB リファレンス_
 a| 
Nexus 9000 スイッチの管理情報ベース (MIB) ファイルについて説明します。



 a| 
_Nexus 9000 シリーズ NX-OS システム メッセージ リファレンス_
 a| 
Cisco Nexus 9000 シリーズ スイッチのシステム メッセージについて説明します。システム メッセージには情報メッセージと、リンク、内部ハードウェア、またはシステム ソフトウェアの問題の診断に役立つメッセージが含まれます。



 a| 
_Cisco Nexus 9000 シリーズ NX-OS リリース ノート (スイッチにインストールされている NX-OS リリースのノートを選択してください)_
 a| 
Cisco Nexus 9000 シリーズの機能、バグ、および制限について説明します。



 a| 
Cisco Nexus 9000 シリーズの規制コンプライアンスおよび安全性に関する情報
 a| 
Nexus 9000 シリーズ スイッチに関する国際機関のコンプライアンス、安全性、および法定情報を提供します。

|===


== ONTAPシステムのドキュメント

ONTAPシステムをセットアップするには、オペレーティングシステムのバージョンに応じて次のドキュメントが必要です。 https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^] 。

[cols="1,2"]
|===
| Name | 説明 


 a| 
コントローラ固有の_インストールおよびセットアップ手順_
 a| 
NetAppハードウェアのインストール方法について説明します。



 a| 
ONTAPのドキュメント
 a| 
ONTAPリリースのあらゆる側面に関する詳細情報を提供します。



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
NetApp のハードウェア構成と互換性に関する情報を提供します。

|===


== レールキットとキャビネットのドキュメント

Cisco Nexus 92300YC スイッチをNetAppキャビネットにインストールするには、次のハードウェア ドキュメントを参照してください。

[cols="1,2"]
|===
| Name | 説明 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["42U システムキャビネット、ディープガイド"^]
 a| 
42U システム キャビネットに関連する FRU について説明し、メンテナンスおよび FRU 交換の手順を示します。



 a| 
link:install-switch-netapp-cabinet-92300yc.html["NetAppキャビネットにCisco Nexus 92300YCスイッチをインストールする"]
 a| 
Cisco Nexus 92300YC スイッチを 4 ポストNetAppキャビネットにインストールする方法について説明します。

|===