---
permalink: switch-cshm/config-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: CSHM がクラスターおよびストレージ ネットワーク スイッチからスイッチ ログと診断データを収集できるようにログ収集を設定します。 
---
= イーサネットスイッチのヘルスモニターのログ収集を設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イーサネットスイッチでログ収集を設定して、イーサネットスイッチヘルスモニター（CSHM）がデバッグおよび AutoSupport レポート用のスイッチログを収集できるようにします。この手順では、ONTAP でのオンデマンドサポートログ収集と時間ごとの定期データ収集の両方を設定します。

.開始する前に
* FIPSモードを使用する場合は、ログ収集を設定する前に、以下の手順を完了してください。
+
.. ベンダーの指示に従ってスイッチ上の SSH キーを再生成します。
.. ONTAP で SSH キーを再生成するには、 `debug system regenerate-systemshell-key-pair`を使用します。
..  `system switch ethernet log setup-password`コマンドを使用して、ログ収集設定を再実行してください。


* スイッチの `show`コマンドにアクセスできる必要があります。アクセスできない場合は、新しいスイッチユーザーを作成し、必要な権限を付与してください。
* スイッチの状態監視を有効にする必要があります。 `Is Monitored:`フィールドが `system switch ethernet show`の出力で *true* に設定されていることを確認してください。
* Broadcom およびCiscoスイッチによるログ収集の場合:
+
** ローカル ユーザーにはネットワーク管理者権限が必要です。
** ログ収集が有効になっている各クラスターに対して、新しいスイッチユーザーを作成します。これらのスイッチは、同一ユーザーに対して複数の SSH キーをサポートしていません。セットアップを再度実行すると、既存の SSH キーが上書きされます。


* NVIDIA スイッチでのサポートログ収集では、ログ収集ユーザーがパスワードなしで `cl-support`コマンドを実行できる必要があります。これを許可するには、次のコマンドを実行してください：
+
`echo '_<user>_ ALL = NOPASSWD: /usr/cumulus/bin/cl-support' | sudo EDITOR='tee -a' visudo -f /etc/sudoers.d/cumulus`



.手順
お使いの ONTAP のバージョンの手順に従って、ログ収集を設定し、定期的なデータ収集を有効にし、必要に応じてオンデマンドサポートログをリクエストしてください。

[role="tabbed-block"]
====
.ONTAP 9.15.1以降
--
. ログ収集を設定するには、スイッチごとに次のコマンドを実行します。ログ収集用のスイッチ名、ユーザー名、およびパスワードの入力を求められます。
+
*注意:* ユーザー指定プロンプトに *y* と答える場合は、ユーザーが以下の必要な権限を持っていることを確認してください。<<開始する前に>> 。

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: CL 5.11.1 の場合、ユーザー *cumulus* を作成し、次のプロンプトに *y* と応答します: ログ収集に admin 以外のユーザーを指定しますか?  {y|n}: *y*

. [[step2]]定期的なログ収集を有効にする:
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -periodic-enabled true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs1*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log modify -device cs2 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs2*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log show*
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       true        scheduled   never-run
cs2                                       true        scheduled   never-run
2 entries were displayed.
----
. サポートログ収集をリクエスト:
+
[source, cli]
----
system switch ethernet log collect-support-log -device <switch-name>
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log collect-support-log -device cs1*

*cs1*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log collect-support-log -device cs2*

*cs2*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log show
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       false       halted      initiated
cs2                                       true        scheduled   initiated
2 entries were displayed.
----
. 定期的な収集の有効化、ステータス メッセージ、前回のタイムスタンプとファイル名、サポート収集の要求ステータス、ステータス メッセージ、前回のタイムスタンプとファイル名など、ログ収集のすべての詳細を表示するには、以下を使用します。
+
[source, cli]
----
system switch ethernet log show -instance
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show -instance*

                    Switch Name: cs1
           Periodic Log Enabled: true
            Periodic Log Status: Periodic log collection has been scheduled to run every hour.
    Last Periodic Log Timestamp: 3/11/2024 11:02:59
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:14:20
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz

                    Switch Name: cs2
           Periodic Log Enabled: false
            Periodic Log Status: Periodic collection has been halted.
    Last Periodic Log Timestamp: 3/11/2024 11:05:18
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:18:54
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz
2 entries were displayed.
----


--
.ONTAP 9.14.1以前
--
. ログ収集を設定するには、スイッチごとに次のコマンドを実行します。ログ収集用のスイッチ名、ユーザー名、およびパスワードの入力を求められます。
+
*注:* 回答する場合 `y`ユーザー指定プロンプトが表示されたら、ユーザーが以下の必要な権限を持っていることを確認してください。<<開始する前に>> 。

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: CL 5.11.1 の場合、ユーザー *cumulus* を作成し、次のプロンプトに *y* と応答します: ログ収集に admin 以外のユーザーを指定しますか?  {y|n}: *y*

. [[step2]] サポートログの収集を要求し、定期的な収集を有効にするには、次のコマンドを実行します。これにより、詳細なログ収集と、 `Support`ログと1時間ごとの収集 `Periodic`データ。
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -log-request true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
+
10 分待ってから、ログ収集が完了したことを確認します。

+
[source, cli]
----
system switch ethernet log show
----


--
====

CAUTION: ログ収集機能によってエラーステータスが報告された場合（ `system switch ethernet log show`の出力に表示されます）、詳細についてはlink:log-collection-troubleshoot.html["ログ収集のトラブルシューティング"]を参照してください。

.次の手順
link:config-snmpv3.html["SNMPv3 を構成する (オプション)"]。
