---
permalink: switch-cshm/monitor-verify.html 
sidebar: sidebar 
keywords: verify, monitor, cluster, management, network, switches, heath, monitor 
summary: イーサネット スイッチの監視が機能しているかどうかを確認する方法を学習します。 
---
= イーサネットスイッチの監視を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イーサネット スイッチ ヘルス モニター (CSHM) は、検出したスイッチを自動的に監視しようとしますが、スイッチが正しく構成されていない場合は、監視が自動的に行われない可能性があります。ヘルスモニタが使用中のスイッチを監視するように適切に設定されていることを確認してください。



== 接続されたイーサネットスイッチの監視を確認する

接続されているイーサネット スイッチが監視されていることを確認するには、次のコマンドを実行します。

[source, cli]
----
system switch ethernet show
----
もし `Model`列に*OTHER*または `IS Monitored`フィールドに「*false*」と表示されている場合、 ONTAP はスイッチを監視できません。通常、*OTHER* の値は、 ONTAP がそのスイッチのヘルス モニタリングをサポートしていないことを示します。

その `IS Monitored`フィールドは、指定された理由により*false*に設定されています。 `Reason`分野。

[NOTE]
====
コマンド出力にスイッチがリストされていない場合は、 ONTAPによってそのスイッチが検出されていない可能性があります。スイッチのケーブルが正しく接続されていることを確認します。必要に応じて、スイッチを手動で追加できます。。 link:monitor-manage.html["イーサネットスイッチの監視を管理する"]詳細についてはこちらをご覧ください。

====


== ファームウェアとRCFのバージョンが最新であることを確認します

スイッチが最新のサポートされているファームウェアを実行していること、および互換性のある参照構成ファイル (RCF) が適用されていることを確認します。詳細は、https://mysupport.netapp.com/site/downloads["NetAppサポート ダウンロード ページ"^] 。

デフォルトでは、ヘルス モニターは監視にコミュニティ文字列 *cshm1!* を持つ SNMPv2c を使用しますが、SNMPv3 も設定できます。

デフォルトの SNMPv2c コミュニティ文字列を変更する必要がある場合は、必要な SNMPv2c コミュニティ文字列がスイッチに設定されていることを確認してください。

[source, cli]
----
system switch ethernet modify -device SwitchA -snmp-version SNMPv2c -community-or-username newCommunity!
----

NOTE: 見るlink:config-snmpv3.html["オプション: SNMPv3 を構成する"]SNMPv3 を使用するための設定の詳細については、こちらをご覧ください。



== 管理ネットワーク接続を確認する

スイッチの管理ポートが管理ネットワークに接続されているかを確認します。

ONTAPが SNMP クエリとログ収集を実行するには、正しい管理ポート接続が必要です。
