---
permalink: switch-nvidia-sn2100-storage/configure-overview-sn2100-storage.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: NVIDIA SN2100スイッチを設定する前に、手順 の概要を確認してください。 
---
= NVIDIA SN2100ストレージスイッチの設定プロセスの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIA SN2100はストレージスイッチで、SAN（ストレージエリアネットワーク）内のサーバとストレージアレイの間でデータをルーティングできます。



== 初期設定の概要

ONTAP を実行しているシステムでNVIDIA SN2100スイッチを設定する手順は、次のとおりです。

. link:install-hardware-sn2100-storage.html["NVIDIA SN2100スイッチのハードウェアを取り付けます"]。
+
手順については、「NVIDIA Switch Installation Guide」を参照してください。

. link:configure-sn2100-storage.html["スイッチを設定します"]。
+
手順については、NVIDIAのドキュメントを参照してください。

. link:cabling-considerations-sn2100-storage.html["ケーブル接続と構成に関する考慮事項を確認"]。
+
光接続、QSAアダプタ、およびスイッチポート速度の要件を確認します。

. link:install-cable-shelves-sn2100-storage.html["NS224シェルフをスイッチ接続型ストレージとしてケーブル接続します"]。
+
NS224ドライブシェルフをスイッチ接続型ストレージ（直接接続型ストレージではない）としてケーブル接続する必要があるシステムの場合は、次の手順に従います。

. link:install-cumulus-mode-sn2100-storage.html["Cumulus LinuxをCumulusモードでインストールします"] または link:install-onie-mode-sn2100-storage.html["Cumulus LinuxをONIEモードでインストールします"]。
+
Cumulus Linux（CL）OSは、スイッチがCumulus LinuxまたはONIEを実行している場合にインストールできます。

. link:install-rcf-sn2100-storage.html["リファレンス構成ファイルスクリプトをインストールします"]。
+
クラスタリングアプリケーションとストレージアプリケーション用に2つのRCFスクリプトが用意されています。





== 追加情報

インストールまたはメンテナンスを開始する前に、次の点を確認してください。

* link:configure-reqs-sn2100-storage.html["設定要件"]
* link:components-sn2100-storage.html["コンポーネントとパーツ番号"]
* link:required-documentation-sn2100-storage.html["必要なドキュメント"]

