---
permalink: switch-nvidia-sn2100-storage/CSHM_log_collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation,SN2100 setup,SN2100 switches configuration,cumulus linux os 
summary: イーサネットスイッチヘルスモニタ（CSHM）のログ収集機能は、ONTAPのクラスタまたはストレージネットワークスイッチからログを収集するために使用します。 
---
= イーサネットスイッチヘルスモニタリングのログ収集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イーサネットスイッチヘルスモニタ（CSHM）は、クラスタネットワークスイッチとストレージネットワークスイッチの動作の健全性を確認し、デバッグ用にスイッチのログを収集します。この手順では、スイッチからの詳細な*サポート*ログの収集を設定および開始するプロセスをガイドし、AutoSupportによって収集された*定期的な*データの1時間ごとの収集を開始します。

.作業を開始する前に
* リファレンス構成ファイル（RCF）を適用する場合は、ログ収集用のユーザを指定する必要があります。デフォルトでは、このユーザは_admin_に設定されています。別のユーザを使用する場合は、RCFの*# SHM User * sセクションで指定する必要があります。
* ユーザは* nv show *コマンドにアクセスできる必要があります。追加するには、次のコマンドを実行します。 `sudo adduser USER nv show` ユーザをユーザに置き換えてログ収集を行います。
* スイッチのヘルスモニタが有効になっている必要があります。これを確認するには、 `Is Monitored:` フィールドは、 `system switch ethernet show` コマンドを実行します


.手順
. ログ収集を設定するには、スイッチごとに次のコマンドを実行します。ログ収集用のスイッチ名、ユーザ名、およびパスワードの入力を求められます。
+
「システムスイッチイーサネットログセットアップ - パスワード」

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. ログ収集を開始するには、次のコマンドを実行し、deviceを前のコマンドで使用したスイッチに置き換えます。これにより、両方のタイプのログ収集が開始されます。 `Support` ログと時間単位の収集 `Periodic` データ：
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
10分待ってから、ログ収集が完了したことを確認します。

+
`system switch ethernet log show`

+

CAUTION: これらのコマンドのいずれかでエラーが返された場合、またはログの収集が完了しない場合は、NetAppサポートにお問い合わせください。



.トラブルシューティング
ログ収集機能によって次のいずれかのエラーステータスが報告された場合（の出力に表示されます） `system switch ethernet log show`)で、対応するデバッグ手順を試します。

|===


| *ログ収集エラーステータス* | *解像度* 


 a| 
* RSAキーがありません*
 a| 
ONTAP SSHキーを再生成します。NetAppサポートにお問い合わせください。



 a| 
*スイッチパスワードエラー*
 a| 
クレデンシャルを検証し、SSH接続をテストし、ONTAP SSHキーを再生成します。手順については、スイッチのマニュアルを参照するか、NetAppサポートにお問い合わせください。



 a| 
* FIPSにECDSAキーがありません*
 a| 
FIPSモードが有効になっている場合は、再試行する前にスイッチでECDSAキーを生成する必要があります。



 a| 
*既存のログが見つかりました*
 a| 
以前のログ収集ディレクトリとにある「.tar」ファイルを削除します。 `/tmp/shm_log` スイッチ上。



 a| 
*スイッチダンプログエラー*
 a| 
スイッチユーザにログ収集権限があることを確認します。上記の前提条件を参照してください。

|===