---
permalink: switch-nvidia-sn2100-storage/install-cumulus-mode-sn2100-storage.html 
sidebar: sidebar 
keywords: install cumulus mode, sn2100 SN2100 switches setup, cumulus linux, cumulus mode 
summary: 'Cumulus Linux (CL) OS は、スイッチが Cumulus Linux または ONIE を実行しているときにインストールできます。' 
---
= Cumulus LinuxをCumulusモードでインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スイッチが Cumulus モードで実行されているときに Cumulus Linux (CL) OS をインストールするには、次の手順に従ってください。


NOTE: Cumulus Linux (CL) OSは、スイッチがCumulus LinuxまたはONIEを実行しているときにインストールできます（link:install-onie-mode-sn2100-storage.html["ONIEモードでインストールする"] ）。

.開始する前に
以下のものが利用可能であることを確認してください。

* 中級レベルの Linux の知識。
* 基本的なテキスト編集、UNIX ファイル権限、プロセス監視に関する知識。さまざまなテキストエディタがプリインストールされており、 `vi`そして `nano`。
* Linux または UNIX シェルへのアクセス。  Windows を実行している場合は、Cumulus Linux と対話するためのコマンド ライン ツールとして Linux 環境を使用します。
* NVIDIA SN2100 スイッチ コンソール アクセスの場合、シリアル コンソール スイッチのボー レート要件は次のように 115200 に設定する必要があります。
+
** 115200ボー
** 8データ ビット
** 1ストップ ビット
** パリティ：なし
** フロー制御：なし




.タスク概要
次の点に注意してください。


NOTE: Cumulus Linux がインストールされるたびに、ファイル システム構造全体が消去され、再構築されます。


CAUTION: cumulus ユーザー アカウントのデフォルトのパスワードは *cumulus* です。 Cumulus Linux に初めてログインするときは、このデフォルトのパスワードを変更する必要があります。新しいイメージをインストールする前に、自動化スクリプトを必ず更新してください。  Cumulus Linux には、インストール プロセス中にデフォルトのパスワードを自動的に変更するためのコマンド ライン オプションが用意されています。

.手順
[role="tabbed-block"]
====
.キュムラス・リナックス 4.4.3
--
. スイッチにログインします。
+
スイッチに初めてログインする場合は、*cumulus*/*cumulus*のユーザー名/パスワードが必要です。 `sudo`特権。

+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Cumulus Linux のバージョンを確認します。 `net show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show system*
Hostname......... cumulus
Build............ *Cumulus Linux 4.4.3*
Uptime........... 0:08:20.860000
Model............ Mlnx X86
CPU.............. x86_64 Intel Atom C2558 2.40GHz
Memory........... 8GB
Disk............. 14.7GB
ASIC............. Mellanox Spectrum MT52132
Ports............ 16 x 100G-QSFP28
Part Number...... MSN2100-CB2FC
Serial Number.... MT2105T05177
Platform Name.... x86_64-mlnx_x86-r0
Product Name..... MSN2100
ONIE Version..... 2019.11-5.2.0020-115200
Base MAC Address. 04:3F:72:43:92:80
Manufacturer..... Mellanox
----
. ホスト名、IP アドレス、サブネット マスク、およびデフォルト ゲートウェイを構成します。新しいホスト名は、コンソール/SSH セッションを再起動した後でのみ有効になります。
+

NOTE: Cumulus Linuxスイッチは、少なくとも1つの専用のイーサネット管理ポートを提供します。 `eth0` 。このインターフェースは、アウトオブバンド管理専用です。デフォルトでは、管理インターフェイスはアドレス指定に DHCPv4 を使用します。

+

CAUTION: ホスト名にはアンダースコア (_)、アポストロフィ (')、または非 ASCII 文字を使用しないでください。

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net add hostname sw1*
cumulus@cumulus:mgmt:~$ *net add interface eth0 ip address 10.233.204.71*
cumulus@cumulus:mgmt:~$ *net add interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *net pending*
cumulus@cumulus:mgmt:~$ *net commit*
----
+
このコマンドは、 `/etc/hostname`そして `/etc/hosts`ファイル。

. ホスト名、IP アドレス、サブネット マスク、デフォルト ゲートウェイが更新されていることを確認します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. スイッチの日付、時刻、タイムゾーン、NTP サーバーを設定します。
+
.. 現在のタイムゾーンを確認します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *cat /etc/timezone*
----
.. 新しいタイムゾーンに更新します:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure --frontend noninteractive tzdata*
----
.. 現在のタイムゾーンを確認してください:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *date +%Z*
----
.. ガイド付きウィザードを使用してタイムゾーンを設定するには、次のコマンドを実行します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. 設定されたタイムゾーンに従ってソフトウェア クロックを設定します。
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *sudo date -s "Tue Oct 28 00:37:13 2023"*
----
.. ソフトウェア クロックの現在の値をハードウェア クロックに設定します。
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *sudo hwclock -w*
----
.. 必要に応じて NTP サーバーを追加します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add time ntp server _<cumulus.network.ntp.org>_ iburst*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
.. 確認する `ntpd`システム上で実行されています:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *ps -ef | grep ntp*
ntp       4074     1  0 Jun20 ?        00:00:33 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:102
----
.. NTP ソース インターフェイスを指定します。デフォルトでは、NTPが使用するソースインターフェースは `eth0`。次のようにして、異なる NTP ソース インターフェイスを設定できます。
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add time ntp source _<src_int>_*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----


. Cumulus Linux 4.4.3 をインストールします。
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*
----
+
インストーラーがダウンロードを開始します。プロンプトが表示されたら「*y*」と入力します。

. NVIDIA SN2100 スイッチを再起動します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. インストールが自動的に開始され、次の GRUB 画面の選択肢が表示されます。何も選択しないでください。
+
** キュムラス・リナックス GNU/Linux
** ONIE: OSのインストール
** CUMULUS-インストール
** キュムラス・リナックス GNU/Linux


. 手順1～4を繰り返してログインします。
. Cumulus Linux のバージョンが 4.4.3 であることを確認します。 `net show version`
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u0
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3"*
----
. 新しいユーザーを作成し、このユーザーを `sudo`グループ。このユーザーは、コンソール/SSH セッションが再起動された後にのみ有効になります。
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----


--
.キュムラス・リナックス 5.4.0
--
. スイッチにログインします。
+
スイッチに初めてログインする場合は、*cumulus*/*cumulus*のユーザー名/パスワードが必要です。 `sudo`特権。

+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Cumulus Linux のバージョンを確認します。 `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.3.0  system build version
uptime              6 days, 8:37:36      system uptime
timezone            Etc/UTC              system time zone
----
. ホスト名、IP アドレス、サブネット マスク、およびデフォルト ゲートウェイを構成します。新しいホスト名は、コンソール/SSH セッションを再起動した後でのみ有効になります。
+

NOTE: Cumulus Linuxスイッチは、少なくとも1つの専用のイーサネット管理ポートを提供します。 `eth0` 。このインターフェースは、アウトオブバンド管理専用です。デフォルトでは、管理インターフェイスはアドレス指定に DHCPv4 を使用します。

+

CAUTION: ホスト名にはアンダースコア (_)、アポストロフィ (')、または非 ASCII 文字を使用しないでください。

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set system hostname sw1*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip address 10.233.204.71/24*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *nv config apply*
cumulus@cumulus:mgmt:~$ *nv config save*
----
+
このコマンドは、 `/etc/hostname`そして `/etc/hosts`ファイル。

. ホスト名、IP アドレス、サブネット マスク、デフォルト ゲートウェイが更新されていることを確認します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. スイッチのタイムゾーン、日付、時刻、NTP サーバーを設定します。
+
.. タイムゾーンを設定します:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set system timezone US/Eastern*
cumulus@sw1:~$ *nv config apply*
----
.. 現在のタイムゾーンを確認してください:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *date +%Z*
----
.. ガイド付きウィザードを使用してタイムゾーンを設定するには、次のコマンドを実行します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. 設定されたタイムゾーンに従ってソフトウェア クロックを設定します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo date -s "Tue Oct 28 00:37:13 2023"*
----
.. ソフトウェア クロックの現在の値をハードウェア クロックに設定します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo hwclock -w*
----
.. 必要に応じて NTP サーバーを追加します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp mgmt listen eth0*
cumulus@sw1:~$ *nv set service ntp mgmt server <server> iburst on*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv config save*
----
+
ナレッジベースの記事を参照link:https://kb.netapp.com/on-prem/Switches/Nvidia-KBs/NTP_Server_configuration_is_not_working_with_NVIDIA_SN2100_Switches["NTPサーバーの構成がNVIDIA SN2100スイッチで機能しない"^]詳細については、こちらをご覧ください。

.. 確認する `ntpd`システム上で実行されています:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *ps -ef | grep ntp*
ntp       4074     1  0 Jun20 ?        00:00:33 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:102
----
.. NTP ソース インターフェイスを指定します。デフォルトでは、NTPが使用するソースインターフェースは `eth0`。次のようにして、異なる NTP ソース インターフェイスを設定できます。
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp default listen _<src_int>_*
cumulus@sw1:~$ *nv config apply*
----


. Cumulus Linux 5.4.0 をインストールします。
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-5.4-mlx-amd64.bin*
----
+
インストーラーがダウンロードを開始します。プロンプトが表示されたら「*y*」と入力します。

. NVIDIA SN2100 スイッチを再起動します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. インストールが自動的に開始され、次の GRUB 画面の選択肢が表示されます。何も選択しないでください。
+
** キュムラス・リナックス GNU/Linux
** ONIE: OSのインストール
** CUMULUS-インストール
** キュムラス・リナックス GNU/Linux


. 手順1～4を繰り返してログインします。
. Cumulus Linux のバージョンが 5.4.0 であることを確認します。 `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.4.0  system build version
uptime              6 days, 13:37:36     system uptime
timezone            Etc/UTC              system time zone
----
. 各ノードが各スイッチに接続されていることを確認します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost                          RemotePort
---------  -----  ----------  ----------------------------------  -----------
eth0       100M   Mgmt        mgmt-sw1                            Eth110/1/29
swp2s1     25G    Trunk/L2    node1                               e0a
swp15      100G   BondMember  sw2                                 swp15
swp16      100G   BondMember  sw2                                 swp16
----
. 新しいユーザーを作成し、このユーザーを `sudo`グループ。このユーザーは、コンソール/SSH セッションが再起動された後にのみ有効になります。
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
. 管理者ユーザーがアクセスするための追加のユーザーグループを追加する `nv`コマンド:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser admin nvshow*
     [sudo] password for cumulus:
     Adding user 'admin' to group 'nvshow' ...
     Adding user admin to group nvshow
     Done.
----
+
見る https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-54/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["NVIDIAユーザーアカウント"^]詳細についてはこちらをご覧ください。



--
.キュムラス・リナックス 5.11.0
--
. スイッチにログインします。
+
スイッチに初めてログインするときは、*cumulus*/*cumulus*のユーザー名/パスワードが必要です。 `sudo`特権。

+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Cumulus Linux のバージョンを確認します。 `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.4.0  system build version
uptime              6 days, 8:37:36      system uptime
timezone            Etc/UTC              system time zone
----
. ホスト名、IP アドレス、サブネット マスク、およびデフォルト ゲートウェイを構成します。新しいホスト名は、コンソール/SSH セッションを再起動した後でのみ有効になります。
+

NOTE: Cumulus Linuxスイッチは、少なくとも1つの専用のイーサネット管理ポートを提供します。 `eth0` 。このインターフェースは、アウトオブバンド管理専用です。デフォルトでは、管理インターフェイスはアドレス指定に DHCPv4 を使用します。

+

CAUTION: ホスト名にはアンダースコア (_)、アポストロフィ (')、または非 ASCII 文字を使用しないでください。

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv unset interface eth0 ip address dhcp*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip address 10.233.204.71/24*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *nv config apply*
cumulus@cumulus:mgmt:~$ *nv config save*
----
+
このコマンドは、 `/etc/hostname`そして `/etc/hosts`ファイル。

. ホスト名、IP アドレス、サブネット マスク、デフォルト ゲートウェイが更新されていることを確認します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. スイッチのタイムゾーン、日付、時刻、NTP サーバーを設定します。
+
.. タイムゾーンを設定します:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set system timezone US/Eastern*
cumulus@sw1:~$ *nv config apply*
----
.. 現在のタイムゾーンを確認してください:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *date +%Z*
----
.. ガイド付きウィザードを使用してタイムゾーンを設定するには、次のコマンドを実行します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. 設定されたタイムゾーンに従ってソフトウェア クロックを設定します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo date -s "Tue Oct 28 00:37:13 2023"*
----
.. ソフトウェア クロックの現在の値をハードウェア クロックに設定します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo hwclock -w*
----
.. 必要に応じて NTP サーバーを追加します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp mgmt listen eth0*
cumulus@sw1:~$ *nv set service ntp mgmt server <server> iburst on*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv config save*
----
+
ナレッジベースの記事を参照link:https://kb.netapp.com/on-prem/Switches/Nvidia-KBs/NTP_Server_configuration_is_not_working_with_NVIDIA_SN2100_Switches["NTPサーバーの構成がNVIDIA SN2100スイッチで機能しない"^]詳細については、こちらをご覧ください。

.. 確認する `ntpd`システム上で実行されています:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *ps -ef | grep ntp*
ntp       4074     1  0 Jun20 ?        00:00:33 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:102
----
.. NTP ソース インターフェイスを指定します。デフォルトでは、NTPが使用するソースインターフェースは `eth0`。次のようにして、異なる NTP ソース インターフェイスを設定できます。
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp default listen _<src_int>_*
cumulus@sw1:~$ *nv config apply*
----


. Cumulus Linux 5.11.0 をインストールします。
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-5.11.0-mlx-amd64.bin*
----
+
インストーラーがダウンロードを開始します。プロンプトが表示されたら「*y*」と入力します。

. NVIDIA SN2100 スイッチを再起動します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. インストールが自動的に開始され、次の GRUB 画面の選択肢が表示されます。何も選択しないでください。
+
** キュムラス・リナックス GNU/Linux
** ONIE: OSのインストール
** CUMULUS-インストール
** キュムラス・リナックス GNU/Linux


. 手順1～4を繰り返してログインします。
. Cumulus Linux のバージョンが 5.11.0 であることを確認します。
+
`nv show system`

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied                description
------------------- ---------------------- ---------------------
build               Cumulus Linux 5.11.0
uptime              153 days, 2:44:16
hostname            cumulus                cumulus
product-name        Cumulus Linux
product-release     5.11.0
platform            x86_64-mlnx_x86-r0
system-memory       2.76 GB used / 2.28 GB free / 7.47 GB total
swap-memory         0 Bytes used / 0 Bytes free / 0 Bytes total
health-status       not OK
date-time           2025-04-23 09:55:24
status              N/A
timezone            Etc/UTC
maintenance
  mode              disabled
  ports             enabled
version
  kernel            6.1.0-cl-1-amd64
  build-date        Thu Nov 14 13:06:38 UTC 2024
  image             5.11.0
  onie              2019.11-5.2.0020-115200
----
. 各ノードが各スイッチに接続されていることを確認します。
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv show interface lldp*

LocalPort  Speed  Mode        RemoteHost                          RemotePort
---------  -----  ----------  ----------------------------------  -----------
eth0       100M   eth   mgmt-sw1                                  Eth110/1/14
swp2s1     25G    Trunk/L2    node1                               e0a
swp1s1     10G    swp   sw2                                       e0a
swp9       100G   swp   sw3                                       e4a
swp10      100G   swp   sw4                                       e4a
swp15      100G   swp   sw5                                       swp15
swp16      100G   swp   sw6                                       swp16
----


見る https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-511/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["NVIDIAユーザーアカウント"^]詳細についてはこちらをご覧ください。

--
====
.次の手順
link:install-rcf-sn2100-storage.html["RCFスクリプトをインストールまたはアップグレードする"] 。
