---
permalink: switch-nvidia-sn2100-storage/install-onie-mode-sn2100-storage.html 
sidebar: sidebar 
keywords: install cumulus onie mode, sn2100 SN2100 switches setup, cumulus linux, onie mode 
summary: 'Cumulus Linux (CL) OS は、スイッチが Cumulus Linux または ONIE を実行しているときにインストールできます。' 
---
= ONIEモードでCumulus Linuxをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スイッチが ONIE モードで実行されているときに Cumulus Linux (CL) OS をインストールするには、次の手順に従ってください。


NOTE: Cumulus Linux (CL) OSは、スイッチがCumulus LinuxまたはONIEを実行しているときにインストールできます（link:install-cumulus-mode-sn2100-storage.html["Cumulusモードでインストール"] ）。

.タスク概要
ネットワーク インストーラ イメージの自動検出を可能にする Open Network Install Environment (ONIE) を使用して、Cumulus Linux をインストールできます。これにより、Cumulus Linux などのオペレーティング システムを選択してスイッチを保護するシステム モデルが容易になります。  ONIE を使用して Cumulus Linux をインストールする最も簡単な方法は、ローカル HTTP 検出を使用することです。


NOTE: ホストが IPv6 対応である場合は、Web サーバーが実行されていることを確認してください。ホストが IPv4 対応の場合は、Web サーバーに加えて DHCP も実行されていることを確認してください。

この手順では、管理者が ONIE で起動した後に Cumulus Linux をアップグレードする方法を示します。

.手順
. Cumulus Linux インストール ファイルを Web サーバーのルート ディレクトリにダウンロードします。このファイルの名前を変更する `onie-installer`。
. イーサネット ケーブルを使用して、ホストをスイッチの管理イーサネット ポートに接続します。
. スイッチの電源を入れます。スイッチは ONIE イメージ インストーラをダウンロードして起動します。インストールが完了すると、ターミナル ウィンドウに Cumulus Linux ログイン プロンプトが表示されます。
+

NOTE: Cumulus Linux がインストールされるたびに、ファイル システム構造全体が消去され、再構築されます。

. SN2100スイッチを再起動します。
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. GNU GRUB 画面で *Esc* キーを押して通常のブート プロセスを中断し、*ONIE* を選択して *Enter* を押します。
. 次に表示される画面で、*ONIE: OS のインストール*を選択します。
. ONIE インストーラー検出プロセスが自動インストールの検索を実行します。プロセスを一時的に停止するには、*Enter* を押します。
. 検出プロセスが停止した場合:
+
[listing, subs="+quotes"]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. ネットワーク上で DHCP サービスが実行されている場合は、IP アドレス、サブネット マスク、およびデフォルト ゲートウェイが正しく割り当てられていることを確認します。
+
`ifconfig eth0`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff

ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.233.204.1    0.0.0.0         UG    0      0      0   eth0
10.233.204.0    *               255.255.254.0   U     0      0      0   eth0
----
====
. IP アドレス指定スキームを手動で定義する場合は、次の手順を実行します。
+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0 10.233.204.71 netmask 255.255.254.0*
ONIE:/ # *route add default gw 10.233.204.1*
----
. 手順 9 を繰り返して、静的情報が正しく入力されていることを確認します。
. Cumulus Linux をインストールします。
+
[listing, subs="+quotes"]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-4.4.3-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
. インストールが完了したら、スイッチにログインします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
====
. Cumulus Linux のバージョンを確認します。
+
`net show version`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u4
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3”*
----
====


.次の手順
link:install-rcf-sn2100-storage.html["RCFスクリプトをインストールまたはアップグレードする"] 。
