---
permalink: switch-nvidia-sn2100-storage/migrate-cisco-storage-switch-sn2100-storage.html 
sidebar: sidebar 
keywords: migrating to a storage switch with NVIDIA SN2100 storage switches, how to migrate 
summary: ONTAPクラスタ用の古いCiscoスイッチを、 NVIDIA SN2100 ストレージ スイッチに無停止で移行できます。 
---
= Ciscoストレージ スイッチからNVIDIA SN2100 ストレージ スイッチへの移行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPクラスタ用の古いCiscoスイッチをNVIDIA SN2100 ストレージ スイッチに移行できます。これは中断を伴わない手順です。



== 要件の確認

次のストレージ スイッチがサポートされています。

* Cisco Nexus 9336C-FX2
* Cisco Nexus 3232C
* 参照 https://hwu.netapp.com/["Hardware Universe"^]サポートされているポートとその構成の詳細については、こちらをご覧ください。


.開始する前に
以下のものがあることを確認してください。

* 既存のクラスターは適切にセットアップされ、機能しています。
* 中断のない操作を保証するために、すべてのストレージ ポートは稼働状態になっています。
* NVIDIA SN2100 ストレージ スイッチは、参照構成ファイル (RCF) が適用された適切なバージョンの Cumulus Linux がインストールされ、構成され、動作しています。
* 既存のストレージ ネットワーク構成は次のとおりです。
+
** どちらも古いCiscoスイッチを両方使用する、完全に機能している冗長なNetAppクラスタ。
** 古いCiscoスイッチと新しいスイッチ両方への管理接続とコンソール アクセス。
** クラスタ LIF がすべてアップ状態にあり、クラスタ LIF がホーム ポート上にある。
** ISLポートが有効で、古いCiscoスイッチ間および新しいスイッチ間でケーブル接続されている。


* 参照 https://hwu.netapp.com/["Hardware Universe"^]サポートされているポートとその構成の詳細については、こちらをご覧ください。
* 一部のポートは、 NVIDIA SN2100 スイッチ上で 100 GbE で動作するように構成されています。
* ノードからNVIDIA SN2100 ストレージ スイッチへの 100 GbE 接続を計画、移行、および文書化しました。




== スイッチを移行する

.例について
この手順では、コマンドと出力の例として、 Cisco Nexus 9336C-FX2 ストレージ スイッチを使用します。

この手順の例で使用するスイッチとノードの名前は次のとおりです。

* 既存のCisco Nexus 9336C-FX2 ストレージ スイッチは _S1_ と _S2_ です。
* 新しいNVIDIA SN2100 ストレージ スイッチは、_sw1_ と _sw2_ です。
* ノードは _node1_ と _node2_ です。
* クラスター LIF は、ノード 1 ではそれぞれ _node1_clus1_ と _node1_clus2_、ノード 2 では _node2_clus1_ と _node2_clus2_ です。
* その `cluster1::*>`プロンプトはクラスターの名前を示します。
* この手順で使用されるネットワーク ポートは _e5a_ と _e5b_ です。
* ブレイクアウト ポートの形式は swp1s0-3 です。たとえば、swp1 の 4 つのブレークアウト ポートは、_swp1s0_、_swp1s1_、_swp1s2_、_swp1s3_ です。
* 最初にスイッチS2をスイッチsw2に交換し、次にスイッチS1をスイッチsw1に交換します。
+
** 次にノードとS2の間のケーブルをS2から外し、sw2に再接続します。
** 次にノードとS1の間のケーブルをS1から外し、sw1に再接続します。






=== ステップ1: 移行の準備

. AutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を停止します。
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
ここで、_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

. 続行するかどうかを尋ねられたら *y* と入力して、権限レベルを「advanced」に変更します。
+
`set -privilege advanced`

+
advancedのプロンプト（*>）が表示されます。

. 各ストレージ インターフェイスの管理ステータスまたは動作ステータスを確認します。
+
各ポートは有効になっている必要があります `Status`。





=== ステップ2: ケーブルとポートを構成する

. ネットワーク ポートの属性を表示します。
+
`storage port show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. 次のコマンドを使用して、各ノードのストレージ ポートが既存のストレージ スイッチに次のように (ノードの観点から) 接続されていることを確認します。
+
`network device-discovery show -protocol lldp`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/1           -
node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/2           -
----
====
. スイッチ S1 および S2 で、次のコマンドを使用して、ストレージ ポートとスイッチが次のように (スイッチの観点から) 接続されていることを確認します。
+
`show lldp neighbors`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
S1# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability           Port ID
node1                 Eth1/1         121         S                    e0c
node2                 Eth1/2         121         S                    e0c
SHFGD1947000186       Eth1/10        120         S                    e0a         
SHFGD1947000186       Eth1/11        120         S                    e0a         
SHFGB2017000269       Eth1/12        120         S                    e0a         
SHFGB2017000269       Eth1/13        120         S                    e0a

S2# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability          Port ID
node1                 Eth1/1         121         S                   e5b
node2                 Eth1/2         121         S                   e5b
SHFGD1947000186       Eth1/10        120         S                   e0b         
SHFGD1947000186       Eth1/11        120         S                   e0b         
SHFGB2017000269       Eth1/12        120         S                   e0b         
SHFGB2017000269       Eth1/13        120         S                   e0b
----
====
. スイッチ sw2 で、ディスク シェルフのストレージ ポートとノードに接続されているポートをシャットダウンします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net add interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. NVIDIA SN2100 でサポートされている適切なケーブルを使用して、コントローラとディスク シェルフのノード ストレージ ポートを古いスイッチ S2 から新しいスイッチ sw2 に移動します。
. スイッチ sw2 で、ノードとディスク シェルフのストレージ ポートに接続されているポートを起動します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. ノードの観点から、各ノードのストレージ ポートが次のようにスイッチに接続されていることを確認します。
+
`network device-discovery show -protocol lldp`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface      Platform
----------- ------ ------------------------- -------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1           -

node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp2           -
----
====
. ネットワーク ポートの属性を確認します。
+
`storage port show`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. スイッチ sw2 で、すべてのノード ストレージ ポートが稼働していることを確認します。
+
`net show interface`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. スイッチ sw1 で、ノードおよびディスク シェルフのストレージ ポートに接続されているポートをシャットダウンします。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. NVIDIA SN2100 でサポートされている適切なケーブルを使用して、コントローラのノード ストレージ ポートとディスク シェルフを古いスイッチ S1 から新しいスイッチ sw1 に移動します。
. スイッチ sw1 で、ノードとディスク シェルフのストレージ ポートに接続されたポートを起動します。
+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. ノードの観点から、各ノードのストレージ ポートが次のようにスイッチに接続されていることを確認します。
+
`network device-discovery show -protocol lldp`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    sw1 (b8:ce:f6:19:1b:96)   swp1            -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1            -

node2      /lldp
            e0c    sw1  (b8:ce:f6:19:1b:96)  swp2            -
            e5b    sw2  (b8:ce:f6:19:1a:7e)  swp2            -
----
====




=== ステップ3: 構成を確認する

. 最終的な構成を確認します。
+
`storage port show`

+
各ポートは有効になっている必要があります `State`および有効 `Status`。

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. スイッチ sw2 で、すべてのノード ストレージ ポートが稼働していることを確認します。
+
`net show interface`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. 両方のノードが各スイッチにそれぞれ 1 つの接続を持っていることを確認します。
+
`net show lldp`

+
.例を表示
[%collapsible]
====
次の例は、両方のスイッチの適切な結果を示しています。

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e0c
swp2       100G   Trunk/L2  node2                  e0c
swp3       100G   Trunk/L2  SHFFG1826000112        e0a
swp4       100G   Trunk/L2  SHFFG1826000112        e0a
swp5       100G   Trunk/L2  SHFFG1826000102        e0a
swp6       100G   Trunk/L2  SHFFG1826000102        e0a

cumulus@sw2:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e5b
swp2       100G   Trunk/L2  node2                  e5b
swp3       100G   Trunk/L2  SHFFG1826000112        e0b
swp4       100G   Trunk/L2  SHFFG1826000112        e0b
swp5       100G   Trunk/L2  SHFFG1826000102        e0b
swp6       100G   Trunk/L2  SHFFG1826000102        e0b
----
====


. 権限レベルを管理者に戻します。
+
`set -privilege admin`

. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.次の手順
link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを構成する"] 。
