---
permalink: switch-nvidia-sn2100-storage/replace-sn2100-switch-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia sn2100 cluster switch - nvidia SN2100 
summary: '故障したNVIDIA SN2100 ストレージ スイッチを非中断手順 (NDU) で交換します。' 
---
= NVIDIA SN2100ストレージスイッチを交換する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
故障したNVIDIA SN2100 ストレージ スイッチを交換できます。この手順は無停止で実行されます。

.開始する前に
NVIDIA SN2100 ストレージ スイッチに Cumulus ソフトウェアと RCF をインストールする前に、次の点を確認してください。

* システムはNVIDIA SN2100 ストレージ スイッチをサポートできます。
* 該当する RCF をダウンロードしました。


その http://hwu.netapp.com["Hardware Universe"^]サポートされているポートとその構成の完全な詳細を提供します。

既存のネットワーク構成には、次の特性が必要です。

* すべてのトラブルシューティング手順を完了して、スイッチを交換する必要があることを確認します。
* 両方のスイッチに管理接続が存在することを確認します。
+

NOTE: すべてのトラブルシューティング手順が完了していることを確認して、スイッチを交換する必要があるかどうかを確認してください。



交換用NVIDIA SN2100 スイッチには、次の特性が必要です。

* 管理ネットワーク接続は機能しています。
* コンソールを使用して交換用スイッチにアクセスできます。
* 適切な RCF および Cumulus オペレーティング システム イメージがスイッチにロードされます。
* スイッチの初期カスタマイズが完了しました。


.手順の概要
この手順では、2 番目のNVIDIA SN2100 ストレージ スイッチ sw2 を新しいNVIDIA SN2100 スイッチ nsw2 に置き換えます。  2 つのノードは node1 と node2 です。

完了するための手順:

* 交換するスイッチがsw2であることを確認します。
* スイッチ sw2 からケーブルを外します。
* ケーブルをスイッチ nsw2 に再接続します。
* スイッチ nsw2 上のすべてのデバイス構成を確認します。


.手順
. このクラスタでAutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を抑制します。
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ はメンテナンス ウィンドウの期間 (時間単位) です。

. 続行するかどうかを尋ねられたら *y* と入力して、権限レベルを「advanced」に変更します。
+
`set -privilege advanced`

. ストレージ ノード ポートのヘルス ステータスをチェックして、ストレージ スイッチ S1 への接続を確認します。
+
`storage port show -port-type ENET`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. ストレージ スイッチ sw1 が使用可能であることを確認します。
+
`network device-discovery show -protocol lldp`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1/lldp
            e0M    sw1 (00:ea:bd:68:6a:e8)   Eth1/46           -
            e0b    sw2 (6c:b2:ae:5f:a5:b2)   Ethernet1/16      -
            e0c    SHFFG1827000286 (d0:39:ea:1c:16:92)
                                             e0a               -
            e0e    sw3 (6c:b2:ae:5f:a5:ba)   Ethernet1/18      -
            e0f    SHFFG1827000286 (00:a0:98:fd:e4:a9)
                                             e0b               -
            e0g    sw4 (28:ac:9e:d5:4a:9c)   Ethernet1/11      -
            e0h    sw5 (6c:b2:ae:5f:a5:ca)   Ethernet1/22      -
            e1a    sw6 (00:f6:63:10:be:7c)   Ethernet1/33      -
            e1b    sw7 (00:f6:63:10:be:7d)   Ethernet1/34      -
            e2a    sw8 (b8:ce:f6:91:3d:88)   Ethernet1/35      -
Press <space> to page down, <return> for next line, or 'q' to quit...
10 entries were displayed.
----
====
. 実行 `net show interface`動作中のスイッチでコマンドを実行して、両方のノードとすべてのシェルフが表示されることを確認します。
+
`net show interface`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----

cumulus@sw1:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e3a)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e3a)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. ストレージ システムのシェルフ ポートを確認します。
+
`storage shelf port show -fields remote-device, remote-port`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   swp3          sw1
3.20    1   -             -
3.20    2   swp4          sw1
3.20    3   -             -
3.30    0   swp5          sw1
3.20    1   -             -
3.30    2   swp6          sw1
3.20    3   -             -
cluster1::*>
----
====
. ストレージ スイッチ sw2 に接続されているすべてのケーブルを取り外します。
. すべてのケーブルを交換用スイッチ nsw2 に再接続します。
. ストレージ ノード ポートのヘルス ステータスを再確認します。
+
`storage port show -port-type ENET`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. 両方のスイッチが使用可能であることを確認します。
+
`net device-discovery show -protocol lldp`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----

cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1/lldp
            e0M    sw1 (00:ea:bd:68:6a:e8)   Eth1/46           -
            e0b    sw2 (6c:b2:ae:5f:a5:b2)   Ethernet1/16      -
            e0c    SHFFG1827000286 (d0:39:ea:1c:16:92)
                                             e0a               -
            e0e    sw3 (6c:b2:ae:5f:a5:ba)   Ethernet1/18      -
            e0f    SHFFG1827000286 (00:a0:98:fd:e4:a9)
                                             e0b               -
            e0g    sw4 (28:ac:9e:d5:4a:9c)   Ethernet1/11      -
            e0h    sw5 (6c:b2:ae:5f:a5:ca)   Ethernet1/22      -
            e1a    sw6 (00:f6:63:10:be:7c)   Ethernet1/33      -
            e1b    sw7 (00:f6:63:10:be:7d)   Ethernet1/34      -
            e2a    sw8 (b8:ce:f6:91:3d:88)   Ethernet1/35      -
Press <space> to page down, <return> for next line, or 'q' to quit...
10 entries were displayed.
----
====
. ストレージ システムのシェルフ ポートを確認します。
+
`storage shelf port show -fields remote-device, remote-port`

+
.例を表示
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     swp3            sw1
3.20    1     swp3            nsw2
3.20    2     swp4            sw1
3.20    3     swp4            nsw2
3.30    0     swp5            sw1
3.20    1     swp5            nsw2
3.30    2     swp6            sw1
3.20    3     swp6            nsw2
cluster1::*>
----
====
. 権限レベルを管理者に戻します。
+
`set -privilege admin`

. 自動ケース作成を抑制した場合は、 AutoSupportメッセージを呼び出して再度有効にします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.次の手順
スイッチを交換したら、link:../switch-cshm/config-overview.html["スイッチのヘルスモニタリングを設定する"] 。
