---
permalink: switch-nvidia-sn2100/required-documentation-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: NVIDIA SN2100スイッチのインストールとメンテナンスについては、推奨されるすべてのマニュアルを確認してください。 
---
= NVIDIA SN2100スイッチのマニュアル要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIA SN2100スイッチのインストールとメンテナンスについては、推奨されるすべてのマニュアルを確認してください。

次の表に、NVIDIA SN2100スイッチで使用可能なマニュアルを示します。

[cols="1,2"]
|===
| タイトル | 説明 


 a| 
link:install_setup_sn2100_switches_overview.html["NVIDIA SN2100スイッチをセットアップして設定します_"^]
 a| 
Cumulus Linuxおよび該当するRCFのインストールなど、NVIDIA SN2100スイッチのセットアップおよび設定方法について説明します。



 a| 
link:migrate_cisco_sn2100_cluster_switch.html["_ CiscoクラスタスイッチからNVIDIA SN2100クラスタスイッチへの移行_"^]
 a| 
Ciscoクラスタスイッチを使用する環境からNVIDIA SN2100クラスタスイッチを使用する環境に移行する方法について説明します。



 a| 
link:migrate_cisco_sn2100_storage_switch.html["_ CiscoストレージスイッチからNVIDIAストレージスイッチへの移行_"^]
 a| 
Ciscoストレージスイッチを使用する環境からNVIDIA SN2100ストレージスイッチを使用する環境に移行する方法について説明します。



 a| 
link:migrate_2n_switched_sn2100_switches.html["NVIDIA SN2100クラスタスイッチを使用する2ノードスイッチクラスタへの移行_"^]
 a| 
NVIDIA SN2100クラスタスイッチを使用して2ノードスイッチ環境に移行する方法について説明します。



 a| 
link:replace_sn2100_switch_cluster.html["NVIDIA SN2100クラスタスイッチを交換してください_"^]
 a| 
クラスタ内の故障したNVIDIA SN2100スイッチを交換し、Cumulus Linuxおよびリファレンス構成ファイルをダウンロードする手順 について説明します。



 a| 
link:replace_sn2100_switch_storage.html["NVIDIA SN2100ストレージスイッチを交換してください_"^]
 a| 
欠陥のあるNVIDIA SN2100ストレージスイッチを交換し、Cumulus Linuxおよびリファレンス構成ファイルをダウンロードする手順 について説明します。

|===