---
permalink: switch-nvidia-sn2100-storage/reset-switch-sn2100-storage.html 
sidebar: sidebar 
keywords: SN2100 reset switch to factory defaults, SN2100 switches configuration, cumulus linux 
summary: NVIDIA SN2100 ストレージスイッチを工場出荷時のデフォルト設定にリセットするには、現在のスイッチ設定を消去します。 
---
= NVIDIA SN2100ストレージスイッチを工場出荷時のデフォルト設定にリセットする
:allow-uri-read: 


[role="lead"]
NVIDIA SN2100 ストレージスイッチを工場出荷時のデフォルト設定にリセットするには、現在のスイッチ構成を消去し、スイッチを元の設定に復元します。

* Cumulus Linux 5.10 以前の場合は、Cumulus イメージを適用します。
* Cumulus Linux 5.11以降では、 `nv action reset system factory-default`指示。


.タスク概要
* スイッチにシリアル コンソールを使用して接続する必要があります。
* コマンドへの sudo アクセスには root パスワードが必要です。



NOTE: Cumulus Linux のインストールに関する詳細については、link:configure-software-sn2100-storage.html["NVIDIA SN2100スイッチのソフトウェアインストールワークフロー"]を参照してください。

.手順
[role="tabbed-block"]
====
.Cumulus Linux 5.10 以前
--
. Cumulusコンソールから、次のコマンドでスイッチソフトウェアのインストールをダウンロードしてキューに追加します。 `onie-install -a -i`スイッチ ソフトウェアへのファイル パスが続きます。例:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://<web-server>/<path>/cumulus-linux-5.10.0-mlx-amd64.bin*
----
. インストーラーがダウンロードを開始します。イメージがダウンロードされ検証されたときにインストールを確認するプロンプトが表示されたら、*y* と入力します。
. 新しいソフトウェアをインストールするには、スイッチを再起動します。
+
`sudo reboot`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
+

NOTE: スイッチがリブートされ、スイッチ ソフトウェアのインストールが開始されます。この処理には時間がかかります。インストールが完了すると、スイッチは再起動し、 `log-in`プロンプト。



--
.Cumulus Linux 5.11以降
--
. スイッチを工場出荷時の状態にリセットし、すべての構成、システム ファイル、およびログ ファイルを削除するには、次のコマンドを実行します。
+
`nv action reset system factory-default`

+
例えば：

+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *nv action reset system factory-default*

This operation will reset the system configuration, delete the log files and reboot the switch.
Type [y] continue.
Type [n] to abort.
Do you want to continue? [y/n] *y*
----


詳細については、NVIDIA https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-511/Installation-Management/Factory-Reset/["工場出荷時設定へのリセット"^]のドキュメントを参照してください。

--
====
.次の手順
スイッチをリセットしたら、link:configure-overview-sn2100-storage.html["再構成する"]必要に応じて変更します。
